### ISSUE TITLE
Self Hosted Git Repo Support

### ISSUE THREAD

**Issue by SebastianM** [drone/drone#10]
Hey guys,

thank you for this great project!
It would be awesome to have support for self hosted git repositories. Then drone would be the perfect solution for a enterprise project I'm working on and I could get rid of Jenkins :)

Cheers
Sebastian

**Comment by bradrydzewski** [comment]
The latest version of Drone completely relies on 3rd party version control systems (ie GitHub, Bitbucket, etc) for user accounts, user login and repository permissions. This means that Drone will not support generic Git repositories.

**Comment by bradrydzewski** [comment]
I will add that all is not lost. We are planning on adding dynamic plugins (using JavaScript) that you may be able to use to hack something together. It will just take a bit of creativity to fully implement the required methods:

```
type Remote interface {
	// Authorize handles authentication with thrid party remote systems,
	// such as github or bitbucket, and returns user data.
	Authorize(w http.ResponseWriter, r *http.Request) (*model.Login, error)

	// GetRepos fetches all repositories that the specified
	// user has access to in the remote system.
	GetRepos(user *model.User) ([]*model.Repo, error)

	// GetScript fetches the build script (.drone.yml) from the remote
	// repository and returns in string format.
	GetScript(user *model.User, repo *model.Repo, hook *model.Hook) ([]byte, error)

	// Activate activates a repository by creating the post-commit hook and
	// adding the SSH deploy key, if applicable.
	Activate(user *model.User, repo *model.Repo, link string) error

	// ParseHook parses the post-commit hook from the Request body
	// and returns the required data in a standard format.
	ParseHook(r *http.Request) (*model.Hook, error)
```

**Comment by martianus** [comment]
Sad, sad day indeed.... :cry: :sob:

**Comment by ramonskie** [comment]
well there go my dream of moving away from bamboo

**Comment by cedk** [comment]
@ramonski FYI, I have written a specific extension to use drone with our self-hosted mercurial repositories:
https://github.com/cedk/drone/tree/trypod
http://hg.tryton.org/trypod
It should not be too difficult to adapt it for other custom usage.

**Comment by bradrydzewski** [comment]
> well there go my dream of moving away from bamboo

I think someone could easily create a deamon that implements the minimum required REST endpoints (login, get repository, upload ssh key) to hook into Drone. This daemon could sit on your Git server, or it could probably even sit on your Drone server and use ssh to communicate with your Git server.

So your dream isn't dead :)

It will just require an extra module, which won't be included in the core Drone codebase.

If nobody wants to create this daemon, I will do it. I just have a pretty long backlog at the moment so it would take a few months. If someone wants to tackle this now I'm happy to offer my assistance.

**Comment by martianus** [comment]
@bradrydzewski @cedk - I've made a fork of the Drone project in which I'm starting a plugin for Stash. I'll definitely be taking up your offers for help. I'll see how far I get in the next few days before I call for help though. I'm using the BitBucket plugin and the Trypod plugins as a base reference for now.

**Comment by philipgiuliani** [comment]
Really cool that you are trying it! Thanks and good luck! :)

**Comment by ChiperSoft** [comment]
Have there been any developments since this issue was closed? I'm interested in using drone for our deployments where I work, but all our repos are self-hosted.

**Comment by bradrydzewski** [comment]
@ChiperSoft the upcoming 0.4 release of Drone will feature a plugin model for hooking up custom remote systems. One just needs to satisfy the following interface:
https://github.com/drone/drone/blob/0.4.0/pkg/remote/remote.go#L9

Self-hosted raw git repositories won't be officially supported, however, I'm confident they can be added through an external plugin once 0.4 is ready.

**Comment by spacemeowx2** [comment]
https://github.com/drone/drone/issues/10#issuecomment-108590120

Now it's 0.8 and I can't find how to make a external plugin to support my custom remote.

**Comment by mavimo** [comment]
@spacemeowx2 ypu should implement the `Remote` interface described in https://github.com/drone/drone/blob/master/remote/remote.go (see other implementation in the same folder).

**Comment by spacemeowx2** [comment]
@mavimo So after I writing it how can I plugin it into drone without compile again?

**Comment by tboerger** [comment]
Currently it's not possible without recompilation, but maybe there will follow some API comparable to secrets and registry.

**Comment by spacemeowx2** [comment]
Got it, thank you.
