### ISSUE TITLE
Unable to use set-key

### ISSUE THREAD

**Issue by rfink** [drone/drone#1001]
I am unable to use set-key with the command line tool with a local gitlab installation.  For the repo name, I've tried:

drone set-key {gitlab-ip}:{gitlab-port}/{group-name}/{project} ~/.ssh/id_rsa
drone set-key {gitlab-ip}:{gitlab-port}/{group-name}/{project}.git ~/.ssh/id_rsa
drone set-key {gitlab-ip}:{gitlab-port}/{project} ~/.ssh/id_rsa

drone set-key {gitlab-ip}/{group-name}/{project} ~/.ssh/id_rsa
drone set-key {gitlab-ip}/{group-name}/{project}.git ~/.ssh/id_rsa
drone set-key {gitlab-ip}/{project} ~/.ssh/id_rsa

drone set-key {gitlab-address}/{group-name}/{project} ~/.ssh/id_rsa
drone set-key {gitlab-address}/{group-name}/{project}.git ~/.ssh/id_rsa
drone set-key {gitlab-address}/{project} ~/.ssh/id_rsa

drone set-key {gitlab-address}:{gitlab-port}/{group-name}/{project} ~/.ssh/id_rsa
drone set-key {gitlab-address}:{gitlab-port}/{group-name}/{project}.git ~/.ssh/id_rsa
drone set-key {gitlab-address}:{gitlab-port}/{project} ~/.ssh/id_rsa

drone set-key gitlab.com/{group-name}/{project} ~/.ssh/id_rsa
drone set-key gitlab.com/{group-name}/{project}.git ~/.ssh/id_rsa
drone set-key gitlab.com/{project} ~/.ssh/id_rsa

drone set-key 192.168.1.7:8080/glew/glew-data.git ~/.ssh/id_rsa
panic: runtime error: assignment to entry in nil map

goroutine 16 [running]:
runtime.panic(0x8d8e60, 0xe11293)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
net/textproto.MIMEHeader.Set(0x0, 0x96c1d0, 0xe, 0xc208064570, 0x4)
	/usr/local/go/src/pkg/net/textproto/header.go:22 +0xb5
net/http.Header.Set(0x0, 0x96c1d0, 0xe, 0xc208064570, 0x4)
	/usr/local/go/src/pkg/net/http/header.go:31 +0x4f
github.com/drone/drone/client.(*Client).run(0xc2080722c0, 0x948f10, 0x3, 0xc2080d2b10, 0x2e, 0x7bb640, 0xc208041320, 0x0, 0x0, 0x0, ...)
	/var/cache/drone/src/github.com/drone/drone/client/client.go:83 +0x594
github.com/drone/drone/client.(*RepoService).SetKey(0xc208042120, 0x7fffb22928af, 0x10, 0x7fffb22928c0, 0x4, 0x7fffb22928c5, 0xd, 0xc208027800, 0x68b, 0xc20802ab60, ...)
	/var/cache/drone/src/github.com/drone/drone/client/repos.go:54 +0x2a5
main.setKeyCommandFunc(0xc2080ce460, 0xc2080722c0, 0x0, 0x0)
	/var/cache/drone/src/github.com/drone/drone/cli/keys.go:47 +0x5db
main.handle(0xc2080ce460, 0xa61c10)
	/var/cache/drone/src/github.com/drone/drone/cli/handle.go:28 +0xd9
main.func·005(0xc2080ce460)
	/var/cache/drone/src/github.com/drone/drone/cli/keys.go:18 +0x31
github.com/codegangsta/cli.Command.Run(0x95e7d0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9f7fd0, 0x26, 0x0, ...)
	/var/cache/drone/src/github.com/codegangsta/cli/command.go:118 +0xec6
github.com/codegangsta/cli.(*App).Run(0xc2080d40f0, 0xc20800e000, 0x4, 0x4, 0x0, 0x0)
	/var/cache/drone/src/github.com/codegangsta/cli/app.go:177 +0xbb8
main.main()
	/var/cache/drone/src/github.com/drone/drone/cli/main.go:47 +0x407

goroutine 19 [finalizer wait]:
runtime.park(0x419b80, 0xe2a730, 0xe15989)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xe2a730, 0xe15989)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

**Comment by bradrydzewski** [comment]
this issue was fixed here:
https://github.com/drone/drone-go/pull/2

however, the command line utility was moved to a new repository. From the stacktrace it looks like you're running the old version based on path names. See the readme for downloads:
https://github.com/drone/drone-cli

or install using brew if on osx:
https://github.com/drone/homebrew-drone
