### ISSUE TITLE
Using with custom mercurial server

### ISSUE THREAD

**Issue by okv** [drone/drone#1002]
Hi there.
Is it possible to configure local drone installation to work with custom mercurial server (e.g. i can do `hg clone http://hg.example.com` to get clonen repository).

**Comment by bradrydzewski** [comment]
Sorry, Drone requires a host system such as GitHub or Bitbucket.  Drone delegates things like user login and repository permissions to these systems, therefore Drone is not architected to work with raw Git or mercurial repositories.

**Comment by smelc** [comment]
Is this still the case at the time I'm writing (July 2019) ?

**Comment by bradrydzewski** [comment]
yes
