### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by ratulmukh** [drone/drone#1003]
Looked great, and I started setting up Drone for my projects. But then I realized that only Scala 2.9 is supported! Sadly I had to pull myself out of using Drone. :( Can you please start support for Scala 2.11?

**Comment by daMupfel** [comment]
Are you using the service at drone.io? this is the github repo for the open source version of drone.

In case you are using the open source version, you can define any docker container from dockerhub you like in your .drone.yml as long as it has git installed on it.

**Comment by ratulmukh** [comment]
Ok, thanks for the pointer!
