### ISSUE TITLE
Documentation request: add installation from sources

### ISSUE THREAD

**Issue by XVilka** [drone/drone#1008]
Currently it is not clear (also Makefile default build option is something different from this) how to install
Drone from the git sources (and how to update without harming settings/database). It would awesome to add these instructions in the readme or /doc.

**Comment by robclancy** [comment]
Yes please! Tried the arch aur package but it never worked for some reason and no idea how to debug it.

**Comment by bradrydzewski** [comment]
building from source now documented in readme. dockerfile also included for building and deploying from source
