### ISSUE TITLE
Ability to customise where 'official' Drone images are pulled from

### ISSUE THREAD

**Issue by mattbostock** [drone/drone#1009]
Currently, the official Drone service and language images are built from:
https://github.com/drone/images

Then published under @bradrydzewski's personal Docker account:
https://hub.docker.com/u/bradrydzewski/
https://github.com/drone/drone/blob/f7eeeff64f887111f73db75ce6f584de1112c367/shared/build/images.go#L25

We'd like the ability to customise where the official Drone images are pulled from because we'd like to have control over the images we use for our CI builds and plan to fork the drone/images repo.

I'm aware that there are [plans](https://github.com/drone/drone/issues/483#issuecomment-56770495) to do away with the official images and also to support [custom image repositories](https://github.com/drone/drone/pull/615).

Would you be willing to accept a pull request that allowed the Docker organisation that these images are pulled from to be set using an configuration setting?

**Comment by mattbostock** [comment]
Alternatively, I'm thinking that a whitelist of allowed images as a configuration option would be another way to achieve this, and have the benefit that we'd protect the Docker host from a developer/engineer from inadvertently using a malicious Docker image from the wild.

**Comment by bradrydzewski** [comment]
closing this because we've deprecated the drone images in 0.4 to avoid such conflict with the official library images. agreed we should be able to white-list images. I have this as separate issue #1061
