### ISSUE TITLE
github URL format

### ISSUE THREAD

**Issue by mwotton** [drone/drone#1012]
Not sure why, but one of my added repos is trying to use git://github.com/meanpath/json2csv where it should be using git@github.com:meanpath/json2csv. All my other repos use it without issue. I tried running "drone delete github.com/meanpath/json2csv" so i could delete and re-add, but it tells me "Unauthorized". Any ideas?

**Comment by bradrydzewski** [comment]
can you check inside the database to see if the "repo_owner" field is empty? you might need to manually purge from the database

**Comment by bradrydzewski** [comment]
it would use `git://` if the repository was public. Is it possible this was added as a public repo first, and then switched to private?

**Comment by bradrydzewski** [comment]
btw, we have a fix coming for that particular sync issue. post-commit hooks from github will trigger Drone to refresh its local repository meta-data

**Comment by mwotton** [comment]
repo_owner field was correct. Have deleted manually and re-added and it seems to work now.
I'll reopen if it happens again.

**Comment by mwotton** [comment]
Yes, it was public first i believe.
