### ISSUE TITLE
drone.toml when running Drone Docker

### ISSUE THREAD

**Issue by ianwalter** [drone/drone#1013]
I would like to add my `drone.toml` file to the volume. I can't really specify the custom `drone.toml` location as a command option because I'm using Kitematic which defers to using the images default command or entrypoint. Can we create an environment variable to specify the location of the drone.toml or check the volume for a drone.toml by default before falling back to `/etc/drone/drone.toml`?

**Comment by bradrydzewski** [comment]
@ianwalter when running Drone inside Docker the recommended approach is to use environment variables for configuration, as opposed to the toml file. All toml file attributes can be represented as environment variables.

So the following toml:

```toml
[github]
client = "c0aaff74c060ff4a950d"
secret = "1ac1eae5ff1b490892f5546f837f306265032412"
```

can be represented as:

```sh
DRONE_GITHUB_CLIENT="c0aaff74c060ff4a950d"
DRONE_GITHUB_SECRET="1ac1eae5ff1b490892f5546f837f306265032412"
```

most should be documented, but if not, the pattern is `DRONE_{category}_{attribute}`. If you have any questions please hit us up in the gitter.im/drone/drone chat room

**Comment by ianwalter** [comment]
Got it, thanks!
