### ISSUE TITLE
Modify user permissions from /admin/users

### ISSUE THREAD

**Issue by sourcec0de** [drone/drone#1014]
I recently got the self hosted drone running and we have a few administrative members on our team.
I can't seem to find any way in the UI to modify user permissions. I ended up having to manually change the `user_admin` attribute in the db to allow them to see the settings button. The page itself wasn't restricted to only admins, though less data was shown without the admin flag.

![image](https://cloud.githubusercontent.com/assets/1580651/7618391/aea7afe0-f966-11e4-9faa-6b0528a71716.png)

I think it would be useful to allow user permissions to be modified on the `/admin/users/:scope/:user` page.

![image](https://cloud.githubusercontent.com/assets/1580651/7618473/36590a7e-f967-11e4-8cc8-06ce803f425c.png)

**Comment by 2ndalpha** [comment]
+1

**Comment by benschumacher** [comment]
This functionality already exists in 0.4.0.
