### ISSUE TITLE
put /api/repos/:repo params yaml format.

### ISSUE THREAD

**Issue by npateriya** [drone/drone#1022]
Content of params (private variable) during update is expected yaml string format .  It would be easier if params KVP can be accepted in json format.

Below returns : 500 Internal Server Error
```
curl -v -X PUT "http://droneio.xyz.com/api/repos/github.com/npateriya/godemo?access_token=XYZ" -d `{“params”: { “hello”: “world” } }`
```

Yaml param for single variable works but not sure how to embed multiple KVP yaml in json. 
```
curl -v -X PUT "http://droneio.xyz.com/api/repos/github.com/npateriya/godemo?access_token=XYZ" -d `{“params”: “hello: world” }`
```

**Comment by bradrydzewski** [comment]
in the 0.4 branch this is now represented as structured data (`map[string]string` in Go) and can be updated as structured JSON via the API. See http://readme.drone.io/docs/api/#updates-a-repo
