### ISSUE TITLE
git deploy: error pushing to new remote

### ISSUE THREAD

**Issue by afterthought** [drone/drone#1026]
If our remote is new we either get "error: unable to push to unqualified destination: master" same as #760 or if we specify the branch to be specific as the resolution to #760 states we see this in the logs which causes the server to respond with a [remote rejected] "missing necessary objects".  Anyone else have this issue yet? When I duplicate the git commands from my workstation everything works fine. Maybe it's the version of git on the drone host?

    $ git remote add deploy ssh://git@deis.example.com:2222/membership-api-stage.git
    $ git push deploy $COMMIT:refs/remotes/deploy/master
    Warning: Permanently added '[deis.example.com]:2222,[x.x.x.x]:2222' (ECDSA) to the list of known hosts.
    error: Could not read 427dc98d972183325a7adeb3e3e3885b0891dcdc
    fatal: Failed to traverse parents of commit 49614b64909d429762e81bb821ad1f6b95497ac8
    error: Could not read 427dc98d972183325a7adeb3e3e3885b0891dcdc
    fatal: Failed to traverse parents of commit 49614b64909d429762e81bb821ad1f6b95497ac8

**Comment by bradrydzewski** [comment]
this functionality was pushed to plugins and is handled quite differently now. I am not aware of any issues with the new plugins, but if this persists we can re-open
https://github.com/drone-plugins/drone-git-push
https://github.com/drone-plugins/drone-deis
