### ISSUE TITLE
No files copied to image during drone-cli "local build" under Windows

### ISSUE THREAD

**Issue by tyrken** [drone/drone#1027]
I liked the feature of using "drone build <dir-to-repo>" to perform a local build of my git repo before pushing to the standard CI server.  Unfortunately the Windows build from http://downloads.drone.io/drone-cli/drone_windows_amd64.tar.gz doesn't work in this manner - the expected directory only had an oddly named "varcachedronesrc<dir-base>" directory in it.

After some hacking I've managed to fix this by:

1) Forcing windows file separators back to unix-style ones where intended for use inside the created docker container/Dockerfile.  (filepath.join was converting to windows style in https://github.com/drone/drone/blob/master/cli/build.go#L164 and https://github.com/drone/drone/blob/master/shared/build/build.go#L440).  Used `strings.Replace(str, "\\", "/", -1)` for lack of a better idea.

2) Switching from the tar-up-and-POST to build an image in ImageService.build (https://github.com/drone/drone/blob/master/shared/build/docker/image.go#L98) to `os.exec` out to a docker 1.6.0 binary.  I don't know what part of the archive is failing but couldn't update to a newer docker repo than 1.5.0 in the `make docker` command without running into https://github.com/docker/docker/issues/10922..

Do you want a PR for this, as the full fix is a bit hacky with the shell out, and I suspect your 0.4.0 branch is quite well on already?

**Comment by bradrydzewski** [comment]
I believe this is fixed in the 0.4 release. The cli was moved to https://github.com/drone/drone-cli. We can re-open if necessary

**Comment by johnrengelman** [comment]
@bradrydzewski it appears that Issues aren't activated on the `drone-cli` repo? do you want bugs filed in this repo?

**Comment by stankovski** [comment]
@bradrydzewski please enable issues in `drone-cli` repo

**Comment by tboerger** [comment]
> @bradrydzewski please enable issues in drone-cli repo

For questions use Gitter or Discuss, if you really find bugs report them to drone/drone.

**Comment by bradrydzewski** [comment]
> @bradrydzewski it appears that Issues aren't activated on the drone-cli repo? do you want bugs filed in this repo?

@johnrengelman @stankovski  for now you can file bugs here. As drone spreads across a large number of repos (especially with plugins) it has become difficult managing all the open issues and I've been contemplating a central issue tracker for all drone repos
