### ISSUE TITLE
enabled status badge per branch

### ISSUE THREAD

**Issue by ssbarnea** [drone/drone#1029]
It seems that drone.io is missing the ability to display build status per branch or even to see the status on a specific branch. Other similar systems do support this by adding the `?branch=name` parameter to the URLs.

Expected
```
/owner/project/status.png
/owner/project/status.png?branch=master
/owner/project/latest
/owner/project/latest?branch=master
```
This is essential in order to be able to distinguish between branches that are broken and those that are working.

**Comment by bradrydzewski** [comment]
@ssbarnea the badge endpoints do accept branch as a query parameter here:
https://github.com/drone/drone/blob/master/server/handler/badge.go#L57

Please note that this repository and issue tracker are for the open source Drone continuous integration server, which is different than drone.io the Saas company
