### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by cadavre** [drone/drone#1038]
Missing docs on:

1) Info about first logged-in user becomes administrator.
2) Lack of info about docker.io configuration (or even pointing it out...)
3) No info about drone.io paths
4) Is there any logging for drone.io actually?

**Comment by bradrydzewski** [comment]
feel free to send a pull request:
https://github.com/drone/docs

**Comment by bradrydzewski** [comment]
marking closed as of 0.4 (for upcoming release). New docs:
http://readme.drone.io/docs/setup/
http://readme.drone.io/docs/build/
http://readme.drone.io/docs/plugin/
http://readme.drone.io/docs/api/
