### ISSUE TITLE
OAuth does not send DefaultScope variable

### ISSUE THREAD

**Issue by philwinder** [drone/drone#1039]
The DefaultScope variable in the github.go file is never sent via OAuth to github. When a user authorizes for the first time it does not send the user:email scope and the login process will fail.

To Recreate:
Log into github, go to settings-Applications and revoke any old Drone applications.
Start drone and try to log in. You will get a user email not found error, because Drone doesn't have permission to access emails.

Workaround:
Add a "scope" variable to your config.toml file. For example:
[auth]
client = "CLIENTID"
secret = "SECRET"
authorize = "https://github.com/login/oauth/authorize"
access_token = "https://github.com/login/oauth/access_token"
request_token = ""
scope= ["repo","repo:status","user:email"]

Thanks,
Phil Winder

**Comment by bradrydzewski** [comment]
is this in the 0.4 branch?

**Comment by philwinder** [comment]
Correct, 0.4.0 branch.

**Comment by djamelfel** [comment]
@philwinder: Thanks you for this workaround

**Comment by bradrydzewski** [comment]
fixed to use default value
