### ISSUE TITLE
Use DSN strings for configuration

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1060]
> **TL;DR** configuration needs more flexibility to support plugins without being overly abstracted. The existing 0.4 implementation is overly abstracted, inflexible, and is increasingly difficult to map to environment variables.

With the 0.4 release we are introducing a plugin model that allows certain pieces of Drone to be completely replaced, for example, the database layer, the queue layer, etc. This requires an added level of flexibility in terms of configuration that is difficult to achieve with the current `drone.toml`

**Issue: Static Typing**

This is due primarily to the nature of Go and static typing. We decode the toml into a structure that has a pre-defined hierarchy and set of fields. It is highly likely that a plugin will need configuration parameters that are not defined in the toml.

**Issue: Toml vs Env**

A more complex `drone.toml` file is increasingly difficult to represent the configuration in Toml and Environment variables. Environment variable are the recommended method to define configuration (per 12-factor apps) and has become the emerging standard in the Docker community.

Ideally we could implement a single approach and move on. We have bigger and more important things to focus on.

**Looking Forward: Systemd**

Systemd is now the standard init system on almost all Linux distributions, which gives us options for configuration that did not exist with upstart. Specifically, the ability to define `EnvironmentFile=`

---

**Proposal**

The proposal is to use environment variables as the sole method to configuration Drone along with DSN formatting configuration strings.

The systemd init file will look like this:

```ini
EnvironmentFile=/etc/drone/drone.conf
```

And the configuration file will look like this:

```sh
SERVER_ADDR=":80"
SERVER_CRT="/path/to/cert.crt"
SERVER_KEY="/path/to/key.key"
DATABASE="postgres://user:pass@localhost/foo"
REMOTE="github://token:secret@github.com?open=false&orgs=foo,bar"
```

**DSN format**

So how do we give different plugins (ie queue, database, etc) flexible configuration capabilities? After doing a bit of research I believe database abstractions (ie `jdbc`, `database/sql`, etc) have already solved this issue with connection strings in DSN format.

The DSN format typically looks like the following: `<driver>://<user>:<pass>@<host>?<key>=<value>`. The most important part of the configuration URL (for Drone) is the `<driver>://` section, so that Drone knows which Driver to load. The remainder of the string is simply passed along to the Driver. This means the Driver itself determines the string format, and has a good amount of flexibility.

**Remote Examples**

```
github://<client>:<secret>@github.com?open=false&orgs=foo,bar
gitlab://<client>:<secret>@foo.com?open=false&orgs=foo,bar&ssl=skip
bitbucket://<client>:<secret>@bitbucket.org
```

Or maybe someone wants to create a custom remote plugin, that runs as an RCP service:

```
tcp://<username>:<password>@localhost
```

**Database Examples**

```
sqlite:///var/lib/drone/drone.sqlite
postgres://root:@localhost/drone
```

**Queue Examples**

```
redis://localhost:5367
```

The benefit is that the URI format is defined by the plugin. This means that Drone will enable any configuration that can fit inside a URI, which has worked pretty well for databases over the years.

**Challenges**

This is probably out of scope for `0.4.0`, however, it would be interesting to make the Docker backend pluggable as well. For example, could we allow people to choose `swarm` or `mesos` as a backend?

```
docker:///var/run/docker.sock?ca=/path/to/ca&cert=/path/to/cert&key=/path/to/key
swarm://6856663cdefdec325839a4b7e1de38e8@swarm-master.cloudapp.net:4243
```

The only real challenge here that I need to think through is how to supply multiple Docker deamon endpoints. The above example only provides a single daemon URL, however, it is likely that larger installations will need to declare multiple. Suggestions welcome.

**Comment by Bugagazavr** [comment]
postgresql and mysql have a different DSN formats :/

**Comment by bradrydzewski** [comment]
> Postgresql and mysql have a different DSN formats :/

The only real format requirement is that a DSN include a `scheme`. Drone will use the `scheme` in order to load the correct plugin. The plugin is then provided the raw DSN string and is responsible for parsing it.

The `postgres://`, `mysql://` and `sqlite3://` schemes will load the default database plugin. While it is true that mysql and sqlite3 don't include the scheme in their DSN, the plugin will be able to remove the scheme prior to opening the database connection:

```Go
func Open(dsn string) (*sql.DB, error) {
	// parse the dsn
	uri, err := url.Parse(dsn)
	if err != nil {
		return nil, err
	}
	// get the driver name
	// if sqlite3 or mysql remove the driver scheme
	driverName := uri.Scheme
	if uri.Scheme != "postgres" {
		uri.Scheme = ""
	}
	// open the database connection
	conn, err := db.Open(driverName, uri.String())
	if err != nil {
		return nil, err
	}
	return conn, nil
}
```

> Currently many ubuntu servers works under LTS trusty release, systemd as default init system is coming in 16.04, ofc. you can use non-LTS version, but many maintainers supports only LTS releases.

This approach should be backward compatible, since we can source the environment variable file from the init script.

**Comment by benschumacher** [comment]
I'm +1 the DSN/URI and environment-only approach. If a user wants a more "configuration file" approach, it would be fairly easy for them to bootstrap environment and execute with a simple command line:

```shell
$ (source /etc/drone/drone.conf && drone)
```

> This is probably out of scope for 0.4.0, however, it would be interesting to make the Docker backend pluggable as well. For example, could we allow people to choose swarm or mesos as a backend?
>
> ```
> docker:///var/run/docker.sock?ca=/path/to/ca&cert=/path/to/cert&key=/path/to/key
> swarm://6856663cdefdec325839a4b7e1de38e8@swarm-master.cloudapp.net:4243
> ```
> The only real challenge here that I need to think through is how to supply multiple Docker deamon endpoints. The above example only provides a single daemon URL, however, it is likely that larger installations will need to declare multiple. Suggestions welcome.

The MongoDB folks have a [connection URI](http://docs.mongodb.org/manual/reference/connection-string/) that allows for multiple hostnames. The crux of the design is that they comma separate within the server portion of the URI, and require username, password, path, etc. to be the same for all of these.

**Comment by bradrydzewski** [comment]
@benschumacher awesome suggestion. I verified that Go's parser won't complain with comma separated hosts and multiple ports, so this approach sounds like a winner to me

```Go
uri, err := url.Parse("docker:///var/run/docker.sock,/var/run/docker.sock,/var/run/docker.sock")
fmt.Println(strings.Split(uri.Path, ","), err)

# prints:
# [/var/run/docker.sock /var/run/docker.sock /var/run/docker.sock] <nil>
```

**Comment by benschumacher** [comment]
Nice. I meant to mention I wasn't sure how the parsers would feel about it, but glad you tested first. ;)
