### ISSUE TITLE
Use build numbers in URL path

### ISSUE THREAD

**Issue by slawus** [drone/drone#1062]
Hi!
I found a bug in 0.3 version. I've tried to use branch with name "#33". Unfortunatelly, it breaks drone.io client - you can't click on test box, and it doesn't show commit message. Screenshot attached.
![zrzut ekranu 2015-06-15 o 17 53 55](https://cloud.githubusercontent.com/assets/1429660/8164240/0f712154-1388-11e5-8470-6ccc51975e33.png)

**Comment by bradrydzewski** [comment]
fixed in 0.4 branch. using build number in URL instead of branch + sha

**Comment by slawus** [comment]
Great to hear :)!
