### ISSUE TITLE
Update data model to support matrix builds, build numbers

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1066]
This is a design document to finalize the data model in `0.4`. Having a solid data model is extremely important with the introduction of plugins, which require data stability. When plugins are introduced, structural changes the data model will be difficult and infrequent, since it could impact hundreds of plugin repositories.

Each data structure below will map directly to a database table. Some data structures have nested objects (one-to-one relationships, such as Build.Commit.Author) which we can also include in the same table (no need for joins). Nested data does not include one-to-many data structures, which are instead broken out into separate structs and tables. The map data structures, however, will be serialized as JSON and stored in a single column.

Hoping to finalize this over the weekend. **Please note** that the below code is pseudo-code. The final implementation will not use embedded anonymous structures.

**User**

Represents the user object

```Go
type User struct {
	ID     int64
	Login  string
	Token  string // access token
	Secret string // refresh token (optional)
	Email  string
	Avatar string
	Active bool
	Admin  bool
}
```

**Repos**

Represents a repository

```Go
type Repo struct {
	ID       int64
	UserID   int64 // foreign key. associate the repo with creator's github access token
	Owner    string
	Name     string
	FullName string
	Link     string // link to repo in remote system (ie github.com/drone/drone)
	Remote   string // clone url
	Branch   string // default branch
	Private  bool
	Trusted  bool
	Timeout  int64

	Keys struct {
		Public  string
		Private string
	}
	Hooks struct {
		PullRequest bool // enable or disable pull request hooks
		Push        bool // enable or disable push hooks
		Tags        bool
	}

	Params map[string]string // private params not stored in yaml
}
```

**Builds**

Represents a build. Includes commit data and optional pull request data. The optional pull request data includes the base of the working branch, to which the pull request is being merged. This is important for testing pull requests in non-github systems

```Go
type Build struct {
	ID       int64
	RepoID   int64
	Number   int
	Status   string
	Started  int64
	Finished int64

	// Head commit. This would be used to clone pushes
	Commit struct {
		Sha       string
		Ref       string
		Branch    string
		Message   string
		Timestamp string
		Remote    string
		Author struct {
			Login string
			Email string
		}
	}

	// optional, nil if not pull request
	PullRequest struct {
		Title       string
		Number       int

		// Base commit (ie target of pull request). We would clone the Base commit
		// first, then merge the Head commit, and then run our tests. This would be
		// used with Bitbucket and GitLab, since they don't provide a ref for pull requests
		Base struct {
			Sha       string
			Ref       string
			Branch    string
			Message   string
			Timestamp string
			Remote    string
			Author struct {
				Login string
				Email string
			}
		}
	}
}
```

**Jobs (Sub-build)**

Every build has at least 1 job. A matrix build will have multiple jobs.

```Go
type Job struct {
	ID       int64
	BuildID  int64
	Number   int
	Status   string
	ExitCode int
	Started  int64
	Finished int64

	Environment map[string]string # matrix parameters
}
```

**Comment by tboerger** [comment]
Sounds already pretty solid.

**Comment by bradrydzewski** [comment]
@tboerger thanks, do you think will support full gogs / gitea integration, specifically the ability to test pull requests? The reason I ask is that the current version of Drone relies on a ref (ie `refs/pull/9852/merge`) to fetch the pull request.

GitLab and Bitbucket, however, don't support fetching a pull request via ref. Instead, we need to fetch both versions from the source and target repositories and merge manually. The current version of Drone doesn't track the source of the pull request (clone url, branch, sha) which makes this impossible.

The above design tries to fix this issue

@Bugagazavr could you weigh-in from a GitLab perspective?

**Comment by tboerger** [comment]
Pull requests are currently getting implemented in gitea. So we are a little bit free how to handle that yet. Forget gogs, the maintainer has no interest in maintaining it anymore, because of that we started the fork.

**Comment by bradrydzewski** [comment]
@tboerger got it, thanks. Hopefully we'll be able to support both the github way (refs) and the bitbucket way (clone source). My totally selfish, biased and unsolicited vote would be for refs :)

**Comment by dhrp** [comment]
perhaps you'd like add a timestamp for each status, or 'step' of your build.

**Comment by benschumacher** [comment]
This seems well thought out. I did wonder, and I saw it mentioned in #597, if the PR builds will work if the source repository requires a different key. I suppose that's out of scope for the data model, however...

**Comment by bradrydzewski** [comment]
@benschumacher GitHub and GitLab enable cloning repositories via https using the OAuth token as the password. So for GitHub and GitLab we can support cloning multiple repositories, both for pull requests and for things like git submodules. I'm confident we'll get something working with Gogs / Gitea as well, since they are actively working on pull request support, and we have the ability to provide implementation feedback early in their process.

Bitbucket .... I'm going to keep my thoughts on Bitbucket to myself. Unfortunately they will have a subpar experience when using Drone compared to other SCM solutions.

**Comment by bradrydzewski** [comment]
@benschumacher also, thanks for taking a look. Pending feedback from @Bugagazavr , but I think we may be good to go with the above structure

**Comment by Bugagazavr** [comment]
@bradrydzewski im not surethat gitlab supports fetch repository via oauth access token ( maybe standard private token ), im need test this

**Comment by bradrydzewski** [comment]
RAML document defining API:
https://github.com/drone/drone/blob/0.4-database/doc/api.raml

Swagger document defining data structure:
https://github.com/drone/drone/blob/0.4-database/doc/swagger.yml#L200

Still trying to decide which format I prefer, however, the important thing is that we have documentation and are working toward a specification that won't change or break every major release.

**Comment by Bugagazavr** [comment]
@bradrydzewski my experiments with cloning repo via https with token has no success, looks like for drone it's possible ssh only

**Comment by bradrydzewski** [comment]
no problem, SSH still works, but the experience will be a bit better with tokens. Tokens are able to clone multiple repositories, which works well for submodules and for getting dependencies via git (`go get`, `npm`, etc)

**Comment by bradrydzewski** [comment]
first draft of the 0.4 API:
http://readme.drone.io/docs/api

generated from the swagger spec:
https://github.com/drone/drone/blob/0.4-database/doc/swagger.yml

**Comment by letusfly85** [comment]
Is this request over??? :sad:

I want to add ssh options below.

* port number, I want to use GitLab on Docker with not 22 port but other port such as 20022
* url for ssh protocol, I want to launch another server against GitLab server, which provide only ssh protocol to operate git command.

Is it reasonable?
