### ISSUE TITLE
Failure to create build container with Drone 0.3.0 on Docker 1.7

### ISSUE THREAD

**Issue by gthiruva** [drone/drone#1068]
Docker 1.7 came out. Something about that broke Drone's ability to publish built images to Docker Hub after a successful build. So, I figured I'll just upgrade to 1.7 on my build machine to see if that fixes the problem with pushing to Docker Hub.

But now, builds don't even start. I just get this error:

```
Error: Failed to create build container. Internal Server Error
```

which seems to come from this line:

https://github.com/drone/drone/blob/90de72aacc9502d1fe454c00f9e7d18124b1705a/shared/build/build.go#L394

Any thoughts?

**Comment by bradrydzewski** [comment]
you might be able to get some more detail by running `docker events` and monitoring its output. I haven't tested with 1.7 yet, but I'll see if I can spin up and instance and do some digging as well

**Comment by eagletmt** [comment]
Same here.
https://gist.github.com/eagletmt/45bd400150ff076dcab7

**Comment by eagletmt** [comment]
drone sends the same request to `POST /v1.9/containers/create`, but Docker 1.7.0 returns 500 saying `json: cannot unmarshal string into Go value of type []string.` .
https://gist.github.com/eagletmt/29f9b948a66153fc42b0

**Comment by gthiruva** [comment]
Looks like @eagletmt beat me to it, but I get the same 500 in response to the `POST /v1.9/containers/create`. I wasn't able to see anything that seemed meaningful in `docker events` output. `docker.log` is what seems to show the most detail.

I'm not sure if @eagletmt's commit was trying to fix the problem. I re-built from his clone, but got the same error (see gist: https://gist.github.com/gthiruva/59cc0234da4ab7246f41). Unfortunately, `docker.log` doesn't show what the body of the POST was.

**Comment by bradrydzewski** [comment]
Docker recently added code to the daemon that fails if the client and daemon have certain version mismatches. This is the error we are seeing in your logs (thanks for posting, by the way):

>  client and server don't have the same version (client: 0.8.0, server: 1.7.0) 

The client (Drone) passes the version number to Docker via an HTTP header variable. We can probably just increment this number to `"1.12"`, which seems to be the minimum for the current Docker release.

@gthiruva would you mind incrementing, re-building and testing locally with this change:
https://github.com/drone/drone/blob/master/shared/build/docker/client.go#L29

```diff
const (
	APIVERSION        = 1.9
	DEFAULTHTTPPORT   = 2375
	DEFAULTUNIXSOCKET = "/var/run/docker.sock"
	DEFAULTPROTOCOL   = "unix"
	DEFAULTTAG        = "latest"
+	VERSION           = "1.12"
-	VERSION           = "0.8.0"
)
```

If that works I can quickly incorporate both changes. Thanks for the help

**Comment by bradrydzewski** [comment]
ok, scratch prior comments. I still see the `[]string` error in the log. There may be other values that need to be converted from `[]string` to `string`. I'll take a look

**Comment by gthiruva** [comment]
@bradrydzewski Sounds good. Let me know if there's anything else I can do to help.

**Comment by gthiruva** [comment]
@bradrydzewski Actually, I think @eagletmt's fix works. I think I had tinkered a little too much with the docker host's configuration before trying out his fix. Tinkered with it some more and it's working with the new code.

I did bump the client API version string as well. But even without that change, things still work with the old version number - which is kind of surprising.

**Comment by adamlc** [comment]
@eagletmt's fix works perfectly for me :)

**Comment by lukebyrne** [comment]
Hi all, I am seeing the same issue, one on a brand new install, the other on a server that has been running for a while, which I did a package upgrade on.

Both are now at `Docker version 1.7.0, build 0baf609` and are throwing the same `Internal Server Error` message.

Is there any `best` fix?

**Comment by rdeutz** [comment]
Any change to get a 0.3.1 out of the door, I started playing around with drone (less knowledge about go) and don't think I am able to build the package on my own. If not I will wait :-)

**Comment by bradrydzewski** [comment]
just merged #1069, a new debian file will be published automatically when the build completes

**Comment by lukebyrne** [comment]
Legend @bradrydzewski, thanks so much for all your work on Drone, its such a great tool!

**Comment by rdeutz** [comment]
Updated drone and it works now, thanks all involved.

**Comment by lukebyrne** [comment]
Hi guys, I am obviously missing something, where can I download the latest packed from?

I grabbed the one from `wget downloads.drone.io/latest/drone.deb` thinking that would be the updated one and installed, my server is telling me that I have `drone version 0.3.0-alpha` installed, but I am guessing that I want `0.3.1`

**Comment by rdeutz** [comment]
I did what is documented here: http://readme.drone.io/setup/install/ubuntu/

**Comment by lukebyrne** [comment]
I did that also, but it seems to be download the 0.0.3-alpha

```
Selecting previously unselected package drone.
(Reading database ... 87959 files and directories currently installed.)
Preparing to unpack drone.deb ...
Unpacking drone (0.3.0-alpha-1435773119) ...
Setting up drone (0.3.0-alpha-1435773119) ...
Your system ubuntu 14: using upstart to control Drone
drone start/running, process 15047
```

**Comment by lukebyrne** [comment]
And that worked.

**Comment by rdeutz** [comment]
@lukebyrne for me it worked, didn't looked at the version while installing but drone -v says: 
drone version 0.3.0-alpha
