### ISSUE TITLE
Add / Remove Docker Workers without stopping / re-starting

### ISSUE THREAD

**Issue by teodor-pripoae** [drone/drone#1082]
Hi,

Right now if I want to tweak conccurency (add/remove worker nodes), I need to do a full restart, stopping all running build.

I would be nice if I could just send a `SIGHUP` to drone process and it will reload config without stopping drone.

**Comment by bradrydzewski** [comment]
I definitely see the value in such a change, but I think we'll need a slightly different implementation. There are a lot of people running Drone inside a Docker container and using environment variables for configuration, in which case SIGHUP wouldn't help.

In fact, when running Drone in Docker, you need to delete and re-add the container just to change the environment variables.

I think an interesting approach that would work with Docker (and non-Docker installs) would be to explore Docker Swarm. This would allow us to add / remove nodes on the fly, with the added benefit of being able to use Docker Machine. It should require very minimal changes to Drone.

Unfortunately I haven't had a chance to play around with Swarm yet.

**Comment by bscott** [comment]
I'm willing to take a stab at it with Swarm

**Comment by bradrydzewski** [comment]
this feature is added now in the 0.4 brach. Workers are managed via the UI
