### ISSUE TITLE
build limit size to be configurable

### ISSUE THREAD

**Issue by epcim** [drone/drone#1087]
Hi, please make the build buffer size configurable (env. variable etc). 
https://github.com/drone/drone/blob/master/shared/build/writer.go#L17

Sure, it's pointless to have such big outputs for CI, however if it happen (due debug enabled etc) than  rather be able to keep them. Alternative approach would be to allow keep the size of buffer, but use it as a pipe, so if overloaded, than the first entries will be dropped. As you probably are more interested how the build ends.

**Comment by mhagen-vmware** [comment]
I believe we are hitting this now, we just enabled a number of new unit tests and now the output in drone is truncating.  It appears to just die mid-sentence but continues on to report pass or failure eventually anyways.

**Comment by bradrydzewski** [comment]
@mhagen-vmware yes this is correct. The build will continue to run and report the status correctly, but the log buffer will discard lines once the limit is reached. The 0.5 version of drone makes this configurable. See DRONE_MAX_LOGS at http://readme.drone.io/0.5/installation/agents/

once 0.5 is released this will be closed

**Comment by bradrydzewski** [comment]
this can now be configured by setting the `DRONE_MAX_LOGS` environment variables, in megabytes, when you setup your build agent. example `DRONE_MAX_LOGS=5` for 5mb log limit. Note, drone 0.5 only
