### ISSUE TITLE
access to generated keys?

### ISSUE THREAD

**Issue by mwotton** [drone/drone#1088]
It's possible I'm going about this the wrong way, but anyway:

I have a package on github that relies on being able to pull other private packages on github. This is orchestrated by the Halcyon tool, so it's difficult to tell drone up-front which repositories it should add a key to github for.

If I can find where drone keeps its deploy keys, i can manually set it up, but I'd be interested to know what the preferred model for this use-case is.

**Comment by bradrydzewski** [comment]
you can go to the repository settings screen (in drone) to get the repository deploy key. If you repository requires access to multiple private repositories, in the current stable release, you need to delete the deploy key from github and then re-add at the user account level.

in the next release we are able to use a netrc + your github auth token to clone repositories, eliminating the need for deploy keys. Unfortunately it isn't available in the current stable version, but that sounds like what you'll want.

tracking the netrc feature in #61
