### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by olalonde** [drone/drone#1104]
Is there a canonical source for Drone's documentation? The README links to http://readme.drone.io/usage/overview/ (which in turn links to http://drone.readthedocs.org/en/latest/ which is dead) and https://github.com/drone/drone/blob/v0.2.1/README.md#builds which seems outdated. 

My googling also turned up http://docs.drone.io/ which doesn't seem up to date or is for an unreleased version of Drone. For example, I can't find this screen anywhere in my own installation: 

![build script](http://docs.drone.io/img/build-script.png)

So... where should I go to find Drone documentation?

Am I correct in thinking that Drone (the open source project) has been abandoned in favour of http://drone.io (the commercial hosted service)? Or is Drone open source development going to continue? I'm not complaining, just a bit puzzled.

**Comment by bradrydzewski** [comment]
readme.drone.io is the closest we have for the 0.3-alpha release, however, the state of documentation is poor and something that is being addressed in the 0.4-beta release.

I recommend using the forum if you have questions about how something works gitter.im/drone/drone
