### ISSUE TITLE
go deployment to heroku: Godeps are required. For instructions

### ISSUE THREAD

**Issue by nickolaich** [drone/drone#1107]
**I have bootstrapped simple rest api.
with drone.io everything is fine except deployment to Heroku.**
After running all tests I have:
remote: -----> Go app detected        
remote:  !     Godeps are required. For instructions:        
remote:  !     https://devcenter.heroku.com/articles/go-support        
remote: 
remote:  !     Push rejected, failed to compile Go app        
remote: 
remote: Verifying deploy.... 

**When I am running it locally (git push heroku master) it works:**
remote: -----> Go app detected
remote: -----> Checking Godeps/Godeps.json file.
remote: -----> Using go1.4.2
remote: -----> Running: godep go install -tags heroku ./...
remote: -----> Discovering process types
remote:        Procfile declares types -> web

Godeps folder exists and contains all generated dependencies.  Godeps is part of my repository code. I had thoughts that it's wrong and tried to remove it and generete deps on a fly (godep save -r), but it didn't help
Any ideas or suggesions how to solve it or where to check?
Thanks in advance

**Comment by bradrydzewski** [comment]
hi there, this repository is for the open source [drone/drone](https://github.com/drone/drone) codebase and is un-related to the drone.io service. Therefore this issue tracker is reserved solely for problems with the open source codebase
