### ISSUE TITLE
Drone set docker container MAC address

### ISSUE THREAD

**Issue by gabrielelanaro** [drone/drone#1114]
I was wandering if it is possible to have a container with the same mac address every time. I believe there is an option in docker:

```
docker run -i -t --mac-address=26:99:7c:50:d8:20 --name=my-container ubuntu bash
```

Alternatively, is it possible to change the mac address within the container?

**Comment by bradrydzewski** [comment]
Not currently, although it is possible that we could expose this configuration parameters in the `.drone.yml` file in the future. You'll need to make sure two builds don't try to secure the same mac address at the same time. This could happen if, for example, you push two changes to your repository in a short timespan and trigger overlapping builds. You would probably want to configure each build server to have build concurrency == 1

**Comment by bradrydzewski** [comment]
please send a PR to https://github.com/drone/drone-yaml-v1 if interested in this capability.
