### ISSUE TITLE
Strange behavior during compilation

### ISSUE THREAD

**Issue by NeumimTo** [drone/drone#1119]
Im getting compile error if i try to call method NashornScriptEngineFactory.getScriptEngine(String). The method really exists: http://cr.openjdk.java.net/~sundar/jdk.nashorn.api/8u40/javadoc/jdk/nashorn/api/scripting/NashornScriptEngineFactory.html

Log:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.312s
[INFO] Finished at: Mon Aug 03 18:11:07 UTC 2015
[INFO] Final Memory: 10M/85M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:compile (default-compile) on project test: Compilation failure
[ERROR] /home/ubuntu/src/bitbucket.org/NeumimTo/dronetest/src/main/java/me/test/Main.java:[11,15] error: no suitable method found for getScriptEngine(String)

Repository: https://bitbucket.org/NeumimTo/dronetest/src/d93e9cd2fb568e4feca1ed7cb4222db618788444?at=master

In drone io i have set java 8

If i run the build locally it pass (tested with oracle jdk 8, elementary os and windows 7)

**Comment by bradrydzewski** [comment]
Hi there, this issue tracker is reserved for the drone open source projects, which is not the same thing as `drone.io` website. For the open source project we reserve the issue tracker only for issues related to the drone codebase:

> #### Help with Failing Builds
> Please use StackOverflow for help with failing builds. Unless your code is written in Go we probably can’t provide much help troubleshooting failing builds.
