### ISSUE TITLE
Drone .deb package requires lsb_release to install cleanly on Debian 8

### ISSUE THREAD

**Issue by nosmo** [drone/drone#1126]
When installing Drone with the .deb package on a completely fresh Debian 8 install, the user is prompted with the following message: 

```
$ dpkg -i drone.deb
Selecting previously unselected package drone.
(Reading database ... 13553 files and directories currently installed.)
Preparing to unpack drone.deb ...
Unpacking drone (0.3.0-alpha-1438588567) ...
Setting up drone (0.3.0-alpha-1438588567) ...
/var/lib/dpkg/info/drone.postinst: 20: /var/lib/dpkg/info/drone.postinst: lsb_release: not found
/var/lib/dpkg/info/drone.postinst: 20: /var/lib/dpkg/info/drone.postinst: lsb_release: not found
/var/lib/dpkg/info/drone.postinst: 24: /var/lib/dpkg/info/drone.postinst: lsb_release: not found
 Your system
 This system is not supported, you can install service manually
```

Installing the ```lsb-release``` package and trying again features no errors, so adding to the ```Depends``` should fix this.

**Comment by bradrydzewski** [comment]
starting with 0.4 release we're distributing Drone as a Docker image only. It eliminates a lot of distro-specific issues we are seeing with regards to packaging and dependencies.

for reference, new installation instructions:
http://readme.drone.io/docs/setup/index.html
