### ISSUE TITLE
Cache bind mounts fail in case repo url contains a colon (e.g. url:port)

### ISSUE THREAD

**Issue by andreas-venturini** [drone/drone#1127]
bind mounts for cache dirs currently fail to work in case the repository url contains a colon (see https://github.com/docker/docker/issues/8604)

e.g. '10.0.0.1:10080/user/app' 

`docker inspect drone-container` gives the following output:

```
[...]

    "VolumesRW": {
        "/tmp/bundle": true,
        "10080/user/app/tmp/bundle": false
    }

[...]
```

This should probably be handled by docker itself, it would still be nice if one could override the default host path set by drone

**Comment by SerialVelocity** [comment]
I'm having the same issue that since the code is being checked out into a path with a colon, setting the classpath of java does not work.

**Comment by bradrydzewski** [comment]
@SerialVelocity until we have a fix you can override the default path to omit the color:

```
git:
  path: alternate/clone/path
```

**Comment by bradrydzewski** [comment]
as of latest release caching no longer uses mounts, so this has been resolved. New caching docs:
http://readme.drone.io/build/cache.html

**Comment by marvinthepa** [comment]
N.B.:

```
git:
  path: alternate/clone/path
```

Does not seem to work anymore, seems it has to be replaced by:

```
workspace:
  base: /go
  path: src/github.com/octocat/hello-world
```

http://readme.drone.io/questions/how-to-customize-the-workspace/

Just for people like me who need to use maven, which (still) breaks down completely when there is a colon in the path (see http://maven.40175.n5.nabble.com/Issue-if-colon-in-project-path-td3281864.html).
