### ISSUE TITLE
Build logs scroll left on Firefox

### ISSUE THREAD

**Issue by ibuildthecloud** [drone/drone#1133]
If you have a build log that has one very long line, on firefox the whole text pane slides to the left.  This means most messages that are shorter can't be seen because they are off screen.  This works fine on Chrome though.

**Comment by bradrydzewski** [comment]
any chance you could provide a gist with the inner html of the <pre> tag? also ff version? thanks!

**Comment by ibuildthecloud** [comment]
This seems to be fixed in the later version.  I don't see it anymore.  Thanks!
