### ISSUE TITLE
Support `.drone.yml` and `.drone.yaml` variant

### ISSUE THREAD

**Issue by zaro0508** [drone/drone#1140]
I made the mistake of setting up my project with '.drone.yaml' file.  I know the project setup instruction specifically say to create a '.drone.yml' file but it should really support '.drone.yaml' as well.  i mean the official website is yaml.org and I think the '.yaml' extension is more widely used.  I was only able to figure out after getting help from the Gitter drone channel, shout out to tboerger!

Error from drone log:
https://api.github.com/repos/zaro0508/play2/contents/.drone.yml?ref=9161a2ae341eed1c5fcbe54c1d037ba0ba41e102: 404 Not Found []

**Comment by donny-dont** [comment]
I'm not a fan of this idea.It means that documentation has to change quite a bit.

Also what if theres a .drone.yml and a .drone.yaml? Which does it choose?

Now I know at work on our instance we've definitely hit the problem you're trying to solve. However I think that it would be better to have a good error message appear rather than supporting variants.

**Comment by zaro0508** [comment]
This change makes '.drone.yml' the default and '.drone.yaml' the fallback.   If you have both then it will accept 'yml'.  I'm not sure the current docs need to be changed at all except for maybe mentioning that drone will look for '.drone.yaml' as a fallback.

**Comment by vtolstov** [comment]
I think the pr is good.

**Comment by donny-dont** [comment]
The code inside the pull request is fine what I am saying is that the problem can be solved in a better manner.

Drone could open up a pull request with a .drone.yml and add the badge to the README.md. Drone could just commit a .drone.yml to the repo ala Github asking you if it should init it with a README. There could be something in the UI that says hey there's no .drone.yml.

I'm not saying that what you experienced isn't a problem I'm just saying there are better solutions in terms of the user experience. Those solutions would make this issue you faced moot.
