### ISSUE TITLE
Support GitHub deployment API

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#1144]
Looks like GitHub has an API to trigger deployments, https://developer.github.com/v3/repos/deployments/. Having support for this would be great as an explicit deployment point can be supported.

Probably need to support the specific hook type to be able to access it within the config and then do actual deploys.

**Comment by bradrydzewski** [comment]
### track event type

We should probably start tracking what event triggered the build. For example, `pull_request`, `push` or `deployment`: 

```
type Build struct {
+ Event string
}
```

### update hook

We need to update the hook to correctly parse the deployment payload. We can see an example payload here: https://developer.github.com/v3/activity/events/types/#deleteevent

The data in the payload needs to be mapped to the commit.

### add step filters

We should then add the ability to filter certain steps based on the hook event type. For example, we may only want to run a heroku deployment when the hook is `deployment`:

```yaml
deploy:
  heroku:
    when:
      event: deployment
```

### add user interface indicator

it would be nice to add a little label / tag to the user interface that the build was a deployment.

### update github status code

the code that updates the github status api should be slightly altered to update the github deployment api if the `build.Event == "deployment"`

Overall this shouldn't be too difficult to implement and will be a really awesome feature.

**Comment by donny-dont** [comment]
This seems to be working so we can probably close this.

**Comment by khirakawa** [comment]
@bradrydzewski is there a way to include the deployment id as an environment variable? It would allow build scripts to update the deployment status (which would allow for things like publishing deployment status messages in Slack)

**Comment by khirakawa** [comment]
I opened a topic here https://discuss.drone.io/t/github-deployments/91

**Comment by bradrydzewski** [comment]
I think we can close this now that we have the ability to filter steps based on deployment target (below) as well as access the `CI_DEPLOY_TO` environment variable.

```
deploy:
  heroku:
    app: foo
    when:
      environment: production
```

We also recently accepted a pull request to update the deployment status automatically, so we no longer need to do so with custom scripts. Reference commit 6ddc2abf47cbf5d101106d966d90186941637de0
