### ISSUE TITLE
Cleanup, Remove `Clone` object

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1146]
We currently define a `Clone` object:
https://github.com/drone/drone-plugin-go/blob/master/plugin/types.go#L6

This is redundant since all this information can be found inside the `Build` object:
https://github.com/drone/drone-plugin-go/blob/master/plugin/types.go#L50

The only catch is that we need to figure out how to pass down the clone (workspace) directory to each plugin / step in the process. It isn't currently part of any of the objects in the plugin payload:

```
{
    "repo" : { ... },
    "build" : { ... },
    "job" : { ... }
}
```

This change impacts many of the plugins, as well as the `drone/drone-plugin-go` library, so it needs to be resolved before we cut an official release and lock down the payload structure.

**Comment by bradrydzewski** [comment]
this is an idea I have to refine the plugin input:

```js
{
	"repo": {}
	"build": {}
	"system": {
		// version of drone
		"version": "0.4-alpha.1",

		// link back to drone. useful for notification plugins to construct link to build
		"link": "https://github.com/drone/drone",

		// plugin white-list, used to filter out non-approved plugins
		"plugins": "plugins/*"

		// global variables, used as default values for plugins
		"globals": [
			"NPM_USERNAME=system",
			"NPM_PASSWORD=pa$$word"
		]
	}

	// store workspace details, including the path, in this data structure
	"workspace": {
		"root": "/drone" # ignore this, for now
		"src": "/drone/src" # ignore this, for now
		"path": "/drone/src/github.com/drone/drone"
		"netrc": {}
		"keys": {}
	}
}
```

Notice that we no longer use the `clone.path`. We use the `workspace.path` value, which can be specified in a new `workspace` section of the yaml:

```yaml
workspace: 
  path: github.com/drone/drone
```

I could even see us doing some cool stuff in the future like:

```
workspace:
  expire: 48hr  # flush the workspace cache every 48 hours
```

**Other Changes**

The `netrc` and the `keys` are moved from the deprecated `Clone` object to the new `Workspace` object, along with the workspace path. The workspace, therefore, defines everything that gets injected into the build environment.

The `system` object is added to provide the information about the Drone system. This could be the version number, the global plugin variables, the plugin whitelist, and (most importantly) the URL to Drone itself which is required by notification plugins that need to construct links back to Drone itself.

**Comment by tboerger** [comment]
Maybe the plugin whitelist as an array?

**Comment by bradrydzewski** [comment]
closing this issue as I've now removed the `clone` object. New payload is publish to `drone-plugin-go`. @tboerger since you are working on plugins, you may want to double-check they work with the new payload

> Maybe the plugin whitelist as an array?

yes, in the system it is an array. Just need to find a way to get arrays (and more complex objects in general) from environment variables into drone. But the data structure is there once we figure that out

**Comment by tboerger** [comment]
I think for env variables you've got 2 solutions.

1) Comma seperated list
2) Numbered env variables like DRONE_PLUGIN_1, DRONE_PLUGIN_2, like it's done within confd env provider
