### ISSUE TITLE
Bitbucket Oauth2 integration

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1147]
Bitbucket now supports oauth2 (including cloning a repository with an access_token) which is really good news. These tokens expire after just 1 hour before needing to be refreshed, which is probably also good news from a security perspective, however, we need to figure out how this impacts our overall system design. 

First, and most importantly, we need to verify that multiple valid access tokens can exist at the same time for a single user. Or stated another way, refreshing an access token doesn't revoke all existing, un-expired access token. **EDIT** I have verified that this won't be an issue! Creating a new token **does not** invalidate existing tokens

Second, we need to figure out what happens if we dispatch a job and the token expires before the job is started. Our workers don't have access to the database to refresh and persist a new access token. Ideally Bitbucket would have offline tokens that don't require refresh (like Google, GitHub, etc), but I didn't see an option in their docs. If multiple access tokens can exist simultaneously, however, this is much less of an issue since we can just force refresh before scheduling a job. If a job takes longer than an hour, this is probably still an issue ... so we'll need to find a way around it.

**Comment by dim** [comment]
+1

**Comment by bradrydzewski** [comment]
**Update** I've verified that refreshing an access token will not invalidate existing tokens. I'm mulling around strategies for exactly how to refresh the access token. I should be able to port Bitbucket to 0.4 this week, as it is my last outstanding item for a 0.4 alpha release

**Comment by bradrydzewski** [comment]
**Snag** in 0.4 drone now sources repository permissions from the host system (ie Bitbucket, Github, etc). When you query a repository in GitHub it includes a `permissions: { read: true, write: true, admin: false}` object. I'm wondering if Bitbucket has a straightforward way to access this information?

**Comment by bradrydzewski** [comment]
0.4 once again supports Bitbucket, however, it now uses the v2 endpoints and OAuth2. The documentation can be found here: https://github.com/drone/drone/blob/0.4.0/docs/setup/bitbucket.md
