### ISSUE TITLE
Ability to force ssh clone URL

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1152]
By default, GitHub now uses the git+https and a netrc file to clone private repositories. This is good for a number of reasons that I won't get into here. It seems that GitHub Enterprise may be able to disable git+https so we need to provide a way to force usage of the git+ssh.

cc @donny-dont maybe you can just verify w/ Richard this is the case?

UPDATE: this was fixed by upgrading GitHub Enterprise. We may still provide this option, but it is now considered a much lower priority.

**Comment by bradrydzewski** [comment]
cc @Bugagazavr when set, the remote plugin could also return an empty string for the .netrc

**Comment by bradrydzewski** [comment]
I'm thinking we add something like `?clone=ssh` to the dsn to enable this feature

**Comment by Bugagazavr** [comment]
:+1:

**Comment by bradrydzewski** [comment]
cool, I probably won't get to this one until later next week. It is a pretty simple change if you want to send a PR, but otherwise I'm happy to take care of it if you don't mind waiting a few days :smile:
