### ISSUE TITLE
listen on port 80 and redirect to https

### ISSUE THREAD

**Issue by davidak** [drone/drone#1172]
optionally drone should be able to listen on port 80 and redirect to https://...

maybe that can be better achieved with a reverse-proxy setup with nginx in production for example?

example nginx vhost:
```
server {
       listen         80;
       server_name    drone.example.com;
       return         301 https://$server_name$request_uri;
}
```

**Comment by bradrydzewski** [comment]
Yes, this configuration should be handled by the reverse proxy. Caddy (for example) will handle this automatically without any configuration. Documenting this sort of advanced Nginx configuration is outside the scope of Drone's documentation
