### ISSUE TITLE
Hook up multi-Docker daemons

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1174]
Re-enable multiple docker daemons. Right now, for testing purposes, only a single daemon was enabled. Some initial implementation details documented here:
http://readme.drone.io/docs/setup/#/docker.md

**Comment by fommil** [comment]
Any idea when you'll get round to this? We have several nodes that are not being utilised at the moment because of this.

**Comment by bradrydzewski** [comment]
just pushed b039519d3f99d3dd2b2f907f032bee87a94153b4 once again allowing drone to manage a worker pool of multiple docker daemons, either local or remote. Tested both, including remote instances created with docker machine and looks like we can mark this complete!

note that docker nodes are now managed via the user interface:

![image](https://cloud.githubusercontent.com/assets/817538/10208943/e152367a-678b-11e5-8401-9ae93f430d97.png)

**Comment by mjschultz** [comment]
Cool! Any plans on allowing matrix builds to use nodes in parallel instead of just commit parallel-ism?

**Comment by bradrydzewski** [comment]
@mjschultz yes, it is planned and shouldn't be too difficult to implement. It just isn't planned 0.4.0 release since I had to draw the line somewhere :)
