### ISSUE TITLE
Token Implementation

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1175]
The token implementation is un-finished and is poorly designed. This includes user tokens, access tokens and post-commit hook tokens. Finalize an implementation and move on!

**Comment by Bugagazavr** [comment]
also in gitlab post-commit token ( repo token ) may be used for clone and access to some build data

```
git clone https://drone-ci-token:repo-token@gitlab.com/namespace/project.git
```

**Comment by bradrydzewski** [comment]
Working to create a common way to handle authorization across all token types (session tokens, user tokens, post-commit tokens). First step was to choose an library for encoding the token. I tested the following libraries with the following results:

```
$ go test -bench=Bench
PASS
BenchmarkJose-4      	   50000	     32994 ns/op
BenchmarkJwt-4       	   50000	     26492 ns/op
BenchmarkAuthCookie-4	  100000	     14420 ns/op
```

**Comment by bradrydzewski** [comment]
Just pushed 8535ea44fdb5004015514fa2ca1c2c3e417003bb which implements a single, unified approach to tokens using the JWT standard. User and session tokens are generated with `user.Hash` and hook tokens are generated with `repo.Hash`

Note that this breaks any existing hook tokens or user tokens.
