### ISSUE TITLE
webhook with gogs

### ISSUE THREAD

**Issue by josselinchevalay** [drone/drone#1176]
Hi all, 

i try to use drone with gogs on docker. 

I use two images : 

- https://hub.docker.com/r/gogs/gogs/
- https://hub.docker.com/r/drone/drone/

i activated link to gogs and drone : i authenticted on drone with gogs login but i can not activated the webhooks

someone would it do that ?

Thx

**Comment by bradrydzewski** [comment]
@josselinchevalay here is what I would expect:

* navigate to repos page (`/account/repos`)
* click on repository to go to repository page
* click activate button, repo is not listed as activated in drone
* hook has been added to gogs
* push a valid `.drone.yml` file to the repository. This should trigger a build

Can you let me know how far you've gotten in the process? Also, do you see anything in the logs? (see docs for accessing logs)

**Comment by josselinchevalay** [comment]
yes it's works

```
docker run -e DRONE_GOGS_URL="" -e DRONE_GOGS_SECRET="" -e DRONE_GOGS_OPEN="true" -p <port pub>:<port private> drone/drone
```

sorry for my mistakes

Thx a lot for reactivity :+1:
