### ISSUE TITLE
Drone cannot clone repo: could not read Username for 'URL'

### ISSUE THREAD

**Issue by Kruemmelmonster** [drone/drone#1177]
Good day everyone!

my drone build is failing due to not being able to clone the repository from my gogs server
My gogs server is running behind a nginx proxy that serves https but serving it directly without nginx doesnt fix the problem!

This is the output from Drone:
```
$ git clone --depth=50 --recursive --branch=master http://domain/user/repo.git /var/cache/drone/src/domain/user/repo
Cloning into '/var/cache/drone/src/domain/user/repo'...
fatal: could not read Username for 'http://domain': No such device or address
```

and this is my .drone.yml
```
image: drone_nodejs
script:
- cd NodejsWebApp1/NodejsWebApp1
- npm install
- npm test
```
and for the sake of completion my Dockerfile for drone_nodejs
```
FROM node:0.12.7-slim

RUN apt-get update -y \
	&& apt-get install -y git

CMD [ "node" ]
```

**Comment by bradrydzewski** [comment]
hey there, you'll want to follow #860

**Comment by Kruemmelmonster** [comment]
my repository im trying to clone is not a private repository! the only thing i activated in the gogs config is that you need a registration to browse the repo's

**Comment by bradrydzewski** [comment]
Can the repository be cloned without a username/password? If not, we need #860 to clone non-public repositories

**Comment by Kruemmelmonster** [comment]
oh pardon it was 4am i didn't realize that it had impact on cloning repo's
