### ISSUE TITLE
0.4 always succeeding

### ISSUE THREAD

**Issue by fommil** [drone/drone#1182]
I ran this script in my build (which was working 0.3)

```
cask install && cask exec ert-runner *.el
```

now, out of sheer stupidity, I was using the wrong docker image and this failed because `cask` wasn't available (return code 127 when that happens).

But drone reports the build as a success!

Therefore, no matter what happens, my builds are passing.

**Comment by fommil** [comment]
another example, http://fommil.com/fommil/e99/3

On the plus side, I'm seeing a lot of green lights :-)

**Comment by bradrydzewski** [comment]
explicitly added `set -e` to the generated build script:
https://github.com/drone/drone-exec/commit/5f1043aae4f917e68491beb912a7e4840a0f5cfc

good catch

**Comment by fommil** [comment]
@bradrydzewski can you please ping me when the `.deb` is rebuilt and I'll start using it

**Comment by bradrydzewski** [comment]
the build agent is a docker container:
http://index.docker.io/u/drone/drone-exec

you can `docker pull drone/drone-exec`, although drone should auto-pull the agent next time it runs the build. I believe I have auto-updated enabled at the moment.

**Comment by fommil** [comment]
so the `.deb` just runs a docker container? heh, its the future.
