### ISSUE TITLE
github `orgs` restriction not letting people in

### ISSUE THREAD

**Issue by fommil** [drone/drone#1184]
After disabling self-registration, I updated to

```
GITHUB_ORGS="ensime,fommil"
REMOTE_CONFIG="https://github.com?client_id=$CLIENT&client_secret=$SECRET&orgs=$GITHUB_ORGS&open=false"
```

(of which one is me and I am an owner of `ensime`) but when I log in, I see this

```
Login is restricted to approved organization members only
```

so I'm guessing org restriction is currently not working.

**Comment by bradrydzewski** [comment]
Updated the docs to use the correct configuration instructions:

```diff
-* `orgs=drone,docker` restricts access to these GitHub organizations. **Optional**
+* `orgs=drone&orgs=docker` restricts access to these GitHub organizations. **Optional**
```

The data URI expects an array or parameters as opposed to a comma-separated string. The markdown docs are updated bdd99041f4561adaffdd65ad36ade4c2a6b2a18b. Next time I publish the docs to `readme.drone.io` this fix will be included.

Good catch
