### ISSUE TITLE
private variables not available in the build

### ISSUE THREAD

**Issue by fommil** [drone/drone#1187]
after upgrading to 0.4 I set some private variables for a build and although I can see them in the admin panel for that repo, I can't access them in the `commands`. If you have trouble reproducing, I have an example.

**Comment by bradrydzewski** [comment]
Private variables are only injected into the plugins (publish, deploy, notify sections) for security reasons. Plugins typically run a fixed set of commands which means they are unable to echo or otherwise compromise secret variables.

We may change this behavior at some point, but first we want to see how far we can get with plugins. So the question is, what are you doing with the secret data and could that be pushed to a plugin

**Comment by fommil** [comment]
some examples:

```
      if [ -n "$SONATYPE_USERNAME" ] && [ -n "$SONATYPE_PASSWORD" ] ; then
        sbt ++$SCALA_VERSION publish ;
      fi

      if [ -n "${DOCKER_TRIGGER_TOKEN}" ] ; then
        curl --data "build=true" -X POST https://registry.hub.docker.com/u/ensime/ensime/trigger/${DOCKER_TRIGGER_TOKEN}/ ;
      fi
```

and also both our emacs and scala tests use the envvar `COVERALLS_REPO_TOKEN` to trigger coverage.

**Comment by bradrydzewski** [comment]
@fommil we have a plugin for triggering a registry build:
http://addons.drone.io/dockerhub/

could we add a plugin for sonatype as well?

**Comment by fommil** [comment]
if all it does in `sbt publish` from that root, then sure.

But after publishing, I'd like to run coverage reporting in an async task and it needs to both: 1) not block the completion of the green light status 2) have access to the token.

**Comment by fommil** [comment]
I'm just looking at the docker hub plugin... am I reading this right, does that require me to put my private token into the public plain text `.drone.yml` file?

**Comment by bradrydzewski** [comment]
nope, you can do this (scroll to bottom of page):
http://readme.drone.io/docs/build/#/env.md

**Comment by fommil** [comment]
also, I only want to trigger the hub build once, not from each entry in the matrix

**Comment by bradrydzewski** [comment]
that use case is addressed -- scroll to bottom of:
http://readme.drone.io/docs/build/#/matrix.md

**Comment by fommil** [comment]
ok cool, I'll try that, e.g.

```
deploy:
  dockerhub:
    token: ${DOCKER_TRIGGER_TOKEN
    repo: ensime/ensime
    when:
      matrix:
        SCALA_VERSION: 2.11.7
```

**Comment by bradrydzewski** [comment]
yep, also `$$DOCKER_TRIGGER_TOKEN` (double `$$`)

**Comment by fommil** [comment]
ok, and that's only on master, not PRs, right?

**Comment by bradrydzewski** [comment]
correct

**Comment by fommil** [comment]
cool, updated, but I'll still need a way to do my `sbt publish` (or mvn/gradle equivalent).

**Comment by fommil** [comment]
if you had a plugin that ran a shell command which was defined by the admin (not the `.drone.yml`), that would solve it. Optionally async (i.e. after success or failure).

**Comment by bradrydzewski** [comment]
also, looking at the sonatype docs it looks like we could create a plugin that pushes to sonatype without sbt. So perhaps sbt could be used to generate the artifacts and plugin could be created that executes the following:

```
$ mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -DpomFile=ossrh-test-1.2.pom -Dfile=ossrh-test-1.2.jar
```

Think of it as a constraint -- if private variables can **only** go to plugins -- can your workflow be adjusted with some slight alterations

**Comment by bradrydzewski** [comment]
let's move this to gitter so that we don't spam people w/ emails that have subscribed

**Comment by fommil** [comment]
no, it is not possible to do what you're suggesting. It must be the `sbt publish` command, it does a lot of magic.

**Comment by bradrydzewski** [comment]
I'd like to explore this a bit more:
https://support.sonatype.com/entries/22189106-How-can-I-programatically-upload-an-artifact-into-Nexus-

I have some contacts in the Scala world that may be able to help out here. If we can demonstrate there are definitely no alternatives to injecting environment variables in the build, I will absolutely add that capability. I'd like to research possible alternatives, however, before I go down that path.

I will explore alternatives to injecting environment variables, which may include:

* using a private script as suggested in the gitter room by @fommil 
* using a proxy container to proxy for uploads. Secure variables are only provided to the proxy container and therefore not accessible to the build container.
* disable injecting variables into the build container unless explicitly enabled in the UI
* ... other ideas that I still need to brainstorm ...

**Comment by fommil** [comment]
if you don't add the capability for me to inject private variables into my builds, I will have to investigate hacks that are completely and utterly insecure. The precedent of injecting private variables into the build has already been set by travis (restricted to `master`), so I should hope that you would have it as an option at the very least.

**Comment by bradrydzewski** [comment]
this issue is dependent on completion of https://github.com/drone/drone/issues/1189 as discussed in the gitter room

**Comment by bradrydzewski** [comment]
This is implemented in the latest `.drone.deb` file and the latest `drone/drone-exec` image. I'm still doing a bit of testing and may tweak the final implementation as described in #1189, however, this issue itself can be closed.

This is an example of a Yaml file where you want secrets variables injected into your build:

```yaml
build:
  image: foo
  commands:
    - echo $FOO
  environment:
    - FOO=$$FOO
```

Note that we include the secrets are in the `environment` section. We don't want to put the secrets in the `commands` section, otherwise they would be echoed out in the build console. So we use the `environment` section instead.

The secrets themselves are stored in an encrypted `.drone.sec` file. This is what the file looks like prior to being encrypted:

```yaml
environment:
  - FOO=BAR
```

The encrypted `.drone.sec` file should be added to your repository. To encrypt the file please see the preliminary docs that I've created: https://github.com/drone/drone/blob/0.4.0/doc/build/secrets.md

The `.drone.sec` feature is new and still being tested. Once it is fully tested we will close out #1189

**Comment by fommil** [comment]
Are you going to drop support for defining these variables in the admin panel?

**Comment by fommil** [comment]
@bradrydzewski can you please set the envvars to empty strings if the values are not available? e.g. in PRs I'm seeing `$SONATYPE_USERNAME` equal to the literal string `$$SONATYPE_USERNAME` but that makes it difficult to detect when its actually set.

**Comment by bradrydzewski** [comment]
yes, I'll work on a solution to that issue. In the mean time, as a temporary workaround, you can look for `DRONE_PULL_REQUEST` environment variable. If the `DRONE_PULL_REQUEST` variable is set, you can assume the other environment variables **won't** be available.
