### ISSUE TITLE
Ability to either set locale in setup or default to en_US.utf8

### ISSUE THREAD

**Issue by cggaurav** [drone/drone#119]
![Localte](http://f.cl.ly/items/0a0v023t1b2V151O420G/Screen%20Shot%202014-02-24%20at%2012.30.10.png)

**Comment by floatdrop** [comment]
Why drone needs to set this? Should'nt it be configured in docker image instead?

**Comment by bradrydzewski** [comment]
@floatdrop yes, as part of #749 we will no longer be setting the locales by default in the `drone/images` ... in fact, we will also be deprecating the `drone/images` in favor of the official docker language stacks

**Comment by bradrydzewski** [comment]
just merged PR from @floatdrop closing this issue
