### ISSUE TITLE
Plugin upgrades leave untagged layers

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1193]
When a plugin automatically upgrades, docker untags the older image layers, leaving them labeled as `<none>`. This is an example of what we see when running `docker images`:

```
REPOSITORY  TAG         IMAGE ID        CREATED         VIRTUAL SIZE
<none>      <none>      a3599da68365    8 hours ago     15.6 MB
<none>      <none>      80e7709b7395    8 hours ago     15.64 MB
<none>      <none>      9e0802a7fe0b    25 hours ago    15.6 MB
<none>      <none>      e2c70e7e5329    29 hours ago    15.59 MB
<none>      <none>      0bc862fde87b    30 hours ago    15.59 MB
```

The can be removed with the following command:

```
sudo docker rmi $(sudo docker images -f "dangling=true" -q)
```

We should implement or document a strategy for dealing with these dangling images. We may implement something directly in drone. We may recommend a cron job. We may recommend running `docker-gc` [1] as a cron job.

[1] https://github.com/spotify/docker-gc

**Comment by tboerger** [comment]
I would suggest integrate parts of https://github.com/rancher/sherdock into drone

**Comment by bradrydzewski** [comment]
@tboerger cool I'll definitely take a look at Sherdock. I think the `regexp` based option could be really interesting.

I should probably consolidate to a single issue, but my plan is expand our plugin model beyond just public / deploy / notify plugins. I'd like a `POST_BUILD` plugin (at the system level) that triggers when a build completes. It could be used to manage the size of the cache (#1160) or remove untagged image (#1193).

I'd like a `POST_ACTIVATE` plugin (also at the system level) that triggers when a repository is added to Drone. This could be used to automatically add `.drone.yml` files or badges the README (#1161).

These plugins would be optional and be declared in the `dronerc` file. Below is a contrived example to give you an idea of what I'm thinking:

```
POST_ACTIVATE=spotify/docker-gc --exclude plugins/* --max-size 10gb
```

I'd like to enable these sort of activities with the plugin model so that people can integrate whatever technologies or strategies they want into Drone, so that we don't force a one-size-fits-all strategy directly inside Drone :)

**Comment by bradrydzewski** [comment]
I'm going to close this in favor of `docker system prune` commands
https://docs.docker.com/engine/reference/commandline/system_prune/
