### ISSUE TITLE
Recreate Queue on Restart

### ISSUE THREAD

**Issue by vtolstov** [drone/drone#1195]
I'm stress test drone 0.4.0 and docker. If i forcebly restart docker and drone, build container may not be destroyed, and restart build does not work, because docker says that container with this name already exists.
I think drone needs check for container existance before creating, and destroy it when rebuild.

**Comment by bradrydzewski** [comment]
Yes, I think ideally Drone would re-build the Queue on restart. When Drone shuts down the builds are still running, so it is just a matter of querying the docker daemon on restart.

**Comment by vtolstov** [comment]
thanks!

**Comment by bradrydzewski** [comment]
re-building the queue is a bit of work, and will take some re-architecting, but I think it will be a very nice feature. This will probably ship after 0.4.0, but hopefully soon after

**Comment by bradrydzewski** [comment]
until we have the ability to re-build the queue on restart, you'll need to run the following commands to mark running builds as errors:

```sql
update builds set build_status = 'error' where build_status IN ('pending','running');
update jobs set job_status = 'error' where build_status IN ('pending','running');
```

**Comment by bradrydzewski** [comment]
proposal to eliminate central push queue and replace with pull queue. see https://github.com/drone/drone/issues/1386

**Comment by bradrydzewski** [comment]
changeset merged 2004
