### ISSUE TITLE
Manually kick off a build

### ISSUE THREAD

**Issue by cjb** [drone/drone#1199]
I'd like to use 0.4 at my company, but I can't (and wouldn't want to) open up a public port on my machine to receive callbacks.  Is it possible to get a button or shell command that kicks off a build against the latest revision of a repo?

**Comment by bradrydzewski** [comment]
@cjb data must be pushed to Drone via a post-commit hook. Drone is intended to be installed on a server with an open port to accept hooks. You could however, manually invoke the `/api/hook` endpoint with a payload that is compatible with the GitHub hook payload. You can get sample GitHub payloads in the GitHub UI by going to your repository settings, webhooks & services section, and clicking on existing webhooks. You would need to include the `access_token` when invoking the hook. You could do this with `cron` or `curl`, etc.

This isn't something we're going to build into Drone, but you are definitely free to reverse engineer the HTTP endpoint to fulfill your use case.
