### ISSUE TITLE
create mariadb database if not existant

### ISSUE THREAD

**Issue by drahnr** [drone/drone#1206]
Is there a reason the database is not generated based on the information the drone.toml config file provides (given authorization is granted)?

Or is this due to the fact that the operation db user may not have sufficient rights to create a database?

**Comment by bradrydzewski** [comment]
yes, there are a number of reasons such as the one you mentioned. Instead of coding around corner cases drone requires the database is created. 

feel free to ask questions in the gitter room at gitter.im/drone/drone
