### ISSUE TITLE
Unable to fetch .drone.yml file, from gitlab

### ISSUE THREAD

**Issue by epcim** [drone/drone#1208]
Hi, I am using drone.io + (custom) gitlab integration for some time, but it suddenly stopped to work for new repos I created.

When the gitlab call drone hook to start build, the following is written to drone.log:

{{{ Unable to fetch .drone.yml file. *Gitlab.buildAndExecRequestRaw failed: <404>
}}}

Ok, it can be an auth/authz issue. However builds (ci runs) works for existing repo, already configured in drone.

I have tried to use new ClientID for gitlab, netrc + add drone user to group, delete repo + reactivate on drone site - same behavior. Still not work only for new repos.  Also I do not see any issues on Gitlab side, so it seems to me that drone.io fetch for .drone.yml fails silently which cause interruption during the build.

Can you give me any guidance how to debug deeply whats going on, what auth/authz are being used.

Thanks in advance.

**Comment by pmichalec** [comment]
I am using drone 0.3.0-alpha + gitlab 7.7

**Comment by epcim** [comment]
I found that drone tries to download from `api/v3/projects` while gitlab permaling works. Surprisingly this affect only newly activated repositories!

```
https://git.vums.blueit/api/v3/projects/chef-cookbooks%2Flab_backup/repository/blobs/616bebfffc8762f68063f3eac1362d5d09?filepath=.drone.yml
```
permalink:
```
https://git.vums.blueit/chef-cookbooks/lab_backup/blob/65456c35187d2a6c06432b6ba6142de09253519e/.drone.yml
```
(ignore different blob hash)

**Comment by bradrydzewski** [comment]
cc @Bugagazavr is the go-to guy for all things GitLab. Perhaps he will have some suggestions

**Comment by Bugagazavr** [comment]
@epcim gitlab version? gitlab installation( custom or omnibus ) ? drone version?

**Comment by epcim** [comment]
Well it was working earlier on 7.x branch but then I updated my node to 7.7 stable. It's custom version - installed from a chef cookbook: https://github.com/atomic-penguin/cookbook-gitlab.

Is there a way to grab more from logs or modify the behavior?

I am now working on an gitlab cookbook for 8.x branch, so if not resolved within days I will upgrade my nodes to 0.4.0 drone and 8.x gitlab to give a try.

```
( default['gitlab']['git_branch']                             = '7-7-stable'    
normal['gitlab']['shell']['git_branch']                     = 'v2.4.1'
default['languages']['ruby']['default_version']             = '2.1.5'
)
```

**Comment by Bugagazavr** [comment]
@epcim sorry, but i can't help you with custom installation, because, i don't know when placed your `production.log`, you can use omnibus installation  ( https://about.gitlab.com/downloads/ this uses embedded chef too )

**Comment by epcim** [comment]
I migrated to drone 0.4.0 and gitlab 8.x
