### ISSUE TITLE
Exclusive drone for a project

### ISSUE THREAD

**Issue by brunowego** [drone/drone#1211]
Have a way to remove the stretch `gitlab.domain.com` from URL?

```txt
http://drone.domain.com/gitlab.domain.com/group/project
```

Thanks a lot!

**Comment by bradrydzewski** [comment]
In the 0.4 branch (next release) the `:host/:owner/:repo` is replaced with `:owner/:repo`. Feel free to ask such questions in our gitter room (https://gitter.im/drone/drone)

**Comment by brunowego** [comment]
Thank you for having responded, sorry to ask here. Thanks for the tip.
