### ISSUE TITLE
Problem with deploying to heroku

### ISSUE THREAD

**Issue by karolsojko** [drone/drone#1214]
I get this when I try to deploy to heroku:

```
$ git remote add heroku https://git.heroku.com/...
$ git push heroku $COMMIT:refs/heads/master
error: RPC failed; result=22, HTTP code = 400
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```

it might have something to do with the fact that dron does a shallow clone - does anybody have a solution for this?

**Comment by donny-dont** [comment]
This 0.4 or 0.3?

**Comment by karolsojko** [comment]
`0.3.0-alpha` - Ok I assume I need to hit DigitalOcean to update their droplet applications to a newer version. Or is there a way to upgrade drone from cli ?

**Comment by bradrydzewski** [comment]
the heroku plugin was re-created in 0.4 invalidating the issue https://github.com/drone-plugins/drone-heroku
