### ISSUE TITLE
Missing webhooks when commit message is big

### ISSUE THREAD

**Issue by mariomarin** [drone/drone#1217]
I had to run this on drone 0.3 `alter table commits alter column commit_message type varchar;` the commit message was limited to 255 characters and it was causing missing webhooks.

```
2015/09/29 20:19:00 Unable to persist commit bbd96e4c1908177b81b4b3a8e77c3aaf8aea9974@develop. meddler.Insert: DB error in QueryRow: pq: value too long for type character varying(255)
```

**Comment by bradrydzewski** [comment]
tracking as https://github.com/drone/drone/issues/914
