### ISSUE TITLE
css problems

### ISSUE THREAD

**Issue by dchristophersen** [drone/drone#1219]
Hi, 

I just installed drone through the .deb-Package. 
Everything seems to work except for the interface UI.

![screenshot 2015-10-01 12 30 29](https://cloud.githubusercontent.com/assets/5519491/10218871/98d9be40-683a-11e5-8e48-425fdbdfdded.png)

I looked in the chrome developer tools and any resources seems to be loaded correctly.

Any ideas on how to fix it?

**Comment by bradrydzewski** [comment]
recently released 0.4 version where this should no longer be an issue
