### ISSUE TITLE
drone login (to gitlab) returns "The redirect URI included is not valid"

### ISSUE THREAD

**Issue by epcim** [drone/drone#1221]
@Bugagazavr can you pls comment the following error I found on the following configuration? any idea?

When I try to LogIn the Drone, I will get: "The redirect URI included is not valid" on an Gitlab page.

```
https://git.lab.ci/oauth/authorize?client_id=7a72db7cb5d74f6870c5d279a96bbf50420db9a84aa8c7d5c1525349dae138e2&redirect_uri=https%3A%2F%2Fdrone.lab.ci%2Fauthorize&response_type=code&scope=api&state=drone
```

drone log:
```
 [GIN] 2015/10/06 - 15:12:38 | 200 |     231.362µs | 172.16.0.214:43077 |   GET     /login
[GIN] 2015/10/06 - 15:12:40 | 303 |     112.659µs | 172.16.0.214:43077 |   GET     /authorize
```

```
CLIENT="7a72db7cb5d74f6870c5d27xxxx"
SECRET="54575e0053a1dcfa6a6916xxxx"

REMOTE_DRIVER="gitlab"
REMOTE_CONFIG="https://git.lab.ci?client_id=$CLIENT&client_secret=$SECRET&skip_verify=true&open=false"
```

Drone 0.4.0 (tested with .deb and builded from source, today)

GitLab 8.0.4

GitLab Shell 2.6.5

GitLab API v3

Ruby 2.1.5p273

Rails 4.1.12

**Comment by bradrydzewski** [comment]
Looks like your redirect URL is incorrect. I see `https://git.lab.ci/oauth/authorize` instead of `https://git.lab.ci/authorize`

Feel free to ask questions in gitter.im/drone/drone prior to logging issues

**Comment by bradrydzewski** [comment]
can you also add logs from GitLab? I'm sure @Bugagazavr will ask for those as well

**Comment by bradrydzewski** [comment]
also, can you confirm you registered the redirect url in gitlab? For example, in GitHub I need to register `https://git.lab.ci/authorize` as the redirect url, and if it doesn't perfectly match, GitHub gives a similar error

**Comment by Bugagazavr** [comment]
@epcim you need have the same URL's in your oauth application and real drone `https://dronehost.com/authorize`, double check your url and schema.

**Comment by epcim** [comment]
thanks, works now (tl;dr - I upgraded old gitlab from 7x to 8x and forgot the configuration steps, where the redirect uri changed on drone side)
