### ISSUE TITLE
Outdated drone.io base system forbids installation of packages

### ISSUE THREAD

**Issue by dietmarw** [drone/drone#1230]
It seems the current base system of drone.io is missing a substantial number of updates. Something that leads to:

```
sudo apt-get install -qq -y libcomedi-dev:i386
```
failing. Trying to do a
```
sudo apt-get update
sudo apt-get upgrade -y 
sudo apt-get update
sudo apt-get dist-upgrade -y 
sudo apt-get update
```
Also fails so there is no chance to get the underlying drone.io system up to current. 
Any chance that you run those commands *once* to get all users up to date and at the same time reduce build times?

**Comment by bradrydzewski** [comment]
this issue tracker is reserved for the open source project, which is not the same as drone.io

**Comment by dietmarw** [comment]
Ah sorry. Didn't know that. So I guess support@drone.io would be the right channel?

**Comment by tbeu** [comment]
@dietmarw please read cryptochat now!!!
