### ISSUE TITLE
Upgrade Python

### ISSUE THREAD

**Issue by techtonik** [drone/drone#1239]
From mailing list:
> I'm not attached to Mercurial or Git, but drone.io is the source of
persistent problems for me when working on astroid because it runs
ancient software.  Apparently it's still on Mercurial 2.0, and the
latest Python version it supports is 3.3.  Since most people who use
Python 3 at all use the latest release, having a CI that's two full
versions behind undercuts the point of having a CI in the first place,
since drone.io isn't even testing the Python 3 version most users have.

**Comment by bradrydzewski** [comment]
hey there, this open source project is not the drone.io service. This codebase runs on Docker and therefore works with any valid Docker image, including the official [python:3.5](https://hub.docker.com/_/python/) image.
