### ISSUE TITLE
Support LXD

### ISSUE THREAD

**Issue by techtonik** [drone/drone#1240]
https://github.com/lxc/lxd is a Docker alternative. Would be pretty cool to spin drones there.

**Comment by bradrydzewski** [comment]
I'm closing this as out-of-scope. Right now drone is heavily integrated Docker containers and there are no plans to unwind the integration at this time to support alternate container engines. If there is a high demand to support alternate engines in the future we can re-open the issue

**Comment by techtonik** [comment]
With LXD you could run drone brains on Windows machine and command remote Linux nodes from there.

**Comment by gtaylor** [comment]
Might be easier to run Drone within a VM and get the same thing.

**Comment by techtonik** [comment]
Clumsy, memory hungry and slow.

**Comment by bradrydzewski** [comment]
Drone (server) is portable and runs on linux / osx / windows. Docker and windows have partnered for native windows support which will enable Drone server (linux) to command a windows server. If we look at an alternate engine, it would likely be rkt given its support for the open container initiative and backward compatibility with Docker images.

**Comment by techtonik** [comment]
It looks like rkt + its spec is aimed at single app containment, which is better suited for various microservices, which need to be guided how to configure them. I see LXD as a lightspeed replacement for VMs, which is probably what CI services want to run.

**Comment by gtaylor** [comment]
Perhaps another way to look at things: Drone is still a relatively young and small (but growing) community. Manpower has to be focused on the things that will give us the best bang for the buck. LXD wasn't mentioned at all in our latest user survey, and is relatively niche at this time.

Who knows what the future holds, but this would be a big detour during a time where we have to be very focused and deliberate in building out our core feature set.

**Comment by sl1pm4t** [comment]
I'm a user of both LXD and Docker, and I really don't see the benefit of adding LXD support to drone.

**Comment by techtonik** [comment]
@gtaylor seem fair. Good luck with you plan. I wish you find the time to repair drone.io - it could be useful for SCons and few other open source projects, which are not hosted on Github and can not use Travis because of this.

I am asking for LXD, because I am running LXD client on Windows machine, and it would be just convenient for me to use the same container to run tests on my LXD server as it is used in CI.
