### ISSUE TITLE
Parallel Matrix Execution

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1254]
Matrix builds are intended to run in parallel, however, the initial implementation runs them sequentially in the interest of getting something to people quickly.

The main issue right now is that our queue is a bit of a mess. I want to sit down and re-design the queue (this will have no external or breaking impact to Drone). An improved queue could let us support multiple architectures (routing builds to different servers based on arch), would support parallelism, and would re-build itself on restart (see #1195).

So #1195 is really the pre-requisite for this issue.

**Comment by elgalu** [comment]
+1

**Comment by chipsenkbeil** [comment]
Any update to the status/priority of this issue? Seems like quite an important one. I certainly know that I could use it, given my build/test times.

**Comment by steve-gray** [comment]
Hey @bradrydzewski: I notice that in 0.5 it seems that things are running in parallel. Is there a way in the YAML that is proposed to allow us to indicate 'Publish, but only when every matrix permutation passes?' as a concept? Following through the documentation, it appears that this is still problematic - similiar to today where if we do a crossbuild, if the chosen publisher permutation succeeds it'll run the deploy, even if other permutations fail.

i.e.:

pipeline:
     stage_build:
         -- Task here that varies based on matrix
     stage_publish:
         run_publish:
               -- Docker push plugin here.

matrix:
   ELASTIC_VERSION:
      - 2
      - 2.2

**Comment by bradrydzewski** [comment]
@steve-gray this can be achieved with a plugin. see https://github.com/drone/drone/issues/1512

**Comment by bradrydzewski** [comment]
this patch landed in 0.5 when agents were introduced and the queue was modified to accept jobs instead of builds (more granular) enabling parallelism. closing in preparation for upcoming 0.5 launch.

**Comment by steve-gray** [comment]
@bradrydzewski - I'm confused - the thread you're referring to says there _could_ be a plugin to do it - but I've not been able to readily find anywhere a description of what hooks a pipelines step can use to introspect about other concurrent workflows for a given pipeline.

There's two discrete problems at play here:

- Wait for an external resource (i.e. Don't run two concurrent deploys from different services/run the same task in two builds concurrently). That's a cleanish plugin scenario where something external can maintain a mutex on another thing.

- Where you only want to run a publish step after all other matrix permutations succeed. Doing this inside the workstream would mean that the drone task containers would need to talk back to drone's server to poll/wait for this stuff. That kind of explicit knowledge of the server itself is kind of without precedent in the plugins for Drone (the closest is the downstream trigger, but not really equivalent).

I suspect I'm missing something?

**Comment by bradrydzewski** [comment]
> Where you only want to run a publish step after all other matrix permutations succeed. Doing this inside the workstream would mean that the drone task containers would need to talk back to drone's server to poll/wait for this stuff. That kind of explicit knowledge of the server itself is kind of without precedent in the plugins for Drone (the closest is the downstream trigger, but not really equivalent).

you could create a plugin that uses the drone api to poll the drone server and wait for all other jobs to complete. The plugin would block while polling, and then unblock once other jobs complete, allowing the rest of the pipeline to complete.

the [downstream](https://github.com/drone-plugins/drone-downstream) plugin is an example of a plugin that interacts with the drone server using the api. You could use this plugin as a reference.

this is some dummy / pseudo code to demonstrate how the plugin could work:


```Go
// this is dummy code
var (
  repo = os.GetEnv("DRONE_REPO")
  build = os.GetEnv("DRONE_BUILD_NUMBER")
  number = os.GetEnv("DRONE_JOB_NUMBER")
  server = os.GetEnv("DRONE_SERVER)
  token = os.GetEnv("PLUGIN_TOKEN)
)

drone := drone.New(addr, token)

for {
  var done int
  jobs, _ := drone.GetBuild(repo, build)
  for _, job := range jobs {
    if job.Number == number {
      continue
    }
    if job.Status == "running" || job.Status == "pending" {
      continue
    }
    done++
  }
  // if all jobs complete
  if done == len(jobs) - 1 {
    break; // exit blocking loop
  }
  // else wait until build is done
  time.Sleep(10*time.Second)
}
```
