### ISSUE TITLE
Upgrade vendored pq library to support sslrootcert option

### ISSUE THREAD

**Issue by chromakode** [drone/drone#1259]
I was not able to get the `sslrootcert` postgres connection option ([in the drone docs here](https://github.com/drone/drone/blob/master/docs/setup/postgres.md#postgres-options)) to work -- it seems to accept any value and have no effect. Digging deeper, it appears that the vendored version of `pq` that drone currently uses doesn't appear to support the `sslrootcert` option: there's no mention of it in the drone repo except for in documentation. Looks like this is supported in more recent versions of `pq`.

**Comment by bradrydzewski** [comment]
fixed by pull request #1264

**Comment by bradrydzewski** [comment]
thanks for letting me know
