### ISSUE TITLE
Drone not able to fetch Gogs repos

### ISSUE THREAD

**Issue by Svenskunganka** [drone/drone#1260]
I'm trying to add Gogs integration to Drone but it seems like Drone isn't pulling my repo's from Gogs successfully. The message from Drone is `Your repository list is empty`. Additionally, Drone has issues pulling my avatar as well. Browser is running `GET drone.domain.tld/avatars/1` with a `404` response.

Logs from `docker logs drone` (seems to be the culprit):
```
[GIN] 2015/10/27 - 01:35:11 | 200 |     912.901µs | [IP REDACTED] |   GET     /
time="2015-10-27T01:35:11Z" level=error msg="Cannot find remote repository avatars/1 for user Svenskunganka. Not Found" 
[GIN] 2015/10/27 - 01:35:11 | 404 |  148.550835ms | [IP REDACTED] |   GET     /repos/avatars/1
```

Access logs from nginx:
```
[IP REDACTED] - - [27/Oct/2015:01:35:11 +0000] "GET /api/v1/user/repos HTTP/1.1" 200 14283 "-" "Go-http-client/1.1" "[IP REDACTED]" // FROM Drone TO Gogs
[IP REDACTED] - - [27/Oct/2015:01:35:11 +0000] "GET /avatars/1 HTTP/1.1" 404 941 "https://drone.domain.tld/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "[IP REDACTED]" // FROM User TO Drone
```

When I run the `/api/v1/user/repos` directly in Gogs I can see both private, public and organization-owned repos that I have access to and according to Nginx logs it proxies `14283` bytes of data, so Drone should recieve the data from Gogs.

Both Gogs and Drone is running inside their own respective Docker containers, with a single additional Nginx proxy in front of them (in order to have them accessible via `git.domain.tld` and `drone.domain.tld`).

Here's my `dronerc` file (redacted the actual domain, want to keep all that private):
```
REMOTE_DRIVER=gogs
REMOTE_CONFIG=https://git.domain.tld
```

Anyone else having similar issues? I know that `v0.4.0` that was released just hours ago added support for Gogs.

**Versions:**
Drone: `v0.4.0`
Gogs: `v0.6.15.0926`
Nginx: `v1.9.5`

**Comment by bradrydzewski** [comment]
@Svenskunganka the dashboard page displays repositories that are active in Drone. This first time you login this list will be empty. The search box, however, contains the full list of repositories (cached for 24 hours). So if you are looking to add a new repository you should try to search.

This is an example of my personal gogs instance before I activate a repository, notice the dashboard is empty but the search box yields results:

![image](https://cloud.githubusercontent.com/assets/817538/10748781/b5b3f946-7c20-11e5-93c5-395f4bc7eac8.png)

You can verify this by hitting the `/api/user/repos/remote` endpoint as well. To be fair I think this is crappy UX in Drone and I'll work on finding a way to make this more clear.

In terms of avatars, these come from gravatar. This is what I see in my installation:

![image](https://cloud.githubusercontent.com/assets/817538/10748835/3ff330fe-7c21-11e5-9938-c0131d8ad10c.png)

Please note that Drone is tested with the absolute latest version of Gogs. I am running `0.6.16.1022`. Unknown also added some endpoints the other day to better accommodate Drone, with means the minimum version will be increased.

I have a local patch that specifies to use the searchbox when the dashboard is empty to help clarify things. I will push that shortly. Cheers

**Comment by bradrydzewski** [comment]
added d54480b1218956189e4ec9b2a450845f6cb590ca to show all repositories (even non-active). This should serve as a temporary fix until I have a better solution

**Comment by bradrydzewski** [comment]
sorry, meant to comment on avatars. In the latest version of GitLab I have no issues with avatars, but I did have to code around some bugs in the Gogs API. Specifically I had to introduce a function to repair malformed avatar urls [1]

```Go
// fixMalformedAvatar is a helper function that fixes
// an avatar url if malformed (known bug with gogs)
func fixMalformedAvatar(url string) string {
	index := strings.Index(url, "///")
	if index != -1 {
		return url[index+1:]
	}
	return url
}
```

[1] see https://github.com/drone/drone/blob/master/remote/gogs/helper.go

The point being is that it seems we are on different versions of Gogs and it is quite possible different versions return different results. If you could provide sample results that would be helpful. Also perhaps upgrading Gogs to ensure we are testing the same version

**Comment by Svenskunganka** [comment]
Ahhh I feel so stupid now, but at least we found a UX issue! :+1:
I'm able to find my repos using the search, just thought that it wasn't able to fetch the repos due to the `Your repository list is empty` message.

I've updated Gogs to `0.6.18.1026`, everything works the same on Drone so no compatibility issues. I still have issues with avatars - I'm not using Gravatar on my Gogs profile, I've directly uploaded one - so perhaps that's the issue? Tried updating Drone to `drone/drone:latest` but it gave an older `0.3.X` version.

**Comment by bradrydzewski** [comment]
no worries, it actually confused quite a few people, so I'm glad we made the improvement :)

> I've updated Gogs to 0.6.18.1026, everything works the same on Drone so no compatibility issues. I still have issues with avatars - I'm not using Gravatar on my Gogs profile

Can you paste the avatar url so I can see the format? The gravatar urls are formatted as `//1.gravatar.com/gravatar/<hash>`. Based on the error message you pasted above I'm wondering if uploaded avatar urls use a different format, specifically if they don't include the domain name?

**Comment by Svenskunganka** [comment]
This is in the markup from Gogs:
![Gogs markdown](http://i.imgur.com/8lvmZgZ.png)

Does not include the domain

**Comment by bradrydzewski** [comment]
ok, cool, I can issue a fix to append the domain if not present
