### ISSUE TITLE
Gogs avatars without domain

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1263]
per issue #1260

the gogs implementation currently assumes a gravatar url with a format of `//1.gravatar.com/gravatar/<hash>`. If someone is not using gravatar, and has uploaded a custom avatar, the url format with be `/avatars/<id>`.

we need to account for the latter by prepending the `//<hostname>`

**Comment by bradrydzewski** [comment]
cc @Svenskunganka

just merged the following pull request:
https://github.com/drone/drone/pull/1265/files

this attempts to expand relative avatar urls to the full url. It is passing tests, but I haven't tested with a non-gravatar gogs configuration, so I'm looking forward to your feedback

**Comment by Svenskunganka** [comment]
Alright, the repo images works well, however the profile image up top is still trying to access the avatar the old way:

![Drone dashboard](http://i.imgur.com/UEY5wkL.png)

**Comment by bradrydzewski** [comment]
Good catch. Pushed a fix for the User avatar that should be available in ~5 min once the build completes. This will require you to login / logout so that it can persist the absolute URL.

**Comment by Svenskunganka** [comment]
Yep, everything's good now after logout/login! Awesome work, Brad!

**Comment by Svenskunganka** [comment]
Found a last issue with the Avatars now that I'm starting with the actual builds that I did not have access to before:

![buildpage](http://i.imgur.com/kLhBzU6.png)

**Comment by bradrydzewski** [comment]
can you get me a copy of the hook payload (from gogs repo settings, hook)? It would be helpful to see what the avatar looks like that comes in the message

**Comment by Svenskunganka** [comment]
Sure, this is the interesting part of the payload:
```json
{
  ...
  "sender": {
    "login": "Svenskunganka",
    "id": 1,
    "avatar_url": "https://git.domain.tld//avatars/1"
  }
}
```

**Comment by bradrydzewski** [comment]
does the image tag in the drone UI have `https://git.domain.tld//avatars/1`?

we actually have a similar issue with gravatar, where I had to create a helper function to parse out `///`:

```
func fixMalformedAvatar(url string) string {
	index := strings.Index(url, "///")
	if index != -1 {
		return url[index+1:]
	}
	return url
}
```

**Comment by Svenskunganka** [comment]
Yeah it has, and directly accessing that link gives a `404` from Gogs, so I think it's a problem on their end.

**Comment by bradrydzewski** [comment]
ok, cool, I'm updating the `fixMalformedAvatar` function now

**Comment by bradrydzewski** [comment]
ok, just pushed https://github.com/drone/drone/commit/e1daf0fd749c3d05b200547e24ab4a353e7a138d
