### ISSUE TITLE
Add login redirect for 404s

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#1266]
If a user isn't logged in and follows a Drone link it will 404 ala GitHub. This can cause some confusion for users as they don't see anything and don't know they aren't logged in. It would be great to have a login prompt if they're not logged in to avert any questions about access.

**Comment by macb** [comment]
I want to add some support for this. My org generally discovers what drone is via a PR hook, so they click and get a 404 and are confused. :)

**Comment by adamstep** [comment]
This is also an issue in our organization. @bradrydzewski would you be opposed having this as a configurable option (through an environment variable)?

**Comment by bradrydzewski** [comment]
@adamstep I think replacing the 404 with a prompt to login will probably solve the issue, as long as the login can re-direct back to that page. If you login and that repository doesn't exists or you don't have access, you'll get a 404 (hopefully with a more intuitive message)

**Comment by adamstep** [comment]
Sounds good, I will look into this.

**Comment by gdubicki** [comment]
+1

**Comment by gtaylor** [comment]
@gdubicki Please don't add +1 comments to issues, as it notifies all subscribers. Use the reaction button on the issue.

**Comment by bradrydzewski** [comment]
Closing now that we have the upcoming 0.5 UI merged which makes it much more clean when you need to authenticate.

I also have a separate issue for improving the error messaging in the main content pane. I'll be tracking this at https://github.com/drone/drone-ui/issues/20

<img width="677" alt="screen shot 2016-07-11 at 4 04 38 pm" src="https://cloud.githubusercontent.com/assets/817538/16749720/338c54e0-4781-11e6-9c7b-c7dba7bde8d1.png">
