### ISSUE TITLE
drone 0.4 docker image can't use /etc/hosts

### ISSUE THREAD

**Issue by thomasf** [drone/drone#1269]
There is no `/etc/nsswitch.conf` in the image so I extended it and added one and it started working:

```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by thomasf** [comment]
This is of an invaluable feature when running a database in a linked container.

**Comment by bradrydzewski** [comment]
@thomasf this makes sense because we're using `scratch` as our base image. The `scratch` image is a blank Docker image that is completely empty, which means the Drone image just has Drone (and some certs) and nothing else.

I should be able to get this added to our build process today

**Comment by cmpis** [comment]
I just started with Drone today and ran in to this issue. Had to hardcode the ip for now.

Two questions: Does /etc/hosts exist/work now? && Any plans to release this soon?

**Comment by tboerger** [comment]
Maybe we should simply switch to alpine as base image? That increases the container size only 3 or 4 MB.

**Comment by bradrydzewski** [comment]
@thomasf we merged the nsswitch but seem to still see postgres connection issues with linked containers. Any chance you could take a look at https://github.com/drone/drone/issues/1436 and provide any tips or tricks to getting this working?

**Comment by thomasf** [comment]
I see that it was resolved.. 

Should I maybe prepare an example docker-compose configuration for the contrib  directory so it's easier to get started for people who wants to use such a setup?
