### ISSUE TITLE
Triggering dependent projects

### ISSUE THREAD

**Issue by rubenv** [drone/drone#1270]
At my company we have a big backend project and multiple client projects (API libraries, frontends, side services, ...).

Aside from unit tests, each client project contains real integration tests which test against a live backend. Since every change in the backend has the potential to break a client (let's hope not), we currently have a Bamboo setup that triggers all the client test suites whenever the backend changes. This is the only way for us to be really confident in our backend changes.

But let's face it, Drone is a much nicer CI system and we'd like to get rid of the Bamboo setup.

Is there a way to configure Drone in a similar way?

--

PS: This might have come up before (very probable), but I didn't find any past discussions. Please close and redirect if this is the case.

**Comment by bradrydzewski** [comment]
Thanks for the feedback. Tracking issue https://github.com/drone/drone/issues/297 :smile: 

I'm thinking we can initially create a Drone plugin for Drone. The plugin could trigger builds for other repositories using the Drone API. We already have an API library available, which should make this pretty easy to create.

```
notify:
  drone_trigger:
    repos:
      - octocat/Hello-World
      - octocat/Spoon-Knife
    token: $$DRONE_TOKEN
```

While I think having a built-in solution might be nicer, it will probably take a while to get there. This plugin, however, can be created today without any code changes to Drone itself :smile: . Plugin are pretty simple to create if you're interested. I can offer suggestions.

**Comment by bradrydzewski** [comment]
I mentioned this in the other issue, but I figured I'd circle back here as well. The plugin ended up being pretty simple so I took 1/2 hour and coded one up. http://addons.drone.io/trigger/
