### ISSUE TITLE
.drone.yml checksum must be lowercase, but PowerShell emits uppercase

### ISSUE THREAD

**Issue by wolfgang42** [drone/drone#1277]
The documentation on [secret variables](http://readme.drone.io/build/secrets.html) suggests the following PowerShell command to get the checksum for the file:
```powershell
$ Get-FileHash .\.drone.yml -Algorithm SHA256
```

The problem is that `Get-FileHash` emits an uppercase hash, but Drone expects a lowercase one, so validating the checksum fails.
You can get a lowercase hash from PowerShell like so:
```powershell
$ (Get-FileHash .\.drone.yml -Algorithm SHA256).Hash.ToLower()
```

On the other hand, perhaps it would be better to accept both uppercase and lowercase checksums? I can submit a pull request for either solution, but I'm not sure which one is better.

**Comment by bradrydzewski** [comment]
@wolfgang42 thanks for the info, very good to know. Let's update the docs to reflect `.Hash.ToLower()`.  I'm also going to be pushing people toward the [drone-cli](https://github.com/drone/drone-cli) project which will handle generating the `.drone.sec` file with a correct shasum
