### ISSUE TITLE
how to build rust project

### ISSUE THREAD

**Issue by harrydevnull** [drone/drone#1278]
I believe we can use custom images for build. I was trying to build a rust project using drone.io
https://drone.io/bitbucket.org/harrydevnull/prakaza/5
and repo is found under
https://bitbucket.org/harrydevnull/prakaza

it makes use of a custom docker image ` schickling/rust` is there anything which I am missing?

**Comment by bradrydzewski** [comment]
hi there, this issue tracker is for the open source Drone project. It is a different codebase / project than drone.io (which does not use Docker). You can use any Docker image with the open source project. Check out http://readme.drone.io/build/build.html for more info
