### ISSUE TITLE
Problem with BitBucket

### ISSUE THREAD

**Issue by janober** [drone/drone#1280]
hi,

wanted to try drone today in combination with BitBucket. Sadly did not have very much luck. Used the latest docker-container (0.4) and followed the instructions. First it seemed to work fine. After I pressed "Login" it displays me the repositories and when I then click on one, it tells me that it has to get activated first. So I press "Activate Now". That is when the problem starts. Because all I get then is the following error message:
```
Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved.
```

In the browser console I get:
```
http://localhost:8800/api/repos/janoberhauser/drone-test:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

and in Docker:
```
Error #01: Bad request
```

To be sure I really gave it all the access-rights there are. So that can not be the issue. Also was I totally unable to find any kind of third-party application access policy in BitBucket. I guess that is only in GitHub. So anybody any idea what is going wrong. Is there maybe something wrong with the container because it is just 19h old.

Thanks!

**Comment by bradrydzewski** [comment]
@janober do you have administrative rights to the repository in Bitbucket? Can you go to the repository settings screen in Bitbucket and manage keys in hooks? You must have admin access to the repository so that Drone can add a post-commit hook

**Comment by bradrydzewski** [comment]
also did you check the logs in Drone to see if there is additional details? run `docker logs` for your Drone container

**Comment by bradrydzewski** [comment]
also does your repository name include whitepsace or special characters that might be related to:
https://github.com/drone/drone/issues/761

**Comment by janober** [comment]
Hello Brad,

first thanks for the very fast answer!

It is a team account and created the OAuth Consumer directly in it. Also am I the admin so that should not be the problem. Created also a second one directly from the Admin user with the same result.

Do have the docker-container running interactively and `Error #01: Bad request` was the output I got.

Tried it with multiple repositories. Some where from the team some where directly from my account. None of them had white-spaces and always exactly the same issue.

**Comment by bradrydzewski** [comment]
I'll add some more debug statements so we can get more detail from the logs. I'm unable to re-produce on my end, but perhaps there is an edge case that isn't being considered.

**Comment by bradrydzewski** [comment]
Just pushed 970cf0e which adds some debugging and improved error messaging to the Bitbucket repository activation code. Can you download the latest image and let me know if the drone logs or http response contain additional useful information?

**Comment by janober** [comment]
Great, thanks a lot!

Not so sure if it is an edge-case or I am simply doing something wrong. Guess the later one is more probable...

Now with the new debugging information it is clear that the problem was the web-hook like you expected. The log output is:
ERRO[0023] unable to create hook  http://localhost:8800/hook?access_token=eyJh....u57U. Bad request 

However I tried it with two OAuth keys. One of the owner and one of the group which has Admin-Rights set for the repository. Both have all the rights set that can be set. So have no idea why it should have problems creating it.

**Comment by bradrydzewski** [comment]
@janober ah yes, I ran into this **exact** same issue when testing out the Bitbucket code. Bitbucket does not let you create a hook for `localhost`, since sending the hook to `localhost` would just send it to themselves.

Since Drone expects to receive `push` and `pull_request` hooks to trigger builds you will need to host Drone at a publicly accessible address (IP or domain name). If you are just testing locally you can use a service like [ngrok](https://ngrok.com/) to tunnel a public address to your personal computer.

**Comment by janober** [comment]
Ah ok, that explains that. Thanks a lot for your help! Have a nice weekend!
