### ISSUE TITLE
[UI-Bug] Adding user menu

### ISSUE THREAD

**Issue by EliasGabrielsson** [drone/drone#1281]
### Description:
In the add user popup (https://yourdomain.com/settings/people) a enter keystroke will close the popup without adding the user.

#### Use case:
* Click add user
* Write user name
* Pressing enter

*Whats happens:*
The pop-up close no user added.

*Whats should happen:*
The pop-up shall be closed and the user shall be added

**Comment by bradrydzewski** [comment]
this is resolved in 0.5
