### ISSUE TITLE
Add ability to cancel builds before they start

### ISSUE THREAD

**Issue by elia** [drone/drone#1284]
(ref #336)

**Comment by bradrydzewski** [comment]
we'll be re-designing the queue over the next few minor releases (to support #1195 and others). Once the queue is re-worked it should give us a bit more flexibility to cancel pending builds.

**Comment by blackghost1987** [comment]
What's the status of this re-work? I would like to request the same feature, it would be very helpful.

**Comment by bradrydzewski** [comment]
fixed in 1.0.0-rc.1
