### ISSUE TITLE
Environment section no longer does environment variable expansion

### ISSUE THREAD

**Issue by stevenpall** [drone/drone#1286]
We have an environment section that contains things like this:
```
  environment:
    - APP_PATH=$DRONE_DIR/..
    - PYTHONPATH=$APP_PATH
```
These variables in turn get used later in the build section. From my testing, `APP_PATH` (for example) is being set as a string literal ("$DRONE_DIR/..") as opposed to the corresponding path. As such, later commands that use the variable fail. Was this behaviour changed in 0.4?

Thanks!

**Comment by bradrydzewski** [comment]
@stevenpall these environment variables are injected at the Docker daemon level (vie -e) and therefore do not expand. If you want to expand the variables you'll need to create the environment variables as part of the build command:

```
build:
  commands:
    - export APP_PATH=$DRONE_DIR/..
    - export PYTHONPATH=$APP_PATH
```

**Comment by stevenpall** [comment]
Ah, I see. That works. Thanks!

**Comment by bradrydzewski** [comment]
great, I'll be sure to update the docs as well
