### ISSUE TITLE
GitHub inter-repo pull request and later push, triggers two builds

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1289]
If I create a pull request (inter-repo) and then later push more commits to my PR, it creates two concurrent builds. Anyway to prevent this, and just trigger the single `push` build without the `pull_request` build?

**Comment by macb** [comment]
:+1: 

I disabled the PR build for the time being for the project (all PRs are built of inter-repo branches any ways) to get around it.

**Comment by bradrydzewski** [comment]
@macb @nodesocket any thoughts on the desired behavior if we implement a fix? I was thinking:

1. if a push also has an open pull request (inter-repository) ignore. Only build the pull_request
2. if a push has a closed pull request (inter-repository) proceed with the build. This would effectively build when you click the `merge` button, in case you wanted to trigger any deployments on merge

**Comment by bradrydzewski** [comment]
merging this issue with #1980
