### ISSUE TITLE
ssh plugin should allow for a timeout option

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1290]
There should be a default timeout of 60 seconds, and you should be able to provide a custom value:

    timeout: 10

**Comment by bradrydzewski** [comment]
ah yes, like a TCP timeout in case the server is down?

**Comment by nodesocket** [comment]
Yeah, there might be a timeout option in the native go ssh binding?

**Comment by bradrydzewski** [comment]
yep, instead of using `ssh.Dial` we'll have to manually construct the ssh connection. There is an example `SSHDialTimeout` function here that we can use:
http://stackoverflow.com/questions/31554196/ssh-connection-timeout

**Comment by bradrydzewski** [comment]
let's move this issue to the ssh plugin repository at https://github.com/drone-plugins/drone-ssh

**Comment by tboerger** [comment]
Should be solved via https://github.com/drone-plugins/drone-ssh/pull/8/commits/f3b01e70fe560b6a827f74521f67fde520f0abf8 on 0.5
