### ISSUE TITLE
Try X-Accel-Buffering for Nginx SSE

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1293]
Seeing timeouts in nginx for the server sent events. This has to do with default timeouts by nginx. Some initial research has led me to the following stackoverflow article:
http://stackoverflow.com/questions/27898622/server-sent-events-stopped-work-after-enabling-ssl-on-proxy

It recommends adding this header:

```
c.Header("X-Accel-Buffering", "no");
```

Which would need to be added inside both of the http handlers in this file:
https://github.com/drone/drone/blob/master/controller/stream.go

cc @pirogoeth

**Comment by pirogoeth** [comment]
@bradrydzewski I'm going to do some testing to see if X-Accel-Buffering accomplishes the same thing as `proxy_read_timeout`. Will provide results soon!

**Comment by bradrydzewski** [comment]
@pirogoeth great, let me know. Just a heads up that the header may need to be set by Drone, and consumed by nginx, but not entirely sure

**Comment by pirogoeth** [comment]
@bradrydzewski it's not looking good so far, setting the header with `proxy_set_header` isn't fixing anything. From what I understand in the `x-accel` docs, it won't modify the read timeout at all, it just optimizes the way nginx receives and proxies data. So if that is the case, then even with `X-Accel-Buffering` set, nginx will still apply the default 60s timeout to the proxy connection and shut down the connection on idle. 

Also, peeking through the [older documentation](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ignore_headers) shows that setting `X-Accel-Buffering` is equivalent to setting `proxy_buffering` in the nginx config. I think the only way to fix this is through setting `proxy_read_timeout`.

**Comment by compressed** [comment]
Agreed. I tried this today and did not see any benefit. Once you have set `proxy_buffering off` then setting this header has no effectin nginx.

The agents will time out whenever the `proxy_read_timeout` value (default `60s`) is reached.

**Comment by bradrydzewski** [comment]
right now I'm streaming the logs from the agent to drone using a regular old http request, but will need to change this to websockets. Since I'm going to need to use websockets for the agent I'm going to replace the SSE with websockets as well ... no reason two have two different stream protocols

**Comment by compressed** [comment]
Oh I see. That sounds like a good idea. Nginx seems to behave much better with websockets as well, so this change may eliminate some of the flakiness with the log exchange between the agent and server that I've seen recently.

**Comment by bradrydzewski** [comment]
closing as 0.5 no longer uses SSE
