### ISSUE TITLE
Plugin output/logging/validation specification/api

### ISSUE THREAD

**Issue by thomasf** [drone/drone#1294]
It's probably a good idea to extend the drone-plugin-go package with some best practices functions which guides plugin developers how to output/log inside a plugin.

The log levels should be debug/info/error/fatal where debug is hidden by default and fatal automatically does a non 0 exit.

Some kind of special function/struct/... to output field validation errors should exist so output regardless of plugin looks the same.

**Comment by bradrydzewski** [comment]
tracking #1656
