### ISSUE TITLE
Docker Publish Fails

### ISSUE THREAD

**Issue by stevenpall** [drone/drone#1296]
When I try to create a new Docker image using the publish module upon build completion, I'm seeing the following:
```
[info] Pulling image plugins/drone-docker:latest
$ /usr/bin/docker -d
A username was not specified. Assuming anoynmous publishing.
$ /usr/bin/docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
$ /usr/bin/docker info
$ /usr/bin/docker build --pull=true --rm=true -f Dockerfile -t <repo>/<image>:<tag> .
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```
I'm wondering if this is related to the "Known Issues" section here: http://addons.drone.io/docker as the host system is CentOS 7 with XFS storage and using the devicemapper storage driver. That being said, based on the error, it seems more like the Docker socket isn't being mounted into this `plugins/drone-docker` container. Is that the way the drone-docker plugin works or am I misunderstanding the model? For reference, this is working on 0.3, however I'm specifying a non-local build host (which is incidentally the host system).

Thanks!

**Comment by bradrydzewski** [comment]
@stevenpall the Drone docker plugin runs Docker in Docker, and does not mount the host machine. This is new behavior in 0.4 because exposing the host machine's socket inside the build container has security implications.

Because it runs Docker-in-Docker it only works with a subset of the storage drivers

**Comment by bradrydzewski** [comment]
also there is a way to run in verbose mode (see the docs) which provides much more detail logs as to why Docker in Docker daemon doesn't start.

**Comment by bradrydzewski** [comment]
But ultimately with `devicemapper` as the storage driver this is going to fail as documented, so I'm not sure there is much I can do to help. If we find errors with supported aufs or overlay drivers we can re-open

**Comment by stevenpall** [comment]
Just a note to anyone else who encounters issues with the Docker plugin on CentOS: even if you're using the overlay storage driver, you'll need to explicitly specify it as the `storage_driver` in your project's `.drone.yml`:
```
publish:
  docker:
    storage_driver: overlay
```

**Comment by georgewhewell** [comment]
I encounter this problem using zfs storage driver on host. The docker-in-docker daemon will only start when I set `storage_driver: vfs`, but then hits https://github.com/drone/drone/issues/1352.

**Comment by djmaze** [comment]
@stevenpall  The need to manually specify the storage driver will hopefully be alleviated with https://github.com/drone/drone-exec/pull/29. 

@georgewhewell With zfs, that probably won't help unfortunately. I am not sure if zfs can be made to work with dind at all. Can you try `docker run --privileged docker:1.10-dind docker daemon -s <storage driver>` on that machine with any of `zfs`, `vfs`, `devicemapper`?
