### ISSUE TITLE
Bitbucket Repository not found for repo names with uppercases

### ISSUE THREAD

**Issue by nickalie** [drone/drone#1297]
Hello,

Tried to activate Bitbucket repo via freshly installed drone with no luck. Getting error:

> Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved. Repository username/my_repo_name not found

docker logs drone:

> [GIN] 2015/11/05 - 09:54:54 | 404 |  666.327173ms | 93.170.111.32:2829 |   GET     /repos/username/my_repo_name
time="2015-11-05T09:55:00Z" level=error msg="unable to create hook http://myhost.com:8000/hook?access_token=someaccesstoken. Repository username/My_RePo_Name not found"
[GIN] 2015/11/05 - 09:55:00 | 500 |  3.812021783s | 93.170.111.32:2829 |   POST    /api/repos/username/my_repo_name

I have administrative access to the repository and drone consumer permissions are:
Account:Email, Read
Team Membership:Read
Repositories:Read
Webhooks:Read and Write

My repo name has underscores and uppercases and looks like "My_RePo_Name". So I tried to activate another repo with name like "MyRepo" (without underscores) - no luck. And after that I was able to activate repo with name like "myrepo" (without underscores and uppercases). So looks like drone unable to activate BitBucket repos with uppercase letters. Is there a solution or workaround for that issue?

Thanks!

**Comment by bradrydzewski** [comment]
tracking #761
