### ISSUE TITLE
Malformed .drone.yml file should display error in UI

### ISSUE THREAD

**Issue by wolfgang42** [drone/drone#1299]
If the `.drone.yml` file for a commit is not correct YAML, an error is logged to the drone container's stderr but no build is created for the commit. This makes it not at all obvious what went wrong.

By way of contrast, when the `.drone.yml` file is correct YAML but is not the format expected by drone, a failed build is created with the following log:
> `[fatal] Error parsing the .drone.yml`

This is much more helpful as it immediately pinpoints what went wrong with the build, in the first place you look to see if anything went wrong with the build.

To reproduce:
1. Create an invalid `.drone.yml` file (for instance, put a key in the middle of an array). Commit the file and push it.
2. Wonder why the commit did not show up in the drone UI. Start debugging the GitLab server to see if the push failed somehow, or the post-commit hooks failed to run. Perhaps Sidekiq has gone funny?
3. After half an hour and a dozen dummy commits, decide that GitLab is working fine. Check the drone logs to see if the post-commit hook ever made it all the way to drone, and find the following line:
> time="2015-11-06T15:45:44Z" level=error msg="failure to calculate matrix for wfaust/Small-Label-Frontend. yaml: line 7: did not find expected '-' indicator"

**Comment by bradrydzewski** [comment]
agreed, let's track this under #672 which I've added to the 0.4.1 milestone since I agree it is really important
