### ISSUE TITLE
Drone LB ip in GIT

### ISSUE THREAD

**Issue by prashantchitta** [drone/drone#1305]
I have a drone server and I have created a LB(Load Balancer) ip for it. I have given that LB IP for GIT authorization callback url. Eventhough Drone auth works, when it tries to do a git clone, it fails with auth error.

```
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I believe its because when it tries to clone git, it sends the vm ip as part of request rather than LB ip. 
As a result, git not able to authorize it. Git would have authorized if it would have come from LB ip. But since outgoing traffic goes through vm/server and does not use LB, GIT is unable to authorize. Correct me if my understanding is wrong.

Is there any solution for it? Did anyone setup LB for drone server?

**Comment by bradrydzewski** [comment]
I'm closing this because it seems similar (or at least related) to #1302 based on the `git clone` error above
