### ISSUE TITLE
Bootstrap database in middleware

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1312]
I'm opening this issue to track problems when running migration scripts against a mysql database. If a migration fails half way through it is unable to re-start, leaving the database in an inconsistent state.

I'm partially addressing this in pull request https://github.com/drone/drone/pull/1311 which uses `IF NOT EXISTS` before creating any database objects. This makes it easier to run a migration script that only partially completed.

The above pull request, however, isn't full proof. Some migration scripts `ALTER TABLE ADD COLUMN` which does not support `IF NOT EXISTS`. So we need to understand why a migration script would fail half-way through the process.

**note** this issue is not meant for people upgrading from 0.3 to 0.4 ... please note the 0.3 database cannot be upgraded to 0.4 due to compatibility issues

**Comment by bradrydzewski** [comment]
@macb a few questions for you:

* what version of mysql are you running
* are you running mysql in a container? if yes, which image?
* are you running mysql on the same host
* are you connecting with the IP address?
* default configuration? or anything notable changes?

I'd like to try and setup an environment so that I can re-produce

**Comment by macb** [comment]
Sure @bradrydzewski:

1. percona 5.5
2. No, in this case it's installed locally.
3. Yep, installed on the same host.
4. It's connecting via the host's IP address.
5. Nothing notable aside from being `percona`. Otherwise the configuration is untouched.

I think I might actually have an idea why this is happening. I'm setting up the host with chef which fetches the image and creates a container using it. I think at some point it's actually killing off the original container (seemingly mid-migration) and starting a new one. The new one comes up but then fails to migrate since some tables exist.

**Comment by bradrydzewski** [comment]
@macb can you share any of the chef script? perhaps we could work through any of the kinks and offer an official chef recipe for people to use

**Comment by macb** [comment]
That's interesting. I'll have to see about open sourcing this provider. It's pretty simple since it's really just plugging together the `chef-docker` provider and some drone configuration:

The important action:
```ruby
      def action_create
        docker_service 'default' do
          tls false
          action [:create, :start]
        end

        docker_image new_resource.image_path do
          tag new_resource.image_tag
          read_timeout 300
          notifies :redeploy, docker_container_name
        end

        docker_container app_name do
          repo new_resource.image_path
          tag new_resource.image_tag
          port  "#{new_resource.host_port}:8000"

          env drone_env.map { |k,v| "#{k}=#{v}" }
          binds drone_binds.map { |k,v| "#{k}:#{v}" }

          restart_policy 'always'
          action :run_if_missing
        end

        # Without this env, hostport, and volume changes won't trigger a redeploy
        # of the container so we'll cache a representation of the env and when
        # that busts, it will redeploy.
        changes = {
          env: drone_env,
          host_port: new_resource.host_port,
          binds: drone_binds,
        }
        file "#{Chef::Config[:file_cache_path]}/drone.env" do
          content Digest::SHA256.hexdigest(changes.to_json)
          notifies :redeploy, docker_container_name
        end
      end
```

The 2 `redeploy`'s are the bits causing the issue I believe. On first run both the `docker_image` and the configuration cache file cause a redeploy. This gets de-duped but still results in a redeploy (which is a stop, remove, run).

**Comment by bradrydzewski** [comment]
@macb does the`docker_container` directive is execute a `docker run`. What happens if instead it performs a `docker create`? Perhaps then the `docker restart` will start the container for the first time?

**Comment by macb** [comment]
It does [this](https://github.com/someara/chef-docker/blob/master/libraries/docker_container.rb#L270-L280). I thought about having it _just_ create, then letting the redeploy bits handle starting it. Just hadn't had a chance to go down that road yet.

**Comment by bradrydzewski** [comment]
@macb I've considered bootstrapping the application on the first http request. This would solve this sort of problem since the migration wouldn't run until someone tried to access a url. This will involve some refactoring and will probably land in release 0.4.1 or later.

I did some research and in the short term we have to deal with some mysql limitations with rollback:

> Some statements cannot be rolled back. In general, these include data definition language (DDL) statements, such as those that create or drop databases, those that create, drop, or alter tables or stored routines.

So what about (and I realize this isn't ideal) adding some sort of `sleep` to the chef script to give it a buffer so that it doesn't try to stop the container before the migration is complete? Then when the above fix is in place, we should be all set

**Comment by bradrydzewski** [comment]
note we could also try *just* `create` as you mentioned and see if that fixes things. I just figured the `sleep` might give us an immediate hack and then put the ball back in my court for a permanent fix.

**Comment by macb** [comment]
Ya I arrived at the same conclusion about mysql rollbacks after investigating for a little bit. I can definitely give just `create` a try. I think that should solve my immediate problem. Either way it's not a big blocker for us upgrading our systems by any means. Just adds a small manual intervention if it happens to end up in that state (though I think the `create table if not exist` may solve some of that, haven't had a chance to use the new image).

**Comment by bradrydzewski** [comment]
**proposal:** instead of initializing the database in the `main` function of the application I propose we initialize in the middleware, when the first request is received. It would look something like this:

```Go
// one-time function to setup and load the store
once.Do(func() {
  store_, err = store.Load(driver, datasource) 
})

// if we couldn't load the database
if err != nil {
    c.String(500, "Unable to load database")
}

// add the store to the request context
store.Set(c, store_)
```

If starting the database fails we can show and error page instead of exiting the application, and perhaps even include a link to the documentation and known database issues. We could do the exact same thing for hooking up a remote repository (like GitHub).

Aside from solving the original issue that was logged here, it let's us display an error page instead of immediately exiting the system, which at present seems to confuse people when they first install Drone.
