### ISSUE TITLE
Wrong build author displayed for Github pull requests

### ISSUE THREAD

**Issue by adamstep** [drone/drone#1313]
We're using Drone to test pull requests within our Github organization. All build appear as being authored by the organization (edmodo) rather than the author of the pull request:

![repo_owner_name](https://cloud.githubusercontent.com/assets/1034502/11099967/35bfaba0-8863-11e5-9202-77c3e8926cc5.png)

I believe the issue is that that the build author is getting data from `hook.PullRequest.Head` instead of `hook.PullRequest.User`: https://github.com/drone/drone/blob/master/remote/github/github.go#L413

If this is indeed not working as intended, I'm happy to send a PR to fix the issue.

**Comment by bradrydzewski** [comment]
cc @donny-dont any chance you can verify a GitHub Enterprise pull request hook has a `user` object as a child of `pull_request`?

```
{
  "number": 1310,
  "pull_request": {
    "user": {
      "login": "bradrydzewski",
      "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/75556?v=3",
```

@adamstep I'm good with the change once we verify it is compatible with GitHub Enterprise. Thanks!

**Comment by donny-dont** [comment]
@bradrydzewski I see that structure in GHE :+1:

**Comment by bradrydzewski** [comment]
@donny-dont thanks! @adamstep if you submit a PR I'll get it merged right away, thanks so much!
