### ISSUE TITLE
Error parsing the .drone.yml

### ISSUE THREAD

**Issue by rfink** [drone/drone#1317]
I've parried it down to the smallest possible file I can think of and still get the error.  I don't know how to enable debugging, so I have no idea how to start figuring out where I'm going wrong.  Example file:

clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  commands:
    - echo "TEST"

Since the drone docker images repo was deleted, my old version wasn't able to access them anymore, breaking my build process, so I had to upgrade both drone and gitlab.  Please help.

**Comment by bradrydzewski** [comment]
have you tried a yaml linter online? also note that the yaml formatting was retained in your above message

**Comment by rfink** [comment]
I just tried http://www.yamllint.com, and it checked out

**Comment by bradrydzewski** [comment]
can you include the following

* error message your receive
* additional details from logs if applicable
* formatted version of your yaml file

**Comment by rfink** [comment]
Sure, thanks.

[fatal] Error parsing the .drone.yml

[GIN] 2015/11/11 - 23:51:18 | 200 |   167.43966ms | 172.17.0.1:46103 |   POST    /api/hook
time="2015-11-11T23:51:18Z" level=info msg="preparing container drone_build_16_job_16"
time="2015-11-11T23:51:19Z" level=info msg="preparing container drone_build_16_notify"
time="2015-11-11T23:51:20Z" level=info msg="Notification container drone_build_16_notify exited with 1"
time="2015-11-11T23:51:20Z" level=info msg="[fatal] Error parsing the .drone.yml\n"

```
clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  commands:
    - echo "MERF"
```

**Comment by bradrydzewski** [comment]
@rfink can you add `debug: true` to your yaml?

```
clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  commands:
    - echo "MERF"
```

**Comment by rfink** [comment]
Sure, here is the new output:

[debug] Using workspace /drone/src/github.com/drone/drone
[debug] Plugin plugins/drone-git:latest is not in the whitelist
[fatal] Error parsing the .drone.yml

**Comment by bradrydzewski** [comment]
this is the problem:

```
[debug] Plugin plugins/drone-git:latest is not in the whitelist
```

can you provide more details how you configured drone?

**Comment by rfink** [comment]
Sure, I followed the instructions to install the docker image:

sudo docker run --volume /var/lib/drone:/var/lib/drone --volume /var/run/docker.sock:/var/run/docker.sock --env-file /etc/drone/dronerc --restart=always --publish=9090:80 --detach=true --name=drone drone/drone:0.4

My /etc/drone/dronerc looks as follows:

#!/bin/bash

# server configuration

SERVER_ADDR=":80"
#SERVER_CERT=""
#SERVER_KEY=""

# database configuration

DATABASE_DRIVER="sqlite3"
DATABASE_CONFIG="/var/lib/drone/drone.sqlite"

# remote configuration

CLIENT="" # oauth2 client. REQUIRED
SECRET="" # oauth2 secret. REQUIRED

REMOTE_DRIVER="gitlab"
REMOTE_CONFIG="http://gitlab.<internal_domain>?client_id=<client_id>&client_secret=<client_secret>&clone_mode=oauth"

# docker configuration

DOCKER_HOST="unix:///var/run/docker.sock"
#DOCKER_CERT=""
#DOCKER_KEY=""
#DOCKER_CA=""

# plugin configuration

PLUGIN_FILTER="plugins/*"

**Comment by bradrydzewski** [comment]
@rfink are you using this with `--env-file`? The docker `--env-file` doesn't support quoted environment variables:

```
-PLUGIN_FILTER="plugins/*"
+PLUGIN_FILTER=plugins/*
```

**Comment by rfink** [comment]
Yes, is there another option I should be using?

**Comment by bradrydzewski** [comment]
nope, the `--env-file` is correct, just remove quotes from your variables as seen below:

```diff
-PLUGIN_FILTER="plugins/*"
+PLUGIN_FILTER=plugins/*
```

**Comment by rfink** [comment]
Wow man, I think that worked.  Thank you so much, you are a life saver.  I was drowning over here :|

**Comment by rfink** [comment]
One more question, previously in the .drone.yml file I was able to specify which branches to build from.  Is that possible with the new format?

**Comment by donny-dont** [comment]
@rfink yep it is you can use a `when:` thats in the docs. Also theres a gitter channel available as well to get support.

**Comment by bradrydzewski** [comment]
@rfink yes, that should behave similar to 0.3:

```
branches:
  - master

build:
 image: foo
 commands:
   - echo foo
```

as Don mentioned feel free to hit up https://gitter.im/drone/drone ... tons of people there that can help and answer questions

looks like we're good here so I'll mark as closed. glad that worked for you!
