### ISSUE TITLE
re-exec errors when pulling images

### ISSUE THREAD

**Issue by macb** [drone/drone#1320]
[info] Pulling image our.docker.index/org/go:latest
[info] Pulling image our.docker.index/org/go:latest
[error] Error pulling our.docker.index/org/go:latest. Error pulling image (latest) from our.docker.index/org/go:latest, Untar re-exec error: exit status 1: output: unexpected EOF

**Comment by bradrydzewski** [comment]
@macb are you able to run `docker pull our.docker.index/org/go:latest` on the machine?

**Comment by macb** [comment]
A `restart` seems to work to get it. At least it did one of the times.

**Comment by bradrydzewski** [comment]
I'm not sure if this is related:
https://github.com/docker/docker/issues/14792

**Comment by macb** [comment]
Maybe. Are there timeouts associated with the pulls for builds?

**Comment by bradrydzewski** [comment]
there are no timeouts within Drone, but Drone pulls an image by invoking the `/images/create?fromImage=foo` Docker daemon endpoint. Docker takes over from there. So it is possible that Docker enforces a timeout.

it is possible to get more details by running `docker events` on the host machine. This will begin streaming a lot of everything happening in the Docker daemon. There also might be additional detail in `/var/log/upstart/docker.log`.

Also, which version of Docker are you running?
