### ISSUE TITLE
compose services could cause indeterminate build results

### ISSUE THREAD

**Issue by macb** [drone/drone#1321]
As an example I was running a test suite with `mysql:5.5` running, however I didn't set `MYSQL_ROOT_PASSWORD` so the container died immediately after starting it. But the test suite continued going until it ran into tests that expected `mysql` to be running.

It seems like if a build is expecting a service to be active, if at any point during the build that service dies, the build should probably be stopped/failed.

**Comment by bradrydzewski** [comment]
Fixed in master. now display individual step failures including services

![screen shot 2017-04-05 at 7 07 08 pm](https://cloud.githubusercontent.com/assets/817538/24700759/20432582-1a33-11e7-9c36-36470833ee9d.png)
