### ISSUE TITLE
Add DRONE_WORKSPACE environment variable for interpolation

### ISSUE THREAD

**Issue by macb** [drone/drone#1322]
In drone 0.3 `DRONE_BUILD_DIR` (now called `DRONE_DIR` in 0.4) was available when setting the `environment` for the build. However that doesn't seem to be the case anymore as it's no longer a substitution variable.

We could move those lines into the `commands` as `export` statements, but I was wondering if that was intentional and if not would it be worth getting `$$DRONE_DIR` or `$$BUILD_DIR` available as a substitution variable?

**Comment by mvdan** [comment]
@bradrydzewski where would a patch for this go? I cannot seem to find where these build substitution variables are set/defined.

**Comment by bradrydzewski** [comment]
Note from https://github.com/drone/drone/issues/2466

> The primary reason DRONE_WORKSPACE is not available is that the values in the yaml are substituted __before__ the yaml is parsed. This leads to a chicken-an-egg program, because we need to parse the yaml if we want to extract the workspace for interpolation.

**Comment by bradrydzewski** [comment]
fixed

**Comment by pnovotnak** [comment]
@bradrydzewski what does "fixed" mean? It doesn't appear that I can use this variable and none of the others are present

**Comment by bradrydzewski** [comment]
It is available if you are using the latest runner:
https://github.com/drone-runners/drone-runner-docker/blob/master/engine/compiler/compiler.go#L230:L232

**Comment by bradrydzewski** [comment]
ah sorry if I misread, are you looking to use this variable for _interpolation_?  If yes, this is not possible because interpolation happens _before_ the yaml is parsed, and the workspace can only be known _after_ the yaml is parsed.  The workspace, however, is available as an environment variable at runtime, inside the container.
