### ISSUE TITLE
Builds stop with [info] Cancel request received, killing process

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1325]
Not sure exactly what causes `[info] Cancel request received, killing process`.

Where does a notify come from? Does it have to come from inside a build container? There is not much in the logs to see other than just:

```
time="2015-11-16T13:00:42Z" level=info msg="closed event stream" 
[GIN] 2015/11/16 - 13:00:42 | 200 | 1m7.560092745s | 10.10.31.0:45388 |   GET     /api/stream/<organization/reponame>
time="2015-11-16T13:00:43Z" level=info msg="closed event stream" 
[GIN] 2015/11/16 - 13:00:43 | 200 | 1m7.520039973s | 10.10.95.0:46532 |   GET     /api/stream/<organization/reponame>
[GIN] 2015/11/16 - 13:00:44 | 200 | 1m1.754982222s | 10.10.84.0:54234 |   GET     /api/stream/<organization/reponame>/12/1
time="2015-11-16T13:00:46Z" level=info msg="preparing container drone_build_13_notify" 
```

Usually a build status is green when that happens.

**Comment by bradrydzewski** [comment]
It comes from the build container being shutdown un-expectedly. This could happen because someone hits the cancel button on the build, or the operating system is trying to kill your container (OOM, etc)

https://github.com/drone/drone-exec/blob/c9e59c4f91e93cc1540e86a02451ea224b47de69/main.go#L206

**Comment by vaijab** [comment]
@bradrydzewski that's exactly what was happening. I increased the timeout to 30 minutes an the problem went away. Thanks!
