### ISSUE TITLE
Main .drone.yml from multi-branch git repos

### ISSUE THREAD

**Issue by gbergere** [drone/drone#1327]
Hello,

I'm a new user of Drone.io but I find it really interesting and able to do great things. However there is still some concern about working...
- We have several .drone.yml (yes because so much branches) so which one is the main ? If someone break .drone.yml in a branch, could it be a problem for drone.io master branch ? How is it working ?
- My second is about working, because I would like to build and push docker image so I would be able to run some script out of docker ? Does it is possible ? My main concerns is I need some tools for deployment but I don't want them in my docker images so I need one to build another... Do I need to use docker in docker ?

Cheers and thanks for this great CI Software !
Geo

**Comment by bradrydzewski** [comment]
> We have several .drone.yml (yes because so much branches) so which one is the main ? If someone break .drone.yml in a branch, could it be a problem for drone.io master branch ? How is it working ?

when Drone executes a build it retrieves the `.drone.yml` file for that commit / branch. Therefore if you make a change to the `.drone.yml` in a branch it does not impact master.

> My second is about working, because I would like to build and push docker image so I would be able to run some script out of docker ? Does it is possible ? 

We have a plugin for building and publishing Docker containers. See http://addons.drone.io/docker/

If you build requires extra tools or software as part of you should install them in your build container. You can do so by running apt-get install (for example) during your build, or you can provide your own custom build image with everything you need pre-installed.

for example let's say you need `imagemagick` as part of your build. You could install on every build into your build container:

```
build:
  image: php
  commands:
    - apt-get install imagemagick libmagickcore-dev
    - composer install
    - phpunit
```

or you could publish an image to the registry with `imagemagick libmagickcore-dev` pre-installed. You could then use this image in your build: 

```
build:
  image: gbergere/php-magick
  commands:
    - go build
    - go test
    - go do something else
```

You can read more about the build process here: http://readme.drone.io/build/

> My main concerns is I need some tools for deployment but I don't want them in my docker images so I need one to build another... Do I need to use docker in docker ?

Docker in Docker should not be required. You should execute you build, tests and bundle your application in the `build` section of the yaml. Then use the `publish` or `deploy` plugins to release your application. In your case, it sounds like you'll want to use the Docker plugin for this.

> Cheers and thanks for this great CI Software !

Thanks! if you don't mind use our [chat room](https://gitter.im/drone/drone) room for these sort of questions so we can reserve the issue tracker for bugs. Cheers!
