### ISSUE TITLE
Cancel action does not work when container is already stopped

### ISSUE THREAD

**Issue by martinsefcik** [drone/drone#1328]
Cancel action does not work when build container is already stopped and build stays in 'in progress' state and there is no way how to cancel it. 

docker.log
```
ERRO[3372] Handler for POST /v1.15/containers/drone_build_35_job_85/stop returned error: Container already stopped
ERRO[3372] HTTP Error                                    err=Container already stopped statusCode=304
```

Version: 0.4

**Comment by bradrydzewski** [comment]
if the build container is stopped is there anything to cancel? There is a window where the build is still in-progress, but the build container is stopped, the environment is being cleaned up, and notifications are being sent out. Is this the case here?

**Comment by martinsefcik** [comment]
Yes, it's this case. There is nothing to cancel, but build is always "In progress" state and there is no way using UI how to move it to failed state. I think it happened when build was running and drone was restarted at same time.

It should be related to #1195 and your workaround mentioned here https://github.com/drone/drone/issues/1195#issuecomment-157809368 could resolve that issue.

**Comment by bradrydzewski** [comment]
ah ok, yes restarting Drone while builds are running puts the system in an inconsistent state. The plan is to re-build the queue when Drone restarts so that it can pick up exactly where it left off. Let's track this under https://github.com/drone/drone/issues/1195

thanks for clarifying
