### ISSUE TITLE
Provide a button to stop pending builds

### ISSUE THREAD

**Issue by DanySK** [drone/drone#1329]
Currently, the `[Cancel Build]` button only appears when the build is marked as started. It would be great to be able to stop (or remove from queue) also the pending builds.

Note that it may currently happen that for some reasons a build gets stuck before it has actually started (see e.g. [this build](https://drone.io/github.com/DanySK/SmarTrRR/16)): in this case, there is no way to cancel it.

**Comment by bradrydzewski** [comment]
@DanySK I'll escalate your issue related to drone.io and follow up to ensure it gets resolved. Since the drone.io codebase and open source codebase are completely different, and this issue doesn't apply to the open source codebase, I'm going to close the issue

**Comment by letalvoj** [comment]
@bradrydzewski it seems that this issue is still valid (running `drone/drone:0.8`), is it going to get resolved anytime soon?

**Comment by letalvoj** [comment]
ok I found https://github.com/drone/drone/issues/1284
