### ISSUE TITLE
'fail to parse token for foo/bar. signature is invalid' with gitlab

### ISSUE THREAD

**Issue by kri5** [drone/drone#1332]
Using gitlab.com, and a freshly installed drone, after authorizing drone to access gitlab, and the 'Drone CI' service on gitlab being empty, when i trigged the 'Activate Now' button on Drone, it fullfill the 'Drone CI' service form on gitlab, but when i hit 'Test Settings' on gitlab, It leads to the error 'fail to parse token for foo/bar. signature is invalid' (on the Drone side).

Unfortunatly, i have no access to any kind of logs on gitlab.com, as it is an hosted service.

Any Ideas?

**Comment by bradrydzewski** [comment]
@kri5 when drone add a hook to GitHub / GitLab / Bitbucket / etc it adds an `access_token` query parameter, which is used to authorize hook requests. This token is verified when the hook is received by Drone and based on the above message seems to be failing:
https://github.com/drone/drone/blob/master/controller/hook.go#L61

The token verification is used by all providers, including GitHub, Bitbucket and Gogs and there are no known issues with those systems. I'm not sure what changed with GitLab, but unfortunately Drone no longer has a GitLab maintainer. If you are interested in helping troubleshoot and get to the bottom of why it is failing it would be greatly appreciated.

**Comment by martinsefcik** [comment]
I think that new version 8.2 RC was deployed on gitlab.com and there was one change in drone service in 8.2:
https://gitlab.com/gitlab-org/gitlab-ce/commit/5aa142212fc4fb7765aad801c1a25696fb752fba
Maybe this is the reason why it is not working anymore.
I didn't try it yet. I have my own instance of Gitlab currently on 8.1 version and It's working correctly with Drone 0.4. 
I'm planning to look at it in the following days and help with Gitlab integration.

**Comment by martinsefcik** [comment]
@kri5 Are you getting error 500 on gitlab.com when you hit 'Test settings' ?

**Comment by kri5** [comment]
@martinsefcik On a newly configured project, i get 500 when i hit the test settings button on gitlab.com

**Comment by stanhu** [comment]
Fix is available here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1856

Posted as an 8.2 regression. Will hopefully be able to get it in before the release.

**Comment by martinsefcik** [comment]
I think this can be closed.
Gitlab 8.2 was released and it's working.

**Comment by kri5** [comment]
@bradrydzewski @martinsefcik Works for me. Gitlab.com runs on 8.2 now, and i have no more issues.
