### ISSUE TITLE
Drone does not report .drone.yml syntax errors back to user

### ISSUE THREAD

**Issue by tooda02** [drone/drone#1337]
If there is a syntax error in .drone.yml, such as `Error #01: yaml: line 57: found a tab character that violate indentation`, the build never gets to the Drone UI.  The only place the error appears is in the Drone server log.   Users without access to the log have no idea why their commit didn't trigger a build.

**Comment by bradrydzewski** [comment]
hey there, yes, definitely need to fix this. Let's track this under issue #672
