### ISSUE TITLE
Drone needs a way to force refresh of an image (e.g plugin or build)

### ISSUE THREAD

**Issue by tooda02** [drone/drone#1340]
Drone appears to keep a Docker image cache.  This is beneficial for performance, but is a problem when a plugin or a build box image has been updated and Drone continues to use the old version.  There needs to be some way to ask Drone to remove an image from its cache, either through the UI or REST API.

**Comment by bradrydzewski** [comment]
@tooda02 plugins always auto-upgrade. Build or compose images can force upgrade by adding the `pull` option in the yaml:

```
build:
  image: foo
  pull: true
```

In terms of image buildup on the machine, we do plan to add some sort of `PRE_BUILD` and `POST_BUILD` plugin that executes a generic container on the host machine when the build completes. We won't provide a solution for cleanup, but will will provide the capability to launch a post-build container. You can see more about the discussion here:
https://github.com/drone/drone/issues/1193#issuecomment-150843153

If you don't mind let's use Gitter for these sort of questions. thanks!!

> Contributions, questions, and comments are welcomed and encouraged. Drone developers hang out in the drone/drone room on gitter. We ask that you please post your questions to gitter before creating an issue.
