### ISSUE TITLE
understanding how to integrate drone.io build bot feedback into PR commenting on bb (bit bucket)

### ISSUE THREAD

**Issue by cartazio** [drone/drone#1342]
1) to what extent is there support for that work flow already? (or would i need to help upstream a wee bit of work? :) )
2) am i correct in thinking that i'll need to create a "drone_CI_Bot" bb account so it can comment on any PR with the current build status if applicable (given my understanding of the bb api)

this seems to not be a work flow / use case thats articulate directly in any the extent (and generally lovely) documentation, and if its currently a missing feature, i'm open to trying to do some leg work to make it happen. (I want to push a team i'm on into doing a code review/PR/CI heavy work flow, and this is one of the last missing steps)

**Comment by bradrydzewski** [comment]
@cartazio first step is to enable pull request testing for Bitbucket. See #597

Second step is to create a plugin for commenting on Bitbucket pull requests. Anyone can extend Drone by creating a custom plugin, see http://readme.drone.io/plugin/

Please note that this open source project and drone.io (the service) do not share the same codebase and are different projects. So if you are looking for this feature in drone.io you might want to make the feature request in user voice http://drone.uservoice.com/forums/176976-feedback-for-drone-io

**Comment by bradrydzewski** [comment]
I'm going to close this in favor of #597

Feel free to create a notification plugin for commenting on Bitbucket pull request and submit for inclusion in our plugin index at http://readme.drone.io/plugins/
