### ISSUE TITLE
Unable to load user repositories when database is MySQL

### ISSUE THREAD

**Issue by asosso** [drone/drone#1353]
I've an issue using drone 0.4.0 with MySQL (or MariaDB) database.

I can't get user repositories:

```
Request URL:https://drone.mynetwork.local/api/user/repos
Request Method:GET
Status Code:500 OK
```

Drone log:

`[GIN] 2015/11/26 - 10:08:38 | 500 |  2.738084883s | MYIPADDRESS |   GET     /api/user/repos`

But remote repositories work well!

```
Request URL:https://drone.mynetwork.local/api/user/repos/remote
Request Method:GET
Status Code:200 OK
```

```json
[
    {
        "owner": "devops",
        "name": "docker-compose",
        "full_name": "devops/docker-compose",
        "avatar_url": ""
    }
]
```

My database configuration with MySQL 5.7 or MariaDB 10

```
DATABASE_DRIVER: mysql
DATABASE_CONFIG: root:mypassword(myhostname:3306)/mydatabase?parseTime=true
```

Charset is `latin1_general_ci` (#1323)

### Sqlite example (it works)

Drone works fine with the same configuration, but sqlite database:

```
Request URL:https://drone.mynetwork.local/api/user/repos
Request Method:GET
Status Code:200 OK
```

```json
[
    {
        "id": 1,
        "owner": "devops",
        "name": "docker-compose",
        "full_name": "devops/docker-compose",
        "avatar_url": "",
        "link_url": "https://git.mynetwork.local/devops/docker-compose",
        "clone_url": "https://git.mynetwork.local/devops/docker-compose.git",
        "default_branch": "master",
        "timeout": 60,
        "private": true,
        "trusted": false,
        "allow_pr": true,
        "allow_push": true,
        "allow_deploys": false,
        "allow_tags": false
    }
]
```

Default sqlite database configuration

```
DATABASE_DRIVER: sqlite3
DATABASE_CONFIG: /var/lib/drone/drone.sqlite
```

**Comment by bradrydzewski** [comment]
@asosso we run our test suite against a `mysql:5.6.27` on every commit and haven't seen any issues. Perhaps you can run the test suite against your particular database setup and report back? This is how we run our tests:

```
DATABASE_DRIVER="mysql" DATABASE_CONFIG="root@tcp(127.0.0.1:3306)/test?parseTime=true" go test github.com/drone/drone/store/datastore
```

If you are able to provide an error message and recommended fix I'm happy to patch the code. Since Drone is only one full time person (me) I'm not always able to test every single database version or configuration, and therefore rely heavily on help from individuals such as yourself. Thanks!

**Comment by asosso** [comment]
I've tested [0.4.0 branch](https://github.com/drone/drone/tree/0.4.0) with MariaDB 10.0.20 and MySQL 5.6.27: same issue. 
It works on master branch, I should probably use it.

#### Repo 

```
 1 tests failed: 

  1) Repo Should Get a Repo List:

    false expected false to be truthy
    /go/src/github.com/franela/goblin/goblin.go:271 (0x633db4)
    /go/src/github.com/franela/goblin/assertions.go:50 (0x62f403)
    /go/src/github.com/drone/drone/store/datastore/repos_test.go:117 (0x52f194)
    /go/src/github.com/franela/goblin/goblin.go:186 (0x633b2d)
```

#### User

```
 1 tests failed: 

  1) User Should get the Build feed for a User:

    false expected false to be truthy
    /go/src/github.com/franela/goblin/goblin.go:271 (0x633db4)
    /go/src/github.com/franela/goblin/assertions.go:50 (0x62f403)
    /go/src/github.com/drone/drone/store/datastore/users_test.go:215 (0x533897)
    /go/src/github.com/franela/goblin/goblin.go:186 (0x633b2d)
```

This error appears in drone log

```
drone_1 | time="2015-11-30T09:38:29Z" level=error msg="Failure to get repository list for MY_USERNAME. Error 1054: Unknown column '$1' in 'where clause'." 
```

**Comment by bradrydzewski** [comment]
@asosso 0.4.0 branch was merged into master a few weeks and should be deleted. I'll do that today. It sounds like I can close this issue, but we can always re-open if needed.
