### ISSUE TITLE
GitLab repositories with long names cannot be activated

### ISSUE THREAD

**Issue by gjtempleton** [drone/drone#1354]
On attempting to activate a GitLab repository with long full repo names drone gives the following error:

`Unable to activate this repository. You must have administrative access to this repository. Also, please check the third-party application access policy to ensure Drone is approved. *Gitlab.buildAndExecRequestRaw failed: <500> ...`

**Comment by bradrydzewski** [comment]
@gjtempleton we either log or return the full error message for every failure path when activating a repository https://github.com/drone/drone/blob/master/controller/repo.go#L21

could you do me a favor and look at the drone logs and paste them in the issue? Also, can you look at the http request (using chrome devtools for example) and paste an error in the response into this issue as well?

there are four places in the code that can fail with a 500 error, so hopefully getting logs and response message will help pinpoint what failed and why.

**Comment by gjtempleton** [comment]
I only seem to be getting the Gin logs, but from Docker logs:
`[GIN] 2015/11/26 - 16:48:53 | 404 |   198.67296ms | 10.201.116.101 |   GET     /repos/georges/thisisaveryveryverylongnameforaproject`

`[GIN] 2015/11/26 - 16:48:55 | 500 |  746.375991ms | 10.201.116.101 |   POST    /api/repos/georges/thisisaveryveryverylongnameforaproject`

HTTP Request fails with this response: 
`*Gitlab.buildAndExecRequestRaw failed: <500> http://git.****.**********.*****/api/v3/projects/data-acquisition-tooling%2Fdynamo_job_manager/services/drone-ci?drone_url=http%3A%2F%2Fdrone.*******.aws.*******.com&enable_ssl_verification=true&token=....`

Hopefully that's enough.

**Comment by bradrydzewski** [comment]
I presume, based on the issue title, that you are able to add repositories to GitLab with short names? If GitLab is returning a 500 response code perhaps it is an issue with GitLab, since Drone doesn't handle short names any differently than long names ...

**Comment by Bugagazavr** [comment]
Gitlab services URL has varchar(255) limit, gitlab can't save full URL to your repo in drone, i will try to send PR with raised limit to gitlab soon

**Comment by gjtempleton** [comment]
Well that explains it. We'd begun to suspect that might be the case. Thanks for letting me know @Bugagazavr We'll try to come up with a workaround for now.

Closing the issue.

**Comment by Bugagazavr** [comment]
@gjtempleton https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1940 if this will be merged in 1-7 december this will be released in 8.3
