### ISSUE TITLE
"Invalid redirect_uri" error when connecting to Bitbucket

### ISSUE THREAD

**Issue by greggilbert** [drone/drone#1355]
I'm running Drone locally (to test) and have ngrok forwarding to the Docker container. Hitting http://abc123.ngrok.io redirects to `/login` as expected. Per [the documentation](http://readme.drone.io/setup/bitbucket.html), I set the Bitbucket Callback URL to `http://abc123.ngrok.io/activate`. Connecting through login, though, I get an `Invalid redirect_uri` error from Bitbucket.

Any idea what's going wrong? Is `/activate` still the proper endpoint? The Docker logs show:

`[GIN] 2015/11/26 - 18:59:58 | 303 |     107.009µs | 192.168.99.1:49895 |   GET     /authorize`

Not sure if that helps. Thanks!

**Comment by bradrydzewski** [comment]
@greggilbert the redirect endpoint is `/authorize` and not `/activate` ... the docs seem to be up to date

**Comment by greggilbert** [comment]
...wow, I can't read. Sorry about that. :[

**Comment by bradrydzewski** [comment]
no worries, happens to the best of us :)

if you hit any other issues feel free to jump in the gitter room for help https://gitter.im/drone/drone
