### ISSUE TITLE
Adding hook to gogs misconfigures hook

### ISSUE THREAD

**Issue by mkaito** [drone/drone#1357]
Automatically adding a hook to a gogs repo seems to use the slack format (instead of the gogs format), which causes drone to throw an `index out of range` error. Manually adding the hook with the given URL seems to work.

**Comment by bradrydzewski** [comment]
@mkaito I'm not sure I understand the issue -- I'm not sure what the Slack format is. Drone is tested with Gogs `0.6.16.1022` and we are able to successfully add hooks. We use the official Gogs Go client to add hooks. Perhaps you can provide more detail (like logs and error messages from the Drone logs) as well as Gogs version and Drone version?

**Comment by thetooth** [comment]
I'm new to both Gogs and Drone, I'm having a similar issue however the error message is a 404.

When I activate a repo a web hook is installed on Gogs for: https://ci.ameoto.com/hook?access_token=???, however if you push to the repo the hook runs but is met with a 404 from Drone. Navigating to this link confirms it, is this URL incorrect or have I messed up along the way?

Drone: 0.4
Gogs: 0.7.22.1125

**Comment by bradrydzewski** [comment]
@thetooth please provide information from the Drone logs. Every single error path is logged, and will reveal the root cause of the error.

**Comment by thetooth** [comment]
http: multiple response.WriteHeader calls time="2015-11-27T20:25:28Z" level=error msg="failure to find repo Ameoto/auth from hook. sql: no rows in result set"
    [GIN] 2015/11/27 - 20:25:28 | 404 |   14.602952ms | 108.162.208.164 |   POST    /hook
    Error #01: sql: no rows in result set

I used the sample configuration for SQLite:
    DATABASE_DRIVER=sqlite3
    DATABASE_CONFIG=/var/lib/drone/drone.sqlite
No errors during activating either, one thing of note is this repo belongs to an organisation and not a user, but I wouldn't expect this to be an issue.

**Comment by bradrydzewski** [comment]
is `Ameoto/auth` in the Drone database? This indicates the `SELECT * FROM repos WHERE repo_full_name='Ameoto/auth'` is coming back with no results.

**Comment by thetooth** [comment]
sqlite> select * from repos WHERE repo_full_name='Ameoto/auth';
    sqlite> select * from repos;
    repo_id|repo_user_id|repo_owner|repo_name|repo_full_name|repo_avatar|repo_link|repo_clone|repo_branch|repo_timeout|repo_private|repo_trusted|repo_allow_pr|repo_allow_push|repo_allow_deploys|repo_allow_tags|repo_hash|repo_scm
    3|1|Ameoto|Auth|Ameoto/Auth|https://git.ameoto.com/avatars/4|https://git.ameoto.com/Ameoto/Auth|https://git.ameoto.com/Ameoto/Auth.git|master|60|0|0|1|1|0|0|???|git

Ahhhh, so repo name is being converted to lowercase making the query fail. I'll run another push since I deleted the build history to see who is sending the wrong string.

**Comment by bradrydzewski** [comment]
yes, seems like there is some case sensitivity issues here. I can confirm that Drone doesn't manipulate case, so perhaps there is an inconsistency in the Gogs message? You should be able to get the hook message sent to Drone via the repository settings > hooks screen in Gogs. If you can paste into the issue  we can investigate further.

**Comment by thetooth** [comment]
```
{
  "secret": "???",
  "ref": "refs/heads/master",
  "before": "c95f0a336db7dc64b9a505335ada2bdd2c640209",
  "after": "94dd5583082b1b52ead31b7e5cc0644fe174134b",
  "compare_url": "https://git.ameoto.com/Ameoto/Auth/compare/c95f0a336db7dc64b9a505335ada2bdd2c640209...94dd5583082b1b52ead31b7e5cc0644fe174134b",
  "commits": [
    {
      "id": "94dd5583082b1b52ead31b7e5cc0644fe174134b",
      "message": "Push test\n",
      "url": "https://git.ameoto.com/Ameoto/Auth/commit/94dd5583082b1b52ead31b7e5cc0644fe174134b",
      "author": {
        "name": "Jeff Jenner",
        "email": "thetooth@ameoto.com",
        "username": "thetooth"
      }
    }
  ],
  "repository": {
    "id": 3,
    "name": "auth",
    "url": "https://git.ameoto.com/Ameoto/Auth",
    "description": "JWT based authentication server.",
    "website": "",
    "watchers": 1,
    "owner": {
      "name": "Ameoto Systems Inc.",
      "email": "",
      "username": "Ameoto"
    },
    "private": false
  },
  "pusher": {
    "name": "Jeffrey Jenner",
    "email": "thetooth@ameoto.com",
    "username": "thetooth"
  },
  "sender": {
    "login": "thetooth",
    "id": 1,
    "avatar_url": "https://git.ameoto.com///1.gravatar.com/avatar/96907efd21d43969ecc8f924611edb76"
  }
}
```
You can see the problem is in the repository/name field, perhaps you could derive the path from the URL?

**Comment by mkaito** [comment]
My issue seems to be on the gogs side, where gogs randomly decides to send a slack-format JSON payload, which doesn't include any of the information that drone needs.

**Comment by bradrydzewski** [comment]
@mkaito gotcha, thanks for clarifying. The gogs community is awesome and I'm sure if you open an issue with them they will be able to assist.

@thetooth I'm thinking we open an issue request with Gogs to fix instead of implementing a workaround in Drone. I'm sure others in the Gogs community would benefit from this fix as well.
