### ISSUE TITLE
Disabling iptables in Docker results in slow and empty dashboard

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#1358]
Due to Docker messing with `iptables` all Docker containers circumvent any rules set by the `ufw` firewall and are publicly visible on my Ubuntu 14.04 machine. To make Docker not punch holes in your firewall you can set

    DOCKER_OPTS="--iptables=false"

in `/etc/defaults/docker`.

However when I do this the Drone dashboard is empty (no repos shown) and terribly terribly slow.

Disabling this setting brings back all repos and the page becomes fast again.

**Comment by bradrydzewski** [comment]
We use the low level `http` package in Go to listen on a TCP port and to make outbount `http` requests to GitHub. This seems like it would be an issue with Docker or with the Go standard library, no?

**Comment by nils-werner** [comment]
I couldn't say. The website is still accessible and usually outgoing HTTP requests are not affected by these sorts of iptables settings. So maybe the port forwarding still works but internally something breaks?

**Comment by bradrydzewski** [comment]
closing as unable to repeat, as well as possibly being a Docker issue
