### ISSUE TITLE
unable to cancel builds if the worker node no longer exists

### ISSUE THREAD

**Issue by macb** [drone/drone#1360]
I have a few builds that have been running for over a day. It appears they were placed on a worker that was ultimately destroyed, so no longer exists in the DB. It's now impossible to stop the build via the UI or API.

Relevant code: https://github.com/drone/drone/blob/master/controller/build.go#L138-L142

e: After poking around in the code I realized the cancel would only stop the container and wouldn't necessarily cleanup any of the state in the DB (such as marking the build as a failure). Would this be another part that would fix that state?

**Comment by martinsefcik** [comment]
related issue #1328

**Comment by bradrydzewski** [comment]
Good catch, if the node is gone and there is no way to cancel or cleanup right now you have to manually edit the database which is annoying. This seems like a pretty simple fix to update the database when no node exists.

> After poking around in the code I realized the cancel would only stop the container and wouldn't necessarily cleanup any of the state in the DB

When the container is killed it will unblock a go routine that is waiting for the container to exit:
https://github.com/drone/drone/blob/master/engine/engine.go#L329

When the above line unblocks it should continue to update the build status, exit code, logs, etc.

When the node was shutdown I would have expected the TCP connection between Drone and the Docker daemon to close, unblocking the above code and allowing it to continue and update the build status to `failed`. That is something I'll also need to look into.

**Comment by chaseadamsio** [comment]
@bradrydzewski this may be related to the issue I was experiencing as well that we discussed.

**Comment by bradrydzewski** [comment]
the behavior has now changed so this can be closed. If an agent no longer exists after a default timeout period (5 minutes) the build is re-queued and no longer stuck in limbo. It can then be cancelled.
