### ISSUE TITLE
No way to set Username and Password for gogs when REQUIRE_SIGNIN_VIEW=true

### ISSUE THREAD

**Issue by wenerme** [drone/drone#1361]
When gogs
```
REQUIRE_SIGNIN_VIEW=true
```

drone still use the http to fetch repo, consider use ssh with public key or allowed to add username or password.

**Comment by tboerger** [comment]
This bug report is invalid. Drone does not manage any user, the users are managed through Gogs and you have to use your Gogs credentials to login on Drone.

**Comment by wenerme** [comment]
How to `use your Gogs credentials to login on Drone` ?

I already use my gogs user logged in to drone, I can see my repo even when
```
REQUIRE_SIGNIN_VIEW=true
```

but the pulling will failed,because when drone pull from gogs do not use my credentials.

**Comment by wenerme** [comment]
The relate pull rquest https://github.com/drone/drone/pull/615

**Comment by tboerger** [comment]
@wenerme this pull request was for 0.3 and is a totaly different thing because it's just the auth for private docker build images.

Your user gets authenticated to gogs and drone gets some token authentication to fetch the projects.
