### ISSUE TITLE
"Unknown remote driver" when building on armhf

### ISSUE THREAD

**Issue by sokoow** [drone/drone#1364]
Hi All,

I'm just building for armhf and have problem taking off the ground with initial setup. I get this when I try to run:

./drone_static
INFO[0000] using database driver sqlite3                
INFO[0000] using database config drone.sqlite           
FATA[0000] unknown remote driver

Help please?

**Comment by bradrydzewski** [comment]
@sokoow looks like you didn't configure Drone properly. You need to hook it up to GitHub (or Bitbucket, etc). Please see the following sections in the docs:

http://readme.drone.io/setup/github.html
http://readme.drone.io/setup/bitbucket.html
http://readme.drone.io/setup/gogs.html
http://readme.drone.io/setup/gitlab.html

Also please use our chat room for questions (https://gitter.im/drone/drone) so we can reserve the issue tracker for bugs and feature requests. Thanks!!

**Comment by sokoow** [comment]
Thanks, the error message is a bit cryptic then, could you change it to "FATA[0000] unknown remote driver, set REMOTE_DRIVER variable" ?
