### ISSUE TITLE
ssh to remote host not working since upgrading to v0.4

### ISSUE THREAD

**Issue by bjodah** [drone/drone#1366]
Maybe I've messed something up, but I used to be able to ssh into a remote server from my builds by adding the Public Key from the repo page in drone to the list of authorized keys. (for deploying using scp for example).

But since upgrading to v0.4 (I did remove the old public key and copied the newly generated one) it no longer works. Also, now I need to pass `-o StrictHostKeyChecking=no` to even get so far (else I get `Host key verification failed.`). Anyone else experiencing this? (I should mention that the remote server is the same server which is running drone).

**Comment by bradrydzewski** [comment]
@bjodah this is now done using plugins, such as ssh or rsync (I use both heavily)
http://addons.drone.io/ssh/
http://addons.drone.io/rsync/

The previous version of Drone provided pre-configured Docker images. These images have been deprecated in 0.4 in favor of any custom image in the Docker registry, including the official language stack. If you want `-o StrictHostKeyChecking=no`  by default you would need to add that to your Docker image.

Feel free to use our gitter channel (at https://gitter.im/drone/drone) for questions and support. Thanks!

**Comment by bjodah** [comment]
Thank you and sorry for the noise!
