### ISSUE TITLE
Replace variables with empty strings if not injected

### ISSUE THREAD

**Issue by axel22** [drone/drone#1368]
As far as I can see, variable substitution with defaults, mentioned in drone docs, does not seem to work:

```
$${param=default} parameter substition with default
```

Instead, the string `$${param=default}` is literally fed to the `.drone.yml`.

**Comment by bradrydzewski** [comment]
can you verify the variable is available without `$${param=default}`? The reason I ask is we have pretty solid test coverage around bash string functions

https://github.com/drone/drone-exec/blob/master/yaml/inject/strings_test.go#L43

**Comment by axel22** [comment]
Thanks for your quick response!

No, the variable is not available with `$$param` - it is a secret that is not expanded if the build is a pull request. Trouble is, I'd like to check if the environment variable, to which I feed the secret to, is set to an empty string if the secret is not available. I would expect that a secret defaults to empty if not defined.

I actually got around this by checking `$DRONE_PULL_REQUEST`.

**Comment by bradrydzewski** [comment]
> set to an empty string if the secret is not available

agreed it makes sense to replace parameters with empty string if they don't exist. I'm going to adjust the issue title accordingly

**Comment by axel22** [comment]
Awesome, thank you!

**Comment by bradrydzewski** [comment]
closing with introduction of https://github.com/drone/envsubst
