### ISSUE TITLE
Needed documentation for version 0.3

### ISSUE THREAD

**Issue by loord** [drone/drone#1371]
Hello - i'm working with 0.3 version and have a problem with deleting github repo, more precisely with error 
< ./drone delete github.com/foo/bar Unauthorized
Please provide docs or help with Authorization.
Thank you.

**Comment by bradrydzewski** [comment]
0.3 alpha is no longer supported and is end of life. If you need to delete a repository I recommend logging into the database to do so. `delete from repos where repo_name=?`
