### ISSUE TITLE
GitLab activation failing

### ISSUE THREAD

**Issue by prasannakumarbr** [drone/drone#1372]
Hi,

i am integrating Gitlab with drone for CI,but am getting error like below

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Thank you in advance for help

**Comment by martinsefcik** [comment]
Are you using Gitlab.com or own Gitlab instance ?

**Comment by prasannakumarbr** [comment]
Thank you for replay,

Am using Gitlab instance

**Comment by tboerger** [comment]
Whitout some logs it's pretty hard to guess why it's not working.

**Comment by martinsefcik** [comment]
Are you getting error 500 in Gitlab on Drone CI service configuration page when you click on 'Test Settings' button?
What Gitlab version are you using ?
Provide as more info as you can.

But I think you should rather use drone gitter room for such kind of "configuration" issues, because It looks like it's problem on your side. Drone 0.4 should works fine with latest Gitlab version.

**Comment by bradrydzewski** [comment]
@prasannakumarbr you will need to provide Drone server logs and GitLab server logs if you would like assistance. It would also be helpful to know where you are getting errors. Login? Activating a repository? This guide gives good tips for logging an issue http://howtoproperlyloganissue.com/

**Comment by prasannakumarbr** [comment]
I am getting response from gitlab server is,

Gitlab.buildAndExecRequestRawfailed<404>http://mbaasgit.payoda.com/api/v3/projects/hilbert.v%2FMBaaS_Service_Stack/keys

**Comment by bradrydzewski** [comment]
Thanks for providing more detail. This is a bug with the GitLab api which fails when a repository contains a dot in the name. This needs to be fixed upstream in GitLab (I believe there is an open issue for it). You can see more discussion here https://github.com/drone/drone/issues/1043

**Comment by Bugagazavr** [comment]
Fixed in https://github.com/drone/drone/pull/1453
