### ISSUE TITLE
Unable to run Drone on MySQL using Google Cloud SQL

### ISSUE THREAD

**Issue by curinir** [drone/drone#1373]
Google Cloud SQL second generation database (MySQL), does not work with Drone 0.4.

When starting up, you get an error like this (using 'docker logs -f drone'):
time="2015-12-12T08:14:56Z" level=info msg="using database driver mysql" time="2015-12-12T08:14:56Z" level=info msg="using database config drone:REDACTED@tcp(REDACTED:3306)/drone?parseTime=true" time="2015-12-12T08:14:56Z" level=error msg="Error 1071: Specified key was too long; max key length is 767 bytes" time="2015-12-12T08:14:56Z" level=fatal msg="migration failed" 

I believe the reason is that drone has very long VARCHAR entries in the config, specified here:
https://github.com/drone/drone/blob/master/store/migration/mysql/1_init.sql
Some of them are longer than 767.

The Google Cloud SQL database uses the following settings:
| innodb_file_format                       | Barracuda              |
| innodb_large_prefix                      | OFF                    |
It is not possible to get SUPER privileges on Google Cloud SQL, so I can't change those settings (ON for innodb_large_prefix.

Would it be possible to use TEXT or do something else for those long columns?

Some more detail about this problem can be found here:
http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/

Information about Google Cloud SQL (2nd generation) can be found here:
https://cloud.google.com/sql/docs/getting-started

**Comment by bradrydzewski** [comment]
@curinir I think the issue may be the `repos.full_name` which is a unique index and > 255 characters. If that is the case we should be able to reduce the column size to 255, since the risk of a repository name being > 255 is very very low. Would you mind taking a look at https://github.com/drone/drone/issues/1323#issuecomment-158330146 and letting me know if that makes sense? If so, should be a simple patch on my end

**Comment by bradrydzewski** [comment]
in fact if you have cloud sql instance handy and can successfully run the `1_init.sql` script with the below modifications and verify it resolves the problem I can patch it right now

```diff
CREATE TABLE IF NOT EXISTS users (
...
-,user_login  VARCHAR(500)
+,user_login  VARCHAR(255)
...

,UNIQUE(user_login)
);

CREATE TABLE IF NOT EXISTS repos (
...
-,repo_full_name     VARCHAR(511)
+,repo_full_name     VARCHAR(255)
...

,UNIQUE(repo_full_name)
);
```

**Comment by bradrydzewski** [comment]
Just merged https://github.com/drone/drone/pull/1375 which should fix the issue. I was able to reproduce locally by creating the tables with a utf8 character set. I then applied the patch to verify the error was gone.

Are you able to test with the latest Docker image and let me know if this can be closed? Thanks

**Comment by curinir** [comment]
Sorry for the slow response. I manually ran the init SQL-script just to verify first, and yes that worked.
I also upgraded my docker image, and it worked nicely.

Thanks for the quick turnaround!

**Comment by kop** [comment]
@bradrydzewski I have exactly the same issue with `0.4.1` image version.

In the database, I see that `repos.repo_full_name` and `users.user_login` fields have length of `255`. However, migration fails.

In the same time, image version `0.4.0` started without any issues,

**Comment by bradrydzewski** [comment]
Im guessing the issue is in the mysql/3.sql file where I introduced
remote_addr and secret_name which are unique keys and > 255 chars. I'm
traveling but can merge a PR from my phone, or can create patch on
Wednesday
