### ISSUE TITLE
Keep track of tasks on plugins

### ISSUE THREAD

**Issue by tboerger** [drone/drone#1376]
To keep tracked the open tasks for ~~my~~ the massive plugin refactoring, mostly driven by me, and for all the new plugins I will maintain a list here.

### Requires functionality

* [ ] [atlas](https://github.com/drone-plugins/drone-atlas)
* [x] [codedeploy](https://github.com/drone-plugins/drone-codedeploy)
* [x] [opsworks](https://github.com/drone-plugins/drone-opsworks)
* [ ] [biicode](https://github.com/drone-plugins/drone-biicode)
* [ ] [boxfuse](https://github.com/drone-plugins/drone-boxfuse)
* [ ] [campfire](https://github.com/drone-plugins/drone-campfire)
* [ ] [chef-supermarket](https://github.com/drone-plugins/drone-chef-supermarket)
* [ ] [cloud66](https://github.com/drone-plugins/drone-cloud66)
* [ ] [cloudfoundry](https://github.com/drone-plugins/drone-cloudfoundry)
* [x] [elastic-beanstalk](https://github.com/drone-plugins/drone-elastic-beanstalk)
* [ ] [engineyard](https://github.com/drone-plugins/drone-engineyard)
* [ ] [exoscale](https://github.com/drone-plugins/drone-exoscale)
* [ ] [flowdock](https://github.com/drone-plugins/drone-flowdock)
* [ ] [hackage](https://github.com/drone-plugins/drone-hackage)
* [ ] [hg](https://github.com/drone-plugins/drone-hg)
* [ ] [lambda](https://github.com/drone-plugins/drone-lambda)
* [ ] [modulus](https://github.com/drone-plugins/drone-modulus)
* [ ] [openshift](https://github.com/drone-plugins/drone-openshift)
* [ ] [packagecloud](https://github.com/drone-plugins/drone-packagecloud)
* [ ] [puppetforge](https://github.com/drone-plugins/drone-puppetforge)
* [ ] [pushover](https://github.com/drone-plugins/drone-pushover)
* [ ] [rackspace-cloudfiles](https://github.com/drone-plugins/drone-rackspace-cloudfiles)
* [ ] [swift](https://github.com/drone-plugins/drone-swift)
* [ ] [testfairy](https://github.com/drone-plugins/drone-testfairy)

### Activate dockerhub

* [x] [artifactory](https://hub.docker.com/r/plugins/drone-artifactory/)
* [x] [chef](https://hub.docker.com/r/plugins/drone-chef/)
* [x] [codedeploy](https://hub.docker.com/r/plugins/drone-codedeploy/)
* [x] [exoscale](https://hub.docker.com/r/plugins/drone-exoscale/)
* [x] [flowdock](https://hub.docker.com/r/plugins/drone-flowdock/)
* [x] [hackage](https://hub.docker.com/r/plugins/drone-hackage/)
* [x] [hg](https://hub.docker.com/r/plugins/drone-hg/)
* [x] [lambda](https://hub.docker.com/r/plugins/drone-lambda/)
* [x] [modulus](https://hub.docker.com/r/plugins/drone-modulus/)
* [x] [nuget](https://hub.docker.com/r/plugins/drone-nuget/)
* [x] [openshift](https://hub.docker.com/r/plugins/drone-openshift/)
* [x] [opsworks](https://hub.docker.com/r/plugins/drone-opsworks/)
* [x] [packagecloud](https://hub.docker.com/r/plugins/drone-packagecloud/)
* [x] [puppetforge](https://hub.docker.com/r/plugins/drone-puppetforge/)
* [x] [pushover](https://hub.docker.com/r/plugins/drone-pushover/)
* [x] [rackspace-cloudfiles](https://hub.docker.com/r/plugins/drone-rackspace-cloudfiles/)
* [x] [scalingo](https://hub.docker.com/r/plugins/drone-scalingo/)
* [x] [sftp](https://hub.docker.com/r/plugins/drone-sftp/)
* [x] [sqwiggle](https://hub.docker.com/r/plugins/drone-sqwiggle/)
* [x] [swift](https://hub.docker.com/r/plugins/drone-swift/)
* [x] [terraform](https://hub.docker.com/r/plugins/drone-terraform/)
* [x] [testfairy](https://hub.docker.com/r/plugins/drone-testfairy/)

### Activate drone

* [x] [hg](http://beta.drone.io/drone-plugins/drone-hg)
* [ ] [chef](http://beta.drone.io/drone-plugins/drone-chef)

### Missing logos

* [ ] [atlas](https://github.com/drone-plugins/drone-atlas)
* [ ] [biicode](https://github.com/drone-plugins/drone-biicode)
* [ ] [cache](https://github.com/drone-plugins/drone-cache)
* [ ] [chef](https://github.com/drone-plugins/drone-chef)
* [ ] [chef-supermarket](https://github.com/drone-plugins/drone-chef-supermarket)
* [ ] [exoscale](https://github.com/drone-plugins/drone-exoscale)
* [ ] [hackage](https://github.com/drone-plugins/drone-hackage)
* [x] [lambda](https://github.com/drone-plugins/drone-lambda)
* [ ] [modulus](https://github.com/drone-plugins/drone-modulus)
* [ ] [openshift](https://github.com/drone-plugins/drone-openshift)
* [ ] [packagecloud](https://github.com/drone-plugins/drone-packagecloud)
* [ ] [puppetforge](https://github.com/drone-plugins/drone-puppetforge)
* [ ] [pushover](https://github.com/drone-plugins/drone-pushover)
* [ ] [rackspace-cloudfiles](https://github.com/drone-plugins/drone-rackspace-cloudfiles)
* [ ] [swift](https://github.com/drone-plugins/drone-swift)
* [ ] [testfairy](https://github.com/drone-plugins/drone-testfairy)

### Other tasks

* [ ] Delete the [capistrano](https://github.com/drone-plugins/drone-capistrano) repository

**Comment by cybernet** [comment]
github level +100

wouldn't be better a wiki page ?

**Comment by tboerger** [comment]
> github level +100

What?

> wouldn't be better a wiki page ?

@bradrydzewski suggested an issue with tasks for him, so I extended it just a little bit with more tasks that can be simply checked after it's done by somebody ;).

**Comment by tboerger** [comment]
I have not mentioned the repo description changes for all the repos to bring it into the same state as the repo content 8)

**Comment by tboerger** [comment]
Let's close that for now since this is anyway out of date.
