### ISSUE TITLE
Can't test gh-pages

### ISSUE THREAD

**Issue by felixrieseberg** [drone/drone#1379]
Drone is *amazing* - and I'd love to use it to work with my gh-pages branch. [Sadly, a hook from gh-pages isn't being acted on](https://github.com/drone/drone/blob/master/remote/github/github.go#L360-L362) - any chance we could use Drone with GitHub Pages?

(Happy to send a pull request, if that would help)

**Comment by bradrydzewski** [comment]
@felixrieseberg this code is there only for historical reasons. The original hosted version of drone (from which some of this code was copy / pasted) did not support different build scripts per branch. As a result, most people didn't want their primary build script running on the gh-pages branch.

This is no longer an issue and we can remove this restriction. I'm traveling at the moment but can review and approve pull requests from my phone. If you can send a PR that remove the below 3 lines I'm happy to accept:

https://github.com/drone/drone/blob/e70c11f06acc0b0d148c05d9005fabfb445c1d4d/remote/github/github.go#L359:L362

Thanks!
