### ISSUE TITLE
AWS ECS plugin

### ISSUE THREAD

**Issue by furybyname** [drone/drone#1387]
Hi,

I've recently created a plugin for simple deploys to AWS ECS.
https://github.com/furybyname/drone-ecs

I think this is a generally useful plugin and would like to put it forward for consideration of adding it to the main repo.

**Comment by furybyname** [comment]
Worth noting I used drone-elastic-beanstalk as a base for this.  i.e main changes are in main.go and types.go

**Comment by bradrydzewski** [comment]
Great, thanks!  I've created a repository in the drone-plugins org. Can you send a pull request?
https://github.com/drone-plugins/drone-ecs

**Comment by tboerger** [comment]
I think https://github.com/drone-plugins/drone-aws-codedeploy is an better example :)

**Comment by furybyname** [comment]
Thanks I'll take a look to see what needs changing.  Does the project need an initial commit so that I can fork it?

**Comment by bradrydzewski** [comment]
@furybyname added an initial commit. I'm going to close this. We can discuss further when the PR is opened, but at first glance it looks good
