### ISSUE TITLE
pulling image from private registry seems to fail 

### ISSUE THREAD

**Issue by xinity** [drone/drone#1388]
hi,

i'm trying to use Portus as a private registry, basically it just works fine, exception when i'm trying to pull a docker image with drone using this kind of URL:
`https://registry.[domain].com/myself/myimage:latest`
--> fails (only through drone, works perfectly fine with a docker client using cli)
             `unable to find image`

`https://registry.[domain].com/myimage:latest`
--> OK 
             `pulling from ...`
any clues on this ?

**Comment by tboerger** [comment]
You are pulling an image with https:// protocol?

**Comment by bradrydzewski** [comment]
@xinity if you don't mind, let's close this and move the discussion to https://github.com/drone/drone/issues/728 

thanks!  cc @jgreat
