### ISSUE TITLE
Caching across matrix builds

### ISSUE THREAD

**Issue by donatj** [drone/drone#1389]
According to the docs:

> Drone keeps a separate cache for each Branch and Matrix combination. Let’s say, for example, you are using matrix builds to test node 0.11.x and node 0.12.x and you are caching node_modules. Drone will separately cache node_modules for each version of node.

This does not appear to be the case in actuality.

I am running Drone using the recommended `.4` Docker image and all my matrix builds are sharing the same cache.

checking `tree` on `/var/lib/drone/cache/` I only see two .tar.gz files.  

I have 3 matrix builds, and 2 cached directories `vendor` and `public/js/vendor`

```
[jdonat@ip-172-31-11-250 cache]$ tree capdig
capdig
└── myon
    ├── cache.1de6ee7f09fb4a9ab871c7f959e726f7.tar.gz
    └── cache.e705f670ede890b82f286bd521fb3611.tar.gz
```

It would appear I have the same cache for every branch and every build.  This may end up being trouble.

**Comment by bradrydzewski** [comment]
good catch, fixed https://github.com/drone-plugins/drone-cache/commit/eda92b69ec91e943ba7d379f467e5c0921cb6b21
