### ISSUE TITLE
Feature Request: Disable Cache Compression

### ISSUE THREAD

**Issue by donatj** [drone/drone#1390]
Compressing my cache is taking a surprising amount of time. Doing some testing locally a straight tar instead of a tar.gz takes one third the amount of time. I have plenty of disk space and would much prefer the speed up of being able to disable this compression.

![screen shot 2015-12-29 at 11 13 41](https://cloud.githubusercontent.com/assets/133747/12038386/4ba4218c-ae1d-11e5-9d3c-caa27b875bf9.png)

**Comment by donatj** [comment]
It's actually not so bad now that I'm not out of CPU credits. Closing.

**Comment by bradrydzewski** [comment]
@donatj I actually have a separate branch that I'll publish that let's use specify a compression level. We've seen issues with corrupted `tar.gz` files per https://github.com/drone/drone/issues/1350 and I'm wondering if alternate compression (or no compression) could solve the issue.

**Comment by donatj** [comment]
Hah, so I jumped the gun.  That would be nice and would save me some CPU credits ;)

**Comment by bradrydzewski** [comment]
you can try develop branch of the cache plugin which will uses no compression by default:

```diff
cache:
+ image: cache:develop
  mount:
    - node_modules
```

compression can be enabled with the following:

```diff
cache:
+ compression: gzip
  mount:
    - node_modules
```

or for bzip compression:

```diff
cache:
+ compression: bzip2
  mount:
    - node_modules
```

**NOTE** that cache plugin will automatically cleanup older archives, but will not cleanup older archives if you switch compression types. If you switch from `gzip` to `bzip` or to no compression, it will leave the older `gzip` files in place.
