### ISSUE TITLE
drone-exec build environment differs from server

### ISSUE THREAD

**Issue by tooda02** [drone/drone#1391]
`drone exec build` is a useful way of testing .drone.yml files, but is limited by some differences between its environment and that when the build is run on a Drone server.  These differences include:
1.  The container is not initialized with each build, so a command like `mkdir xxx` fails on the second build because directory xxx already exists.   For performance reasons, we may not want to re-initialize by default every time, but it should be an option.
2.  Build attribute variables such as $$BRANCH are not available.
3. .drone.sec is not decrypted.  Ideally, it would be possible to provide a link to the repo on a Drone server, so that .drone.sec could be decrypted as if it were that build's secret.  An alternative would be a drone exec argument to reference a plaintext alternative to .drone.sec for testing.

See also Brad's comment on [PR pass `drone exec` args to drone-exec container #14](https://github.com/drone/drone-cli/pull/14#issuecomment-164236985)

**Comment by bradrydzewski** [comment]
we should be able to use the following to get the commit, remote, branch and other git-related details and pass to the build: https://github.com/mattn/goveralls/blob/master/gitinfo.go

the secure file cannot be decrypted locally without exposing the key or sending the secret file to the server. I would suggest we provide a `-e` parameter to the command line to pass multiple secret environment variables. These can be added to the list of global variables, which are injected in a similar manner to secure variables in the `.drone.sec`.

the drone server url (in `system.link`) can come from the `DRONE_SERVER` environment variable that is required when using the command line utility.

these changes should get us 90% there ...

**Comment by sehqlr** [comment]
I would be interested in helping implement this. I'm using this in conjunction with Terraform to build up and destroy clusters, so the secrets are needed in every run.

**Comment by gabrielpconceicao** [comment]
+1

**Comment by bradrydzewski** [comment]
I just pushed https://github.com/drone/drone-cli/commit/4c47c74bb86ece88b44622475b01242f4936ad7e which should allow us to execute `drone exec` with some extra data, including multiple secrets using `-e FOO=BAR` syntax and commit details based on your local git repository.

This doesn't close out the issue, as there are still some gaps, but hopefully this gets us a bit closer

**Comment by bradrydzewski** [comment]
all drone server fields now exposed to the `drone exec` command as flags. This is as close as we can get, given that `drone server` and `drone exec` have one major difference ... the former clones your code and the latter does not.
