### ISSUE TITLE
Plugin Template improvement proposal

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1392]
I also have another idea for supporting more robust templates for our notification plugins. Instead of `Template string` in the struct we could do `Template template.Template` where `template.Template` is a struct with custom parsing in our library @ https://github.com/drone/drone-go/tree/master/template

It could look like this:

```
type Template struct {
    Type string
    Text string
}
```

The custom JSON parsing could handle a few different values ...

This is a remote template:

```
template: http://gist.github.com/sd76sdf6sd7868s7d
```

This is an embedded template:

```
template: |
    {{ foo }}
```

This is an embedded template that overrides the template type to use Go templates:

```
template: 
  type: go
  text: |
    {{ .foo }}
```

This could let us support multiple template languages, including Go templates and handlebars templates, giving people some solid choices.

**Comment by bradrydzewski** [comment]
cc @crhym3

**Comment by tboerger** [comment]
As you already know I have already implemented the remote functionality within `drone-email`

```go
func remoteTemplate(kindOf, path string) (string, error) {
	resp, err := http.Get(path)

	if err != nil {
		return "", errors.New(
			fmt.Sprintf("Failed to fetch remote %s", kindOf))
	}

	contents, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		return "", errors.New(
			fmt.Sprintf("Failed to parse remote %s", kindOf))
	}

	return string(contents), nil
}
```

```go
	if _, err := url.Parse(vargs.Subject); err != nil {
		contents, err := remoteTemplate("subject", vargs.Subject)

		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		vargs.Subject = contents
	}
```

**Comment by tboerger** [comment]
Ah, and I forgot to mention I like the proposal!

**Comment by crhym3** [comment]
@bradrydzewski sounds good, with a tiny suggestion: I wouldn't use `string` as the template type, rather a custom definition, e.g. using `iota`.

Also, would be cool if it could distinguish between Go's `text/template` and `html/template`.
