### ISSUE TITLE
Make docker drone image keep track with master branch

### ISSUE THREAD

**Issue by denghongcai** [drone/drone#1394]
the drone image at dockerhub is too old, can you keep track with the master branch as the latest tag at dockerhub?

**Comment by bradrydzewski** [comment]
the drone docker image is published on every push / merge to master. The last image was published 13 hours ago

<img width="280" alt="screen shot 2016-01-05 at 9 24 37 am" src="https://cloud.githubusercontent.com/assets/817538/12122159/34dd928c-b38e-11e5-9f99-80e883b90b46.png">
