### ISSUE TITLE
No repositories from Gogs

### ISSUE THREAD

**Issue by Ant59** [drone/drone#1396]
I've setup Drone using the Gogs driver and logins work perfectly fine. However, none of my repositories are shown in Drone, not even in the search box as suggested in another issue. I just get "No Matches Found".

Gogs' API shows both repositories on Gogs.
Drone's API shows nothing but "[]".

What am I missing?

**Comment by bradrydzewski** [comment]
there is a known issue in Drone where we cache the repository list for 24 hours which means newly created repositories aren't displayed immediately. You can directly navigate to the page (ie `mydrone.com/foo/bar` or to restart Drone to flush the cache.

we have an open issue for this and are planning a fix to refresh the cache manually, which will land in the 0.4.1 release.

**Comment by Ant59** [comment]
Thank you for the quick response. Navigating direct worked perfectly.
