### ISSUE TITLE
Add the possibility to do complete git fetches. 

### ISSUE THREAD

**Issue by artworx** [drone/drone#1397]
My usecase is to measure the code quality changes on pull requests. In order to do that I need access to the full git history.

**Comment by bradrydzewski** [comment]
You can use `--depth` to increase the number of commit history (ie `--depth=1000`) and there is also an open [pull request](https://github.com/drone-plugins/drone-git/pull/14) for a flag to fetch all builds. Feel free to use the [gitter](https://gitter.im/drone/drone) room or [message board](https://discuss.drone.io) for these sort of questions to reserve the issue tracker for verified issues and bugs

**Comment by artworx** [comment]
What I mean with a `complete` fetch is get all the branches. 

Neither `--depth` nor https://github.com/drone-plugins/drone-git/pull/14 fetch the full branches from git.

**Comment by bradrydzewski** [comment]
feel free to send a PR that enables the `--all` flag for https://github.com/drone-plugins/drone-git
