### ISSUE TITLE
docker: Missing nsswitch.conf

### ISSUE THREAD

**Issue by fclairamb** [drone/drone#1398]
If you use the docker container as is, it won't read the /etc/hosts file. You need to add some nsswitch.conf file and then it will consider it.

I discovered this will doing a docker composition with a linked gogs container. But I'm pretty sure it applies to everyone.

**Comment by bradrydzewski** [comment]
We actually have an open issue and pull request to add an nsswitch (#1398). Would you mind reviewing and testing? The pull request is at https://github.com/drone/drone/pull/1306

**Comment by fclairamb** [comment]
For future viewers, the original issue is #1269 .
