### ISSUE TITLE
DRONE_PULL_REQUEST and CI_PULL_REQUEST show strange data

### ISSUE THREAD

**Issue by ralfschimmel** [drone/drone#1400]
Running a fresh install (today) using the 0.4 docker image on kubernetes (GKE).
Everything runs great except for the DRONE_PULL_REQUEST variable, it seems to hold some strange data and not the PR id.

`echo "Pull Request id $CI_PULL_REQUEST"`

shows

`Pull request id %!d(string=30)`

**Comment by gtaylor** [comment]
Oh fun. I don't have any words of wisdom for this issue (sounds like a Go string formatter gone awry), but if you have any GKE questions ping me in https://discuss.drone.io/ (I'm @gtaylor there, too). We've been running Drone in production within GKE for a few months now with great success.

**Comment by bradrydzewski** [comment]
yep, the `fmt.Sprintf` was expecting a `%d` but getting a `%s`. I just pushed a quick fix https://github.com/drone/drone-exec/commit/52a316b34e9c4a720d084f1ebb86039a8167ca59

**Comment by ralfschimmel** [comment]
Great guys, thanks!
