### ISSUE TITLE
Bundle/serve static files from the Drone binary

### ISSUE THREAD

**Issue by gtaylor** [drone/drone#1402]
Right around 6pm PST on Jan 7, CloudFlare's cdnjs is experiencing some issues. This has pretty much broken our Drone setup for the team, since it blocks the page loading on the file that is failing (https://cdnjs.cloudflare.com/ajax/libs/stickyfill/1.1.2/stickyfill.js).

We should probably provide some way to serve these files locally. A CDN can make all kinds of sense for a high trafficked site, but we're probably just fine bundling these into the binary and serving them from Drone to minimize this chance. It does inflate the binary slightly, but this is a preferable tradeoff to most or all of the userbase being unable to use the Drone web UI.

I realize that these CloudFlare outages are rare, but it's tough to have your team locked out of your CI setup :(

**Comment by tboerger** [comment]
+1 for bundling the assets

**Comment by geromueller** [comment]
+1 at least make it optional

**Comment by wyattjoh** [comment]
https://github.com/gogits/gogs serves their assets out of a directly from a public folder, I assume that it would be possible for Drone to do the same? Benefits from having a reverse proxy serve/cache them for you..

**Comment by tboerger** [comment]
> https://github.com/gogits/gogs serves their assets out of a directly from a public folder, I assume that it would be possible for Drone to do the same? Benefits from having a reverse proxy serve/cache them for you..

No, I would really stick with the singlefile deployments, e.g. use go-bindata as we already do it but just add an option like Gogs to use local assets instead of the CDN assets.

**Comment by bradrydzewski** [comment]
let's move to https://github.com/drone/drone-ui/issues/32
