### ISSUE TITLE
adding a worker node currently not working from the UI

### ISSUE THREAD

**Issue by fommil** [drone/drone#1403]
The current instructions for adding a remote worker are to run this script on the worker

https://gist.github.com/bradrydzewski/a6090115b3fecfc25280

(which appears to assume IP addresses, so actually the comments need to be adjusted) then to use the add nodes UI interface and paste the relevant data.

However, this results in the following server error:

```
ERRO[173156] error connecting to docker daemon tcp://213.136.89.60:2376. Get https://213.136.89.60:2376/v1.15/version: x509: cannot validate certificate for 213.136.89.60 because it doesn't contain any IP SANs. 
```

and changing to use hostnames gives

```
ERRO[173222] error connecting to docker daemon tcp://fieldmarkeng.co.uk:2376. Get https://fieldmarkeng.co.uk:2376/v1.15/version: x509: certificate is valid for *, not fieldmarkeng.co.uk. 
```

so something doesn't work.

Maybe the script needs to be updated to take the hostname into account? Or the drone server needs to handle `--tls` instead of `--tlsverify`

**Comment by fommil** [comment]
the CLI doesn't appear to have any documentation for `drone node create`, but I tried this and it failed

```
$ drone node create --docker-host=213.136.89.60 --docker-tls-verify=false --docker-cert-path=cert.pem
INFO[0000] using database driver sqlite3                
INFO[0000] using database config drone.sqlite           
FATA[0000] unknown remote driver        
```

(btw, I get this error for pretty much anything I type with the cli)

**Comment by fommil** [comment]
I had an out of date drone CLI (btw, is it possible to install it from source? I don't like downloading random binaries, especially when go is so easy to compile)

now the error is

```
 drone node create --docker-host=213.136.89.60 --docker-tls-verify=false --docker-cert-path=$PWD/cert.pem
Error reading cert.pem or key.pem from /root/cert.pem
```

but I think it would be a lot easier if this all worked from the UI

**Comment by fommil** [comment]
I got this to work with the CLI using https://github.com/ensime/ensime-server/issues/1209 but it would be good if this worked from the UI.

Also, it would be great if the node script generated a different key for the server than the client. As I understand it, this approach uses the same private key for server and client? (and the CA is not used by drone)

**Comment by tboerger** [comment]
@fommil quite easy to build on your own, see this makefile https://github.com/drone/drone-cli/blob/master/Makefile

**Comment by fommil** [comment]
@tboerger is there a go get command for that?

**Comment by tboerger** [comment]
go get github.com/drone/drone-cli && cd $GOPATH/github.com/drone/drone-cli && make...
:)

**Comment by fommil** [comment]
hmm, it's usually just a go get thing, is the cd and make part really necessary?

**Comment by fommil** [comment]
package github.com/drone/drone-cli: no buildable Go source files in /home/fommil/.go/src/github.com/drone/drone-cli

is that something you might add to your build? it'd be really nice to use standard go commands to install the cli!

**Comment by tboerger** [comment]
go get github.com/drone/drone-cli/...

**Comment by tboerger** [comment]
The ... will build all sub packages including cmd. Alternatively go get github.com/drone/drone-cli/cmd

**Comment by fommil** [comment]
hmm, neither of those work for me

```
~ go get github.com/drone/drone-cli/cmd
package github.com/drone/drone-cli/cmd: cannot find package "github.com/drone/drone-cli/cmd" in any of:
	/usr/lib/go/src/github.com/drone/drone-cli/cmd (from $GOROOT)
	/home/fommil/.go/src/github.com/drone/drone-cli/cmd (from $GOPATH)
~ go get github.com/drone/drone-cli/...
package github.com/Sirupsen/logrus/hooks/airbrake: cannot find package "github.com/Sirupsen/logrus/hooks/airbrake" in any of:
	/usr/lib/go/src/github.com/Sirupsen/logrus/hooks/airbrake (from $GOROOT)
	/home/fommil/.go/src/github.com/Sirupsen/logrus/hooks/airbrake (from $GOPATH)
package github.com/docker/docker/pkg/units: cannot find package "github.com/docker/docker/pkg/units" in any of:
	/usr/lib/go/src/github.com/docker/docker/pkg/units (from $GOROOT)
	/home/fommil/.go/src/github.com/docker/docker/pkg/units (from $GOPATH)
```

**Comment by tboerger** [comment]
Sorry, it helps to check the source first. go get github.com/drone/drone-cli/drone should work. maybe you need to fetch the deps.

**Comment by fommil** [comment]
```
~ go get github.com/drone/drone-cli/drone
# github.com/drone/drone-cli/drone
.go/src/github.com/drone/drone-cli/drone/exec.go:230: not enough arguments in call to docker.Run
```

**Comment by tboerger** [comment]
put a GO15VENDOREXPERIMENT=1 in front of the command to activate the go 1.5 dep vendoring.

**Comment by fommil** [comment]
cool! that works. This is how I will install drone from now on. It would be good to include this as an installation option.

**Comment by bradrydzewski** [comment]
For reference, this document details the recommend approach for installing workers:
https://github.com/drone/drone/blob/master/docs/cli/machines.md

The gist you mentioned should no longer be referenced in the documentation, however, if it is still there we should remove it and replace it with the above link.

There is a known issue in the UI where we don't display the error message when adding a node fails. We are tracking this in issue https://github.com/drone/drone/issues/1253

There are no known issues, however, adding nodes from the UI if you correctly setup the certs on the Docker daemon and paste in the correct values in the UI. The UI and CLI use the same REST andpoint. This process is actually very prone to user error (I include myself in this bucket as well) which is why I recommend using the CLI.

**Comment by fommil** [comment]
@bradrydzewski thanks. However the new documentation doesn't seem to show how to set up the remote docker servers anymore, so how does one actually create the certificates and key?

**Comment by bradrydzewski** [comment]
@fommil this is all handled by docker machine. It will setup the create the certs and setup the docker daemon with tls enabled. It then stores a copy of those certs on your local machine.

This section of the docs might help explain the process a little better:
https://github.com/drone/drone/blob/master/docs/cli/machines.md#instructions

**Comment by fommil** [comment]
is the "a new server" bit for running on the drone server machine or does this mean "on the machine that will shortly become a drone node"

**Comment by fommil** [comment]
and what is a "digitalocean-access-token"?

**Comment by bradrydzewski** [comment]
I'd recommend skimming the docker machine documentation https://docs.docker.com/machine/

This will probably make more sense once you've looked at the Docker machine documentation but the quick explanation is that Docker machine supports a number of different plugins / providers for provisioning Docker instances. The Drone documentation shows an example `docker machine` command that provisions a Docker instance on Digital Ocean (cloud provider). The actual command that you execute will depend on which provider you choose to use.

**Comment by fommil** [comment]
Right, but I don't want to use a provider because all our nodes are going to be contributed by our users and we just want them to send us the key/cert once its all setup. I don't think the new approach considers our use case.

**Comment by bradrydzewski** [comment]
Docker machine has an ssh provider that will login to an existing machine and will install docker and setup all the certs: https://github.com/docker/machine/blob/master/docs/drivers/generic.md

Docker machine outputs the path to the certificates in the `DOCKER_CERT_PATH` variable. The drone command line utility is actually reading this path, and uploading the certs. It essentially automates the process of copy / pasting the certs into the UI..

Docker machine is not required at all. You can setup the certs manually and paste into the UI but this is very prone to user error and difficult to debug, resulting in the assumption that Drone is broken. The benefit of using Docker machine is that it is repeatable and guarantees a correct setup.

My suggestion would be for your community members to add your public key to the `authorized_keys` file on the server they donate at which point you can run `docker machine` using the ssh provider, in conjunction with the drone command line utility.

Of course, of this will matter in 0.5 release when we switch to a pull queue and agents (see https://github.com/drone/drone/issues/1386)

**Comment by fommil** [comment]
I won't have ssh access to any of the node machines, we're not asking our donators to trust us that much.
