### ISSUE TITLE
don't use sassc

### ISSUE THREAD

**Issue by vtolstov** [drone/drone#1414]
May be switch from C sassc compiler to go version?
https://github.com/c9s/c6 if this possible?

**Comment by bradrydzewski** [comment]
in the drone/drone-ui project I'm experimenting with a react (and also) and angular2 UI neither of which use scss

**Comment by tboerger** [comment]
And https://github.com/c9s/c6 is anyway not in a working state. Beside that there is an alpine linux package for sassc

**Comment by vtolstov** [comment]
Im asked because i'm build drone from sorce, and sassc needs to build it

**Comment by bradrydzewski** [comment]
You can use this script to install sassc:
https://github.com/drone/drone/blob/master/contrib/setup-sassc.sh

We are moving away from sassc which will likely be released with Drone 0.5

**Comment by vtolstov** [comment]
Do you have issue or pr to watch on progress to moving from sassc ?

**Comment by gtaylor** [comment]
@vtolstov This will land with the new UI. There is no separate issue, but look out for the 0.5 announcement.
