### ISSUE TITLE
expose DRONE_VERSION/CI_VERSION environment variable

### ISSUE THREAD

**Issue by johnrengelman** [drone/drone#1415]
Some tools out there (i.e. Artifactory) can keep track of the CI server information. It would be nice to be able to complete the data with the drone version. 
This tracks with the existing `CI_NAME` envvar that is already exposed.

**Comment by gtaylor** [comment]
Hadn't really thought about it, but this would be useful to us as well. Makes sense, especially if we are already exposing CI_NAME.

**Comment by bradrydzewski** [comment]
the version number is passed through to the drone-exec runner in the `System.Version` field, so this should be easy enough

**Comment by bradrydzewski** [comment]
DRONE_VERSION added to 0.5

**Comment by k0nserv** [comment]
What happened with this? `echo $DRONE_VERSION` prints nothing in drone steps with Drone 0.8?

**Comment by k0nserv** [comment]
ping @bradrydzewski
