### ISSUE TITLE
Gogs client doesn't work with vhost contexts

### ISSUE THREAD

**Issue by michaelgibson** [drone/drone#1416]
Our gogs service is hosted using a shared domain with a sub-context.
i.e. https://www.example.com/gogs

I can see in the code where the url_.Path is nulled out but I'm not sure of the decision behind this.
https://github.com/drone/drone/blob/master/remote/gogs/gogs.go#L33

It would be nice to get it working with different base extensions.

**Comment by bradrydzewski** [comment]
recently merged https://github.com/drone/drone/pull/1413 which fixes the issue
