### ISSUE TITLE
User Management: validate 'Add User' is not empty string

### ISSUE THREAD

**Issue by andreas-venturini** [drone/drone#1418]
Currently a user can simply be created by (accidentally) clicking on "Add User" without entering a name. 
The user cannot be deleted afterwards. 

![screenshot from 2016-01-14 00 00 02](https://cloud.githubusercontent.com/assets/4801917/12310674/d0763356-ba51-11e5-8ce2-2a40430a1dea.png)

**Comment by FPurchess** [comment]
also of value to know: How to delete this 'empty' user?

(The problem is that "delete" triggers an API call to the toplevel REST collection instead of a specific user due to the missing username.)

**Comment by FPurchess** [comment]
@bradrydzewski Do you think it's a good idea to integrate a tag based validation for all models which then can be called by all controllers / plugins? Maybe something in this direction:
https://github.com/go-playground/validator
https://github.com/asaskevich/govalidator
https://github.com/go-validator/validator
https://github.com/leebenson/conform

**Comment by tboerger** [comment]
Some basic validation makes sense. I would suggest https://github.com/go-playground/validator, it plays pretty well with gin.

**Comment by FPurchess** [comment]
great! so as far as I can see, a simple binding tag should do the magic?

**Comment by tboerger** [comment]
I'm using https://github.com/asaskevich/govalidator for my project now.
