### ISSUE TITLE
Pull Request builder does not fail gracefully if the Pull Request has a merge conflict

### ISSUE THREAD

**Issue by tolgap** [drone/drone#1420]
The Pull Request builder fetches the merged ref of the Pull Request:
`git fetch --no-tags --depth=50 origin +refs/pull/:id/merge:`. This is a good thing, I agree. But if the PR has a merge conflict, the only error you see is:

```
$ git remote add origin https://github.com/myorg/my-project
$ git fetch --no-tags --depth=50 origin +refs/pull/143/merge:
fatal: Couldn't find remote ref refs/pull/143/merge
[info] Pulling image plugins/drone-cache:latest
[info] build failed (exit code 1)
```

This error really had me puzzled as I thought my network setup was somehow not working. So I think Drone should catch unmergable PRs. The (Go) Github API [gives you the ability to check if a PR is mergable](https://github.com/google/go-github/blob/master/github/pulls.go#L33).

Drone could print to the build log that the PR is unmergable because of merge conflicts and the developer should fix the conflicts first, otherwise the PR ref cannot be checked out.

**Comment by dunyakirkali** [comment]
:+1:

**Comment by bradrydzewski** [comment]
closing this in favor of a plugin-specific solution. Subscribe to https://github.com/drone-plugins/drone-git/issues/20 for updates
