### ISSUE TITLE
Proposal for native build environments

### ISSUE THREAD

**Issue by strich** [drone/drone#1421]
I first discovered Drone through its mission statement of being a direct evolution and replacement to the current industry titan Jenkins. A goal I think anyone would be happy to get behind.

It appears that Drone is ticking all the boxes in doing this with its modern take on CI. Containerization of entire build environments is a great fit for CI. However I have an edge case that I'd like to explain and hope to see supported in Drone.

### The Build Stage
I develop video games for the PC platforms Windows, OS X, and Linux. I currently use the Unity3D Engine as the backbone for my projects. This 3D engine, at this point in time, can only be built on the Windows platform. Unity are working on being able to perform builds within a Linux environment, however it won't likely be a solid option for quite some time.

There are other 3D engines in a similar position where Windows is the primary build environment, and will continue to be for awhile yet.

### The Test Stage
Regardless of whether the various 3D engine and middleware vendors make a Linux build environment an option, we must test and analyse our video games. Doing so involves running the built game on as many different environments as possible for flaws, or for testing performance against specific hardware stacks. For this we obviously need the Windows environment as well as native and dedicated access to the machine itself for accurate performance testing.

I understand the fantastic benefits for environment isolation and containerization, and I will benefit from it with the various peripheral applications we create and use with our game projects. However for the game itself we require the ability to use environments that Docker does not support (and never will).

I realize this kind of case is not a primary case for a CI system, and therefore I don't expect first class support for it. However I do know that most of my not-so-small industry is in the same situation and I would like to think it be a supported feature for a developer to use Drone with native build agents.

**Comment by gtaylor** [comment]
One of the worst problems with Jenkins is that it tries to be everything to everyone. And it mostly succeeds at this, despite being clunky, cantankerous, and generally unpleasant to deal with. Drone is kind of the antithesis in that it is relatively small, focused, and fills a certain niche very well.

Especially given the small size of our pool of manpower now, I'd hate to see us go down this rabbit hole just yet, if ever. The core of Drone is containerization, and it's one of the reasons that I subjectively love it. Without containers, Drone isn't especially noteworthy. But toss in the plugins-as-containers setup, and it really shines in its simplicity and ease of extension.

I feel like something you are describing could be better served by another CI system. Especially with our community being small, staying focused on the core of what makes Drone unique is probably our best bet. We shouldn't even be *trying* to be everything to anyone anytime soon. And the Docker ecosystem itself is still in a crazy state of flux.

My opinion on this is no more important than anyone else's, but I don't see a ton of value in expending time or resources on this sort of effort. As you said, it's a bit of an edge case and it would require massive re-thinking of our core.

**Comment by vtolstov** [comment]
After mergong to drone ability to talk to drone agent running on host, this
task can be not very hard.
16 янв. 2016 г. 3:50 пользователь "Greg Taylor" <notifications@github.com>
написал:

**Comment by bradrydzewski** [comment]
I'm going to merge this issue with https://github.com/drone/drone/issues/135
