### ISSUE TITLE
can't bulid from source  

### ISSUE THREAD

**Issue by wangben12** [drone/drone#1424]
just fork drone and  build on drone.io ,any thing wrong ?
output 
=================================
git clone git://github.com/wangben12/drone.git /home/ubuntu/src/github.com/wangben12/drone 
Cloning into '/home/ubuntu/src/github.com/wangben12/drone'...
$ go version
go version go1.4.2 linux/amd64
$ make deps
go get -u golang.org/x/tools/cmd/cover
go get -u golang.org/x/tools/cmd/vet
go get -u github.com/kr/vexp
go get -u github.com/eknkc/amber/...
go get -u github.com/eknkc/amber
go get -u github.com/jteeuwen/go-bindata/...
go get -u github.com/elazarl/go-bindata-assetfs/...
go get -u github.com/dchest/jsmin
go get -u github.com/franela/goblin
go get -u github.com/PuerkitoBio/goquery
go get -u github.com/russross/blackfriday
GO15VENDOREXPERIMENT=1 go get -u github.com/go-swagger/go-swagger/...
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context expects import "golang.org/x/net/context"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context/ctxhttp
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context/ctxhttp: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/net/context/ctxhttp expects import "golang.org/x/net/context/ctxhttp"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/netutil
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/net/netutil: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/net/netutil expects import "golang.org/x/net/netutil"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/ast/astutil
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/ast/astutil: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/ast/astutil expects import "golang.org/x/tools/go/ast/astutil"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/buildutil
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/buildutil: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/buildutil expects import "golang.org/x/tools/go/buildutil"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/exact
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/exact: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/exact expects import "golang.org/x/tools/go/exact"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types expects import "golang.org/x/tools/go/types"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types/typeutil
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types/typeutil: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/types/typeutil expects import "golang.org/x/tools/go/types/typeutil"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports
	imports github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports expects import "golang.org/x/tools/imports"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/gopkg.in/airbrake/gobrake.v2
	imports github.com/go-swagger/go-swagger/vendor/gopkg.in/airbrake/gobrake.v2: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/gopkg.in/airbrake/gobrake.v2 expects import "gopkg.in/airbrake/gobrake.v2"
package github.com/go-swagger/go-swagger/...
	imports github.com/go-swagger/go-swagger/vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2
	imports github.com/go-swagger/go-swagger/vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2: code in directory /home/ubuntu/src/github.com/go-swagger/go-swagger/vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2 expects import "gopkg.in/gemnasium/logrus-airbrake-hook.v2"
make: *** [deps] Error 1

**Comment by tboerger** [comment]
Pretty simple error, you need go >= 1.5 to compile drone.

**Comment by wangben12** [comment]
thks for reply 😁,I'm  new to  go .

**Comment by bradrydzewski** [comment]
instructions for compiling are found at https://github.com/drone/drone#from-source or even better, you can look at the project's `.drone.yml` file

it looks like you did not set `export GO15VENDOREXPERIMENT=1`

for these type of question, please use our gitter room at https://gitter.im/drone/drone or our discourse format at https://discuss.drone.io
