### ISSUE TITLE
Drone CLI displays HTML page

### ISSUE THREAD

**Issue by tboerger** [drone/drone#1425]
If you try to generate a .drone.sec file and the repository is not activated you get an HTML page. It just happened with drone-plugins/drone-hg to me.

**Comment by gabro** [comment]
Same thing when you ask info about a non-existent repo

e.g.

```
drone build last org/non-existent
```

or 

```
drone repo info org/non-existent
```

**Comment by bradrydzewski** [comment]
this will go away when we move to the react-based ui ... it will allow us to return a proper json message in stead of the 404 not found webpage. I'm going to mark this as wont-fix because we are not going to implement a fix but instead replace the UI
