### ISSUE TITLE
feature request: download full log from Drone CI web interface

### ISSUE THREAD

**Issue by fracting** [drone/drone#1429]
I use Drone CI to build large project, for example GCC:

http://52.8.143.18/fracting/gcc-dummy/1
(BTW, this is Win32 version of GCC compiled by Win32 version of GCC on Wine on Linux in Drone CI)

The log is very long, and it seems to be truncated in the web interface.
Could we implement a "download full log" feature?

Thanks!

**Comment by bradrydzewski** [comment]
although we don't have a download button in the UI we do have an endpoint to download the full log `/api/repos/fracting/gcc-dummy/1/1?full=true`

**Comment by fracting** [comment]
Thanks for the response, but sorry I still don't understand, I tried `http://52.8.143.18/api/repos/fracting/gcc-dummy/1/1?full=true` but it does not work, I should be missing something, could you please give me an example how to use it?

Thank you!

**Comment by bradrydzewski** [comment]
sorry I gave you the wrong url pattern. use `/api/repos/{owner}/{name}/logs/{number}/1?full=true`

**Comment by fracting** [comment]
Thanks, I tried http://52.8.143.18/api/repos/fracting/gcc-dummy/logs/1/1?full=true and it works this time!

BTW, the log seems to be truncated, (as well as the log in web interface), but it might be either my own problem or a separate bug, I'll keep monitor on that and report an issue if needed.

**Comment by tboerger** [comment]
Maybe the database column is too small?

**Comment by fracting** [comment]
I downloaded the truncated log, and the size is exactly 2000000 bytes.

I read GetBuildLogs()

```
        defer r.Close()
        if full {
                io.Copy(c.Writer, r)
        } else {
                io.Copy(c.Writer, io.LimitReader(r, 2000000))
        }
}
```

Is it reasonable to ask upstream Drone increasing the number, or should I only do it in my fork?

To me it seems like it is reasonable to have a full log large enough for compiling gcc using gcc.

Thanks!

**Comment by bradrydzewski** [comment]
> Is it reasonable to ask upstream Drone increasing the number, or should I only do it in my fork?

We've observed that > 2MB of logs will crash the browser. This is why we limit the amount to 2MB. The reason we have the `full` flag is so that we can (eventually) add a button to the UI to download the full logs. This is how most other CI systems handle the issue.

**Comment by tboerger** [comment]
Maybe we need to group the output somehow like travis is doing that

**Comment by fracting** [comment]
@tboerger could you give some advice how to adjust default database column to get rid of 2MB limited?
Since ` http://52.8.143.18/api/repos/fracting/gcc-dummy/logs/1/1?full=true ` doesn't solve my problem, I believe that there is another limitation, which might be the default database column you pointed out.

Thanks!

**Comment by bradrydzewski** [comment]
closing since the logs are no longer truncated in the user interface, or by the server endpoint
https://github.com/drone/drone/blob/db5b8e83ee57da4e214e988c9254d5de4c3b40c5/server/build.go#L80

**Comment by Dorian** [comment]
```
	if full {
		// TODO implement limited streaming to avoid crashing the browser
	}
```

https://github.com/drone/drone/blob/master/server/build.go

**Comment by tcely** [comment]
The logs are still truncated on the agent.

https://github.com/drone/drone/blob/81103a98208b0bfc76be5b07194f359fbc80183b/cmd/drone-agent/agent.go#L277

**Comment by Akito13** [comment]
> /api/repos/{owner}/{name}/logs/{number}/1?full=true

Tried this and did not work for me. Is this still up-to-date?

**Comment by andno037** [comment]
Have the same question is:
'/api/repos/{owner}/{name}/logs/{number}/1?full=true'
up and running?

**Comment by tboerger** [comment]
Instead of asking on an *4 years* old issue you should simply look at the code, seearch on the docs, or ask on forum/chat!

https://github.com/drone/drone/blob/master/handler/api/api.go#L212
e.g. `/api/repos/{owner}/{name}/builds/{build}/logs/{stage}/{step}`
