### ISSUE TITLE
Make auto pulling of plugins optional

### ISSUE THREAD

**Issue by michaelgibson** [drone/drone#1431]
Drone is currently automatically pulling the latest image for plugins based on commits:
https://github.com/drone/drone/commit/65f885e47876fc490edcb96a4f75975aa0a9d9cb
and
https://github.com/drone/drone/commit/1b8a00f5f696815140a5b79f01244cc6ada82563

I would prefer this behavior be optional as the update overwrites any customized image builds you may have installed.

**Comment by tboerger** [comment]
I don't think that we will do that change in this direction because it's more or less a backward compat breakage. Current behavior is auto update, maybe we should add a flag that disables auto updates.

**Comment by michaelgibson** [comment]
That seems fine as long as there is a way to control the behavior.

**Comment by msteinert** [comment]
I believe #1378 would address this issue. (still waiting for a review!)

**Comment by michaelgibson** [comment]
Yeah that looks like a potential direction for my purposes...Mostly.
I'm currently running drone-git using statically defined hosts: https://docs.docker.com/engine/reference/run/#managing-etc-hosts

So would need to expose some of the options in the HostConfig:
i.e. 
NetworkMode
and
ExtraHosts

**Comment by bradrydzewski** [comment]
let's track this as #1324 which has open pull request #1378 which will be incorporated into the 0.5 release
