### ISSUE TITLE
Github authentication causes redirect loop on self hosted Drone

### ISSUE THREAD

**Issue by onnimonni** [drone/drone#1434]
Hey!

I'm running drone 0.4 in docker behind nginx reverse proxy (nginx handles https).

My configs:
```
"REMOTE_CONFIG=https://github.com?client_id=$ID&client_secret=$SECRET",
"REMOTE_DRIVER=github",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"DATABASE_DRIVER=sqlite3",
"DATABASE_CONFIG=/var/lib/drone/drone.sqlite"
```

Github redirects me into url:
```
https://REDACTED/authorize?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=AVE5YPXBHDUGHYTRJHXFPA2Z3JFSISUA553ZYYFU7Q6XVX7QY2LQ%3D%3D%3D%3D
```
Which redirects back to:
```
https://github.com/login/oauth/authorize?client_id={REDACTED}&redirect_uri=http%3A%2F%2F{REDACTED}%2Fauthorize&response_type=code&scope=repo%2Crepo%3Astatus%2Cuser%3Aemail&state=ERISZ56LRZ35B2UGK4D2YDDUSCQTAIQ5WS2BEFRP2NS4E4BIW2GQ%3D%3D%3D%3D
```
It seems that my application is wrongly configured.

Should drone handle the error parameters from Github, At least give user notification that the settings are wrong?

I'm using ```/authorize``` endpoint in Github application **Authorization callback URL**.

<img width="552" alt="github_authorization_url" src="https://cloud.githubusercontent.com/assets/5691777/12551394/ae4397cc-c372-11e5-959b-15c80f57e256.png">

**Comment by bradrydzewski** [comment]
I can see the redirect_url being sent to GitHub is http (`&redirect_uri=http%3`) but the Authorization callback url is https. This is resulting a redirect mismatch error message from GitHub.

If you are using nginx please ensure you have configured `X-Forwarded-Proto` so that when the drone server attempts to determine its own url that it knowns it is https
http://readme.drone.io/setup/proxy_reverse/

**Comment by onnimonni** [comment]
This was it! Thanks alot :)
