### ISSUE TITLE
drone 0.4 database ping failed

### ISSUE THREAD

**Issue by valentinbud** [drone/drone#1436]
First of all allow me to tell you that I think drone is an exquisite piece of technology that's very easy to understand and use. Thank you for sharing :).

I am trying to deploy drone 0.4 with Postgres Database located in another container.

```
$ docker run -d --name drone-postgres -e POSTGRES_USER=drone -e POSTGRES_DB=drone -e POSTGRES_PASSWORD=drone postgres
```

I have verified that the database is up and running with another docker container.

```
$ docker run -it --link drone-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U drone'
```

After entering `drone` password I am inside a psql shell. I suppose it is working.

Next I have run drone with environment variables.

```
$ docker run --rm -it -e DATABASE_DRIVER=postgres -e DATABASE_CONFIG=postgres://drone:drone@172.17.0.2:5432/drone drone/drone:0.4

INFO[0000] using database driver postgres
INFO[0000] using database config postgres://drone:drone@172.17.0.2:5432/drone
INFO[0000] database ping failed. retry in 1s
INFO[0001] database ping failed. retry in 1s
INFO[0002] database ping failed. retry in 1s
INFO[0003] database ping failed. retry in 1s
INFO[0004] database ping failed. retry in 1s
INFO[0005] database ping failed. retry in 1s
INFO[0006] database ping failed. retry in 1s
INFO[0007] database ping failed. retry in 1s
INFO[0008] database ping failed. retry in 1s
INFO[0009] database ping failed. retry in 1s
INFO[0010] database ping failed. retry in 1s
```

The IP Address is from `docker inspect drone-postgres`. Could you please tell what have I done wrong or another way to deploy drone with Postgres, both in docker containers.

**Comment by tboerger** [comment]
Have you also tried `DATABASE_CONFIG=postgres://drone:drone@postgres:5432/drone`? As per default you can use the link name as host to connect to.

**Comment by valentinbud** [comment]
@tboerger just tried it, same result.

```
$ docker run --rm -it --link drone-postgres:postgres -e DATABASE_DRIVER=postgres -e DATABASE_CONFIG=postgres://drone:drone@postgres:5432/drone drone/drone:0.4  INFO[0000] using database driver postgres
INFO[0000] using database config postgres://drone:drone@postgres:5432/drone
INFO[0000] database ping failed. retry in 1s
INFO[0001] database ping failed. retry in 1s
INFO[0002] database ping failed. retry in 1s

**Comment by tboerger** [comment]
I don't really know but maybe this is apso related to the scratch base image. I'm using my own custom docker image...

**Comment by bradrydzewski** [comment]
@valentinbud can you `docker pull drone/drone:0.4` and confirm you have the latest docker image?

We had an open issue that I believe might be related:
https://github.com/drone/drone/issues/1269

We merged a PR a few days ago to fix:
https://github.com/drone/drone/pull/1306

**Comment by valentinbud** [comment]
@bradrydzewski sure. I have just removed the dev machine and created a new one with docker-machine, so I have no images.

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

docker pull drone/drone:0.4
0.4: Pulling from drone/drone
a751b1edea64: Pull complete
a39ef86716f9: Pull complete
5fd6e7ab8fa4: Pull complete
f005ec171ab3: Pull complete
3e96393070da: Pull complete
036eaaa9dd63: Pull complete
b509b5ab561b: Pull complete
40dea3261655: Pull complete
Digest: sha256:2ec06956976eadeaec2517e334eed82a4e744273154d2e852816aa9ae3eb3829
Status: Downloaded newer image for drone/drone:0.4
```

Same result with both `postgres` and IP Address in the Postgres connection string.

```
$ docker run --rm -it --link drone-postgres:postgres -e DATABASE_DRIVER=postgres -e DATABASE_CONFIG=postgres://drone:drone@postgres:5432/drone drone/drone:0.4
INFO[0000] using database driver postgres
INFO[0000] using database config postgres://drone:drone@postgres:5432/drone
INFO[0000] database ping failed. retry in 1s
INFO[0001] database ping failed. retry in 1s
INFO[0002] database ping failed. retry in 1s
INFO[0003] database ping failed. retry in 1s
INFO[0004] database ping failed. retry in 1s
INFO[0005] database ping failed. retry in 1s
INFO[0006] database ping failed. retry in 1s
```

@tboerger based on Alpine, Debian, Busybox?

**Comment by bradrydzewski** [comment]
@valentinbud can you confirm the `/etc/hosts` file is created by Docker inside the running Drone container?

**Comment by bradrydzewski** [comment]
@valentinbud also you mentioned you verified connectivity, however, the example you provided used the IP address instead of the hostname. Are you able to verify connectivity using linked containers and the hostname using the same command below?

```
$ docker run -it --link drone-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U drone'
```

**Comment by valentinbud** [comment]
@bradrydzewski I have tried it both with IP address and hostname of linked container. Same result.

```
docker run -it --link drone-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U drone'
Password for user drone:
psql (9.5.0)
Type "help" for help.

drone=#
```

I have just received a new error before the drone container finally gave up and exited.

```
INFO[0029] database ping failed. retry in 1s
ERRO[0030] pq: SSL is not enabled on the server
FATA[0030] database ping attempts failed
```

Should SSL be enabled and properly configured on the Postgres server?

**Comment by bradrydzewski** [comment]
you could try adding `?sslmode=disable` per this stackoverflow:
http://stackoverflow.com/questions/21959148/ssl-is-not-enabled-on-the-server

**Comment by valentinbud** [comment]
@bradrydzewski I am still wandering how could I check inside the container the if `/etc/hosts` exists, since the container doesn't even have `cat` or anything else for that matter.

Although I have used `docker inspect`. I am running `drone/drone:0.4` in a separate tmux pane interactively.

```
$ docker inspect modest_colden | grep Hosts
    "HostsPath": "/mnt/sda1/var/lib/docker/containers/619e421ae826df3a8696fd0384425679b19bf09781ef947254fa25ffff03b772/hosts",
 $ docker-machine ssh dev sudo cat /mnt/sda1/var/lib/docker/containers/619e421ae826df3a8696fd0384425679b19bf09781ef947254fa25ffff03b772/hosts
172.17.0.3      619e421ae826
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      postgres dbae54a6ef34 drone-postgres
```

**Comment by valentinbud** [comment]
@bradrydzewski thanks! It works with hostname and IP address once I add `?sslmode=disable`. 

Just to answer myself, security wise, TLS should be properly configured and enabled throughout the infrastructure.

**Comment by bradrydzewski** [comment]
> Just to answer myself, security wise, TLS should be properly configured and enabled throughout the infrastructure.

You should be fine as long as your are running Drone and Postgres on the same machine and not exposing Postgres. If you decide to expose Postgres or run on a separate server, requiring a remote connection, you should definitely consider TLS mode.

This would require you to setup certificates with Postgres and then to mount those certificate files into the Drone container using Docker volumes. You can then reference these certificate files using the following parameters in your Postgres connection string:

* sslcert - Cert file location. The file must contain PEM encoded data.
* sslkey - Key file location. The file must contain PEM encoded data.
* sslrootcert - The location of the root certificate file. The file must contain PEM encoded data.
Valid values for sslmode are:

More information at https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters

**Comment by valentinbud** [comment]
@bradrydzewski thank you for the extra valuable information. For now they both run on the same machine and Postgres doesn't expose its port. I am definitely going to configure TLS on all services once I go multi machine.

**Comment by Dids** [comment]
@bradrydzewski Any idea why this would also be happening with sqlite3? Same error on multiple containers using default settings and a host mounted volume.

**Comment by tboerger** [comment]
@Dids let me guess, you are using some kind of Centos/Fedora/Atomic/Redhat? Than your volume just needs a `Z` flag, e.g. http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

This is related to SELinux.

**Comment by Dids** [comment]
@tboerger Just regular old Ubuntu. I'm running HAProxy and two instances of the Drone container for both Github and Bitbucket.

**Comment by bradrydzewski** [comment]
@Dids the only known scenario that can cause the sqlite3 database connection failure is when the volume is not properly mounted. The root cause of such issues can be the following:

* volume is not correctly mounted per the documentation
* volume is not correctly mounted due to OS restrictions (known issues with SE linux per @tboerger)
* volume is correctly mounted, but database configuration environment variables are misconfigured

There are of course other scenarios, unrelated to drone or docker, that could cause sqlite database connections to fail. For example, two separate OS processes both trying to lock the database file for writes.

To further troubleshoot we need to see the actual database error message, which is not included in the message pasted above. Drone will attempt to connect to the database 30 times and will then print the database error message, from sqlite. Without this message we can only speculate.

**Comment by Dids** [comment]
@bradrydzewski Here's what's essentially my Docker compose file (I use Tutum/Docker Cloud):

```
misc-drone-bitbucket:
  image: drone/drone:0.4
  expose:
    - "8000"
  environment:
    - HTTP_CHECK=HEAD / HTTP/1.0
    - VIRTUAL_HOST=http://bitbucket.drone.my-domain.com
    - VIRTUAL_HOST_WEIGHT=2
    - REMOTE_DRIVER=bitbucket
    - REMOTE_CONFIG=https://bitbucket.org?client_id=my-client-id&client_secret=my-client-secret
    - DATABASE_DRIVER=sqlite3
    - DATABASE_CONFIG=/var/lib/drone/drone.sqlite
    #- DEBUG=true
    #- GIN_MODE=debug
  volumes:
    - /data/drone_bitbucket:/var/lib/drone
    - /var/run/docker.sock:/var/run/docker.sock
  tags:
    - misc
  restart: always
```

I never saw any sqlite errors, but I did notice that if I redeploy the container, it correctly creates the directories on the second launch/deploy. I've seen this before with Tutum though, so I'm assuming it's a Docker Compose issue (or a Tutum issue for that matter).

At any rate, it's not letting me go any further, still stuck on *503 Service Unavailable* with no error messages in the container logs.

**Comment by Dids** [comment]
Solved all of my issues by moving to a custom Rancher setup. No issues with volumes and everything just works.

**Comment by firrae** [comment]
Hi there,

So I just went to try and get Drone working on my personal server and I've gotten the docker image downloaded and everything set up EXACTLY as http://readme.drone.io/setup/overview states. When I do the docker run command I get 2 errors back after a bit of a wait:

```
time="{timecode}" level="error" msg="unable to open database file"
time="{timecode}" level="fatal" msg="database ping attempts failed"
```

I've tried making an empty database file while defining the sqlite3 database driver. Is there something I'm doing wrong?

To clarify I'm pretty well retyping EXACTLY what is in the guide and getting these errors. I have created the dronerc file and populated it with my Github credentials.

**Comment by bradrydzewski** [comment]
`unable to open database file` happens when sqlite3 cannot create the database because the parent directory does not exist. The default directory for the database, `/var/lib/drone`, does not existing in the container and must be mounted as a volume, per the docs. This can be done with the following flag when starting the drone container `--volume /var/lib/drone:/var/lib/drone`

**Comment by Dids** [comment]
@firrae Where are you deploying the containers? Docker Cloud (previously Tutum) has volume issues when deploying, esp. on the first deployment.

**Comment by tboerger** [comment]
@firrae as you stated that you are deploying on your own server, which OS do you have? Maybe something from the RedHat family? There are known issues where the volume needs a speciic additional flag, e.g. `--volume /var/lib/drone:/var/lib/drone:z` or `--volume /var/lib/drone:/var/lib/drone:Z`, explained at http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

**Comment by firrae** [comment]
@bradrydzewski I have the exact line in my command as per http://readme.drone.io/setup/overview/#create-and-run-a-drone-container:68f80267fa3a50980dbb745a782b8dca. I am using that docker command verbatim. I have made sure to also create the directories where they didn't pre-exist.

@Dids I am deploying this on a private virtual server in our office. To also answer @tboerger I'm running Ubuntu 14.04 (kernel 4.X). That Ubuntu instance is virtualized on V-Sphere.

Using Ubuntu I figured would have me safe from any issue like the ones SELinux has.

**Comment by bradrydzewski** [comment]
the `unable to open database file` is a low level error from sqlite because it cannot create the database file. The two most common root causes (lack of mounted volume and SELinux) are mentioned above, however, I'm not familiar enough with the internals of sqlite to advise further. Perhaps it makes sense to post to the sqlite issue tracker to get more assistance.

**Comment by Dids** [comment]
I've seen lots of permission related issues with Docker and volumes when creating/modifying files as a non-root user. Could this be an issue here also?

**Comment by firrae** [comment]
I am using Docker via a user with sudo level access, so I'm not sure where the issue might end up. I'll go check what the sqlite issue tracker says, but sqlite seems to be running and working fine otherwise. Is there a create script I could use to premake the sqlite file so it doesn't have to technically create it?

**Comment by Dids** [comment]
No no, I was referring to the Drone dockerfile running a service as a different user which creates/modifies the sqlite file. On the host system (using volumes) this user doesn't exist, so the file permissions are wrong and cause issues.

**Comment by bradrydzewski** [comment]
@Dids drone runs as root inside the container. You are correct that running drone as non-root would cause issues, in which case drone would be broken for thousands of people :)

**Comment by bradrydzewski** [comment]
> I am using Docker via a user with sudo level access

Doesn't the Docker deamon run as root [1]? Have you made any custom configuration to your Docker installation or to its default deamon settings? Have you added any additional runtime flags?

[1] https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

> create script I could use to premake the sqlite file 

It is unlikely this would make a difference. If libsqlite cannot create the database it is unlikely it will be able to open the file with a write lock.

**Comment by Dids** [comment]
@bradrydzewski Thanks Brad, that's actually good to hear. :)

My setup is somewhat identical to @firrae, as I'm running a VM (Ubuntu 14.04), then followed the Drone docker setup word for word. Nothing crazy going on that could be causing it, apart from using AUFS with Docker.

**Comment by firrae** [comment]
@bradrydzewski I installed it via the instructions on the Docker site (https://docs.docker.com/engine/installation/linux/ubuntulinux/). From there I'm able to run Hello World and a few other very basic things so I figured it was all good and tried installing Drone.

**Comment by bradrydzewski** [comment]
@Dids @firrae have you tried doing something like `docker run --volume=/var/lib/drone:/var/lib/drone -t -i busybox /bin/sh` which drops you to a prompt and then `ls /var/lib/drone`? and `touch /var/lib/drone/foo.txt` to test the ability to access the volume and write files?

**Comment by firrae** [comment]
@bradrydzewski I can try that this evening when I have physical access to the box again.

**Comment by Dids** [comment]
@bradrydzewski Yup, I've seen it create files on the host side, so it shouldn't be that either. Other containers on the same host are using volumes just fine too.

**Comment by bradrydzewski** [comment]
I'm able to consistently reproduce this issue under three conditions:

1. incorrectly mount the volume
2. instruct sqlite3 to create the database in a folder that does not exist (usually related to number 1)
3. invalid permissions to write the file (usually related selinux or apparmor)

I would recommend you do some additional debugging to try to uncover the root cause. Here are some things I can suggest:

1. try using `docker volume create` to create a container volume instead of a host volume
2. try using a container volume like `--volume=/var/lib/drone`
3. try using `DATABASE_CONFIG=/` to avoid volumes all together and to create the database inside the container root directory (not this will not persist and should be used for debugging only)
4. try compiling your own version of drone and add debugging code. Add Go code that checks the directory and tries to write a file. Perhaps Go will provide more meaningful error messaging.

Aside from the above suggestions I'm not sure how much more I'm going to be able to help simply due to inability to reproduce. The issue also seems to be isolated to a small number of installations which makes this even more difficult to troubleshoot ... it would be much easier if everyone was having this issue, although I'm glad they aren't :)

**Comment by firrae** [comment]
Oh, apparmor, I have that installed... The official Docker install instructions says you need to have it installed. Could that be the issue?

And that's fair, this seems to be a fairly rare issue, and in my part it's likely due to me not being very advanced in my knowledge in Docker/sysadmin.

**Comment by firrae** [comment]
OK, well I restarted the VM again and now it works... That was anticlimactic...

**Comment by jamrizzi** [comment]
If you are using the drone from the rancher catalog, use database instead of localhost.  Look at the examples below.

If you are linking postgres, use it this way . . .
```
postgres://root:pa55word@database:5432/postgres?sslmode=disable
```
instead of . . .
```
postgres://root:pa55word@127.0.0.1:5432/postgres?sslmode=disable
```

If you are linking mysql, use it this way . . .
```
"root:pa55word@tcp(database:3306)/drone?parseTime=true"
```
instead of . . .
```
"root:pa55word@tcp(localhost:3306)/drone?parseTime=true"
```

**Comment by ianseyer** [comment]
Trying to deploy the latest version from the Rancher catalog or a Postgres/Github setup.

See this in the logs:
```
4/1/2017 2:39:11 PMtime="2017-04-01T19:39:11Z" level=info msg="using database driver postgres"
4/1/2017 2:39:11 PMtime="2017-04-01T19:39:11Z" level=info msg="using database config postgres://<user>:<pass>@database:5432/postgres?sslmode=disable"
4/1/2017 2:39:11 PMtime="2017-04-01T19:39:11Z" level=info msg="database ping failed. retry in 1s"
4/1/2017 2:39:12 PMtime="2017-04-01T19:39:12Z" level=info msg="database ping failed. retry in 1s"
4/1/2017 2:39:13 PMfatal error: runtime: out of memory
```

The container is stuck in a reboot cycle, and the public facing IP serves a `503`.

1. Any ideas why this is happening? Drone is the only thing running on a t2.small ec2 instance (2gb RAM), and i've tried configuring everything at least a dozen times.
2. Can we get more verbose logging?

**Comment by bradrydzewski** [comment]
> Can we get more verbose logging?

No because Go does not instrument the standard library or database drivers with logging. There is no magic flag that can automatically start dumping verbose logs (like with Java). This is the best we have.

> Any ideas why this is happening?

The error claims the server is out of memory. The error message is coming from the Go standard library which is claiming it cannot allocate memory. Why would the Go runtime not be able to allocate memory? Have you checked the server memory usage?

```
4/1/2017 2:39:13 PMfatal error: runtime: out of memory
```

> what are the "Generate" buttons for, next to github and database config? They seem to just generate nonsense.

You mean the generate button on the secrets tab? You paste your secret file and it generates the encrypted version.

**Comment by ianseyer** [comment]
I see.

How much memory should be required of the host?

Also, I am still getting the ping database issue before the memory issue.

**Comment by bradrydzewski** [comment]
> How much memory should be required of the host?

the drone server usually allocates 8mb memory to start and with cached data usually runs around 12mb idle

> Also, I am still getting the ping database issue before the memory issue.

the database ping failure simply means that the postgres driver cannot establish a connection with the postgres server. Generally this happens when perhaps the username, password, address or some other parameter in the database connection string is incorrect. Or that the server cannot be reached due to network configuration issues. Unfortunately without direct server access and knowledge of your configuration, this is not something I can troubleshoot. You can read the official postgres driver documentation for more detail https://github.com/lib/pq which may provide more insight.

**Comment by ianseyer** [comment]
I definitely have that much RAM free at runtime; it's on a 2GB machine where the only other container alive is postgres.

I have quadruple checked the configuration by reinstalling everything running on the host:
1. postgres from the catalog, dbname postgres, user and pass both postgres
2. drone from the catalog, with the postgres secret key being `postgres://postgres:postgres@database:5432/postgres?sslmode=disable` and the linked service being `postgres-lb`.

This is as vanilla as I can get the installation, and it still repeatedly tries to connect and then throws the memory error.

**Comment by bradrydzewski** [comment]
To confirm there are no issues with drone:0.4 and postgres I just downloaded and setup and instance using docker-compose file. This is as vanilla as it gets and runs without issue.

This is the exact file / configuration I used. Hopefully this helps

```
version: '2'

services:
  drone-server:
    image: drone/drone:0.4
    ports:
      - 8080:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - REMOTE_DRIVER=gogs
      - REMOTE_CONFIG=${GOGS_URL}
      - DATABASE_DRIVER=postgres
      - DATABASE_CONFIG=postgres://postgres@postgres:5432/postgres?sslmode=disable

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
```
