### ISSUE TITLE
Public Key in UI can't be copy pastesd

### ISSUE THREAD

**Issue by davidak** [drone/drone#1437]
The Identifier in the Public Key in build settings added in https://github.com/drone/drone/pull/1383 appears in a second line.
Technically it must be one line to be added to authorized_keys.

**Comment by tboerger** [comment]
I think it just looks like that, i have taken the key with copy and paste and it's not multiline.

**Comment by davidak** [comment]
i copied it and pasted in a text editor. tested with chromium and firefox.

![bildschirmfoto 2016-01-26 um 18 44 42](https://cloud.githubusercontent.com/assets/91113/12589214/f6a75dec-c45c-11e5-9883-4e5a526cd909.png)
it looks like one line in the inspector of FF but if you click on the text there, it is also 2 lines

**Comment by tboerger** [comment]
Than the public key must end with a newline :(

**Comment by bradrydzewski** [comment]
closing in preparation for 0.5 which no longer uses or provides keys. Key are not used by 0.4 but were kept for compatibility purposes. All 0.5 plugins are being updated to not rely on the presence of a key.
