### ISSUE TITLE
Whitelist Github users for PRs on public repos

### ISSUE THREAD

**Issue by siddharthist** [drone/drone#1441]
This ticket tracks @Cadair's point (1) in #1061.

A great way to secure drone builds from PR attacks on public repos is to disable automated builds except for a limited whitelist of GH users. This relies on Github's own security features, which are quite strong. 

This would allow public repos to automatically test uploads from frequent and trusted contributors without exposing themselves to the many risks of running unvetted code in Docker on their build server.

**Comment by gtaylor** [comment]
Kubernetes and most of the larger Google github projects do this with excellent results. See the Kubernetes issue tracker for an example. They use Jenkins.

**Comment by bradrydzewski** [comment]
From the other conversation but also relevant here:

> the .drone.sec file has a checksum of the yaml encrypted into the file. If the checksum doesn't match no private data is injected into the build environment, thus protecting the pull request (and non-pull requests) from those attacks

The list of trusted builders could be stored in the Yaml and the checksum would ensure it hasn't been altered in a negative way.

That being said as long as the Yaml is signed with a checksum we can safely inject secrets into certain sections of the Yaml, specifically trusted plugins. So the question comes down to this -- when we execute a pull request do we need secrets in the build section? Or just the plugin section (for sending notifications, pushing reports, etc)

**Comment by gtaylor** [comment]
Only thing that handling whitelists in .drone.yml is that it prevents more ergonomic workflows like this:

https://github.com/kubernetes/kubernetes/pull/20244

Note the k8s-bot.

**Comment by siddharthist** [comment]
@bradrydzewski For projects like [Mantl](https://github.com/CiscoCloud/microservices-infrastructure/), it would be very useful to have secrets in the build section. To effectively test, we have to build a cluster on a public cloud, which involves API keys that we don't want to expose to the public. We could (and are doing so now) write a custom plugin for this functionality, but that is time-consuming and indirect. 

That's a good thought about storing a list of trusted builders in the drone.yml file!

**Comment by bradrydzewski** [comment]
@gtaylor I think the bot is pretty cool, thanks for sharing

My only thought is that the reason we push people to plugins is because plugins don't execute untrusted code which means they cannot be configured to expose secrets. This eliminates a whole class of security issues (assuming you sign the yaml) that are otherwise a problem with Travis or Jenkins.

@siddharthist I think this is the beauty of plugins and why we have them, so that we don't need to build everything into Drone core. I want as much as possible in plugins, and as little as possible in Drone core.

**Comment by siddharthist** [comment]
@bradrydzewski Of course if you're not interested in having this functionality as a part of drone's core, please feel free to close this PR. 

Is it possible to develop a plugin that would dictate under what conditions drone would move to the build phase?

**Comment by bradrydzewski** [comment]
In fact, as a follow-up, I think this would make a fantastic plugin, or even multiple plugins. The reason I could see this as multiple plugins is that some teams might want to use a maintainers file in their repo, some teams might want to use a GitHub organization team, etc. Plugins allow for this type of flexibility.

I'm not sure Drone is optimized at the moment for this sort of a plugin (running plugins before a build), however, that is a change I would definitely support.

**Comment by siddharthist** [comment]
Ah, jinx. I'll open a new ticket for introducing that functionality and close this one.

**Comment by bradrydzewski** [comment]
@siddharthist awesome!  I realize it isn't the exact functionality you were looking for, but hopefully it seems like a good compromise. We can definitely work together to add one (or more) of these sort of plugins to the official plugin registry.

I'm actually really excited about this.

@gtaylor I think we could definitely achieve something similar to the Kubernetes bot. It would likely be a separate service that would be registered with your repository, and that the plugin would invoke, but I think it should be possible if we expose the right hooks from Drone.

**Comment by gtaylor** [comment]
Yeah, being able to easily drop a plugin in with whatever behavior you're looking for would be pretty slick.
