### ISSUE TITLE
Error response from daemon: Wrong login/password, please try again

### ISSUE THREAD

**Issue by kenden** [drone/drone#1446]
When building a docker image, following these instructions: http://addons.drone.io/docker/

I am reading the docker password from an environment variable, but it is like substituting the variable in the .drone.yml doesn't work (this variable: $$REGISTRY_PASS, below)

I have a  .drone.yml file with the following:
```
debug: true

publish:
  docker:
    username: myuser
    password: $$REGISTRY_PASS
    email: myuser@mycompany.com
    repo: mycompany/myrepo
    tag: 'v66666789'
    file: Dockerfile
```

And I have a /etc/drone/dronerc file with:
```
REMOTE_DRIVER=github
REMOTE_CONFIG=https://github.com?client_id=123edited123&client_secret=add9f1ea03edited07ae52d255

REGISTRY_PASS=mypassword
```

After starting drone with:
```
 sudo docker run \
	--volume /var/lib/drone:/var/lib/drone \
	--volume /var/run/docker.sock:/var/run/docker.sock \
	--env-file /etc/drone/dronerc \
	--restart=always \
	--publish=80:8000 \
	--detach=true \
	--name=drone \
	drone/drone:0.4
```

When running a build, it fails with:
Error response from daemon: Wrong login/password, please try again

But if I replace '$$REGISTRY_PASS' by 'mypassword' in the yml file, it builds fine.
I don't want to have my docker password in the github repo though.

The env-file appears to be read properly:
I see the following when I run 'sudo docker inspect drone':
```
"Config": {
        .....
        "Env": [
            "REMOTE_DRIVER=github",
            "REMOTE_CONFIG=https://github.com?client_id=123edited123&client_secret=add9f1ea03edited07ae52d255",
            "REGISTRY_PASS=mypassword",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DATABASE_DRIVER=sqlite3",
            "DATABASE_CONFIG=/var/lib/drone/drone.sqlite"
        ],
        "Cmd": null,
        "Image": "drone/drone:0.4",
        ...
```

If there a way for me to troubleshoot this further? Can see what values where used in the yml file?
Is anyone having the same issue?

**Comment by bradrydzewski** [comment]
drone does not read `$$REGISTRY_PASSWORD` from environment variables, it reads them from the secrets file. Please see http://readme.drone.io/usage/secrets/ for more details.

**Comment by kenden** [comment]
Great, thanks for the super fast answer!
I suggest a link from http://addons.drone.io/docker/ to http://readme.drone.io/usage/secrets/ next to the mention of $$DOCKER_PASSWORD so no one else trips on this. (Although now, this bug can be found on google).
http://addons.drone.io/docker/ also matches https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md, but it's a different version, where would one look to change it?

**Comment by conradkleinespel** [comment]
If you land on this issue because you're having problems with a private registry, make sure you have set the `registry` item, like so :
```yaml
publish:
  docker:
    username: myuser
    password: $$REGISTRY_PASS
    email: myuser@mycompany.com
    registry: my-registry.com
    repo: mycompany/myrepo
    tag: 'v66666789'
    file: Dockerfile
```
