### ISSUE TITLE
After switching drone from http to https github hook does not work anymore

### ISSUE THREAD

**Issue by talon-vonneudeck** [drone/drone#1450]
A new key did not help, neither did restarting drone.
It was necessary to delete the repository and to add it again to fix this.

**Comment by bradrydzewski** [comment]
this is because when you added the hook to GitHub it was http. If you change the hook to https every hook in GitHub needs to be updated. Not sure this is a drone issue

**Comment by talon-vonneudeck** [comment]
True. I understand your point. But I did update the hook in GitHub.
Also after deleting the everything by using the button in the settings drone showed a message that no repos where added but also did not send me or my users to mydroninstance.com/authorize. Everyone has to go there manually and reauthorise drone.
I wonder if drone could ask by itself to reauthorise if there is no valid authorisation so that this could be avoided.
