### ISSUE TITLE
Yaml Improvements for Version 0.6

### ISSUE THREAD

**Issue by siddharthist** [drone/drone#1452]
There's a lot of discussion on #1443 re: a new format for drone configuration, hopefully minimizing the number of unique steps in favor of a uniform pipeline, with scripting capabilities. Let's discuss this architecture and our ideas on this ticket prior to an RFC.

**Comment by bradrydzewski** [comment]
I'm going to close and re-open a new issue so I can include some ground rules... I'm anticipating that I will otherwise get a large number of proposals for changing the yaml without taking into consideration certain design constraint, historical learnings, etc

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone/drone/issues/1505
