### ISSUE TITLE
When docker fails to pull image and build.pull is set to true, drone uses cached image.

### ISSUE THREAD

**Issue by unikoid** [drone/drone#1454]
Hello,

I tried to use Drone and found the following issue.
If you specify `pull: true` in your .drone.yml and drone fails to pull specified image for whatever reason, drone executes all build steps with the image from local docker cache, despite the fact that this cached version may be obsolete.
I don't think this behaviour is correct since the goal of `pull` parameter is to ensure that build is always in up-to-date environment.

Problem source seems to be here, https://github.com/drone/drone-exec/blob/master/docker/util.go#L101 . There is no error handling for PullImage call, so if it fails, this fact is just ignored.

If you confirm this is a real bug, I'll try to provide a pull-request to fix this later.

**Comment by tboerger** [comment]
IMHO it should not fail because of that, but some log message that it failed and falls back to the cached version should be helpful.

**Comment by bradrydzewski** [comment]
@tboerger agreed, I view this as working as expected. In the event DockerHub is unavailable we expect Drone to fallback to the local cache and continue with the build. Note that plugins automatically re-pull on every build as well, so this doesn't just impact images with `pull: true`

**Comment by unikoid** [comment]
Ok, I understand your point.
But my actual case was not about DockerHub. I've used base image from private docker registry both for build and test my project in Drone and for production environment. One day this base image has been removed from registry and I didn't know about this as my Drone builds were successful. And when I attempted to build production docker image I realized that there is no more base image in registry and I must switch to another.

I understand that my case is rather special and that it is not good practice to remove images from docker registry. But this is the reason why I don't think it's good idea to continue build if latest base image version is required and we are not really certain that this requirement is fulfilled.

**Comment by bradrydzewski** [comment]
the main issue is that our plugins use this auto-pull functionality. Since plugins are core to Drone -- they handle cloning, caching and more -- any changes to the plugin behavior has a cascading effect. Since the desired behavior is continue a build if a newer version of the plugin cannot be pulled, we are unable to change this behavior for build images.

I appreciate you explaining the use case in more detail, but unfortunately we can't make any changes to this behavior in the interest of not adversely impacting plugin behavior.
