### ISSUE TITLE
changing worker pool requires restart?

### ISSUE THREAD

**Issue by mjschultz** [drone/drone#1455]
I'm working on getting an autoscaling group up and running with drone. Right now I'm able to bring up a new instance and add the workers via the drone cli (`drone node create`). I then remove all the `unix:///var/run/docker.sock` workers so I only have the remote worker available. When I attempt to rebuild an existing build, drone seems to try to assign it to the local socket (without success).

Once I restart the drone container (via `docker restart drone`), and attempt to rebuild the existing build it assigns to the remote worker properly.

Similarly when I re-add the local socket and remove all the remote workers and attempt a restart I need to go through the same path.

This seems like the pool is allocated statically at startup but the workers themselves are checked at runtime?

**Comment by bradrydzewski** [comment]
There is a known issue that removing nodes from a queue requires a restart, because they remain on the Go channel. Adding nodes to the queue does not require a restart. This is covered in #1386 which is replacing the current queue mechanism in 0.5 (next release).
