### ISSUE TITLE
Save artifacts between build steps

### ISSUE THREAD

**Issue by emilebosch** [drone/drone#1457]
Let's say i have a static website generator. The image to generate the images (its ruby yes). Is about a 100MB. And the actual output of the build just about 5.

I would love to have 2 build steps. One where i can generate the output, save it somewhere and a second one where i can package it in a docker container.

Is there someway to save these artifacts between build steps? Thanks.

**Comment by bradrydzewski** [comment]
these sort of questions should use https://discuss.drone.io or https://gitter.im/drone/drone
