### ISSUE TITLE
Cache limit

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1458]
The drone cache used all of my disk. Perhaps there should be some limiting to maximum size of the entire cache?

**Comment by bradrydzewski** [comment]
I'd like to create a `drone-cleanup` utility similar to [docker-custodian](https://github.com/Yelp/docker-custodian) but that is optimzed for build servers. This would include cache management, removing untagged images, etc

**Comment by nodesocket** [comment]
Any idea when this is going to push? Can't the build automatically do cleanup? I.E. when a build is triggered, as the last step, purge cache older than 48 hours?

**Comment by marceldegraaf** [comment]
Hi @bradrydzewski, are there plans to release a `drone-cleanup` utility soon? My drone cache is currently using ~60GB disk space.

In the meantime, how can I clean up the cache manually (or with cron) to make sure the build server doesn't run out of disk space entirely?

**Comment by marceldegraaf** [comment]
Addendum: I could let cron delete all `cache.*.tar` files older than e.g. 48 hours from `/var/lib/drone/cache/`. Would that work, or is that too naive and will it break future builds depending on these older cache files?

**Comment by tboerger** [comment]
> Addendum: I could let cron delete all cache.*.tar files older than e.g. 48 hours from /var/lib/drone/cache/. Would that work, or is that too naive and will it break future builds depending on these older cache files?

That should work as drone just rebuilds a cache if it's missing. In worst case you will have a longer build time because of the cache rebuild.

**Comment by marceldegraaf** [comment]
Great, thanks. I'll look into that and share the cron script here once I have something working.

**Comment by mjschultz** [comment]
We just do something like `sudo find /var/lib/drone/cache -atime +7 -delete` which will delete any drone cache file that hasn't been accessed in the last wee, if that helps.

**Comment by marceldegraaf** [comment]
Yeah, that's exactly what I'm adding to our CI server now, too. Thanks for sharing :smiley:

**Comment by nodesocket** [comment]
Here is what I just implemented in `crontab`:

```
# Every Sunday at 3:00am, delete Drone cache not accessed within the last 5 days
0 3 * * 7 find /var/lib/drone/cache -atime +5 - delete
```

**Comment by bradrydzewski** [comment]
the cache plugins can now purge history thanks to https://github.com/drone/drone-cache-lib/pull/1 from @jmccann
