### ISSUE TITLE
Drone notification plugin incorrectly report success after matrix build

### ISSUE THREAD

**Issue by fracting** [drone/drone#1459]
Here is a matrix build on my Drone CI server:

http://wine-ci.org/Alexpux/MSYS2-packages/9/2

The first task fails, the second task successes. 
Github correctly recognize this task group as a failure build, but drone irc plugin sent a `success` report to my irc channel. 

https://github.com/Alexpux/MSYS2-packages/pull/436

VS

```
MSYS2-packages> [build Alexpux/MSYS2-packages#41073392] success on dummy-test-for-rsync by fracting (http://wine-ci.org/Alexpux/MSYS2-packages/9)
```

**Comment by bradrydzewski** [comment]
@fracting I'm not having this issue with notification plugins. Have you made any customizations to drone or drone-exec that might alter its default behavior and introduced a bug?

**Comment by fracting** [comment]
@bradrydzewski yes, i have made customization on both drone and drone-exec:

https://github.com/fracting/drone
https://github.com/fracting/drone-exec

Apologize for not mention it earlier. Maybe this is my own fault, would you mind keep this issue open for a few days and wait for my investigate result? Or if you have advice where to look at that would be also great appreciated. Thanks!

**Comment by gtaylor** [comment]
To help manage issue tracker clutter, might be worth closing this issue and re-opening it if you find anything.

**Comment by fracting** [comment]
Make sense, thanks for comment!

**Comment by fracting** [comment]
I'm able to reproduce this issue with drone 0.4.2 without any customize.

Here is the link http://ec2-52-53-253-179.us-west-1.compute.amazonaws.com:8888/fracting/xz/2/4

```
debug: true
build:
  image: drone/golang:1.5
  pull: true
  commands:
    - if [ $$id = 1 ]; then (exit 1); fi
    - if [ $$id = 2 ]; then (exit 1); fi
    - if [ $$id = 3 ]; then (exit 1); fi
    - if [ $$id = 4 ]; then (exit 0); fi

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  id:
    - 1
    - 2
    - 3
    - 4
```
This time I'm testing with drone-gitter plugin, so it is not caused by any special plugin.

![drone-gitter](https://cloud.githubusercontent.com/assets/194342/16346447/fcca3760-3a79-11e6-9620-d571dd511bfb.png)

I'm re-opening this issue since I eventually have chance to test upstream Drone after 4 months...

Anyone mind have a look?

**Comment by bradrydzewski** [comment]
0.4.2 is frozen with 0.5 now in master. Even if such an issue exists, which I haven't been able to repeat, it wouldn't get backported at this time.

**Comment by fracting** [comment]
@bradrydzewski is there a drone service I can test with drone 0.5? Could you give me access to beta.drone.io or similar things?
