### ISSUE TITLE
[0.4] Drone repo page responds with 404 instead of 403

### ISSUE THREAD

**Issue by Jean85** [drone/drone#1465]
I'm using GitLab login integration. I have a browser bookmark pointed to Drone's repo page. When the login fails, Drone responds with a 404 (not found) instead of a 403 (Unauthorized) or (better) redirecting to the login page, as it happens if I open Drone's homepage.

**Comment by gtaylor** [comment]
Looks like a dupe of #1266.

**Comment by bradrydzewski** [comment]
closing as duplicate, please subscribe to #1266
