### ISSUE TITLE
DNS  issue: no such host.

### ISSUE THREAD

**Issue by vando** [drone/drone#1466]
I have this error message for Drone 0.4

```
[GIN] 2016/02/05 - 16:05:40 | 303 |    1.386974ms | XXX.XXX.XXX.XXX:47009 |   GET     /authorize
time="2016-02-05T16:05:40Z" level=error msg="cannot authenticate user. Error exchanging token. Post https://github.com/login/oauth/access_token: dial tcp: lookup github.com: no such host"
```

Even if I forced an IP address or I used Google's DNS, I found that the DNS query doesn't exist (sniffing the Docker's virtual interface).

I don't have any firewall rule for dropping or reset connections and I don't use a proxy. 

And if I run `drone_static` outside of Docker, I have this message

```
[GIN] 2016/02/05 - 15:27:38 | 303 |    1.157281ms | XXX.XXX.XXX.XXX:62817 |   GET     /authorize
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7f31563ac4fc]

runtime stack:
runtime.throw(0xda6020, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
```

(all lines in in this gist: [#46a5d59](https://gist.github.com/vando/46a5d593a1ac8abc5b22))

Related info:

* **OS:** Debian 8.3 (jessie) 64bits
* **Kernel**: 3.16.0-4-amd64
* **Docker:** 1.9.1 (build a34a1d5)

**Comment by bradrydzewski** [comment]
please subscribe to https://github.com/drone/drone/issues/1435 ... this seems to have impacted a very small subset of Drone installations and I'm unable to repeat, so any additional debugging is very appreciated.

the panic seems to hide the error, but this happens when it fails to run `http.ListenAndServe` which typically happens if the port can't be opened. So you might want to check permissions and if the default port is already in use.

**Comment by vando** [comment]
I attached a debugging log that covers first time login at Drone service: [drone.debug.txt](https://github.com/drone/drone/files/119874/drone.debug.txt).

For the panic error I exported  `SERVER_ADDR=":8000"`, this port isn't in use but error still happen.

**Comment by bradrydzewski** [comment]
did you try compiling drone from scratch?

**Comment by vando** [comment]
I extracted it from the docker container.

**Comment by bradrydzewski** [comment]
I'd recommend building from source for your host environment. Also closing and merging this with #1435

**Comment by vando** [comment]
[I did it](https://github.com/vando/docker-drone) and now it works. Thanks @bradrydzewski
