### ISSUE TITLE
Expose duration in UI

### ISSUE THREAD

**Issue by chuyskywalker** [drone/drone#1469]
I'd like to know how long the overall build took to run. Exposed in the build list and in the individual build pages themselves. 

Timestamping output in the build log itself would also be useful (to help narrow down slow build sections).

There's a great Jenkins plugin called [Timstamper](https://wiki.jenkins-ci.org/display/JENKINS/Timestamper) which provides these timestamps, but also a sidebar toggle that lets you switch between absolute and relative.

**Comment by bradrydzewski** [comment]
subscribe to #1298

**Comment by bradrydzewski** [comment]
btw, meant to mention that similar to timestamper, docker eposes a timestamp to each line in the logs which I'm hoping to capture in the 0.5 release

**Comment by chuyskywalker** [comment]
Curse me for searching on "duration" and not finding it! Thanks.

**Comment by bradrydzewski** [comment]
heh, no worries. I did the same thing and couldn't find it when I search for duration. Luckily I remembered who opened the original issue :)
