### ISSUE TITLE
Implement proper Caching

### ISSUE THREAD

**Issue by skorfmann** [drone/drone#147]
I was playing around with Drone.io over the weekend and I'm really impressed. 

However, there is one big issue for our Rails project: Bundling all the Gems (~ 250 Gems, where about 10 of these are git checkouts) takes about 10 minutes for each build, as I've found no way to provide a cacheable directory to Bundler.

I've seen the issues #43 and #143, but as far as I understood the solution proposed in #43, the cache would only be invalidated when the actual setup commands have changed. In my case, it would need to re-run the commands when the content of the project's ```Gemfile.lock``` has changed.

Furthermore, it would be neat to be able to share a cache directory between different projects. In our current Jenkins setup, we're sharing a global Bundler directory, which speeds up new project builds enormously. 

Here is an excerpt of our build file:

```bash
BUNDLE_PATH="$JENKINS_HOME/shared/bundle"
bundle install --path="$BUNDLE_PATH"
```

**Comment by kylewelsby** [comment]
I would really like for my build to run faster, all the `npm install` and `bundle install` slows the builds down considerably. 
Could drone have a local HTTP cache/mirror or something for regular requests to known services.

**Comment by glaszig** [comment]
i am doing a `ls -la` before `bundle install` in the `script` phase and the cache directory is _always_ empty.

**Comment by nathwill** [comment]
it looks like the cache is currently branch-specific, which makes it awkward for feature-branch based PRs, as the cache gets duped for every feature branch, but doesn't have the advantage of faster builds

**Comment by bradrydzewski** [comment]
Per branch caching is removed per #912 (thanks @nathwill)

Note that #902 will expose much more of the underlying Docker implementation and will allow mounting volumes from the yaml file. So #902 will end up replace the `cache` section with a `volumes` section.

We're also working on modularity and plugins. The `git clone` functionality is being moved to a plugin:
https://github.com/drone-plugins/drone-git

This will give us much more flexibility and should allow us to perform a `git checkout` instead of a `git clone` if a `.git` directory already exists. This would allow us to start caching the repository root. Stay tuned.

**Comment by davidak** [comment]
consider this:

you have cached installed dependencies and run a build again. since the last build the dependencies have changed.

so we have to run the commands from setup section again to update the dependencies. that would be still faster than installing all again.

**Comment by glaszig** [comment]
@nathwill #912 does not seem to change anything for me. i'm a little confused now -- is this still a work in progress or should the simple case of sharing one folder (for rubygems) basically work?

as afore-remarked, `ls -la` on the cache folder yields an empty one, each and every build.

**Comment by nathwill** [comment]
@glaszig #912 changes the cached folder from per-repo-branch to per-repo, but is still repo specific, and not generic to the build-box (maybe you're testing different repos?). you can also poke around under /tmp/drone on the build host and find the cached directory for direct inspection.

in any case, it's definitely working on our system; maybe you can share your .drone.yml and drone version?

**Comment by glaszig** [comment]
> #912 changes the cached folder from per-repo-branch to per-repo, but is still repo specific, and not generic to the build-box

alright. that's what i read from the code; what i expected.

> maybe you're testing different repos?

no. always the same. only different branches. so, i should see your changes having an effect.

> you can also poke around under /tmp/drone on the build host and find the cached directory for direct inspection.

yeah. there's a folder structure there and also my `cache` folder. but it is empty.

> maybe you can share your .drone.yml and drone version?

```
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-24-generic x86_64)

# docker -v
Docker version 1.4.0, build 4595d4f

# drone -v
drone version 0.3.0-alpha
```

drone.yml  
```
image: drone/ruby
env:
  - RAILS_ENV=test
cache:
  - /tmp/bundler
script:
  - rbenv versions
  - pwd
  - ls -la /tmp/bundler
  - cp config/database.drone.yml config/database.yml
  - sudo chown -R ubuntu:ubuntu /tmp/bundler
  - sudo chmod -R ug+rw /tmp/bundler
  - bundle install --path /tmp/bundler
  - bundle exec rake db:create
  - bundle exec rake db:schema:load > /dev/null
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec
services:
  - mysql
```

**Comment by nathwill** [comment]
seems right to me, but i noticed that the drone version didn't update when my patch went in... the version i have installed is:

```
[root@drone01.prod ~]$ rpm -q drone
drone-0.3.0_alpha-1427045373.x86_64
```

outside of that, i've no idea why it might not be caching for you.

**Comment by glaszig** [comment]
same version. somehow can't get the cache working. giving up for now.

```
# apt-cache showpkg drone
Package: drone
Versions:
0.3.0-alpha-1427045373
```

**Comment by glaszig** [comment]
follow-up.

during a build today i ran `docker inspect` on the container.

```
# docker inspect 5c6bc2baaa1b
[{
...
    "HostConfig": {
        "Binds": [
            "/tmp/drone/github.com/jamii-Technologies/vipcall_controller/tmp/bundler:/tmp/bundler"
        ],
...
    "Volumes": {
        "/tmp/bundler": "/var/lib/docker/vfs/dir/03b72641890f9e5fb837db1adc74d2519fc2c06203aa99f4b5d7d132edeb6b4b"
    },
    "VolumesRW": {
        "/tmp/bundler": true
    }
}
]
```

what i see there is an assumably correct `HostConfig.Binds` entry.  
What looks suspicious to me (as someone not knowing enough about docker internals) is the `Volumes` entry pointing to a folder in `/var/lib/docker/vfs/dir`. I then took a look into that folder on the host machine and found 136 such folders, presumably for each drone build, which eventually contained the gems installed during the build.

Drone/docker is writing the content of my cache folder to a new directory during every build. That's why the cache is always empty.

Any idea what is wrong here?

**Comment by abtris** [comment]
I think `VOLUMES` are not used in `docker build` only in `docker run`.

**Comment by bradrydzewski** [comment]
update: @donny-dont has been working on proper caching, including the ability to cache portions of the git directory (which prior to his changes complains if you clone into a non-empty directory). I think this will take time to perfect, but it will be a really good start

**Comment by donny-dont** [comment]
Hoping to get through the pull request process today and then this should be closed. Will write some docs around it too.

**Comment by donny-dont** [comment]
https://github.com/drone-plugins/drone-git/pull/1 is needed for caching as `git clone` cannot happen in a non empty directory. This changes the behavior to use `git init` which allows the caching volumes to be present.

**Comment by donny-dont** [comment]
Alrighty https://github.com/drone-plugins/drone-git/pull/1 is merged just need to write docs and this can close.
