### ISSUE TITLE
Open registration is broken.

### ISSUE THREAD

**Issue by politician** [drone/drone#1470]
I've tried a dozen different ways to login to drone, but continue to receive "registration is closed" errors.

```Bash
$ journalctl -u drone-test
Feb 08 02:54:37 xxxx-d-app-05 sh[18000]: REMOTE_DRIVER=bitbucket
Feb 08 02:54:37 xxxx-d-app-05 sh[18000]: REMOTE_CONFIG=https://bitbucket.org?open=true&orgs=gratafy&client_id=xxxxxxx&client_secret=yyyyyy

/* ... snip ... */

Feb 08 02:56:49 xxxx-d-app-05 sh[18028]: [GIN] 2016/02/08 - 02:56:49 | 303 |     169.701µs | 50.170.10.22 |   GET     /authorize
Feb 08 02:56:52 xxxx-d-app-05 sh[18028]: time="2016-02-08T02:56:52Z" level=error msg="cannot register politician. registration closed"
```

Looking in the code, I can clearly see that the `REMOTE_CONFIG` variable should be parsed as a URL whose query parameters match my values. (https://github.com/drone/drone/blob/master/remote/bitbucket/bitbucket.go#L45)

I can also clearly see that `Login` will simply passthrough this `open` variable. (https://github.com/drone/drone/blob/master/remote/bitbucket/bitbucket.go#L124)

I also see that the error reported in the logs will only occur (https://github.com/drone/drone/blob/4a85f4029c30c59ce81426dcff0ca4dbd3b5df90/controller/login.go#L52) when the database doesn't contain this user and the open flag is false (it's true!) and the database contains more than one user - it's a new database that should be empty.

Can you add some code to log the values read from REMOTE_CONFIG? I see that you're using logrus -- try `log.WithFields({"remote_config": obj}).Info("Found REMOTE_CONFIG. Here's the values I found.")`.

I suspect that despite all of this very plain and obvious code, open is being set to `false`.

**Comment by politician** [comment]
Well, I fixed it.  It turns out that I had volume mounted the underlying database.  After deleting it and restarting the service, I was able to register.

However, I'm not sure if I should close this issue.  It seems like `REMOTE_CONFIG` isn't being honored when a database exists.  That seems like a bug.

**Comment by bradrydzewski** [comment]
closing as unable to repeat. I'm running the latest version and remote_config is being honored for auth, repo permissions, hooks, etc. If you can come up with a repeatable config we can re-open

**Comment by politician** [comment]
Will do.
