### ISSUE TITLE
Change name / location of .drone.yml 

### ISSUE THREAD

**Issue by iammerrick** [drone/drone#1475]
[Is there a way to change the location of the .drone.yml file](http://stackoverflow.com/questions/35304898/change-location-of-drone-yml)

Looking at the source code ( though I don't know go) it appears the look up for .drone.yml only occurs at the root of the repository and is not searched for recursively correct?

**Comment by xiaods** [comment]
see drone/server.go,  the DRONE_PATH can be specified.
60 ^I^Icli.StringFlag{                                                            
 61 ^I^I^IEnvVar: "DRONE_YAML",                                                    
 62 ^I^I^IName:   "yaml",                                                          
 63 ^I^I^IUsage:  "build configuraton file name",                                  
 64 ^I^I^IValue:  ".drone.yml",                                                    
 65 ^I^I},

**Comment by tboerger** [comment]
@xiaods but that is a 0.5 feature, that wasn't available on 0.4

**Comment by bradrydzewski** [comment]
closing since this is solved in 0.5
