### ISSUE TITLE
Gitlab 8.5.0-rc1 does not work: Unexpected EOF

### ISSUE THREAD

**Issue by kri5** [drone/drone#1477]
Drone fails to launch builds trigger by gitlab 8.5.0-rc1, which is the gitlab.com production version.

We get the following error : `failure to get .drone.yml for myOrg/myRepo. unexpected EOF`

The line from which the error comes is https://github.com/drone/drone/blob/ef8f236175da41f2d12c8614936a9c41d6f3f80b/controller/build.go#L185

Any ideas?

**Comment by bradrydzewski** [comment]
does this work with prior gitlab releases? if yes, perhaps we need to troubleshoot at the gitlab level?

**Comment by kri5** [comment]
Yes it seems to work with prior versions of gitlab, as i haven't changed the drone setup in weeks, but we use gitlab.com, so we do not control which version of gitlab-ee they run.

I tried to take a look at commits which would have inpacted the gitlab api, but i could'nt figure out something.

**Comment by bradrydzewski** [comment]
Perhaps they introduced a bug? In this case it seems to fail to download the yaml file using the API. Maybe they can check their logs to see why that API call would fail? or if there is something we need to change with how we invoke that API for the latest GitLab version?

**Comment by kri5** [comment]
I'll try to add debug on drone side tomorrow to try to figure which call exactly fails

**Comment by Bugagazavr** [comment]
@kri5 thanks, yep this is a gitlab 8.5.0 rc1 glitch, i tried to fetch drone.yml direct via api and got

```curl: (18) transfer closed with 177 bytes remaining to read```

**Comment by bradrydzewski** [comment]
@Bugagazavr thanks for verifying this

**Comment by Bugagazavr** [comment]
@kri5 @bradrydzewski gitlab knows about this bug, this should be fixed in rc2 https://gitlab.com/gitlab-org/gitlab-ce/issues/13350#note_3684359

**Comment by bradrydzewski** [comment]
great, I'm going to close this since it is a gitlab issue
