### ISSUE TITLE
Problem with Gogs avatars

### ISSUE THREAD

**Issue by kop** [drone/drone#1487]
Hi,
I have a problem with Gogs 0.8.25 <-> Drone 0.4.0 integration.
I think it's related to #1263.

The problem is that Drone is rendering wrong URL's for Gravatar avatars:

```
http://gogs.domain.com/https://secure.gravatar.com/avatar/1a397956970bf0945881510b7f5280ae
```

Custom avatar images are working ok.

**Comment by bradrydzewski** [comment]
yes, I've noticed something changed in the latest Gogs release that has broken avatars. It likely has something to do with this code:
https://github.com/drone/drone/blob/master/remote/gogs/helper.go#L122

and related unit test:
https://github.com/drone/drone/blob/master/remote/gogs/helper_test.go#L146

**Comment by kop** [comment]
Just reviewed a webhook sent by Gogs. This URL comes from the webhook, so it's definitely Gogs fault. And it seems it's fixed already: https://github.com/gogits/gogs/issues/2630

So issue can be closed, thanks.
