### ISSUE TITLE
drone doesn't allow to run a custom user on build commands

### ISSUE THREAD

**Issue by zavalit** [drone/drone#1489]
Hi,
In my Docker image i introduced another user **dev**, that is responsible for running everything, that is project related. actually it's also a sudoer. 
when drone tries to execute commands on an image, it gets problems with permissions.
here is an outcoming log, from drone build: https://gist.github.com/zavalit/941ca433b836fddfe883

**Comment by bradrydzewski** [comment]
see https://github.com/drone/drone/pull/900#issuecomment-151236913
