### ISSUE TITLE
Drone CI web terminal incorrectly interpret tput output to *(B characters 

### ISSUE THREAD

**Issue by fracting** [drone/drone#1491]
Hi folks,

I have installed tput in my Drone CI build image, with configure like:

https://github.com/Alexpux/MSYS2-pacman/blob/master/scripts/libmakepkg/util/message.sh#L28
```
colorize() {
	# prefer terminal safe colored and bold text when tput is supported
	if tput setaf 0 &>/dev/null; then
		ALL_OFF="$(tput sgr0)"
		BOLD="$(tput bold)"
		BLUE="${BOLD}$(tput setaf 4)"
		GREEN="${BOLD}$(tput setaf 2)"
		RED="${BOLD}$(tput setaf 1)"
		YELLOW="${BOLD}$(tput setaf 3)"
	else
		ALL_OFF="\e[0m"
		BOLD="\e[1m"
		BLUE="${BOLD}\e[34m"
		GREEN="${BOLD}\e[32m"
		RED="${BOLD}\e[31m"
		YELLOW="${BOLD}\e[33m"
	fi
	readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
}
```

Drone CI web UI does not interpret `tput sgr0` correctly, as a result there are some *(B characters in the output.

Note that for some reason I have to use my custom terminal (mintty.exe) and redirect the output to Drone terminal. Mintty does render `tput sgr0` correctly, but Drone CI web UI does not.

Is there any chance to support `tput sgr0` or at least avoid those *(B ?

Thanks!

**Comment by fracting** [comment]
Here is an example output:
http://wine-ci.org/fracting/MSYS2-packages/61

```
\r
==>(B Making package: xz 5.2.1-2 (Tue, Feb 16, 2016  5:24:53 PM)(B\r
==>(B Checking runtime dependencies...(B\r
==>(B Checking buildtime dependencies...(B\r
==>(B Installing missing dependencies...(B\r
```

**Comment by fracting** [comment]
BTW, there is also some unexpected `\r` in the end of lines during building, however, once the build is complete, those `\r` will be disappear. Could that be improved as well? Thanks very much!

**Comment by bradrydzewski** [comment]
drone does not have a fully compliant ansi terminal parser. We have a parent issue for this. If anyone is will to re-write a fast, compliant parser I am very interested in the help

for updates let's use https://github.com/drone/drone/issues/939
