### ISSUE TITLE
Paginate REST query

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#1494]
Currently there's no way to do pagination on the REST API endpoints. Would be great to be able to set the following values.
- size - the number of values to retrieve
- offset - the offset of the list of values

One thing that's an open question would be how do you ensure you don't have duplicates as builds are added. One suggestion might be to have a from date time offset. That way you can ensure a consistent listing.

**Comment by gtaylor** [comment]
The only thing I have to add is that especially if we are eventually thinking about adding DB support for Cassandra or other non-relational or eventually consistent DBs, we probably can't use size/offset.

An alternative is to instead ask for an `after` param instead of `offset`. The value of `after` would be whatever ID the DB is using, which varies wildly. This also has the bonus of making sure that later pages don't shift around when new objects are created (IE: give me page 2, size 20. The last entry shifts off the page as soon as a new one gets "pushed" to the top of page 1).

If there's enough interest, I can scrounge up an example of how pagination works in Cassandra, since HBase, BigTable, and some others will be similar.

**Comment by flyinprogrammer** [comment]
:+1: to both of these comments -- I have a performance issue currently in that we are starting to use Drone against an internal github, and my user has access to hundreds of repos. Viewing the front page takes seconds to load lol. I was planning on seeing if I could hack together the code needed to limit the organizations an instance of Drone would care about. Even with that however, pagination is going to be needed in some cases.

**Comment by bradrydzewski** [comment]
@flyinprogrammer pagination will solve this sort of performance issues. Drone fetches your list of repositories from GitHub which can take 1-2 seconds. It caches this data in memory for 15 minutes to prevent such delays. It is likely we'll increase the cache time to reduce GitHub round trips once we add a "force refresh" button to the UI

**Comment by gtaylor** [comment]
This is probably the subject for another issue, but I'd love to see us not do that fetching unless we're adding repositories (main page only showing the activated repositories). I have access to hundreds myself, so the list is massive and load times long.

**Comment by bradrydzewski** [comment]
@gtaylor we'll always need to fetch the full list from GitHub so that we can get the intersection of repositories that you have access to that are registered in drone. But agreed that from a UX perspective we should only show active repositories on the home page. Also think that a 3 day cache (similar to Travis) with a force-refresh button will improve the above mentioned perf issues.

**Comment by gtaylor** [comment]
Sorry to hijack the issue.

Back on topic: Do we still feel that we need to keep the non-relational DBs in mind going forward? That would be relevant to this and other future discussions.

**Comment by flyinprogrammer** [comment]
@gtaylor absolutely relevant and required for future development if the community is up for the challenge.

**Comment by bradrydzewski** [comment]
@gtaylor I'll provide a detailed answer here :)

I do not believe we need to build for non-relational databases based on some preliminary benchmarks I've performed. See https://github.com/drone/drone/issues/1234#issuecomment-148874156

These simple benchmarks demonstrate a small Postgres database (on a $20 digital ocean server) is capable of handling high query volume for a dataset with 5MM repositories and 60MM builds. I believe a very large drone installation (1000 nodes running at capacity 24/7) could generate around 12MM builds per year, taking 5 years to reach the dataset size in the benchmark. I'm guessing a larger machine would handle even larger datasets, and we could always implement some sort of archiving if necessary (do you really need to see 5 year old builds?).

I'm not convinced (yet) there is a compelling technical reason to support non-relational databases, however, I will say these benchmarks are not comprehensive enough to say so definitively. Perhaps our GKE benchmarks will provide more information to help facilitate a decision.

**Comment by flyinprogrammer** [comment]
@bradrydzewski how many concurrent user fetches were you doing against that db? And I assume because of these in memory caches you're only running 1 'master' drone ?

**Comment by bradrydzewski** [comment]
@flyinprogrammer we executed the most resource intensive query (user feed query) and the database was able to process between 300 and 1000 requests per second depending on how many repositories the user had access to. This test purely isolated the database which is where we'd see the most immediate bottleneck when running a large Drone install.

**Comment by guiguan** [comment]
A pagination support for retrieving list of builds of a repo could be handy

**Comment by ArturGajowy** [comment]
I too can't wait for this feature to be released. Hope the CLI `--limit` will work for limit > 50 then? How about pagination in the GUI?

**Comment by ArturGajowy** [comment]
@bradrydzewski thx! We're using drone 0.8.6 (both the server and my cli), but the following only lists 50 builds:

```
artur@y510p:~$ drone build ls rchain/rchain   --limit 50 | grep 'Build #' | wc
     50     150    1050
```

I've seen the `--limit` option works for limits <50. Is the issue in the CLI then?

**Comment by bradrydzewski** [comment]
The `--limit` is the not the same thing as pagination.  The limit specifies the max number of builds printed to the console. To see older builds the CLI would need to implement pagination using a new `--page=N` argument.

**Comment by ArturGajowy** [comment]
I see, thx.

**Comment by Raffo** [comment]
@bradrydzewski @ArturGajowy I went on and I just did it, it works quite nice on my machine and here are the two required PRs: 

https://github.com/drone/drone-go/pull/39
https://github.com/drone/drone-cli/pull/106

**Comment by bradrydzewski** [comment]
the important endpoints now have pagination (although many endpoints still do not).  I am going to close this issue and recommend creating separate issues for specific endpoints with real-world requirements for pagination.
