### ISSUE TITLE
can't flip the trusted flag

### ISSUE THREAD

**Issue by lvlv** [drone/drone#1500]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [x] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

@tboerger 

I'm using drone:0.4 (f4077f41a0de) on my ubuntu 14.04, I tried to set my repo as trusted through UI but that was not saved to sqlite.
Also the drone log shows that the PATCH was received by drone.

**Comment by tboerger** [comment]
I can confirm that this is the same behavior on beta.drone.io, I tried to mark drone-rubygems as trusted, the UI looks fine until I reload the page

**Comment by bradrydzewski** [comment]
> For security reasons this option is only available to trusted repositories. Trusted repositories are enabled on a per-repository basis by a __Drone administrator__ from your repository settings screen.

this can only be done by a drone administrator for security reasons because trusted build essentially have root access to the host machines. This is not something a non-administrative user can grant for themselves

**Comment by shankiesan** [comment]
I also bumped into this problem and was a bit confused. Of course @bradrydzewski making myself an admin did the trick, but this could do with being more obvious in the UI.

Is this an issue with Drone UI, or does the API simply "fail silently" if the user isn't an admin? If it's the former, I'll do some work on a PR. If it's the latter, I guess some API changes will be needed, which is probably over my head for Go.

**Comment by ylecuyer** [comment]
When trying to flip the trusted flag for a repo the pop 'Failed to update the repository settings' without much details. In the console it says 'Insuficient privileges'.

@bradrydzewski the message shown in the console should be shown in the popup too. Or better, it should say only admin can edit this repo property

**Comment by alexanderadam** [comment]
@bradrydzewski should it be obvious in the meantime that it additional privileges are required or should the active but for most of the users still non-functional toggle still active?

Because I just tested and the UI "bug" is still present. Or any other update on this?
If not, the issue should probably be reopened, right?
