### ISSUE TITLE
Separate GitHub commit statuses for PRs and pushes

### ISSUE THREAD

**Issue by mithrandi** [drone/drone#1502]
Travis-CI has separate `.../pr` and `.../push` commit statuses, whereas Drone does not. There is a reason these should be distinguished: A PR build is run against the result of merging the head of the merge source into the head of the merge base; a branch ("push") build is simply run against the head of the branch.

Thus, in the case of a PR, the PR build actually tests what will land on the merge base, whereas the branch build does not necessarily test this; currently Drone will run both builds, but the results will just overwrite the same commit status, so the status you end up with will randomly depend on which build ran last.

**Comment by mithrandi** [comment]
This issue is alluded to in the comments on #1382, but wasn't explored there.

**Comment by mithrandi** [comment]
#1289 is related, but not the same as what I'm asking for here.

**Comment by bradrydzewski** [comment]
I'm open to the change. If you are willing to send a PR we can get this merged right away

**Comment by bradrydzewski** [comment]
proposed one line change:

```
github.String("continuous-integration/drone/"+b.Event)
```

note 1 minor modification would be to convert `pull_request` to `pr` when generating the status, since that seems to be the common convention others are using.

**Comment by bradrydzewski** [comment]
fixed by #1502 and will be included in 0.5 release
