### ISSUE TITLE
Multiple remote drivers

### ISSUE THREAD

**Issue by Dids** [drone/drone#1503]
I'm moving from a self-hosted Drone installation to a containerized Docker installation, but I use both GitHub and BitBucket for the projects that I use with Drone.

I noticed that the Docker-specific instructions only allow me to specify one remote driver using an environment variable. Ideally I'd want to specify one for both GitHub and BitBucket, but I couldn't find any information on this anywhere.

Is it not possible to use multiple remote drivers anymore (I know it was before)?

**Comment by tboerger** [comment]
Please see https://github.com/drone/drone/issues/1336#issuecomment-158459430 which describes why multiple remotes were removed in 0.4, and the suggested workaround. There are no plans to re-add multiple remotes in a future release.

**Comment by Dids** [comment]
Figured I'd have to run multiple containers, just sad to see that feature go. Thanks though!

**Comment by tboerger** [comment]
Drone got such a small footprint that it really doesn't hurt to run an instance per remote. You don't need a totally different environment for those instances, they can share the same docker worker nodes.

**Comment by cyberplant** [comment]
In our case, we have hundreds of repos in bitbucket and github and it's an inconvenience having two separate drone instances.

Is there a way to have all driver-related paths grouped, so we can setup a reverse proxy that makes multiple drone instances transparent to our users? we can share a same DB between instances, so generic settings will be available from both instances.

Right now, there are a couple of places (for example the repository dashboard) that doesn't contain the driver in the URL, but the ones related to repos are fine.

**Comment by bradrydzewski** [comment]
It is possible we'd eventually create a pluggable remote implementation that sends all remote logic to an external service (ie micro-service). This could allow someone to create their own remote implementation, which could include mashing up two GitHub and Bitbucket, for example.

I envision it would be configured something like this:

```
DRONE_CUSTOM_REMOTE=true
DRONE_CUSTOM_REMOTE_URL=http://...
```

In order to make this happen we would need to define an API protocol (likely using [rpc](https://golang.org/pkg/net/rpc/)) to communicate with the service in a standard way.

If this is something you are interested in contributing I would certainly accept a pull request.

**Comment by cyberplant** [comment]
Hey! I'm revisiting this issue cause I need to move forward. 

I was thinking in another option. What do you think about having a setting for a hardcoded user for github + bitbucket?

In our case, we use drone for company stuff, and we have a user in both services for accessing the repositories.

As it is now, people with access to drone has access to the private repositories of everybody that has connected to drone, and it can be good to avoid that.

If you think that this can be a good idea, then we can move forward and make a PR.

**Comment by donny-dont** [comment]
No. As mentioned a PR that would be accepted would have an API protocol that Drone could hit which would do whatever it is you want.

If that is something you're interested in I've kicked around the idea of busting out the remote into its own library which could then be run as its own endpoint. At this point you could make your own implementation of it that did what you want and then make that as your own container. If you want to do some implementation on something like that just contact me on gitter. Its been low on my priority list but maybe we can get somewhere with some additional hands.

**Comment by cyberplant** [comment]
I will.. we need to upgrade drone to a newer version and this is one of the things that is getting in the way.

Thanks for your response.

**Comment by bradrydzewski** [comment]
just to echo what @donny-dont  said ...

my recommendation would be to add a remote implementation that allows drone to hit an external set of endpoints for custom, pluggable remotes. One could then create their own custom remote implementing the exact logic necessary.

note that pluggable remotes would not be something the drone team creates or maintains. The plugins themselves are outside the scope of the project. Drone would simply provide the capability to delegate to a 3rd party set of endpoints, but nothing more. You would then be able to create a simple remote that combines github and bitbucket, for example.

**Comment by cyberplant** [comment]
Yes, I understood that part, and sounds good to me. I like the idea of being able to handle this by myself outside of drone. We're python programmers, so we will probably do it in python.

On my last comment I thought a 'simplification' that was allowing hardcoded users for github/bitbucket. But, I can do that by myself as a "remote auth endpoint".

Thanks for your responses, guys! You always reply very fast, it's a pleasure!
