### ISSUE TITLE
Drone Build container + Custom Networks

### ISSUE THREAD

**Issue by sylus** [drone/drone#1508]
This might be related to: https://github.com/drone/drone/issues/1492 but am not sure.

I recently updated my docker-compose to the v2 syntax and put both my drone + gitlab containers in a network called ci. 

Everything works and drone correctly sees when I perform a push to gitlab and attempts to start the build. The problem is the build execution container environment can’t see gitlab from the ci network so times out when I start to do a git fetch.

I thought making the repo trusted and setting net: ci would be enough but seems I am missing something? I confirmed that when drone launches the build execution environment it is only in the docker bridge network while all of my other containers (drone, gitlab, postgres, etc) are on my ci network.

- [X] I have searched for existing issues
- [X] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [X] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
drone does not use docker compose v2 syntax for composed containers and does not yet support custom networks. Subscribe to https://github.com/drone/drone/issues/1268 for updates

**Comment by sylus** [comment]
Thanks for the heads up! :)
