### ISSUE TITLE
Multiple GitHub checks

### ISSUE THREAD

**Issue by gabro** [drone/drone#1509]
Hi, I'm currently evaluating drone for my team and I'm facing this problem: I'd like to have multiple checks on GitHub (i.e. multiple status scopes per commit) linked to different steps of the build.

For instance, we currently have two checks on javascript projects: one for the tests and one for the linter.
Here's an example:

<img width="716" alt="screen shot 2016-03-02 at 2 50 01 pm" src="https://cloud.githubusercontent.com/assets/691940/13462160/32f912be-e086-11e5-8216-cd5254d522d0.png">

We'd like to keep the two separated.

Is it possible to achieve this result using drone?

I thought about writing a plugin that runs the linter and adds a status check using the GitHub API, but I'm not sure where it would fit. None of the plugin types (clone, publish, deploy, notify) seems to be a good fit, so I'm wondering where there's a more natural way of doing this.

Thanks for the great job on drone, it's been a great experience so far and I'd love to switch over to it.

**Comment by bradrydzewski** [comment]
@gabro drone does not have the ability to send per-stage statuses to GitHub. Without getting into the full technical details, I can tell you that it would take very major architectural changes to Drone to make something like this possible which makes it unlikely at this time. For this reason it probably needs to be delegated to plugins or custom scripts.

Since the build environment is a shell, for example, you could wrap your lint commands in a shell script that traps the exit code and sends the status to GitHub:

```sh
#!/bin/sh

npm run lint
EXIT_CODE=$?

if [[ $EXIT_CODE == 0 ]]
then
  export STATUS="success"
else
  export STATUS="failure"
fi

GITHUB_TOKEN=<your api token>

curl "https://api.github.com/repos/$CI_REPO/statuses/$CI_COMMIT?access_token=$GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"state\": \"$STATUS\", \"description\": \"eslint\", \"target_url\": \"$CI_BUILD_URL\"}"

exit $EXIT_CODE
```

**Comment by gabro** [comment]
Thank you for the thorough answer @bradrydzewski! I'll try the script approach, although I would've preferred to keep this as a plugin so that the implementation doesn't have to live on the repo.

A would probably do the job, but I still have a concern towards the "type" of it.

**Comment by gabro** [comment]
Thanks. I managed to have this working. For future reference here's the exact config I put together:

### `.drone.yml`

```yaml
build:
  web-lint:
    image: quay.io/buildo/node-0.12.7-npm-3
    commands:
      - ./web/drone-eslint.sh $$GITHUB_ACCESS_TOKEN
    when:
      branch:
        - web-*
        - master
```

### `web/drone-eslint.sh`

```sh
#! /bin/bash

GITHUB_TOKEN=$1
GITHUB_API=https://api.github.com
GITHUB_STATUS_ENDPOINT=$GITHUB_API/repos/$REPO/statuses/$SHA
CI_CONTEXT="stylechecker/eslint"

# Notify GitHub stylechecking has started
echo 'Starting ESLint...'
curl "$GITHUB_API/repos/$CI_REPO/statuses/$CI_COMMIT?access_token=$GITHUB_TOKEN" \
  -s \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"state\": \"pending\", \"description\": \"The ESLint style checking is in progress\", \"target_url\": \"$CI_BUILD_URL\", \"context\": \"$CI_CONTEXT\"}" \
  > /dev/null

# Run ESLint
cd `dirname $0`
npm run lint
EXIT_CODE=$?

# Notify GitHub according to ESLint exit code
if [[ $EXIT_CODE == 0 ]]
then
  export STATUS="success"
  export DESCRIPTION="No style issues"
  echo $DESCRIPTION
else
  export STATUS="failure"
  export DESCRIPTION="ESLint found style issues"
  echo $DESCRIPTION
fi

curl "$GITHUB_API/repos/$CI_REPO/statuses/$CI_COMMIT?access_token=$GITHUB_TOKEN" \
  -s \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"state\": \"$STATUS\", \"description\": \"$DESCRIPTION\", \"target_url\": \"$CI_BUILD_URL\", \"context\": \"$CI_CONTEXT\"}" \
  > /dev/null

exit 0 # don't make the build fail, just notify GitHub
```

**Comment by SGTGunner** [comment]
@gabro Do you mind sharing what your docker image file looks like? I am trying to do this and keep getting an error. The error is that it cannot find the shell file in the image.
@bradrydzewski I have trying to use the http://docs.drone.io/creating-custom-plugins-bash/ as a reference and it cannot seem to find or execute the shell file.

**Comment by tboerger** [comment]
Look at the plugin index, there should be already some github build status plugin.

**Comment by makslevental** [comment]
@tboerger i can't find such a plugin. can you point me to one?

**Comment by tboerger** [comment]
> @tboerger i can't find such a plugin. can you point me to one?

https://github.com/drone/drone-plugin-index/pull/125, be aware that the example format is the 0.8 format.
