### ISSUE TITLE
[Feature Request] Better "not authenticated" indications when not logged-in

### ISSUE THREAD

**Issue by bobbo** [drone/drone#1519]
Currently there is no obvious indication that a user is not logged in when they are on a repo page. The header displays the user avatar when logged in, but this area is blank when not authenticated. This can cause confusion when following a link directly to a repository. 

When a user is not logged in, the area used for authenticated users' avatars should contain a link to the Login page; perhaps with some extra messaging to indicate that the user is not logged in. It could also be helpful to add a link to the login page in the 403 error message page.

**Comment by bradrydzewski** [comment]
tracking as #1266
