### ISSUE TITLE
No logging output when using default journald logging driver

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1523]
For obvious reasons Drone fails to log output when using the journald driver in docker by default. However, it is possible in docker to specify logging driver per-container - so if this mode of operation is not supported, sensible default behavior for drone would be to force all containers to start with `log-driver=json`.

**Comment by OndrejIT** [comment]
Same problem...
![image](https://cloud.githubusercontent.com/assets/11267809/25101037/fb911c06-23b2-11e7-9fd4-aad8ec7d05b1.png)

**Comment by bradrydzewski** [comment]
happy to accept a PR to specify the log driver. Labeling as help wanted.

**Comment by OndrejIT** [comment]
--log-driver=gelf

**Comment by andreaso** [comment]
Why is it obvious that Drone would fail to display log output when using the journald driver?

One of the best things about upgrading our Drone server from Ubuntu 14.04 to Ubuntu 16.04 was that I could use the journald log driver, not having to choose between system logs (syslog) and docker logs (json).  Up until Drone 0.7.1 using the journald driver worked great for me, displaying the Drone build logs in the Drone web ui while at the same time also allowing me to view/search them using journalctl.

That broke for me with Drone 0.7.2, which appear to force the json driver? Now I only get the build logs in the web ui.
