### ISSUE TITLE
Namespacing .drone.yml

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1526]
Due to its easy deployability you can end up with several drone instances which you might potentially want to build against which present slightly different environments in order to build (or in our case, drastically different).

My sort of proposed solution to this is to allow a drone instance to configured with a `NAMESPACE` environment variable, which would specify a preferred prefix to `.drone.yml` and `.drone.sec`.

i.e.
`NAMESPACE=internal` would cause drone to preferably try and download `.internal.drone.yml` and `.internal.drone.sec` when starting a build, and then revert to using `.drone.yml` and `.drone.sec`.

Possibly a secondary parameter would be `NAMESPACE_ONLY` to enforce only building if the .<namespace>.drone.yml is found.

**Comment by fracting** [comment]
This is also a feature I was waiting for a long time, thanks @wrouesnel for the feature request!

**Comment by bradrydzewski** [comment]
We recently merged a pull request to enable this behavior https://github.com/drone/drone/pull/1532

You can use the `BUILD_CONFIG_FILE` environment variable to alter the name of the yaml file. The sec file will automatically adopt the same naming configuration. If you wanted `.internal.drone.yml` you could include the following in your drone configuration:

```
BUILD_CONFIG_FILE=.internal.drone.yml
```

You could then have a second drone instance that is configured with the following:

```
BUILD_CONFIG_FILE=.external.drone.yml
```
