### ISSUE TITLE
Make default registry configurable

### ISSUE THREAD

**Issue by jeffastorey** [drone/drone#1527]
Drone depends on images from the docker public reigstry for its core functionality - drone-exec, drone-git, etc. For those of us running behind corporate networks that do not have access to the public docker registry, we cannot pull these images. Having the default registry be configurable would be very helpful.

I opened this issue after discussing with @bradrydzewski on gitter.

**Comment by cmingxu** [comment]
+1


this would be super useful for me as for sometime I experience super slow network connection.

**Comment by bradrydzewski** [comment]
this is exposed in the upcoming 0.5 release:

```

		cli.StringFlag{
			EnvVar: "DRONE_PLUGIN_NAMESPACE",
			Name:   "namespace",
			Value:  "plugins",
			Usage:  "default plugin image namespace",
		},
```

this allows you to set something like this:

```
DRONE_PLUGIN_NAMESPACE=index.mycompany.com/plugins
```
