### ISSUE TITLE
repository name component must match

### ISSUE THREAD

**Issue by TrollWarlord** [drone/drone#1529]
The plugin system doesn't account for images with capital characters. 
```[error] Error pulling TrollWarlord/drone-elastic-beanstalk:latest. repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"```

```"[a-zA-Z0-9]+(?:[._-][a-zA-Z0-9]+)*"````

**Comment by bradrydzewski** [comment]
this error message comes from Docker, not from Drone https://github.com/docker/docker/issues/17836
