### ISSUE TITLE
View for only activated repos

### ISSUE THREAD

**Issue by jeffastorey** [drone/drone#1533]
The list of repos in the main view of drone can get very long, and it's difficult to tell which are actually active. This is a suggestion to split the repo screen into 2 - one that shows only activated projects and one that shows you all where you can choose to activate any of them.

**Comment by tgsoverly** [comment]
+1

**Comment by gtaylor** [comment]
Please don't add +1 comments. Either hit Subscribe or use the thumbsup response on the issue being submitted.

**Comment by ericanderson** [comment]
I don't know Tim's situation but from iPhones you don't get to do thumbs up it seems
