### ISSUE TITLE
Show build times on the build page

### ISSUE THREAD

**Issue by bitemyapp** [drone/drone#1534]
Given that I'm pretty sure y'all have the information recorded, it would be nice if we could see how long each build took. From drone:

![screenshot from 2016-03-23 10-29-00](https://cloud.githubusercontent.com/assets/320177/13990375/1121ee60-f0e2-11e5-80aa-6a6c278ca6f6.png)

Whereas in CircleCI:

![screenshot from 2016-03-22 22-34-57](https://cloud.githubusercontent.com/assets/320177/13990388/18d5a2dc-f0e2-11e5-9688-f503d10ac208.png)

Any reason this couldn't or shouldn't be done? We're actually quite happy with the build times we're getting with Drone (much better than CircleCI) but we'd still like to see if anything we do is making the build times climb.

**Comment by bradrydzewski** [comment]
merging with #1534

**Comment by bitemyapp** [comment]
@bradrydzewski you merged the ticket with itself as justification to close the ticket?

**Comment by bradrydzewski** [comment]
edit: merging with #1298
