### ISSUE TITLE
Badges don't update without a page refresh

### ISSUE THREAD

**Issue by jeffastorey** [drone/drone#1535]
When on a project page or a specific build page and the status of a build is Running, it will continue to show as running even after the build finishes. It only updates when the page is refreshed. Because the badge bounces back and forth, it indicates to me that I would expect it to update when done, but that does't seem to be the case.

Also on the main build page, the page doesn't show new builds without a refresh either.

**Comment by bradrydzewski** [comment]
closing because the issue wasn't discussed in Gitter per the issue template checklist. We can re-open once we've discussed and verify

> I have discussed the issue with the community at https://gitter.im/drone/drone
