### ISSUE TITLE
Bitbucket PR Webhook Events Not Automatically Enabled 

### ISSUE THREAD

**Issue by jsonfry** [drone/drone#1549]
Using the `0.4` tag of drone from https://hub.docker.com/r/drone/drone/ (Last built about 5 hours ago, so assuming this commit from 5 hours ago https://github.com/drone/drone/commit/8a6857a74b6c7acb307635a32db0d5ac5f65c2f3)

I have drone configured and working with Bitbucket as the remote driver as per this page http://readme.drone.io/setup/remotes/bitbucket/

When having this:
```
when:
      branch: master
      event: pull_request
```
or 
```
when:
      event: pull_request
```

in a build step of my `.drone.yml` file, that step is not triggered when a pull request is created or updated.

I looked at the webhook that was setup in Bitbucket by Drone, and it only has the `repo:push` event enabled, not the `pullrequest:created` or `pullrequest:updated` events (even though the option for this is enabled in Drone).

I checked the Bitbucket Drone code and found this line https://github.com/drone/drone/blob/master/remote/bitbucket/bitbucket.go#L383 where the `pullrequest:created` and `pullrequest:updated` events seem to be handled so I think this is a bug. Drone does seem to trigger on pull requests once I tick those webhook options on the Bitbucket webhook. 

Although I did find this issue #597 which is still open but after reading the linked issue #1066 I think this refers to building what the result of the pull request merge would be.

**Comment by bradrydzewski** [comment]
Bitbucket pull requests are not yet supported due to lack of Bitbucket support for merge refs. Even if we enabled the hooks mentioned above we would be unable to clone. So although we have most of the code in place we lack the necessary features from Bitbucket.

Lets continue tracking progress in https://github.com/drone/drone/issues/597
