### ISSUE TITLE
Proper handling of carriage returns

### ISSUE THREAD

**Issue by renatosilva** [drone/drone#1558]
Build output currently does not handle carriage returns properly. They are used in terminals for rewriting the current line but the web terminal is just printing everything. In the following bash test case, *doing* is supposed to only appear in the ongoing build but not after build has finished:

```bash
printf 'doing'
printf '\r%5s\r'
printf 'done\n'
```

It seems [these lines](https://github.com/drone/drone/blob/dfea14c/static/scripts/term_buf.js#L31-L33) can be improved to move the cursor to the beginning or maybe delete the current line. Note that this is not related to #939 since the current line has already been converted by whatever ANSI-to-HTML library you decided to use.

**Comment by bradrydzewski** [comment]
I've renamed #939 to be more inclusive of any terminal output issues. The display is fully handled by a 3rd party library, so we need to either improve or replace this library. I would prefer to track this under #939 instead of having multiple issues to track problems with the 3rd party library.
