### ISSUE TITLE
Testing Github Pull Requests

### ISSUE THREAD

**Issue by skorfmann** [drone/drone#156]
I was wondering why drone is checking out the unmerged version of the pull request. That's the code I've found here (https://github.com/drone/drone/blob/master/pkg/build/repo/repo.go#L109-L112):

``` go
cmds = append(cmds, fmt.Sprintf("git fetch origin +refs/pull/%s/head:refs/remotes/origin/pr/%s", r.PR, r.PR))
cmds = append(cmds, fmt.Sprintf("git checkout -qf pr/%s", r.PR))
//cmds = append(cmds, fmt.Sprintf("git fetch origin +refs/pull/%s/merge:", r.PR))
//cmds = append(cmds, fmt.Sprintf("git checkout -qf %s", "FETCH_HEAD"))
```
Other than that, it would be good to test a pull request again as soon as the base branch has new commits.

**Comment by bradrydzewski** [comment]
the latest release is building using the merge ref `refs/pull/1/merge` instead of the head ref ``refs/pull/1/head`. I believe that was the original ask, so closing this issue now.
