### ISSUE TITLE
Truncate large build logs to include the tail instead of the head

### ISSUE THREAD

**Issue by goober** [drone/drone#1563]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

The last part of the build output is mostly more interesting for a user than the beginning. e.g. the final build status and build errors are usually printed at the end. When the build output is larger than the 2mb limit it will truncate the output and only include the first 2mb from the logs. I suggest that the truncation is done so the end of the output is included instead.

**Comment by bradrydzewski** [comment]
Let's track #733 which is all about enabling / improving large build logs
