### ISSUE TITLE
CLI Tool: trailing slashes in DRONE_SERVER URL cause a 404

### ISSUE THREAD

**Issue by DCRichards** [drone/drone#1564]
When using the CLI tool, specifying the env variable `DRONE_SERVER` or using the `-s` option of the tool, leaving a trailing slash on the URL will result in a 404 error with no explanation.

Eg running:

```bash
export DRONE_TOKEN=<token>
export DRONE_SERVER=http://myserver.com/
drone user self
````

Will result in:

`404 page not found`

This has been noted in [this discussion](https://discuss.drone.io/t/attempting-to-secure-data-results-in-404/138).

**Comment by tboerger** [comment]
Will be solved with https://github.com/drone/drone-cli/pull/33

**Comment by bradrydzewski** [comment]
@tboerger thanks for the fix, just merged
