### ISSUE TITLE
Support `environment_url` when it becomes available

### ISSUE THREAD

**Issue by khirakawa** [drone/drone#1566]
This is a feature request to support the `environment_url` for deployment statuses when it is ready for use. See https://developer.github.com/changes/2016-04-06-deployment-and-deployment-status-enhancements/ for more details.
- [X] I have searched for existing issues
  The ability to send deployment statuses was merged [here](https://github.com/drone/drone/pull/1551), but hardcodes the `targetUrl`
- [X] I have discussed the issue with the community at https://gitter.im/drone/drone
  Please see https://gitter.im/drone/drone?at=57070ce774d45a71586e6bbf
- [X] I am not using the issue tracker to ask why my build failed

**Comment by helaili** [comment]
+1 for this request. The `environment_url` parameter is available provided [a header is set](https://developer.github.com/v3/repos/deployments/#create-a-deployment-status). Currently, here's what we got: 

![image](https://user-images.githubusercontent.com/2787414/44948947-ca8d1000-ae27-11e8-98f9-0f89dff9b053.png)

Below is an example where this parameter is set. Developers don't need to figure out the URL of their deployed application which is quite convenient for review apps on transient environments.  

![image](https://user-images.githubusercontent.com/2787414/44949036-9581bd00-ae29-11e8-84b2-355be451c666.png)

It would require that the deployment plugin (I'm using [the now plugin](http://plugins.drone.io/lucaperret/drone-now/) for instance) retrieve and return to Drone the environment URL. Is this currently possible for a plugin to communicate back data?

**Comment by bradrydzewski** [comment]
Let me dig a bit deeper this week. I am working on the 0.9-beta.1 release and I need to revisit some implementation details of the deployment API, so this will be a good chance for me to address this while I'm in the code. I will post back in a few days.

In terms of the now plugin, you could temporarily fork the plugin and make an API request to get the environment_url from GitHub API. This would be a temporary workaround until we have an 0.9-beta.1 available.

**Comment by bradrydzewski** [comment]
ahh, I think I understand. The now plugin is creating a per-deployment URL which you would like to include in the GitHub deployment status? Is that correct?

**Comment by helaili** [comment]
👍

**Comment by bradrydzewski** [comment]
Because of the way Drone is architected, the only runtime data that is passed from a pipeline step back to Drone is the exit code and stdout / stderr. This means it would not be possible for the now plugin to pass the environment_url back to Drone.

The challenge is that Drone does not have guaranteed access to the filesystem where the build is running. Drone is controlling the build via the Docker remote API (or Kubernetes API) and the build may be running on a completely different machine.

One option could be to disable deployment status updates, so that you could control the status updates in the pipeline. For example you could do something like this:

```diff
+deploy_status:
+  disabled: true

pipeline:
  build:
    image: node
    commands:
    - npm install
    - npm test
  now:
    image: lucap/drone-now
    deploy_name: foo
+ status:
+   image: plugins/gh-deploy-status
```

I need to think through this a bit more ...

**Comment by bradrydzewski** [comment]
Drone does have a deployment API inspired by GitHub :)
http://docs.drone.io/cli-deploy/

You can use the `drone deploy` command and you can pass custom parameters that will be passed to your pipeline containers as environment variables. You might be able to trigger a drone deploy at the end of your pipeline using a plugin, probably something similar to http://plugins.drone.io/drone-plugins/drone-downstream/ ...

---

I also have an idea for how to handle this going forward, but it is still a bit conceptual, so my apologies if I do a poor job of explaining ...

The next Drone release will support multi-document yaml files. The syntax is inspired by kubernetes, and allows you to specify a kind and type for each resource:

```
kind: pipeline
name: backend

steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test

---
kind: secret
type: encrypted

data:
  username: 3843714a63ed2ad524854f57ccc480ce=
```

I could imagine defining a zeit resource that creates your environment on-the-fly and then passes this information to your pipeline, and back to drone as structured data:

```
---
kind: provisioner
type: zeit
name: zeit

parameters:
  site_id: xxx-yyy-zzzz

---
kind: pipeline
name: backend

steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test

depends_on:
- zeit
```

I am not yet sure how we would define custom resources (like zeit) but I imagine these running as REST microservices, perhaps similar to probot, accepting webhooks from Drone and returning back structured data.

I am still trying to work this all out in my head, though ....

**Comment by bradrydzewski** [comment]
sorry I am a little slow on this one, but we added `environment_url` [1] to our source control management library which means we can include the url in our next release candidate.

[1] https://github.com/drone/go-scm/commit/f5fde5b45c41e81fec043dddcb167d1d3083c2c4

**Comment by bradrydzewski** [comment]
closing this as resolved :)
