### ISSUE TITLE
Offline / Private Environment

### ISSUE THREAD

**Issue by steve-gray** [drone/drone#1572]
Hello,

Is it possible to add a prefix variable that can be appended to all container names, allowing us to run a fully offline copy of drone using a mirrored set of containers.

Essentially we're using Artifactory, and we want to have a non-internet connected test environment - and plugins for the various elements would be mirrored to artifactory - requiring a prefix to be specified for the FQDN on the container pulls.

Right now, no internet - no love - unless I've missed something dramatic here.

-steve

**Comment by bradrydzewski** [comment]
drone will always fall back to the local Docker cache (on the host machine) and will happily execute if the required images are in the local cache. If you want to change to use an internal registry you will need to publish images or plugins to your registry and then reference them in the yaml using the full name:

```
build:
  image: foo.com/golang

deploy:
  slack:
    image: foo.com/slack
```

Then you will need to include your plugins in the white list. You can do so by adding the following configuration to your drone server:

```
PLUGIN_FILTER=plugins/* foo.com/*
```

For all future questions, please use our [gitter room](https://gitter.im/drone/drone) to reserve the issue tracker for bug reports. Thanks!

**Comment by steve-gray** [comment]
Does this apply for the Git plugin too?
