### ISSUE TITLE
CoreOS fleet based deploy plugin available

### ISSUE THREAD

**Issue by crisidev** [drone/drone#1575]
Hello,
I have written a plugin for Drone to deploy on CoreOS clusters using Fleet. 
The plugin is available at https://github.com/crisidev/drone-fleet

I would like to publish the plugin in your addons store, to allow others to simply use that?
Is there a procedure I should follow?

Thanks

**Comment by tboerger** [comment]
Thank you for the afford but please post things like that on discuss.drone.io or tell it to us on the Gitter chat. As the issue template says the issue tracker should be used only for issues.

@bradrydzewski should create the required repository within the drone-plugins organization, than you are able to create a pull request to make this an official plugin.

**Comment by bradrydzewski** [comment]
plugins compatible with drone 0.5 or higher can be registered following this guide http://readme.drone.io/tutorials/how-to-register-a-plugin/
