### ISSUE TITLE
Drone can't found git

### ISSUE THREAD

**Issue by luizkowalski** [drone/drone#1579]
I just started using drone with DigitalOcean, when I try to run a job, I see this

`/usr/local/bin/drone: line 75: git: command not found`

here is my drone.yml file
```
image: williamyeh/java8
commands:
  - mvn install
  - mvn test
```

am I missing something?

**Comment by bradrydzewski** [comment]
The digital ocean one-click install is an old version unfortunately and not compatible with the current version or docs. Let's move this discussion to the gitter channel, per the issue template gitter.im/drone/drone
