### ISSUE TITLE
Global Secrets - not accessible during build

### ISSUE THREAD

**Issue by microadam** [drone/drone#1596]
Hello,

I would like to be able to use global secrets (those specified in `PLUGIN_PARAMS`) during the build and image pull phase (specifically, so I can use them in the `auth_config` and not have to store the same GCR token in the `drone.sec` file on all my projects). Currently these are only accessible at the plugins phase (works well for the slack webhook URL for example).

Is this something that might be possible in the future? The name `PLUGIN_PARAMS` suggests they are specifically for plugins, so it does kind of make sense, but it would be great to be able to specify global secrets that can be used in all phases and not just plugins.

Thanks a lot

**Comment by bradrydzewski** [comment]
> Currently these are only accessible at the plugins phase 

This is partially true. Global secrets are available to all sections of the yaml for private repositories, but only available to plugins for public repositories. This is for security reasons to prevent a malicious pull request from exposing your secrets.

Either way this is covered by https://github.com/drone/drone/issues/1538#issuecomment-201403419 which gives you direct control over when secrets are injected. Let's merge with and track #1538 going forward

**Comment by microadam** [comment]
@bradrydzewski That makes a lot of sense! Thanks! Should I expect it to work on Pull Requests on private repos?
