### ISSUE TITLE
Gogs delete hooks

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1603]
Gogs does not currently expose an API to remove hooks. This means when you de-activate a Gogs repository in Drone the previously created post-commit hooks are not removed. If you re-add the repository you will receive duplicate hooks and launch multiple builds.

We should explore adding the appropriate endpoints to the Gogs API client.

**Comment by Unknwon** [comment]
Method added: https://github.com/gogits/go-gogs-client/blob/master/repo_hook.go#L67

**Comment by bradrydzewski** [comment]
@Unknwon awesome, thanks for the heads up!

**Comment by tboerger** [comment]
Solved via #1752
