### ISSUE TITLE
Gogs pull request support

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1605]
The Gogs remote implementation does not currently process pull request hooks. I'm not sure what it would take to integrate full pull request support, but this would definitely be a nice addition to our current Gogs functionality.

**Comment by hhenkel** [comment]
[Webhook support](https://github.com/gogits/gogs/commit/3f7f4852efaaa56a0dada832dc652a1fc8869ae7) has been added to develop branch of gogs today.
