### ISSUE TITLE
support build the drone executable in docker

### ISSUE THREAD

**Issue by gaocegege** [drone/drone#1613]
I found that when the programmer needs to build drone from the source code, he or she has to install the sassc, and some golang packages. If the drone allows the programmer to build the drone binary in a docker container, that's really cool.

FYI, [dapper](https://github.com/rancher/dapper) is an awesome tool to do this. Or we could write a extra Dockerfile and some bash codes, it also works well.

**Comment by bradrydzewski** [comment]
you can build drone with drone, using `drone exec .`
