### ISSUE TITLE
Pass build environment via the webhook

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1614]
When integrating drone with other services where you might want to webhook a build from an external source, it would be _extremely_ useful to be able to add additional JSON objects to the webhook which could be used by the `.drone.yml` file to configure aspects of the build or to pass configuration to custom plugins.

**Comment by bradrydzewski** [comment]
Can you provide example use cases for such functionality? I'm not sure I completely understand the issue or problem we are trying to solve. Instead of defining a solution it would be ideal to define the problem first, so we can brainstorm possible solutions or see if existing functionality can solve the problem as well.

**Comment by wrouesnel** [comment]
The specific problem we've been trying to solve is version propagation amongst dependent repositories, without needing to explicitly notify downstream ones.

So the perfect solution looks something like: PR against parent repo, drone builds and checks. Then our dependency discoverer looks at the produced artifacts, and notifies drone via webhook to rebuild all the repositories that use that artifact. 

It's at this step you'd want to modify the build from the webhook, since whatever updates the dependencies after source code checkout needs to know what it's updating too.

The perfect part comes then from making that discoverer use this intelligently: keep propagating that PRs artifacts until you run out of downstreams, and then do something like comment on the upstream PR what breaks, or notify downstream owners when a breaking PR is merged.

The whole concept needs some generic features from drone plugin wise to work, of which near as I can tell the ability to configure build parameters from the triggering webhook is one of them (the other is editing the source dir pre-script post-checkout but we could also  fake it via custom checkout plugins).

**Comment by vaijab** [comment]
@wrouesnel you can achieve that with recently added custom build parameters. I wrote a tool (could be used as a plugin) to trigger downstream builds and add custom params.

drone-trigger: https://github.com/UKHomeOffice/drone-trigger

**Comment by bradrydzewski** [comment]
closing since this can be used via @vaijab plugin, noted above
