### ISSUE TITLE
RFC: modify cache plugin behavior

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1617]
I would like to propose modifications to the caching plugin.

The cache plugin is currently unique compared to all other plugins. Here are some properties unique only to the cache plugin:

1. the cache plugin is defined once but executed twice, once to restore the cache, and again at the end of the build to re-build the cache
2. the cache plugin maintains state on the host machine
3. the cache plugin receives special permission to mount a host machine volume

The cache plugin also has some deficiencies:

1. the cache is stored on the host machine and not shared across machines
2. the cache plugin can fill up the host machine's disk storage
3. the cache plugin cannot update the cache at the end of a pull request
4. the cache plugin is executed at fixed points in the build process and ordering cannot be customized

__I very much dislike__ having this concept of a special plugin that is treated differently from all plugins. It complicates the code, and this complexity is not without its drawbacks as we see above.

I propose we start treating caching plugins just like any other plugin. These changes would result in a somewhat more complex, but flexible yaml file:

```yaml
pipeline:
  cache:
    driver: rsync
    action: restore
    mount:
      - node_modules
    when:
      event: [ pull_request, push ]

  build:
    image: node
    commands:
      - npm install
      - npm test

  cache:
    driver: rsync
    action: rebuild
    mount:
      - node_modules
    when:
      event: [ push ]
```

There are a few important properties here:

1. the cache plugin is defined twice. Once to restore and once to rebuild
2. the cache plugin has an action field which defines restoring vs rebuilding
3. the cache plugin can be restricted by event type, or not restricted at all
4. the cache plugin uses a remote system (in the above example, rsync) to push the cache to a central server, allowing the cache to be shared across builds servers

There are some drawbacks that I should mention:

1. the yaml sacrifices verbosity for flexibility
2. the cache will require a central server to push cached files
  1. this means someone needs to setup a central server (s3, google storage, ssh server, etc)
  2. this means using the cache plugin will require secrets
  3. this means caching won't "just work" out of the box like it does today

I would envision having either a single cache plugin with multiple drivers, or more likely, multiple cache plugins that can post files to different storage mediums. This would include:

1. s3
2. google cloud storage
3. open stack cloud files (or whatever it is called)
4. open source minio.io
5. any old server using rsync or scp

There are some design challenges that I have not solved yet with this approach:

1. what if we want to cache `.git`? If the cache is arbitrarily defined as a regular step in the pipeline how can we execute before the git clone step?

Overall I think the pros outweigh the cons here but wanted to gather community feedback before we make any final decisions.

**Comment by nodesocket** [comment]
So the downfall of using a centralized store is obviously latency reading/writing to S3 or GCS and complexity of adding api keys.

Basically how it works now is fine except for two things:

- PRs don't update the cache

From: http://readme.drone.io/usage/caching/
> Pull requests have read-only access to the cache. This means pull requests are not permitted to re-build the cache. This is done for security and stability purposes, to prevent a pull request from corrupting your cache.

- No automatically purging of old cache data.

If those two things are solved, for my use case, I don't need the granular control and centralized storage.

**Comment by firrae** [comment]
I agree with @nodesocket, I think storing my cache in S3 would more than likely slow it down rather than help in any meaningful way. It is potentially problematic considering the deficiencies you list, but maybe there's merit in the change that I can't see currently as it is outside the scope of the things I've come across so far.

In the end, if you go this route I, personally, would appreciate some sort of option to host it locally. For projects like mine it would be greatly inefficient to have to go out over the network and pull info into the office and out, and the cost of storage when storing it locally is cheaper, faster, and more efficient.

**Comment by nodesocket** [comment]
👍  I bet cloud based storage _(S3, GCS)_ would be horrendous in terms of performance and frankly be a headache to manage.

If you do implement shared cache storage, please leave the option to use `local`. Is it possible to allow PRs to update the cache using `local`?

**Comment by tboerger** [comment]
I like this proposal, including the remote storage. The big question is how much different storage types we choose and if we build on plugin for all. I would think about different plugins on short term.

I would like to use Minio (for the others that is a S3 server implementation in go which can run locally and takes ~5mb memory), so a Minio or S3 functionality is important.

For local storage you can also use rsync with the IP or domain of your host, so no requirement to leave some local network...

**Comment by bradrydzewski** [comment]
thanks all for the comments

> If you do implement cloud based cache storage, please leave the option to use local. Is it possible to allow PRs to update the cache using local?

Yes the 0.5 version lifts many restrictions thanks to improvements and changes to how we are handling secrets. As a result you'll have full control over when the cache steps execute  and under which conditions.

> I bet cloud based storage (S3, GCS) for cache would be horrendous in terms of performance and frankly a headache to manage.

still probably faster than an `npm install` from scratch assuming we still tar up the cache directory to prevent individual file transfer :smile: 

> The big question is how much different storage types we choose and if we build on plugin for all. I would think about different plugins on short term.

agreed we should keep them separate

> I, personally, would appreciate some sort of option to host it locally

I would like to experiment with an rsync cache plugin. This plugin would be given a remote address and sync files to that address. This plugin could be configured, however, to use the host machines address. So the plugin would essentially be instructed to ssh into the same server it is running on. This would behave like _like_ local caching, while prevent drone from having to mount a volume (which is what I'm trying to avoid).

Worst case is we can try this, and if it sucks, we can revert back to mounting a volume :smile:

**Comment by nodesocket** [comment]
This might be getting too technical, but would the plugin create a ssh connection when reading the cache, close it... then create a new ssh connection when updating the cache... and close it?

Seems like there might be a decent slow down and overhead due to opening, establishing, authorizing and closing ssh connections? Or am I over thinking it?

**Comment by tboerger** [comment]
Now you really want to complain about two ssh or http or whatever connections?

**Comment by bradrydzewski** [comment]
I'm sure we'll see a performance, but not sure the severity. I would guess adding maybe 10-15 seconds to the cache step, but will need to measure to be sure.

The technical goal (for me) is to find a way to provide caching without having to mount a volume inside the cache container like we do today. This makes my life way easier in terms of managing the code and having all plugins behave the same, without having special logic just for the cache plugin.

Of course the design challenge is coming up with a solution that makes reasonable tradeoffs in performance and overall usability. As much as I dislike mounting the volume, it requires no special configuration and is easy to use .... so this will definitely be a challenge :smile:

**Comment by firrae** [comment]
To be honest local ssh shouldn't be overly burdensome, at least in my experience. Rsync is something I only have moderate experience with, and it's never been a good experience so having a local S3 option would be the solution I would go with.

I do agree with separating the plugins, but would it be possible to run 2 of them at the end to keep a remote copy of the cache and have some sort of fallback system to check a remote cache if the main cache is empty?

**Comment by tboerger** [comment]
That's the nice thing, you can run the same plugin multiple times ;)

**Comment by firrae** [comment]
Well my thought is you don't want the cache downloaded twice, that's why I was wondering about the fallback option when it tries to load. Running it twice at the bottom is cool, but that would be the ultimate seal for me to make me want this 100x over the current solution.

**Comment by brgaulin** [comment]
If I were to use this I would probably opt for some kind of rsync, local network type. Where probably my drone controller(thing with UI) or minio would hold the cache, and the worker nodes would just pull it from there.

As for the syntax, I think getting cache out of drone core is really important, it sounds like it is really mucking things up in there. 

I don't think I would want PRs updating my cache. But that would be configurable so I'm fine with the new syntax =P

As for verbosity, I wonder if we should start supporting multiple files to configure drone? Or like a configuration section where you can configure things like ports, hostnames, usernames, then when plugins run they can just reference those by default, and your pipeline section becomes less verbose

**Comment by bradrydzewski** [comment]
> As for verbosity, I wonder if we should start supporting multiple files to configure drone? Or like a configuration section where you can configure things like ports, hostnames, usernames, then when plugins run they can just reference those by default, and your pipeline section becomes less verbose

The 0.5 release implements a new mechanism for managing and injecting secrets into your build environment or plugins. Secrets are now stored in the database (we still have to sign the yaml) and are now injected as environment variables into specific images (to limit exposure) instead of being injected into the yaml. You can read more here:
https://github.com/drone/drone/issues/1538#issuecomment-204085810

This is an example of an 0.4 yaml

```
publish:
  docker:
    repo: foo/bar
    username: $$USERNAME
    password: $$PASSWORD
    email: $$EMAIL
```

This is an example of the same yaml in 0.5 ... much less verbose!!!!

```
pipeline:
   ...
  docker:
    repo: foo/bar
```

The secrets will be added to your repository using the command line utility (below example) and then injected into the build environment as environment variables. The plugins are being altered, one by one, to read sensitive data from optional environment variables.

```
drone secrets add --image=docker octocat/hello-world DOCKER_USERNAME octocat`
```

I also have a proposal for adding secrets at the organization level. I believe for something like caching this will be important, so that an organization admin can setup the secrets one time, which can in turn be used by every repository in the organization
https://github.com/drone/drone/issues/1619

**Comment by bradrydzewski** [comment]
ok I implemented a simple caching plugin that used sftp to send archives to a remote server. It is important to note this was a separate server in the same Digital Ocean NY1 data center as my build server.

The sftp cache plugin is here if anyone is interested in looking at the code:
https://github.com/drone-plugins/drone-sftp-cache

The yaml file I tested with looked like this:

```
pipeline:
  sftp_cache:
    mount: node_modules
    restore: true

  build:
    image: node:6.0.0
    commands:
      - npm install

  sftp_cache:
    mount: node_modules
    rebuild: true
```

I used this package.json for testing since it seemed rather large:
https://github.com/kriasoft/react-starter-kit/blob/master/package.json

The resulting node_modules file was 250md:

```
$ du -ha 72472a9fbb82887dc9219d6005129b51 
238M	72472a9fbb82887dc9219d6005129b51
```

It took 10 seconds to download and untar the cached node_modules folder:

```
cache restored in 10.133501039s
```

It took 8 seconds to tar and upload the node_modules folder:

```
cache built in 8.762721353s
```

The build time was reduced from 4 minutes to 30 seconds using the cache, so the added 18 seconds to download and upload the cache is well worth it. I would therefore __conclude__ that remote caching should not be a huge issue with reasonable network speed and fast storage (storage speed will vary depending on sftp vs s3 vs whatever else)

**Comment by firrae** [comment]
> I would therefore conclude that remote caching should not be a huge issue with reasonable network speed and fast storage (storage speed will vary depending on sftp vs s3 vs whatever else)

That is more than likely true, and I know my specific case is likely different that most, but I work from home and have hardware in the house that I use for all my development needs (except source storage). As a business starting up it was cheaper for me to do that, and being where I am in Canada I don't have a ton of options when it comes to internet (it's either dial up or the cable company) and even then speeds are slow. That's my main reason for wanting to be able to store locally. I don't have access to using Drone (currently) on anywhere near a Gb connection (I have 30Mbps down and 5Mbps up at best) and with latency to S3 (at least until the Toronto datacenter :D)

Would it be unmanageable? No. But would I have an exponentially better experience running the cache out of my home in some way? More than likely.

I'll keep an eye out for an S3/Minio plugin to try for sure as those are my prefered storage places currently out of the list (I'm not overly savvy to set up ftp/rsync processes, I'm a coder).

**Comment by bradrydzewski** [comment]
Remember that one can always create a custom plugin that uses local storage. The official plugins will push people toward networked storage solutions, but a custom plugin can always mount a volume on the host machine (it will just have to run in trusted mode to do so). 

> I'll keep an eye out for an S3/Minio plugin to try for sure as those are my prefered storage places currently out of the list (I'm not overly savvy to set up ftp/rsync processes, I'm a coder).

sftp runs over ssh so it should be enabled on any linux system, without any special setup required. You just need to provide a username and ssh key.

**Comment by firrae** [comment]
> sftp runs over ssh so it should be enabled on any linux system, without any special setup required. You just need to provide a username and ssh key.

Hm, ok, I'll have to look into that then.
