### ISSUE TITLE
Organization secrets

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1619]
I would like the option to store secrets at the team level and not just at the repository level. This proposal outlines the implement details. Note that I am looking for volunteers to implement this capability and am therefore marking these as help wanted.

### Why?

Some reasons that come to mind:

1. defining per-repository secrets is annoying
2. batch updating per-repositroy secrets is annoying 
3. developers don't always know the secrets
4. developers don't always have admin access to repos to add secrets
5. global secrets are insecure for public facing installations and should be deprecated

### Security Considerations

the following secure measures should be implements:

1. only an organization owner (maintainer in github terminology) can modify secrets
2. organization secrets are only exposed to a build the signature is verified

### Command Line Changes

the command line utility should support adding secrets for organizations:

```
drone secrets add {organization} {key} {value}
drone secrets rm {organization} {key} {value}
```

this should also include mandatory `--image` and `--event` flags for limiting secrets to particular plugins or images, as well as events (ie no pull requests).

### API Changes

the API will require new endpoints for adding secrets:

```
POST /api/teams/{team}/secrets
DELETE /api/teams/{team}/secrets/{key}
```

### Database Changes

the database will require a new table for storing secrets:

```sql
create team_secrets (
    team_secret_id  primary key auto-increment
    team_secret_key varchar(250)
    team_secret_value varchar(2000)
    team_secret_images varchar(2000)  -- json string array
    team_secret_events varchar(2000)  -- json string array
);
```

### Conflict Resolution

the organization secrets should not take precedence over repository secrets. This is more of an implementation detail, but we can easily accomplish this by appending organization secrets to an array before repository secrets. When we loop through the array repository secrets will replace organization secrets in the Docker environment variable map.

**Comment by brgaulin** [comment]
👍  We manage tens of repos, and they share many secrets at the team level, this would be fantastic.

I think some kind of conflict resolution is a good idea, if a repo has a secret, I would expect that to override an organization one.

**Comment by xiaods** [comment]
+1

**Comment by nunofgs** [comment]
Since `PLUGIN_PARAMS` was removed, we are left with no way to manage secrets except manually adding a `drone.sec` to dozens of repositories.

Any news on this PR?

**Comment by bradrydzewski** [comment]
> Since PLUGIN_PARAMS was removed

@nunofgs plugin_params was not removed from the current stable 0.4.2 release. It is still available for use and can still be used in place of drone.sec files.

**Comment by xiaods** [comment]
prefer the central secrets. can't wait the new feature.

**Comment by nunofgs** [comment]
> @bradrydzewski: @nunofgs plugin_params was not removed from the current stable 0.4.2 release. It is still available for use in place of or in conjunction with the drone.sec file.

Indeed. I was referring to 0.50. I understand it's still being worked on. Just wanted to make sure that an alternative to `PLUGIN_PARAMS` was on the way.

> @xiaods: prefer the central secrets. can't wait the new feature.

Yup, sounds great and makes a lot of sense.

**Comment by bradrydzewski** [comment]
@nunofgs just to clarify, even without organization secrets, you won't be required to manually add drone.sec files to dozens of repositories because the drone.sec file was removed in favor of central repository secrets. These secrets still need to be added to each repository, however, as a workaround they could be added in batch to ease the burden:

```sh
drone repo ls | xargs -I{} drone secret add {} KEY VALUE
```

Please note that I've labeled this issue as "help wanted" because it is not something I will be focusing on in the short term. It is likely I will be spending most of my time on bug fixes and stability improvements in the weeks following the 0.5 release, and will not be able to dedicate time to new features. So for those interested in this capability, the best way to accelerate implementation is to send a pull request 😄

**Comment by tboerger** [comment]
I'm starting to work on it. First I will update the client and the API.

**Comment by tboerger** [comment]
To see the progress you can look at https://github.com/tboerger/drone/tree/feature/org-secrets

**Comment by tboerger** [comment]
We can close this since it's implemented, right?

**Comment by donny-dont** [comment]
Need another issue for global now?

**Comment by tboerger** [comment]
> Need another issue for global now?

They are anyway not mentioned within this issue :)

**Comment by maximelebastard** [comment]
Has this been removed?
http://readme.drone.io/0.5/usage/cli/cli_secret/

I can't see the topic org in my CLI.
I guess it has been replaced by global secrets and vault secrets which need an Enterprise pack, isn't it?
