### ISSUE TITLE
Drone distributed setup

### ISSUE THREAD

**Issue by bbaugher** [drone/drone#162]
This is more of a question than an issue but is it possible to setup several drone "slaves" that build for the same repo or repos? It doesn't call this out in the docs but it seems to be possible if they all share the a database and you [add a proxy](http://drone.readthedocs.org/en/latest/install.html#proxy-server) in front of them. If so, can you point me to the docs that explain how to configure drone's database connection? Can you run into problems with a setup like this?

**Comment by bradrydzewski** [comment]
ok, this feature is complete and we even have documentation:
http://readme.drone.io/setup/config/workers/

This is just an initial implementation and is still a bit involved. I have some ideas for simplifying this and allowing you to provision servers in the UI. See https://github.com/drone/drone/issues/852

**Comment by liveforeverx** [comment]
@bradrydzewski Hi! It seems, like the configuration disappear from documentation. Does feature was removed in new versions?

**Comment by bradrydzewski** [comment]
@liveforeverx the documentation for the current stable version can be found at https://github.com/drone/drone/blob/v0.4.0/docs/cli/machines.md
