### ISSUE TITLE
Organization plugins

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1620]
Just a reaction to seeing the organization secrets PR, a related issue is organization-level plugins i.e. to add default notification plugins.

We've run straight into this issue using drone currently where we have a shared mailing list which should receive build notifications, but a large number of repositories where we'd need to manually specify email servers/settings (or script it, but the maintenance overhead is substantial).

This would be an extra field against an organization which pointed to a git repository which contained the shared `.drone.yml` file for the organization. A refinement of the concept might allow for a folder structure to customize this per repository.

**Comment by bradrydzewski** [comment]
this has come up in the past and we've declined to implement this feature. It comes with quite a bit of complexity and edge cases, and we felt the complexity was justified.
