### ISSUE TITLE
UI text for pull requests

### ISSUE THREAD

**Issue by jeffastorey** [drone/drone#1623]
When a build is executed from a pull request, the text of the UI shows the target branch, like `<user> has authored to <target-branch>`.  This is confusing because the authoring to that branch hasn't occurred yet. Ideally we could have text that looks like `@bradrydzewski opened pull request #11 to master`

**Comment by xiaods** [comment]
Cool，any update?

**Comment by bradrydzewski** [comment]
I moved the issue to https://github.com/drone/drone-ui/issues/46 where the new user interface resides.
