### ISSUE TITLE
Workspace Size Limit?

### ISSUE THREAD

**Issue by steve-gray** [drone/drone#1629]
Hey @bradrydzewski,

I'm finding I'm having some difficulty with a docker-in-docker setup for a compose based test. Basically I'm:

- Creating a DIND service in a container
- Running a DIND client as the 'build' task with a DOCKER_HOST environ set.

Some specifics;
- Running docker version from the client shows both the server/client image versions as expected.
- When running docker-compose from the client/build sequence container, it'll invariably bomb out early with:

```
$ docker-compose -p self_contained up -d
Creating network "selfcontained_default" with the default driver
Pulling site_sso (private-repo-path-removed-from-github-post.com/mocks/sso:v1.0.0)...
v1.0.0: Pulling from mocks/sso
Digest: sha256:a2fa6532491a966b15c3048d43e31773953775ba7f5e8976cc375e2164f4d759
Status: Downloaded newer image for private-repo-path-removed-from-github-post.com/mocks/sso:v1.0.0
Creating selfcontained_site_sso_1

ERROR: for site_sso  Untar re-exec error: exit status 1: output: write /var/cache/yum/x86_64/7/base/gen/primary_db.sqlite: no space left on device
Traceback (most recent call last):
  File "<string>", line 3, in <module>
[info] build failed (exit code 255)
```

I've tried running df -h against both the running container and the service container to see who's out of space, and only the /drone mount seems to be approaching full. Are the containers somehow having their data logged to that path?

Any ideas?

-Steve

**Comment by bradrydzewski** [comment]
drone doesn't have any workspace limits (or resource limits for that matter)

let's move this discussion to the [gitter channel](https://gitter.im/drone/drone) and we can re-open this issue if we can confirm a bug with drone. We're trying to reserve the issue tracker for confirmed bugs, and use the gitter room for questions and troubleshooting
