### ISSUE TITLE
How to set the "Authorization callback URL" within Github

### ISSUE THREAD

**Issue by qq511700505** [drone/drone#1642]
I used the docker image **drone:drone:0.4.0**, and set the **Application callback URL** as 
`http://drone.linoxide.com/api/auth/github.com `, as the official user guide says.
But I get an error respond from trying to  retrieve the URL : ` http://drone.linoxide.com/api/auth/github.com?error=redirect_uri_mismatch&..... `

What should I do， please give some advice, thanks.

**Comment by bradrydzewski** [comment]
@qq511700505 please read the official drone documentation (anything referring to api/auth/github.com is very outdated). http://readme.drone.io

also per the issue template, please use the [gitter room](https://gitter.im/drone/drone) for questions and reserve the issue tracker for bugs
