### ISSUE TITLE
Tidb is recommended instead of SQLite, remove the dependency on CGO

### ISSUE THREAD

**Issue by insionng** [drone/drone#1643]

**Comment by tboerger** [comment]
No chance... Sqlite is battle tested, meddler doesn't support it, the migration lib doesn't support it.

**Comment by insionng** [comment]
Well then, the problem is closed.

**Comment by bradrydzewski** [comment]
@insionng we've considered tidb in the past and I would certainly like to remove the CGO dependency. I think it is definitely something we'd consider once it is more mature. Thanks!

**Comment by insionng** [comment]
@bradrydzewski Okay.
