### ISSUE TITLE
i wonder to know whether drone server support HA mode. 

### ISSUE THREAD

**Issue by xiaods** [drone/drone#1647]
i have been search the docs, i am not found any clues on ha relative topic with drone, anyone don't care it?

**Comment by tboerger** [comment]
There is no ha yet since the queue is in-memory. But it's on the plan of course. Moving to agents instead of push for the jobs is the first step

**Comment by tboerger** [comment]
Beside that, the issue tracker is reserved for confirmed bugs, for questions like that we've got the Gitter chat or discuss.drone.io

**Comment by xiaods** [comment]
@tboerger thanks for your reminder, closed it.
