### ISSUE TITLE
[0.5.x] Bitbucket remote driver oAuth error

### ISSUE THREAD

**Issue by andrewmclagan** [drone/drone#1650]
Booting up 0.5 using the Bitbucket remote receiving the following oAuth error response in my logs:

`level=error msg="cannot authenticate user. oauth2: cannot fetch token: 400 BAD REQUEST\nResponse: {\"error_description\": \"Invalid OAuth client credentials\", \"error\": \"unauthorized_client\"}"`

Steps attempting to resolve:

- Have verified that the correct credentials are set
- The callback URL is correct
- Previously worked on 0.4 branch
- Wiped the oAuth credentials and started again
- Github remote works fine
- Removing container between runs
- Verified the ENV_VARS are present in the container

Settings are as follows:

(docker-compose)
````
drone:
    image: drone/drone:0.5
    ports:
        - 80:8000/tcp
    env_file: ./.dronerc
    volumes:
        - /var/lib/drone:/var/lib/drone
````

(.dronerc)
````

I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION=true
I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS=true
GIN_MODE=debug
DRONE_OPEN=true
DRONE_AGENT_SECRET=**REDACTED**
DRONE_ADMIN=**REDACTED**
DRONE_BITBUCKET=true
DRONE_BITBUCKET_CLIENT=**REDACTED**
DRONE_BITBUCKET_SECRET=**REDACTED**
DATABASE_DRIVER=mysql
DATABASE_CONFIG=**REDACTED**@tcp(**REDACTED**:3306)/continuous_integration?parseTime=true
````

------------
- [**YES** ] I have searched for existing issues
- [**YES**] I have discussed the issue with the community at https://gitter.im/drone/drone
- [**YES**] I have provided a sample `.drone.yml` file to help the team reproduce
- [**N/A**] I have provided details from the build logs
- [**YES**] I have provided details from the server logs by running `docker logs drone`
- [**YES**] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
Good catch ... looks like we were using the wrong flag name. Fixed with https://github.com/drone/drone/commit/82eb00a4d004e330ef5b405e84d3a155f98a23b9 and new image published

**Comment by andrewmclagan** [comment]
Was just cURLing to trace back through the stack.. thanks for that.

**Comment by andrewmclagan** [comment]
I will reopen this with the following:

It seems agents are having trouble cloning from Bitbucket, failing with the following error:

`fatal: could not read Username for 'https://bitbucket.org': No such device or address`

Without ...allot... of investigation or knowledge of how agents are to authenticate when cloning private repos I assume its related to the above Bitbucket issue in general?

**Comment by paketo-admin** [comment]
Hi, 
You can below curl URL 

$ curl -X POST -u "client_id:secret" \
  https://bitbucket.org/site/oauth2/access_token -d grant_type=password \
  -d username={username} -d password={password} /// this is API exposed by bitbucket

where
client_id : your client id (eg: 75frt****)
secret : your secret key (eg:8uyrioooreu*****)

username : <Your bitbuket login username>
password : <Your bitbucket login password>

so above url will be updated as
$ curl -X POST -u "75frt****:8uyrioooreu****" \
  https://bitbucket.org/site/oauth2/access_token -d grant_type=password \
  -d username={abc123@gmail.com} -d password={******} 

Note : Initially i was using alias username in 'username' field and i was facing error "Unauthorised client" error, later when i changed username to my registered email id [abc123@gmail.com], it worked fine.

Hope this helps.

**Comment by tboerger** [comment]
And how should that help on an issue closed a year ago?
