### ISSUE TITLE
Webhook 404 for Github pull requests

### ISSUE THREAD

**Issue by adamlc** [drone/drone#1651]
Hey guys, we're actually just in to process of migrating from GitLab to GitHub (and using Drone). For some reason the webhooks in Github seem to be failing for pull_requests, everything else seems to work fine!

Heres the requests and responses from the Github UI.

```
Request URL: https://drone.jumplead.com/hook?access_token=**SNIP**
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/375c44e
X-GitHub-Delivery: **SNIP**
X-GitHub-Event: pull_request
```

```
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
Connection: keep-alive
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Fri, 20 May 2016 14:25:08 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Fri, 20 May 2016 14:25:08 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Drone-Version: 0.4.1+373
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
```

Also drone logs:

```
time="2016-05-20T14:25:08Z" level=error msg="failure to get build config for Jumplead/Worker. GET https://api.github.com/repos/Jumplead/Worker/contents/.drone.yml?ref=7d16e8a5ce7f6b968e72fb9f002991a54fc972a3: 404 Not Found []"
time="2016-05-20T14:25:08Z" level=error msg="Error #01: GET https://api.github.com/repos/Jumplead/Worker/contents/.drone.yml?ref=7d16e8a5ce7f6b968e72fb9f002991a54fc972a3: 404 Not Found []\n" ip=192.30.252.46 latency=391.891183ms method=POST path="/hook" status=404 time="2016-05-20T14:25:08Z" user-agent="GitHub-Hookshot/375c44e"
```

This is a private repo btw. Looks to be something wrong with the reference? Possibly similar issue to #1463?

**Comment by bradrydzewski** [comment]
does your pull request include a valid .drone.yml file? It is getting a 404 when trying to fetch the pull request. There are no known issues with fetching the .drone.yml for pull requests, aside from when using amendments for which we have an open issue.

given my inability to repeat and no other installations reporting issues this is something you're going to need to dig into further. You should be able to look at the pull request hook sent from GitHub and:

1. what sha is drone using from the hook?
2. why does that sha return a 404 when fetching the .drone.yml?
3. did the user that registered the repository de-authorize drone, preventing it from being able to authorize the request to the fetch the yaml?

also note that, per the issue template, issues should be discussed in https://gitter.im/drone/drone prior to logging issues.

**Comment by adamlc** [comment]
@bradrydzewski That would well be it! To be honest that didnt even cross my mind, I'll add a Drone file to my PR and see if that works!

**Comment by adamlc** [comment]
That was it @bradrydzewski, apologies about that. I'll put it down to being a friday. Have a great weekend!

**Comment by bradrydzewski** [comment]
no worries, glad that fixed it :)
