### ISSUE TITLE
RFC: Logging within Plugins

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#1656]
I was getting to the point where I was going to start migrating some plugins to 0.5. What I'm wondering is if we should standardize on how plugins log.

In Golang this is [logrus](https://github.com/Sirupsen/logrus). One nice thing there is that we could have a custom log formatter for the Drone plugins. This would provide a standard way of logging that could then be utilized by the UI. For example you could maybe toggle on and off the logging from the plugins. This might be a better solution than having a `debug: true` for each plugin.

Anyone have any particular thoughts here?

**Comment by tboerger** [comment]
A custom logrus formatter sounds totally fine to me. We can get similar functionality for node, ruby and python as well.

**Comment by bradrydzewski** [comment]
If we use logrus we would need to write custom formatters. This is the current log output from the S3 plugin which is difficult to read from the command line:

```
time="2016-06-17T17:12:18Z" level=info msg="Attempting to upload" bucket=downloads.drone.io endpoint= region=us-east-1 
time="2016-06-17T17:12:18Z" level=info msg="Uploading file" bucket=downloads.drone.io content-type="application/octet-stream" name="release/darwin/amd64/drone.sha256" target="/release/darwin/amd64/drone.sha256" 
time="2016-06-17T17:12:19Z" level=info msg="Uploading file" bucket=downloads.drone.io content-type="application/gzip" name="release/darwin/amd64/drone.tar.gz" target="/release/darwin/amd64/drone.tar.gz" 
time="2016-06-17T17:12:19Z" level=info msg="Uploading file" bucket=downloads.drone.io content-type="application/octet-stream" name="release/linux/amd64/drone.sha256" target="/release/linux/amd64/drone.sha256" 
```

I think something like this would be more readable:

```
uploading files to downloads.drone.io

release/darwin/amd64/drone.sha256 -> /release/darwin/amd64/drone.sha256
release/darwin/amd64/drone.tar.gz -> /release/darwin/amd64/drone.tar.gz
release/linux/amd64/drone.sha256" -> /release/linux/amd64/drone.sha256

successfully uploaded 3 files
```

If we are going to use `logrus.WithFields` we will need to write custom formatters. It is likely that a single plugin will require multiple formatters because it is logging different data points for different events. For example, the S3 plugin has more generic debug statements:

```
time="2016-06-17T17:12:18Z"
   level=info
   msg="Attempting to upload"
   bucket=downloads.drone.io
   endpoint= region=us-east-1 
```

and more detailed file upload information:

```
time="2016-06-17T17:12:18Z"
  level=info
  msg="Uploading file"
  bucket=downloads.drone.io
  content-type="application/octet-stream"
  name="release/darwin/amd64/drone.sha256"
```

This does pose a small challenge because we can only have a single logrus formatter:

```
logrus.SetFormatter(...)
```

We could work around the issue by having a formatter that is capable of inspecting the fields, and formatting the output appropriately:

```
type formatter struct {}

func (f *formatter) Format(entry *Entry) ([]byte, error) {
  if v, ok := entry.Data["target"]; ok {
    return []byte{
      fmt.Sprintf("%s -> %s", entry.Data["name"], entry.Data["target"]),
    }, nil
  }
  // else if debug statement for bucket
  // else if error uploading
  // else if error reading file
  // else if error parsing glob
}
```

I think the logrus `log.WithFields` is very clean and readable, however, formatters could end up being much more verbose that something like `log.Infof("%s -> %s", name, target)`

**Comment by jamesk** [comment]
Just my thoughts, realise I might be lacking some context:
Wouldn't it be better for the raw logs to contain as much information as possible i.e. be structured e.g. JSON

The specification from drone's point of view should be around the format of plugin logs e.g JSON vs XML vs CSV and which fields have meaning to drone e.g. `level`. I could imagine a toggle in the UI that flips between something like the readable example and the raw logs which would be the UI parsing and rendering.

As a simple example if the logs were in JSON format the UI could filter out all debug messages on toggle and then only display the `msg` field, highlighting `warn` level messages in yellow and `error` messages in red. Or perhaps display the `msg` field and other fields with a certain prefix e.g. `simple_` or `simple.`

**Comment by thomasf** [comment]
I'm almost there with the first draft of a new package for writing plugins
(https://github.com/thomasf/drone-plugins-go).

I just have a few plain package level methods:

```go

func Debug(v ...interface{})
func Debugf(format string, v ...interface{})
func Debugln(v ...interface{})
func Fatal(v ...interface{})
func Fatalf(format string, v ...interface{})
func Fatalln(v ...interface{})
func Print(v ...interface{})
func Printf(format string, v ...interface{})
func Println(v ...interface{})

// these are non standard loggers which prints as a field error, see example below.

func Usage(value interface{}, v ...interface{})
func Usagef(value interface{}, format string, v ...interface{})
func Usageln(value interface{}, v ...interface{})
```
 
Latest prototype:


API Usage:

```go
package main

import (
	"context"
	"flag"

	"github.com/thomasf/drone-plugins-go/plug"
)

var build = "0" // build number set at compile-time

// Plugin defines the Downstream plugin parameters.
type Plugin struct {
	Repos  []string
	Server string
	Token  string
	Fork   bool

}

func main() {
	var p Plugin
	flag.BoolVar(&p.Fork, "fork", false, "Trigger a new build for a repository")
	plug.StringSliceVar(&p.Repos, "repositories", "List of repositories to trigger")
	flag.StringVar(&p.Server, "server", "", "Trigger a drone build on a custom server")
	plug.Env(&p.Server, "DOWNSTREAM_SERVER", "") // emtpy string means default PLUGIN_...
	flag.StringVar(&p.Token, "token", "", "Drone API token from your user settings")
	plug.Env(&p.Token, "DOWNSTREAM_TOKEN", "")
	plug.EnvFiles()
	plug.Run(p.Exec)
}

// Exec runs the plugin
func (p *Plugin) Exec(ctx context.Context) error {

	isValid := true
	if len(p.Token) == 0 {
		plug.Usageln(&p.Token, "you must provide your Drone access token.")
		plug.Debugln("not valid")
		isValid = false
	}

	if len(p.Server) == 0 {
		plug.Usageln(&p.Server, "you must provide your Drone server.")
		plug.Debugln("not valid")
		isValid = false
	}

	if !isValid {
		return plug.ErrUsageError
	}

	//client := drone.NewClientToken(p.Server, p.Token)
	// ...
	plug.Println("success!")
	return nil
}

```

Usage as a plugin:

```
$ PLUGIN_ENV_FILE=1.env,2.env go run main.go  -server asd -token asd 
success!
```

or with debug enabled (PLUGIN_PLUGIN_DEBUG=1):

```
$ PLUGIN_PLUGIN_DEBUG=1 PLUGIN_ENV_FILE=1.env,2.env go run main.go  -server asd -token asd 
19:59:01 plug.go:28: drone plugins debug mode is active!
19:59:01 plug.go:30: flag 'env-file' using env vars: PLUGIN_ENV_FILE
19:59:01 plug.go:30: flag 'fork' using env vars: PLUGIN_FORK
19:59:01 plug.go:30: flag 'repositories' using env vars: PLUGIN_REPOSITORIES
19:59:01 plug.go:30: flag 'server' using env vars: DOWNSTREAM_SERVER, PLUGIN_SERVER
19:59:01 plug.go:30: flag 'token' using env vars: DOWNSTREAM_TOKEN, PLUGIN_TOKEN
19:59:01 plug.go:50: loading env files: 1.env, 2.env
19:59:01 plug.go:53: error loading env files: open 2.env: no such file or directory
19:59:01 plug.go:57: [envfile] setting PLUGIN_TOKEN=WOHOO
19:59:01 plug.go:88: flag 'env-file' set by env var 'PLUGIN_ENV_FILE': 1.env,2.env
19:59:01 plug.go:88: flag 'token' set by env var 'PLUGIN_TOKEN': asd
19:59:01 plug.go:93: ------ executing plugin func  -----
19:59:01 main.go:54: success!
19:59:01 plug.go:95: ------ plugin func done  -----
```

or a (very rudimentary) formatted usage print. 

```
$ PLUGIN_ENV_FILE=1.env,2.env PLUGIN_FORK=cool go run main.go  -server asd -token asd 
plugin option 'fork' error: strconv.ParseBool: parsing "cool": invalid syntax
Usage: Trigger a new build for a repository
plugin usage:

source env file
names as plugin option: env_file
currently set by: env_file
current value 1.env,2.env

Trigger a new build for a repository
names as plugin option: fork
currently set by: fork
current value false

List of repositories to trigger
names as plugin option: repositories

Trigger a drone build on a custom server
names as plugin option: server
names as env var: downstream_server

Drone API token from your user settings
names as plugin option: token
names as env var: downstream_token
exit status 1
```

**Comment by bradrydzewski** [comment]
In an effort to keep drone simple, I am closing this as out of scope. I think developers are accustomed to reading unstructured log data at the terminal, and this would provide an overall small benefit compared to effort and complexity it would introduce.

I think we should instead focus on improving the terminal component in the user interface, adding code folding, similar to Travis et al.
