### ISSUE TITLE
Signature newlines Windows vs Unix

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1662]
There is an issue when attempting to sign a file on windows due to newlines. Windows uses `\r\n` and Unix uses `\n`. When cloning a repository it seems like git converts newlines to the Windows format automatically depending on your git configuration, which means signature created on Windows may not match the actual file pushed to your git repository.

cc @donny-dont

**Comment by donny-dont** [comment]
https://help.github.com/articles/dealing-with-line-endings/ for reference

**Comment by johnwchadwick** [comment]
I am also facing this problem, but I'm unsure what the solution should be. I'm thinking the easiest way to deal with it would be to try to deduce the autocrlf option, but that seems obtrusive. Perhaps a more robust, and less obtrusive, way to deal with it would be to always convert crlf sequences to lf sequences for purposes of signing, thus making this a non-issue - but that _might_ break existing signatures, if users use a non-default autocrlf option. Thoughts?

**Comment by bradrydzewski** [comment]
I thinking stripping `\r` with `bytes.Replace` is probably fine. This is what Go itself does to handle `\r\n` and `\n` discrepancies.

**Comment by johnwchadwick** [comment]
Would it also make sense to trim `\n` if it's the last character? Some text editors forcibly add it as a result of the different semantic ideas people have about line termination (you know, whether the last line requires a terminator.)

Either way, if you want, I can make a pull request for this.

**Comment by tboerger** [comment]
I think dropping \r should be fine

**Comment by bradrydzewski** [comment]
signatures gone in upcoming release. closing! :)
