### ISSUE TITLE
Long terminal output is trimmed

### ISSUE THREAD

**Issue by makkrnic** [drone/drone#1665]
When terminal output is very long, it gets trimmed after some time. See http://sartura-drone.makkrnic.com/makkrnic/openwrt-qemu-x86/6
The terminal output is missing after the first `[ 69%]` and since the build succeeded, there obviously should be more output.

**Comment by bradrydzewski** [comment]
we have open issues https://github.com/drone/drone/issues/1429 https://github.com/drone/drone/issues/733 and https://github.com/drone/drone/issues/1563 concerning large log output
