### ISSUE TITLE
Branch in build environment is always "master", even if that wasn't the branch that triggered the build

### ISSUE THREAD

**Issue by bitemyapp** [drone/drone#1669]
I'm trying to get a CI process setup whereby I fire off my ansible deployment when a branch named `staging` is pushed to and successfully builds. To that end, I'd like it if the checkout of my repo had the matching branch name.

Is there some means of accomplishing that?

**Comment by donny-dont** [comment]
@bitemyapp please use our Gitter channel or our Discuss forum for these sorts of questions. It keeps down on the number of issues and does not bog the development down.

http://readme.drone.io/community/overview/

**Comment by bitemyapp** [comment]
@donny-dont it needs fixed regardless of whether I find a workaround.

**Comment by bradrydzewski** [comment]
@bitemyapp cloning is handled by plugins. Please feel free to send a PR to https://github.com/drone-plugins/drone-git that alters the default behavior
