### ISSUE TITLE
orgs=myorg doesn't work

### ISSUE THREAD

**Issue by mastertinner** [drone/drone#1673]
In the documentation http://readme.drone.io/setup/remotes/bitbucket/ it says that I can append my `REMOTE_CONFIG` with `?orgs=myorg`. For me this feature doesn't work and it's also not documented in the API of Bitbucket. Furthermore, Bitbucket doesn't know any concept of an Organization like Github. They have "Teams". Is this a legit feature or just a copy-paste bug from Github?

**Comment by bradrydzewski** [comment]
> Bitbucket doesn't know any concept of an Organization like Github. They have "Teams". Is this a legit feature or just a copy-paste bug from Github?

drone uses GitHub semantics and naming, but yes, this refers to Bitbucket teams

> For me this feature doesn't work and it's also not documented in the API

Please note that organizations are case sensitive and you need to request the appropriate permissions when you configure oauth scopes. You also need to use the slug name. I have an team called `drone.io` which needs to be declared as `droneio` (bitbucket slug name)

I just spent 30 minutes testing this against 0.5 using both failure and success scenarios, and was able to confirm it is working as expected. I'm therefore going to close this issue.

In the future I recommend using the gitter room to ask questions and get help debugging, prior to logging issue, as requested by our github issue template. https://gitter.im/drone/drone
