### ISSUE TITLE
Create 0.4 for branches for the currently available plugins

### ISSUE THREAD

**Issue by tboerger** [drone/drone#1675]
To track the progress of the branching for the 0.4 release I have opened this issue. Below you can see a list of plugins that have been branched or which should be branched before the migration to 0.5. Feel free to mark rows as done if I missed something!
## Branch
- [x] [drone-anynines](https://github.com/drone-plugins/drone-anynines)
- [x] [drone-artifactory](https://github.com/drone-plugins/drone-artifactory)
- [x] [drone-azure-storage](https://github.com/drone-plugins/drone-azure-storage)
- [x] [drone-azure-web-apps](https://github.com/drone-plugins/drone-azure-web-apps)
- [x] [drone-bintray](https://github.com/drone-plugins/drone-bintray)
- [x] [drone-bitballoon](https://github.com/drone-plugins/drone-bitballoon)
- [x] [drone-cache](https://github.com/drone-plugins/drone-cache)
- [x] [drone-chef](https://github.com/drone-plugins/drone-chef)
- [x] [drone-chef-supermarket](https://github.com/drone-plugins/drone-chef-supermarket)
- [x] [drone-cloudcontrol](https://github.com/drone-plugins/drone-cloudcontrol)
- [x] [drone-cloudfoundry](https://github.com/drone-plugins/drone-cloudfoundry)
- [x] [drone-codedeploy](https://github.com/drone-plugins/drone-codedeploy)
- [x] [drone-containership](https://github.com/drone-plugins/drone-containership)
- [x] [drone-coverage](https://github.com/drone-plugins/drone-coverage)
- [x] [drone-deis](https://github.com/drone-plugins/drone-deis)
- ~~[drone-devpi](https://github.com/drone-plugins/drone-devpi)~~ (moved development)
- [x] [drone-docker](https://github.com/drone-plugins/drone-docker)
- [x] [drone-dockerhub](https://github.com/drone-plugins/drone-dockerhub)
- [x] [drone-dotcloud](https://github.com/drone-plugins/drone-dotcloud)
- [x] [drone-downstream](https://github.com/drone-plugins/drone-downstream)
- [x] [drone-ecr](https://github.com/drone-plugins/drone-ecr)
- [x] [drone-ecs](https://github.com/drone-plugins/drone-ecs)
- [x] [drone-elastic-beanstalk](https://github.com/drone-plugins/drone-elastic-beanstalk)
- [x] [drone-email](https://github.com/drone-plugins/drone-email)
- [x] [drone-gcr](https://github.com/drone-plugins/drone-gcr)
- [x] [drone-gh-pages](https://github.com/drone-plugins/drone-gh-pages)
- [x] [drone-git](https://github.com/drone-plugins/drone-git)
- [x] [drone-github-release](https://github.com/drone-plugins/drone-github-release)
- [x] [drone-git-push](https://github.com/drone-plugins/drone-git-push)
- [x] [drone-gitter](https://github.com/drone-plugins/drone-gitter)
- [x] [drone-google-cloudstorage](https://github.com/drone-plugins/drone-google-cloudstorage)
- [x] [drone-heroku](https://github.com/drone-plugins/drone-heroku)
- [x] [drone-hg](https://github.com/drone-plugins/drone-hg)
- [x] [drone-hipchat](https://github.com/drone-plugins/drone-hipchat)
- [x] [drone-irc](https://github.com/drone-plugins/drone-irc)
- [x] [drone-marathon](https://github.com/drone-plugins/drone-marathon)
- [x] [drone-npm](https://github.com/drone-plugins/drone-npm)
- [x] [drone-nuget](https://github.com/drone-plugins/drone-nuget)
- [x] [drone-opsworks](https://github.com/drone-plugins/drone-opsworks)
- [x] [drone-pushover](https://github.com/drone-plugins/drone-pushover)
- ~~[drone-pypi](https://github.com/drone-plugins/drone-pypi)~~ (moved development)
- [x] [drone-rancher](https://github.com/drone-plugins/drone-rancher)
- [x] [drone-rsync](https://github.com/drone-plugins/drone-rsync)
- [x] [drone-rubygems](https://github.com/drone-plugins/drone-rubygems)
- [x] [drone-s3](https://github.com/drone-plugins/drone-s3)
- [x] [drone-s3-sync](https://github.com/drone-plugins/drone-s3-sync)
- [x] [drone-scalingo](https://github.com/drone-plugins/drone-scalingo)
- [x] [drone-sftp](https://github.com/drone-plugins/drone-sftp)
- [x] [drone-sftp-cache](https://github.com/drone-plugins/drone-sftp-cache)
- [x] [drone-slack](https://github.com/drone-plugins/drone-slack)
- [x] [drone-slack-blame](https://github.com/drone-plugins/drone-slack-blame)
- [x] [drone-ssh](https://github.com/drone-plugins/drone-ssh)
- [x] [drone-terraform](https://github.com/drone-plugins/drone-terraform)
- [x] [drone-tutum](https://github.com/drone-plugins/drone-tutum)
- [x] [drone-webhook](https://github.com/drone-plugins/drone-webhook)
## Migrate
- [ ] [drone-anynines](https://github.com/drone-plugins/drone-anynines)
- [ ] [drone-artifactory](https://github.com/drone-plugins/drone-artifactory)
- [ ] [drone-azure-storage](https://github.com/drone-plugins/drone-azure-storage)
- [ ] [drone-azure-web-apps](https://github.com/drone-plugins/drone-azure-web-apps)
- [ ] [drone-bintray](https://github.com/drone-plugins/drone-bintray)
- [ ] [drone-bitballoon](https://github.com/drone-plugins/drone-bitballoon)
- [ ] [drone-cache](https://github.com/drone-plugins/drone-cache)
- [ ] [drone-chef](https://github.com/drone-plugins/drone-chef)
- [ ] [drone-chef-supermarket](https://github.com/drone-plugins/drone-chef-supermarket)
- [ ] [drone-cloudcontrol](https://github.com/drone-plugins/drone-cloudcontrol)
- [ ] [drone-cloudfoundry](https://github.com/drone-plugins/drone-cloudfoundry)
- [ ] [drone-codedeploy](https://github.com/drone-plugins/drone-codedeploy)
- [ ] [drone-containership](https://github.com/drone-plugins/drone-containership)
- [x] [drone-coverage](https://github.com/drone-plugins/drone-coverage)
- [ ] [drone-deis](https://github.com/drone-plugins/drone-deis)
- ~~[drone-devpi](https://github.com/drone-plugins/drone-devpi)~~ (moved development)
- [x] [drone-docker](https://github.com/drone-plugins/drone-docker)
- [ ] [drone-dockerhub](https://github.com/drone-plugins/drone-dockerhub)
- [ ] [drone-dotcloud](https://github.com/drone-plugins/drone-dotcloud)
- [x] [drone-downstream](https://github.com/drone-plugins/drone-downstream)
- [ ] [drone-ecr](https://github.com/drone-plugins/drone-ecr)
- [ ] [drone-ecs](https://github.com/drone-plugins/drone-ecs)
- [ ] [drone-elastic-beanstalk](https://github.com/drone-plugins/drone-elastic-beanstalk)
- [ ] [drone-email](https://github.com/drone-plugins/drone-email)
- [ ] [drone-gcr](https://github.com/drone-plugins/drone-gcr)
- [x] [drone-gh-pages](https://github.com/drone-plugins/drone-gh-pages)
- [x] [drone-git](https://github.com/drone-plugins/drone-git)
- [x] [drone-github-release](https://github.com/drone-plugins/drone-github-release)
- [x] [drone-git-push](https://github.com/drone-plugins/drone-git-push)
- [x] [drone-gitter](https://github.com/drone-plugins/drone-gitter)
- [ ] [drone-google-cloudstorage](https://github.com/drone-plugins/drone-google-cloudstorage)
- [ ] [drone-heroku](https://github.com/drone-plugins/drone-heroku)
- [ ] [drone-hg](https://github.com/drone-plugins/drone-hg)
- [ ] [drone-hipchat](https://github.com/drone-plugins/drone-hipchat)
- [ ] [drone-irc](https://github.com/drone-plugins/drone-irc)
- [x] [drone-marathon](https://github.com/drone-plugins/drone-marathon)
- [x] [drone-npm](https://github.com/drone-plugins/drone-npm)
- [ ] [drone-nuget](https://github.com/drone-plugins/drone-nuget)
- [ ] [drone-opsworks](https://github.com/drone-plugins/drone-opsworks)
- [ ] [drone-pushover](https://github.com/drone-plugins/drone-pushover)
- ~~[drone-pypi](https://github.com/drone-plugins/drone-pypi)~~ (moved development)
- [ ] [drone-rancher](https://github.com/drone-plugins/drone-rancher)
- [ ] [drone-rsync](https://github.com/drone-plugins/drone-rsync)
- [ ] [drone-rubygems](https://github.com/drone-plugins/drone-rubygems)
- [x] [drone-s3](https://github.com/drone-plugins/drone-s3)
- [x] [drone-s3-sync](https://github.com/drone-plugins/drone-s3-sync)
- [ ] [drone-scalingo](https://github.com/drone-plugins/drone-scalingo)
- [ ] [drone-sftp](https://github.com/drone-plugins/drone-sftp)
- [x] [drone-sftp-cache](https://github.com/drone-plugins/drone-sftp-cache)
- [x] [drone-slack](https://github.com/drone-plugins/drone-slack)
- [x] [drone-slack-blame](https://github.com/drone-plugins/drone-slack-blame)
- [x] [drone-ssh](https://github.com/drone-plugins/drone-ssh)
- [ ] [drone-terraform](https://github.com/drone-plugins/drone-terraform)
- [ ] [drone-tutum](https://github.com/drone-plugins/drone-tutum)
- [ ] [drone-webhook](https://github.com/drone-plugins/drone-webhook)

**Comment by MetalMatze** [comment]
👍 Does that mean, that the plugins will be available as docker images with a 0.4 tag? Will drone use them automatically?

**Comment by MetalMatze** [comment]
I see, thanks!

**Comment by tboerger** [comment]
But to directly answer the question, it will work out of the box with 0.4 and the same for 0.5 when the plugin is migrated.

**Comment by bradrydzewski** [comment]
I updated the list above. Note that some plugins have already been ported to 0.5 but the code is sitting in a `release/0.5` branch

**Comment by donny-dont** [comment]
NPM has an open pull request https://github.com/drone-plugins/drone-npm/pull/9

Slack Blame has work on https://github.com/drone-plugins/drone-slack-blame/tree/feature/0.5-update

**Comment by tboerger** [comment]
So for the migration to 0.5 builds of the existing plugins there is only pushover pending. It's just pending because the author of the used go lib has removed the lib from github :(

**Comment by bradrydzewski** [comment]
This is my initial thoughts on which plugins will be managed under the offiicial namespace. I will individually message top contributors of projects not in this list to take individual ownership.

There isn't really any well-defined criteria for what is official vs unofficial. These are some of the criteria I'm considering:

1. is this plugin critical to drone or the drone build / release process?
1. is this plugin very heavily used by the drone community?
1. is this plugin for a major service (ie S3)
1. is this plugin for a core unix utility (ie ssh)
1. is this plugin simple and relatively feature complete?
1. does this plugin require elevated privilege and code review (docker, grc)

The list ended up being a bit longer than initially expected, however, I expect most of these plugins will be mostly frozen with the exception of bug fixes. There will be a major focus on stability and I plan to heavily encourage developers to fork and extend as opposed to supporting every possible feature or configuration option.

### official

1. drone-coverage __[ready]__
1. drone-docker __[ready]__
1. drone-downstream
1. drone-gcr
1. drone-git __[ready]__
1. drone-git-push
1. drone-gitter __[ready]__
1. drone-google-cloudstorage
1. drone-hg
1. drone-npm __[ready]__
1. drone-rsync
1. drone-s3 (merge with s3-sync) __[ready]__
1. drone-sftp-cache __[ready]__
1. drone-slack __[ready]__
1. drone-ssh 
1. drone-webhook

Currently __8__ out of __16__ plugins are ported and ready for 0.5

### maybe official

1. drone-email
1. drone-github-release
1. drone-gh-pages
1. drone-heroku
1. drone-ecr

**Comment by tboerger** [comment]
Feel free to transfer the ownership to drone-community :)

**Comment by gtaylor** [comment]
This makes sense to me, and we can bend either way as needed.

Only note I have is that if we're making drone-gcr official, we should probably do the same for drone-ecr. Alternatively, I believe one or both of these can be done with drone-docker now. 

I don't feel strongly, but I figured I'd cast "Unofficial" votes for:

* drone-github-release (The behaviors here can vary a bit. Punt to the community)
* drone-gh-pages (Ditto)
* drone-heroku (Maybe we could convince someone with Heroku ties to take this on?)

Yes votes:

* drone-email (Not sexy, but a chunk of users will expect this to be present and solid)
* drone-ecr (See earlier statement, or nuke drone-gcr and drone-ecr entirely)

**Comment by bradrydzewski** [comment]
I think `drone-ecr` and `drone-gcr` could actually just be simple scripts that wrap the main docker plugin and set a few default values. The `drone-ecr` plugin definitely needs to be a separate thing because aws doesn't use standard docker login, so we need to make a few AWS API calls before invoking docker login.

I'll probably test it out with gcr first, which may end up being just a simple bash script wrapper. We'll see though. I'm definitely open to ecr.

**Comment by sl1pm4t** [comment]
I need the google-cloudstorage plugin, so I'm having a go at porting it to 0.5
Progress is over [here](github.com/sl1pm4t/drone-google-cloudstorage).

**Comment by tboerger** [comment]
So this is our final list of official 0.5 plugins:

* [ ] drone-coverage
* [ ] drone-docker
* [ ] drone-downstream
* [ ] drone-email
* [ ] drone-gcr
* [ ] drone-gh-pages
* [ ] drone-git
* [ ] drone-git-push
* [ ] drone-github-release
* [ ] drone-gitter
* [ ] drone-google-cloudstorage
* [ ] drone-hg
* [ ] drone-npm
* [ ] drone-rsync
* [ ] drone-s3
* [ ] drone-s3-sync
* [ ] drone-sftp-cache
* [ ] drone-slack
* [ ] drone-ssh
* [ ] drone-webhook

**Comment by tboerger** [comment]
Just to clarify, the other remaining plugins are intended to be moved to the community, just the list mentioned one comment above will be maintainer by the drone-plugins organization.

**Comment by tonglil** [comment]
Is there any instructions on what it takes to migration/upgrade a plugin from 0.4 to 0.5?

Specifically major changes that need to be done? I have a custom (soon to be open sourced) Drone 0.4 Kubernetes plugin that is written (fortunately or not) with https://github.com/drone/drone-plugin-go.

**Comment by donny-dont** [comment]
@tonglil no nothing really. If you look at the list above you'll see pull requests that update to 0.5. Its pretty painless for the most part. If you have any particular questions you can ask on gitter.

**Comment by tboerger** [comment]
https://github.com/drone/drone-plugin-starter that is a pretty good start, it's the blueprint for new 0.5 plugins

**Comment by appleboy** [comment]
I write some [notification plugin](http://readme.drone.io/0.5/usage/notifications/) like [facebook](https://developers.facebook.com/docs/messenger-platform), gtalk and [line](https://developers.line.me/messaging-api/overview) for drone `0.5` version.

* [x] [drone-line](https://github.com/appleboy/drone-line)
* [x] [drone-facebook](https://github.com/appleboy/drone-facebook)
* [x] [drone-gtalk](https://github.com/appleboy/drone-gtalk)

**Comment by bradrydzewski** [comment]
@appleboy that is awesome. Hopefully we can have a plugin registry soon so that we can show them off to everyone!

**Comment by appleboy** [comment]
@bradrydzewski Awesome. I am looking forward to the plugin registry.

**Comment by appleboy** [comment]
Another two plugin as following for drone `0.5` version:

* [x] [drone-jenkins](https://github.com/appleboy/drone-jenkins) Drone plugin for trigger Jenkins jobs.
* [x] [drone-scp](https://github.com/appleboy/drone-scp) Drone plugin to copy files and artifacts via SSH.

**Comment by bradrydzewski** [comment]
I think we can close this, but if not, lets move to discourse

**Comment by tboerger** [comment]
Yeah it's fine to close it
