### ISSUE TITLE
Introduce a mechanism to limit a build containers resources

### ISSUE THREAD

**Issue by Crafter6432** [drone/drone#1681]
It would be nice to have an option to limit the amount of running builds and to be able to set a maximum of resources for each container in order to avoid the whole system crashing if someone runs a forkbomb or anything else that consumes to much resources.

**Comment by bradrydzewski** [comment]
you can limit container resources in the yaml using the following fields:

```
memswap_limit
mem_limit
cpu_quota
cpu_shares
cpuset
```

**Comment by Crafter6432** [comment]
But that doesn't protect me against malicious commands with the objective to crash my system as someone who will run these would obviously remove resource limits in .drone.yml

**Comment by tboerger** [comment]
> But that doesn't protect me against malicious commands with the objective to crash my system as someone who will run these would obviously remove resource limits in .drone.yml

If you are using the `.drone.yml` signing it will protect you.

**Comment by wrouesnel** [comment]
The other side of this is that it would would be nice to add resource allowances to user accounts that would control how many builds can execute simultaneously.

**Comment by AlekseyMartynov** [comment]
Also please consider supporting Docker's new `pids-limit` option. For public repos it's very important to guard against malicious PRs trying to run fork bombs 💣

**Comment by edouardkleinhans** [comment]
Any news on this topic ?

**Comment by aisensiy** [comment]
BTW is it possible to limit the disk size?

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone/pull/2085
