### ISSUE TITLE
status badges do not update b/c cache-control is not set to none

### ISSUE THREAD

**Issue by ctb** [drone/drone#1687]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [ ] I am not using the issue tracker to ask why my build failed

The drone badge from [our project's README](https://github.com/spacegraphcats/spacegraphcats) is not updating properly.

Oddly, I can't seem to do 'curl -I' on the the badge URL to see what the headers are ??(https://drone.io/github.com/spacegraphcats/spacegraphcats/status.png) - it returns 404 -- but in any case this may be something that can be fixed by setting cache-control to None in the HTTP headers.
See https://github.com/github/markup/issues/224 for more.

**Comment by tboerger** [comment]
Please contact the drone.io support, this issue tracker handles only the opensource version of drone and not the hosted service.
