### ISSUE TITLE
Drone build page display empty build log on IE 11

### ISSUE THREAD

**Issue by fracting** [drone/drone#1689]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [ y] I have searched for existing issues
- [ n] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ n] I have provided a sample `.drone.yml` file to help the team reproduce
- [ n] I have provided details from the build logs
- [ n] I have provided details from the server logs by running `docker logs drone`
- [ y] I am not using the issue tracker to ask why my build failed

Hi, this is reported by @mkae in https://github.com/TeaCI/tea-ci/issues/9

I've reproduce the same problem with upstream Drone 0.4.2.

On Windows 10 + Internet Explorer 11, drone build pages always show empty log, while other browser like Firefox/Chrome works fine.

Here is a screenshot:

![drone-empty](https://cloud.githubusercontent.com/assets/194342/16343775/a957392e-3a6b-11e6-9edc-57522c48f117.png)

Here is an exception show in debug console:

![drone-empty-debug](https://cloud.githubusercontent.com/assets/194342/16343790/bff1db62-3a6b-11e6-87bf-7f4e53b97f69.png)

Could someone have a look if it is a browser bug or Drone UI bug?

Thank you!

**Comment by bradrydzewski** [comment]
0.4.2 is frozen with 0.5 now in master. We are working on a new set of designs for 0.5 and this issue is unlikely to get fixed / backported.
