### ISSUE TITLE
Support drone CLI with the new Docker for Windows

### ISSUE THREAD

**Issue by jhasse** [drone/drone#1691]
The new Docker for Windows now comes with Hyper-V support and runs in cmd / PowerShell instead of bash. See https://download.docker.com/win/beta/InstallDocker.msi

Running drone exec in cmd.exe with Docker running in the background (`docker run hello-world` works), gives me:

```
> drone exec

[DRONE] starting job #1
INFO[0000] Pulling image drone/drone-exec:latest
ERRO[0000] Error pulling drone/drone-exec:latest. Post http://unix.sock/v1.15/images/create?fromImage=drone%2Fdrone-exec%3Alatest: dial unix /var/run/docker.sock: socket: Es wurde eine Adresse verwendet, die mit dem angeforderten Protokoll nicht kompatibel ist.

Post http://unix.sock/v1.15/images/create?fromImage=drone%2Fdrone-exec%3Alatest: dial unix /var/run/docker.sock: socket: Es wurde eine Adresse verwendet, die mit dem angeforderten Protokoll nicht kompatibel ist.
```

Sorry for the German error messages, I have no idea how to fix that easily on Windows.

**Comment by bradrydzewski** [comment]
@jhasse did you set `DOCKER_HOST`, `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH` environment variables to use the correct location of your docker daemon on windows? The error message seems to indicate this is not the case, and is therefore falling back to the default unix address.

Please feel free to use the [gitter room](https://gitter.im/drone/drone) for questions or help troublehsooting and we can always follow up with a GitHub issue if needed.
