### ISSUE TITLE
Headers were already written message in logs

### ISSUE THREAD

**Issue by vespakoen** [drone/drone#1695]
Error handling has some issues, in stead of getting an error message, all we get is:

```
drone_1         | [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
drone_1         | http: response.Write on hijacked connection
```

I wish I could fix it but my knowledge of go is very lacking, so just reporting it

**Comment by bradrydzewski** [comment]
the fix has been merged to master and is available in the drone:0.5 docker image
