### ISSUE TITLE
Bitbucket login failed

### ISSUE THREAD

**Issue by antonypp** [drone/drone#1705]
dronerc
```
I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION=true
I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS=true
DRONE_AGENT_SECRET=<key>

DRONE_OPEN=true

DRONE_BITBUCKET=true
DRONE_BITBUCKET_CLIENT=<key>
DRONE_BITBUCKET_SECRET=<key>
```

`time="2016-07-09T10:52:22Z" level=error msg="cannot authenticate user. Post https://bitbucket.org/site/oauth2/access_token: x509: failed to load system roots and no roots provided"`

**Comment by tboerger** [comment]
You know what those environment variables mean? Beside that you have not read the issue template where you have been asked some questions.

**Comment by tboerger** [comment]
This issue tracker is for confirmed bugs, if you encounter issues it's most of the time easier to solve via the support chat at Gitter.

**Comment by antonypp** [comment]
found a temporary solution
` docker run --volume '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'`
this use system certificates

**Comment by antonypp** [comment]
@bradrydzewski This is a temporary solution to the problem is not solved, I think that the problem in "centurylink/ca-certs" drone image build him, and all certificates must be inside drone image

**Comment by bradrydzewski** [comment]
@antonypp I'm unable to repeat the issue on my computer or on my digital ocean server. I'm also unaware of any of our bitbucket users having this issue. Is there something about your host machine network settings that are perhaps different than most users? corporate proxy server? If so, it makes perfect sense that you have to mount your own certs if you need a custom cert pool
