### ISSUE TITLE
Menu popup window leaves traces of itself on second click

### ISSUE THREAD

**Issue by strk** [drone/drone#1711]
To reproduce, on Firefox 47.0 for Linux:

 1. Go to project page as an authenticated user
 2. Click on the 3 vertical dots on the upper-right corner (a menu pops up)
 3. Click again on the same 3 vertical dots (the menu text disappears but the border remains)

Here's a screenshot of the leftover:
![screenshot-drone-menu-leftover](https://cloud.githubusercontent.com/assets/289678/16775438/e1333160-4860-11e6-8f75-cb1f528c98f2.png)

This happens as of commit 35e54354004d067ae0bc586d74a68cb7f7e659fd

**Comment by bradrydzewski** [comment]
UI issues should go to https://github.com/drone/drone-ui ... although in this case I question whether this is an issue with drone or with the getmdl.io library, since I'm unable to repeat on latest Firefox on OSX, which would point to either a browser rendering bug or library bug
