### ISSUE TITLE
Drone demands read/write GitHub permissions where it should only need read only

### ISSUE THREAD

**Issue by mikedlr** [drone/drone#1712]
When I sign up for drone.io with my github account it requests read/write access to the account details and to private respositories.  

I understand why drone needs to have read access to both of those values in some circumstances.  I don't see why it should want to have write access and I think that access to private respositories should be optional.  

In my understanding, if the permissions are left as is
- bugs in drone may damage users repositories accidentally
- drone getting hacked my compromise all of the github accounts linked to drone.  

Please reduce the privileges requested to the minimum needed or at most those planned to be used in the near future.

**Comment by bradrydzewski** [comment]
this is not the drone.io issue tracker. drone.io is a separate project / codebase and this is dedicated to the open source codebase.
