### ISSUE TITLE
Where is the issue tracker for drone.io?

### ISSUE THREAD

**Issue by anacrolix** [drone/drone#1714]

**Comment by tboerger** [comment]
There is uservoice and the support email. This issue tracker is only for the open-source version of drone.

**Comment by bradrydzewski** [comment]
@anacrolix you can submit issues or feedback to https://drone.uservoice.com/forums/176976-feedback-for-drone-io

this repository is dedicated to the open source version of drone, which is a re-write of the drone service to deeply integrate with docker. This version will eventually replace the legacy codebase powering drone.io once we reach a more stable release, hopefully end of summer.
