### ISSUE TITLE
drone.io Go build is out of date

### ISSUE THREAD

**Issue by anacrolix** [drone/drone#1715]
Go 1.6.2 or 1.7 is preferred, current drone.io only has 1.4.

**Comment by bradrydzewski** [comment]
the open source codebase is powered by docker containers, allowing you to use any image from the registry for your build environment, including the latest `go:1.7rc1` image.

this feature is not yet available in drone.io, which is a separate legacy codebase. There are plans to upgrade drone.io to use this open source codebase once we reach a stable release.

**Comment by bradrydzewski** [comment]
@anacrolix also forgot to add, if you want beta access to the new version of drone let me know. It is unlikely the legacy version will get updated in the short term as we focus instead on the complete upgrade. But I'm happy to get you setup on the new version.

**Comment by anacrolix** [comment]
That would be appreciated @bradrydzewski , I'll give it a try.
