### ISSUE TITLE
drone client is not honouring/using http(s)_proxy settings

### ISSUE THREAD

**Issue by rbuckland** [drone/drone#1723]
When using the drone client and server in a corporate environment, sometimes you may be separated by a proxy server. 

The proxy would be available via the standard environment variables

```
✔ rbuckland:some-project [ ubuntu ✭ | ● 4 ✚ 2 ] ➭ env | grep -i proxy 
http_proxy=http://localhost:3128
HTTPS_PROXY=http://localhost:3128
https_proxy=http://localhost:3128
HTTP_PROXY=http://localhost:3128
```
(in this simple case - localhost:3128 is a locally running proxy server)

When running drone secure 

```
    drone secure --repo myuser/some-project --in .drone.sec.yml
```

it will fail with 

```
Get http://drone-server-behind-proxy-server.foo:31100/api/repos/myuser/some-project/key: dial tcp: lookup drone-server-behind-proxy-server.foo on 10.33.44.55: no such host
```

In this case, 10.33.44.55 will be my locally assigned DNS server (cat /etc/resolv.conf) which cannot resolve drone-server-behind-proxy-server.foo

When proxy settings are detected, no DNS resolution should be performed, rather the request(s) should be handed straight to the proxy server in question.

**Comment by bradrydzewski** [comment]
the default Go `http.RoundTripper` reads these proxy variables, however, drone overrides the client `http.RoundTripper` to load the system cert pool (for corporate networks that don't use cert authorities). I've merged a patch that adds the proxy variables to our custom `RoundTripper` to match the default Go http client. See https://github.com/drone/drone/pull/1724

```diff
 		if trans, ok := auther.Transport.(*oauth2.Transport); ok {
-			trans.Base = &http.Transport{TLSClientConfig: c}		 
+			trans.Base = &http.Transport{
+				TLSClientConfig: c,
+				Proxy: http.ProxyFromEnvironment,
+			}
  		}
```

**Comment by rbuckland** [comment]
I have backported this patch to v0.4.2 on my fork here https://github.com/rbuckland/drone-cli/tree/backport1724
