### ISSUE TITLE
Help Debug why secrets don't work

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1727]
With 0.5 secrets are a bit more complex than prior versions and I propose we provide some utilities to help individuals understand how they work and debug. Sort of a like a sql explain plan, I propose a `drone secret explain` command.

The command could look like this:

```
$ drone secrets explain drone/drone
$ drone secrets explain --pull_request drone/drone # for pull request
$ drone secrets explain --pull_request --context=path/to/.drone.yml drone/drone
```

Example output could look like this:

```
$ drone secrets explain --pull_request drone/drone

secret: MY_SECRET
image "gynzy/docker-drone-node:*" does not match "gynzy/docker-drone-node"

secret: HEROKU_TOKEN
image "plugins/heroku:*" matches "plugins/heroku:latest"
event [tag, push] does not match pull_request

secret: AWS_KEY
image "plugins/s3" matches "plugins/s3"
event [pull_request, push] matches pull_request
```

It is also possible that we could run the explain plan on the Yaml parsing and compiling itself to show how it is transformed. This might be even more helpful but will be way more difficult and involved.

**Comment by appleboy** [comment]
Nice command. 👍

**Comment by bradrydzewski** [comment]
until we have this command available, common reasons for secrets not being injected are

### Image mismatch

When you add a secret you need to provide a list docker image(s) that the secret can be exposed to. The list of images must be an exact match to what is in your yaml, or must use matching logic.

Let's use this yaml as an example:

```
pipeline:
  publish:
    image: plugins/docker
```

These command __will__ expose secrets:

```
drone secret add --image plugins/docker DOCKER_USERNAME octocat
drone secret add --image plugins/* DOCKER_USERNAME octocat
```

These commands __will not__ expose secrets:

```
drone secret add --image docker DOCKER_USERNAME octocat # missing plugins/ prefix
drone secret add --image publish DOCKER_USERNAME octocat # publish is the step name, not the image name
```

Note that if you are using tags in the image name, they need to be taken into account when you specify the `--image` flag

```
pipeline:
  publish:
    image: plugins/docker:latest
```

These commands __will__ expose secrets

```
drone secret add --image plugins/docker:latest DOCKER_USERNAME octocat
drone secret add --image plugins/docker:* DOCKER_USERNAME octocat
```

### Pull Requests

For security reasons Drone will not expose secrets for pull request events. If you want secrets exposed to pull requests it needs to be enabled when adding the secret:

```
drone secret add --event pull_request --image plugins/docker:latest ...
```

### Invalid or Missing Signature

For security reasons, Drone will not expose secrets unless the yaml is signed and that signature matches the contents of the yaml. If the yaml file changes, the signature needs to be updated.

If you don't have a `.drone.yml.sig` file secrets will not work. Please read the full documentation which explains how to sign your yaml file.

If you have a `.drone.yml.sig` but the signature is invalid, you will see a warning message above your build logs. You will need to re-sign the yaml and push the updated signature file

**Comment by naveensrinivasan** [comment]
Thanks, here is a sample file https://github.com/naveensrinivasan/drone-test/blob/master/.drone.yml

Here is the output for my global secrets
```
GuessWho➜  drone : master ✔ : ᐅ  k8s:(gke_revature-tools_us-west1-a_drone) drone global secret add --image 'busybox:*' --event pull_request --skip-verify   PASSWORD octocat
GuessWho➜  drone : master ✔ : ᐅ  k8s:(gke_revature-tools_us-west1-a_drone) drone global secret ls
PASSWORD
Images: busybox:*
Events: push, tag, deployment, pull_request
SkipVerify: true
Conceal: false
```
And I am still not getting output for `$PASSWORD`


Here is the output from the build 
```
+ printenv
DRONE_BRANCH=master
DRONE_COMMIT_AUTHOR_AVATAR=https://avatars.githubusercontent.com/u/172697?v=3
DRONE_JOB_FINISHED=0
CI=drone
DRONE_VERSION=0.5.0+822
HOSTNAME=313f640c0d30
DRONE_REPO_LINK=https://github.com/naveensrinivasan/drone-test
DRONE_COMMIT_AUTHOR=naveensrinivasan
DRONE_PREV_BUILD_NUMBER=1
SHLVL=2
HOME=/root
DRONE_COMMIT_BRANCH=master
DRONE_REPO_PRIVATE=false
DRONE_REPO_SCM=git
DRONE_BUILD_STATUS=success
DRONE_ARCH=linux/amd64
DRONE_PREV_COMMIT_SHA=845273d06c7640a98f116790975416cd16e2d5a4
DRONE_COMMIT_MESSAGE=Testing Build
DRONE_REPO_BRANCH=master
DRONE_YAML_VERIFIED=false
DRONE_REMOTE_URL=https://github.com/naveensrinivasan/drone-test.git
DRONE_JOB_STATUS=running
DRONE_REPO_OWNER=naveensrinivasan
DRONE=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DRONE_BUILD_NUMBER=2
DRONE_BUILD_STARTED=0
DRONE_REPO_TRUSTED=true
DRONE_BUILD_LINK=http://drone.revatureengineering.com/naveensrinivasan/drone-test/2
DRONE_YAML_SIGNED=false
DRONE_COMMIT=0290214e5cc2747ab99dde6ebfb3e1832723b439
SHELL=/bin/sh
DRONE_JOB_NUMBER=1
DRONE_JOB_STARTED=1482715517
DRONE_BUILD_EVENT=push
DRONE_REPO_NAME=drone-test
DRONE_BUILD_CREATED=1482715387
DRONE_COMMIT_SHA=0290214e5cc2747ab99dde6ebfb3e1832723b439
DRONE_COMMIT_AUTHOR_EMAIL=nsrinivasan1976@gmail.com
DRONE_JOB_EXIT_CODE=0
DRONE_COMMIT_REF=refs/heads/master
DRONE_REPO_AVATAR=https://avatars.githubusercontent.com/u/172697?v=3
DRONE_PREV_BUILD_STATUS=failure
PWD=/drone/src/github.com/naveensrinivasan/drone-test
DRONE_COMMIT_LINK=https://github.com/naveensrinivasan/drone-test/commit/0290214e5cc2747ab99dde6ebfb3e1832723b439
DRONE_BUILD_FINISHED=0
DRONE_REPO=naveensrinivasan/drone-test
+ echo $PASSWORD
```

Please let me know how I could add secrets. I have tried following command and none of them have solved my issue

1.  `drone global secret add --image 'busybox:*' --event pull_request --skip-verify   PASSWORD octocat` 
2. `drone global secret add --image 'plugins/busybox:*' --event pull_request --skip-verify   PASSWORD octocat` 
3. `drone global secret add --image 'docker/busybox:*' --event pull_request --skip-verify   PASSWORD octocat`

**Comment by bradrydzewski** [comment]
Based on the CLI output, `busybox:*` will not match `busybox` in you yaml

**Comment by bradrydzewski** [comment]
closing since secret impl changes to interpolate using `${variable}`. This, combined with the error message regarding lack of signature, should suffice.
