### ISSUE TITLE
Proposal: Trigger a new build with build parameters

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1733]
## Abstract

A proposal for implementing a new API endpoint for triggering new builds with custom build parameters, that is required for more flexible pipelines.

Related existing issues:
- #1614 Pass build environment via the webhook
- #894 Allow environment variables to be set on build basis + ondemand builds

## Motivation

Currently, drone jobs work around a single git repository. Builds are triggered by different Github, gitlab, etc events via webhooks. This functionality probably covers the majority of use cases. However, there is no simple way to chain jobs, i.e. jobA ---> triggers ---> jobB ---> triggers ---> jobC.

### Use case 1

Ability to trigger a downstream job to do a deployment after a successful code build

There two git repositories:
- `repoA` - contains application code and tests
- `repoB` - contains kubernetes deployment files

A developer pushes a new commit or a tag to repoA, github triggers a drone build which runs a configured pipeline, builds a docker image, pushes it to a docker registry. The image is tagged with git sha and is ready for deployment.

There next logical step is to trigger a `repoB` master branch (or specific git tag/sha) and pass a custom build parameter `APP_IMAGE_TAG: 579e3ea`. Drone kicks off a new build of `repoB:master`, which deploys `repoA` docker image with `${APP_IMAGE_TAG}` to kubernetes.

Then, we also need an ability to trigger a job to do a deployment of a service. Application code does not necessarily have to be changed to trigger a deployment. Each application has environment-aware configuration, for example kubernetes manifests which describe how a particular application needs to be deployed and what configuration it requires.

An application can consists of multiple containers, i.e. kubernetes pods. A change to each of those components need to trigger a deployment, if we decouple application code from the deployment code, then a change to configuration or individual component code is able to trigger `repoB` to kick of a deployment.

## High Level Design

Add a new API endpoint `/api/repos/:owner/:name`. This endpoint accepts `POST` with `Content-Type: application/json`. A new post handler function will have to be added to handle the request.

POST data example:
```
{
  "build_parameters": {
    "DOCKER_IMAGE_TAG": "v0.0.1",
    "ENVIRONMENT": "production",
  },
  "tag": "v1",
  "branch": "master",
  "revision": "579e3eabb9b40709051f1da87e8f5e787e71aada"
}
```
All above parameters are optional and can be omitted. By default HEAD of default branch will be checked out. `build_parameters` will then be injected in to a build as environment variables.

## Additional work

Originally, @bradrydzewski suggested to add custom build parameters support to an existing API endpoint `/api/repos/:owner/:name/builds/:number` for restarting old jobs with added custom build parameters. The scope of this proposal covers that too.

Drone git plugin (https://github.com/drone-plugins/drone-git) will have to slightly changed. The plugin needs to default to HEAD of a default branch if revision is unspecified.

## Unknowns

Potentially, add a new event type?

**Comment by bradrydzewski** [comment]
> Ability to trigger a downstream job to do a deployment after a successful code build

this can be done today with the existing endpoint. You can see an example in the [downstream](https://github.com/drone-plugins/drone-downstream) plugin

> There next logical step is to trigger a repoB master branch (or specific git tag/sha) and pass a custom build parameter APP_IMAGE_TAG: 579e3ea. Drone kicks off a new build of repoB:master, which deploys repoA docker image with ${APP_IMAGE_TAG} to kubernetes.

This can already be done with the `drone build fork`. If drone is enabled for repository B then drone will __already__ have an existing entry for the commit sha in the drone database. Therefore we can use the `drone build fork` command to, for example, to re-build the existing entry with a new build number.

In the event that hooks are disabled for these repositories, and there is no entry in the database, the `/hook` endpoint should be used instead. The hook endpoint gives individuals broad flexibility to trigger a build with full control over the data in the hook payload.

> Then, we also need an ability to trigger a job to do a deployment of a service. Application code does not necessarily have to be changed to trigger a deployment. Each application has environment-aware configuration, for example kubernetes manifests which describe how a particular application needs to be deployed and what configuration it requires.

This already exists using the `drone deploy` command. You can use `drone deploy 55 production` to, for example, deploy build number 55 to production. This is similar to the fork command, in that it creates a new build entry in the database, but also sets the event type to `deployment`. This allows you to conditionally execute steps based on the the deployment type and target environment:

```
pipeline:
  ...
  deploy:
    ...
    when:
      event: deployment
      environment: production
```

I believe these existing capabilities satisfy the use cases mentioned above. In the event we still need to pass additional parameters at runtime (such as environment variables) I recommend augmenting the existing capabilities https://github.com/drone/drone/issues/894#issuecomment-233707244

**Comment by vaijab** [comment]
@bradrydzewski downstream plugin allows to kick off an existing build. I don't think that developers should have a mental map between drone build numbers and say git tags.

`drone build fork` again, works around an existing build.

`drone deploy` works with existing builds.

In case of drone database corruption or data loss, above solutions will fail, because build numbers will no longer represent git tags or branches I want to deploy.

**Comment by bradrydzewski** [comment]
This proposal has come up at least 3 times in the past and has not been accepted because upon further discussion we've found the existing capabilities work for the majority of real world situations, with `/hook` as a fallback.

Have you used these existing capabilities yet? Perhaps it instead makes sense to use them in a production setting and providing feedback based on real world usage pain points that you and your team have experienced.

> downstream plugin allows to kick off an existing build. I don't think that developers should have a mental map between drone build numbers and say git tags.

> drone build fork again, works around an existing build.

why won't be the build be in the database?

> drone deploy works with existing builds.

why won't the build be in the database?

> In case of drone database corruption or data loss, above solutions will fail, because build numbers will no longer represent git tags or branches I want to deploy.

This should be solved at the database level. We recommend running your database with regular backups and possibly configured with replication. In the event of data loss a GitHub post-commit hook could be re-triggered to re-sync the database.

**Comment by jon-shanks** [comment]
Hi, this looks useful. I'm not sure i follow the ins and outs of how it is possible by you @bradrydzewski 

The concerns are separate for most people, building and testing vs deploying. Deployments could be anywhere via anything i.e. heroku vs kubernetes vs whatever else. Knowing what versions of things you are deploying is necessary but to know that you need to know what was built. We wouldn't want the deployment files to live with code, because the code doesn't care about the deployment but you need that data of the version you want to deploy.

The workable scenario would be:

[code] -> [tests] -> [integrations] -> [build image] -> [push image]

at this point, the artifact is produced, maybe also you push to artifactory or nexus or whatever else, maybe you also push up some code coverage information to something else or reports on some tests to s3 to be consume by something else etc. 

[docker repo webhook] -> [drone] -> [github checkout for deployment] -> [deploy]

or maybe you decide that someone wants to deploy a specific version into a specific environment, maybe preview or demo or whatever else. We might want to say, actually version 0.1.0-alpha1+64baec2  is the version with the latest changes i want to preview, so i will trigger that build with that version to deploy it to then review or whatever else. This could be done via slack, or chatops, or however you wanted to do it.

**Comment by bradrydzewski** [comment]
> We wouldn't want the deployment files to live with code, because the code doesn't care about the deployment but you need that data of the version you want to deploy.

there is no requirement that you have to deploy live code. You can use the `drone deploy` function to re-trigger a pipeline execution (maybe that is a better term than build) that deploys existing code that is already compiled, or an existing image.

for example:

```yaml
pipeline:
  # build the code
  # skip this step if event type is deployment
  build:
    image: golang
    commands:
      - go build 
      - go test
    when:
      event:
        exclude: [ deployment ]

  # publish the image to docker registry
  # skip this step if event type is deployment
  publish:
    repo: foo/bar
    tags: [ latest, ${DRONE_COMMIT} ]
    when:
      event:
        exclude: [ deployment ]

  # deploy the image to production
  # only execute during deployment
  deploy:
    image: python
    commands:
     # run some python deploy script that deploys the existing image
     - ./deploy.py 
    when:
      event: deployment
      environment: production
```

I believe everything you are requesting is possible with drone as-is today. Much of this functionality is new, including the `drone deploy` functionality which was added at the tail end of the 0.4 and not well documented.

**Comment by jon-shanks** [comment]
@bradrydzewski that's great. Is it possible then for me to trigger a build using build deploy of a specific version using drone? I might not want to deploy what was just built, but a specific version of something that was built at some point in time to some environment. This could be programmatic but also maybe manual i.e. deploy version 5 into QA for some manual QA analysis on that product?

**Comment by bradrydzewski** [comment]
@jon-shanks yes, you can use `drone deploy {environment} {build number}` where `{build number}` represents a build in drone mapping to an individual commit sha and ref. You can use the latest build or any historical build.

The catch is that you have to know the build number that corresponds to the commit or tag or whatever that you want to deploy, but the Drone API has all of this data to make a lookup possible. We could certainly discuss making this more user friendly without adding major new functionality to drone.

This is a somewhat messy example to demonstrate that it is possible to trigger a deployment for a specific commit by commit sha:

```sh
drone build list drone/drone --format="{{ .Number }} {{ .Commit }}" \
    | grep "b675867967586e34e86b387434e0d5aac8c2bdf1" \
    | cut -d' ' -f1 \
    | xargs -I{} drone deploy drone/drone production {}
```

or by tag:

```sh
drone build list drone/drone --format="{{ .Number }} {{ .Ref }}" \
    | grep "refs/tags/v1.3.4" \
    | cut -d' ' -f1 \
    | xargs -I{} drone deploy production drone/drone {}
```

**Comment by jon-shanks** [comment]
@bradrydzewski i'm still confused here , sorry. This looks like it is deploying from the same repo, but i dont want to, i want to trigger a build on another repo? are you saying that i can do it like this?

**Comment by vaijab** [comment]
@bradrydzewski I think to achieve what we're proposing here without adding a lot of new functionality to drone, we need to add custom build parameters support to `/hook` endpoint. Would you be up for that?

**Comment by bradrydzewski** [comment]
> I think to achieve what we're proposing here without adding a lot of new functionality to drone, we need to add custom build parameters support to /hook endpoint. Would you be up for that?

I'm open to adding parameters to both the `/hook` endpoint similar to what was discussed in https://github.com/drone/drone/issues/894#issuecomment-233707244. I think we first need a documented use case describing how it will be used and why this is necessary. Specifically why is the fork / re-build endpoint inadequate? If the sole reason is a possible database failure, I'm probably not open to the PR

**Comment by vaijab** [comment]
@bradrydzewski cool, no worries. As promised I am going to do a PR to implement suggested feature in https://github.com/drone/drone/issues/894#issuecomment-233707244

I will try to achieve what we described in the proposal using current drone features. Thanks!

**Comment by jon-shanks** [comment]
@bradrydzewski . I feel we have given our use case. We want to define our own ways of working, what you have provided is a very specific solution to do what we want and it still doesn't meet our needs. We would like the flexibility of having an API to achieve our own workflow around drone product, we don't really want to be pulling data from one api call and then pushing data to another api call in some adhoc way to retrigger another job as that isn't particularly clean. 

The example is, we want to leverage https://docs.docker.com/docker-hub/webhooks/ which we have no control over. When the payload gets sent we want to send specific data to drone. We could in theory extrapolate data from drone and then prepare the webhook, then change the webhook to then post data to the api to trigger the build? but not sure if that would work or not? But also seems quite convoluted and not particularly flexible. I think the most sense here is to allow people to work in a way they want to by allowing some flexibility on how jobs build. Right now that isn't there.

**Comment by bradrydzewski** [comment]
> I feel we have given our use case

this is the first time dockerhub has come up. I feel like it is very fair to ask for a specific use case so I understand the exact problem we are solving before proposing solutions.

> We want to define our own ways of working, what you have provided is a very specific solution to do what we want and it still doesn't meet our needs.

we want to work within the boundaries of drone when possible

> The example is, we want to leverage https://docs.docker.com/docker-hub/webhooks/ which we have no control over. 

If this is the intended use case then I don't understand how this proposal solves the problem. The json format proposed in the abstract does not match what is sent by DockerHub.

> We could in theory extrapolate data from drone and then prepare the webhook, then change the webhook to then post data to the api to trigger the build

Per the abstract and json format defined above this would still be required.

> I think the most sense here is to allow people to work in a way they want to by allowing some flexibility on how jobs build. Right now that isn't there.

Having a small service that sits between the source webhook and target drone seems to achieve this goal.

__In conclusion__ I do not believe this proposal is going to meet the defined DockerHub use case. It is also unlikely that drone will build support for individual payload types (ie DockerHub) directly into the Drone server. Drone has always promoted external plugins and services for such things and will continue to do so.

I believe there are still alternative approaches that can be explored, such as a custom plugin, although "we want to define our own ways of working" seems to indicate a lack of appetite for such suggestions. If you change your mind and are open to exploring native-Drone solutions please let me know.

**Comment by airtonix** [comment]
@jon-shanks @vaijab  http://concourse.ci will do exactly what you want and more... unfortunately, it just doesn't have a gui like drone does.
