### ISSUE TITLE
Bitbucket server docs are not entirely clear

### ISSUE THREAD

**Issue by bobrik** [drone/drone#1734]
It may as well be Atlassian's fault that they made the process so unnecessary complex, but at this point it's very hard to understand how to configure bitbucket server to work with drone.

* http://readme.drone.io/0.5/installation/services/bitbucet_server/ (note `bitbucet` too)

I managed to get to the following screen:

![image](https://cloud.githubusercontent.com/assets/89186/17145136/040f68c0-5351-11e6-890f-0ec08ac456a5.png)

And it's not clear how to generate the keys and what URLs to use. Step by step guide for making it work would be great.

cc @josmo

**Comment by bradrydzewski** [comment]
please open a PR with [github.com/drone/docs](https://github.com/drone/docs)

**Comment by bradrydzewski** [comment]
(the community members that maintain the docs subscribe to the docs repository, so that is the best way to bring this to their attention)
