### ISSUE TITLE
Add cancel handler

### ISSUE THREAD

**Issue by mhagen-vmware** [drone/drone#1741]
When a job is cancelled, we need the ability to cleanup test resources outside of the drone worker container.  Having a on terminate block in the yml file or something like this would be great:

cancel:
    - ./cleanup-scripts.sh

build:
.
.
.

notify:
.
.
.

**Comment by bradrydzewski** [comment]
This is already possible in the upcoming 0.5 release. See http://readme.drone.io/0.5/usage/overview/#constraints:68f80267fa3a50980dbb745a782b8dca

**Comment by mhagen-vmware** [comment]
@bradrydzewski I am not seeing in that link, how you handle when the drone job is cancelled by someone pressing the Cancel button from the web ui? It looks like that just covers when a build step fails?

**Comment by bradrydzewski** [comment]
You can specify a step should execute based on status. So you can do something like this

```
pipeline:
  step:
    ...
    when:
      status: [ killed, failure ]

**Comment by mhagen-vmware** [comment]
Awesome, thanks!

**Comment by djmaze** [comment]
This doesn't work for me. My cleanup step has:

```
when:
  status: [ success, killed, failure ]
```

When clicking the Cancel button, Drone shows `ERROR: termination request received, build cancelled`, but the cleanup step is never run. 

This is using the current `drone/drone:0.5` image from the Hub.

**Comment by clarktlaugh** [comment]
I was trying to figure out if this is still expected to work... can we use "killed" for a "when"?
