### ISSUE TITLE
Implement DRONE_COMMIT_MESSAGE env variable

### ISSUE THREAD

**Issue by mhagen-vmware** [drone/drone#1742]
It looks like it is partially implemented here:
drone/agent.go:
253		"DRONE_COMMIT_MESSAGE":       w.Build.Message,

But I couldn't get it to work - it was just an empty string, and it is not listed in the documentation here:
http://readme.drone.io/usage/variables/

We need this in order to pass build directives into the jobs other than just [skip ci]

**Comment by bradrydzewski** [comment]
This is implemented in the upcoming 0.5 release. See http://readme.drone.io/0.5/usage/environment/
