### ISSUE TITLE
Error: dial tcp: missing address

### ISSUE THREAD

**Issue by kushtrimjunuzi** [drone/drone#1743]
I tried to add drone secret env and nothing happens and is not injecting at sftp_cache container or golang container, also I tried to add server flag at sftp_cache section and still nothing same error. Running plugins/sftp-cache as separate docker run is working as expected but not in drone.

drone secret add --image=plugins/sftp-cache foo/bar SFTP_CACHE_SERVER 10.0.3.2:2223

.drone.yml
pipeline:
sftp_cache:
restore: true
username: foo
mount: [ node_modules, .git ]
build:
image: "golang:1.7rc3"
commands:
- "go get ./..."
- "go build"
- "env"

Drone version is v0.5 or docker image id 5aec71743dd1, also drone cli is latest from master branch compiled today.
Thanks.

**Comment by bradrydzewski** [comment]
Please use the gitter to triage the issue per the issue template. We can reopen once confirmed
