### ISSUE TITLE
drone/stream

### ISSUE THREAD

**Issue by djherbis** [drone/drone#1745]
@bradrydzewski 

I noticed you moved away from https://github.com/djherbis/fscache in
https://github.com/drone/drone/commit/34c3c92ec3f3f8cd58a7eef5960f6fc071a4dd20#diff-dccdced0b28e643d2e310f7cbc6d0e07L7

It looks like the code is largely derived from my project (mainly https://github.com/djherbis/stream), any reason to the discontinuation?

**Comment by bradrydzewski** [comment]
the fscache library was used as a temporary solution until our message broker / queue was complete, which is able to handle the project's streaming needs https://github.com/drone/mq

I do remember running into some issues with the fscache package and it not quite being able to integrate with drone reliably, at which point I just hacked something together. I think it was more of an issue with how drone was trying to use fscache, than an issue with the package itself, however it was so long ago I can't even really remember what drove that decision.

Sorry, wish I could provide more feedback :(
