### ISSUE TITLE
Drone 0.5 fails on getting builds for some repos

### ISSUE THREAD

**Issue by onbjerg** [drone/drone#1746]
Hi.

I tried using Drone 0.5 today on k8s. I have a previously populated Postgres database with builds from 0.4.

A lot of the repo build lists are working, but some of them aren't. When I navigate to some repos to see the build history, the API returns 500.

I checked the logs, but nothing of note is in there. It might be because when ``store.GetBuildList`` fails, the API just returns HTTP 500 without logging the actual error ([ref](https://github.com/drone/drone/blob/master/server/build.go#L22)).

Could we log the error so I can debug further? As I said, it only happens for some repos of mine, but there is no pattern so far, so I don't really know what's going on.

**Comment by bradrydzewski** [comment]
the 0.4 log format is not compatible with 0.5 data so this is expected. There is not a 100% clean path to upgrade to 0.5. Note that 0.5 is also not released yet.

**Comment by bradrydzewski** [comment]
sorry misread this. I thought build history was referring to the logs. I see you have a PR to log the error message, which I've commented on and recommended returning the error message to surface in the UI

**Comment by onbjerg** [comment]
The build history is not showing for some repos. Is this expected?

**Comment by onbjerg** [comment]
Or? 😟

**Comment by qrpike** [comment]
I'm having this issue as well, possibly a DB corruption issue as it used to work fine.

**Comment by bradrydzewski** [comment]
This issue centers around the fact that when you upgrade legacy versions of drone, the newer version of drone cannot read the old logs (they were stored in different formats). Nothing to do with database corruption.

**Comment by qrpike** [comment]
@bradrydzewski I've been using v 0.5 for what seems like almost a year now. I have the mysql volume as a ceph rbd. I switched it to run on a different server, now everything but the actual 'builds' list is working. mysqlcheck says everything is fine :/
