### ISSUE TITLE
Communicating closed/reopened pull request status through drone

### ISSUE THREAD

**Issue by Tathanen** [drone/drone#1748]
Regarding this issue: https://github.com/drone/drone-wall/issues/43

I'm wondering if it's within the scope of drone to expose a little more info about GitHub pull requests.  Obviously since drone is build-based, we currently only receive information about a pull request when a build is triggered.  Closing a pull request (or reopening a closed pull request) doesn't trigger a build.  For clients that use drone's API to track pull requests via builds, this leaves an unfortunate gap.  If a PR is closed, there is no closure on the client's end.  It knows if a merge happened, but a non-merge resolution is effectively schrodinger's cat.  In the case of the [drone wall](https://github.com/drone/drone-wall), a pull request will just hang on the wall unresolved until a timeout forces its removal.

There are a few potential solutions.  One being a special kind of "build" that is broadcast in tandem with closed/reopened pull requests that is basically just an informational notice.  Perhaps flagged in such a way that it doesn't show up in the actual drone interface, by virtue of it not being a real build, but it's still present to be consumed by clients that are more concerned with the status of the PR.  Alternatively, there could be a new route, `user/feed/events` perhaps, that is just a feed of PR state-changes.  Maybe even a websocket that could be monitored.

If any of this sounds feasible, or if there are any other solutions (that don't involve a separate client-specific connection directly to GitHub), great!

**Comment by bradrydzewski** [comment]
lets track this under https://github.com/drone/drone/issues/1878
