### ISSUE TITLE
Automate drone integration with gogs

### ISSUE THREAD

**Issue by jonathan-kosgei** [drone/drone#1768]
Hi,

Gogs just recently built in a new feature to create an admin user from the cli. I'm looking to completely automate the integration of gogs and drone using tokens created in gogs, but I'm not exactly sure how to go about it. This page says I have to set REMOTE_CONFIG=https://gogs.hooli.com?open=false to allow users to sign in manually via drone's web ui, I'm looking to bypass this step and programatically create hooks via api to completely bypass this step. How exactly would I go about this? Thanks!

**Comment by bradrydzewski** [comment]
>  I'm looking to bypass this step and programatically create hooks via api to completely bypass this step. How exactly would I go about this? Thanks!

this is not currently possible. You can try to hack around this limitation by manually inserting a record directly into the database, into the `users` table. For reference this is the user table structure:
https://github.com/drone/drone/blob/master/store/datastore/ddl/sqlite3/1_init.sql#L3

feel free to use our [gitter](https://gitter.im/drone/drone) channel for these sorts of questions as we try to reserve the issue tracker for verified issues. Thanks!

**Comment by jonathan-kosgei** [comment]
No prob +1 Thanks again!
