### ISSUE TITLE
expose errors in oauth2 authorization code grant

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1775]
Right now when the oauth2 provider (ie Bitbucket) fails to grant an authorization code an `error` query parameter is returned, as defined in the oauth2 specification:
https://tools.ietf.org/html/rfc6749#section-4.1.2.1

Drone currently looks for the `code` and re-directs, without checking for the `error` query parameter. In error scenarios (misconfiguration for example) this can result in redirect loops, and by not catching and exposing the error it can be difficult to debug.

We should therefore start catching and returning the error. This is the block of code:
https://github.com/drone/drone/blob/master/remote/bitbucket/bitbucket.go#L46:L50

Which could be adjusted to something like this:

``` diff
package bitbucket

import (
+   "errors"
    "fmt"
    "net/http"
    "net/url"
```

``` diff
    code := r.FormValue("code")
+   if err := r.FormValue("error"); err != "" {
+       return nil, errors.New(err)
+   }
    if len(code) == 0 {
        http.Redirect(w, r, config.AuthCodeURL("drone"), http.StatusSeeOther)
        return nil, nil
    }
```

Note that this should be adjusted in both the GitHub and Bitbucket implementations.

**Comment by bradrydzewski** [comment]
cc @holms

**Comment by holms** [comment]
Problem was that we've forgot to put certain permissions in bitbucket. We had to be carefully when reading docs. Thanks. But still there shouldn't be redirect loop in my opinion.

**Comment by alecharmon** [comment]
✋ Hey @bradrydzewski do you mind if i pull a pr for this? its my first time working in this repo.... what do you think the easiest way of testing that error scenario?

**Comment by holms** [comment]
Just create wrong permissions in bitbucket :)
