### ISSUE TITLE
agents will not connect because of wildcard certificate

### ISSUE THREAD

**Issue by larstobi** [drone/drone#1782]
I have deployed drone server and agents. We are using a valid wildcard certificate for the server. The drone server is behind a haproxy server which does the TLS connection.

After installing the new wildcard certificate, the agents won't connect and they print this message:

`unable to ping the server. Post https://build.opstest.example.com/api/queue/ping: x509: certificate is valid for *.example.com, not build.opstest.example.com`

`reconnect in 15s. Post https://build.opstest.example.com/api/queue/pull/linux/amd64: x509: certificate is valid for *.example.com, not build.opstest.example.com`

This is the server config:

```
DATABASE_DRIVER=sqlite3
DRONE_AGENT_SECRET=XXXX
DATABASE_CONFIG=/var/lib/drone/drone.sqlite
DRONE_GITHUB=true
DRONE_GITHUB_CLIENT=XXXX
DRONE_GITHUB_SECRET=XXXX
HTTPS_PROXY=http://proxy.example.com:80
HTTP_PROXY=http://proxy.example.com:80
NO_PROXY=admin.cloud
DRONE_ADMIN=larstobi
DRONE_DEBUG=true
```

This is the agent config:

```
DRONE_SERVER=http://app0.opstest.admin.cloud:8000
DRONE_TOKEN=XXXX
HTTPS_PROXY=http://proxy.example.com:80
HTTP_PROXY=http://proxy.example.com:80
NO_PROXY=admin.cloud
DRONE_DEBUG=true
```

How can I make the agents accept a wildcard certificate?

**Comment by vtolstov** [comment]
You have wildcard for subdomain, but try connect to sub-subdomain.
Certificate not valid for this.

2 Сен 2016 г. 13:27 пользователь "Lars Tobias Skjong-Børsting" <
notifications@github.com> написал:

**Comment by tboerger** [comment]
Already discussed at https://gitter.im/drone/drone?at=57c96591d52261ec344a5804

A wildcard cert for `*.admin.cloud` is not valid for `*.optest.admin.cloud`

**Comment by fjoesne** [comment]
I have this same problem, but i'm connecting directly to a subdomain, so the *.sub.domain is not whats causing it.
```
REMOTE_DRIVER=gitlab  
REMOTE_CONFIG=https://git.example.com?client_id=...
```
log: 
`Cannot authenticate user. Error exchanging token. Post https://git.example.com/oauth/token: x509: certificate signed by unknown authority`

Note: both drone and git are running with the same wildcard certificate.

**Comment by codejamninja** [comment]
I am having the same problem. The gitlab server has a wildcard certificate from GoDaddy, and drone has a letsencrypt certificate.

**Comment by codejamninja** [comment]
The problem happens on login. It won't let me login to gitlab because it rejects my gitlab's certificate.

**Comment by bradrydzewski** [comment]
In this case, mount your hosts ca-certificates into the drone server as a volume. The certificates are loaded by the TLS package in the Go standard library. You can see the paths that the Go standard library search here: https://golang.org/src/crypto/x509/root_linux.go

If you correctly install your certificate on the host machine, and correctly mount the certificate volume, it should solve the problem. If not, I recommend posting a question on StackOverflow and asking how to get wildcard certs working with Go programs. StackOverflow should give you access to domain experts that are more qualified to help you triage this issue further.
