### ISSUE TITLE
Drone 4.x Gogs remote drive broken with Gogs 0.9.97^

### ISSUE THREAD

**Issue by cusspvz** [drone/drone#1785]
Drone 4.x Gogs's driver has been broken with Gogs 0.9.97 and newer.

Every builds throw up the error: `fatal: Couldn't find remote ref refs/heads/XXX`

**Comment by bradrydzewski** [comment]
I'm running drone `0.5.0+704` and gogs `0.9.99.0903` and am unable to reproduce issues with the Gogs driver or with cloning repositories. Note that I am running the latest versions and have both configured to auto-upgrade.

If you continue to experience issues I recommend debugging in https://gitter.im/drone/drone where community members might be able to assist. There are many active gogs users in our channel. If we can pinpoint a reproducible bug in drone we can certainly re-open the issue.

**Comment by cusspvz** [comment]
Thanks for testing.

A little bit off-topic: Before posting it here, I've tried to test with a staging stack based on the `0.5` tag, as described on the `0.5` docs, but I was unable to launch workers because [drone/agent](https://hub.docker.com/r/drone/agent/) is not published.

**Comment by jbub** [comment]
Hey @cusspvz were you able to work around this issue, im experiencing it with Gogs 0.9.97 and 0.4, i also tried upgrading drone to 0.5, but still the same. I am running gogs behind caddy web server. This is the output from the build:

```
+ git init
Initialized empty Git repository in /drone/src/xx/yy/zz/.git/
+ git remote add origin https://xx.zz.vv/xx/zz.git
+ git fetch --no-tags origin +refs/heads/master:
fatal: unable to access 'https://xx.zz.vv/xx/zz.git': The requested URL returned error: 500
exit status 128
exit code 1
```

I was able to track it here https://github.com/gogits/gogs/blob/master/modules/auth/auth.go#L127, 
for some reason when running inside drone build, the authorization header contains token with `x-oauth-basic` suffix and not username and password. When i try to access the url directly from browser (after providing basic auth), its working corrently and it is not throwing 500. 

About `drone/agent` not published, you have to use the main drone docker image, but instead of running the root command, use the `drone/drone:0.5 agent` command.

**Comment by bradrydzewski** [comment]
@jbub you can run the git plugin in isolation for easier debugging:
https://github.com/drone-plugins/drone-git#usage

> for some reason when running inside drone build, the authorization header contains token with x-oauth-basic suffix and not username and password

this is standard practice for enabling 3rd party systems to authenticate when using git+http. In fact, this isn't unique to gogs. This is how drone clones github, bitbucket and gitlab. You can read a bit more about it here:
https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

note that drone has been using this method to authenticate git+http transport requests for the past year. So this is a heavily vetted method for authenticating, that has been testing in thousands of real world installations.

>  also tried upgrading drone to 0.5, but still the same.

I run drone 0.5 and gogs 0.9.99.0915 and am not experiencing any issues cloning public or private repositories. I have both configured to auto-upgrade to the latest docker images, so if there is an issue I'm generally aware of it pretty quickly.

>  am running gogs behind caddy web server

Is it possible caddy is stripping or mutating the authorization header?

**Comment by jbub** [comment]
Thanks for the info @bradrydzewski, i will investigate more and report back.

**Comment by cusspvz** [comment]
@jbub thanks for the tip about the agent, couldn't find it anywhere, or just missed it. I've tried to use **Drone 0.5** with Gogs **0.9.97** because I was getting issues with **0.4** as well. Are you already using **0.5**? Could you please test with Gogs **0.9.71**?

**Comment by tboerger** [comment]
Brad is currently using Gogs `0.9.99.0915` with Drone `0.5`
