### ISSUE TITLE
[Drone 0.5] Drone is not overriding the image CMD with the commands in the build

### ISSUE THREAD

**Issue by dcerecedo** [drone/drone#1788]
Using the following build file, drone is executing the default image command which is set to `CMD ["mvn"]` instead of running the commands specified.
```
pipeline:
  build:
    image: library/maven:3-jdk-8
    commands:
     - mvn clean install
```

**Comment by bradrydzewski** [comment]
per issue template please use https://gitter.im/drone/drone for questions

**Comment by bradrydzewski** [comment]
> one is executing the default image command which is set to CMD ["mvn"]

this is an incorrect assessment of the problem. Drone always, without exception, overrides the entrypoint and command for build containers.

please see the following sectino of the documentation:
http://readme.drone.io/0.5/usage/overview/#commands:68f80267fa3a50980dbb745a782b8dca

you will see that drone converts your build to a shell script which gets executed as the entrypoint and command:

```
#!/bin/sh
set -e

mvn clean install
```

I'm therefore not sure what issue you are experiencing, but the assessment that drone is using the default cmd is incorrect. If I use this yaml on the latest version of drone ...

```
pipeline:
  build:
    image: maven:3-jdk-8
    commands:
     - mvn -version
```

I see the following passing build results with commands executed as expected:

<img width="300" alt="screen shot 2016-09-09 at 9 21 12 am" src="https://cloud.githubusercontent.com/assets/817538/18390263/1d998b04-766f-11e6-8564-a4a3e63e6774.png">

I therefore cannot verify or reproduce the claim that drone is using the default CMD value and have to close the issue. If you continue to experience problems please use the [gitter channel](https://gitter.im/drone/drone) to triage and open an issue once others have been able to confirm the problem. Thanks!
