### ISSUE TITLE
Get build logs in the drone CLI

### ISSUE THREAD

**Issue by larstobi** [drone/drone#1794]
I would like to get at the build logs via the Drone CLI.

Use case example with build number:

```
drone build logs [-f] drone/drone 6
```

The -f option causes drone to not stop when end of file is reached, but rather to wait for additional data to be appended to the input.  The -f option is ignored if the specified job has stopped.

Another way to get logs would be from the git commit hash:

```
drone build logs [-f] drone/drone 240f2a8
```
## 

Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:
- [X] I have searched for existing issues
- [X] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [X] I am not using the issue tracker to ask why my build failed

**Comment by tboerger** [comment]
Maybe you also have to provide the job number as an additional flag.

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone/drone-cli/issues/42
