### ISSUE TITLE
shm-size does not seem to be supported ?

### ISSUE THREAD

**Issue by olymk2** [drone/drone#1798]
tried adding shm-size: 1g to a drone yaml when the tests start the container complains about the shm size being to small, running docker or docker compose with this parameter works and the container runs, guessing this is not being passed through drone to docker compose correctly

build:
  image: alexeiled/docker-oracle-xe-11g
  pull: True
  shm-size: 1g

am i passing this into drone correctly, and should i work or is this not supported yet ?

**Comment by bradrydzewski** [comment]
drone supports a subset of fields from the docker-compose file, where new fields are added on an as-needed basic. This is the list of currently supported fields:
https://github.com/drone/drone/blob/master/yaml/container.go#L58:L81

this is an example of a pull request that adds a new field:
https://github.com/drone/drone/commit/aaa702dab6858ac47a71e93c2ed6e9c54e0527be#diff-81eb6a8c464a5e832e044ddd009644ef

feel free to send a pr if it is something you would like added.
