### ISSUE TITLE
Can I retag when deploy to docker?

### ISSUE THREAD

**Issue by zhangsm** [drone/drone#1799]
```shell
publish:
  docker:
    registry: ***
    username: ***
    password: ***
    email: ***@test.com
    repo: ***/library/backend-api
    tags: [$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)]
    force_tags: true
    insecure: true
    file: Dockerfile
    load: ***/docker/image.tar
    save:
      destination: ***/docker/image.tar
```

not working ....

but got `***/library/backend-api:latest`

**Comment by bradrydzewski** [comment]
per the issue template, please ask all usage questions in our support channel, https://gitter.im/drone/drone

> tags: [$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)]

this is not expected to work. This is valid bash. The `.drone.yml` is not a bash file and therefore you should not expect bash syntax to work.

instead you can use string interpolation
http://readme.drone.io/usage/variables/
