### ISSUE TITLE
Feature request: limit agents to certain orgs

### ISSUE THREAD

**Issue by joshq00** [drone/drone#1804]
Limiting agents can allow us to use drone and provide teams with a few "free" agents -- or they can choose to supply their own hardware (for their orgs) to skip the queue -- with one central dashboard.

This would solve internal issues of scaling/ownership of the CI system, without forcing teams to each manage and run their own instance.

**Comment by bradrydzewski** [comment]
this is supported in the 0.5 release candidate. The agent has the ability to filter the jobs it is able to pull by providing a filter.

for reference, this is the configuration parameter:
https://github.com/drone/drone/blob/feature/mq/drone/agent/agent.go#L101:L104

the filter value can be expressed as a simple sql statement like this:

```
DRONE_FILTER=repo-owner IN ('drone', 'docker', 'foo', 'bar')
```

this allows you to direct builds to specific machines using more fine-grained controls.

**Comment by bradrydzewski** [comment]
note that this is available thanks to the new broker that was recently created / integrated. The selector capabilities are described in greater detail here:
http://mq.drone.io/stomp-extension-selector/

**Comment by joshq00** [comment]
Is it required that I run a separate stomp process or is this run by default? The reason I ask is that I am running drone dashboard from source in cloud foundry, which does not currently support multiple ports, and only accepts http/1.x

**Comment by bradrydzewski** [comment]
> Is it required that I run a separate stomp process or is this run by default?

It is run by default as part of the drone server process. The broker is embedded directly in drone binary and listens on a websocket at `/ws/broker`

**Comment by joshq00** [comment]
Awesome. Thank you @bradrydzewski
