### ISSUE TITLE
MariaDB: agent_addr exceeds max key length

### ISSUE THREAD

**Issue by joshq00** [drone/drone#1805]
In [6.sql](https://github.com/drone/drone/blob/master/store/datastore/ddl/mysql/6.sql), the `agents` migration creates a unique index of length 500. MariaDB has a max index of 255 and caused the migration to fail/prevents drone from starting. Changing to `varchar(255)` resolved the issue for us. Not sure of possible implications if non-IPs are used for `agent_addr`

**Comment by bradrydzewski** [comment]
sure if you send a PR I'll merge

**Comment by joshq00** [comment]
Do you have any preference between decreasing the field size and removing the constraint?

**Comment by bradrydzewski** [comment]
let's keep the constraint and just decrease the field size. thanks!
