### ISSUE TITLE
Expose previous build details in the model.Build{} (API)

### ISSUE THREAD

**Issue by vaijab** [drone/drone#1818]
Currently there is no way to know whether a build was a new build triggered by GitHub or it was a fork (build restart) of an existing build. The only place I managed to find the previous build number was in a forked build environment as `DRONE_PREV_BUILD_NUMBER` (https://github.com/drone/drone/blob/2d90155d5a0f1d2270a0f6ba4b112ed48b15248c/agent/agent.go#L289).

I would be great if it was possible to fetch information about the original build from the API. This information could then be surfaced in the UI as well.

Looking at the code, I see that `BuildLast` is there but only in `queue.Work{}`  (https://github.com/drone/drone/blob/2d90155d5a0f1d2270a0f6ba4b112ed48b15248c/queue/types.go#L14). Would it be possible to add some extra fields to `model.Build{}` about the original job?

**Comment by bradrydzewski** [comment]
maybe something like the parent build number? So if a build is forked from build number 25, the parent field would store the number 25 ...

```diff
type Build struct {
	ID        int64  `json:"id"            meddler:"build_id,pk"`
	RepoID    int64  `json:"-"             meddler:"build_repo_id"`
	Number    int    `json:"number"        meddler:"build_number"`
+	Parent    int    `json:"parent"        meddler:"build_parent"`
	Event     string `json:"event"         meddler:"build_event"`
	Status    string `json:"status"        meddler:"build_status"`
	Enqueued  int64  `json:"enqueued_at"   meddler:"build_enqueued"`
	Created   int64  `json:"created_at"    meddler:"build_created"`
	Started   int64  `json:"started_at"    meddler:"build_started"`
	Finished  int64  `json:"finished_at"   meddler:"build_finished"`
	Deploy    string `json:"deploy_to"     meddler:"build_deploy"`
	Commit    string `json:"commit"        meddler:"build_commit"`
	Branch    string `json:"branch"        meddler:"build_branch"`
	Ref       string `json:"ref"           meddler:"build_ref"`
	Refspec   string `json:"refspec"       meddler:"build_refspec"`
	Remote    string `json:"remote"        meddler:"build_remote"`
	Title     string `json:"title"         meddler:"build_title"`
	Message   string `json:"message"       meddler:"build_message"`
	Timestamp int64  `json:"timestamp"     meddler:"build_timestamp"`
	Author    string `json:"author"        meddler:"build_author"`
	Avatar    string `json:"author_avatar" meddler:"build_avatar"`
	Email     string `json:"author_email"  meddler:"build_email"`
	Link      string `json:"link_url"      meddler:"build_link"`
	Signed    bool   `json:"signed"        meddler:"build_signed"`
	Verified  bool   `json:"verified"      meddler:"build_verified"`
}
```

**Comment by vaijab** [comment]
Yes, `Parent` is a better word for it. Should I give it a go at implementing it?
