### ISSUE TITLE
Drone sign feedback from CLI

### ISSUE THREAD

**Issue by timgent** [drone/drone#1822]
Issue: Feedback from drone CLI could be improved when signing a .drone.yml

Currently: If the repo you are trying to sign isn't enabled in drone it won't give any feedback (just a blank line). Similarly it does't give any feedback when successful

Ideal: A sensible error message is presented if the repo you are trying to sign isn't enabled in drone. If it is successful it also tells you this.

Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:
- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [ ] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
I would accept a pull request that adds an error message. I disagree a success message is required because this is implied by the lack of error message, a zero exit code, and new or updated file written to disk

**Comment by timgent** [comment]
Thanks @bradrydzewski  
I agree a success message is less important, and partly a matter of style. I tend to think they are useful as a developer using a CLI tends to ideally not want to run another command to verify the success of what they just did. For example when I git commit or git push I think it is nice that I'm explicitly told what the outcome of the action was, rather than assuming success on a blank error message or needing to check the exit code or the commit log.

**Comment by bradrydzewski** [comment]
closing since the signature is killed in upcoming version of drone
