### ISSUE TITLE
There are two different versions of the online documentation for version 0.5

### ISSUE THREAD

**Issue by francoishill** [drone/drone#1834]
This seems to be the "older" docs: http://readme.drone.io/0.5/manage/server/
Guess then this is the "newer"? http://readme.drone.io/0.5/installation/server/

In the second link if we go to the [Agents](http://readme.drone.io/0.5/installation/agents/) it uses WebSockets (prefixed with `ws://` instead of `http://`) for the `DRONE_SERVER` variable.

This could be very misleading since the "latest" docker image for 0.5 does not work with the "older" docs.

Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [ ] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
drone/docs to track issues with docs

**Comment by bradrydzewski** [comment]
Also note `latest` is not 0.5, it is 0.4 ... 0.5 is not yet released and therefore only available under the 0.5 tag
