### ISSUE TITLE
cannot find build secrets,error setting commit status 

### ISSUE THREAD

**Issue by fanux** [drone/drone#1836]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [x] I have searched for existing issues
- [ ] I have discussed the issue with the community at https://gitter.im/drone/drone
- [x] I have provided a sample `.drone.yml` file to help the team reproduce
- [x] I have provided details from the build logs
- [x] I have provided details from the server logs by running `docker logs drone`
- [ ] I am not using the issue tracker to ask why my build failed

```
build:
  image: golang:1.6.2
  commands:
    - go build
```

logs:
```
time="2016-10-28T14:27:51Z" level=debug msg="cannot find build secrets for fanux/brone. GetTreeEntryByPath: error not exist"
time="2016-10-28T14:27:51Z" level=error msg="error setting commit status for fanux/brone/4"
```

I am using gogs driver.

**Comment by bradrydzewski** [comment]
Please use gitter.im/drone/drone for usage support
