### ISSUE TITLE
Provide global agent volume

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1837]
We should provide the ability to define, at the agent level, the ability to mount a global volume or set of volumes into each container.

The primary use case is the ability to mount certificate pools into containers, which may be very useful to organizations that are using self-signed certificates or custom cert pools. This is an example of how it might look:

```
docker run \
  -e DRONE_VOLUME=/etc/ssl/certs:/etc/ssl/certs \
  drone:0.5 agent
```

We should account for security by giving the ability to mount the volume readonly:

```
-e DRONE_VOLUME=/etc/ssl/certs:/etc/ssl/certs:ro
```

Another optional use case could be teams that want a local shared cache on the host machine per repository (cc @strk). While having shared volumes does not immediately provide this capability, it would provide the primitives on top of which one could build a local cache plugin.

**Comment by bradrydzewski** [comment]
Note that this can also be used to clean-up the logic for mounting the `drone exec` local volume [1]. This functionality could be rolled into `DRONE_VOLUME` where running `drone exec` will automatically append the local git directory as a volume in the list.

Below is an example of how this could work, but it is just example and the actual implementation will probably look a bit different:

```diff
-	if a.Local != "" {
-		transform.PluginDisable(conf, a.Disable)
-		transform.ImageVolume(conf, []string{a.Local + ":" + conf.Workspace.Path})
-	}
+	if a.Local == true {
+		transform.DisableClone(conf)
+		transform.ImageVolume(conf, a.Volumes)
+	}
```

[1] https://github.com/drone/drone/blob/5377c628449ffe827206aed6157d99efc8820da6/agent/agent.go#L167:L170

**Comment by strk** [comment]
It might be useful for the volume to have a standard mount point, like `/drone` is for the workspace, a convention so that `.drone.yml` (or plugins) recipes could rely upon (ie: if /drone/local is available, then do this and that...)

**Comment by vaijab** [comment]
I, as a lot of us, probably use kubernetes to run drone. I am not sure how useful would it be to have a single global agent volume. Maybe I just cannot see good use cases for that yet.

**Comment by strk** [comment]
I run drone on the development machine, and ask other contributors to do the same, to build a network of distributed agents. Running an agent currently requires downloading a lot of source code which is usually already available on the developer machine so the aim with a global volume is to map the local source code to use as reference upon checking out the code to be tested.

**Comment by tboerger** [comment]
I need that functionality as well, I'm running drone in a private network with certs signed by an internal CA. The agent and the server got volumes to mount it, but the clone step fails because of the self-signed certificate.

**Comment by bradrydzewski** [comment]
changeset 30b561636f5c31b7e2d1f4838d75f49bc1a32774 adds the `DRONE_VOLUME` parameter which is a string slice of volume mounts. Will be documented in 0.6

**Comment by koolay** [comment]
How to use `DRONE_VOLUME` in a plugin?

**Comment by bradrydzewski** [comment]
You need to provide DRONE_VOLUME to your server configuration. Example:

```
DRONE_VOLUME=/usr/share/drone:/tmp/drone
```

This will mount `/usr/share/drone` on the host into all containers at path `/tmp/drone`
