### ISSUE TITLE
Matrix Build / Awaiting Tasks

### ISSUE THREAD

**Issue by steve-gray** [drone/drone#1840]
Hey,

A while back I enquired about syncing the build state for drone tasks, so that all processes waited for an upstream process before continuing (i.e. wait for all matrix permutations to complete to a certain stage, before then executing the next stage). Now that 0.5 is reasonably stable-looking, I tried actually sitting down and pulling apart the 0.5 downstream plugin to see if I could use it.

What I believe I've found is that there's some gaps in the client driver to permit this: Specifically theres no means of introspecting about a builds jobs.  I can connect, see the model.Build which I obtain using the slug and build number environment variable, with the usual token passing - but I can't then get from that to anything meaningful.

Is this kind of synchronisation going to be possible in the YAML/execution engine natively in the pipelines stuff that's in the works - or is the view still to externalise this? (Given it's only interacting with drone itself) - if so, the client API probably needs expanding. I can do a PR for all the extra work on the drone/drone project to start hammering adding all the extra endpoints and data, but my questions are:

- Is this problem going to go away naturally with upcoming new features?
- If this isn't going to be core in the YAML, it'll end up being *very* tightly coupled to drones internals, is there a case to keep this as a in-house plugin?
- If it's going to be a community plugin - who wants to take up adding the relevant capabilites to the API?

If the answers are 'No, No, and <You>' - then I'll turn this issue into a PR and start working on adding the API's needed.

-Steve

**Comment by bradrydzewski** [comment]
> What I believe I've found is that there's some gaps in the client driver to permit this: Specifically theres no means of introspecting about a builds jobs

jobs are included in the payload when you access the build endpoint:
https://drone.company.com/api/repos/{owner}/{name}/builds/{number}

so it should just require a minor change to the build model at which point you'll start seeing the jobs get populated by client calls:

```diff
type Build struct {
	...
	Link      string `json:"link_url"      meddler:"build_link"`
	Signed    bool   `json:"signed"        meddler:"build_signed"`
	Verified  bool   `json:"verified"      meddler:"build_verified"`
+	Jobs      []*Job `json:"jobs,omitempty" meddler:"-"`
}
``` 

> Is this kind of synchronisation going to be possible in the YAML/execution engine natively in the pipelines stuff that's in the works - or is the view still to externalize this?

There are no immediate plans to include this natively in the engine. If at some point we did want this natively, it would need to be prototyped as a plugin first, similar to what we are doing with coverage.

> If this isn't going to be core in the YAML, it'll end up being very tightly coupled to drones internals, is there a case to keep this as a in-house plugin?

Going forward all new plugins are community owned. We are actively trying to move all plugins out of the drone organization toward community ownership, with the exception of the git and docker plugin which are core to the system.

> If it's going to be a community plugin - who wants to take up adding the relevant capabilites to the API?

Feel free to send a PR to add the field as mentioned above

**Comment by bradrydzewski** [comment]
also let's use the maintainer channel, https://gitter.im/drone/drone-dev for these sort of questions going forward.

**Comment by bradrydzewski** [comment]
merge with existing issue https://github.com/drone/drone/issues/1512
