### ISSUE TITLE
[Feature request] git sparseCheckout support

### ISSUE THREAD

**Issue by PeterDaveHello** [drone/drone#1849]
Thanks for providing such an awesome service/project! I really love your simple UI design!

As the main maintainer of a super huge/fat project - @cdnjs, I'm wondering if you would like to support git sparseCheckout. By default, git will checkout all the files from the repository to the filesystem, by sparseCheckout, we can decide to checkout partial of the files, so this will help decrease the number of files git will checkout, which will totally save both disk sapce, cpu time, build time!

There is only a small different steps between git clone and git, but would help a lot for a huge repo :smile: 

Reference:
- https://git-scm.com/docs/git-read-tree
- https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

- [x] I have searched for existing issues
- [x] I have discussed the issue with the community at https://gitter.im/drone/drone

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone-plugins/drone-git/issues/37
