### ISSUE TITLE
Versioning + changelog

### ISSUE THREAD

**Issue by rgarcia** [drone/drone#185]
Having versions with changelogs make it much easier to keep up with a project.
Context for me is that I'd like to have some idea of what I'm in for upgrading a drone server I set up a month ago.

**Comment by kaedroho** [comment]
@bradrydzewski is there a summary of the changes made in the 0.5 and upcoming 0.6 releases anywhere?

**Comment by tboerger** [comment]
AFAIK not for 0.5, but here you can see the release notes for the upcoming 0.6: http://readme.drone.io/releases/0.6.0-rc.1/

**Comment by Raffo** [comment]
Is there an update on this? It was closed a long time ago, but once again a version was tagged (0.8.6) and there are no release notes nor info on how to upgrade (it should just know but it would be great to know upfront). As a user, I just want to have as much knowledge as I can before doing an upgrade. 

Can you provide some info? /cc @tboerger @bradrydzewski

**Comment by Raffo** [comment]
Thanks @tboerger  for the quick reply, I can also help with that if you need help. 

In the meantime, are you are aware of any breaking changes or things I should watch out for when going from 0.8.5 to 0.8.6? It's only a minor version, but it's hard to tell if something will break.

**Comment by tboerger** [comment]
Drone 0.8.6 just includes a fix for Gitea, everything else shouldn't be changed. Let's see what we can work out for the upcoming 0.9 release, I will try to write a changelog for every release ;)
