### ISSUE TITLE
Inconsistent output log

### ISSUE THREAD

**Issue by DamienCassou** [drone/drone#1855]
- [x] I have searched for existing issues
- [x] I have discussed the issue with the community ⇒ no answer
- [x] I have provided a sample `.drone.yml` file to help the team reproduce
- [ ] I have provided details from the build logs
- [ ] I have provided details from the server logs by running `docker logs drone`
- [x] I am not using the issue tracker to ask why my build failed

I don't understand why sometimes drone shows logs and sometimes don't. Locally, I always get logs. But remotely, sometimes, I don't get anything. For example, https://ci.petton.fr/nico/amd-mode.el/6 shows no log. But this one does: https://ci.petton.fr/nico/amd-mode.el/2. The commands executed by .drone.yml changed in between, but I don't understand what I did that caused this.

In all cases, command outputs should be on stdout, but drone only shows the output for one of them.
- https://ci.petton.fr/nico/jade/5 <- no output from the test runner
- https://ci.petton.fr/nico/amd-mode.el/2 <- output from the test runner (a different one)

```
$ cat .drone.yml 
build:
  image: nicolaspetton/emacs
  commands:
    - cask install ;
    - ./run-tests.sh ;

$ cat run-tests.sh 
#!/bin/sh -e
cask exec ert-runner "$@"
```

The repository is at https://petton.fr/git/nico/amd-mode.el.

**Comment by bradrydzewski** [comment]
Hi @DamienCassou it looks like this is using Drone 0.4, which is about 6 months behind master which uses a new build runner and streaming protocol. If you can reproduce these issues in 0.5 we can re-open, but at this point we would not go back and retroactively troubleshoot and upgrade older versions of Drone.

If you are interested in manually patching 0.4 you can find a snapshot of the 0.4.2 code at the following tag https://github.com/drone/drone/tree/v0.4.2

**Comment by NicolasPetton** [comment]
@bradrydzewski Drone 0.5 is not released yet, is it?

**Comment by NicolasPetton** [comment]
@bradrydzewski I have the exact same issue with a drone instance installed today:
https://ci.petton.fr/nico/jade/5

Should we reopen this issue?

**Comment by bradrydzewski** [comment]
this bug is resolved in master, which will be part of the 0.6 release

**Comment by NicolasPetton** [comment]
@bradrydzewski thanks. Is there an easy way to use master? Or maybe I could just use the 0.6 docker images already?

**Comment by NicolasPetton** [comment]
@bradrydzewski thanks. Is there an easy way to use master? Or maybe I could just use the 0.6 docker images already?

**Comment by bradrydzewski** [comment]
I'll post to discourse.drone.io once 0.6 is ready for use. 0.6 is currently pre-release and not stable
