### ISSUE TITLE
Make lots of stuff pluggable

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1863]
The goal of this issue is to track things we might want to make pluggable in drone. We are getting to a point where configuration options are exploding, and people want to add new configuration options that may be more niche.

Instead of adding more and more configuration options, I'd like to explore making drone configurations scriptable. So instead of most options being provided as environment variables they would be provided as a script, or code, or something.

This could work by providing the server or agent with a directory to scripts or plugins. Drone would load all scripts in that directory, register them, and begin using them at runtime to alter or override the default behavior.

This issue will collect various use cases.

#### use Case 1

user wants to automatically add default steps to all Yaml files

#### use case 2

user wants to automatically mount a special directory only for a single plugin (cache plugin). This would allow a special cache plugin to safely work with a local directory on the host machine, without having to expose that volume to other pipeline steps, and without having to mark the build trusted

#### use case 3

user wants to automatically enable docker service containers to run in privileged mode without having to make the repository trusted. This could include adding/ dropping capabilities.

 #### use case 4

user wants a central or shared yaml file configuration that could apply to all, or a subset, of registered repositories.

#### use case 5

user wants to inject global or organization secrets using more advanced logic with data verification. For example, do not inject the global hipchat secret if the user has changed the hipchat url.

### Server Plugin, Authorizations & Scopes

admin wants to limit which repositories can be accessed in drone, and which users can activate which repositories.

## Example

This example demonstrates how one might use Docker compose to launch drone with a plugin to mutate the yaml prior to execution and add secrets (use case 5 above)

```
services:
  drone-agent:
    image: drone/drone:0.5
    command: agent
    environment:
      - DRONE_SERVER=ws://drone.company.com/ws/broker
      - DRONE_YAML_EXTENSION=http://drone-secret-injector-plugin

  drone-secret-injector-plugin:
    image: jmccann/drone-secret-injector
    environment:
      PLUGIN_CONFIG: |
        - match: plugins/docker|plugins/docker:(.+)
          environment:
            PLUGIN_USERNAME: foo
            PLUGIN_PASSWORD: bar
            PLUGIN_REGISTRY: registry.foo.com 
```

The above example assumes plugins are using some sort of RPC. The pro to using RPC is that it works with docker-compose and kubernetes without requiring a custom image.

We could also explore using the upcoming Go 1.8 pugins capability. The negative to this approach is that the plugins would need to be either bundled in the Docker image (meaning people would need to use custom drone images) or you would need to download the individual plugin .so files and mount as volumes in your Drone container.

Using native plugins seems ideal, but RPC and micro-services seem easier to install and setup.

**Comment by vaijab** [comment]
## Use case: start a privileged service implicitly
A user wants to always have a docker-in-docker service available on `${DOCKER_HOST}`. Currently a dind service requires a trusted repo.

**Comment by bradrydzewski** [comment]
a basic implementation so people start testing this out. Based on feedback we can plan to quickly iterate on this feature, which means it is unstable right now, but the more feedback we get the sooner we can finalize https://github.com/drone/drone/pull/1897

**Comment by bradrydzewski** [comment]
There is a basic implementation in master that lets you transform a yaml. Outside of simple unit tests I have used it heavily and will definitely want some feedback.

Below is some code that demonstrates how the various use cases above could be coded:

```go
package main

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/drone/drone/yaml"
)
func main() {
    r := gin.Default()
    r.POST("/example1", example1)
    r.POST("/example2", example2)
    r.POST("/example3", example3)
    r.POST("/example5", example5)
    r.Run() // listen and serve on 0.0.0.0:8080
}

// handle use case 1
func example1(c *gin.Context) {
	config := new(yaml.Config)
	if err := c.BindJSON(config);  err != nil {
		c.String(500, err.Error())
		return
	}
	config.Pipeline = append(config.Pipeline, &config.Container{
		Image: "plugins/slack:latest",
		Pull: true,
		Environment: map[string]string{}{
			"PLUGIN_WEBHOOK": "https://hooks.slack.com/services/...",
			"PLUGIN_CHANNEL": "dev",
		},
	})
	c.JSON(200, config)
}

// handle use case 2
func example2(c *gin.Context) {
	config := new(yaml.Config)
	if err := c.BindJSON(config);  err != nil {
		c.String(500, err.Error())
		return
	}
	for _, container := range config.Pipeline {
		if !strings.HasPrefix(container.Image, "drillster/drone-volume-cache") {
			continue
		}
		container.Volumes = append(container.Volumes, "/tmp/cache:/cache")
	}
	c.JSON(200, config)
}

// handle use case 3
func example3(c *gin.Context) {
	config := new(yaml.Config)
	if err := c.BindJSON(config);  err != nil {
		c.String(500, err.Error())
		return
	}
	for _, container := range config.Services {
		if !strings.HasPrefix(container.Image, "docker") {
			continue
		}
		container.Privileged = true
	}
	c.JSON(200, config)
}

// handle use case 5
func example5(c *gin.Context) {
	config := new(yaml.Config)
	if err := c.BindJSON(config);  err != nil {
		c.String(500, err.Error())
		return
	}
	for _, container := range config.Pipeline {
		if !strings.HasPrefix(container.Image, "plugins/docker") {
			continue
		}
		container.Environment["DOCKER_USERNAME"] = "foo"
		container.Environment["DOCKER_PASSWORD"] = "bar"
		container.Environment["DOCKER_REMOTE"] = "index.foo.com"
	}
	c.JSON(200, config)
}
```

You would start a program and pass the URL of the endpoint to the drone agent. For example, the above server starts on 8080 so you could provide the agent `DRONE_YAML_EXTENSION=http://localhost:8080/example1` assuming they run on the same server.

Again, still experimental, but hoping others can jump in and help get this spec finalized and implemented. Thanks all

**Comment by patrickjahns** [comment]
I am trying to grasp the feature - here is how I understood it so far:
- I provide `DRONE_YAML_EXTENSION`  via config to my drone-server 
- Whenever an event is fired, drone reads the drone.yml from the repostitory
- It then goes on and calls the `DRONE_YAML_EXTENSION` url with the configuration (drone.yml) as body
- The server at that url transforms the YAML and returns it to drone?

Would this also allow for creating custom plugins that can be called before any further drone steps (pipelines) will be taken?
An example would be, to prepend all build pipelines with a plugin, that parses git comments and executes certain functions on the content?
I was thinking of providing for example the drone command line steps via comments. 
Example:
```
@drone deploy staging
```
or
```
@drone build latest
```
or nicely as merging bot
```
@drone merge master
```


Quite similar functionality as to what the [dev ops bot rultor](https://github.com/yegor256/rultor) provides - without the need for running two systems

**Comment by tln** [comment]
Glad I found this, it will be nice to add notifications for every repo.

Is there a reason to move away from drone-launched docker containers using stdin-stdout for this?RPC requires an always running web server, much heavier than a one-shot filter.

**Comment by bradrydzewski** [comment]
> Is there a reason to move away from drone-launched docker containers using stdin-stdout for this?RPC requires an always running web server, much heavier than a one-shot filter.

Drone will continue to use drone-launched docker containers using stdin-stdout for build plugins. We are not making any changes to how build plugins work.

The plugins (extensions) that are being discussed in this thread are static. They are not created and destroyed on the fly like build plugins. They are more like micro-services, so using rest makes more sense here.

**Comment by manuelfelipe** [comment]
hey @bradrydzewski, is this something that you guys still plan to implement / have in core at some point ? looks really interesting for us. We are in a similar situation to what is described in #1990 were in about 100 different repos we have pretty much the same drone file and doing changes is starting to be a maintenance hell 

Was trying to play with it to see if I can get a build template out of it but looks like the code you merge in #1897 is no longer in master.

**Comment by mcnicholls** [comment]
I'm just about to attempt to construct a build system using drone and since we also have about 100 different repos that require the same .drone.yml, I'm going to be building a system that requires this kind of functionality in some form.

I'm going to start with 0.5 as it seems this functionality is still in there at that point, but I'm keen to know what form we think this will take in future releases.
I may even be able to contribute to the feature if we know how it should work.

**Comment by verbruggenalex** [comment]
I'm in the same boat. I have 160 projects with the same composer dependency. In Jenkins I was able to put a small required Jenkinsfile in their repository that would install it's starterkit and then import the required pipeline. This is extra security so that they can not fiddle with the pipeline. Just a simple diff could abort the build if the file was altered.
<p><details><summary><b>Jenkinsfile</b> <sup>(working example)</sup></summary>

```java
def extcode

node {
  checkout scm
  sh "composer install"
  extcode = load "vendor/vendor-name/package-name/Jenkinsfile"
  extcode.createWorkflow()
}
```
</details></p>
If I take the docker approach to achieve externalising the pipelines I most likely bypass the drone pipeline notifications which would remove the nice UI pipeline steps functionality to show a clean divided log. Ideally for me drone could provide a workspace initialization wich after verification would enable the import of installed yml files.
<p><details><summary><b>.drone.yml</b> <sup>(proposed example)</sup></summary>

```yml
workspace:
  path: starterkit
  init:
    composer:
      image: composer/composer
      commands:
        - composer install
        - composer verify .drone.yml
services:
  starterkit: ./vendor/vendor-name/vendor-package/drone.services.yml
pipeline:
  starterkit: ./vendor/vendor-name/vendor-package/drone.pipeline.yml
```
</details></p>

Now I understand this is not functionality you can build in a couple of days. And my need for externalising services and pipelines is quite urgent. So my question here is: _Is it currently possible to to send drone divided logs from a docker build so I can keep the nice detail/summary overview in the UI like I used for my code examples?_

**Comment by gboddin** [comment]
Hello,

Some info for use case 4 : 

We have lots of repository that could share the same pipeline, and we'de like for drone to build them with a default .drone.yml if none is found.

As a temporary hack/work-arround on 0.7 we implemented https://github.com/gboddin/drone/commit/b96400f5ad7362a756893505e364c0f0c12c8aaa.

This downloads an external config by default if none is found.

However I feel this is not the correct way to do it and after checking drone, I think the correct way would be : 

- Expose a repo specific config for the drone.yml file path in the UI
- If the file is an url, drone downloads it instead of getting if from the repo
- The change of this URL should be available for admins only

Benefits :
- Build projects that relies on the same components and have the same workflow without maintaining multiple .drone.yml
- The call could include query string parameters so the server can generate a .drone.yml based on the project
- .drone.yml can stay free of use for another drone (customer) instance
- Multiple drone instances could use different pipeline at the same time

**Comment by jpic** [comment]
I thought .drone.yml already supported anchors ?
https://learnxinyminutes.com/docs/yaml/

**Comment by EricRobert** [comment]
Hello,

I am using DRONE_YAML_EXTENSION to inject arguments to reproduce the nvidia-docker behaviour and thus, enable having build steps that can use NVIDIA GPUs.

It looks like recent versions dropped the support for this feature.
Any plan to add it back?

**Comment by vaijab** [comment]
Looks like this was removed in https://github.com/drone/drone/commit/a95b118cb3bb1a3153cfa14fe7669df877fe00c7

Discussion: https://discourse.drone.io/t/implicit-yaml-transformation-pluggable-yaml/1138

**Comment by bradrydzewski** [comment]
I am going to close this since we now have a bunch of new types of plugins that solve a lot of different use cases mentioned in this thread ...

Configuration plugins:
https://github.com/drone/drone-config-plugin-starter

Secret plugins:
https://github.com/drone/drone-secret-plugin-starter

Registry credential plugins:
https://github.com/drone/drone-go/tree/master/plugin/registry

The configuration plugins will be of interest to many in this thread. It is super flexible and can solve two use cases that were brought up in previous comments:

1. the ability to fetch a default yaml if none exists for the repository. The [plugin starter](https://github.com/drone/drone-config-plugin-starter) shows an example of how this could be done, but of course, you are free to code the logic in whatever way you see fit
2. the ability to mutate the yaml on the fly. You can fetch the yaml, append or remove steps, and then return this to drone.
3. the ability to extend the drone yaml syntax. For example, you could implement the [docker compose extends](https://docs.docker.com/compose/extends/) keyword to enable shared steps and shared logic. You would need to transpile the yaml, taking extends into account, and return a valid yaml back to drone

The above examples are just examples. You are free to solve these problems however you want as long as you return a valid configuration file back to Drone. Get creative :)
