### ISSUE TITLE
Tag Hooks not working for Gogs

### ISSUE THREAD

**Issue by mjwwit** [drone/drone#1870]
Tag hook support for Gogs was introduced in #1498 but is not working (anymore).
I tested using the latest Drone 0.5 image from Docker Hub and the latest version of Gogs on Docker Hub.

The Gogs webhook payload is:
```json
{
  "secret": "mysecret",
  "ref": "0.0.5",
  "ref_type": "tag",
  "repository": {
    "id": 84,
    "owner": {
      "id": 3,
      "username": "org",
      "full_name": "Organization",
      "email": "",
      "avatar_url": "https://gogs.somewhere.com/avatars/3"
    },
    "name": "project",
    "full_name": "org/project",
    "description": "Some description",
    "private": true,
    "fork": false,
    "html_url": "https://gogs.somewhere.com/org/project",
    "ssh_url": "ssh://git@gogs.somewhere.com:10022/org/project.git",
    "clone_url": "https://gogs.somewhere.com/org/project.git",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 7,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2016-11-24T08:42:01Z",
    "updated_at": "2016-11-24T12:21:33Z"
  },
  "sender": {
    "id": 1,
    "username": "michael",
    "full_name": "Michael de Wit",
    "email": "michael@somewhere.com",
    "avatar_url": "https://gogs.somewhere.com/avatars/1"
  }
}
```
It also sends the following headers:
```
X-Gogs-Delivery: asdf-asdf-asdf-asdf
X-Gogs-Event: create
```
The Drone response is successful (200 OK), but the body is empty and no build is triggered (the project has steps for "tag" events).

*Tag Hooks* are enabled in the Drone repository settings, and *Create* hooks are enabled in the Gogs repository settings.

**Comment by bradrydzewski** [comment]
I have a patch to improve the tag implementation that I will submit shortly, however, Gogs does not return the sha in the tag hook. This is a problem for Drone because we need a sha in order to fetch the .drone.yml using the Gogs API.

I think we've done as much as we can from the Drone side of things, and now require improvements to the Gogs hook payload to include sha:

```diff
{
+ "sha": "940bd336248efae0f9ee5bc7b2d5c985887b16ac",
  "ref": "v1.0.0",
  "ref_type": "tag",
  "repository": {
    "id": 1,
    "owner": {
      "id": 1,
      "username": "gordon",
      "full_name": "Gordon the Gopher",
      "email": "gordon@golang.org",
      "avatar_url": "https://secure.gravatar.com/avatar/8c58a0be77ee441bb8f8595b7f1b4e87"
    },
    "name": "hello-world",
    "full_name": "gordon/hello-world",
    "description": "",
    "private": true,
    "fork": false,
    "html_url": "http://gogs.golang.org/gordon/hello-world",
    "ssh_url": "git@gogs.golang.org:gordon/hello-world.git",
    "clone_url": "http://gogs.golang.org/gordon/hello-world.git",
    "default_branch": "master",
    "created_at": "2015-10-22T19:32:44Z",
    "updated_at": "2016-11-24T13:37:16Z"
  },
  "sender": {
    "id": 1,
    "username": "gordon",
    "full_name": "Gordon the Gopher",
    "email": "gordon@golang.org",
    "avatar_url": "https://secure.gravatar.com/avatar/8c58a0be77ee441bb8f8595b7f1b4e87"
  }
}
```

**Comment by tboerger** [comment]
For gitea we already merged a fix for that, but we can't influence Gogs as unknwon is not available.

**Comment by mjwwit** [comment]
Before this can be closed, a change is required in Drone.
Drone uses the raw file API of Gogs/Gitea to retrieve the `.drone.yml` config file, it accesses this API using the following endpoint: `GET /repos/:username/:reponame/raw/:ref/:path`, but it uses the full git ref as `:ref` (`refs/tags/v1.0.0`). Gogs and Gitea only support a short ref (`v1.0.0`).

**Comment by bkcsoft** [comment]
I'm not sure why it uses the API for this at all? just regular `/:user/:proj/raw/:sha/.drone.yml` should work just fine. TBH I'm not sure why gogs/gitea even has this endpoint 😕

**Comment by mjwwit** [comment]
It may have been part of @bradrydzewski's fix, because the SHA was not included in the webhook payload at first. It's just that it was never going to work because of an incorrect implementation.

As far as I can see, there are two possible solutions now:
1. Fix the current raw API implementation, correctly using the short ref. The upside of this fix will be that it will also be compatible with Gogs.
2. Remove usage of the raw API and use the SHA to directly access the file, as suggested by @bkcsoft. The upside is that this is probably very similar to other Git services, the downside is that Gogs will not work with this, since it's missing a SHA in the payload.

**Comment by vtolstov** [comment]
I think that we need something like GitHub because gogs try to implement
API like GitHub.

20 Дек 2016 г. 16:20 пользователь "Michael de Wit" <notifications@github.com>
написал:

**Comment by bradrydzewski** [comment]
> Fix the current raw API implementation, correctly using the short ref. The upside of this fix will be that it will also be compatible with Gogs.

I prefer this option.

> Remove usage of the raw API and use the SHA to directly access the file

The potential problem with this option is Gogs and Gitea will eventually implement application oauth, granting access to API endpoints. For this reason I would prefer the Drone codebase to rely on the API endpoints as much as possible.

**Comment by lunny** [comment]
Hi, any work on progress in this issue?

**Comment by mjwwit** [comment]
@lunny I'm working on a PR

**Comment by lunny** [comment]
👍

**Comment by damagedcode** [comment]
tested in my local， fantastic

**Comment by MehSha** [comment]
same issue here with latest gogs 0.9.113 (released yesterday).
not only tag event, but PR and branch create does not work as well.

**Comment by bradrydzewski** [comment]
Drone does not support PR or branch create events. It supports push events. Lack of PR support is documented

**Comment by MehSha** [comment]
OK thank you! may be because gogs has delivery on these events, caused me to expect drone to support them!!! sorry!
is that planed to implement? specially on PR that could be very helpful (checking tests before merging, for example)

**Comment by bradrydzewski** [comment]
There is an open issue for PR support if you want to subscribe to https://github.com/drone/drone/issues/1605

It is certainly a feature I'd like to see, but unfortunately I have other items I need to focus on right now. Certainly open to contributions, though.

**Comment by bradrydzewski** [comment]
merged fix, thanks!
