### ISSUE TITLE
Export/import drone active projects configuration

### ISSUE THREAD

**Issue by dgonzalez** [drone/drone#1877]
This is a feature request (although I am not sure if this is already implemented but I couldn't find it).

When you are working with done in a devops fashion (automating the deployment of Drone itself) we are in a situation where we want to keep the configuration of the active projects between builds. 

Let's say we spawn a new Drone in another AWS region, we want to be able to automatically inject the configuration of active projects without manual intervention.

Is that possible? would it be a nice feature to have?

**Comment by vaijab** [comment]
> Is that possible? would it be a nice feature to have?

I recently migrated drone from one kubernetes (aws) cluster to another. It was just a and RDS mysql dump and import.

**Comment by dgonzalez** [comment]
@vaijab the problem with your approach is that we go down to the rout of specific databases for dumps. I mean, if I use SQLite or y use MySQL there is a big difference on how do I restore a dump from a database. If drone provided something like "give me a json file with my active projects" that could be imported lately it would be amazing.

**Comment by bradrydzewski** [comment]
The recommended approach is to use database backups to restore from one environment to another. If you need to migrate across database vendors you might try using some of the automated database migration utilities.

For more advanced control, I recommend using the API to read data from one environment and write to another. If you need a language binding for the API we have a few available:

https://github.com/drone/drone/tree/master/client
https://github.com/drone/drone-node
https://github.com/drone/drone-ruby

I probably would not add such a utility to the official Drone repository. I think it could be developed as a separate repository, and could be a community-driven effort for individuals that need a more powerful, cross-database migration tool. I would therefore recommend interested parties create an publish such a project to GitHub. I would be happy to provide a link to such a project in the documentation.
