### ISSUE TITLE
Agent CPU usage increases with uptime

### ISSUE THREAD

**Issue by kbrownlees** [drone/drone#1879]
I have my agent (0.5) running on an AWS free tier ec2 instance. I have to keep rebooting it because it slowly starts chewing up my CPU credits. There is nothing else running on this instance.

Ubuntu 16.01.1 LTS.

My start command:

    sudo docker run --env DRONE_SERVER=... --env DRONE_SECRET=... --env DRONE_PLUGIN_PRIVILEGED=quay.io/kando/drone-docker-kando:*,plugins/docker:* --env DOCKER_MAX_PROCS=1 --volume /var/run/docker.sock:/var/run/docker.sock --restart=always --detach=true --name=drone-agent drone/drone:0.5 agent

Cloud watch for the last two weeks (the jumps are everytime I have rebooted it)
![48f658913546019cbb9e4e6e4779676da9c6d2b3](https://cloud.githubusercontent.com/assets/641520/20953981/1da706ee-bc9c-11e6-9913-bdd0eec1af3b.png)

htop from the box:
![92a5d1c653edde9e3465bf054f5f80ec5bb6026d](https://cloud.githubusercontent.com/assets/641520/20953996/3bd19788-bc9c-11e6-8f0b-463b4d73737b.png)

**Comment by bradrydzewski** [comment]
I'm not seeing any CPU issues with my agents. This is a snapshot from my instance below that has been running for a few days. If I notice any abnormal behavior I'll report back but unless I can find a way to repeat, I will need someone experiencing issues to take a more active role in debugging

<img width="959" alt="screen shot 2016-12-06 at 10 58 30 pm" src="https://cloud.githubusercontent.com/assets/817538/20954276/c71a1fda-bc07-11e6-84d7-e77f83b326a7.png">

**Comment by bradrydzewski** [comment]
Also can you provide a bit more information about which chart(s) seem to indicate there is an issue, and what you would expect the chart / trend to look like vs what you are seeing on your instance?

I see there are random CPU spikes to 3-4%, but this seems infrequent and could be explained by the fact that Drone has a persistent TCP connection sending heartbeats, combined with intermittent Go garbage collection.

**Comment by kbrownlees** [comment]
I just updated to the latest, so will let it run and report back if it still exists. Also, what version of docker would be best to use? I have a 1.11.2 since there was an issue with my builds when I tried to update to one of the early 1.12 releases but that could be fixed now so I can try to upgrade again.

Also happy to run a custom build if it comes to that.

**Comment by vaijab** [comment]
Just to add to this. I am not seeing CPU being used when drone is idle. I've had drone agent processes running for a while now and they do a lot of work when they are not idle. I cannot tell you which version I am running, but something recent I guess.

**Comment by kbrownlees** [comment]
Seems like I managed to grab a bad version last time I upgraded, doesn't appear to be happening with the latest. Will reopen if it comes back, apologies!
