### ISSUE TITLE
Standard error (stderr) is truncated

### ISSUE THREAD

**Issue by adrienverge** [drone/drone#1884]
This issue was partly [discussed on gitter](https://gitter.im/drone/drone?at=584adf4328d755bf14e580b1); I'm posting it here for reference and for people that encounter the same problem. It could be related to Docker version (see [this message](https://gitter.im/drone/drone?at=584c205cc29531ac5d46b49c)), although I'm not able to verify it at the moment.

---

First of all, thanks for this excellent software. I've been using it for 6 months and love it.  But I'm hitting a problem since I updated to 0.5. I understand it is in beta and I'm willing to solve it myself and make a patch if needed.

Sometimes, logs in stderr get lost and are never displayed neither on Drone web interface, nor in the API (`/api/repos/{owner}/{name}/logs/{number}/1?full=true`).

This bug can be reproduced with the following `.drone.yml` file:

```yaml
pipeline:
  test:
    image: alpine
    commands:
      - echo This goes to stdout
      - echo This goes to stderr >&2
```

On some builds `This goes to stderr` is displayed, on others it's not.  I've tested different images (`centos:7`, `node:6`...), same result.  It looks like stderr is truncated when the test series ends.  The more commands in the test series, the more likely the bug appears (on one of my long builds, the bug occurs every time).

It's very annoying when the tests outputs on stderr, because I just see `exit code 1` without any explanation.

Drone version: 0.5 (e5f13b794c11)
Docker version: 1.10.3
OS: CentOS 7

**Comment by bradrydzewski** [comment]
I was unable to reproduce with the sample yaml. Anyone else able to reproduce?

**Comment by bradrydzewski** [comment]
@adrienverge I believe this was the regression in docker 1.10.3 that impacted log output https://github.com/docker/docker/issues/22502

**Comment by adrienverge** [comment]
@bradrydzewski Thanks for following this up. I'll try Docker 1.12 and keep you informed.

**Comment by adrienverge** [comment]
I manually updated to Docker 1.12 and it solves the problem.

Thanks!
