### ISSUE TITLE
Allow variables inside volume mount

### ISSUE THREAD

**Issue by mrueg** [drone/drone#1900]
I currently to build a solution for developers to build their applications locally via drone ci.
As the home directory of the user varies, something like this came to my mind, when they try to run `drone exec`:
`volumes: $USER_HOME/.m2:/drone/.m2`

and having the user run it via something like this:
`drone exec --repo.trusted --secret USER_HOME=/home/foo`

Unfortunately there seems to be no variable support available for volumes.

Would it be possible to add support for it to drone?

**Comment by bradrydzewski** [comment]
we recently made changes to secrets and this is now possible:
http://readme.drone.io/usage/secret-guide/

note you need to change `$USER_HOME ` to `${USER_HOME}`

you will also need to update your cli to get the latest version
