### ISSUE TITLE
RFC secret modifications

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1901]
This is a proposal for changes (and hopefully finalization) of how secrets work in 0.5. This is a summary of why I believe changes are necessary:

1. I have been discussing with @donny-dont and we both agree that the new secret implementation is too complex and results in end-user confusion and frustration, in addition to support burden.
2. The interpolation is also how docker-compose handles secrets, and parity with docker-compose is a project goal. This is also how people seem to expect secrets to work, although I'm not sure if it is because they are used to 0.4 or used to docker-compose, or both.
3. The existing implementation is also not flexible enough for using different secrets with the same name for different steps. See issue https://github.com/drone/drone/issues/1888

# Goal

The goal is to ship a very basic, stable secret implementation in Drone and delegate advanced secret features to plugins. This allows developers to augment, experiment and iterate on secrets without breaking Drone.

I should note that we've made four breaking changes to secrets over the past year and I am not yet confident we have finalized how secrets should work in Drone. This is why I think the best solution is to delegate secrets to plugins, where we are free to experiment and iterate without constraint.

# Proposal

I believe we should take the best parts of 0.4 and 0.5 secrets to create a hybrid implementation that is secure and user-friendly. I propose we continue to manage secrets from the command line (and eventually user interface)

```
drone secret add octocat/hello-world DOCKER_USERNAME foo
drone secret add octocat/hello-world DOCKER_PASSWORD bar
drone sign octocat/hello-world
```

We remove the --image flag

```diff
-drone secret add --image=plugins/docker octocat/hello-world DOCKER_USERNAME foo
+drone secret add octocat/hello-world DOCKER_USERNAME foo
```

We interpolate secrets into the Yaml similar to 0.4

```yaml
pipeline:
  build:
    image: golang
    commands: [ go build, go test ]
  docker:
    image: plugins/docker
    repo: foo/bar
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
```

## Multi-Line Secrets

In 0.4 we had problems interpolating multi-line secrets. They would cause yaml parsing errors. To mitigate this issue we will automatically quote multi-line strings.

```
pipeline:
  build:
    image: alpine
    commands:
      - echo ${SSH_KEY} > ~/.ssh/id_rsa && chomd 0600 ~/.ssh/id_rsa
```

This could look something like this

```
if strings.Container(secret, "\n") {
  secret = fmt.Sprintf("%q", secret)
}
```

## Registry Secrets

In 0.4 we interpolated registry secrets in the `auth_config` section. I personally never really liked this approach and think we can probably find a better solution.

```
pipeline:
  build:
    image: foo.com/foo/bar
    auth_config:
      username: ${REGISTRY_USERNAME}
      password: ${REGISTRY_PASSWORD}
```

One option would be to store the registry credentials in the database in the repository table. This would mean registry credentials would be stored separately from secrets.

```diff
type Repo struct {
---
+ Registry string
+ RegistryUser string
+ RegistryPass string
+ RegistryEmail string
}
```

Ideally we wouldn't need to sign the yaml to pull private images. To mitigate security issues we can use the `Registry` field to store the name of the registry to which the registry username and password should be exposed.

Given the following configuration:

```
pipeline:
  build:
    image: registry.foo.com/bar/baz
```

The registry name stored in the database (ie registry.foo.com) would be used to match the image in the yaml. The registry username and password would only be used to pull images that match the registry. This allows us to safely use registry credentials without signing the yaml. 

## Pluggable Secret Stores

Finally we need to make secrets pluggable via extensions. I think we've tried to create a generic secret implementation that works for all possible use cases, and this has proven overly complex for end users.

I do not believe it is a good idea to continue to iterate and change the secret implementation in the core codebase since it causes breaking changes and instability.

I therefore propose we ship Drone with the most basic implementation of secrets. It will be simple, secure and most importantly will be stable. Any customization, including global or organization or using vault as a backend or whatever, would be implemented as an extension.

We can add a section to the documentation for extensions, similar to plugins.drone.io, so that teams can easily discover and take advantage of community extensions.

**Comment by jmccann** [comment]
This looks good mostly to me.

I think my biggest concern is how I'll re-implement global and org secrets.  We are using them a lot.  It is good to know they'll be implementable via extensions but I currently have no idea what that looks like.  So that is the biggest "risk" to me right now.

**Comment by bradrydzewski** [comment]
The addon (or plugin or extensions or whatever we call it) would be hosted in the same pod as the drone container and would be invoked at runtime. It would probably be a rest endpoint. The request would include repository meta-data:

```
POST http://drone-secret-addon

{
  "repo": "drone/drone"
  ...
}
```

The response would return a list of secrets:

```
[
{ "name": "docker_username", "value": "..." },
{ "name": "docker_password", "value": "..." },
]
```

I would envision the addon would be part of the compose file, like this:

```
services:
  drone-server:
    image: drone/drone:0.5
    environment:
      - DRONE_SECRET_EXTENSION=http://drone-secret-addon

  drone-secret-addon:
    image: drone/drone-secret-addon
```

I could even see the ability to add the configuration inline as part of the compose file. This would be similar to managing secrets with 0.4.

```
services:
  drone-secret-addon:
    image: drone/drone-secret-addon
    environment:
      DRONE_SECRET_CONFIG: |
          [*.docker_username]
            skip_verify = false
            secret = "octocat"
          [*.docker_password]
            skip_verify = false
            secret = "pa55word"       
          [dolores.slack_token]
            skip_verify = false
            secret = "....."     
```

There could be more advanced plugins that (for example) fetch secrets from services like vault or other secret stores.

The biggest drawback comes to individuals using organization secrets. I'm not sure if this is being used extensively since it wasn't introduced until 0.4 (to replace global secrets, which were promptly re-added). I get the sense that global secrets are more widely used. But for those using organization secrets you would lose the ability to set them using the Drone CLI.

**Comment by tonglil** [comment]
> Registry Secrets

Could you clarify how this will work for a Drone used by multiple teams?

For example: if repo A by team A wants to use registry `foo.com`, and repo B by team B also wants to use registry `foo.com`, but don't want to have their login info available to each other?

---

> Multi-Line Secrets

Really happy to hear about this!

---

Overall, I like the idea that secrets will work more similar to 0.4. The UI was one of the best parts of 0.4 because team members using this would not have to install a CLI tool to manage secrets - anyone can just copy secrets into the UI + paste the new results into the `.sec` file.

**Comment by bradrydzewski** [comment]
> Could you clarify how this will work for a Drone used by multiple teams?

there should be no change from an end-user perspective. The registry credentials are stored per-repository. This just details a technical change where we will store registry credentials in a separate database table, instead of in the `secrets` table like we do today in 0.5.

> anyone can just copy secrets into the UI + paste the new results into the .sec file.

In many organizations there was a clear separation between developers writing code and the individuals that managed the passwords. This was detailed a bit in this issue:
https://github.com/drone/drone/issues/1538

In 0.5 were therefore decided to store secrets in the drone database and to replace the `.sec` file with a `.sig` file. The sig file is a cryptographic signature of the yaml. This allows developers to modify the yaml and generate a signature without having to know or have access to secrets.

It is possible to use secrets in 0.5 without requiring a signature file. There can be security implications, but if you repository is private and your developers know the secrets anyway, it doesn't really pose any risk.

The `.sig` file is currently generated by the CLI. It is possible we could add a screen to the user interface that let's the user drag/drop their yaml onto the page to generate the signature, if there is interest in such a feature.

**Comment by tonglil** [comment]
Re registry credentials: gotcha, thanks for the clarification.

Re `.sig` file: I see. I will have to play around with this before further comments. Thanks.
