### ISSUE TITLE
Drone.IO disappeared on us without warning and lost deployment configs?

### ISSUE THREAD

**Issue by mikesparr** [drone/drone#1904]
I'm emailing `support@drone.io` in hopes that someone can access our past deployment configs since you shut off service without notice for us paying customers. I was shocked to learn from an engineer this morning he could not deploy our latest software build anymore.

The archive you left up in place of `drone.io` includes only the build settings but not the server deployment settings, which are required to recreate scripts elsewhere. We have a couple backed up but they are just some ENV settings and running our deploy scripts.

Can you email me please with copies of the deployments from my projects so we may proceed to find alternative provider?

**Comment by bradrydzewski** [comment]
support@drone.io would be the appropriate channel for questions
