### ISSUE TITLE
RFC: Run all steps for all event types, by default

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1906]
The current behavior is that plugins do not execute, by default, for pull requests. In order to execute a plugin for a pull request it must be explicitly enabled:

```diff
pipeline:

  notify:
    image: plugins/slack
    channel: developers
    username: drone
   when:
     event: [ push, pull_request ]
```

This causes confusions for many drone users. There is a bit of magic under the covers where drone is automatically detecting what steps are plugins, and automatically disabling them for pull requests. The fact that this logic does not apply to build steps only adds to the confusion.

The goal, therefore, is to remove this inexplicit behavior and always execute all steps in the pipeline regardless of event type. This would eliminate the need to explicitly enable plugins for pull requests:

```diff
pipeline:

  notify:
    image: plugins/slack
    channel: developers
    username: drone
-  when:
-    event: [ push, pull_request ]
```

This means you would need to explicitly configure when you want plugins to execute, or not execute. For the record, I'm already doing this personally for more drone repositories ...

```diff
pipeline:

  notify:
    image: plugins/slack
    channel: developers
    username: drone
+  when:
+    event: push
```

The potential downside is the user could forget to configure a plugin to skip pull requests, which could have negative consequences if the plugin executes a deployment, for example.

I believe this problem is mitigated, however, by the fact that secrets are not injected for pull requests. So even though a plugin might accidentally execute for a pull request, it is unlikely it would successfully execute without secrets.

**Comment by bradrydzewski** [comment]
cc @jmccann @tboerger @donny-dont @benschumacher

**Comment by metalmatze** [comment]
> So even though a plugin might accidentally execute for a pull request, it is unlikely it would successfully execute without secrets.

Without that, it could be really bad. But like this I think it's ok. 👌

**Comment by bradrydzewski** [comment]
I'm 50 / 50 on the change, so if there are strong feelings here we can keep the default implementation. Probably need to hear from folks using org or repo secrets

**Comment by mjwwit** [comment]
Are you still making an exception for `deployment` type events, or will those be going through every pipeline step by default as well?

**Comment by bradrydzewski** [comment]
@mjwwit no, this pull request removes that exception, and would require you add the following line in your yaml to skip steps locally:

```diff
pipeline:
  docker:
    image: plugins/docker
    when:
+     local: false
``` 

The goal is really to remove any and all magic in the yaml. In this case when developers are starting to use drone, they assume `drone exec` runs all steps, and then struggle to figure out why it skeps certain steps, and then they think drone is broken.

They have similar issues with plugin steps and pull request. See https://github.com/drone/drone/issues/1906

This will definitely be a mildly annoying change to existing drone users, but this should be much more intuitive going forward for new users (hopefully there will be many) and result in much less frustration and support requests.

**Comment by bradrydzewski** [comment]
Note that I edited by above comment. I though the question was for issue 1910 and then realized it was for issue 1906. The issues are related, so my reply still made sense after some minor tweaks :)

**Comment by jmccann** [comment]
I'm torn on this.

In the environment I've been supporting there have not been many cases where someone has wanted to run plugins during a `pull_request`.  The times they have (a couple times I know of) we DID get bit by current behavior.  I even forgot and was spinning on it before remembering we had to explicitly add it with `event: [pull_request, push, tag, deployment]` as well as adding the event to the secret.  So I would say it is more intuitive that it runs for all events, including `pull_request`. (+1)

However, my gut feel is that it should remain as it is.  I think this is a good protection from potentially malicious PRs.  In my environment it is hosted internally and maybe a malicious PR is not as great of a concern ... but I don't know why it still IS a concern of mine (personally).  So I would say leave it as it is. (-1)

There is also the ability now to extend/plugin your Drone configuration now with #1897, right?  Could that be used instead to add `pull_request` to all plugins if a Drone environment wanted it instead?  What if we do have plugins run in `pull_request` by default?  Can that be "undone" with a plugin/extension?

Finally, I feel like there are different types of PRs.  A "trusted" PR that is from a branch in the same repo and an "untrusted" PR that is from a fork.  I wouldn't mind having a "trusted" PR run plugins but would want an "untrusted" PR to not run them.  Not sure if this is something that has been considered?

**Comment by bradrydzewski** [comment]
> In the environment I've been supporting there have not been many cases where someone has wanted to run plugins during a pull_request

agreed, in fact I think most people won't want plugin steps to run for pull requests. I would expect them to add a when clause to limit when the step should execute.

```diff
pipeline:
  publish:
    image: plugins/docker
    when:
+     event: [ push ]
```

If you look at the [.drone.yml](https://github.com/drone/drone/blob/master/.drone.yml) for the official drone project you'll notice I specify an event for ever step (even though I don't need to). This change would make this behavior required.

> I think this is a good protection from potentially malicious PR

I think you would still be protected from a malicious pull request because you would sign your yaml file. If you only want your plugin to run for push events, you would add `event: [ push ]`. If a pull request altered this, the signature would fail and secrets wouldn't be released.

**Comment by bradrydzewski** [comment]
Also note that by default, secrets would not be released to pull requests. So just because a plugin step executes during a pull request (because developer forgets to add when clause) the secrets won't be released, causing the plugin and build to fail.

**Comment by bradrydzewski** [comment]
I think this proposal really comes down to the following:

__PRO__ this will probably make sense to new users who have never used drone. They will expect pipeline steps to always execute, unless the step is configured to not execute using a `when` clause.

__CON__ this will cause most yaml files to be slightly more verbose. They will need a `when.event` block when they didn't need one before

__CON__ this will be confusing to existing drone users that have learned the existing quirks that otherwise confuse new drone users :)

**Comment by benschumacher** [comment]
I'd add one more CON, which might be transitory.

**CON** some plugins do a poor job of failing gracefully (in a clear manner) when secrets aren't set.

In general, I like the current approach, but I could see the personal preference side of this. For example, I may want to get notified via Slack if a PR comes in, but I likely don't want a container published. That said, if secrets aren't made available to PRs at all, anyhow, then I don't think that work regardless, which begs the question, which plugins *are* we expecting to work in these conditions? (I'm fully acknowledging my ignorance to some use cases here...)

**Comment by gtaylor** [comment]
cc @alienth for  a look

**Comment by alienth** [comment]
As a new user, I'd definitely be surprised at the limiting keyword `when` being necessary to add a case (`pull_request`) rather than remove it. I guess from a cleanliness standpoint, I'd desire a more well-defined `when` keyword that works consistently for both build steps and plugin execution.

On the security POV, I'd tend to prefer to rely on more explicit controls rather than relying on implicit config magic. It seems that secrets injection already has explicit controls which define what events are safe for injection.

That said, I could see a case where a secret is declared safe for a `pull_request` event in an specific environment (for example, where access to your PR system is strongly restricted). This sets up a trap where a new notification is defined which uses an unrestricted PR system. In that scenario, an easily forgotten `when` clause could lead to secrets being leaked.

I'm a very new user, so please consider this to be a mostly-uninformed first impression.

**Comment by gtaylor** [comment]
Also probably good for @JordanMilne to take a peek, too.
