### ISSUE TITLE
GOGS setup page needs updating

### ISSUE THREAD

**Issue by sokoow** [drone/drone#1913]
Hey Brad,
I think gogs setup instructions need to be slightly updated: http://readme.drone.io/admin/setup-gogs/

I'm getting this after following them:

./drone  server
WARN[0000] agents can connect with token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0Ijoic2VjcmV0IiwidHlwZSI6ImFnZW50In0.Nl9DEpaJMHJ8KCZKapmmQWWtb9PP6pwkeIJ-Jqcogeo 
ERRO[0010] cannot register sokoow. registration closed 

or a 404 when I set ?open=false.

Any idea?

**Comment by tboerger** [comment]
It's documented correctly, you just skipped the admin part. Registration is closed and you have not defined any admin user

**Comment by bradrydzewski** [comment]
the docs are up-to-date

also note that `?open=false` is not a thing anymore. That was a parameter in drone 0.4 but is not used in drone 0.5

**Comment by sokoow** [comment]
ok thanks, but one line of note about DRONE_OPEN would be useful there:)

**Comment by tboerger** [comment]
@sokoow it's part of the general install instructions like http://readme.drone.io/admin/installation-guide/ and also part of the reference like http://readme.drone.io/admin/installation-reference/
