### ISSUE TITLE
Registration process unclear in Bitbucket Server documentation 

### ISSUE THREAD

**Issue by davidak** [drone/drone#1914]
Hey @josmo,

thanks for implementing Bitbucket Server support!

We have problems to configure it since the registration of the application in Bitbucket don't work as described.

We tried to debug this but get stuck. Maybe you know how to do it and can fix the instructions.

http://discourse.drone.io/t/bitbucket-server-documentation/176/

**Comment by josmo** [comment]
@davidak I'll see about updating the docs. Unfortunately depending on what version of stash/bitbucket server the workflow varies slightly.

only the incoming link matters


1. You'll need to go to application links in the admin panel
enter the url for where drone will be hosted and click create link (it will say the service isn't up yet just continue)
2. give it a name and don't fill anything out (I know stupid but it's the only way it works)
3. edit the application link you just created
4. select Incoming authentication
5. Match the Consumer key to the ENV variable for drone
6. Consumer name doesn't really matter
7. copy in the public key that was created and matches what drone is using for the private key
8. make sure to add the consumer callback url to be the hosted link with /authorize at the end

sorry it's so many steps and a non intuitive order but Stash/Bitbucket server is not super easy to integrate with :/

**Comment by JaegerBane** [comment]
Is the current consensus that Drone doesn't _really_ support Bitbucket? I had a read through that discourse thread and it doesn't appear to have resolved the original issue.

I'm currently in the process of researching Drone for use as CI on a container-based project with the repos stored on Bitbucket, and the above doesn't look very encouraging :(

**Comment by davidak** [comment]
@JaegerBane i was not able to get it working with our server. @appleboy has a working setup.

You can try to get it working with your bitbucket server and report back.

**Comment by bradrydzewski** [comment]
> Is the current consensus that Drone doesn't really support Bitbucket

I do not think so. There are multiple individuals successfully running Drone + Bitbucket Server in production. There are other individuals that have experience blocking issues preventing a working setup.

So perhaps a more accurate description would be partial or alpha support. Certainly having more people try and provide feedback could help advance the integration.

**Comment by josmo** [comment]
@JaegerBane I'm not sure the discourse thread you're talking about specifically but if it's the one I remember, I believe they had a working solution of a different kind which meant they weren't pursuing the bitbucket integration yet.  Right now my experience is that it's solid once you have the configuration figured out (I'll be the first to admit it's not the easiest :/ Sadly the auth situation there is more complicated then I'd like). I feel like it's worth it but that's up to each to decide if it's worth it for them :)

One thing that will help that's not currently documented is you no longer need to put the rsa key as a file in the container. You can use STASH_CONSUMER_RSA_STRING to set it up as an environment variable string.   Feel free to hit me up if you have an questions. I only have access to certain versions but I'm more then willing to help.

**Comment by fazpu** [comment]
The integration is has been working fine for me. I also got stuck because I had this wrong:

You will also need to check the following permissions:

Account:Email
Account:Read
Team Membership:Read
Repositories:Read
Webhooks:Read and Write

Hope it helps. The decription is taken from http://readme.drone.io/0.5/install/setup/bitbucket/.

**Comment by twpayne** [comment]
I've opened https://github.com/drone/docs/pull/218 to document some of these.

**Comment by bradrydzewski** [comment]
closing in favor of https://github.com/drone/docs/pull/218
