### ISSUE TITLE
Show warning when fail to auth to docker registry

### ISSUE THREAD

**Issue by jmccann** [drone/drone#1917]
We ran into a situation where auth was failing to pull from a private registry. We already had pulled the image previsouly so it was cached. We had `pull: true` set.

We pushed an updated version of a tag to our registry. Drone was not pulling it due to auth failure, which I would expect. But the auth failure was not in logs and Drone continued to run tests from the cached image, which I would not expect. So we thought Drone was ignoring `pull: true` for some reason. We later "updated" our registry auth (we remember it had changed) in Drone and everything started to work as expected.

So given:
* registry credentials are provided
* Drone is not able to auth

I would expect Drone to provide a warning to the user so if their build fails or they get unexpected results they have an idea why.

Discussed in http://discourse.drone.io/t/failure-to-pull-latest-private-image-uses-cached-image-instead/188

**Comment by patrickjahns** [comment]
This will be really helpful

**Comment by tonglil** [comment]
I agree, pull fails should warn (but continue) if auth doesn't succeed.

**Comment by bradrydzewski** [comment]
as of 1.0 this now results in a failed build
