### ISSUE TITLE
HTTP Streaming for build jobs API 

### ISSUE THREAD

**Issue by Dorian** [drone/drone#1927]
While a job is running the API returns 404.

e.g.

```ruby
/api/repos/owner/name/builds

id  | ref | status
576 | refs/pull/113 | running

/api/repos/owner/name/logs/576/1

"404 Not Found"
```

I tried using HTTP Streaming and regular HTTP queries.

I want to be able to read the job output from my console in real time, is it possible?

Also posted on Discourse: http://discourse.drone.io/t/http-streaming-for-build-jobs-api/230

**Comment by bradrydzewski** [comment]
Websockets are prefixed with /ws ...Soon this case it is /ws/logs/:owner/:name/:build/:number

The frontend, drone-ui, is based on the API. So any piece of functionality you see in the UI is backed by endpoints that any client can access. You can see all endpoints at https://github.com/drone/drone/blob/master/router/router.go

**Comment by Dorian** [comment]
@bradrydzewski Actually it's using HTTP streaming already but thanks :)

```
/api/stream/:org/:repo/:build_id/:job_id
```

**Comment by bradrydzewski** [comment]
I believe that is an old endpoint as is not available in the latest version of drone. I would therefore recommend using `/ws/logs/:owner/:name/:build/:number`

**Comment by Dorian** [comment]
Oh, maybe we are using an old version of drone, but the HTTP Streaming was pretty simple to implement and it works :) 

```
  STREAM_URL   = BASE_URL + "/stream/#{OWNER}/#{NAME}/:build_id/#{ENV['JOB_ID'] || 1}"

  def api(url, stream: false)
    url << "?access_token=#{DRONE_API_TOKEN}"
    uri = URI(url)

    Net::HTTP.start(uri.host, uri.port) do |http|
      request = Net::HTTP::Get.new uri

      http.request request do |response|
        response.read_body do |chunk|
          lines = chunk.lines.grep(/^data:/).map { |l| l.gsub(/^data:/, '') }
          print lines.map(&:strip).compact.join("\n")
        end
      end
    end
  end

  api(STREAM_URL.gsub(':build_id', ARGV.first), stream: true)
```

**Comment by Dorian** [comment]
@bradrydzewski websockets don't seem to be available in the version I'm using:

```
wsd -url "ws://our.ci.server/ws/logs/:org/:repo/:build_id/:job_id?access_token=ACCESS_TOKEN" -origin "http://our.ci.server"

# and many other combinations, I get:

panic: websocket.Dial ws://... ... ... bad status
```
