### ISSUE TITLE
Support Proxy Protocol in server

### ISSUE THREAD

**Issue by johnrengelman** [drone/drone#1939]
Drone 0.5 relies on the X-Forwarded-For and X-Forwarded-Proto headers to determine the server's base URL and in the OAuth authentication flow. It also relies on websockets for things like streaming the build logs to the client.

Currently this configuration is not supported under AWS's ELB. First, the X-Fowarded headers are only sent when the ELB is in HTTPS/HTTP mode. However, when in this mode, the connection can't be upgraded to a websocket connection. This requires the SSL/TCP mode. But once set to SSL/TCP mode the X-Forwarded headers are no longer sent and Drone can no longer execute the OAuth authentication sequence (you end up in a redirect loop as Drone doesn't know the original protocol requested).

This is typically resolved by enabling ProxyProtocol support (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html) which allows the ELB to send client information. This requires the server side to understand the protocol.

There are 2 options to address this.
1) Use the AWS ALB which supports websockets in HTTPS/HTTP mode - however, the ALB can't be used for SSL/TCP connections so it limits scenarios where the balancer needs to be used to support both modes
2) Support the proxy protocol line in request strings using something like this - https://github.com/ninchat/go-proxyprotocol

**Comment by xsmaster** [comment]
@johnrengelman I'm running into this issue right now. I'm using an ALB in HTTP mode and unable to see the build logs at the time of building the project. 

Any ideas of a workaround?

**Comment by johnrengelman** [comment]
I ended up putting an nginx server that syrips the proxy line from the
message in front of the drone server.

**Comment by xsmaster** [comment]
@johnrengelman Not sound dense. I would just like to use your workaround.

Is your setup like:

1. `Inbound Traffic --> NGINX --> ALB --> Drone Server`
or 
2. `Inbound Traffic --> ALB --> NGINX --> Drone Server`

Thanks for your help!

J

**Comment by johnrengelman** [comment]
Inbound -> ELB w/ proxy protocol enabled -> nginx -> drone

**Comment by johnrengelman** [comment]
`nginx.conf`
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    log_format  proxy '$proxy_protocol_addr - $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent"';

    access_log  /var/log/nginx/access.log  proxy;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```
`/etc/nginx/conf.d/default.conf`
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server { 
    listen       80 proxy_protocol;
    server_name  localhost;
    access_log   main;
    set_real_ip_from 172.29.201.0/24;
    real_ip_header proxy_protocol;

    resolver 169.254.169.250;
    set $backend_upstream "http://upstream:80";
    client_max_body_size 0;
  
    location / {
      proxy_pass      $backend_upstream;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_buffering off;
      chunked_transfer_encoding off;
      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
      proxy_set_header X-Forwarded-Proto "https";
    }
    
    location ~* /ws {
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Proto "wss";
        proxy_set_header Host $host;
    }
  }
```

**Comment by bradrydzewski** [comment]
Starting with 0.8 we have the ability to provide the hostname with DRONE_HOST so that we can deprecate X-Forwarded-For and X-Forwarded-Proto. We also removed websockets in favor of server-sent events.

This should eliminate the need for proxy protocol.
