### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by MorphBonehunter** [drone/drone#1943]
Today i want to give drone with gittea an try and failed to get it working.

I've build drone myself (latests master) on Archlinux (go version go1.7.5 linux/amd64) and after starting up and try to login to Gitea (gogs) i got the following exeption:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]
```
So ok, maybe something wrong with my build, so i extracted the drone binary from your docker image
(docker save -> extract etc.) but interestingly its the same error with that.

So i google a little bit and found this two bugs #1765 and #1759.
This all reads like it is an problem on arm so i wonder why i have this on amd64 but i thought i should give it a try and alter the Makefile a little bit (for simplicity):
```
diff --git a/Makefile b/Makefile
index f40359b2..2f82b71a 100644
--- a/Makefile
+++ b/Makefile
@@ -46,7 +46,7 @@ test_postgres:
 build: build_static build_cross build_tar build_sha
 
 build_static:
-       go install -ldflags '${EXTLDFLAGS}-X github.com/drone/drone/version.VersionDev=$(DRONE_BUILD_NUMBER)' github.com/drone/drone/drone
+       go install github.com/drone/drone/drone
        mkdir -p release
```
After that the resulting binary isn't staticaly linked and works.
So now my question is if this is really related to the glibc (glibc on Arch is 2.24) and if drone can something do against this as i realy want to use the drone bin outside of docker?
(easiest thing as an new make target for creating a dynamically linked binary?) 

I'm courios about this bug as i runs inside the docker container.
As this is something with opening a supporting shared library (as i understand) it only works inside the docker container because there is no other file (except one ca file) besides the drone binary, isn't it?

**Comment by olymk2** [comment]
I just hit this on ubuntu 64bit I can confirm its an issue, that change has fixed it for me thanks for posting how you got around the problem.

**Comment by MorphBonehunter** [comment]
@olymk2 another one if you don't want to change something on drone "code" and you use systemd, you could workaround it with following in your systemd service file:
```
InaccessiblePaths=/etc/nsswitch.conf
```
This prevents drone from reading this file and the dynamic lib loader for nss modules don't kicks in.

**Comment by olymk2** [comment]
@MorphBonehunter good to know but i am not using systemctl because this is just for drone-cli unless you mean i should set that on my remote drone server ?

I basically compiled the project and copy drone command to /usr/bin so there is no service running to my knowledge.

**Comment by MorphBonehunter** [comment]
@olymk2 it is only an workaround for the case if you want to run drone-{server,agent} not in the provided docker container (there is no nsswitch.conf) on "bare-metal".
If you use it as cli you are right, there is no service and it work as you said.

**Comment by MorphBonehunter** [comment]
Mhh...i'm a little bit astonished.
I hit the problem (of course) when i try to use drone as cli as in this case i can not easily avoid the usage of `/etc/nsswitch.conf`. So i give it a try to use the bin from http://readme.drone.io/usage/getting-started-cli/ and it worked!
So i did not `make build_static` but `make build` for generating all binarys with the following outcome:
```
ldd release/drone 
	not a dynamic executable
ldd release/linux/amd64/drone
	not a dynamic executable
```
`release/drone` crashes, `release/linux/amd64/drone` doesn't crash and runs as expected but does not include the whole "feature-set" `release/linux/amd64/drone server: sql: unknown driver "sqlite3" (forgotten import?)`.

Maybe someone could give me a hint why leave out some features does not trigger the bug (i did an strace and found that the "release" file also reads /etc/nsswitch.conf but does not try to read /etc/ld.so.cache or any of the libnss libs)...

**Comment by MorphBonehunter** [comment]
@bradrydzewski: i've patched the Drone Makefile locally with the following lines:
```
diff --git a/Makefile b/Makefile
index f40359b2..b8d7e6a7 100644
--- a/Makefile
+++ b/Makefile
@@ -50,6 +50,12 @@ build_static:
 	mkdir -p release
 	cp $(GOPATH)/bin/drone release/
 
+build_dynamic:
+	rm -f $(GOPATH)/bin/drone
+	go install -ldflags '-X github.com/drone/drone/version.VersionDev=$(DRONE_BUILD_NUMBER)' github.com/drone/drone/drone
+	mkdir -p release/dynamic
+	mv $(GOPATH)/bin/drone release/dynamic/
+
 # TODO this is getting moved to a shell script, do not alter
 build_cross:
 	GOOS=linux   GOARCH=amd64 CGO_ENABLED=0 go build -o release/linux/amd64/drone   github.com/drone/drone/drone
```
I don't know if this is clever or should be done another way (this is why i don't create a pull requests, it works for me building Arch Linux Packages) but would you mind that something like this could be implemented in the Makefile for generating dynamic linked bins?

**Comment by MorphBonehunter** [comment]
@bradrydzewski i've hit an similar problem today with gitea and @tboerger suggests to build with build tag `netgo`.
Maybe this could also an solution (a better one as patching the Makefile :smile: ) for this case?

**Comment by bradrydzewski** [comment]
@MorphBonehunter we the netgo build tag already

This can probably be closed.  Extracting the binary from the Docker image is not recommended, and the makefile static compilation is intended for building the Docker image.

If you want to build drone for archlinux you can just run the below commands. The makefile is going away. I don't even use it locally.

```
# download deps
go get -u github.com/drone/drone-ui/dist
go get -u golang.org/x/tools/cmd/cover
go get -u github.com/jteeuwen/go-bindata/...
go get -u github.com/elazarl/go-bindata-assetfs/...

# generate code
go generate github.com/drone/drone/server/template
go generate github.com/drone/drone/store/datastore/ddl

# build binary
go install github.com/drone/drone/drone
```
