### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by Quving** [drone/drone#1944]
Hello people,

I set up my own drone-server and i noticed that my drone-server is different from the one i used at work. 
At work a build log is streamed in realtime without any refreshes required. The browser can be openend and if a build is triggered its shown. 
Despite to that i need to refresh my browser for each changes (even the build-log) 
Has somebody experienced the same behaviour like i did? 

Best regards,
Quving

**Comment by bradrydzewski** [comment]
Please direct support questions to discourse.drone.io or gitter.im/drone/drone per the issue template. Thanks!

**Comment by bkleef** [comment]
Useful discourse reference https://discourse.drone.io/t/drone-fails-to-sync-new-github-repos-via-the-api/728/8.
