### ISSUE TITLE
drone secret command not consistent with official drone.io documentation.

### ISSUE THREAD

**Issue by fdiazcobos** [drone/drone#1953]
In the documentation http://readme.drone.io/0.5/usage/secrets/

In several parts uses the unexisting command ```$drone secrets```
The correct command is ```$ drone secret``` without the final "s"

Also, if you want to skip signature verification, according to  the documentation you should put:
```$ --skip-verify=true``` but that is not working

If you use the --help in the secret command, the correct way to use it is it:
```$ --skip-verify ```without the "=true" this is working fine

**Comment by jmccann** [comment]
I think the link you are referencing is old docs.

The official docs are at http://readme.drone.io.  If you search 'secret' there you will be lead to http://readme.drone.io/cli/drone-secret-add/ which seems correct.

**Comment by fdiazcobos** [comment]
Yes, you are right I was reading "old" doc :S . But any way I think old documentation (For the current version 0.5) should be deleted, at least for me,  search engines redirects me to that web page.
Thank you @jmccann
