### ISSUE TITLE
not work docker images deploy private repo gitlab

### ISSUE THREAD

**Issue by andruwa13** [drone/drone#1960]
Hello, I have such an error denied: **access forbidden**
file **_.drone.yml_** :
pipeline:
  docker:
    image: plugins/docker
    repo: registry.gitlab.com/user/repo
    registry: registry.gitlab.com
    username: user
    password: ${REGISTRY_PASSWORD}
    email: admin@exemple.com

**_command drone cli:_**
export DRONE_SERVER=http:exemple.com
export DRONE_TOKEN=token
drone secret add /user/repo
REGISTRY_PASSWORD=’password'
drone sign /user/repo

**_git:_**

git add .
git commit -m 'new file'
git push

**_drone:_**

clone:
###########
exit code 0

docker:
##############
denied: access forbidden
exit status 1
exit code 1
P.S. drone version 0.5

**Comment by bradrydzewski** [comment]
Please use gitter or discourse for support questions, per the issue template
