### ISSUE TITLE
Support and or document Tunneling

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1968]
Support [localtunnel.me](https://localtunnel.github.io/www/) for individuals that want to test Drone and receive hooks on their local laptop or corporate firewall.

Go package:
https://godoc.org/github.com/NoahShen/gotunnelme/src/gotunnelme

Inspired by
https://github.com/agrison/harpoon

**Comment by AlekSi** [comment]
https://ngrok.com is worth supporting too.

**Comment by bradrydzewski** [comment]
Sure. Does ngrok have a Go api?

**Comment by gtaylor** [comment]
You can just download the ngrok client and point it at your local Drone socket. No integration needed.

**Comment by bradrydzewski** [comment]
The benefit of `localtunnel.me` is that you don't need an account and they provide an api. This means we could start drone with a `--localtunnel` flag and it would automatically start drone with a public address.

The goal is to help individuals evaluate and test drone locally. This issue comes up frequently enough in our support channels that an integrated solution could make sense.

There are other Go projects taking this approach:
https://github.com/agrison/harpoon

The alternative solution would be documenting ssh tunnels. The negative to ssh tunnels is that you need a public facing server. The positive is there are teams running Drone behind firewalls that GitHub cannot reach. Better support for ssh tunnels could provide these teams with a documented pattern for tunneling GitHub requests to their Drone instance.
https://blog.rodneyrehm.de/archives/38-You-may-not-need-localtunnel-or-ngrok.html

**Comment by gtaylor** [comment]
FWIW, I think ngrok only requires that you download the client. You can do many things without an account.

Only thing that would give me pause is that I'd hate to see people expecting support for this in a production setting if it was baked into core. Some of these tunneling services can be slow and the connectivity can be spotty. Webhooks may get dropped from time to time, to no fault of Drone's. Steering them to a few suggested services and having a how-to may make the separation a bit more explicit and also mean one less thing to maintain in the core.

**Comment by bradrydzewski** [comment]
agreed, closing
