### ISSUE TITLE
Gitlab / Drone - failure to parse token from hook. signature is invalid

### ISSUE THREAD

**Issue by cgebe** [drone/drone#1970]
I am using gitlab ce 8.14.5 and trying to set up drone 0.5.

As stated in #1332, gitlab is not setting up the web hook properly in this version. However by manually creating the hook: https://drone.server.com/hook/access_token=eyJhbGciOiJIUzI1NiIs... and testing it,
I get the following error from drone-server: 'failure to parse token from hook for owner/project. signature is invalid'.

I know #1332 was solved by updating gitlab to 8.2 which i cannot do, because my university provides exactly this gitlab. However the only change concerning the previous issue was the missing hook. By manually adding the hook with the access token provided under Account -> Show Token, the call should work without a problem?

**Comment by bradrydzewski** [comment]
> I get the following error from drone-server: 'failure to parse token from hook for owner/project. signature is invalid'.

You cannot setup webhooks manually. Each webhooks is cryptographically signed by Drone and cannot be generated by an end user. They can only be generated by the server when you enable the repository in the user interface.

**Comment by cgebe** [comment]
Thank you Brad for your answer! This is an unfortunate situation which my team and i are currently in. Since another build system is out of the question ;), we need to decide and hopefully get a working solution. Cheers!
