### ISSUE TITLE
Ability to only restart one matrix job

### ISSUE THREAD

**Issue by jhasse** [drone/drone#1977]
When viewing a specific matrix build job and hitting REBUILD, the build is completely restarted. It would be nice if the restart button on a specific matrix job view would only restart this particular matrix job, not all of them.

**Comment by bradrydzewski** [comment]
unfortunately we are moving in the opposite direction. Builds will be immutable and restarting a build will result in a new build number. It will therefore not be possible to restart a single matrix item for an existing pipeline.

Reference issue https://github.com/drone/drone/issues/2035
