### ISSUE TITLE
Gitea (community-driven Gogs) integration

### ISSUE THREAD

**Issue by tomsiwik** [drone/drone#1978]
Related to: http://discourse.drone.io/t/drone-0-5-and-gogs-gitea/301

Gitea's development is currently flourishing and i would be happy to see integrations/plugins for drone. Especially since Gitea is actively developing on the Oauth front and more.
'Some' improvements on the api can be found here: https://github.com/go-gitea/gitea/issues/64

See also: https://github.com/go-gitea/gitea/issues/27

**Comment by ekozan** [comment]
you have forgot the best of all : https://github.com/go-gitea/gitea/pull/1332

**Comment by bradrydzewski** [comment]
merged pull request from @appleboy. Will be included in 0.7 release
