### ISSUE TITLE
TAKEOFF drone fails because I don't use GPS, can someone help? 

### ISSUE THREAD

**Issue by nadavkehila** [drone/drone#1979]
Hi, 

I am working on Indoor drone capabilities so I don't use GPS. 
The drone fails to Takeoff although on Mission-planner I deactivated all the prior sanity checks to the GPS. 
I try to deactivate those parameter through the program i write on C++ but i am not sure how to do it.

Can someone help to a friend in need??

**Comment by bradrydzewski** [comment]
This is not an appropriate forum for uav questions
