### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by StyleT** [drone/drone#2002]
Many companies use Active Directory to manage access to different resources. Usually AD server has LDAP protocol support to work with tools like Jira/TeamCity/BitBucket/etc.. It would be great to support authentication in Drone through LDAP.

**Comment by bradrydzewski** [comment]
Drone does not handle authentication. Drone delegates authentication to the source code management system, e.g. GitHub. So when you want to login to Drone, you are redirected to GitHub to login, and then back to Drone.

Therefore if you want to login to Drone using LDAP, and Drone delegates GitHub Enterprise for login, you need to configure GitHub Enterprise for LDAP.

**Comment by tboerger** [comment]
If you are hosting your code on Gogs/Gitea or Gitlab you can use LDAP for the authentication and it works pretty good with Drone.
