### ISSUE TITLE
https://discuss.drone.io down?

### ISSUE THREAD

**Issue by sulliwane** [drone/drone#2003]
trying to open ```https://discuss.drone.io/c/how-tos``` I get:
![screenshot from 2017-04-13 17-47-32](https://cloud.githubusercontent.com/assets/1733686/24999760/60f44e78-2071-11e7-93ef-be073404ca1b.png)

**Comment by bradrydzewski** [comment]
yes, the server was shutdown. We moved to discourse.drone.io (hosted by discourse) last year
