### ISSUE TITLE
Show builds logs in CLI

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2005]
The `drone logs` command has been disabled because changes to the build logs (storing logs per step) makes this more complex. This command needs to be re-designed. This is just one possible design for how this could work ...

First, we create a new command to list the pipeline steps:

```
$ drone build ps -repo foo/bar -build 42
PID	STEP		STATE
1 	clone		success
2 	postgres	success
3 	build		failure
4 	docker		skipped
5 	slack		running
```

The pipeline step number can then be used to stream the logs for that step:

```
$ drone build logs -repo foo/bar -build 42 -pid 1

+ git init
Initialized empty Git repository in /go/src/github.com/drone/drone/.git/
+ git remote add origin https://github.com/drone/drone.git
+ git fetch --no-tags origin +refs/heads/master:
From https://github.com/drone/drone
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
+ git reset --hard -q 7e522f86a75f9ac67acbcd1e66f8548b1471bc32
+ git submodule update --init --recursive
```

**Comment by appleboy** [comment]
Could you review this PR https://github.com/drone/drone/pull/1986 first?

**Comment by vtolstov** [comment]
@bradrydzewski why not create ability to display logs from all pipelines if pid is missing?

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone/drone-cli/issues/39
