### ISSUE TITLE
Support for CLI plugins

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2006]
Support for command line plugins similar to Heroku

https://github.com/heroku/cli
https://devcenter.heroku.com/articles/developing-cli-plugins

**Comment by Dorian** [comment]
So, their main cli used to be in Ruby, now it's in Go, but plugins can be in any language, for instance this one is in Javascript https://github.com/heroku/heroku-pg

Pretty neat!

**Comment by tboerger** [comment]
For me it looks like the core is written in go but the plugins are written in Javascript.
