### ISSUE TITLE
SSL enable plugins, docs and downloads subdomains

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2031]
The subdomains are currently S3 buckets, so we'll need to use something like cloudflare [1] or move to digital ocean with caddy.

[1] https://support.cloudflare.com/hc/en-us/articles/200168926-How-do-I-use-Cloudflare-with-Amazon-s-S3-Service-

**Comment by msuterski** [comment]
@bradrydzewski Fastly hosts open source projects for free and they terminate TLS. Lots of projects are fronted by them, e.g. Hashicorp sites. 

If you're interested, we can help you our setting up the service.

**Comment by gtaylor** [comment]
Fastly is the way to go if they are offering! We are very satisfied users. Easy to park them in front of S3 buckets or web apps, and you can do some crazy stuff with VCL if you are so inclined.

**Comment by bradrydzewski** [comment]
Downloads are now served from github releases which is https

**Comment by gtaylor** [comment]
@bradrydzewski Awesome! Sounds like it might be safe to close this?
