### ISSUE TITLE
Tag semver parsing, environment variables

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2034]
For example if DRONE_TAG=v1.2.3 we could expose the following variables:

```
DRONE_SEMVER=1.2.3
DRONE_SEMVER_MAJOR=1
DRONE_SEMVER_MINOR=2
DRONE_SEMVER_PATCH=3
```

**Comment by tonglil** [comment]
If you could point to where this should be implemented, I am happy to give it a shot!

**Comment by ozbillwang** [comment]
@tonglil 

Seems this is the target file: https://github.com/drone/drone/blob/master/version/version.go

**Comment by tonglil** [comment]
@ozbillwang that is the file for managing Drone's version, not parsing the tag from the webhook payload.

**Comment by bradrydzewski** [comment]
I am closing in favor of https://github.com/drone-plugins/drone-docker/issues/150, which is the primary use case I was trying to solve. Handling this at the plugin level seems to make more sense.
