### ISSUE TITLE
Move CLI to drone-cli

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2037]
Why change back to a separate CLI repository? Some things have changed that makes this a more viable approach than it was before. 

1. the runtime is now in a separate repository that can be imported for use by drone exec
2. the drone api is stabilizing 
3. the CLI is no longer required for daily use with the removal of the signature file

There is also a lot of community interest around improving the CLI. By decoupling the CLI from the core repository I hope to achieve the following:

1. increase the pace of improvements
2. reduce the number of outstanding pull requests
3. increase the number of individuals with write access

**Comment by bradrydzewski** [comment]
I've moved drone-cli to a separate project and setup a team with write access. This includes the following individuals so far @tboerger @appleboy @jmccann @Bugagazavr . I also added @Dorian who hasn't contributed to drone yet, but is doing some interesting things with https://github.com/Dorian/drone-builds

There are some things we might want need to figure out:

1. how do we want to publish (s3 or github releases)
2. brew script will need to be updated accordingly
3. we should decide on a standard for output. For example tabular or list? We should pick one and keep things consistent so that the cli doesn't look like it was written by 10 different people 😛 
4. we should decide on error conventions
5. when to use arguments vs flags? Does `urfave/cli` support our design?

Note that everyone will have the ability to merge pull requests, however, the branches are protected, meaning that an approval will be required before merging.

**Comment by appleboy** [comment]
1. vote `github releases` 👍

**Comment by bradrydzewski** [comment]
@appleboy I'm inclined to agreed. @jmccann thoughts? Would this work with homebrew?

**Comment by bradrydzewski** [comment]
I haven't used github releases. @tboerger is this something you could help setup?

**Comment by tboerger** [comment]
I'm actively using github releases, but this works only for tags and not for "latest" builds.

**Comment by bradrydzewski** [comment]
> but this works only for tags and not for "latest" builds.

maybe this is a good thing? It will force more frequent tagging ...

**Comment by tboerger** [comment]
1) Maybe gitHub for tags and s3 for latest builds?
2) Currently a manual step, but maybe we can script something based on tagging, at least to create a PR
3) I really like the templateable list format we got
4) Keep it like it is :P
5) I personally build my cli stuf mostly on flags. But if we choose arge we must build a better help output than it's currently the case.

**Comment by jmccann** [comment]
I like @tboerger thoughts for 1 and 2.

**Comment by bradrydzewski** [comment]
ok, a few thoughts

I'm trying to eliminate my s3 dependency so we'll host the CLI downloads on github releases. I've setup the integration and published the 0.6.0 release:
https://github.com/drone/drone-cli/releases

We will tag more frequent minor versions (ie 0.6.1...N) when we need to make newer CLI versions available. Everyone in this thread has the ability to tag a new release I believe.

I feel like we don't need to publish a `latest` version of the CLI because most people interested in the latest build can probably build from source. With `/vendor` in place and with the CLI separated from drone core it becomes much easier to install from source:

```
go get github.com/drone/drone-cli/drone
```

If we decide we really need a `latest` version published we can maybe check bintray in the future?

**Comment by bradrydzewski** [comment]
@tboerger there are some CLI packages that are more optimized for args
https://github.com/alecthomas/kingpin

**Comment by bradrydzewski** [comment]
closing now that repository is moved

**Comment by Tzrlk** [comment]
Can someone quickly document the cli location on the main drone readme to avoid confusion?
