### ISSUE TITLE
Build immediately fails in drone 0.6 with "client is newer than server"

### ISSUE THREAD

**Issue by francoishill** [drone/drone#2048]
Quote of the "full" error log in the build: `ERROR: Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)`

Infrastructure is on Rancher with [CoreOS Stable](https://coreos.com/releases/) currently running docker version `1.12.6`.

Where do I start to dig deeper as to why this error happens?

**Comment by bradrydzewski** [comment]
you can set `DOCKER_API_VERSION=1.24` with the agent

http://stackoverflow.com/questions/43072703/client-is-newer-than-server-client-api-version-1-24-server-api-version-1-21

**Comment by francoishill** [comment]
Awesome, that solved it, thanks @bradrydzewski

**Comment by andrewmclagan** [comment]
To record it here:

Had this issue on Kubernetes (GCE) and the above resolved it. thanks

**Comment by appleboy** [comment]
Add `env` In k8s to fix this issue:

```yaml
        env:
        - name: DOCKER_API_VERSION
          value: "1.24"
```
