### ISSUE TITLE
'skip verify' and 'conceal' secret settings not saved

### ISSUE THREAD

**Issue by amq** [drone/drone#2050]
After creating a secret using web UI or CLI, the skip verify setting doesn't get saved

```
> drone secret add --skip-verify=true repo DOCKER_PASSWORD password
puTHTXZ7

> drone secret ls repo
DOCKER_PASSWORD
Events: push, tag, deployment
SkipVerify: false
Conceal: false
```

In web UI, the checkbox is unchecked after reloading the page

Tested on `0.6` and `latest`, both with clean volumes

The same applies to `--conceal=true`

**Comment by bradrydzewski** [comment]
Closing because `--conceal` is disabled (see release notes) and `--skip-verify` is deprecated. The commands changed in 0.6 and you can see an updated reference at http://docs.drone.io/manage-secrets/

If you have additional questions you can use gitter.im/drone/drone
