### ISSUE TITLE
Separate server and agent binaries and images

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2052]
Now that the CLI is moved to a separate repository I will propose separating the server and agent into separate binaries and publishing separate images for each. The binaries will follow the standard multi-binary layout:

```
cmd/drone-server
cmd/drone-agent
```

We will then publish images for each

```
drone/drone
drone/agent
```

The `drone/agent` does not have any CGO dependencies so we can cross-compile for armhf and arm64 and therefore distribute official images for each:

```
drone/agent:linux-arm
drone/agent:linux-arm64
```

Versioned tags would look like this:

```
linux-arm
0.6.0-linux-arm
0.6-linux-arm
```

We can probably remove `codegangsta/cli` in a subsequent release since there is really no reason to include such a heavy dependency now that the CLI is moved to a separate repository. But this is something we'll take at a later time.

**Comment by gtaylor** [comment]
With the aspirations for cross-compilation of the agent, splitting agent/server seems like the best route. :+1: 

> We can probably remove codegangsta/cli in a subsequent release since there is really no reason to include such a heavy dependency now that the CLI is moved to a separate repository.

Unless this is hurting us in some specific way, meh.

**Comment by xinity** [comment]
as both agent and server would share the same code, i don't really see the benefits of splitting.
using same image have also great advantages i think.

perhaps splitting can help making even smaller images ?

**Comment by bradrydzewski** [comment]
the major benefit of splitting is being able to compile arm / arm64 / win64 images for the agent, so that you can run a mutli-architecture setup. We cannot (at this time) compile mutli-arch server images due to its CGO dependency

**Comment by xinity** [comment]
thanks for clarification @bradrydzewski

**Comment by bkleef** [comment]
An arm64 Docker image (for at least agent) would be really helpful.

**Comment by automaticgiant** [comment]
👎  😢 
see related work in consul/nomad/vault re: cgo/multiplatform

one of my favorite things about drone and alot of golang things is that it's often one binary per platform

not sure which libs you're using through cgo. that's important i guess.
is there a way to not compile the cgo stuff (and consequently the ui i guess) on unsupported platforms? i think hashicorp does do that, but can't think of a good example. probably nomad.

yeah. i think nomad doesn't compile certain features based on platform/arch.
and keeps it simple as far as one client/server/cli binary.

**Comment by gtaylor** [comment]
> is there a way to not compile the cgo stuff (and consequently the ui i guess) on unsupported platforms? i think hashicorp does do that, but can't think of a good example. probably nomad.

This is just trading install-time complexity for build and run-time nightmares. Please, no conditional compilation with Go! We're going to see increasing requests for supporting various platforms, each with their own quirks. Let's not let that nastiness spill over into Drone Server.

**Comment by bradrydzewski** [comment]
> but i fully expect splitting up binaries/images to be an inconvenience that will increase deployment complexity unnecessarily.

I definitely understand the concern here. I do feel pretty confident that this will not cause any major inconvenience. Consider how this change will (roughly) impact how you run drone with the following example:

```diff
docker run drone/drone
-docker run drone/drone agent
+docker run drone/agent
```

And how this change would (roughly) impact compiling and running drone locally:

```diff
-go install github.com/drone/drone/drone
-drone server
-drone agent
+go install github.com/drone/drone/cmd/...
+drone-server
+drone-agent
```

Note that I personally do not run drone in containers locally. It slows down my development workflow and drone runs perfectly on osx with docker for mac. So I do not see this impacting my local development either.

There is also precedence for the multi-binary project structure within the Go community. We can see this approach used in some of the following projects:
https://github.com/camlistore/camlistore/tree/master/cmd
https://github.com/kubernetes/kubernetes/tree/master/cmd
https://github.com/golang/go/tree/master/src/cmd

So while I definitely understand the concern, and agree that we should not complicate setup and installation, I do not see this being an issue. But I do agree that IF we obverse this increasing complexity or causing problems I will be happy to revisit the decision.

Hope that helps address any concerns :)

**Comment by bradrydzewski** [comment]
merged into master
