### ISSUE TITLE
ability to specify platform requirement in matrix builds

### ISSUE THREAD

**Issue by cyberb** [drone/drone#2053]
I need to build apps one per platform (arm,x86).
Right now even if I run agents on multiple platforms I cannot override platform requirement using matrix variable (as well as plugin image names)
I am migrating from TeamCity where I can create separate build configurations with corresponding arch requirements.
I understand that TeamCity is java and all the plugins just work so it is a bit simpler.

**Comment by bradrydzewski** [comment]
drone supports a platform attribute:

```
platform: linux/amd64
```

which can be used in a matrix build:

```
platform: ${platform}
matrix:
  platform:
    - linux/amd64
    - linux/arm
```

when you configure the agent you can provide it with the platform parameter that can be used to filter which jobs it can receive:

```
DRONE_PLATFORM=linux/amd64
```

if you have further questions feel free to use the support channel at https://gitter.im/drone/drone
