### ISSUE TITLE
[Feature Request] ability to re-enable repo if it was disabled

### ISSUE THREAD

**Issue by josmo** [drone/drone#2058]
Sometimes builds get disabled and there's no simple way to re-enable and get the past history and next build.

It would be great to have the ability to re-enable a past repo and have the build history come back. Right now it looks like it keeps it in the database but when enabling it just creates a "new" project.

@bradrydzewski this is another one I'm down to take a stab at if you think it's worth it and have an idea of the best way to do it.

**Comment by bradrydzewski** [comment]
check out http://docs.drone.io/cli-repository-repair/ :)

**Comment by josmo** [comment]
@bradrydzewski I was meaning when you disable builds from drone in the accounts tab.  Then when you re-enable it loses the history (even though it's still in the db) and starts the build over.

**Comment by bradrydzewski** [comment]
Ah ok, this will be resolved with https://github.com/drone/drone/issues/2036

**Comment by josmo** [comment]
Ah sweet! Good to know
