### ISSUE TITLE
Configurable Session/Token Timeout

### ISSUE THREAD

**Issue by talon-hartmann** [drone/drone#2066]
We recently upgraded to Drone 0.7 and are generally happy with the improvements, but an issue still remains: The session token expiration seems to be hardcoded at 72 hours in two places:

https://github.com/drone/drone/blob/240f2a8ec520003a6c7a66a7236a742d4d665a06/server/login.go#L103

https://github.com/drone/drone/blob/240f2a8ec520003a6c7a66a7236a742d4d665a06/server/login.go#L143

As a drone admin, I often get complaints from developers that they find themselves logged out when clicking on a Drone status link going to Drone in our slack etc. 

An acceptable way to address this would be to offer an ENV variable to specify the number of expiration hours. Apparently, such an option existed at one point, as referenced in https://github.com/drone/drone/issues/609#issuecomment-60192587

**Comment by bradrydzewski** [comment]
implemented by #2170
