### ISSUE TITLE
Migrate Gitlab API client to API V4

### ISSUE THREAD

**Issue by thomasf** [drone/drone#2068]
API V3 will be removed in GitLab 9.5, to be released on August 22, 2017.

https://docs.gitlab.com/ce/api/v3_to_v4.html

**Comment by thomasf** [comment]
This is just a month away now.. 

It would be nice if maybe there was docker compose files in the contrib dicrectory (or maybe a separate drone-dev-kit or drone-gitlab-dev-kit repo) which sets up a gitlab install for local development with drone,.. Currently everyone that wants to hack on gitlab API stuff has to do it by themselves.

This is personally a much larger metal blocker for starting the work than the actual API migration work itself. From what I have seen there is no clear indication how people who develop drone "core" integration practically do that work.

Actual integration tests against gitlab would of course also be nice but that's a larger task.

**Comment by vanadium23** [comment]
Hello, @bradrydzewski @thomasf.
I'd like to work on this issue, because previously contributed to gitlab API and want to see how it worked from client side view.

**Comment by thomasf** [comment]
I got stuck on a few details while setting up my development environment last time I wanted to work on this so I didn't actually write any code. This should probably be fixed soonish, I might have another go at it soon again if time allows.

**Comment by thomasf** [comment]
this issue closes https://github.com/drone/drone/issues/2068 

btw. Gitlab decided to keep the v3 api around a bit longerbecause they had too many v3 api requests to their site.. So latest gitlab still works with drone which is good

**Comment by bradrydzewski** [comment]
closed by #2126
