### ISSUE TITLE
Self-host all HTML/CSS/JS assets

### ISSUE THREAD

**Issue by jacksgt** [drone/drone#2069]
Hi,

currently the the Drone Web UI fetches various assets from code.getmdl.io
This is fine for most people, however the administrator might want to disable this feature.

Use cases include running a Drone (and Gitlab/Gitea/...) instance in internal, private network without access to the internet.

Gitea for example has an [Offline Mode](https://docs.gitea.io/en-us/config-cheat-sheet/#server-server) which disables use of CDN for static files.

**Comment by bradrydzewski** [comment]
tracking https://github.com/drone/drone-ui/issues/32
