### ISSUE TITLE
Squash drone/drone PRs

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2073]
What do you think about turning on squash merging on GitHub of PRs?

With good PR titles, it would help in parsing through the [change log](https://github.com/drone/drone/compare/v0.6.0...v0.7.1) to identify what happened by removing possibly noisy commit messages.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/3250776/27106791-ec37e2ee-5062-11e7-9cf9-404aa2b4a03c.png">

**Comment by bradrydzewski** [comment]
done! just enabled those flags on drone

**Comment by tonglil** [comment]
Thank you!
