### ISSUE TITLE
RFC: Add debugging for VCS connection

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#2077]
Drone should expose an admin view that exposes any cases where its webhook could not be serviced.

For first time users if they trigger a build and receive no feedback they are unsure of where to begin debugging. This is a pretty consistent query on Gitter.

Additionally we had an issue where Drone's database was not configured for UTF8 and this would cause 500s when emoji were used in a PR title. There was no indication within Drone that a webhook was received but was unable to be processed.

**Comment by bradrydzewski** [comment]
this was fixed in 0.6 :) we now show an error in the UI when this happens
