### ISSUE TITLE
[QUESTION] drone docker image ports

### ISSUE THREAD

**Issue by pantocrator27** [drone/drone#2081]
Is it really necessary for the drone docker image to export 80, 443, 8000?  Based on the documentation everything is mapping to 8000 inside the container.

**Comment by jhernandezme** [comment]
I think that the may reason of exporting 80, 443 along with 8000 is the support for automated ssl with let's encrypt, lets say you want it directly and not behind a proxy. 

http://docs.drone.io/configure-lets-encrypt/
