### ISSUE TITLE
Add version info in Drone webpage

### ISSUE THREAD

**Issue by ogarcia** [drone/drone#2084]
Is possible add a page footer (or in account section under of sync list) that shows Drone version?
Something like in [Gogs](https://try.gogs.io/) that says `© 2017 Gogs Versión: 0.11.22.0621`

**Comment by bradrydzewski** [comment]
I will add to the html document in a meta tag

```
<meta name="version" content="0.7.3-build.1121">
```

In the mean time, you can determine your drone version by looking at the http request, which will have an `X-Drone-Version` http header with the current version number.

**Comment by vanadium23** [comment]
@bradrydzewski but in footer will be friendlier to user, can I add it?

**Comment by bradrydzewski** [comment]
the application does not have a footer at this time. This would require layout and design changes, which I would like to avoid. Meta tag is the best option at the moment.

**Comment by tboerger** [comment]
Some people might say that displaying the version unauthorized is some security risk at all. So maybe it's even better to drop the header and add some metadata page for authenticated users?

**Comment by vanadium23** [comment]
For unauthorized user?

**Comment by tboerger** [comment]
User that aren't authenticated. You don't want to show the used version to everyone

**Comment by bradrydzewski** [comment]
closed by https://github.com/drone/drone/commit/eb1dc3a3a8374e3d1e5c64ebe9b9e89440744409
