### ISSUE TITLE
Add support for "Cron Jobs"

### ISSUE THREAD

**Issue by ogarcia** [drone/drone#2086]
Like in Travis CI, it would be a good idea that you can set periodics builds without make changes in repository.

**Comment by bradrydzewski** [comment]
see the related issue https://github.com/drone/drone/issues/1525 and instructions http://readme.drone.io/questions/how-to-schedule-builds/

**Comment by mattcopas** [comment]
@bradrydzewski The above docs link (and in other related issues) is broken. Is there an updated version of this?

**Comment by StoneJia** [comment]
> @bradrydzewski The above docs link (and in other related issues) is broken. Is there an updated version of this?

https://readme.drone.io/config/cron/ may work.
