### ISSUE TITLE
Got an internal_error after auth Gitlab

### ISSUE THREAD

**Issue by ZongliangLee** [drone/drone#2101]
version : latest, 0.7
I follow the official installation guide to build the drone server.
Run docker using the following variables

> #!/bin/bash
> docker run -d \
>   --dns {MY_OWN} \
>   -e DRONE_GITLAB=true \
>   -e DRONE_GITLAB_CLIENT={FROM_GITLAB} \
>   -e DRONE_GITLAB_SECRET={FROM_GITLAB} \
>   -e DRONE_GITLAB_SKIP_VERIFY=true \
>   -e DRONE_GITLAB_URL=https://{PRIVATE_GITLAB}.com \
>   -e DRONE_SECRET=0 \
>   -e DRONE_OPEN=true  \
>   -e DRONE_ADMIN={USER_NAME}  \
>   -v /var/lib/drone:/var/lib/drone \
>   -P \
>   --restart=always \
>   --name=drone_latest \
>   drone/drone:latest

**And I can login my Gitlab successfully, but after I press the green access button.**

![image](https://user-images.githubusercontent.com/15358211/27939417-0fdf33f4-62f7-11e7-9df2-a64e484fa51f.png)

**It show me an interal_error**

![image](https://user-images.githubusercontent.com/15358211/27939474-7931a5d0-62f7-11e7-8c05-de4e6d07c907.png)

**Here is my log:**

```
eddler.Targets: column [user_remote] not found in struct
meddler.Targets: column [user_access] not found in struct
meddler.Targets: column [user_name] not found in struct
meddler.Targets: column [user_gravatar] not found in struct
meddler.Targets: column [user_syncing] not found in struct
meddler.Targets: column [user_created] not found in struct
meddler.Targets: column [user_updated] not found in struct
meddler.Targets: column [user_synced] not found in struct
meddler.Targets: column [user_access_expires] not found in struct
meddler.WriteTargets: column [user_remote] not found in struct
meddler.WriteTargets: column [user_access] not found in struct
meddler.WriteTargets: column [user_name] not found in struct
meddler.WriteTargets: column [user_gravatar] not found in struct
meddler.WriteTargets: column [user_syncing] not found in struct
meddler.WriteTargets: column [user_created] not found in struct
meddler.WriteTargets: column [user_updated] not found in struct
meddler.WriteTargets: column [user_synced] not found in struct
meddler.WriteTargets: column [user_access_expires] not found in struct
time="2017-07-07T01:24:23Z" level=error msg="cannot update bob.li. meddler.Update: DB error in Exec: no such column: user_expiry" 
meddler.Targets: column [user_remote] not found in struct
meddler.Targets: column [user_access] not found in struct
meddler.Targets: column [user_name] not found in struct
meddler.Targets: column [user_gravatar] not found in struct
meddler.Targets: column [user_syncing] not found in struct
meddler.Targets: column [user_created] not found in struct
meddler.Targets: column [user_updated] not found in struct
meddler.Targets: column [user_synced] not found in struct
meddler.Targets: column [user_access_expires] not found in struct
meddler.WriteTargets: column [user_remote] not found in struct
meddler.WriteTargets: column [user_access] not found in struct
meddler.WriteTargets: column [user_name] not found in struct
meddler.WriteTargets: column [user_gravatar] not found in struct
meddler.WriteTargets: column [user_syncing] not found in struct
meddler.WriteTargets: column [user_created] not found in struct
meddler.WriteTargets: column [user_updated] not found in struct
meddler.WriteTargets: column [user_synced] not found in struct
meddler.WriteTargets: column [user_access_expires] not found in struct
time="2017-07-07T01:31:43Z" level=error msg="cannot update bob.li. meddler.Update: DB error in Exec: no such column: user_expiry" 
```

**Comment by bradrydzewski** [comment]
Please use gitter.im/drone/drone for support

**Comment by davecozz** [comment]
@bradrydzewski perhaps it would be beneficial to add a CONTRIBUTING.md file so that potential contributors know what is expected? https://help.github.com/articles/setting-guidelines-for-repository-contributors/ 

I'd be happy to make a PR if that would help.

**Comment by bradrydzewski** [comment]
@davecozz can you take a look at our issue template?

**Comment by davecozz** [comment]
Ah, I see you have some instructions in there already. A big yellow banner *might* help weed out a little more noise but if people are already ignoring instructions, who knows.  ¯\\\_(ツ)\_/¯
