### ISSUE TITLE
Does not create web hooks with Bitbucket Server v4.13.0

### ISSUE THREAD

**Issue by delfer** [drone/drone#2109]
**Drone 7.3** from **docker** hub
Configured to use Bitbucker server (stash) v4.13.0. 
I can login to Drone using Bitbucket account (oAuth), see repositories and can enable them.
But:
- Drone does not create hooks
- Drone not building after push/pr/tag etc
![01-no-hooks](https://user-images.githubusercontent.com/3233181/28109715-b9e08966-66f8-11e7-8084-a503ea70e1a3.png)

**DEBUG** enabled on both server and agent - no one error. Just access logs and 
`level=debug msg="delfer granted &{Pull:true Push:true Admin:true} permission to ACH/drone-with-java"`

**Comment by bradrydzewski** [comment]
https://github.com/drone/docs/issues/223

**Comment by delfer** [comment]
Thank you!
