### ISSUE TITLE
could not read Username ... No such device or address with Bitbucket Server v4.13.0

### ISSUE THREAD

**Issue by delfer** [drone/drone#2110]
**Drone 7.3** from **docker** hub
Configured to use Bitbucker server (stash) v4.13.0. 
It detects changes, starts building, react to errors in **.drone.yml** but stucks with error:

```
+ git init
Initialized empty Git repository in /drone/src/git.DOMAIN/projects/ACH/repos/drone-with-java/commits/178f4f482242795de461c7d4ccd8359fb34e03d6/.git/
+ git remote add origin http://git.DOMAIN/scm/ach/drone-with-java.git
+ git fetch --no-tags origin +refs/tags/buildItNow:
fatal: could not read Username for 'http://git.DOMAIN': No such device or address
exit status 128
```

I think server can access (detects problemns in **.drone.yml**) but agent not (can't clone).

Used copy of https://github.com/drone-demos/drone-with-java with add pipeline in **.drone.yml**

**Comment by bradrydzewski** [comment]
this is generally a network configuration issue and not a drone issue. Per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), please triage issues in our community support channel before creating github issues.
