### ISSUE TITLE
Display build steps before execution

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2113]
Sometimes you are trying to debug a build configuration, but you're not sure which steps get triggered by that action.

It would really nice at the top of the drone build if it showed "which" pipeline steps "qualify" for this drone build. Sometimes the jobs are really long so it would be nice to see what the pipeline looks like without waiting for the entire pipeline to execute.

This would also allow gated builds reviewers to have an easy understanding of what steps this gated build will run.

**Comment by bradrydzewski** [comment]
lets track this as https://github.com/drone/drone/issues/1857

note that this is mostly implemented in branch for the 0.8 version of the user interface https://github.com/drone/drone-ui/tree/exp/polymer2 :)

**Comment by tonglil** [comment]
Oh wow, I missed that in my search.
Thank you! :)

**Comment by bradrydzewski** [comment]
unfortunately I don't have a better screenshot at the moment, but the user interface will display all steps when the build starts. Steps that are pending (to be executed in the future) will have the little clock next to them

<img width="968" alt="screen shot 2017-07-13 at 5 22 52 pm" src="https://user-images.githubusercontent.com/817538/28228901-714ba52a-68ae-11e7-8df1-e47be2cbf85f.png">

**Comment by tonglil** [comment]
That looks perfect!
