### ISSUE TITLE
[Bitbucket server] Drone CLI not working with upper-case user's names

### ISSUE THREAD

**Issue by delfer** [drone/drone#2115]
> Bugs or Issues? Please do not open a GitHub issue until you have
> discussed and verified in our chatroom:
>     https://gitter.im/drone/drone

No answer.

> $ drone --version
> drone version 0.7.0

> drone registry add --repository ACH/drone-with-java --hostname *** --username ***--password ***
> json: cannot unmarshal array into Go value of type drone.Registry

The same with quotes
> $ drone registry add --repository 'ACH/drone-with-java' --hostname *** --username *** --password ***
> json: cannot unmarshal array into Go value of type drone.Registry

> $ drone registry add --repository "ACH/drone-with-java" --hostname *** --username *** --password ***
> json: cannot unmarshal array into Go value of type drone.Registry

And **repository** is  case-sensitivity
> $ drone registry add --repository ach/drone-with-java --hostname *** --username *** --password ***
> client error 404:

**Comment by bradrydzewski** [comment]
I am closing as I am unable to repeat. The below CLI commands work for me as expected

```
drone registry add \
  --repository=foo/bar \
  --username=foo \
  --password=bar \
  --hostname=foo.com
```

If you continue experiencing issues please consider sending a pull request
