### ISSUE TITLE
pluggable runtime engines (Nomad, etc)

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2116]
This issue is being created based on comments in #1815

https://github.com/drone/drone/issues/1815#issuecomment-313897565
https://github.com/drone/drone/issues/1815#issuecomment-315936727

The tldr is that there is interest in using alternate runtime engines (alternate to docker) such as nomad, kubernetes and more. This issue will focus on creating the necessary abstractions and enabling plugins (using the [plugins](https://golang.org/pkg/plugin/) package).

This may turn into a meta issue, since we will need to gather requirements for nomad, kubernetes, and we may want to also consider native builds (no containerization) to support platforms like osx and ios.

This discussion may also result in new yaml formats. It is possible the current yaml format (which we will not break) cannot sufficiently represent pipeline definitions for alternative runtime engines. _Please note_ this is not an open invitation to re-design the yaml just because.

**Comment by automaticgiant** [comment]
so i guess the foundational bit is to figure out what kind of things are pipeline primitives, and how far into dag-workflow stuff we want to go. for the record, ordered batch job dependencies (read: pipeline stages) have been mentioned as roadmap for nomad, but not positive that they want to do that or have it be an external integration. I'm looking at Airflow for complex stuff(platform mgmt), but the simple pipeline model(and yaml) that drone has now, certainly can be made to leverage Nomad jobspec(s), which is especially important in a nomad deployment where you don't want drone to control a whole docker daemon, and have the primary scheduler blind to its resource consumption. (Airflow could also be a target, if you basically want to use Drone as a VCS/webhook/build-controller driver to Airflow/x, which would be cool). But I really like the simple declarative pipeline config that Drone has now.

so there are pipeline stages, which could be nomad batch jobs of single tasks, or single task groups. k8s could have non-longrunning pods (maybe idk) as stages, longrunning pods/jobs or nomad services could implement existing service functionality.

the weird thing is how does the networking work. i think that pod networking is more complex, so not sure how that plays. maybe if we abstract right, they just refactor for nomad/k8s/lambda/ecs/swarm/airflow, and we don't have to make it 1:1 compatible.

if we include hcl jobspec or whatever other backend native declarative format into the yaml in fields or some other way, like conversion of native format into yaml as sub-object, maybe we can leverage full expressivity of each backend's functionality and configuration patterns.

the drone pipeline/webhook/cli/dash/secrets would be a great thing to hook up to a (currently) simple scheduler like Nomad, or more complicated workflow system like Airflow.

**Comment by bradrydzewski** [comment]
I am going to close this because the drone runtime has been moved to its [own package](https://github.com/drone/drone-runtime) and fully supports plugins. That means if someone wants a custom engine (nomad, etc) it can be created and plugged-into drone using dynamic linking. No need to compile a custom version of Drone or publish a custom Drone image.

Plugin documentation:
https://github.com/drone/drone-runtime#runtime-engines

Plugin package:
https://github.com/drone/drone-runtime/tree/master/engine/plugin

For anyone interested in this capability, the first step is to create an external plugin for the desired runtime engine. Such a plugin would not immediately be accepted into the drone core codebase. Instead it should be incubated as a community plugin. After an incubation period (6 months) we can consider adding to drone core.

**Comment by tboerger** [comment]
This is a great step to be pluggable!
