### ISSUE TITLE
[Docs Request] Docs for Contributing 101

### ISSUE THREAD

**Issue by Adron** [drone/drone#2127]
I've RTFMed out the [installation](http://docs.drone.io/installation/) instructions and [help](http://docs.drone.io/installation-help/) docs. Since I've also been interested in contributing I've been checking out the [Github Issues](https://github.com/drone/drone/issues) and thought that having some documentation around getting started from a documentation perspective would be super helpful. Something, when one is asking to dive into assist with things, could read over quickly to get started.

## Topics Would Include:

* Cloning the Drone.io Repository.
* Getting a successful Drone.io build.
* Knowing the architecture of the Drone.io build.
* Setting up the environment for testing.
* Submitting a [Feature Request] with a Github Issue. (i.e. the details, what it is, why, how it would affect others/projects, what benefits it would provide)
* Submitting feature code pull request. (i.e. prereqs, what should be included, the code, proven tests, etc)

**Comment by bradrydzewski** [comment]
thanks for the feedback! moved to https://github.com/drone/docs/issues/224
