### ISSUE TITLE
[Docs Request] Automation of Drone.io Environments

### ISSUE THREAD

**Issue by Adron** [drone/drone#2128]
A lot of the work I've been doing lately involves automating the creation and deployment of Drone.io itself, and then the deployment of apps with Drone.io. In turn, I'd like to contribute a section on ways to automate the creation and deployment of Drone.io. Specifically, deployment via tooling like Terraform or even creation of settings, users, or other elements of Drone.io once Terraform has created and environment for and with Drone.io.

## Topics Would Include:

* Deploying Drone.io with Terraform in GCP/AWS/Azure (where to find details, what steps to take, various options, etc)
* Deploying Drone.io User Accounts, Repositories, etc via Terraform.
* Deploying Drone.io Builds for Repositories based on ... X Y Z topic TBD.

**Comment by bradrydzewski** [comment]
thanks for the the feedback :)  moved to https://github.com/drone/docs/issues/225
