### ISSUE TITLE
API scopes for personal tokens

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2130]
moved from https://github.com/drone/drone/issues/1812#issuecomment-253182687

> I don't mind having a real github user and then using drone to generate JWTs with different scopes. Would that be possible?

yes, I think this would be a good compromise.

you can find the token code here:
https://github.com/drone/drone/blob/master/shared/token/token.go

we could do something like this:

``` diff
type Token struct {
    Kind string
    Text string
+   Scope []string // []string { "repo:read", "repo:write", "repo:admin" } ???
+   Repos []string // []string { "drone/drone", "drone/docs" }
}
```

Defining a set of scopes will be a bit of a challenge since I'm not sure how granular we want to get, so perhaps we can split this into phases. The first phase could be to add Repos. If the Repos slice is empty we can assume there are no restrictions. Otherwise if the repos slice is not empty we match the current repo to the contents of the slice.

Once we have this working, we can get an RFC together with some fine-grained scopes. We should be able to solicit community input for this to make sure we have all of our bases covered.

**Comment by ogarcia** [comment]
@bradrydzewski I think that the most common is this case:

Have a shared repository where work several people and you want to (for example) program some automatic builds into cron using drone-cli. At this moment you must use your own personal key with your permissions to make the calls with cli that is some insecure.

I think that the first approach is simply have API keys for access respository/pipeline.

**Comment by bradrydzewski** [comment]
0.9 introduces a concept of machine accounts which will be helpful. It also includes cron :)

**Comment by bradrydzewski** [comment]
machine accounts introduced in latest release (as well as native cron).
