### ISSUE TITLE
The new UI in version 0.8 does not integrate with browser password manager in login form in Chromium

### ISSUE THREAD

**Issue by ogarcia** [drone/drone#2135]
In version 0.8 the new login form does not integrate with browser password manager. It not autocomplete user and password and, in a clean browser, does not ask for save login data.

Tested with Chromium Versión 59.0.3071.115. With Firefox seems work well.

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone/drone-ui/issues/131
