### ISSUE TITLE
default some columns to utf8mb4

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2144]
We often see mysql databases created with the latin1 character set which fail to handle certain languages and special character sequences like emojis. Instead of relying on this to be configure correctly, we should probably just force a subset of drone fields to use the correct character set.

We should probably set a default for the commit title and message, at a minimum.

```sql
build_message VARCHAR(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_ci
```

**Comment by yangwenmai** [comment]
Maybe we should be exec this sql :
```sql
ALTER TABLE `builds` MODIFY COLUMN `build_message` VARCHAR(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```
