### ISSUE TITLE
Drone server failed to unmarshal webhook payload from Gogs (labels are present)

### ISSUE THREAD

**Issue by tkushnir** [drone/drone#2154]
Steps to reproduce:
1. Create PR with labels.
2. See drone-server logs. These errors are found there in my case:
```
drone-server_1  | time="2017-08-07T06:00:10Z" level=error msg="failure to parse hook. json: cannot unmarshal object into Go struct field .labels of type string" 
drone-server_1  | time="2017-08-07T06:00:10Z" level=error msg="Error #01: json: cannot unmarshal object into Go struct field .labels of type string\n" ip=89.188.125.8 latency=16.784072ms method=POST path="/hook" status=400 time="2017-08-07T06:00:10Z" user-agent=GogsServer
```
3. See "labels" section of payload (can be found in webhook edit page in Gogs). In my case:
```json
    "labels": [
      {
        "id": 268,
        "name": "component/library",
        "color": "7614de",
        "url": ""
      }
    ],
```

It seems like drone webhook processing function works incorrectly, somewhere around [this](https://github.com/drone/drone/blob/c8313f8cd8b398becaa46563121a4c5526b1081a/server/hook.go#L324) line.
Gitter discussion is [here](https://gitter.im/drone/drone?at=59887a8845fc670746015e41).

**Comment by tkushnir** [comment]
@bradrydzewski: please, comment on this.

**Comment by bradrydzewski** [comment]
This issue is probably this line. AFAIK it is not even used, and could probably just be removed.
https://github.com/drone/drone/blob/master/remote/gogs/types.go#L58

**Comment by mxmehl** [comment]
I have the exact same error with [Gitea](/go-gitea/gitea) (Gogs fork). The error is consistently only showing with PRs having labels.

Gitea v1.4.0, Drone 0.8.5. Please let me know if you need more data or tests.

**Comment by bradrydzewski** [comment]
I think we are waiting on a patch. This is not something I'm actively working on, so the best way to resolve is to send a pull request.
