### ISSUE TITLE
Logs intermittently stop working in the UI

### ISSUE THREAD

**Issue by rochdev** [drone/drone#2156]
The following error is displayed in the console:

```
Uncaught TypeError: Cannot read property 'full_name' of undefined
    at subscribeLogs (drone-app.html:20943)
    at drone-app.html:21390
```

Drone 0.8.0-rc3 on GKE
Chrome 60 on OS X Sierra

**Comment by bradrydzewski** [comment]
moved to https://github.com/drone/drone-ui/issues/142 (we track UI issues in the UI repository)
