### ISSUE TITLE
The UI intermittently stops working in the build view

### ISSUE THREAD

**Issue by rochdev** [drone/drone#2157]
The following error appears in the console:

```
GET https://drone.asgard.8d.com/stream/events 504 ()
```

After which the UI stops updating and does not respond to clicking on the different steps.

Drone 0.8.0-rc3 on GKE
Chrome 60 on OS X Sierra

**Comment by bradrydzewski** [comment]
same root cause as identified in https://github.com/drone/drone/issues/2159, where reverse proxy is timing out server sent event connection.
