### ISSUE TITLE
Builds page must be refreshed for changes to appear

### ISSUE THREAD

**Issue by rochdev** [drone/drone#2159]
When new builds are triggered, the builds page does not display them until the page is refresh.

Expected behaviour: the builds page should be responsive when events happen on the server

**Comment by frebib** [comment]
Only sometimes, I find that on occasion the page will update on it's own

**Comment by bradrydzewski** [comment]
Live updates definitely work. The most common problem we see are network configations that break server sent events due to buffering, timeouts and killing connections. If you are using a vpn, load balancer, reverse proxy, etc you need to configure in a way that supports SSE

**Comment by rochdev** [comment]
@bradrydzewski Do you have an example for nginx? The only thing between my machine and drone are a GCE TCP load balancer and an nginx ingress controller. The documentation only explains how to make websockets work which if I understand correctly is no longer valid for 0.8

**Comment by bradrydzewski** [comment]
Check out https://github.com/drone/docs/issues/230

**Comment by rochdev** [comment]
Wouldn't using websockets instead alleviate this problem since they have built-in support by most reverse proxies including nginx?

**Comment by rochdev** [comment]
Most websockets libraries also come with fallbacks for companies which may have a proxy that refuses websockets such as long and short polling.

**Comment by bradrydzewski** [comment]
I replaced websockets with server sent events because http/2 does not support websockets, and version 0.8 begins taking advantage of http/2 connections for grpc and includes experimental quic support.

**Comment by rochdev** [comment]
My understanding is that this is for the communication between the server and agents and not between the client and the server if I'm not mistaken. Also, supporting both would be more flexible until SSE has wider support. Right now we are a bit stuck since we don't have full control on our nginx proxy which is managed by a Kubernetes ingress controller.

**Comment by bradrydzewski** [comment]
drone serves http requests (api and asset) using http2 and quic.

<img width="578" alt="screen shot 2017-08-10 at 2 29 26 pm" src="https://user-images.githubusercontent.com/817538/29192988-670b9752-7dd8-11e7-9634-b382aed4c44b.png">

**Comment by rochdev** [comment]
@bradrydzewski Is the fact that `/events/stream` does not automatically reconnect on timeout also due to a bad configuration on the server side? It feels like this should be handled by the client.

**Comment by bradrydzewski** [comment]
The client does automatically reconnect. This is handled automatically by the browser, although I am not sure how the browser handles various error codes.

When I stop my server I can see the SSE connection break, and the browser attempts to reconnect infinitely. Once I restart my server I see the SSE connection re-established and the live updates resume.

<img width="772" alt="screen shot 2017-07-31 at 3 23 29 pm" src="https://user-images.githubusercontent.com/817538/29195757-f829853a-7de4-11e7-813c-922656fd1f20.png">

**Comment by rochdev** [comment]
In my case the connection is ended with a 504 Gateway Timeout since the server times out after 1 minute. Even though I will increase this, I would expect the stream to still reconnect after the timeout.

Since it's not a network error and more of a somewhat graceful disconnection, is it possible it's not handled by the browser?
