### ISSUE TITLE
Allow substitution to matrix variable

### ISSUE THREAD

**Issue by cedk** [drone/drone#2164]
My main use case is that the Python docker image have the form "python:3.5" but for the tox build system they have the form "py35". So for now I have to use the 'include' close to define two variables but it will be great if I could have a PYTHON_VERSION=3.5 and use ${PYHTON_VERSION/.//}

**Comment by tboerger** [comment]
Are you sure that http://docs.drone.io/substitution/#string-operations doesn't work for matrix variables?

**Comment by cedk** [comment]
Sorry my bad, when I tried the first time, I did not notice that I made a mistake in the expression.
