### ISSUE TITLE
[Feature Request] Ability to change the name of a current project/repo

### ISSUE THREAD

**Issue by josmo** [drone/drone#2167]
Allow changing the name of an org or repo name.

This seems like a good candidate for the cli. Something allow the lines of
```
drone repo update --full-repo-name=newproj/supercat1 proj/supercat
```
would move the repo to the new name.

@bradrydzewski I'm not sure if this is really feasible but I'm willing to give it a go.
from what I can tell critical things would include

in the repo table - repo_owner, repo_name, repo_full_name
  *unknowns- repo_link, repo_clone
in the builds table -
  * unknowns if it even matters but build_link, build_remote (I doubt these would matter nearly as much as the ones in the repo table)

**Comment by josmo** [comment]
is that something the repair hook would handle?

**Comment by bradrydzewski** [comment]
drone now stores the unique repository ID (from github, bitbucket, etc) in the database so that it can automatically detect repository name changes and update accordingly.
