### ISSUE TITLE
Feature Request - block/pause step

### ISSUE THREAD

**Issue by ozbillwang** [drone/drone#2169]
Start from this discussion in gitter, but don't feel that's a nice solution

>@bradrydzewski Another basic requirement. I need to run terraform plan (dry-run, similar as ansible option --check) first, block/pause this pipeline, review the logs, if everything goes well, I'd like to click a confirm button or input y/n to run next step terraform apply to apply the change or give up. How to set the pipeline in drone? Seems I can't find a block step.

>Brad Rydzewski @bradrydzewski Aug 16 10:15
drone doesn't have block steps. Instead we have deployments / promotions http://docs.drone.io/deployments/
a pipeline finishes, and then you can promote it
so for example, your build would complete, and then you could promote the build. This will kick off a new execution, during which you could run terraform apply

Can I ask for a feature to have a `block step`, which I can click in UI (or enable via drone cli) to easily control the following steps?

**Comment by bradrydzewski** [comment]
we have an open issue for this. https://github.com/drone/drone/issues/1512 for updates

**Comment by ozbillwang** [comment]
Thanks for the updates. I will follow that issue.
