### ISSUE TITLE
unable to access 'http://172.16.1.11:3000/root/go.git/'

### ISSUE THREAD

**Issue by Penglq** [drone/drone#2172]
+ git init

Initialized empty Git repository in /go/src/root/go/.git/

+ git remote add origin http://172.16.1.11:3000/root/go.git

+ git fetch --no-tags origin +refs/heads/master:

fatal: unable to access 'http://172.16.1.11:3000/root/go.git/': Failed to connect to 172.16.1.11 port 3000: Operation timed out

exit status 128

**Comment by bradrydzewski** [comment]
For usage support please ask your question at https://gitter.im/drone/drone
