### ISSUE TITLE
Substitution replace '/'

### ISSUE THREAD

**Issue by grin0c** [drone/drone#2177]
Hi. The name of the tag is 'dev/0.0.1'. How to use "Substitution" to replace '/' with '-'?
I need from 'dev/0.0.1' to 'dev-0.0.1'. I tried ${DRONE_TAG/\//-/} but it doesn't work.
P.S. I wrote in the gitter I didn't get the answer

**Comment by bradrydzewski** [comment]
the substitution syntax is `${stringZ/\//-}`

there is an example in the unit tests for this exact scenario
https://github.com/drone/envsubst/blob/master/eval_test.go#L172

going forward please use https://gitter.im/drone/drone for questions. Even if you do not get an initial response you should re-ask the question there.
