### ISSUE TITLE
Colourful output is not rendered correctly in Firefox

### ISSUE THREAD

**Issue by mprasil** [drone/drone#2178]
I'm using drone 0.8.0-rc3

Colourful output is not rendered correctly in Firefox while the same output is rendered fine in Chromium. I'm using latest FF 55.0.2, disabled all ad-blockers and such. I remember colourful output worked just fine in the previous releases, so perhaps some change in 0.8.0 broke it?

**Comment by bradrydzewski** [comment]
duplicate of https://github.com/drone/drone/issues/939

**Comment by mprasil** [comment]
Hi @bradrydzewski I feel like the issue is slightly different as I don't see any ANSI sequence - it's just the output is not coloured. (minor nitpick, I know)
