### ISSUE TITLE
Follow in Firefox doesn't follow the log output

### ISSUE THREAD

**Issue by mprasil** [drone/drone#2179]
When I enable following in Firefox while the job is running, browser doesn't follow the log output - in fact instead of scrolling to the end of the stream, it seems so "jump" to the top of the page. 

Drone 0.8.0-rc3
Firefox 55.0.2

All works as expected in Chromium

**Comment by bradrydzewski** [comment]
duplicate of https://github.com/drone/drone-ui/issues/140

**Comment by mprasil** [comment]
Apologies for that @bradrydzewski, do we report all UI bugs under drone-ui?
