### ISSUE TITLE
Caddy needs to have disabled compression for /stream

### ISSUE THREAD

**Issue by mprasil** [drone/drone#2180]
Hi,
Documentation might need a small update for caddy reverse proxy configuration. I had to disable gzip compression for /stream/, otherwise live updates wouldn't get through to browser. (caddy is probably trying to cache a bit of output and waits for the GET to finish)

This configuration seems to be working correctly:
```
drone.mycomopany.com {
+    gzip {
+        not /stream/
+    }
    proxy / localhost:8000 {
        websocket
        transparent
    }
}
```

**Comment by bradrydzewski** [comment]
please open or send a PR to https://github.com/drone/docs

perhaps it makes sense, per the issue template, to use https://gitter.im/drone/drone to discuss before creating issues so we can direct you to the appropriate location, or existing issues.
