### ISSUE TITLE
Build Status updated on Drone Dashboard but not on GitHub

### ISSUE THREAD

**Issue by XuryaX** [drone/drone#2194]
I was checking out drone.  and set it upon AWS using docker-compose. The build status is updated on Drone Dashboard but the same status is not reflected on guthub.

![image](https://user-images.githubusercontent.com/6430258/30094107-7b26602c-92e7-11e7-8ddb-176f98309b53.png)

![image](https://user-images.githubusercontent.com/6430258/30094113-8bb2f27a-92e7-11e7-9d28-5eceea02cb43.png)

**Comment by bradrydzewski** [comment]
please use [discourse.drone.io](https://discourse.drone.io) for support questions
