### ISSUE TITLE
Drone agent not connecting to host

### ISSUE THREAD

**Issue by a1exanderjung** [drone/drone#2195]
I'm having trouble using the latest version of Drone `0.8.0`.  In particular connecting the drone agent to the drone server.  In all previous version, including `0.7.3`, the drone agent would connect to the drone agent specified by the environmental variable `DRONE_SERVER`.  However, recent releases will yield the following error message from the agent:

    level=fatal, msg="DRONE_HOST is not properly configured"

This suggests that there is a change in environment variable in progress and that `DRONE_SERVER` is being replaced with `DRONE_HOST` for consistency purposes.  This makes perfect sense, but it is currently undocumented.  When attempting to use the environmental variable `DRONE_HOST` instead with the latest version of drone, the agent fails again:

    level=fata, msg="verson control system not configured"

**Comment by bradrydzewski** [comment]
please use https://discourse.drone.io for support and questions.
