### ISSUE TITLE
Add SIGTERM support

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2205]
Trigger graceful shutdown process on SIGTERM (in addition to SIGINT).

RE: https://discourse.drone.io/t/termination-signals/647.

**Comment by bradrydzewski** [comment]
I noticed this being discussed in the Slack thread. Package is here:
https://github.com/cncd/pipeline/blob/master/pipeline/interrupt/interrupt.go

**Comment by bradrydzewski** [comment]
I moved this to its own package, leftpad style
https://github.com/drone/signal

Updated and merged https://github.com/drone/drone/pull/2219
