### ISSUE TITLE
How do i clone other repos and then run them before actually start the test.

### ISSUE THREAD

**Issue by lnshi** [drone/drone#2211]
The commit is going to repo `A`, but before actually start running the tests in `A`, i need to deploy service from repo `B`, and `C` first.

Repo `A`, `B` and `C` are all my private repo in bitbucket cloud, all have `Dockerfile` and `run.sh` in it.

I just totally cannot find any useful documents, examples, and the gitter channel is also closed..., can someone here help?

**Comment by tboerger** [comment]
As you can see on the issue template the issue tracker is reserved for confirmed issues or bugs and not for questions how to solve a use case. So I kindly ask you to post your question on https://discourse.drone.io/ or on Stackoverflow.

**Comment by lnshi** [comment]
@tboerger @bradrydzewski i posted the question [https://discourse.drone.io 699](https://discourse.drone.io/t/how-drone-pull-and-deploy-my-other-dependent-services-from-my-bitbucket-first-before-running-the-integration-test/699), pls help, thank u.
