### ISSUE TITLE
Can we get DRONE_WORKER env var added as well known env var?

### ISSUE THREAD

**Issue by mhagen-vmware** [drone/drone#2216]
It would be useful to use to have hostname and/or host ip address pushed into the worker container as an environment variable so that our builds can know which worker they are running on.

**Comment by bradrydzewski** [comment]
Merged patch https://github.com/drone/drone/commit/63001a7c66b621793ca7ef450eac2c94bd1728f1 which exposes the host machine to the pipeline as the `DRONE_MACHINE` environment variable. This is available in `drone/drone:latest` and will be included in 0.8 final.

Please note that workers identify themselves by hostname. This means the default value will be the hostname of the docker container, which may or many not be useful, but will be unique. You can explicitly override this value by setting `DRONE_HOSTNAME`. This can be set to whatever you want (it is purely used for labeling) and can be set to an IP address, domain name, etc.

Also note that the `DRONE_MACHINE` environment variable will only be available at runtime. That is to say that it is not available when the yaml is compiled and cannot be used as a yaml [substitution](http://docs.drone.io/substitution/) variable.
