### ISSUE TITLE
Store and expose the source / head branch for pull requests

### ISSUE THREAD

**Issue by foklepoint** [drone/drone#2222]
This was talked about In a previous discussion on Gitter. The issue is that the `CI_COMMIT_REFSPEC` includes the branch you’re pushing to in a pull request but it has the format: `branch-im-pushing-to:merge-branch`. For plugins, it'd be nice not to have to parse this variable and rather just have the `branch-im-pushing-to` as a CI variable

**Comment by foklepoint** [comment]
@bradrydzewski @gtaylor

**Comment by bradrydzewski** [comment]
These are the planned changes to the format for 0.9.  Note that we will capture the source and target branch, as well as the commit sha before and after. This should hopefully fill any gaps we have with the current data model.

```diff
type Build struct {
---
-	Commit       string `db:"build_commit"        json:"commit"`
+	Before       string `db:"build_before"        json:"before"`
+	After        string `db:"build_after"         json:"after"`
	Ref          string `db:"build_ref"           json:"ref"`
-	Branch       string `db:"build_branch"        json:"branch"`
+	Source       string `db:"build_source"        json:"source"`
+	Target       string `db:"build_target"        json:"target"`
---
}
```

**Comment by laszlocph** [comment]
This is great. Is the v0.9 branch available on Github?

**Comment by bradrydzewski** [comment]
0.9 is not yet posted to GitHub, but I will post an update here once available. In the meantime, this feature is coded and ready to ship, pending the 0.9 release. Will close the issue once a 0.9 release candidate is posted.

**Comment by bradrydzewski** [comment]
1.0.0-rc.1 now includes `DRONE_TARGET_BRANCH` and `DRONE_SOURCE_BRANCH` for pull requests.

**Comment by bradrydzewski** [comment]
note that this is possible using Starlark scripting plugin:
https://github.com/drone/drone-convert-starlark

```python
def main(ctx):
  if ctx.build["before"] == "develop":
    # do someting
  else:
    # do something else
```

**Comment by bradrydzewski** [comment]
we officially announced support for starlark scripting:
https://blog.drone.io/create-pipelines-using-starlark/

with initial documentation:
https://docs.drone.io/starlark/overview/

as mentioned, we are pushing users toward starlark for advanced use cases that are not supported by the yaml.  hope this helps!
