### ISSUE TITLE
Bade Image not updating

### ISSUE THREAD

**Issue by vishal24tuniki** [drone/drone#2224]
I've integrated badge in my github repo using markdown. Though the direct url works, when the repo page loads, the image isn't downloading

`[![Build Status](https://drone-ci-thunderstorm.amagi.com/api/badges/amagimedia/ott_ssp/status.svg)](https://drone-ci-thunderstorm.amagi.com/amagimedia/ott_ssp)`

Request & Response headers in Github

URL:https://camo.githubusercontent.com/13011537319843fd944f54ff20f2c9dc220026c8/68747470733a2f2f64726f6e652d63692d7468756e64657273746f726d2e616d6167692e636f6d2f6170692f6261646765732f616d6167696d656469612f6f74745f7373702f7374617475732e737667
Request Method:GET
Status Code:502 Bad Gateway
Remote Address:151.101.0.133:443
Referrer Policy:origin-when-cross-origin
Response Headers
view source
Accept-Ranges:bytes
Cache-Control:no-cache, no-store, private, must-revalidate
Connection:keep-alive
Content-Length:24
Content-Security-Policy:default-src 'none'; img-src data:; style-src 'unsafe-inline'
Content-Type:text/plain; charset=utf-8
Date:Sun, 17 Sep 2017 04:12:54 GMT
Server:github-camo (df02412a)
Strict-Transport-Security:max-age=31536000; includeSubDomains
Timing-Allow-Origin:https://github.com
Via:1.1 varnish
X-Cache:MISS
X-Cache-Hits:0
X-Content-Type-Options:nosniff
X-Fastly-Request-ID:f0a673c4ffab49c7e283470950489f554f226652
X-Frame-Options:deny
X-GitHub-Request-Id:698A:48D7:39B6D90:3D0EC35:59BDF646
X-Served-By:cache-lcy1139-LCY
X-Timer:S1505621574.159240,VS0,VE356
X-Xss-Protection:1; mode=block
Request Headers
view source
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:camo.githubusercontent.com
Referer:https://github.com/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by bradrydzewski** [comment]
Please post support questions to discourse.drone.io
