### ISSUE TITLE
optimize repository synchronization process

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2230]
When syncing a large number of repositories it can take many seconds. During this time period additional http requests from the same user could result in duplicate synchronizations. This can be resolved by immediately setting the user synchronization date.

The change to the relevant [sections of code](https://github.com/drone/drone/blob/ec6016062bd1d7d702c5edf383eb0728df33dbdd/server/user.go#L69:L83) would roughly look like this:

```diff
+		user.Synced = time.Now().Unix()
+		store.FromContext(c).UpdateUser(user)
		sync := syncer{
			remote: remote.FromContext(c),
			store:  store.FromContext(c),
			perms:  store.FromContext(c),
		}
		if err := sync.Sync(user); err != nil {
			logrus.Debugf("sync error: %s: %s", user.Login, err)
-		} else {
-			logrus.Debugf("sync complete: %s", user.Login)
-			user.Synced = time.Now().Unix()
-		}
```

In addition we should optimize the automatic synchronization process to immediately return the repository list prior to synchronization (this means the list could be slightly stale) and then perform the synchronization async in the background.

**Comment by tonglil** [comment]
I would definitely prefer staleness over a timeout/cancel, especially if the UI could display that a sync is not yet complete.

**Comment by bradrydzewski** [comment]
the patch to prevent duplicate sync should be easy enough. I am not sure yet how I want to handle the async aspect and UI notification. I need to think through it a bit more, but expect a solution and 0.8.1 tag this week.

**Comment by bradrydzewski** [comment]
I implemented the first (more simple) fix as part of https://github.com/drone/drone/pull/2235

It is available in the latest docker image and will be tagged in 0.8.1

**Comment by bradrydzewski** [comment]
improvements to the sync process are complete. The database transactions are more efficient, and the synchronization happens asynchronously (does not block the user interface).
