### ISSUE TITLE
Cannot Clone Private Repositories

### ISSUE THREAD

**Issue by XuryaX** [drone/drone#2237]
I checked a couple of posts from older versions:-
https://github.com/drone/drone/issues/371

But it seems I cannot get the public key for drone itself. I checked the settings page of repo, but it doesn't contain a sshkey either.

I tried going inside docker container, and it seems, that there are ssh keys in the filesystem.
https://stackoverflow.com/questions/46525611/running-docker-interactive-shell

How to clone private repositories using drone public key?

**Comment by bradrydzewski** [comment]
Please create a thread at https://discourse.drone.io for usage support. We reserve the issue tracker for bug reports and feature requests only.
