### ISSUE TITLE
Drone calling wrong URL on gitea tag create hook

### ISSUE THREAD

**Issue by rhaamo** [drone/drone#2245]
The webhook when creating a tag always returns 404, I'm using drone 0.7.

According to some issues I found (https://discourse.drone.io/t/drone-0-5-817-gitea-a-gogs-fork-tag-webhook-404/105/5, https://github.com/drone/drone/issues/1870 then https://github.com/go-gitea/gitea/issues/426), drone is likely using the wrong url to get the .drone.yml file for tag push.

I can manually access to "https://mygitea/api/v1/repos/dashie/somerepository/raw/v0.4.2/.drone.yml" without the extras "refs/tag", with, it fails.

But in the log from the nginx serving gitea:
```"GET /api/v1/repos/dashie/somerepository/raw//.drone.yml HTTP/1.1" 404 3544 "-" "Go-http-client/1.1"```

Looks like the tag is missing "/raw//.drone.yml"

Is that a new bug or incompatible with the/my current gitea (1.2.0+rc2) webhook ?

For reference, the payload my gitea is pushing:

```
{
  "secret": "blah====",
  "sha": "b2fb92d248b4ceb8e23817c7ecd23d4c1bbb3e49",
  "ref": "v0.4.2",
  "ref_type": "tag",
  "repository": {
    "id": 69,
    "owner": {
      "id": 1,
      "login": "dashie",
      "full_name": "x",
      "email": "x",
      "avatar_url": "x",
      "username": "dashie"
    },
    "name": "somerepository",
    "full_name": "dashie/somerepository",
    "description": "x.",
    "empty": false,
    "private": false,
    "fork": false,
    "parent": null,
    "mirror": false,
    "size": 26600,
    "html_url": "http://mygitea/dashie/somerepository",
    "ssh_url": "gogs@mygitea:dashie/somerepository.git",
    "clone_url": "http://mygitea/dashie/somerepository.git",
    "website": "https://mygitea/",
    "stars_count": 0,
    "forks_count": 1,
    "watchers_count": 1,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2017-05-05T11:00:49+02:00",
    "updated_at": "2017-10-18T09:39:09+02:00",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": false
    }
  },
  "sender": {
    "id": 1,
    "login": "dashie",
    "full_name": "x",
    "email": "x",
    "avatar_url": "x",
    "username": "dashie"
  }
}
```

**Comment by bradrydzewski** [comment]
Please use https://discourse.drone.io/ for support questions.
