### ISSUE TITLE
GRPC Health Checks

### ISSUE THREAD

**Issue by jmccann** [drone/drone#2246]
Currently agent connectivity to server can be terminated under certain conditions (e.g. no jobs for a while and/or firewall/LB terminating idle connections).  This results in jobs being triggered and sitting in pending until the agent is restarted and "reconnected" to the server.

GRPC health checks could help prevent/correct this issue and make the Drone platform more stable in general.

Discussion regarding this in Discourse: https://discourse.drone.io/t/0-8-1-agent-loses-connection-overnight/864/7
GRPC Health Checks docs: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by appleboy** [comment]
The same issue in kubernetes.

**Comment by Franklin89** [comment]
I am also seeing this while running in Docker Swarm.

**Comment by bradrydzewski** [comment]
Until we have a patch, it is not recommended to route agent communication through a load balancer or reverse proxy. When I start working on this I will update the issue status, but in the meantime, please feel free to send a patch if you want to expedite a resolution to this issue.
