### ISSUE TITLE
README.md does not contains build instructions

### ISSUE THREAD

**Issue by strk** [drone/drone#2247]
I spent the last 30 minutes trying to figure out how to build the drone server, thinking about upgrading a production server from 0.5 to current (0.8?). Is there any reason not to write simple instructions in the README.md file ?

For the 0.5 branch there was a Makefile, which was basically self-documented, why not putting it back ?

**Comment by bradrydzewski** [comment]
we are using `BUILDING` files in the drone repositories now

**Comment by strk** [comment]
Thanks, received upon pull, with commit
0c972d8fc5960c7c9d3d9f8b9538b27c74dbef2d
