### ISSUE TITLE
Missing error handling for empty repo list

### ISSUE THREAD

**Issue by marvinthepa** [drone/drone#2248]
If the user does not have access to any repos, instead of telling the user so, the GUI at `$DRONE/account` just blocks at "Loading...".

the Javascript Console shows why:

```
Uncaught TypeError: Cannot read property 'sort' of null
    at app.js:101
    at d.callback (app.js:1462)
    at d.<anonymous> (app.js:1437)
    at d.r.emit (app.js:3169)
    at XMLHttpRequest.n.onreadystatechange (app.js:1468)
```

Reason for this seems to be that `$DRONE/api/user/repos?all=true` returns the string `null` which seems to be parsed as json.

Backend: Bitbucket Server

**Comment by bradrydzewski** [comment]
this was fixed in version 0.8 of drone.

<img width="793" alt="screen shot 2017-10-23 at 7 33 19 am" src="https://user-images.githubusercontent.com/817538/31894878-81a14212-b7c4-11e7-973b-65d9a3a80db6.png">
