### ISSUE TITLE
Build status not refresh on GitHub

### ISSUE THREAD

**Issue by tomhaj** [drone/drone#2249]
Hi,

It seems like build status indicator on GitHUb is not refreshing when build succeed.

<img width="1004" alt="zrzut ekranu 2017-10-24 o 01 12 26" src="https://user-images.githubusercontent.com/12626874/31917616-ae49c304-b858-11e7-9191-b17de244c618.png">

<img width="1080" alt="zrzut ekranu 2017-10-24 o 01 11 35" src="https://user-images.githubusercontent.com/12626874/31917623-b4db3fea-b858-11e7-85e3-ca577aa098fd.png">

It only works on failure builds

<img width="998" alt="zrzut ekranu 2017-10-24 o 01 15 25" src="https://user-images.githubusercontent.com/12626874/31917670-fe656636-b858-11e7-82ab-29aa169ba0d1.png">

**Comment by bradrydzewski** [comment]
this happens when DRONE_HOST is not properly configured [1]. If you have further questions please use https://discourse.drone.io for end-user support.

[1] https://discourse.drone.io/t/build-status-updated-on-drone-dashboard-but-not-on-github/563/2

**Comment by tomhaj** [comment]
Thanks for fast reply! Issue can be closed.
