### ISSUE TITLE
Please, support keybase Git system.

### ISSUE THREAD

**Issue by MichelDiz** [drone/drone#2254]
keybase Git system for CI

Ref: https://keybase.io/blog/encrypted-git-for-everyone

**Comment by tboerger** [comment]
How should that work at all? Drone relies on the user authentication from the remote like github, gitlab and so on. Beside that it looks like you need a configured keybase account which also won't work for server environments. Additionally to that, IMHO it only makes sense for systems with pull requests and more features than just push and pull commits :).

**Comment by MichelDiz** [comment]
That would be a new exception, which would make room for local Git services. After all Git is a technology independent of any third party service like GitHub, Gitlab and etc.

Keybase is a great option for those who are starting out and want to use the idea behind Keybase itself. Encryption and so on.

Well, maybe it could be a Linux container (https://keybase.io/docs/the_app/install_linux) with the Keybase client running. That is authorized in advance by the user.

Could be an "extra" user of the team. That would do only this work related to CI. The authorization process is already foreseen by the keybase client, the problem lies in defining what the automation would look like. How this "worker container" would work. You have developed the Drone, you know how to do automation. It would be enough to analyze the process used by Keybase staff, am I wrong?

They have a whole CLI (command line interface) context that could be leveraged for automation.

1. > Keybase linux container
2. > Some automation with pulls and requests
3. > Drone automation CI things
4. > Voit la

Please clarify if logic does not beat.

Cheers

**Comment by bradrydzewski** [comment]
Every new remote connector (eg github, gitlab, bitbucket, etc) must implement below following interface. A keybase connector would need to implement this interface as well.

```
type Remote interface {
	// Login authenticates the session and returns the
	// remote user details.
	Login(w http.ResponseWriter, r *http.Request) (*model.User, error)

	// Teams fetches a list of team memberships from the remote system.
	Teams(u *model.User) ([]*model.Team, error)

	// Repo fetches the named repository from the remote system.
	Repo(u *model.User, owner, repo string) (*model.Repo, error)

	// Repos fetches a list of repos from the remote system.
	Repos(u *model.User) ([]*model.Repo, error)

	// Perm fetches the named repository permissions from
	// the remote system for the specified user.
	Perm(u *model.User, owner, repo string) (*model.Perm, error)

	// File fetches a file from the remote repository for the given ref
	// and returns in string format.
	File(u *model.User, r *model.Repo, ref, f string) ([]byte, error)

	// Netrc returns a .netrc file that can be used to clone
	// private repositories from a remote system.
	Netrc(u *model.User, r *model.Repo) (*model.Netrc, error)

	// Activate activates a repository by creating the post-commit hook.
	Activate(u *model.User, r *model.Repo, link string) error

	// Deactivate deactivates a repository by removing all previously created
	// post-commit hooks matching the given link.
	Deactivate(u *model.User, r *model.Repo, link string) error

	// Hook parses the post-commit hook from the Request body and returns the
	// required data in a standard format.
	Hook(r *http.Request) (*model.Repo, *model.Build, error)
}
```

As tboerger mentioned, drone does not manage users or permissions or even login. These things are delegated to the source code management system (github, bitbucket, stash, gitlab, gogs, gitea, gerrit, etc). I am not familiar with the keybase git system, however, implementing the above interface would be the recommended place to start.

**Comment by tboerger** [comment]
I still don't believe that it can be integrated easily, but let's see what others bring up.

**Comment by venth** [comment]
Hi @bradrydzewski, where can I find any tests to help understand how the Remote interface is called and what exact data has to be provided?

**Comment by tboerger** [comment]
All relevant files should be part of https://github.com/drone/drone/tree/master/remote

**Comment by bradrydzewski** [comment]
closing this due to lack of interest / volunteer
