### ISSUE TITLE
Build not triggering due to 404 on webhook

### ISSUE THREAD

**Issue by jonasob** [drone/drone#2255]
We're using Drone in combination with Gitea, and had this working flawlessly on this repository up until today: `https://drone.fsfe.org/fsfe-ams/oidcp`

At this commit `
https://git.fsfe.org/fsfe-ams/oidcp/commit/65de140645564ba985eee0427ed03f79e499cbd4` Drone stopped building. All previous commits have triggered a build properly, but none of the later commits have. From the Drone logs, we get these errors when the webhook is triggered:

```
time="2017-11-03T12:53:44Z" level=error msg="failure to get build config for fsfe-ams/oidcp. 404 Not Found" 
time="2017-11-03T12:53:44Z" level=error msg="Error #01: 404 Not Found\n" ip=172.17.0.1 latency=156.731944ms method=POST path="/hook" status=404 time="2017-11-03T12:53:44Z" user-agent=GogsServer 
```

In desperation (well), I tried disabling the repository in Drone and then enabling it again, creating a new webhook, but the error message did not change on new commits and builds are still not triggered.

**Comment by jonasob** [comment]
Turns out this is also related to Gitea changes. Pulling the latest drone changes the error message to:

```
time="2017-11-03T14:26:53Z" level=error msg="error: fsfe-system-hackers/community: cannot find .drone.yml in refs/heads/master: 404 Not Found" 
```

Which seems true enough. It tries to get the .drone.yml through the api: `https://git.fsfe.org/api/v1/repos/fsfe-system-hackers/community/raw/3cf576657978aea39876338f84d7cf43fe7beb1f/.drone.yml` which now returns 404 after a Gitea iupgrade.

**Comment by jonasob** [comment]
And of course we're not the first to notice :-)

https://github.com/go-gitea/gitea/issues/2824

So clearly a Gitea issue, not Drone.

**Comment by 9908928306555p** [comment]
I am getting error 404 for the github-webhook. 
http://d786652a.ngrok.io/github-webhook/.
