### ISSUE TITLE
Secrets don't work in Drone 0.7

### ISSUE THREAD

**Issue by AlexanderMazaletskiy** [drone/drone#2258]
Hi, guys! I did all steps  in http://readme.drone.io/usage/secret-guide/. 
I see all secrets in Drone UI.
sign yml, but secrets not seen. Why?

**Comment by appleboy** [comment]
Please post your question in https://discourse.drone.io/

**Comment by tboerger** [comment]
The docs at readme.drone.io are outdated, they are focused on drone 0.5 and will be removed soon. Please use the updated documentation at docs.drone.io. Beside that @appleboy is right, the issue template clearly say that you should ask questions on discourse or stackoverflow.
