### ISSUE TITLE
Feature request - Force HTTPS if LetEncrypts is enabled

### ISSUE THREAD

**Issue by khanhicetea** [drone/drone#2261]
Could we redirect all http (except ACME `~/.well-known/*`) to https if LetEncrypts option is enabled ?

And adding `HTTP Strict Transport Security`

Thanks.

**Comment by tboerger** [comment]
If Let's Encrypt is enabled it is already redirecting the requests to HTTPS, it's just not setting the HSTS header.

**Comment by khanhicetea** [comment]
Hi @tboerger ,

I re-check my drone server (v0.8.1) via curl, and this is what I got (I replaced hostname and ip)

```bash
$ curl -vvv http://drone.example.com/
*   Trying 172.17.17.2 ...
* Connected to drone.example.com (172.17.17.2) port 80 (#0)
> GET / HTTP/1.1
> Host: drone.example.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value
< Content-Type: text/html; charset=UTF-8
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Last-Modified: Wed, 08 Nov 2017 15:47:23 GMT
< X-Content-Type-Options: nosniff
< X-Drone-Version: 0.8.1+build.1318
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< Date: Wed, 08 Nov 2017 15:47:23 GMT
< Content-Length: 370
```

Then I try to access via http url on browser => it redirected to Github OAuth page with redirect_url was an http url

Thanks !

**Comment by khanhicetea** [comment]
We already have HSTS header provide by middleware `Secure` 

```go
// Secure is a middleware function that appends security
// and resource access headers.
func Secure(c *gin.Context) {
	c.Header("Access-Control-Allow-Origin", "*")
	c.Header("X-Frame-Options", "DENY")
	c.Header("X-Content-Type-Options", "nosniff")
	c.Header("X-XSS-Protection", "1; mode=block")
	if c.Request.TLS != nil {
		c.Header("Strict-Transport-Security", "max-age=31536000")
	}

	// Also consider adding Content-Security-Policy headers
	// c.Header("Content-Security-Policy", "script-src 'self' https://cdnjs.cloudflare.com")
}
```

**Comment by tboerger** [comment]
This handler is enabled if let's encrypt is active, so it clearly redirects: https://github.com/drone/drone/blob/master/cmd/drone-server/server.go#L568

**Comment by khanhicetea** [comment]
Sorry but please look to reality that "no redirect" in my context (I enabled LetEnscrypt, used 0.8.1)

Btw, your mentioned code just prove that "http" uses the same `handler` with "https", but no redirecting middleware or something do it. 

Thanks.

**Comment by tboerger** [comment]
Damn, right... @bradrydzewski why have you dropped the HTTP to HTTPS redirect if Let's Encrypt is enabled? I'm sure we had a redirect in there before...

**Comment by jhasse** [comment]
This seems to be missing again in 1.0.0-rc.1.

**Comment by bradrydzewski** [comment]
it has to be configured in 1.0

```
DRONE_HTTP_SSL_REDIRECT=true
DRONE_HTTP_SSL_TEMPORARY_REDIRECT=true
DRONE_HTTP_SSL_HOST=cloud.drone.io
DRONE_HTTP_STS_SECONDS=315360000
```
