### ISSUE TITLE
docker mtu 

### ISSUE THREAD

**Issue by donghuabin72** [drone/drone#2268]
The environment I use is openstack vm, The network card mtu is 1454 ,not 1500 
When I build with drone, I find that it creates a new container and the mtu of the network  card
is 1500 .  so the container was not able to access the Internet

by the way ,during the use, I discovered that the drone created a bridge network using docker and the mtu is 1500, I need to set the mtu of this network for 1400 to get online

I've done the following, but it doesn't work

networks:
  default:
    driver: bridge
    driver_opts: io.drone.network.pod=true

My drone version is 0.8.1

What else do I need to write, thank you.

**Comment by bradrydzewski** [comment]
Please use our [discourse](https://discourse.drone.io) forum for end-user support questions. Thanks!
