### ISSUE TITLE
Drone specific metrics?

### ISSUE THREAD

**Issue by prologic** [drone/drone#2271]
I see #2014 ad recently merged; Are there any Drone specific metrics that are exposed such as build counters, queue depth, connection stats between server<->agent(s)

**Comment by bradrydzewski** [comment]
Yes, all of the above are available at the prometheus endpoint. These metrics are an enterprise feature, but are currently still available in the community image.
http://docs.drone.io/configure-prometheus/

The agents also expose health metrics at the `/healthz` endpoint on port 3000 and implement the docker healthcheck. The agents also implement a `/varz` endpoint that provides some additional runtime information (current builds, number of threads polling new builds, etc).

**Comment by prologic** [comment]
Cool! I'll check these out and provide a Grafana dashboard and Prometheus
AlertManager v2 rules (unless you have already?)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
