### ISSUE TITLE
[Feature Request] Better accessible Restart Button 

### ISSUE THREAD

**Issue by rdeutz** [drone/drone#2279]
Since Drone 0.8 the Restart button has moved to the side menu and is not so good accessible. Can we have a copy of the button accessible in the build overview?

**Comment by tboerger** [comment]
Duplicate of https://github.com/drone/drone/issues/2278

**Comment by tboerger** [comment]
For further information subscribe to https://github.com/drone/drone-ui/issues/187

**Comment by rdeutz** [comment]
I have seen the discussion but it seems to me not clear what the direction is.

ref: https://discourse.drone.io/t/drone-0-8-no-restart-button/908

**Comment by tboerger** [comment]
This issue have already been created (duplicate) and it have been moved to the correct repository, the drone-ui repo (so this issue should be closed).

**Comment by rdeutz** [comment]
Done thanks.
