### ISSUE TITLE
Docker images for 0.8.3 are missing

### ISSUE THREAD

**Issue by calind** [drone/drone#2280]
Hi,

I looks like the tags for 0.8.3 are missing on the docker hub. Are they available somewhere else?

**Comment by ptman** [comment]
Ah, I should've probably opened an issue instead of this: https://discourse.drone.io/t/drone-0-8-3-docker-image/1177/3

**Comment by tboerger** [comment]
Looks like the tag 0.8.2 is in reality 0.8.3 now: https://beta.drone.io/drone/drone/1356/11

**Comment by tboerger** [comment]
@bradrydzewski maybe you should use the new auto tag :)
