### ISSUE TITLE
Feature request - drone agents set port from env variable

### ISSUE THREAD

**Issue by yellowmegaman** [drone/drone#2281]
Hi! Drone 0.8.1 here
I'm currently scaling drone via hashicorp nomad, got 1 server and random amount of agents.
I'd like to be able to tell drone agent which port to use, so they can co-locate on one machine (optimal for lightweight tasks).

Currently all agents have random port, they are reaching server just fine, are accepting tasks without issues, but:

```
Dec 14 14:21:31 frankenci logz server frankenci ci0[1530]: INFO: 2017/12/14 14:21:31 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 172.17.0.2:9000->10.132.0.2:38194: write: broken pipe"
Dec 14 14:21:41 frankenci logz server frankenci ci0[1530]: INFO: 2017/12/14 14:21:41 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 172.17.0.2:9000->10.132.0.2:38206: write: broken pipe"
Dec 14 14:21:51 frankenci logz server frankenci ci0[1530]: INFO: 2017/12/14 14:21:51 transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.17.0.2:9000->10.132.0.2:38220: read: connection reset by peer
Dec 14 14:22:01 frankenci logz server frankenci ci0[1530]: INFO: 2017/12/14 14:22:01 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 172.17.0.2:9000->10.132.0.2:38234: write: broken pipe"
Dec 14 14:22:11 frankenci logz server frankenci ci0[1530]: INFO: 2017/12/14 14:22:11 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 172.17.0.2:9000->10.132.0.2:38248: write: broken pipe"```

So, basically all agents continue to listen on port 9000, but this port is port_mapped to host to some random value. It would be truly great if i could specify env var like `DRONE_AGENT_PORT` and agent just used it.

Thanks a lot in advance!

**Comment by bradrydzewski** [comment]
This is already supported with docker port mappings. The server listens on port 9000 inside the container, but this can be mapped to a different port (example 11000 below) using the following command line options:

```sh
docker run -p 11000:9000  drone/drone
```

The agent can then be configured to connect to the new port:

```
DRONE_SERVER=<address>:11000
```

Or alternatively you can just put the two instances on separate user-defined docker networks to avoid collisions.

If you have any additional usage question, please start a thread at https://discourse.drone.io for

**Comment by yellowmegaman** [comment]
Thanks for rapid response! But i was talking about agents, not server. Gonna open thread on discourse soon.

**Comment by bradrydzewski** [comment]
> I'd like to be able to tell drone agent which port to use

yes, you can tell the agent which port to use with `DRONE_SERVER`. This environment variable should be in the format of `<ADDRESS>:<PORT>`
