### ISSUE TITLE
I find a BUG in http://docs.drone.io/ where in GITLAB.

### ISSUE THREAD

**Issue by juq7ang** [drone/drone#2285]
![image](https://user-images.githubusercontent.com/34638217/34152292-1274f198-e4e9-11e7-9f36-ac4d7d3a38b8.png)
when I` docker-compose up` by the `docker-compose.yml`. 
`docker logs -f xxxxxxx` we can see many problems : `DRONE_HOST is not properly configured.`

But i have found long time to konw why so diffcult. Because your doc is wrong.

**Comment by bradrydzewski** [comment]
if you find an issue in the docs, kindly send a pull request to https://github.com/drone/docs
