### ISSUE TITLE
How to set up the plug-in time zone

### ISSUE THREAD

**Issue by jeffzhangme** [drone/drone#2291]
The time zone in the drone server is different from that in the docker plugin. How does the time zone in the docker plugin change?

```drone-server_1  | time="2018-01-05T08:53:45+08:00" level=error msg="pull queue item: 375: successfully removed from backup"```

```time="2018-01-05T01:44:01Z" level=warning msg="The \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"```

**Comment by bradrydzewski** [comment]
discourse.drone.io for support questions
