### ISSUE TITLE
Agent build failed due to OOM. k8s kills it and drone server stuck

### ISSUE THREAD

**Issue by dolanor** [drone/drone#2292]
Hello,

I have a setup with drone installed on a k8s install.
At some point, our metalinter step goes into OOM and get killed by k8s.
```
Killing container with id docker://drone-agent:Need to kill Pod    Killing    2018-01-05T16:14:57Z    2018-01-05T16:14:57Z    1
Killing container with id docker://drone-dind:Need to kill Pod    Killing    2018-01-05T16:14:57Z    2018-01-05T16:14:57Z    1
The node was low on resource: memory.    Evicted    2018-01-05T16:14:56Z    2018-01-05T16:14:56Z    1
```
Problem is that drone server doesn't update the state or doesn't try to reschedule to a new agent that connects and put itself into waiting for a job.

It seems one of the linter goes crazy (8GB) and creates that. We didn't find which one yet.

**Comment by bradrydzewski** [comment]
I believe this can be consolidated under https://github.com/drone/drone/issues/2189. If the agent restarts unexpectedly the build is stuck in a pending or running state and not re-scheduled.
