### ISSUE TITLE
make sync frequency configurable

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2299]
Should be able to configure the frequency of automatic repository and permission synchronization. The default values are currently 72 hours and 30 minutes, respectively.

**Comment by ptagr** [comment]
+1. thanks!

**Comment by bradrydzewski** [comment]
sync now happens in the background and therefore does not block the user interface.

**Comment by bradrydzewski** [comment]
re-opening this because it may still be nice to configure sync frequency
