### ISSUE TITLE
Let's encrypt tls-sni challenge

### ISSUE THREAD

**Issue by jhernandezb** [drone/drone#2300]
Due to https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

New accounts won't be able to use lets encrypt with the current tls-sni and also won't work in drone until it's migrated to http-01 challenge

Also related https://github.com/golang/go/issues/21890

**Comment by tboerger** [comment]
To get this fixed we have to wait for autocert or switch to a different lib like lego, I would prefer to wait for autocert for now.

**Comment by bradrydzewski** [comment]
agreed, there is already a CL for autocert

**Comment by x1ddos** [comment]
I've literally just submitted that CL. autocert now has http-01 support.
