### ISSUE TITLE
use plugins/docker ; docker registry login use token ; then authentication required.

### ISSUE THREAD

**Issue by lixwlixw** [drone/drone#2305]
publish:
    image: plugins/docker
    repo: 172.25.163.133:5000/lixw/demooo
    registry: 172.25.163.133:5000
    username: hack
    auth: SBUB7Do8ZpuUwZVwY1OeuZFyf8YgKUDxpPCoe_yiA6k
    insecure: true
    tags: [ latest ]

Successfully built 1ae0f930f7ee
23s
98
Successfully tagged 21bec705873a1ea2f32e70b5cf9cc0d93ef628c3:latest
23s
99
+ /usr/local/bin/docker tag 21bec705873a1ea2f32e70b5cf9cc0d93ef628c3 172.25.163.133:5000/lixw/demooo:latest
23s
100
+ /usr/local/bin/docker push 172.25.163.133:5000/lixw/demooo:latest
23s
101
The push refers to a repository [172.25.163.133:5000/lixw/demooo]
23s
102
ea9e0b972565: Preparing
23s
103
72a2a7ebda91: Preparing
23s
104
cd7100a72410: Preparing
23s
105
unauthorized: authentication required
23s
106
time="2018-01-17T08:54:08Z" level=fatal msg="exit status 1"

How can we fix this problem?

**Comment by bradrydzewski** [comment]
Per our issue template, please use [discourse.drone.io](https://discourse.drone.io) for user support questions.
