### ISSUE TITLE
Stop locking the issues

### ISSUE THREAD

**Issue by alanjds** [drone/drone#2318]
Locking issues hinders people to voluntarily help the project. Is annoying to have bunch of 👍 comments, but Github had solved this already w/ the "Reaction" bar.

Please stop locking the issues. I found some to be closed already but I cannot even inform that on the issue. Will remain open.

**Comment by tboerger** [comment]
Most of the time issues are getting locked if the author doesn't follow the issue template. The issue tracker is reserved for confirmed issues, support and help should be directed to the Drone discourse forum as asked for on the issue template.

**Comment by bradrydzewski** [comment]
https://discourse.drone.io
