### ISSUE TITLE
Add emoji support

### ISSUE THREAD

**Issue by hijak** [drone/drone#2319]
Hi

I am loving using the product thank you very much!!

i would like to request a small feature to support emoji using the :BLAH: format on the web interface

I like to use emoji in my commits because it make me happy wan

Thanks

**Comment by bradrydzewski** [comment]
drone fully supports emoji (see screenshot) however, you need to make sure you create your database with the appropriate characterset. You can contact your database provider for more details.

<img width="695" alt="screen shot 2018-01-26 at 11 19 17 am" src="https://user-images.githubusercontent.com/817538/35456395-25fb2ca0-028a-11e8-9844-64dd1a7d4dcf.png">

If you have any further questions, please post to our [user forum](https://discourse.drone.io/).

**Comment by hijak** [comment]
Hi

ive moved over to mysql and ensured the charsets but it seems hit and miss weather drone will pick up the push event when some emojis are used in the commit message.. eg: i used ⬛ in one commit and drone picked it up and build but i tried to use 🚀 and it didn't do anything when that commit was pushed

im still not able to get drone to show emoji when using the `:emoji:` format in the commit message which is what i ideally want to do rather than copying emoji into the commit msg

isn't there some way of making the ui seeing `:emoji:` and then converting it for viewing pleasure

**Comment by metalmatze** [comment]
I don't see it as drone's reposibility to convert `:emoji:` to the actual emoji.
If you have an actual emoji in the message then show it, if not, then don't show it.
