### ISSUE TITLE
Conditional logic between event and branch in when block 

### ISSUE THREAD

**Issue by julesGoullee** [drone/drone#2322]
I want to launch task on: pull_request AND push on specific branch.

I try:

> 

    when:
      event: [tag, pull_request, push]
      branch: [master, develop, staging]

If I activate Repository Hooks on pull request and push, when I create pull request Drone launch two job(with one never start).....

**Comment by bradrydzewski** [comment]
Hi Jules, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), please start a thread on our [mailing list](https://discourse.drone.io) for end-user support.
