### ISSUE TITLE
Set env vars on `drone exec --local`

### ISSUE THREAD

**Issue by jamoozy** [drone/drone#2325]
This is a feature request based on the thread here:
> https://discourse.drone.io/t/set-env-vars-on-drone-exec-local/1689

In summary, I'm requesting that both the `-e`/`--env` & `--env-file` flags be added to Drone, in a way analogous to Docker's usage of these flags.  The environment variables defined by these flags should be populated into the environment of all build steps in a pipeline when run via `drone exec --local`.

With a slight bit of guidance (pointer to key files & branch to start from) I'd be happy to give implementing this a go.

**Comment by evert0n** [comment]
I have been missing this too when I attempt to run locally more advanced setups.

**Comment by bradrydzewski** [comment]
Closed by https://github.com/drone/drone-cli/pull/85

For future reference, issues related to the CLI should be created in the CLI repository :) https://github.com/drone/drone-cli
