### ISSUE TITLE
Why the default git clone step take such a long time?

### ISSUE THREAD

**Issue by sirius1024** [drone/drone#2329]
![image](https://user-images.githubusercontent.com/6395714/35710971-6b03bcde-07f5-11e8-8fed-b98792a2a7d7.png)

As you see in above picture, git clone step taking ages, 42 minutes...How can I find why it toke such a long time?

 I didn't define anything with git clone, just work with default first step.

CI target: github
Drone version: 0.8.2-1
platform: rancher 1.6.14
OS:  CentOS Linux 7 (3.10.0)
Docker version: 17.06.2-ce
OS file system:
![image](https://user-images.githubusercontent.com/6395714/35711318-57a8f2b0-07f7-11e8-83df-dfc0e95811db.png)

**Comment by bradrydzewski** [comment]
Please use [discourse](https://discourse.drone.io) for end-user support
