### ISSUE TITLE
Copy running builds

### ISSUE THREAD

**Issue by RobinKnipe** [drone/drone#2330]
https://github.com/drone/drone/blob/75150d4a429da6c95cb851bfecded03a50936675/server/build.go#L480

I'm trying to "reuse" a build. Only problem is that when I want to "reuse" this build it is currently in `status: running`, which the code above actively prevents. Is there a way to circumvent this restriction, if not could you consider adding a way to do so (especially in case where the build is currently `running`)?

I have tried explicitly setting the `fork=true` option to try and suggest to drone that I really do want it to reuse a running build, but no dice! What is the `fork` option for, as it seems to have no affect?

Is this perhaps something that the upcoming _Gated Builds_ will help with?

**Comment by bradrydzewski** [comment]
this was closed by https://github.com/drone/drone/pull/2394 and is available in `drone/drone:latest`

**Comment by RobinKnipe** [comment]
Yup that's great, thanks @bradrydzewski !
