### ISSUE TITLE
Validation when adding a registry

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2334]
The add registry endpoint expects a __hostname__ only and should reject any values with special characters such as slashes. Otherwise they cannot be deleted.

**Comment by shivamMg** [comment]
@bradrydzewski There's a nice hostname validator in [goa](https://github.com/goadesign/goa/blob/master/validation.go#L58) framework. Their validators do not come in a separate package though; so to use them we'll have to import the goa package. If it seems superfluous we can implement it ourselves. They've linked the RFC they used for creating that regex: https://www.ietf.org/rfc/rfc1035.txt (Page 7).

**Comment by shivamMg** [comment]
Used `IsHost` validator from [govalidator](https://github.com/asaskevich/govalidator) instead. The one in goa is just for `<label>` from the RFC, and not for `<domain>`. Regex for domain becomes pretty complex. Also an IP can also be a possible registry address.

**Comment by bradrydzewski** [comment]
Merged into 0.9 release. Pending verification.
