### ISSUE TITLE
DRONE_HOST not used for Webhooks

### ISSUE THREAD

**Issue by Zegorax** [drone/drone#2336]
Hello everyone, 

Here's my docker-compose file which can be used for reproducing the issue :
```version: '2'

services:
  drone-server:
    image: drone/drone:latest
    network_mode: bridge
    hostname: drone.server.test
    ports:
      - 50005:8000
    expose:
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=https://drone.server.test
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=https://git.server.test
      - DRONE_SECRET=thisissecret

  drone-agent:
    image: drone/agent:latest
    command: agent
    network_mode: bridge
    restart: always
    depends_on:
      - drone-server
    links:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET= thisissecret
```

When activating a repository for Drone, it creates successfully a webhook in (my case) Gitea, however, the Webhook URL is not correct. It displays something like http://localhost:50005 despite the DRONE_HOST being set.

**Comment by bradrydzewski** [comment]
Drone uses the incoming http.Request to ascertain its own address when creating the webhook. If Drone cannot introspect its own address, it would usually tell me that you have a reverse proxy or load balancer in front of drone and are not setting x-forwarded-for or x-forwarded-proto headers.

If you have any further questions, please use our [forum](https://discourse.drone.io) for user support questions.
