### ISSUE TITLE
Drone exec creates duplicate drone_default networks

### ISSUE THREAD

**Issue by DCRichards** [drone/drone#2337]
## Description

Running `drone exec` multiple times will often result in the following:

```bash
2018/02/09 12:29:47 Error response from daemon: network drone_default is ambiguous (3 matches found on name)
```

This appears to be because drone is doing `docker network create drone_default` on each run, or similar. The correct behaviour should be to check if the network exists before creation.

## Workaround

For those experiencing this, the workaround is to run the following to remove the networks:

```bash
docker network rm $(docker network ls -f name=drone_default -q)
```

**Comment by bradrydzewski** [comment]
drone deletes the network when `drone exec` completes, so the only way the network already exists would be if you run multiple `drone exec` at the same time, if you kill 9 drone exec preventing it from cleaning up, or if there is an internal docker error.

In drone 0.10 all container resources, including the network, are namespaced with a random string to prevent these sort of conflicts [1]

[1] https://github.com/drone/drone-yaml-v1/blob/master/config/compiler/ns.go#L15

**Comment by bradrydzewski** [comment]
Closing this because the CLI is not part of the core project, and is stored in a separate repository with a separate issue tracker https://github.com/drone/drone-cli
