### ISSUE TITLE
Gitlab cannot search by Namespace/Project anymore

### ISSUE THREAD

**Issue by Angelinsky7** [drone/drone#2339]
Please see : https://gitlab.com/gitlab-org/gitlab-ce/issues/40446
now the only correct way to get a project with the api is by using the id :
`api/v4/projects/{:id}`
https://docs.gitlab.com/ce/api/projects.html#get-single-project

**Comment by bradrydzewski** [comment]
I am not able to reproduce any issues with Drone fetching a repository. I executed the following test and it fetched the repository as expected:

```
package main

import (
	"log"
	"testing"

	"github.com/drone/drone/model"
	"github.com/drone/drone/remote/gitlab"
	"github.com/kr/pretty"
)

func main() {
	opts := gitlab.Opts{
		URL: "https://gitlab.com",
	}
	remote, err := gitlab.New(opts)
	if err != nil {
		log.Fatalln(err)
	}
	user := &model.User{
		Token: "",
	}
	repo, err := remote.Repo(user, "gitlab-org", "gitlab-ce")
	if err != nil {
		log.Fatalln(err)
	}
	pretty.Print(repo)
}
```

**Comment by Angelinsky7** [comment]
if you read https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#1023-2017-11-30
you'll see at https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#performance-3-changes-1 :
`Drastically improve project search performance by no longer searching namespace name.`
and sorry when it comes to bug report i don't see why i should use "user support", this a clearly a breaking change in gitlab implementation and clearly your responsibility to adapt to it.

**Comment by bradrydzewski** [comment]
> Drastically improve project search performance by no longer searching namespace name.

The official documentation states that `URL-encoded path of the project` can be used with the  `api/v4/projects/{:id}` endpoint. I am unable to reproduce any issues when using the url-encoded path with the endpoint. So at this time, there appears to be absolutely nothing to fix.

If you disagree, send a pull request. That simple.
