### ISSUE TITLE
unable to fetch bitbucket repositories

### ISSUE THREAD

**Issue by fazpu** [drone/drone#2342]
Hi, I am trying to upgrade from drone:0.7 to 0.8.4.

I am unable to fetch repositories from Bitbucket. The Bitbucket setup should be correct as it was previously working with 0.7 version. I also tried to generate new Bitbucket OAuth access, but I am getting the same error:

```
client error 500: Error fetching repository list. sql: Scan error on column index 12: sql/driver: couldn't convert <nil> (<nil>) into type bool
```

**Comment by bradrydzewski** [comment]
for end user support, please use https://discourse.drone.io/
