### ISSUE TITLE
Build time issue/bug?

### ISSUE THREAD

**Issue by NaurisSadovskis** [drone/drone#2343]
Hi guys, 
first - thanks for Drone, it's really awesome. 

My issue - I'm running Docker-in-Docker on Kubernetes using [Helm chart](https://github.com/kubernetes/charts/tree/master/incubator/drone) & latest version (0.8.4), and I'm running into two time-related issues:
- each time I trigger a build, timer starts at 00:50 (50 seconds) and goes down to 00:00 and then continues onwards as normal
- each time I trigger a build, some steps (not only `clone`) would start at 59:10 and continue onwards until reaching 00:00 and continue as normal (the task completion time appears to be correct).

Screenshot:
![time](https://user-images.githubusercontent.com/15460047/36115500-2b7888d6-102b-11e8-80d6-6f42c98e4c35.png)

I checked time difference between my local machine and nodes and it *appears* to be around ~50 seconds, so that's that.  

However, is it an expected behaviour? Thought I'd check!

**Comment by bradrydzewski** [comment]
@NaurisSadovskis hey there, we track issues with the user interface in github.com/drone/drone-ui. Since this repository does not have any of the UI rendering code, it wouldn't make sense to track such questions here.

**Comment by NaurisSadovskis** [comment]
Thanks, I'll open an issue there, thank you!
