### ISSUE TITLE
Remove `X-Drone-Version` header

### ISSUE THREAD

**Issue by mattes** [drone/drone#2348]
What is the header being used for? From a security perspective this header should be removed.

**Comment by tboerger** [comment]
This is currently the only indicator to find out the used version of drone.

**Comment by bradrydzewski** [comment]
We now have `/version` which returns the version number so I would accept a pull request that removes the header if anyone feels strongly about it. I'm going to close the issue, but feel free to send a pull request that removes it. Cheers.
