### ISSUE TITLE
drone agent arm reports platform as amd64

### ISSUE THREAD

**Issue by hijak** [drone/drone#2351]
Hi

I think your base image for the arm agent needs adjusting
```
Schema version: 1
Image name: drone/agent
Tag: linux-arm
Architecture: amd64
Number of history entries: 11
Create date: 2018-02-21 22:30:38
```

The agent fails to start on rpi

**Comment by bradrydzewski** [comment]
I am unable to reproduce. I am testing on Scaleway arm servers and the docker daemon downloads and runs the image without issue. Lets move to the user support forum (discourse.drone.io) and we can always re-open the issue if needed.
