### ISSUE TITLE
Services not accessible

### ISSUE THREAD

**Issue by nicktgr15** [drone/drone#2362]
I have the same issue as in https://github.com/drone/drone/issues/2340

Tried the example `drone.yml` provided in https://github.com/drone/drone/issues/2340 and I'm getting the following:
```
[ping:L1:9s] + psql -U postgres -d test -h database \n  -c "SELECT * FROM pg_catalog.pg_tables;"
[ping:L2:9s] 
[ping:L3:10s] psql: could not translate host name "database" to address: Name or service not known
2018/03/02 17:18:51 drone_step_0 : exit code 2
```

Using the drone example provided by @bradrydzewski. 

```
drone --version
drone version 0.8.2
```

```
docker --version
Docker version 17.12.0-ce, build c97c6d6
```

**Comment by bradrydzewski** [comment]
please use our community forum for support questions https://discourse.drone.io

**Comment by nicktgr15** [comment]
Apologies. Fixed now.. the problem was drone 0.8.2 installed using brew. Installing it using the curl command from your docs which installs 0.8.3 fixed the problem. Very weird :/
