### ISSUE TITLE
git One push, but always multi pipeline run, why???

### ISSUE THREAD

**Issue by sunvooker** [drone/drone#2364]
link to been closed. #2360 
but the issue is with gogs version control, not gitlab.

and i have question, pipeline start can get git version hash code, why not remove duplication by the hash code??

**Comment by bradrydzewski** [comment]
@sunvooker per our [github issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md) we as that you use our [discourse forum](https://discourse.drone.io) for end user support.
