### ISSUE TITLE
Support Docker secrets through _FILE environment variables

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#2365]
A number of docker official images have the convention where you can specify a file which contains the environment variable. This is used for injecting secrets into the container.

As an example the mysql image allows you to set [_FILE values](https://hub.docker.com/_/mysql/).

> As an alternative to passing sensitive information via environment variables, _FILE may be appended to the previously listed environment variables, causing the initialization script to load the values for those variables from files present in the container. In particular, this can be used to load passwords from Docker secrets stored in /run/secrets/<secret_name> files. For example:
> `$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root -d mysql:tag`

This would allow sensitive information like the DRONE_DATABASE_DATASOURCE to be stored in a file and used.

**Comment by donny-dont** [comment]
There's support in [urfave/cli](https://github.com/urfave/cli#values-from-files) but I don't see anything that lets you chain together one environment variable.

**Comment by bradrydzewski** [comment]
let's combine with https://github.com/drone/drone/issues/2223 which discusses _FILE as well
