### ISSUE TITLE
Matrix in pipeline stage

### ISSUE THREAD

**Issue by cblomart** [drone/drone#2367]
Hello,

I have modified drone/pipeline to handle matrix setting in a comparable way to what is one on the general yaml config.
I would like to test it further in drone but can't figure out how to test it with my forked packages.
See http://github.com/cblomart/pipeline.git for reference and comments!

Cedric

**Comment by bradrydzewski** [comment]
For testing purposes, you could replace the vendored dependency with your custom form. You can read more about how to do this here: 
https://github.com/kardianos/govendor/blob/master/doc/faq.md#q-ive-forked-a-package-and-i-havent-upstreamed-the-changes-yet-what-should-i-do

For further questions and discussion, lets move this to a thread in our mailing list at https://discourse.drone.io

**Comment by cblomart** [comment]
Opened https://discourse.drone.io/t/matrix-stage-build/1902

Thx for the magic scroll.

**Comment by cblomart** [comment]
@bradrydzewski 
Looking at Pr for https://github.com/cncd/pipeline ? 
(I was also intrigued about gprc stream patch which may -or not- stabilise situatios like i have of agents losing connection to server -on swarm cluster-)

**Comment by cblomart** [comment]
@bradrydzewski 
no news?

**Comment by bradrydzewski** [comment]
@cblomart see the discussion about matrix variables in our roadmap here https://discourse.drone.io/t/roadmap-for-the-1-0-release/1723 ... the tldr is that we are not really looking to add any new features to the yaml. Instead we will pursue an alternate .drone.js file format which can be used to script more complex configurations, like this.
