### ISSUE TITLE
Feature request: Store image metadata and show it in UI

### ISSUE THREAD

**Issue by mrueg** [drone/drone#2373]
As a user i want to get information about the image, its version and its sha-hash `registry/image:version@sha256` within the log, so I can reproduce failing/working builds even if the projects `.drone.yml` did not specify a version of the image.

Currently this information doesn't seem to be stored. It would be nice if the browser UI includes this metadata and `drone logs` had an option to show the image metadata

**Comment by tboerger** [comment]
Or you simply pin the used images to specific versions :)

**Comment by mrueg** [comment]
Possible but not a practical solution, if you don't want to upgrade n repositories for one image update. I prefer to run latest with pull: true instead.

**Comment by tboerger** [comment]
I would suggest non-breaking version pins like `plugins/matrix:1` with `pull: true`

**Comment by mrueg** [comment]
Still not really practical, assume the tested application uses openssl and a prebuild container image: test/container:1 for test. The container image uses alpine:3.4 that gets switched to alpine:3.7 as a base and the openssl version changes causing breakage on a PR of your project. Explicit information about the used image makes it easy to spot the cause.

**Comment by bradrydzewski** [comment]
after consideration, we have decided we will not be implementing this feature.  We are abstracting agents / runners outside the codebase and we now have support for a variety of runners (docker, virtualbox, os/exec, etc). We considered whether or not we wanted to allow agents to store unstructured metadata and ultimately decided against the approach.  If something changes we will re-open this issue.
