### ISSUE TITLE
[Feature] Optional encryption of secrets and registry passwords

### ISSUE THREAD

**Issue by Sharsie** [drone/drone#2374]
We would like to open a discussion about encryption of drone secrets and docker registry passwords.

At the moment the secrets and registry passwords are stored in the database as byte => plain text.

For the sake of keeping me sane I will refer to both registry passwords and secrets as **secrets** from now on, thank you very much.

We would like to implement application level encryption where secrets would be encrypted before being stored and decrypted when loaded from the storage engine.

We have already gone through some attack vectors in [discourse](https://discourse.drone.io/t/recommended-way-to-configure-registry-credentials-for-private-docker-hub-repos/678/7) (points 4 and 5) when talking about registry credentials, this was before we found out the secrets are also stored in plain text. SSH_KEYs, aws credentials...you know the deal what happens when the database is compromised.

# Points to consider:

1. What encryption algorithm shall be used
2. How to enable encryption
3. Should we support disabling of encryption
4. How to tackle the migration from non-encrypted to encrypted values

@bradrydzewski we would very much appreciate your input regarding 3 and 4.

## 1. Encryption algorithm
I think it is clear we should use AES-256 with GCM mode. If there is a strong use case for another algorithm, we would welcome some insight into it.
For AES-256 we need a 32byte key. The question is, whether the user should be forced to provide a full length key or whether we should take a random key from the user and run it through sha256 or use scrypt/bcrypt instead if we do not mind importing non standard crypto lib. For this use case, I believe sha256 would be enough as we only need a fixed length byte representation.
[Here is a snippet which demonstrates the use.](https://play.golang.org/p/imeuxw8JirM)

## 2. Enabling encryption
We have discussed a few options, e.g. using drone secret for a key and another flag to enable encryption, but we ended up agreeing that when a user needs to specify another env variable, they might as well specify an encryption key itself which will also serve as a flag to enable encryption.
`DRONE_ENCRYPTION_KEY=my-amazinglySecret_key!`.

## 3. Disabling encryption
Should drone support a migration from encrypted state to non encrypted state? Is there a use case you would want to support for such a feature? I can only think of this as a way to reencrypt the storage engine with a new key -> Disable encryption, migrate to plain text -> Enable encryption, migrate to encrypted values.

However, disabling of encryption would not be such a mundane task, as we still need the encryption key to load encrypted values and migrate them to plain text. This would mean that the second point - enabling encryption - would need to support this as two different env variables... key and flag instead of a single one.

## 4. Migration
So the encryption itself is pretty straightforward and relatively easy to implement, the main caveat is the migration of non-encrypted storage engine/what to do when user defines an encryption key on active database.

We have a few solutions but do not think either one of them is an ideal way to solve it so we would really welcome some input on this.

I will go from the simplest solution to the most difficult to implement (and probably the cleanest for the end result.)

### a) Breaking change, new major version
No migration needed, implement the encryption and inform users they need to readd secrets and registry credentials if they want to use it.

### b) Encryption flag column in the storage engine
All new secrets will be encrypted. Old secrets will remain in plain text.
Add DB migration to append secrets and registry table with a new boolean column `encrypted`. Old secrets will remain in plain text while newly added become encrypted. This will allow users to only readd secrets which they need to have encrypted.

### c) Automatic migration
This is where we strugle, because the migration is on an application level, we cannot use the standard sql migrations.

1. This would effectively mean we would need a flag in the storage engine, whether the secrets are encrypted, as there is no safe way to determine this from the secrets themselves.
The process would be as follows:
Check for encryption key -> if encryption key is provided , check whether the secrets are encrypted -> if not, fetch all secrets and store them encrypted
If disabling would be supported:
Check for encryption key -> if encryption key is provided, check for encryption_on flag -> if the flag is not set check whether the secrets are encrypted -> if yes, fetch all secrets using the encryption key, decrypt them, store as plain text.

2. Or we would need an SQL migration which would add a boolean column same as in b) with default `false`. Then we would fetch all secrets, encrypt them and change the column flag to `true`. After the migration, the column could be removed. The problem is that we cannot hook between sql migrations, so we cannot do this:
- add `encrypted` column to secrets
- migrate secrets
- remove `encrypted` column from secrets

which effectively means we would either need to
Keep the column there (not nice)
or
Do not use default sql migrations (not cool)

## Additionally, DB Migrations:
SQLITE [defines secret value as TEXT](https://github.com/drone/drone/blob/master/store/datastore/ddl/sqlite/files/007_create_table_secets.sql), we would probably need BLOB for the encrypted value, or store the value as base64encoded string. But simple SQL migration will solve this.

Mysql defines the value as MEDIUMBLOB, postgres as bytea, so we are fine there
As far as registry credentials go, all are stored as VARCHAR(8000) or TEXT, so all storage engines need to be migrated to blob/byte.

**Comment by tboerger** [comment]
IMHO the db can stay like it is, if you want to have something more secure you should stick with vault. But these are just my 2 cents.

**Comment by Sharsie** [comment]
I don't think this is about wanting something more secure, it's rather about protecting drone users who are not even aware their credentials are being exposed. As I already mentioned on discourse I believe this is an information which drone users should be made aware of at least through documentation. As an example, our team gave me permission to migrate drone from 0.5 to 0.8, giving me access to the database in the process, without even realizing that by doing this I also gained access to some production databases and ssh keys used for deployments.

Being a security freak I am I immediately freaked out. Imagine a similiar developer with not so good intentions who does not really like his company... and then everybody wonders what went wrong and how could it happen and we hear the same story all over again

But honestly...If there is a possibility of eliminating even a single attack vector, given the issue is not that complex to implement, I don't see how someone, in this day and age, can be even slightly against it.

**Comment by tboerger** [comment]
> Being a security freak I am I immediately freaked out. Imagine a similiar developer with not so good intentions who does not really like his company... and then everybody wonders what went wrong and how could it happen and we hear the same story all over again

But in that case I'm pretty sure you also got access to the encryption key, so this seems to be security be obscurity :)

> But honestly...If there is a possibility of eliminating even a single attack vector, given the issue is not that complex to implement, I don't see how someone, in this day and age, can be even slightly against it.

I'm not really against it, but at least for me it feels more like security by obscurity. And in the end it's absolutely not my decision if this gets integrated or not ;).

**Comment by Sharsie** [comment]
> But in that case I'm pretty sure you also got access to the encryption key, so this seems to be security be obscurity :)

Hmm, I think we are not on the same note :) I understand that security through obscurity is probably the worst kind of security and I am also strongly against using such solutions.

But in this case, the encryption key should never be stored in the database, it should be configured on the server side. In case of sqlite, it does not make much difference, unless the db is elsewhere

**Comment by miketonks** [comment]
I would love to see a new drone feature adding encryption of the secrets stored in the DB.  This seems like a common approach.  In fact I'm surprised to find drone doesn't do this already, given the kind of secrets it's likely people will want to store.

I agree the encryption key should not be stored in the DB!

**Comment by bradrydzewski** [comment]
https://readme.drone.io/install/server/storage/encryption/
