### ISSUE TITLE
Support of the native builds without Docker.

### ISSUE THREAD

**Issue by XVilka** [drone/drone#2378]
Would be nice if you will reconsider the support of the "native" builds without Docker usage. There are many projects that own their servers, thus the using Docker just wastes the performance which can be used for building itself. Currently we are using Jenkins but it would be awesome to finally ditch it in favor of more lightweight solution (and less control complexity).

**Comment by bradrydzewski** [comment]
native builds remains out of scope. If something changes we will re-open https://github.com/drone/drone/issues/135
