### ISSUE TITLE
drone stopped working with error mesage: panic recovered

### ISSUE THREAD

**Issue by cyberb** [drone/drone#2384]
Drone server was working fine for few months and now it stopped showing any project content.

![screenshot from 2018-03-23 18-42-26](https://user-images.githubusercontent.com/885528/37847834-164d6d88-2eca-11e8-88fe-9fbb31a307b2.png)

2018/03/23 18:35:36 [Recovery] panic recovered:
GET /api/repos/syncloud/nextcloud/builds HTTP/1.1
Host: build.syncloud.org
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Cookie: __test=1; __utma=18921914.710776845.1470082672.1520632009.1521506569.54; __utmz=18921914.1521506569.54.3.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/; user_sess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjIwNjM1MzYsInRleHQiOiJjeWJlcmIiLCJ0eXBlIjoic2VzcyJ9.GBJ3r4DznWPApqQLfu-lxvNqFG4q8bxSz_TOpmBXfAE
Pragma: no-cache
Referer: http://build.syncloud.org/syncloud/nextcloud
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:489 (0x430c3f)
/usr/local/go/src/runtime/panic.go:63 (0x42faee)
/usr/local/go/src/runtime/signal_unix.go:290 (0x445d1f)
/go/src/github.com/drone/drone/remote/github/github.go:209 (0x9f2c11)
/go/src/github.com/drone/drone/router/middleware/session/repo.go:97 (0x8646ed)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/session/repo.go:50 (0x863d10)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/token/token.go:26 (0x8656e7)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/session/user.go:68 (0x864ba2)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/store.go:15 (0x963947)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/contrib/ginrus/ginrus.go:26 (0x963d9f)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/header/header.go:25 (0x85c720)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/router/middleware/header/header.go:17 (0x85c6c9)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/recovery.go:45 (0x85a38a)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 (0x84c0fa)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:284 (0x851f30)
/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:265 (0x85184b)
/usr/local/go/src/net/http/server.go:2568 (0x6c8d02)
/usr/local/go/src/net/http/server.go:1825 (0x6c4ea2)
/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45f7d1)

**Comment by leibowitz** [comment]
A bit strange, but mine was working fine and stopped working about 15 minutes ago.

I wonder why ... maybe the github api is returning content differently? I would be surprised, but I'm really intrigued by this one.

**Comment by bradrydzewski** [comment]
see https://github.com/drone/drone/issues/2383 and https://discourse.drone.io/t/github-api-regression-nil-pointer-error/1983

**Comment by mvdan** [comment]
@cyberb did you mean to post your user session cookie?

**Comment by bradrydzewski** [comment]
@mvdan good catch, I scrubbed the original post

**Comment by cyberb** [comment]
Thanks, was in the rush  :)
