### ISSUE TITLE
Builder images are not cached when using multi-staged build Docker feature

### ISSUE THREAD

**Issue by lukassup** [drone/drone#2388]
I am using `plugins/docker` w/ [multi-stage build feature](https://docs.docker.com/develop/develop-images/multistage-build/) to build a simple Golang app. The Dockerfile looks similar to this:

```Dockerfile
FROM golang:1.10 as build
WORKDIR /go/src/github.com/lukassup/my-app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get -ldflags='-s -w' .

FROM scratch
COPY --from=build /go/bin/my-app /bin/my-app
ENTRYPOINT ["/bin/my-app"]
```

Currently `golang:1.10` is pulled each time the build step is triggered. Can I have the build image NOT pruned instantly and/or persist on the main Docker daemon?

**Comment by bradrydzewski** [comment]
The issue tracker for the docker plugin is github.com/drone/drone-docker. However, per our issue template we politely ask that you use our [mailing list](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md) for end-user support before creating issues. Thanks!
