### ISSUE TITLE
Test coverage badge / report

### ISSUE THREAD

**Issue by steffenmllr** [drone/drone#239]
First off thanks for done, it's a great project. I'm testing a couple of nodejs projects at the moment and was asking myself if there is a way to display my coverage results ?

I'm thinking something in the line of:

```yaml
coverage:
  - npm run coverage
```
Which produces a stdout in percent and gets saved to the sqlite and displayed in a nice bagde. Is there a way to make that happen ?

**Comment by davidak** [comment]
i would like to save different metrics for every build and get nice graphs over time.

for example to see if the tests take longer from a specific commit on.

or if the commits from one person make the code always slower.

also there could be different graphing types that can get selected for each metric.

http://www.chartjs.org/
http://www.flotcharts.org/

**Comment by bradrydzewski** [comment]
@davidak I would love this too. My biggest concern, however, is the ability for Drone to create a data structure that is generic enough to support such a diverse group of metrics and display requirements. Can we create something that will ever be good enough for all use cases? Or would we end up with something marginal at best that everyone complains about?

Can Drone report coverage as well as [Coverall](https://coveralls.io/)? Or dependency stats as well as [David DM](https://david-dm.org/)? Or code quality as well as [Code Climate](https://codeclimate.com/)?

Unfortunately all of the above are closed source. Would we be better off putting our effort into standalone, open source alternatives to the above tools? And then ensure they integrate seamlessly with Drone? Drone has a pretty engaged and motivated community, and I think we could definitely rally the community around such an effort.

**Comment by davidak** [comment]
we should start with simple coverage since it belongs to tests and we are running them.

as you said cobertura is a widely used format that most language support somehow.

that could be plugins that can be used somewhere else but i don't want to rely on external services.

maybe there is already code to display the result of coverage (per file, changes between build, trend, ...).

**Comment by bradrydzewski** [comment]
I think the path forward is something similar to the GitHub Status API for Drone.

We can create a Drone Status API that allows a 3rd party system to tag a commit with a very simple set of meta-data. We can surface this meta-data in the Drone user-interface along with a link to the detailed results in the 3rd party system.

We (the Drone team) can kick-off open source alternatives to these third party systems if we need to. It will honestly be easier to create these systems from scratch than cram all of this functionality into Drone. We could put engineering effort into making this simple and seamless. It could be as simple as 1 extra binary that you need to download and run.

**Comment by davidak** [comment]
sounds good. so we would have the overall coverage percentage for each build in drone and by clicking on it we get to a report in another tool that is hosted on the same server.

**Comment by bradrydzewski** [comment]
closing in favor of drone's sister project (coverage server and plugins) found at https://github.com/drone-plugins/drone-coverage as well as the proposal for the status api at https://github.com/drone/drone/issues/927

**Comment by Depado** [comment]
As the [drone-plugins/drone-coverage repository](https://github.com/drone-plugins/drone-coverage) is deprecated as it is (see drone-plugins/drone-coverage#27), should we reopen this issue to discuss the potential test coverage/badge thing ? As it seems it will be integrated in drone ?

**Comment by mvdan** [comment]
Agreed with @Depado - looking for a way to set up code coverage with Drone, and all we would really need is for it to be integrated with the web UI or to be able to have a badge.

**Comment by Graffine** [comment]
+1. We really need a way to integrate coverage rate with web UI to have a coverage badge.

**Comment by r-moiseev** [comment]
Any update on this? We need this feature too

**Comment by rcdailey** [comment]
Would be nice to hear from @bradrydzewski

**Comment by posquit0** [comment]
Would be nice to hear from @bradrydzewski
