### ISSUE TITLE
Drone not building the current version of a pull request

### ISSUE THREAD

**Issue by SebastianStehle** [drone/drone#2390]
Hi, 

I have the following config: https://github.com/Squidex/squidex/blob/master/.drone.yml

Basically it runs on tags, master branch and pull-requests. On other branches it just does nothing.

I have the following pull request with 3 commits:

![capture2](https://user-images.githubusercontent.com/1236435/38100945-18f42f72-337f-11e8-8673-93e5f48169da.PNG)

In the next screenshot you see that drone is running twice for each commit (I also retried the second build). One time for the branch (Where it basically does nothing and completes within seconds) and the other time for the pull request. But the build for the pull-request is using the old commit and not the current version at this point of time.

![capture](https://user-images.githubusercontent.com/1236435/38100957-22e557e0-337f-11e8-9c81-03dc57fb1079.PNG)

I have no idea what I am doing wrong, it happens from time to time.

**Comment by bradrydzewski** [comment]
Please see https://discourse.drone.io/t/planned-change-to-git-clone-logic/1165

I'm am going to close this because it is a git plugin issue, as opposed to an issue with Drone core, and because we a new experimental image available for people to test.

**Comment by SebastianStehle** [comment]
It seems to build now, but the UI still shows the old commit message.

**Comment by SebastianStehle** [comment]
Sorry, I have forgotten to mention that I use your fix.

**Comment by bradrydzewski** [comment]
> I have forgotten to mention that I use your fix.

ah great. If you experience any issues with the experimental git plugin, please provide feedback in the discourse thread. Thanks :)
