### ISSUE TITLE
Integrate gitlab ce 8.9.9 got the authentication error

### ISSUE THREAD

**Issue by koala2012** [drone/drone#2392]
my gitlab version is gitlab ce 8.9.9

I used oauth to connect via drone 0.8, but I when I authorized the app got following error,

this error pop out from drone logs

level=error msg="can not authenticate user. invalid character '<' looking for beginning of value"

**Comment by bradrydzewski** [comment]
Please use our mailing list for end-user support. discourse.drone.io
