### ISSUE TITLE
Build specific branch and all pull requests

### ISSUE THREAD

**Issue by mrdziuban** [drone/drone#2393]
Right now we can specify that pipelines should only run on certain branches, which makes it so that pushes and pull requests against that branch are executed, but is there a way to make it so builds are always run on pull requests regardless of the target branch?

**Comment by bradrydzewski** [comment]
Not at this time. We will update https://github.com/drone/drone/issues/2064 when a solution is in place

**Comment by mrdziuban** [comment]
Thanks @bradrydzewski, I'll subscribe to that and keep an eye out for updates.
