### ISSUE TITLE
version control system not configured

### ISSUE THREAD

**Issue by xujialiang** [drone/drone#2403]
I use coding.net , but not work

**Comment by tboerger** [comment]
The error clearly say that a version system like coding is not correctly configured. Beside that please follow the issue template where it's kindly requested to put support questions on discourse.drone.io

**Comment by eyeye** [comment]
I encounter this issue too.

When use drone from latest docker image, setting DRONE_CODING=true has no effect, result: "version control system not configured".

When build drone from git source code, It's works.

**Comment by eyeye** [comment]
I found
```
go build -ldflags '-extldflags "-static" -X github.com/drone/drone/version.VersionDev=build.'${DRONE_BUILD_NUMBER} -o release/drone-server github.com/drone/drone/extras/cmd/drone-server
```
at .drone.sh, but I can't find the `github.com/drone/drone/extras/cmd/drone-server` extras directory, Isn't that the problem?

**Comment by bysir-zl** [comment]
@eyeye i found `git clone git@github.com:drone/drone-enterprise.git extras` at drone.sh

so release/drone-server build from `git@github.com:drone/drone-enterprise.git/cmd/drone-server`, i think drone-server in `git@github.com:drone/drone-enterprise.git` not supported coding.

**Comment by bysir-zl** [comment]
@eyeye  i tryed build drone from git source code , but it has other problem : `sql: unknown driver \"sqlite3\" (forgotten import?)`, how you do that?

**Comment by bradrydzewski** [comment]
this is now fixed in `drone/drone:latest`
