### ISSUE TITLE
Tiny Whoop F3 Board not Working

### ISSUE THREAD

**Issue by spartan-fpv** [drone/drone#2404]
I have recieved a Tiny Whoop Pro F3 board and other standard components for building a Tiny Whoop. I attached the camera vtx combo straight to the battery port, like I have done in the past with an Eachine E100 clone. But, when attached, Motor 1 doesn’t spin. I disconnected the camera, and tried flying the drone, and it flew. I have no idea why it is doing this. I then after attached the camera to the designated OSD ports, and it did the same thing. I tried lowering the motor rate down to 1000, and that led to each individual motor starting at different times when the camera was not attached. The motors are brand new. The batteries are brand new. Please someone help!!!!

**Comment by bradrydzewski** [comment]
please do not post here again
