### ISSUE TITLE
not work username number (GitLab)

### ISSUE THREAD

**Issue by andruwa13** [drone/drone#2407]
Does not want to work correctly with the user in which the numbers begin  (3_1_3_u)
do not display all repo
![welcome drone 2018-04-25 14-30-54](https://user-images.githubusercontent.com/5846351/39243184-51c30460-4895-11e8-81f7-be463caf304f.png)
  
does not work Build (Build list is empty)

![welcome drone 2018-04-25 14-32-23](https://user-images.githubusercontent.com/5846351/39243243-861265b2-4895-11e8-8bd1-7c361a290740.png)

Another user is working
![webakcent_lab_bot 100migrantov ru drone 2018-04-25 14-34-18](https://user-images.githubusercontent.com/5846351/39243344-cb3e397c-4895-11e8-9b66-39c4c7db7a43.png)

**Comment by bradrydzewski** [comment]
👋 As indicated in our issue template we politely ask that you use our community forum for support prior to creating github issues. Thanks!
