### ISSUE TITLE
FAQ say Enterprise Edition is free (with constraints) but idea how to get it

### ISSUE THREAD

**Issue by kevb** [drone/drone#2410]
From the FAQ

> Drone Enterprise is free for entities with both: (a) annual gross revenue under (USD) $1 million (according to GAAP, or the equivalent in its country of domicile); and (b) less than (USD) $5 million in aggregate debt and equity funding. Support is not included.

I'm just a solo developer with no funding, so I assume I qualify. There's no details on how to take advantage of this. Would be great if you could provide some details.

Thanks!

**Comment by bradrydzewski** [comment]
discourse.drone.io for questions please
