### ISSUE TITLE
drone issues in docker swarm stack

### ISSUE THREAD

**Issue by ColorFuzzy** [drone/drone#2414]
1. docker stack in swarm mode doesn't support the `depend_on` keyword.
> If drone-agent starts in front of drone-server(almost most of the time), drone-agent will trigger a dns error.

solve:
> I have to start drone-server first and then start drone-agent

2. grpc fails with docker swarm virtual ip
> First, I succeed to run drone-server, and drone-agent.
> Then, I push code to trigger a build, everything works well.
> Last, I push code to trigger another build after about 6 hours, this build will always pending.

solve:
> I have to start drone-server first, and get its real IP. Then let drone-agent connects to drone-server with drone-server's real ip, not the hostname which points to a virtual ip.

**Comment by bradrydzewski** [comment]
:wave: hey there, as mentioned in our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), please use [discourse.drone.io](https://discourse.drone.io) for technical support and general questions.
