### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by codingfrombrazil** [drone/drone#2416]
Hello, some of us can't contribute with Go code for the project, but still, I would like to contribute with Drone. I think it's important for us users, to contribute, even if it is a small amount.

So, maybe consider a donate button, or Patreon. Some features could be crowdfunded or something.

This project really allow us to save some money, just look at the prices of CI/CD, beginners can't afford that prices D:  So the least we can do sometimes, is to give $5 dollars when we are able to.

I think it would benefit the project. Sorry if this has been discussed and I didn't see before.

**Comment by bradrydzewski** [comment]
Hey there, I appreciate the sentiment. We decided against donations, however, the best way to help sponsor the project is to convince your employe to purchase an enterprise license, which includes extra features and access to our Slack channel. More information here https://drone.io/enterprise/

If your company is not in a position to purchase a license, no worries. There are other ways to help the community including translating documents into your native language, giving talks, writing blog posts or tweeting about Drone to spread awareness. And to be honest, a simple Thank You is more than enough 😄

**Comment by codingfrombrazil** [comment]
Thanks xD I understand.
