### ISSUE TITLE
[new metrics] drone_job_duration_seconds 

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2418]
`drone_job_duration_seconds `

Type: histogram

Purpose: tracks the duration of a drone job

Labels:
- org or repo (see note)
- status (success|failed)
- branch (see note, maybe just `master`/default and `other`?)

> Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
https://prometheus.io/docs/practices/naming/#labels

**Comment by metalmatze** [comment]
I'm not entirely sure if a counter (with the total seconds) doesn't make more sense here. It should be _really_ hard to come up with good buckets for this histogram.

**Comment by gtaylor** [comment]
This would be really useful for some of our teams who are wanting to track and reduce build times.

**Comment by bradrydzewski** [comment]
I agree with @metalmatze that implementing this in a generic way will be quite difficult, and there are concerns with cardinality. I would prefer the core server metrics focus on system performance and usage, as opposed to individual repository metrics.

I do agree that repository metrics are very useful to teams.

The compromise we have devised is to provide a way for teams to extract custom metrics from the system by creating a custom metrics provider. We have a boilerplate template that you can use to get you up and running quickly, and you can add new metrics with just a few lines of code

https://github.com/drone/boilr-metrics

I would encourage teams to publish their custom metrics providers and share with the community. We can find a place to share such projects in the official Drone documentation.
