### ISSUE TITLE
Registries should not contain HTTP schemes in their URL

### ISSUE THREAD

**Issue by puradox** [drone/drone#2425]
When adding Docker registries, adding registries with a scheme such as `http://` or `https://` will result in unexpected behavior. Drone will happily add the registry with a scheme, but is unable to remove or update the same registry due to conflicts in routing. For example, `DELETE /api/repos/{owner}/{repo}/registry/https://123.dkr.ecr.us-west-2.amazonaws.com` will result in the following response:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="version" content="0.8.4&#43;build.1398">
<script>
	window.DRONE_USER = {"id":1,"login":"puradox","email":"[...]","avatar_url":"https://avatars0.githubusercontent.com/u/941763?v=4","active":false,"synced":1527875693,"admin":true};
	window.DRONE_SYNC =  false ;
	window.DRONE_CSRF = "[...]"
</script>
<link rel="shortcut icon" href="/favicon.png"></head>
<body>
<script type="text/javascript" src="/static/vendor.fc7f2b27186ea985e44c.js"></script><script type="text/javascript" src="/static/bundle.467f73292ec23d1702cb.js"></script></body>
</html>
```

The same request using the Drone CLI will result in the error, `invalid character '<' looking for beginning of value`.

Perhaps it would be helpful to new users if there was a small snipet in the documentation on valid registry URLs. It took me a few hours of debugging and reading source code to discover this small, but important, requirement.

Futhermore, it could be beneficial to check for invalid registry URLs upon creation to ensure expected behavior for all other registry endpoints.

**Comment by bradrydzewski** [comment]
this will be patched in 0.9. Lets track this under https://github.com/drone/drone/issues/2334
