### ISSUE TITLE
Add Rebuild button to UI

### ISSUE THREAD

**Issue by Niondir** [drone/drone#2428]
I'm a little confused about the state of this issue. I would definitely need a UI button to simply trigger a build after adding a new Repo or Rebuilding a failed build.

From all the discussions I see there is also a lot of demand in the community and it seems like the REST API already exists and #318 also helped with rebuilding. But all the issues regarding the topic are closed:

https://github.com/drone/drone/issues/107 - Allow an option to retest without a commit
https://github.com/drone/drone/issues/126 - Manually force new builds
https://github.com/drone/drone/issues/148 - Should be able to retry build
https://github.com/drone/drone/issues/307 - Please add 'rebuild' button to rebuild any build that has finished
https://github.com/drone/drone/issues/497 - Empty page after creating repository

https://github.com/drone/drone/pull/318 - already enabled rebuilding
https://github.com/drone/drone/pull/158  - would need to be implemented again

**Comment by tboerger** [comment]
Triggering a "rebuild" without a commit is not possible, where should drone get the information that regulary gets sent by a GitHub webhook?

If there is already a build just get into the build, open the burger menu and you are able to rebuild this commit.

**Comment by bradrydzewski** [comment]
Please avoid creating duplicate issues.

**Comment by Niondir** [comment]
> If there is already a build just get into the build, open the burger menu and you are able to rebuild this commit.

Okay thanks, found the button. Was just hidden to well. 

With the initial build, that's fine.
