### ISSUE TITLE
flair requirement on reddit

### ISSUE THREAD

**Issue by Sabotaz** [drone/drone#2429]
Hello,
I tried to post an issue about usage on reddit, but I couldn't :(
It says "Post must contain post flair", but there is no flair in this subreddit...

![image](https://user-images.githubusercontent.com/187283/40964940-ab3a55c0-68ac-11e8-9436-67f2738eff19.png)
Please turn the flair requirement off, or add some flairs :)

Thanks !

**Comment by Sabotaz** [comment]
yes really sorry to post there, but i couldn't post somewhere else :(
I tried to post on discourse, but it said "Sorry, access to this forum is by invite only."
Finally, i posted on reddit (about docker USER) using the "old reddit", so i didn't put any flair on my post.

**Comment by bradrydzewski** [comment]
no worries, it is my fault, because in this case I didn't read your post closely enough. I will make sure we get the flair thing squared away, and in the meantime, will take a look at your post on reddit to see if I can answer :)
