### ISSUE TITLE
Generate next step for the current pipeline in a generic way

### ISSUE THREAD

**Issue by vbrandl** [drone/drone#2433]
Is it possible for a plugin to generate the next step in the pipeline in a generic way (or could it be implemented)? This would make it possible to provide opinionated defaults to build projects (kinda like travis). You could implement a plugin that detects build tools, the used language, ... and perform a default build. E.g. if a pom.xml is present in the cloned repository -> use `maven:latest` and execute `mvn install && mvn test`.

Just as drone is opinionated to use git to clone the repository, many projects could be build that way without a need to create a `.drone.yml`. So if no configuration is present in a repositroy it would default to `plugin/git -> plugin/opinionated-build -> what ever is returned by the previous step`.

I think this might already be possible by using Docker in Docker and performing the build inside the same container as the detection plugin but it would be cleaner to generate a separate step in the pipeline for the build itself.

**Comment by bradrydzewski** [comment]
This is not something that is possible with the current yaml configuration. There is an exploratory effort to support a javascript build script (e.g `.drone.js` file) as an alternative to the the yaml configuration file. If the `.drone.js` proposal is adopted something like this would be possible, however, it is not something we are considering providing with the yaml integration.
