### ISSUE TITLE
[feature] Add Pull Request support for Bitbucket Server (stash) with WebHook

### ISSUE THREAD

**Issue by prabdeb** [drone/drone#2435]
I did some work regarding this enhancement, please find the details below. Need your help with suggestions/comments to find best possible way to get it implemented. 

**Implementation:** Drone Bitbucket Server driver is written with [WebHook](https://confluence.atlassian.com/bitbucketserver059/managing-webhooks-in-bitbucket-server-949255017.html) that supports Push/Tag/Pull Request Events.

**Known Issues:** 

1. Bitbukcet WebHook Pull Request Update event feature is missing - https://jira.atlassian.com/browse/BSERV-10279
2. Bitbukcet WebHook Push/Tag event commit message not there in payload - https://jira.atlassian.com/browse/BSERV-10278

**Workarounds for knows issues:**

1. Used Bitbukcet PR Comment event and an additional configurable field DRONE_STASH_PR_COMMANDS to support command that will trigger the update event.
2. Used some custom message - Repository.Project.Key/Repository.Slug - Changes[0].RefID - pipeline

**Concerns:**

1. Current pipelines on-boarded with Bitbucket Post hook, needs to re-on-boarded with WebHook, by manually disabling all the repositories and re-enabling them post upgrade.

**Implementation:** https://github.com/drone/drone/compare/master...prabdeb:feature/pull_request_bb_server

**Comment by dtandon** [comment]
This feature is critical for Drone integration w/ BB Onprem installations and it would be good if it can be priortized

**Comment by bradrydzewski** [comment]
hey there, just wanted to provide an update. I have downloaded Bitbucket Server (5.11) and am actively working on improving the current implementation. Progress can be tracked at https://github.com/drone/go-scm/tree/master/scm/driver/stash

**Comment by prabdeb** [comment]
Thanks @bradrydzewski, this looks great, please do let me know if I can help with any feature w.r.t. stash new driver!

**Comment by bradrydzewski** [comment]
Bitbucket Server (Stash) now has feature parity with GitHub, including support for pull requests, in our latest 1.0.0-rc.1 release.
