### ISSUE TITLE
Drone can't handle JSON files.

### ISSUE THREAD

**Issue by clanstyles** [drone/drone#2439]
I was trying to make Drone work with a JSON file and it wouldn't process the file right. I added it as a secret and cleaned it up with the ```jq``` tool. I then imported the secret 
```   
 secrets:
      - source: gc-service-account
        target: service_account
```

I tried to echo it to the file system, so bazel could mount the credentials. And the JSON isn't formatted right anymore.

Any recommendations?

**Comment by bradrydzewski** [comment]
there are no known issues using json secrets with drone. The gcr token, for example, is a json file and works without issue with the gcr plugin. If you are having issues with secrets, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), you should start a thread in our mailing list as opposed to creating github issues. thanks!
