### ISSUE TITLE
Optional Automatic Purging

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2440]
Provide the ability to retain the last N builds per-repository (e.g. last 50 builds). When a new build is created the build history is pruned and older builds are deleted from the database. This will be an optional, opt-in feature, and N will be configurable.

**Comment by matthax** [comment]
What is the current behavior? Are all build records kept indefinitely?

**Comment by tboerger** [comment]
> What is the current behavior? Are all build records kept indefinitely?

That's currently the case yeah

**Comment by patrickjahns** [comment]
Would it be possible to also say date as metric? On a system with a lot of builts - it might not reflect the history as much as saying - keep builds for X amount of days

**Comment by w-flo** [comment]
Maybe it's a good idea to also add a special pipeline step related to this? Maybe using the "when: event:" syntax. It could be useful to clean up build artifacts, e.g. delete a docker image from the docker registry. Obviously, someone (most likely the .drone.yml author) needs to take into account that some pipeline steps might have failed, so it's possible there are no artifacts to delete.
If drone keeps track of which "build" is currently deployed in at least one environment, it would be nice to be able to exclude those builds from automatic purging.

**Comment by bradrydzewski** [comment]
The plan is to expose a `DELETE /api/repos/{owner}/{name}/builds` endpoint with a few different query parameters to control the purge behavior. `?before={number}` will purge builds before the given build number, and `?retain={number}` with retain the last `N` builds.

This will let you setup some sort of regular cron task to purge builds, or they use the global webhooks for event-driven purging.

This approach is in line with our philosophy of supporting advanced functionality through plugins and extensions, while keeping Drone core simple and focused.

**Comment by bradrydzewski** [comment]
purge endpoint shipped in 1.0

**Comment by lizhenwei** [comment]
@bradrydzewski hi ,I am new drone user, and I have 5G sqllite database,I find all drone doc. but not find this purge endpoint,  can you tell me ,how to use it? thank you every much

**Comment by lizhenwei** [comment]
> 该计划是公开一个`DELETE /api/repos/{owner}/{name}/builds`带有几个不同查询参数的端点来控制清除行为。`?before={number}`将清除给定构建号之前的构建，并`?retain={number}`保留最后的`N`构建。
> 
> 使用此端点，您可以创建常规 cron 任务来清除构建，使用全局 Webhooks 进行事件驱动的清除，或者提出根据您的使用和保留要求进行优化的您自己的独特逻辑。
> 
> 这种方法符合我们通过插件和扩展支持高级功能的理念，同时保持 Drone 核心简单和专注。

I find this doc,https://docs.drone.io/api/builds/build_stop/ ,but this is stop ,not purge log , please help me ,I dont' find the resolve method~
