### ISSUE TITLE
Validate event restrictions for Secrets

### ISSUE THREAD

**Issue by markcwhitfield** [drone/drone#2447]
It seems that currently neither the CLI nor database validate the `events` a secret is restricted to. This means that e.g.

`drone secret add ... --event tag,push,pull_request`

Will create a secret only usable by the nonexistent event `"tag,push,pull_request"` rather than the obviously intended behavior (or failure). The UI will also display the event as this same comma-delimited string, which appears to be a valid value at first glance. Combined with #2423 this can result in secrets issues that are very difficult to diagnose.

**Comment by bradrydzewski** [comment]
this changed in 1.0.0-rc.1 and is no longer applicable. For secrets stored in the database there is a single `--pull-request` flag (boolean). For more complex restrictions plugins must be used.
