### ISSUE TITLE
Build list is empty

### ISSUE THREAD

**Issue by JoeyX-u** [drone/drone#2448]
[root@i-w65sq82a docker-yaml]# docker ps
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS                    PORTS                                                           NAMES
0297260c4454        harbor.aaa.com/kubernetes/drone-agent:latest   "/bin/drone-agent ..."   11 minutes ago      Up 11 minutes (healthy)   3000/tcp                                                        dockeryaml_drone-agent_1
108e903ed67a        harbor.aaa.com/kubernetes/drone:latest         "/bin/drone-server"      11 minutes ago      Up 11 minutes             80/tcp, 443/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:80->8000/tcp   drone-server
[root@i-w65sq82a docker-yaml]# docker logs 0297260c4454
{"time":"2018-07-03T09:10:26Z","level":"debug","message":"request next execution"}
[root@i-w65sq82a docker-yaml]# docker logs --tail=10 108e903ed67a
[GIN-debug] GET    /api/debug/pprof/block    --> github.com/drone/drone/server/debug.BlockHandler.func1 (13 handlers)
[GIN-debug] GET    /api/debug/pprof/threadcreate --> github.com/drone/drone/server/debug.ThreadCreateHandler.func1 (13 handlers)
[GIN-debug] GET    /api/debug/pprof/cmdline  --> github.com/drone/drone/server/debug.CmdlineHandler.func1 (13 handlers)
[GIN-debug] GET    /api/debug/pprof/profile  --> github.com/drone/drone/server/debug.ProfileHandler.func1 (13 handlers)
[GIN-debug] GET    /api/debug/pprof/symbol   --> github.com/drone/drone/server/debug.SymbolHandler.func1 (13 handlers)
[GIN-debug] POST   /api/debug/pprof/symbol   --> github.com/drone/drone/server/debug.SymbolHandler.func1 (13 handlers)
[GIN-debug] GET    /api/debug/pprof/trace    --> github.com/drone/drone/server/debug.TraceHandler.func1 (13 handlers)
[GIN-debug] GET    /metrics                  --> github.com/drone/drone/server/metrics.PromHandler.func1 (12 handlers)
[GIN-debug] GET    /version                  --> github.com/drone/drone/server.Version (12 handlers)
[GIN-debug] GET    /healthz                  --> github.com/drone/drone/server.Health (12 handlers)
[root@i-w65sq82a docker-yaml]# 

[root@i-83agzcfh incubator-dubbo-dubbo-2.6.2]# ls
Dockerfile  main.go  main_test.go  README.md
[root@i-83agzcfh incubator-dubbo-dubbo-2.6.2]# cat .drone.yml 
workspace:
  base: /go
  path: src/gogs.aaa.com/lihongfeng/first

pipeline:
  test:
    image: golang:1.10.2
    commands:
      - go test
  build:
    image: golang:1.10.2
    commands:
      - go build
  publish:
    image: plugins/docker
    repo: kikajack/first
    dockerfile: ./Dockerfile
    tags: latest
    # registry: https://harbor.aaa.com
    secrets: [ docker_username, docker_password ]
  # deploy:
  #   image: appleboy/drone-ssh
  #   host:
  #     - your_host
  #   username: your_name
  #   password: your_pass
  #   port: 22
  #   command_timeout: 300 
  #   script:
  #     - docker pull repo_url:latest
  #     - docker rm -f docker-demo || true 
  #     - docker run -d -p 8065:8065 --name docker-demo repo_url
  #     #######

![image](https://user-images.githubusercontent.com/40482665/42211595-8fa314a0-7ee6-11e8-8fda-2e37041d95b8.png)

![image](https://user-images.githubusercontent.com/40482665/42211611-98523a9a-7ee6-11e8-8e45-90808f661b7c.png)

**Comment by tboerger** [comment]
If you have nothing pushed after activation of drone there can't be any build.

Beside that please follow the issue template, support requests should be done via reddit or stackoverflow, the issue tracker is reserved for confirmed bugs or feature requests.
