### ISSUE TITLE
Honor DRONE_HOST setting in the shared/httputil

### ISSUE THREAD

**Issue by titpetric** [drone/drone#2449]
The `DRONE_HOST` environment variable should be the canonical way to set a hostname of the drone instance. In the shared/httputil package however, the scheme/hostname is autodetected, possibly also exposing server misconfiguration (ie, no X-Forwarded-Proto headers). I'd suggest to use DRONE_HOST setting always and *only falling back to auto-detect if it's not set*. (actually, from what I read, DRONE_HOST is a required setting so it makes no sense to have autodetection here).

**Comment by bradrydzewski** [comment]
this change has already been made in the 0.9 codebase, and will be available in 0.9-rc.1

**Comment by titpetric** [comment]
Great! Thanks.
