### ISSUE TITLE
Is secret logging using correct logic?

### ISSUE THREAD

**Issue by tcely** [drone/drone#2451]
https://github.com/drone/drone/blob/a85f89a3c188ea9eba0991c483bb2a2b9e855377/cmd/drone-agent/agent.go#L270

It looks like secrets with Mask true shouldn't have their value added here. Am I missing something?

**Comment by bradrydzewski** [comment]
Secret masking was removed from 0.8, so this is dead code. In 0.9 we are implementing a new runtime library which implements secret masking, here [here](https://github.com/drone/drone-runtime/blob/master/runtime/line.go#L54). Lets move any discussion to our forum https://www.reddit.com/r/droneci/
