### ISSUE TITLE
Option to configure a service account when enabling repos/webhooks

### ISSUE THREAD

**Issue by ortizmj12** [drone/drone#2460]
The current way repo webhooks are enabled (http://docs.drone.io/hooks/) has bit us a few times. We've had a few situations:
- The user on the team hasn't been given admin permissions on their git repo yet
- The team is getting help setting up their Drone configs and the person helping enables the repo instead
- The user who enabled the repo in Drone left the company. So when their account was disabled and permissions removed from the git repo it broke the webook.

It would be really useful if we were able to configure a service account to be used when enabling the repo in Drone.

**Comment by tboerger** [comment]
Most people create an admin account for that, beside that there should be a chown command for the cli. That's also a way to move the ownership after the activation automatically.

**Comment by bradrydzewski** [comment]
I am going to combine this with #2422 , support for GitHub Applications, which solves for the exact problem described in this issue. GitHub Applications centralizes webhooks and authentication tokens (for cloning the repository) which will eliminate this issue entirely.
