### ISSUE TITLE
drone:server:"INFO: 2018/08/17 11:26:02 transport: http2Server.HandleStreams received bogus greeting from client: "GET / HTTP/1.1\r\nHost: 19""

### ISSUE THREAD

**Issue by yangwenmai** [drone/drone#2471]
message: `INFO: 2018/08/17 11:26:02 transport: http2Server.HandleStreams received bogus greeting from client: "GET / HTTP/1.1\r\nHost: 19"`
when I visit `http://my_local_ip:9000`.
and curl http://my_local_ip:9000

```
 ➭ curl http://192.168.0.56:8000/version
{"source":"https://github.com/drone/drone","version":"0.8.6+build.1534"}
 ➭ curl http://192.168.0.56:9000
��%
```

But I visit  `http://my_local_ip:8000` is ok.

I don't known that' why, please give me a advice for those error.

And It is strange that Before is normal.

**Comment by bradrydzewski** [comment]
👋 Hey there! Per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), please use our [community forum](https://discourse.drone.io) for end-user support.
