### ISSUE TITLE
Adding the option to allow admin to assign custom hash when creating/updating user

### ISSUE THREAD

**Issue by beeonthego** [drone/drone#2473]
Hi,

Thanks for all the contributors for making this great open source project. 

We are building an app and integrating single sign-on for Gitea and Drone. The idea is when a user creates a new repo or adds a deployment key, a private SSH key will be automatically generated and saved in drone, and the public SSH key will be saved in Gitea. 

To achieve this, we need to know the user hash, and generate a token to authenticate the user with Drone API, sync repo, activate repo, and save the secret. This can not be easily done with the token of Drone admin user.

We have slightly modified the User data type in drone-go client and server side implementation to allow admin users to opt in and assign custom user hash when creating/updating user account in Drone.   Since this is opt-in, current installation will not be affected. Current user hashes will continue to work after enabling this feature. Is this something that other developers might be interested?  Would you consider accepting this feature? 

Cheers!

**Comment by bradrydzewski** [comment]
drone 1.0 now supports machine users where you provide their token at the time of creation.
