### ISSUE TITLE
I'm stuck in the loop.

### ISSUE THREAD

**Issue by cswww** [drone/drone#2476]
I'm stuck in the loop.
repeat “click to login"
![2018-09-04 1 16 06](https://user-images.githubusercontent.com/30970064/44997411-b50f1600-afe0-11e8-815a-5f9069c4fb4a.png)
![2018-09-04 1 16 27](https://user-images.githubusercontent.com/30970064/44997412-b7717000-afe0-11e8-8459-9d62f2e31319.png)

docker run \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  --volume=/var/lib/drone:/data \
  --env=DRONE_TLS_AUTOCERT=true \
  --env=DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID} \
  --env=DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET} \
  --env=DRONE_SERVER_HOST=${DRONE_SERVER_HOST} \
  --env=DRONE_SERVER_PROTO=http \
  --env=DRONE_RUNNER_CAPACITY=2 \
  --env=DRONE_LOGS_DEBUG=true \
  --publish=80:80 \
  --restart=always \
  --detach=true \
  --name=drone \
drone/drone:0.9.0-alpha.1-linux-arm

**Comment by bradrydzewski** [comment]
hi there, you have likely misconfigured your GitHub application configuration. Please note that we do not provide end-user-support in our GitHub issue tracker. Per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), we ask that you create a tread in our [support forum](https://discourse.drone.io/).
