### ISSUE TITLE
Failed to create the secret

### ISSUE THREAD

**Issue by nai6514531** [drone/drone#2478]
![image](https://user-images.githubusercontent.com/13310359/45090153-1ea63600-b141-11e8-8033-edc978e98685.png)
use cli also can not work：
![image](https://user-images.githubusercontent.com/13310359/45090215-4ac1b700-b141-11e8-9229-f5f491f01a56.png)
how should i do??

**Comment by tboerger** [comment]
👋 Hi there, please use our forum for end-user support. https://discourse.drone.io
