### ISSUE TITLE
Cancel button for matrix builds

### ISSUE THREAD

**Issue by jpds** [drone/drone#2484]
I have a pipeline which has 4 matrix builds, I can individually cancel the jobs by going to their individual pages and hitting cancel, but I'd like button to cancel all of them from the matrix view.

**Comment by bradrydzewski** [comment]
matrix builds are deprecated and will be removed in 0.9 in support of more powerful multi-machine pipeline primitives. I am going to close this issue since we won't be investing any more time in matrix in preparation for the next release.
