### ISSUE TITLE
[FEATURE] Display only short commit msg on overview

### ISSUE THREAD

**Issue by dennisschuerholz** [drone/drone#2486]
I just noticed drone displays the whole commit message (with removed linebreaks) in the overview and commit view:
![screenshot_2018-09-12 business kanzlei-schumacher-lipsius drone](https://user-images.githubusercontent.com/5845183/45391894-1e1c0c80-b625-11e8-87ad-4fc464e8f26a.png)
![screenshot_2018-09-12 business kanzlei-schumacher-lipsius drone 1](https://user-images.githubusercontent.com/5845183/45391902-2c6a2880-b625-11e8-8a06-de98f43e4cb3.png)

I would propose to only display the first line of a commit message in the overview (as it's popular around git softwares) and to display the whole message in the commit/build view (respecting linebreaks/whitespace, probably even rendering markdown). As an example I attached the view of the same commit in my gogs instance:
![screenshot_2018-09-12 business kanzlei-schumacher-lipsius 2](https://user-images.githubusercontent.com/5845183/45391996-9a165480-b625-11e8-9bf8-0eb8033f6ae1.png)
![screenshot_2018-09-12 business kanzlei-schumacher-lipsius](https://user-images.githubusercontent.com/5845183/45392000-9d114500-b625-11e8-8caa-bbdb4ea28bb1.png)

**Comment by bradrydzewski** [comment]
I believe this is resolved in the 1.0 user-interface, but if not we can open a new ticket at github.com/drone/drone-ui
