### ISSUE TITLE
Changing settings doesn't alter Github webhooks

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2489]
Changing repository settings doesn't alter Github webhooks. For example, we want to disable pull requests from triggering Drone builds but unchecking that checkbox doesn't change Github webhook settings.

**Comment by bradrydzewski** [comment]
This is the expected behavior.  These flags in the user interface are used to filter incoming webhooks. They are not meant to interact with or modify the github webhooks.

We have a discourse forum you can use if you have any further questions. Thanks
https://discourse.drone.io/
