### ISSUE TITLE
Document agent filtering

### ISSUE THREAD

**Issue by hnykda** [drone/drone#2491]
Hi,

it seems that agents can already filter builds based on some criteria, but I am unable to find any resource which would tell me how to do it and I am unable to parse it from go.

I haven't found a word about labels or agent selection in docs, not in the [old](http://docs.drone.io/getting-started/) nor [new](http://readme.drone.io) (?). I am not even sure it should be done on the agent side as env var or in the `.drone.yml`. Therefore, I consider this as an issue.

I found mentions and relevant code on these:

* https://github.com/drone/drone/issues/2472
* #2200 
* https://github.com/drone/drone/issues/2171#issuecomment-327589521
* https://github.com/drone/expr/blob/master/selector_test.go
* https://github.com/drone/drone/pull/2198
* https://github.com/drone/drone/pull/2199
* https://github.com/drone/drone/pull/2442

Is someone able to give me a short summary or reference, at least something we can extrapolate based on the source code?

**Comment by bradrydzewski** [comment]
this is a support matter, so lets move this to https://discourse.drone.io or if you prefer, https://github.com/drone/docs. Thanks!
