### ISSUE TITLE
Drone agent without volume

### ISSUE THREAD

**Issue by Diaoul** [drone/drone#2494]
I don't have permission to make host bind mounts so I need another way to connect to the docker daemon from within the drone-agent container as mounting `/var/run/docker.sock` is not possible:
```
failed to update service drone-ci_drone-agent: Error response from daemon: access denied:
no access to Service Create with [Host Bind Mounts], Service Update, on collection xxxxxxxx-xxx-xxx-xxx-xxxxxxxxxxxx
```
I have tried to add environment variables `DOCKER_TLS_VERIFY`, `DOCKER_CERT_PATH` and most importantly `DOCKER_HOST` but it doesn't seem like this is supported.

Is it possible to avoid using `/var/run/docker.sock` and use the `DOCKER_HOST` directly? I've searched half the day and couldn't find a satisfying answer.
If this is a feature you want to add I might be able to provide a PR with some pointers.

**Comment by bradrydzewski** [comment]
👋 hi there, this can likely be solved without a code change, but for end-user-support questions we kindly ask that you create a thread in our discourse forum. https://discourse.drone.io/. Thanks!
