### ISSUE TITLE
Substitution incorrectly parses commit hashes as scientific notation

### ISSUE THREAD

**Issue by drrt** [drone/drone#2498]
If your commit hash is, for example, `83e2010d8350e6ee7c735ff921e8d003c02ccdc2` the substitution `${DRONE_COMMIT_SHA:0:6}` will result in `inf`, which is the string golang uses when formatting numbers into strings when the number is too large to print.

**Comment by bradrydzewski** [comment]
If you are using substitution for a yaml attribute, I recommend quoting it to be safe:

`field: '${DRONE_COMMIT_SHA:0:6}'`
