### ISSUE TITLE
Error: Cannot match pipeline name with stage

### ISSUE THREAD

**Issue by DomHudson** [drone/drone#2506]
## Summary
I am trying to run the example `.drone.yml` just to verify my drone setup is correctly working. Regardless of what I put in this file I get an error saying: `Cannot match pipeline name with stage`. 

In the logs I see the same error
```
{"level":"error","repo":"dom/drone","build":2,"stage":1,"time":"2018-10-10T09:50:48Z","message":"cannot match pipeline name with stage"}
```

I've grepped through the code base to try and work out what this error means but cannot find where it is defined. I am unsure if it is a bug or if it is a genuine error in my configuration but I am using the example `.drone.yml` file.

```
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
```

Start command:
```
 docker run   --volume=/var/run/docker.sock:/var/run/docker.sock   --volume=/var/lib/drone:/data   --env=DRONE_TLS_AUTOCERT=false   --env=DRONE_GITEA_SERVER=http://XXXXX:3000   --env=DRONE_GITEA_SKIP_VERIFY=true   --env=DRONE_SERVER_HOST=XXXXX   --env=DRONE_SERVER_PROTO=http   --env=DRONE_RUNNER_CAPACITY=2   --env=DRONE_PRIVATE_MODE=false   --env=DRONE_LOGS_DEBUG=true   --publish=80:80   --name=drone   drone/drone:0.9.0-alpha.2
```

![screenshot from 2018-10-10 10-49-44](https://user-images.githubusercontent.com/10864294/46728245-47f33e00-cc7a-11e8-8815-299ca1b1dfd5.png)

**Comment by tboerger** [comment]
Please follow the guide on the temporary home if the 0.9 documentation to get a 0.9 setup rolling: https://readme.drone.io

The documentation at https://docs.drone.io will be replaced with the final release of 0.9. This version got a massive break to the current pipeline Definition.
