### ISSUE TITLE
now that Github has disabled webhooks for more than 24h - force a new drone build?

### ISSUE THREAD

**Issue by vittico** [drone/drone#2515]
Hello!

First of all, I ignore if there is another way to do it, and I have tried with the cli... with no success.

Is there any way to force a *new* build without a webhook? I mean Github is down now, and many of us would like to have a way to do a new build with whatever there is on a specific branch, a new build, not a rebuild of a past build, something like:

drone build start etaleinc/etale-java-main 

again guys, is there any way to actually accomplish this?

**Comment by bradrydzewski** [comment]
We have an open thread in our discourse forum related to this topic. Lets move the discussion there https://discourse.drone.io/t/force-a-build-on-a-certain-branch/2813/2
