### ISSUE TITLE
Drone is not recognizing gitea release creation

### ISSUE THREAD

**Issue by xoxys** [drone/drone#2519]
Hi,

if i create a release from the gitea ui (creates also a tag in background), drone does not recognize it and is not running the pipeline.

If i instead push a tag from command line to remote repo, drone will run twice. One run for the push and one run for the tag... That duplicates the runtime. Any chance to fix this?

**Comment by tboerger** [comment]
If the ui action doesn't trigger a webhook there is nothing drone can do, so this sounds like a gitea issue.

Drone receives a push webhook and a tag webhook in that case, which is the expected behavior.  If you think this is the wrong behavior this is also something that needs to be changed within gitea.

**Comment by bradrydzewski** [comment]
I was just testing this yesterday in 0.9. I can confirm that pushing a tag only creates a single build, assuming the tagged commit already exists in the remote repository. If you push a new commit _and_ a new tag then you can expect two builds.

**Comment by lunny** [comment]
@xoxys which drone version did you test?

**Comment by xoxys** [comment]
@lunny latest 8

**Comment by strahe** [comment]
Hi, I encountered the same issues on the latest version(1.1, 1.2). im sure gitea release has triggered the webhook.  (drone response 200 but no content)

![s1](https://user-images.githubusercontent.com/7932644/59483505-509eb280-8ea0-11e9-9f15-a906058e90a7.png)

![s2](https://user-images.githubusercontent.com/7932644/59483512-572d2a00-8ea0-11e9-9c2e-d7088ac02d36.png)
