### ISSUE TITLE
upgrade to 0.9.0

### ISSUE THREAD

**Issue by dottgonzo** [drone/drone#2520]
after some months on which all was perfect, i'm experiencing much troubles (drone-git hangs, errors with sqlite, etc...), so today decided to upgrade and test the 0.9.0 version. 
Unfortunately it was impossible, because the drone server container fails and the logs show: "version control system not configured".

Now i'm back with 0.8 version and still continue to live with many bugs. Maybe the better solution is to clean the db, but as i read, it will be possible by the cli on 0.9.0, and correcting it by hand is annoying...

**Comment by bradrydzewski** [comment]
you should not upgrade to 0.9 until we have published a migration utility.  There is currently no automated upgrade path from 0.8 to 0.9.  Once a migration utility is available we will publish an announcement to https://discourse.drone.io
