### ISSUE TITLE
1.0.0-rc.1: GitLab, cannot find repository error="sql: no rows in result set"

### ISSUE THREAD

**Issue by boredland** [drone/drone#2522]
Hi!
I'm trying to upgrade to the 1.0.0-rc.1. While I was able to (re-)configure GitLab and everything seems to work, whenever a trigger arrives at Drone it prints the following to stdout:
```
drone-server_1   | 2018-11-10T20:01:04Z |ERROR| cannot find repository error="sql: no rows in result set" ip=11.0.0.110 method=POST name=[project_name] namespace=[namespace_name] path=/hook request_id=bfjji04etrt0l997jv60
```
I suspect the "project_name" part of this, since it should be the repository name it searches for. That differs in GitLab.

**Comment by boredland** [comment]
I nailed it down and worked around it. 

Here is what I found:
1. In GitLab you can have Groups (Namespaces) that have a name and a path variable.
2. In GitLab you can define a Repository Name and its Path.
In both cases I can reproduce the Drone Webhook uses NOT the path, but instead its name. That way, it doesn't "find" it, when the webhook arrives.

**Comment by bradrydzewski** [comment]
I'm not an advanced gitlab user, but we do have some pretty solid testing and samples in place, if you want to see how we are parsing the webhooks and mapping to structs:
https://github.com/drone/go-scm/blob/master/scm/driver/gitlab/webhook.go

Example push hook from GitLab:
https://github.com/drone/go-scm/blob/master/scm/driver/gitlab/testdata/webhooks/push.json

Example push hook mapped to the Drone type:
https://github.com/drone/go-scm/blob/master/scm/driver/gitlab/testdata/webhooks/push.json.golden

**Comment by boredland** [comment]
Group Namespace and Path are under: Group -> Settings -> General -> Group name vs. Path, transfer, remove
Repo Name and Path are under: Repository -> Settings -> General -> Rename repository

**Comment by boredland** [comment]
I guess it is an "edgy" case, when your groupname differs from your groups path and your repo name differs from your repo path.

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/go-scm/commit/e4326a4726b4865ac9274f9b674a81a2333fa0c6

**Comment by boredland** [comment]
Hi @bradrydzewski! While this is fixed for the particular use-case, there is more: in GitLab you can have nested namespaces like organization/projectA/repository_a. That example would lead to:
```
{
2018-12-12T14:51:06.833496800Z app[web.1]:   "admin": false,
2018-12-12T14:51:06.833512168Z app[web.1]:   "error": "404 Project Not Found",
2018-12-12T14:51:06.833522038Z app[web.1]:   "level": "warning",
2018-12-12T14:51:06.833535082Z app[web.1]:   "msg": "api: cannot sync repository permissions",
2018-12-12T14:51:06.833551873Z app[web.1]:   "name": "repository_a",
2018-12-12T14:51:06.833567378Z app[web.1]:   "namespace": "projectA",
2018-12-12T14:51:06.833582216Z app[web.1]:   "read": true,
2018-12-12T14:51:06.833592386Z app[web.1]:   "request-id": "1EG5o81KQaqMywnEBD0ytlpUy9y",
2018-12-12T14:51:06.833601785Z app[web.1]:   "time": "2018-12-12T14:51:06Z",
2018-12-12T14:51:06.833611795Z app[web.1]:   "user.login": "someuser",
2018-12-12T14:51:06.833627875Z app[web.1]:   "write": false
2018-12-12T14:51:06.833643319Z app[web.1]: }
```

**Comment by WesleySkillern** [comment]
@bradrydzewski I am having the same issue as @boredland . 

I would be happy to provide additional information if more is required than the above comment. 

Essentially, we see the sync repository permissions fail for the structure “groupA/groupB/repo”, but it works for “group/repo”. In order to solve completely, it would also involve frontend changes to display the correct repo names in the drone web interface. Right now the drone frontend displays “groupA/groupB” for repos that should be shown as “groupA/groupB/repo”, so we cannot distinguish them.

**Comment by xuyao18** [comment]
Hi @bradrydzewski I  met the same situation with @WesleySkillern .

After I read the code in drone and do some little hack . 

I found in my gitlab system (v10.4.2) ,  it cannot recongize url like "GroupA/GroupB/repo", when sync repos or get repo permisssion information .  

I think you can change the code like `replaceHook(ctx, s.client, repo.Slug, hook)` to `replaceHook(ctx, s.client, repo.UID, hook)`

Using UID to find information in gitlab, it may help drone find project properly.
