### ISSUE TITLE
1.0.0.-rc.1 agent - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by h774211** [drone/drone#2525]
Running agent rc.1 throws the following error in logs

{"level":"error","error":"invalid character '<' looking for beginning of value","platform":"linux/amd64","time":"2018-11-11T20:07:46Z","message":"cannot get queue item"}

the agent call the rpc service "POST /rpc/v1/request" response 

"<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon.png><title>Drone | Continuous Integration</title><link href=/css/app.b667b0e1.css rel=preload as=style><link href=/js/app.28abcb1f.js rel=preload as=script><link href=/js/chunk-vendors.6bc2aeab.js rel=preload as=script><link href=/css/app.b667b0e1.css rel=stylesheet></head><body><noscript><strong>We're sorry but Drone does not work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=/js/chunk-vendors.6bc2aeab.js></script><script src=/js/app.28abcb1f.js></script></body></html>"

**Comment by bradrydzewski** [comment]
Hi there, we provide end-user support through our discourse forum and reserve the issue tracker for confirmed bugs. Please start a thread in our discourse forum and we can help you work through this issue, which is related to mis-configuration. https://discourse.drone.io/
