### ISSUE TITLE
Too much access rights on private repositories and organisations

### ISSUE THREAD

**Issue by hmilkovi** [drone/drone#2532]
Not enterprise edition related.

As Drone requests "syncs" all my Github repositories for all organisations I think it
has and serious security issue with authorisation.

I have tight contracts with users about code sharing and privacy, that's why I find it an really big issue
for users like me what have multiple access rights in multiple organisations and/or multiple private repositories in my private Github account.

Full access to all private repositories is not acceptable, furthermore more in Europe it could easily go under GDPR issue:
![image](https://user-images.githubusercontent.com/9272497/48777503-01f6b480-ecd3-11e8-839b-549c1976de3b.png)

**Comment by bradrydzewski** [comment]
see https://github.com/drone/drone/issues/309#issuecomment-176271104
and https://github.com/drone/drone/issues/2422
