### ISSUE TITLE
where is the coresponding source code of the drone/drone:1.0.0-rc.1

### ISSUE THREAD

**Issue by xujintao** [drone/drone#2535]
The lastest master branch tagged with 0.8.9 cannot match drone/drone:1.0.0-rc.1

**Comment by tboerger** [comment]
We know that... The 1.0.0 source haven't been made public yet because @bradrydzewski is managing some legal stuff because the enterprise source will be part of the repository.

**Comment by bradrydzewski** [comment]
discussed [here](https://discourse.drone.io/t/drone-coming-with-limits-and-license/2652/9?u=bradrydzewski)
