### ISSUE TITLE
Step condition tag & branch not working with Github

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2536]
There's a step condition combination which should ensure that a step gets executed only if the event is a a tag and that tags refers to a specific branch/branches:
```
when:
  event: tag
  branch: master
```
Github doesn't seem to set `base_ref` to a any value in push events of tag creation:
```
{
  "ref": "refs/tags/v1.0.0",
  "before": "0000000000000000000000000000000000000000",
  "after": "20b734acaddc9c5a45319e83d191daf4f70291e3",
  "created": true,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/foo/bar/compare/v1.0.0",
  "commits": [

```
The create event of Github, however, includes the branch in `master_branch`:
```js
{
  "ref": "v1.0.0",
  "ref_type": "tag",
  "master_branch": "master",
  "description": "foo",
  "pusher_type": "user",
````

**Comment by bradrydzewski** [comment]
closing because a git tag is a pointer to a commit sha, not a branch. It is therefore not possible to limit a step by both tag and branch.

**Comment by natlibfi-arlehiko** [comment]
Fair enough. It seems that the new documentation doesn't include the condition example anymore: https://docs.drone.io/config/pipeline/conditions/
