### ISSUE TITLE
proposal: Support for Team Foundation Server

### ISSUE THREAD

**Issue by Timer** [drone/drone#2537]
Having support for Team Foundation Server (TFS, on-premise Azure Devops) would be great!

If there's documentation on writing a new remote, I'd take a stab at this!

**Comment by tboerger** [comment]
First of all it got to be integrated into https://github.com/drone/go-scm

**Comment by bradrydzewski** [comment]
and also https://github.com/drone/go-login

**Comment by ScottGuymer** [comment]
@Timer did you have a go at this?

**Comment by Timer** [comment]
@ScottGuymer I no longer work at the company who uses TFS -- I ultimately got my department to switch to GitHub before I left (for Drone compatibility).

**Comment by ScottGuymer** [comment]
Ah... Probably not a solution for us. 

Was the switch worth it?

**Comment by Timer** [comment]
@ScottGuymer we were much more productive on GitHub than TFS!

n.b. we were using TFS, not Azure DevOps Server

**Comment by ScottGuymer** [comment]
😆 

Upgrade is "Coming Soon" ™️

**Comment by bradrydzewski** [comment]
I am going to close this due to lack of volunteers to implement. If someone comes across this issue and is interested in TFS support they should first add TFS support to the below packages. Once added we can re-open this issue.

* https://github.com/drone/go-scm
* https://github.com/drone/go-login
