### ISSUE TITLE
Missing usefull error message on login fail

### ISSUE THREAD

**Issue by Niondir** [drone/drone#2538]
Logging in with a unverified email address fails with generic error message. The server log states:

```
time="2018-11-30T07:55:31Z" level=error msg="cannot authenticate user. No verified Email address for GitHub account"
```

It would be very helpful to display this message to the user.

**Comment by tboerger** [comment]
But maybe an admin don't want to give such a detailed error.

**Comment by bradrydzewski** [comment]
the validation / error message no longer exists in Drone 1.0 so I think we can consider this resolved.
