### ISSUE TITLE
Migration script to 1.0 from 0.8

### ISSUE THREAD

**Issue by dwojcAVI** [drone/drone#2548]
i was just checking if the migration script to 1.0 from 0.8 will be ready on November 16th of 2019 or what happened.  Today is December 10th and it is not on the documentation.  am i missing something?

**Comment by apricote** [comment]
The announcement was made on Discourse: [Migration Utility for 1.0](https://discourse.drone.io/t/migration-utility-for-1-0/3147).

You can find the utility in the repository [drone/drone-migrate](https://github.com/drone/drone-migrate).

**Comment by tboerger** [comment]
The migration script is still not final since it's missing multiple parts. The promise was to finish it before the final 1.0.0 of drone.

**Comment by brinehart** [comment]
@tboerger Is this in place yet? The documentation still states that it will be ready "on or before November 16th"

**Comment by bradrydzewski** [comment]
@brinehart migration utility available at https://github.com/drone/drone-migrate
