### ISSUE TITLE
How to use Drone with self-hosted git repository

### ISSUE THREAD

**Issue by vitalik** [drone/drone#2552]
I've been searching and asking forums about this:

is it possible to use Drone with self-hosted git repositories  (**without** GitHub or GitLab) ?

**Comment by jhasse** [comment]
Yes. Use Gitea and see https://docs.drone.io/installation/gitea/. Btw: You can also self-host GitLab.

**Comment by vitalik** [comment]
well my question is about the case when I have git repo **WITHOUT** gittea, gitlab, github

just bare repository accessible only over ssh

**Comment by apricote** [comment]
This is not possible because Drone uses the SCM provider for user managment. Also SCM provider webhooks are used to trigger the builds.

**Comment by vitalik** [comment]
can you please explain a little bit the flow ?

does Drone periodically  checks some  external API to find new code pushes ?

Or it's other way around  - a SCM provider "notifies" Drone to trigger build ?

**Comment by apricote** [comment]
You can check out the full interface at https://github.com/drone/go-scm/tree/master/scm

When you activate a Repository in Drone, Drone will use the `go-scm` drivers to create Webhooks in your SCM Provider. The SCM Provider will call the webhooks when new events happen (push, tag, pr created...) and Drone will create a new Job.

**Comment by bradrydzewski** [comment]
closing as duplicate of https://github.com/drone/drone/issues/10
