### ISSUE TITLE
[Performance] Why we use hard-coded queries instead of Stored Procedure for PostgreSQL?

### ISSUE THREAD

**Issue by Dentrax** [drone/drone#2556]
I found this file when I was investigating the source code:

[sql_gen.go](https://github.com/drone/drone/blob/master/store/datastore/sql/postgres/sql_gen.go)

This means that Postgres queries are executing on the server side. As we know there is **Stored Procedure** support for PostgreSQL. You can check it out [here](https://www.postgresql.org/docs/11/plpgsql.html).

Instead of _reading_ and _executing_ the _queries_ from the **sql_gen.go** file, does it not give us much more performance to do it entirely on the _Postgre_ database?

How noticeable is under heavy query load?

For example, for the [repoInsertIgnore](https://github.com/drone/drone/blob/master/store/datastore/sql/postgres/sql_gen.go#L452) constant;

```
var repoInsertIgnore = `
INSERT INTO repos (
 repo_user_id
,repo_owner
,repo_name
,repo_full_name
,repo_avatar
,repo_link
,repo_clone
,repo_branch
,repo_timeout
,repo_private
,repo_trusted
,repo_active
,repo_allow_pr
,repo_allow_push
,repo_allow_deploys
,repo_allow_tags
,repo_hash
,repo_scm
,repo_config_path
,repo_gated
,repo_visibility
,repo_counter
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
ON CONFLICT (repo_full_name) DO NOTHING
`
```
We are executing it [RepoBatch](https://github.com/drone/drone/blob/29785b86f6534ded974120de0fcf7c21397a9d0d/store/datastore/repos.go#L70) function in the [repos.go](https://github.com/drone/drone/blob/master/store/datastore/repos.go) file.

Instead of;

We can **CALL** the _Stored Procedure_.  After the _Stored Procedure_ runs, it may return different values to us;

1. `RETURN 0` **Insert success:** _OK_
2. `RETURN 1` **Failed to insert:** _Null or Empty argument_
3. `RETURN 2` **Failed to insert:** _Value already exist_
4. `RETURN 3` **Failed to insert:** _Unexpected behaviour_
5. `RETURN 4` **Failed to insert:** _Unknown error_

According to the return result, we can continue our function operations. 

Thanks in advance...

**Comment by tboerger** [comment]
We are using the same functionality for all supported databases, so where is the real benefit to start using something totally different than for the other databases?

**Comment by bradrydzewski** [comment]
as mentioned, drone supports mysql and sqlite in addition to postgres. The goal is to use similar code wherever possible across all three providers.
