### ISSUE TITLE
Proposal: show webhook url when enable repo failed

### ISSUE THREAD

**Issue by lizheming** [drone/drone#2560]
I'm using Gitlab in my company, and developer have no administrative access for repo. If we want to add webhook for repo, we need apply it. From https://github.com/drone/drone/issues/1043 this issue we can know drone need administrative access, so it can't add webhook for my project although It shows enabled in drone. 

So I think how about show a dialog with webhook url and secret and some tips like "sorry, drone add webhook failed, please add webhook and secret manually." when drone add webhook failed. Then we chan handle it by myself. just now I have no chance to use Drone in my company project because I don't know what secret should I add in webhook.

btw, i'm using drone 0.8, but also i think drone 1.0 is the same way.

**Comment by bradrydzewski** [comment]
Sorry unfortunately this is not a feature request that we can implement. The reason adding the repository webhook fails is because you need admin access to the repository. Even if you want to manually add the webhook, you still need admin access in GitHub / Gogs / Gitea / Bitbucket.

> The Repository Webhooks API allows repository admins to manage the post-receive hooks for a repository [1]

[1] https://developer.github.com/v3/repos/hooks/

**Comment by lizheming** [comment]
At first thanks for your apply, and merry x'mas. 
something I don't understand. Drone just need add and trigger webhook access, am i right? And I can apply adminer someone who has access to add webhook, so webhook have admin access and also can ping normal. That works well when i add webhook for other system in gitlab. so is there any other reason that drone must need I have admin access?

**Comment by tboerger** [comment]
Maybe Gitlab allows to add webhooks by non-admins, but all other supported scm allow that to admins only. Since the workflow is streamlined it's not that nice to add an exception for Gitlab only.

**Comment by bradrydzewski** [comment]
@lizheming I think the best option is to give the repository administrator access to Drone so they can login and enable the repository. There is a cost to every line of code we add to this project (both in terms of writing the code and support) and it is not yet clear to me that we can get enough benefit from this feature to justify the cost.

**Comment by lizheming** [comment]
@bradrydzewski I'm very agree with you, and @tboerger is also right, it's a feature just for gitlab. From this doc https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions we can know only `Owner` and `Maintainer/Master` role can configure project hooks, and there has no `Maintainer/Master` role in other scm. Owner have more rights than Maintainer just like set project public, delete project... I also want to have Owner right in my project, but company won't set this high level role for develop to forbidden remove project behavior. I know this rule is so strange, but... it's so sad! 😢 

I'm the `Maintainer/Master` role right now and I can add webhook from gitlab web ui, but it's still fail when enable repository from drone. So maybe we can change this issue to another question: I'm the project's maintainer, and can add webhook from web ui, why webhook add failed when I enable repository in drone?

At last, Merry Christmas for everyone, thank you for your reply again~ 😄
