### ISSUE TITLE
DRONE_RUNNER_VOLUMES mount path is ignored

### ISSUE THREAD

**Issue by TankTheFrank** [drone/drone#2561]
I'm using 1.0.0-rc3 with "DRONE_RUNNER_VOLUMES=/var/cache/drone:/cache,/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"

Both get mounted but the target path is ignored and gets mounted under the host path, instead of "/cache" it gets mounted under "/var/cache/drone" in the container.

Going on a limb here since the source code for 1.0.0 is not available yet but I'd say that is related to #2549

**Comment by tboerger** [comment]
The length doesn't equal 2?

func toVolumes(items []string) map[string]string {
	set := map[string]string{}
	for _, item := range items {
		parts := strings.Split(item, ":")
		if len(parts) != 2 {
			key := parts[0]
			val := parts[1]
			set[key] = val
		}
	}
	return set
}

**Comment by bradrydzewski** [comment]
there was a regression [here](https://github.com/drone/drone-yaml/commit/a6b4999cf22d8dafe9d27a6763789ebdcde7bf82). I patched `rc.3` so if you re-pull the image you will get the fix.

**Comment by tboerger** [comment]
And what about the if len(parts) != 2 ? Isn't that wrong?

**Comment by bradrydzewski** [comment]
@tboerger drone server uses different logic (below) so I think this particular issue can be closed, but you are correct that it looks like there is an issue with the CLI.  

```
func convertVolumes(from []string) map[string]string {
	to := map[string]string{}
	for _, s := range from {
		parts := strings.Split(s, ":")
		if len(parts) != 2 {
			continue
		}
		key := parts[0]
		val := parts[1]
		to[key] = val
	}
	return to
}
```
