### ISSUE TITLE
support nginx reverse proxy with url prefix

### ISSUE THREAD

**Issue by storezhang** [drone/drone#2567]
in my nginx conf
`        location /drone/ {
            proxy_set_header Origin "";

            proxy_pass http://192.168.50.220:21080/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_buffering off;

            chunked_transfer_encoding off;
        }`

but in my brsower catch
![image](https://user-images.githubusercontent.com/4278758/50737093-5fea4780-1200-11e9-99ae-6f78f8107697.png)

static files url is not add "drone" prefix

thanks

**Comment by bradrydzewski** [comment]
see [https://github.com/drone/drone/issues/475] ... no plans to support base urls. Instead you need to assign a subdomain.
