### ISSUE TITLE
nested yaml plugin options not parsing to expected json

### ISSUE THREAD

**Issue by btkostner** [drone/drone#2568]
Original issue here: https://github.com/drone-plugins/drone-s3-sync/issues/51

Using Drone image: `drone/drone:1.0.0-rc.3` with `plugins/s3-sync`.

When configuring acl values like so, it does not work:
```
settings:
  acl:
    "*": public-read
```

Bug when configuring it as a JSON string, it seems to work:
```
settings:
  acl: '{ "*": "public-read" }'
```

**Comment by bradrydzewski** [comment]
@btkostner just wanted to follow up to see which version of Drone you are using, and if you are able to reproduce in the latest version. Thanks!

**Comment by btkostner** [comment]
@bradrydzewski sorry for the delay. I was sick last week and have a bunch of work this week. I'll try to get this all figured out today. I'm currently running drone image `drone/drone:1.0.0-rc.4`, but this issue was on `drone/drone:1.0.0-rc.3`. Is there any way to confirm the yaml without compiling `drone-yaml`?

**Comment by btkostner** [comment]
Looks like you are right. Seems to template fine. I'll see if I can find a problem in the `drone-s3-cache` repo instead. Sorry for the false alarm.

**Comment by bradrydzewski** [comment]
no worries, if you need additional help feel free to hit us up in our chatroom at [gitter.im/drone/drone](https://gitter.im/drone/drone).
