### ISSUE TITLE
Provide multiarch images for arm/arm64

### ISSUE THREAD

**Issue by everflux** [drone/drone#2572]
Please provide the drone image as multi-arch image so it works on ARM and ARM64 as well.

**Comment by tboerger** [comment]
On 0.8 the server wasn't officially supported on arm/arm64, so we won't publish images for that.

For 1.0.0 there are already images for arm/arm64.

**Comment by everflux** [comment]
The 1.0.0 image is not available on dockerhub and dockerhub does not recognize the rc4 as multi-arch image. Do you plan to push a manifest to support multi-arch once 1.0.0 is published?

**Comment by tboerger** [comment]
Also rc4 should already provide a manifest. Is that currently missing @bradrydzewski?

**Comment by everflux** [comment]
I checked on the dockerhub website where the arch labels are not displayed and manually from the cli which shows just  a single architecture, amd64.

```
$ docker pull drone/drone                        
Using default tag: latest
latest: Pulling from drone/drone
297640bfa2ef: Pull complete 
7b4a6779ebc9: Pull complete 
Digest: sha256:c239a00fad5e01d721aede117624e6b5a912c4321443616dab3a3d758763d9d6
Status: Downloaded newer image for drone/drone:latest
$ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect --verbose drone/drone 
```

Thanks for taking care!

**Comment by tboerger** [comment]
Latest doesn't refer to 1.0.0, that should be still 0.8.x

**Comment by everflux** [comment]
Thanks for the clarification, for rc4 multi-arch is indeed present.

```
$ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect --verbose drone/drone:1.0.0-rc.4 | jq ".[].Descriptor.platform.architecture"
"amd64"
"arm64"
"arm"
```
