### ISSUE TITLE
Missing Unit Test (Update) in TestRepoCrud()

### ISSUE THREAD

**Issue by Dentrax** [drone/drone#2575]
I came across something while I was navigating over the project source files. The [TestRepoCrud(t *testing.T)](https://github.com/drone/drone/blob/master/store/datastore/repos_test.go#L365) function in the [repos_test.go](https://github.com/drone/drone/blob/master/store/datastore/repos_test.go) doesn't have [UpdateRepo](https://github.com/drone/drone/blob/master/store/datastore/repos.go#L46) test. Maybe it could be overlooked. I think logic should be like this:

```
s.CreateRepo(...)
s.GetRepo(...)
s.UpdateRepo(...)
s.DeleteRepo(...)
s.GetRepo(...)
```

...instead of:

```
s.CreateRepo(...)
s.GetRepo(...)
s.DeleteRepo(...)
s.GetRepo(...)
```

Isn't that?

**P.S:** Of course **UpdateRepo** function is actually already being tested [here](https://github.com/drone/drone/blob/master/store/datastore/repos_test.go#L48) but; you know, It's a **CRUD** test function. :)

**Comment by bradrydzewski** [comment]
hey for posting questions, please use discourse.drone.io or gitter.im/drone/drone ... we use the issue tracker primarily as a todo list, so we have most discussions in these other tools. Thanks!
