### ISSUE TITLE
Customize GitHub Status Message (1.0)

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2577]
When we abstracted the go-scm library we made it more difficult to customize the status message, which is why it is currently disabled in the latest release candidate. I think we can satisfy customization and support for all providers by exposing this as a generic template string:

```
continuous-integration/drone/{{ if .Build.Event eq "pull_request" }}pr{{ else }}push{{ end }}
```

**Comment by s0undt3ch** [comment]
Please :)

**Comment by s0undt3ch** [comment]
I would go as far as allowing a repo to set its desired status message(and context) or completely disable it if customization is not possible.
That way we can use a plugin to push our desired status message and context...

**Comment by bradrydzewski** [comment]
Yes, I think disabling the built-in Status and delegating to plugins is a much better idea, and is in line with how we allow other aspects of the codebase to be customized.

I would also say that, while you can definitely use plugins in your Pipeline to customize Status, you might also consider using system webhooks. As you experience with cancellations, there may be situations where a plugin does not execute which would leave the status in a pending state. Webhooks will always execute.  I will document this more once I introduce the ability to disable status.

**Comment by s0undt3ch** [comment]
Are there any docs about the webhooks?

**Comment by s0undt3ch** [comment]
http://docs.drone.io/configure-system-webhooks/ is a 404

**Comment by bradrydzewski** [comment]
here you go https://discourse.drone.io/t/how-to-use-global-webhooks/3755

**Comment by bradrydzewski** [comment]
Quick update. The following two variables will be included in the next snapshot:

* `DRONE_STATUS_DISABLED` disable the default status setter
* `DRONE_STATUS_NAME` customize the label prefix.  the label is created by concatinating the name and event, like`{name}/{event}`, where the default name is `continuous-integration/drone` and by default produces `continuous-integration/drone/{event}`

When you disable status you have the option of delegating status to an external service, through the use of webhooks. Brief overview of webhooks here:
https://discourse.drone.io/t/how-to-use-global-webhooks/3755

**Comment by bradrydzewski** [comment]
cc @geekdave this will be the final implementation, which removes the awkward template syntax.

**Comment by bradrydzewski** [comment]
closing now that this has been implemented in 1.0 final, implementation details at https://github.com/drone/drone/issues/2577#issuecomment-462964836

**Comment by s0undt3ch** [comment]
Is there a way to access the drone URL for a particular pipeline from within that pipeline, perhaps as an environ variable?
Do we have access to that on the webhooks?
The idea is to allow setting the build status on github based on the pipeline, besides the whole build.

**Comment by bradrydzewski** [comment]
yes, there is an environment variable that provide a link to your pipeline:

```
DRONE_SYSTEM_PROTO=https
DRONE_SYSTEM_HOSTNAME=cloud.drone.io
DRONE_BUILD_LINK=http://cloud.drone.io/drone/hello-world/42
```

environment variables that let you construct the link manually:

```
DRONE_SYSTEM_HOSTNAME=cloud.drone.io
DRONE_SYSTEM_PROTO=https
DRONE_REPO=drone/hello-world
DRONE_BUILD_NUMBER=42
```

environment variables that could be useful when creating a github status:

```
DRONE_COMMIT_SHA=eb82c922e6dff2b2cf9df3c87843e74f97498507
DRONE_PULL_REQUEST=24
DRONE_BUILD_STATUS=success
```

all of the above parameters are available in the webhook payload, with the exception of the `DRONE_BUILD_LINK`, which can be constructed using the data available in the webhook.

**Comment by s0undt3ch** [comment]
So, a build which runs several pipelines, the above information for each of the pipelines is still true?

Say, a build runs both a lint pipeline and a tests pipeline, I will be able to construct a URL for each of those?
