### ISSUE TITLE
drone/controller dockerfile missing

### ISSUE THREAD

**Issue by everflux** [drone/drone#2579]
I would like to build a custom image for the drone/controller, but I could not find the build instructions or docker file. (I checked "drone" there are dockerfiles for the agent and server, in "drone-runtime" is no dockerfile. The VCS label from the controller references  https://github.com/bradrydzewski/drone-ee.git which is a private repository.)

**Comment by tboerger** [comment]
The source for 1.0.0 is currently stored within this private repo. It's not published yet.
