### ISSUE TITLE
Proposal: Add env var for the step that caused a build failure

### ISSUE THREAD

**Issue by jamesorlakin** [drone/drone#2586]
Hi all,

I was wondering whether an environment variable could be provided to plugins on the step that caused a build to fail.

The suggested use case would be to give more detail to notification plugins. I would love to know at a glance in Slack whether the build failed during the testing step, or something mundane to do with linting. At the minute its either a pass or fail message, and then a dig through the logs to see what the issue was.

Maybe something like this?

```
- name: slack
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook: https://hooks.slack.com/services/...
    template: >
      {{#success build.status}}
        CI passed! 🎉
        Commit `{{truncate build.commit 8}}` on branch {{build.branch}}.
        <{{build.link}}|Link to build log>
      {{else}}
        CI Failed on step {{build.failedStep}}
        Commit `{{truncate build.commit 8}}` (by {{build.author}}) on branch {{build.branch}}.
        <{{build.link}}|Link to build log>
      {{/success}}
```

There was a similar suggestion a year and a half ago - https://github.com/drone/drone/issues/1740#issuecomment-329984464

Thanks.

**Comment by bradrydzewski** [comment]
added via https://github.com/drone/runner-go/commit/042700a61c6aac5291071cb0d68cca83cdf6f585

note that this is going to be part of the runner framework, which means it will be available to any runners (agents) that are created with this framework. The docker runner will not use this framework right away, so might take a few weeks before available.

**Comment by bradrydzewski** [comment]
I am going to close this since this is implemented and available to all runners that use the `runner-go` library. List of runners using this library:

- exec
- ssh
- digitalocean

List of runners being actively ported to this library:

- docker
