### ISSUE TITLE
Google fonts being requested

### ISSUE THREAD

**Issue by ikarulus** [drone/drone#2588]
I think I waited long enough to open an issue here. :)

https://discourse.drone.io/t/remove-googlefonts-request-for-privacy-and-gdrp/3409
> I wanted to open an issue on github but it said I have to discuss this first.
> The web ui opens a request to google servers to download the roboto font. This is not really necessary.

I want to point out that this is kinda critical in an open source/FLOSS project.

**Comment by ikarulus** [comment]
And maybe you wanna adjust this issue template.
> Bugs or Issues? Please do not open a GitHub issue until you have
> discussed and verified with community support:
There are some cases when it's unclear if it classifies as bug or not but could be critical after all. E.g. user's privacy when requesting stuff from $hugeCompany servers. In most cases (as far as I know) most FLOSS projects don't do it.

**Comment by bradrydzewski** [comment]
no plans to change the fonts at this time, however, if you are concerned about the google fonts servers you should be able to build from source and strip fonts as needed.
