### ISSUE TITLE
Docker hub publish Drone 0.8.10 release

### ISSUE THREAD

**Issue by kneal** [drone/drone#2591]
I am seeing Drone had a tagged feature set for `0.8.10` but Docker hub does not have a published image. I was wondering if that release was going to be published to Docker Hub.

Drone Docker Hub:
https://hub.docker.com/r/drone/drone/tags?page=1

Drone Release Page:
https://github.com/drone/drone/releases/tag/v0.8.10

```
docker pull drone/drone:0.8.10
Error response from daemon: manifest for drone/drone:0.8.10 not found
8c8590ada100:drone-agent z001nr1$ docker pull drone/drone:0.8.9
0.8.9: Pulling from drone/drone
297640bfa2ef: Pull complete
6d34061bcde3: Pull complete
Digest: sha256:6056575462036f2579d17885532e5152e5478cf1c495ef183d2381a7e0cd8668
Status: Downloaded newer image for drone/drone:0.8.9
```

**Comment by bradrydzewski** [comment]
It looks like I forgot to update the release configuration and overwrote the 0.8.9 image instead of publishing 0.8.10. So you should be able to get the 0.8.9 image to get the latest release.

**Comment by kneal** [comment]
Sounds good. Thank you!

**Comment by jacksgt** [comment]
Since Drone 1.0 has been released, I think this issue can be closed.
