### ISSUE TITLE
Streams leaking resources

### ISSUE THREAD

**Issue by luis-silva** [drone/drone#2596]
I'm raising this issue and a PR (#2597) to address memory and goroutine leaks in drone server.

### The Problem

I've noticed that, when using Streams, Drone was leaking go routines and heap space. I was able to reproduce it by doing the following:
- Opening a new tab and access Drone
- Refreshing the page multiple times (or opening multiple tabs)
- Analysing the resource usage by accessing `/api/debug/pprof/`, `go tool pprof`, debug logs and chrome developer tools.

The logs showed multiple connections being opened but never closed, just by refreshing the page
![connections](https://user-images.githubusercontent.com/4629568/52945024-b357c580-3368-11e9-927a-59cee9da76c9.png)

Memory tracking showed that the heap never got garbage collected
![memory_pre](https://user-images.githubusercontent.com/4629568/52945400-8a840000-3369-11e9-8799-de6250d22385.png)

Go routines would never terminate
<img width="2400" alt="goroutines" src="https://user-images.githubusercontent.com/4629568/52945604-01b99400-336a-11e9-8c57-5dda43b8f08b.png">

Go routines and heap usage confirmation in pprof endpoint
![pprof](https://user-images.githubusercontent.com/4629568/52945440-a4254780-3369-11e9-86a9-e71e83ee94f9.png)

Idle streams not getting closed:
<img width="530" alt="stream duration" src="https://user-images.githubusercontent.com/4629568/52945765-64ab2b00-336a-11e9-806d-1836eea62822.png">

### Analysis

When profiling I found the two main issues to be:

**Timers memory leak**
<img width="288" alt="timer_leak" src="https://user-images.githubusercontent.com/4629568/52947069-9c67a200-336d-11e9-9dd9-cab454744523.png">

The 60 minute timer to close the stream was not actually working. This was due to the fact that a new timer was being created for every iteration of the for loop, which happened every 30 seconds when the ping timeout ran, which meant that new 60 minute timers were created every 60 seconds. This would also prevent the old timers from being garbage collected as Go won't consider them unused until they're triggered.

I solved that issue by creating the timers outside of the for loop and properly reseting them only when data was flowing through the stream.

**Stream not being closed**
<img width="435" alt="repolist" src="https://user-images.githubusercontent.com/4629568/52947459-accc4c80-336e-11e9-97f0-c2f1c15ff2e9.png">
Using drone with a large number of repositories (> 1000) means that the database call to retrieve the repos can generate a map of over 1MB in size. This is done for every stream (this means every tab, every page refresh, etc) and this is not cached and only cleaned up once the stream closes. Since the stream was not closing, the memory usage gets very high very quickly.

The fix for this is to ensure the 1 hour idle timeout actually works and all this data can eventually be garbage collected. I also added some handlers to close the stream based on the gin context.

### The Fix

Memory being freed and reused after the 1 hour idle timeout
![post memory](https://user-images.githubusercontent.com/4629568/52945996-edc26200-336a-11e9-834d-51283db166af.png)

Connections being properly closed by the server and reopened by the browser after the default 3 seconds
![post_conn](https://user-images.githubusercontent.com/4629568/52948188-b5be1d80-3370-11e9-9029-62e56cf3c20d.png)

Testing the timers, both the ping and the idle timer work
<img width="335" alt="timers" src="https://user-images.githubusercontent.com/4629568/52946695-8c9b8e00-336c-11e9-8c05-63cd736fed65.png">

**Comment by bradrydzewski** [comment]
Thanks for the pull request.  I created a separate branch and Docker image so that we can let others start testing the fix. The image is `drone/drone:0.8.9-pr.2597`. After a few weeks of successful testing we can re-tag `drone/drone:0.8.9-pr.2597` as `drone/drone:0.8.10`

**Comment by luis-silva** [comment]
Thanks for merging this, I'll also start running this version in our dev drone instance.
As a note, you already have the git tag `0.8.10` in the `drone/drone` repo but no docker image was actually released to docker hub.
