### ISSUE TITLE
Ability to filter logs (for example, to mask passwords)

### ISSUE THREAD

**Issue by charliebravodev** [drone/drone#2606]
Hello,

I see that #2308 introduced a way of purging logs via an HTTP request, in case you exposed passwords by mistake in the logs. As mentioned in #1584, other CI systems such as Travis or Jenkins provide features for filtering out logs to ensure no secrets are displayed. Is there a mechanism that would allow one to filter logs displayed in the user interface, otherwise is there a way one can write a plugin to do so ?

Thanks a lot !

**Comment by bradrydzewski** [comment]
drone already has this feature. see https://github.com/drone/drone-runtime/blob/master/runtime/line.go#L106:L115

**Comment by charliebravodev** [comment]
Awesome ! Is this documented anywhere ? It would be great to mention it in the docs ? I would have definitely headed to discourse but I thought feature requests were supposed to be placed here.

Thanks again for the quick answer !
