### ISSUE TITLE
DRONE_* Environment Variables

### ISSUE THREAD

**Issue by ukos-git** [drone/drone#2607]
What built-in variables can I reference from a bash script *drone plugin*?

I have seen `DRONE_COMMIT` [in the docu](https://docs.drone.io/user-guide/pipeline/cloning/) but I would love to have the directory where the repository is linked to available in my bash script.

Also: If there is more than the above mentioned variable, could we add a list of available variables to the documentation?

**Comment by tboerger** [comment]
The available environment variables are already documented at https://docs.drone.io/reference/environ/

**Comment by Raiondesu** [comment]
Hello, @tboerger. I guess, this answer is outdated, as the link leads to a 404 page.

There's still no obvious way to find environment variables in the docs, at the moment of this message.

**Comment by tboerger** [comment]
Than you have not searched the docs properly as the env variables are listed at https://docker-runner.docs.drone.io/configuration/environment/variables/

**Comment by till** [comment]
@tboerger Can you elaborate?

I am searching on docs.drone.io?

![image](https://user-images.githubusercontent.com/27003/68769306-5b629c80-0624-11ea-9c0c-68ebc8b43ac3.png)

**Comment by ukos-git** [comment]
I think in the new docs you need to specify the scope to search in first.
This then redirects to the right docs section on another subdomain. As far as I know, you cannot search within all docs. I think it is the right way from a user perspective because you want to have the environment variables for a specific use case and not mix up installation with pipeline environment variables.

On [docs.drone.io](https://docs.drone.io/) select that you want to get the docs for the [pipelines](https://docs.drone.io/configure/pipeline/)

<img src=https://user-images.githubusercontent.com/16167358/68775466-d0d36a80-062e-11ea-83cc-2126cd14d0a1.png width=75%>

select the pipeline you are running. e.g. docker
<img src=https://user-images.githubusercontent.com/16167358/68776182-f3b24e80-062f-11ea-857b-c5d1305025b4.png width=75%>

now the search works:

<img src=https://user-images.githubusercontent.com/16167358/68776330-33793600-0630-11ea-8e9d-269b705a7c0b.png width=75%>

Unfortunately, you cannot search directly for ["environment reference"](https://docker-runner.docs.drone.io/configuration/environment/variables/) which is the actual list of environment variables.

You can, however, navigate there from the menu which is straight forward:

<img src=https://user-images.githubusercontent.com/16167358/68776488-73401d80-0630-11ea-8798-4a286593955a.png width=75%>

**Comment by tboerger** [comment]
The search is indeed far away from being great :(

**Comment by ash-ishh** [comment]
Updated Link: https://docs.drone.io/pipeline/environment/reference/
