### ISSUE TITLE
Build breaks with Githubs new Draft PR feature.

### ISSUE THREAD

**Issue by nickvergessen** [drone/drone#2617]
1. Push a branch
2. Create a Draft PR (see https://github.blog/2019-02-14-introducing-draft-pull-requests/)
3. Expect tests to run.

Actually it fails:
https://drone.nextcloud.com/nextcloud/spreed/1683/29
```
git fetch --no-tags origin +refs/pull/1591/merge:
fatal: Couldn't find remote ref refs/pull/1591/merge
```

**Comment by nickvergessen** [comment]
To get drone working again, you simply need to mark your PR as "Ready to review" on Github and repush/rebuild

**Comment by bradrydzewski** [comment]
Drone 1.0 supports draft pull requests. The difference is that 1.0 uses `refs/pulls/%d/head` to clone the pull request and 0.8 uses `refs/pulls/%d/merge`. I tested with 1.0 and can confirm everything works correctly.



<img width="789" alt="screen shot 2019-03-01 at 6 45 00 am" src="https://user-images.githubusercontent.com/817538/53645454-c2066e00-3bed-11e9-90bf-b9dc2b502421.png">

**Comment by MorrisJobke** [comment]
Thanks - the migration to 1.0 is on our roadmap already. Thanks for the nice work here 👍
