### ISSUE TITLE
Major and minor version tags in Dockerhub

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2618]
Please publish Drone images in Dockerhub with major (`1`) and minor version (`1.1`) tags so that users don't have to risk using the `latest` tag (Which may introduce breaking changes) or specific tags `1.0.0-rc.5` which do not receive updates.

**Comment by bradrydzewski** [comment]
drone 1.0 is not yet released, which is why `1` does not exist yet.
