### ISSUE TITLE
Jsonnet extension not working

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2619]
I have started the Jsonnet extension as specified in https://docs.drone.io/extend/config/jsonnet/. Drone server however does not seem to connect the extension (DRONE_YAML_ENDPOINT and DRONE_YAML_SECRET are specified) and connectivity is tested to work using `nc` inside the Drone server container.

Drone attempts to find the YAML but does not contact the extension:
```
{"commit":"7a59cce5230cc14bb0e05b0df90f3850c3ae6008","error":"Not Found","event":"push","level":"warning","msg":"trigger: cannot find yaml","ref":"refs/heads/test","repo":"xxx/xxx","time":"2019-03-04T08:30:34+02:00"}
```

Tested with `1.0.0-rc.5` and `latest`.

**Comment by bradrydzewski** [comment]
hey there, for end user support please create a thread in our support forum, at discourse.drone.io
