### ISSUE TITLE
Need to approve all build for protected repo

### ISSUE THREAD

**Issue by DblK** [drone/drone#2626]
On a personal instance, when I configure the repo to protected I need to sign the drone file as excepted.

![config](https://user-images.githubusercontent.com/832617/54429984-62967b00-4722-11e9-97aa-f8af38a3261d.png)

During the first build, I need to approve because I just sign it which is fine.
However, during the following build I need to approve every build on first step which is weird.

![build-aprove](https://user-images.githubusercontent.com/832617/54434880-88764c80-472f-11e9-8af5-a740519dde76.png)

What should I do?
I don't know if it's useful to know or not but I use Gitea.

Thanks

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
