### ISSUE TITLE
Store cron job that spawned build in Build struct and database

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2628]
this can be used to visualize which cron job started a build, and can be used to enable support for using the cron job name in the `when` and `trigger` clauses. 

example when configuration:

```
when:
  cron: [ nightly ]
```

example trigger configuration:

```
trigger:
  cron: [ nightly ]
```

**Comment by bradrydzewski** [comment]
support for triggers added by e8558813

```
trigger:
  cron: [ nightly ]
```

support for `when` requires modifying `compiler.SkipData` in the drone-yaml library. This is a simple change. hopefully I will find time for this today or tomorrow.

**Comment by bradrydzewski** [comment]
closed by 4ad44026 and e855881

**Comment by mvdan** [comment]
Perhaps I'm missing something obvious, but the `when` as shown above doesn't work for me. The step that's supposed to only run as part of that cron job always runs, including regular pushes to master and pull requests. I'm on 1.1.0.

**Comment by andrewrynhard** [comment]
I am seeing the same as @mvdan. Happy to look into the code, not sure where to start.

**Comment by mmack-innio** [comment]
Same here. Tried to trigger on cron [ hourly] and did not work.

**Comment by andrewrynhard** [comment]
This seems to only work for triggers.

**Comment by bradrydzewski** [comment]
for this to fully work as envisioned, we also need https://github.com/drone/drone/issues/2705
