### ISSUE TITLE
error docker:dind

### ISSUE THREAD

**Issue by custertian** [drone/drone#2632]
I’d like to do

    docker-compose up -d

Seems like `plugins/docker` is able to do what I want, but it fails if I don’t specify the publish-related stuff. I want to use it without publishing.

Another alternative could be services, but I try always failed

    kind: pipeline
    
    steps:
    
    - name: test
      image: docker:dind
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      commands:
      - docker ps -a
    
    services:
      docker:
        image: docker:dind
        privileged: true
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock

error:

    yaml: unmarshal errors: 
    
    line 8: cannot unmarshal !!str `/var/ru...` into yaml.VolumeMount 

    line 13: cannot unmarshal !!map into []*yaml.Container

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone).

**Comment by custertian** [comment]
> 👋 hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone).

thank you
