### ISSUE TITLE
DRONE_STAGE_NAME/NUMBER not passed to plugins

### ISSUE THREAD

**Issue by jhasse** [drone/drone#2637]
If I understand it correctly, `DRONE_STAGE_NUMBER` would be the replacement for 0.8's `DRONE_JOB_NUMBER`. Apparantly this new variable isn't available to plugins though: https://github.com/Drillster/drone-volume-cache/issues/23

**Comment by bradrydzewski** [comment]
fixed in latest

**Comment by quantonganh** [comment]
@bradrydzewski Can you show me where is the fix? I tried 1.0.1 and only saw:
- DRONE_STAGE_STARTED
- DRONE_STAGE_FINISHED
- DRONE_STAGE_STATUS

**Comment by jhasse** [comment]
`DRONE_STAGE_NUMBER` works for me in 1.0.1 (tested using https://github.com/Drillster/drone-volume-cache).
