### ISSUE TITLE
Drone connect to my github , but cannot activate

### ISSUE THREAD

**Issue by Ddd1101** [drone/drone#2640]
my docker-compose.yml

version: '2'

services:
  drone-server:
    image: drone/drone:1.0.0
    ports:
      - 8082:80
    volumes:
      - ./:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RUNNER_CAPACITY=3
      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=ccf51708f5d3bf22009f
      - DRONE_GITHUB_CLIENT_SECRET=18f79a52f02762a7dd3207140908885d09348966
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

it stay activating .

![屏幕快照 2019-04-02 上午8 07 30](https://user-images.githubusercontent.com/22629976/55367250-b2e14b80-551e-11e9-8f1b-750447a5206e.png)

**Comment by DragonSuper** [comment]
DRONE_SERVER_HOST needs public address
because https://github.com is public net address
so drone deploys public net？

**Comment by bradrydzewski** [comment]
I was unable to reproduce the issue. If you can provide more details, or send a patch, we can reopen.
