### ISSUE TITLE
Git clone is hanging on arm64 by gogs

### ISSUE THREAD

**Issue by DragonSuper** [drone/drone#2642]
Hi, I have a problem on arm64
Drone:1.0.0/lastest
Gogs:0.11.86/lastest
Docker:1.12.6, for api is 1.24
arch: arm64
git clone is not work , Information is as follows , has not error, just hanging, then failure:

Initialized empty Git repository in /go/src/gogs.xiaozheng.com/super/godev/.git/
+ git fetch origin +refs/heads/master:

But on amd64 is ok, just arch and docker version is different
arch: amd64
docker: 18.09.3,for api is 1.39
the info is:

Initialized empty Git repository in /go/src/gogs.xiaozheng.com/super/godev/.git/
+ git fetch origin +refs/heads/master:
From http://ip:port/xxx/godev
 * branch master -> FETCH_HEAD
* [new branch] master -> origin/master
+ git checkout 6c303fbf74ad509cbd0cb2b6b1f1e2c861211954 -b master
 Already on 'master'

docker run info on arm64，it is essentially the same with amd64:
docker run \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  --volume=/var/lib/drone:/data \
  --env=DRONE_GIT_ALWAYS_AUTH=false \
  --env=DRONE_GOGS_SERVER=http://xxx:10080 \
  --env=DRONE_RUNNER_CAPACITY=2 \
  --env=DRONE_SERVER_HOST=xxx:20080 \
  --env=DRONE_SERVER_PROTO=http \
  --env=DRONE_TLS_AUTOCERT=false \
  --env=DRONE_DEBUG=true \
  --env=DOCKER_API_VERSION=1.24 \
  --env=DRONE_RUNNER_PLATFORM=linux/arm64 \
  --publish=20080:80 \
  --publish=20443:443 \
  --restart=always \
  --detach=true \
  --name=drone \
  drone/drone:1.0.0-linux-arm64

I want to look at debug info by drone docker‘s logs，but just error info
error: clone exit code 128 
just so so，I Cannot be solved temporarily，So I need help，

thanks，thanks，thanks！
Docker Version issue？Arch Version issue？
I think my config is right，because it works on amd64.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
