### ISSUE TITLE
Issue with sub-projects with Gitlab

### ISSUE THREAD

**Issue by downright77086** [drone/drone#2643]
When not using sub projects Drone is fine when we try activation Drone with a sub-project we get a 404 error as follows.

```{"admin":false,"error":"404 Project Not Found","level":"warning","msg":"api: cannot sync repository permissions","name":"android-pipeline-test","namespace":"android","read":true,"request-id":"1JPTXf4qtGu0Uo5qJ9G4VQuGBby","time":"2019-04-04T16:36:13Z","user.login":"drone.ci","write":false}```

**Comment by bradrydzewski** [comment]
see this issue https://github.com/drone/drone/issues/2009

**Comment by rafaelri** [comment]
@bradrydzewski I'd like to help on this issue (actually on #2009 but as it is closed I cant send any message there).

**Comment by dromer** [comment]
@rafaelri did you have a look at this yet? for us this is also turning into an issue, we use the subgroups to de-clutter and organize some of our projects. It would be really great to have this capability.

**Comment by tboerger** [comment]
This is a pretty complex task, I have started to work on that but the whole UI part got to be changed.

**Comment by Wercurial** [comment]
@tboerger hi，now my team is want to use gitlab's subgroup for out project.Do you support this function now?
