### ISSUE TITLE
Allow environment variables in DRONE_RUNNER_VOLUMES

### ISSUE THREAD

**Issue by brandonocasey** [drone/drone#2646]
I would like all of my repositories to have their own host folder mounted via `${DRONE_REPO}`. Currently this is possible by trusting all repositories, and allowing each one to mount a host directory on their own. I am suggesting that `DRONE_RUNNER_VOLUMES` should allow appending a `DRONE_REPO` to the host path before a runner is created, and preferably before `drone.yml` has had a chance to alter any `DRONE_*` environment variables (if altering `DRONE_*` variables is even possible). 

Example: 
```yaml
DRONE_RUNNER_VOLUMES: "/var/www/html/${DRONE_REPO}:/webroot"
```

**Comment by bradrydzewski** [comment]
I think it would be helpful to step back and describe the problem that this is trying to solve before we discuss possible solutions. Can you describe your specific use case and why you want persistent folders mounted for each repository? What does this enable that Drone does not provide today?

**Comment by agnewp** [comment]
for us, a certificate for our company Github enterprise server got updated where your job's docker container root CA store did not have the latest entrust root CA. the way other containers in our cluster handle this is to map a read only volume to the node's root CA store.  there is no way we can find to deal with this issue currently. any suggestions?

**Comment by bradrydzewski** [comment]
@agnewp see https://docs.drone.io/reference/agent/drone-runner-volumes/

**Comment by agnewp** [comment]
i'll give it a try.  it is unclear to me weather this applies to only provisioned agents. Do these settings apply to running with a kubernetes provisioner?

**Comment by bradrydzewski** [comment]
This is only for agents. Warning that the native Kubernetes runtime is experimental and may be significantly modified over the coming months [1][2]. At this juncture I recommend using agents for a production installation, which are stable.

[1] https://github.com/drone/drone-runtime/issues/53#issuecomment-482473370
[2] https://github.com/drone/drone-runtime/issues/65

**Comment by agnewp** [comment]
okay, good to know. looking at the code i noticed affinity will probably also be a needed setting for running native k8s jobs. people like to have their specialized nodes after all.

**Comment by bradrydzewski** [comment]
affinity is supported with both agents and the kubernetes runtime https://docs.drone.io/user-guide/pipeline/nodes/

**Comment by bradrydzewski** [comment]
I am going to close this particular issue (interpolating environment variables in global volume string) in support of configuration plugins. Configuration plugins attempt to solve this exact problem by allowing you to mutate the configuration at runtime. This could be used to append per-repository volumes. 

Configuration plugins are not very well documented yet, however, there is some information in this thread, as well as links to a starter plugin project, as well as links to plugins that community members have created and published. These can be used for reference. See https://github.com/drone/drone/issues/1021#issuecomment-417819643 and subsequent comments in the same thread.
