### ISSUE TITLE
Suggestion: Use project directory name for workspace: base directory

### ISSUE THREAD

**Issue by atomi** [drone/drone#2648]
Using `src` as the default base path seems arbitrary.  

Would it not make more sense to use the projects directory name as the base as that is what the developer who created the project decided already?    
And I only say this because some tools do expect the project directory to be the same across builds.    

Just a suggestion. Perhaps it's too much of a breaking change - feel free to close.

**Comment by bradrydzewski** [comment]
Thanks for the suggestion, however, we will not be able to accommodate the request. Similar to the Go 1.0 compatibility guarantee [1] we are trying to avoid breaking changes now that Drone 1.0 is released. You can change the default directory, however, with the following syntax:

```
workspace:
  base: /go
  path: src/github.com/foo/bar
```

This historical reason for having a separate base and path was to support Go projects. The base could be set to the gopath to ensure dependencies were saved between steps. Going forward this is less important with the advent of Go modules, and with the addition of temporary volumes [2].

[1] https://golang.org/doc/go1compat
[2] https://docs.drone.io/examples/language/golang/
