### ISSUE TITLE
Missing documentation describing the use of named volumes

### ISSUE THREAD

**Issue by XhstormR** [drone/drone#2654]
I saw [this document](https://docs.drone.io/user-guide/pipeline/steps/#volumes) saying that it supports named volumes, but I have not found other pages that explain how to use them.

And I saw [this issues](https://github.com/drone/drone/issues/1348), has this feature been implemented in 1.0?

**Comment by bradrydzewski** [comment]
named volumes are documented at https://docs.drone.io/user-guide/pipeline/volumes/

If you have any further questions you can post to our community support forum at https://discourse.drone.io or our chatroom at https://gitter.im/drone/drone.
