### ISSUE TITLE
How can I build a docker image with the drone source code?

### ISSUE THREAD

**Issue by andyyumiao** [drone/drone#2655]
or where is the docker makefile?

**Comment by appleboy** [comment]
https://github.com/drone/drone/blob/master/docker/Dockerfile.server.linux.amd64

**Comment by laszlocph** [comment]
The makefile is the .drone.yml in the source code. This is how i do it: https://github.com/laszlocph/drone-oss/blob/master/.drone.yml

**Comment by bradrydzewski** [comment]
follow the build instructions in the BUILDING file to compile the binaries, and then run the following commands to build the Docker images:

```
docker build -f docker/Dockerfile.server.linux.amd64 -t drone/drone .
docker build -f docker/Dockerfile.agent.linux.amd64 -t drone/agent .
```
