### ISSUE TITLE
upgrade from drone 0.8.2 to 1.0 broke oauth flow when behind nginx-ingress

### ISSUE THREAD

**Issue by Morriz** [drone/drone#2657]
Ok, I have spent more than 16 hours trying to figure out what is going on, and have asked questions on discourse. I am now really certain that the oauth flow logic has changed and as such breaks oauth with github when drone runs behind an nginx-ingress (or istio gateway for that matter).

I get "Bad Credentials" with 1.0, but reverting to to 0.8.2 makes it work flawlessly. 

How can we increase debug output in drone server to see what it does with the http headers?

Honestly, I would love to see you guys deliver a working docker-compose setup including nginx-ingress. I will quickly do so myself now that I say this. I am pretty certain I can't make it work...

**Comment by tboerger** [comment]
We documented a working docker-compose setup. But since there are various reverse proxies out there it's intentionally left out.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
