### ISSUE TITLE
Drone+gogs webhook 

### ISSUE THREAD

**Issue by zzzacbbt** [drone/drone#2659]
gogs+Drone lastest
![image](https://user-images.githubusercontent.com/38638768/55930481-f725c780-5c53-11e9-9319-92035929aa37.png)
gogs webhook can work,but drone no change
![image](https://user-images.githubusercontent.com/38638768/55930495-16bcf000-5c54-11e9-9c2d-20956e27db56.png)
I want to know why?

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io). Also please note that we have a thread dedicated to this topic at https://discourse.drone.io/t/nothing-happens-when-i-push-code-no-builds-or-builds-stuck-in-pending/3424
