### ISSUE TITLE
Pipeline hangs when trigger.status is failure

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2667]
problem with build hanging when pipeline dependency graph is defined, where the final node in the graph should only execute on failure (below).

this was discussed in the comments of #2553 

```test
kind: pipeline
name: greeting

steps:
  - name: en
    image: alpine:3.8
    commands:
      - echo hello
      - echo world
      - sleep 10
      - exit 1

---
kind: pipeline
name: saludo

steps:
  - name: es
    image: alpine:3.8
    commands:
      - echo hola
      - echo mundo

---
kind: pipeline
name: salutation

steps:
  - name: fr
    image: alpine:3.8
    commands:
      - echo bonjour
      - echo monde
      - echo $DRONE_BUILD_STATUS

trigger:
  status:
+   - failure

depends_on:
  - greeting
  - saludo
```

**Comment by bradrydzewski** [comment]
closed by 3ba2c9ab3ad2ff688c029abe3d90e24c065ca8b4

**Comment by scidoc-coder** [comment]
I believe this is still an issue. I am also getting skipped with the lastest drone.

**Comment by bradrydzewski** [comment]
I tested to make sure there was no regression since this issue was closed, and everything worked as expected. You can see the example here:
https://cloud.drone.io/drone/hello-world/125

If you continue to experience issues I recommend creating a thread a [discourse](https://discourse.drone.io) and providing steps to reproduce, including a sample configuration. Without a sample configuration we cannot advise why this might not be working for you.
