### ISSUE TITLE
Don't see organisation's repositories

### ISSUE THREAD

**Issue by siberianguy** [drone/drone#2669]
I decided to give Drone.io a try, logged in using my GitHub credentials, granted access to my organization but still don't see any repositories from an organization. I tried out "Sync" just in case, did not help. I've googled this problem and most of the answers seem to revolve around the idea of not having access granted for an organisation but it should not be a problem in this case

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by bradrydzewski** [comment]
OP was using `cloud.drone.io` which is a free service for open source repositories only, and will not display private repositories. The behavior the OP was experiencing was therefore expected. For anyone else that comes across this thread please note, if you want to use Drone with private repositories you need to install and run Drone on your own servers.
