### ISSUE TITLE
Session cookie Secure flag and lifetime

### ISSUE THREAD

**Issue by exploide** [drone/drone#2671]
I noticed that the `_session_` cookie is not protected with the `Secure` flag. This happens even when `DRONE_SERVER_PROTO=https` is set. I would like to propose checking this environment variable and setting the `Secure` flag when appropriate. :smiley: 

Besides, the lifetime of the cookie is several decades long. Maybe this could be reduced a bit :wink:

**Comment by bradrydzewski** [comment]
Sure, I recommend sending a pull request. First you can add an environment variable to the configuration [1] and and pass to the session manager, and then you can update the session manager to set the value [2]. Should be a simple patch.

[1] https://github.com/drone/drone/blob/master/cmd/drone-server/config/config.go#L256
[2] https://github.com/drone/drone/blob/master/session/session.go#L46

> Besides, the lifetime of the cookie is several decades long. Maybe this could be reduced a bit 

the contents of the cookie is a cryptographically signed string that has the expiration date encoded in the value. So we have do an expiration date.

**Comment by exploide** [comment]
Thanks for the explanation! I'm not a go programmer but this looks comparably simple. Maybe I find time to do this.

One question: Why is the introduction of a new environment variable required? Can't we simply check if `DRONE_SERVER_HOST=https`? This does already exist.

**Comment by bradrydzewski** [comment]
> Why is the introduction of a new environment variable required

We do not want to make assumptions with regards to how people want their instances configured. It is possible to use Drone with http and https, and we do not want to break any existing installations.

In this case, and explicit configuration parameter is best.

**Comment by exploide** [comment]
> It is possible to use Drone with http and https, and we do not want to break any existing installations.

I don't see what possibly could break. If `DRONE_SERVER_HOST=https` but port 80 is still exposed, it does nothing more than returning a redirect to https. So everything should be fine.

Explicit configuration is usually a good idea, but it also introduces complexity and admins can easily forget to set the new variable to `true`. At least if the default is `false`.

Do you still demand a new variable and if yes what should the default value be?

**Comment by bradrydzewski** [comment]
we should use DRONE_COOKIE_SECURE as the variable name

**Comment by exploide** [comment]
Great, thanks!

I was working on a PR and had it almost ready but needed to look up some Go specific stuff first.

Thanks anyways :smiley:
