### ISSUE TITLE
Disable Pull requests and forks by default

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2672]
I think enabling pipelines for pull requests and forks by default is not good:
- You need to disable them in the UI every time you add a repo OR you must disable them in pipeline configuration if you don't want to see failed builds because pull requests and forks cannot access secrets by default (Which is good)
- Since any user can create a pull request or a fork it might be a possible security risk if some party starts creating these rapidly to increase load in the Drone server (DDOS)

**Comment by bradrydzewski** [comment]
sorry, there are no plans to change the current default behavior.
