### ISSUE TITLE
agent does not always gracefully shut down

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2678]
Watchtower (utility to auto-upgrade Docker images) is not properly stopping the Agent on upgrade, which causes stuck builds. The root cause is unknown and requires more research. Hopefully it is something simple ...

**Comment by bradrydzewski** [comment]
Note that the inability to gracefully shut down properly also impacts autoscaling.  In some cases the agent receives a SIGTERM and blocks indefinitely even though no builds are running. The end result is the autoscaler runs `docker stop --timeout=60` and it takes a full 60 minutes to stop the agent, when it should stop immediately.

**Comment by c2h5oh** [comment]
@bradrydzewski it's `-t 60` or `--time=60` and the unit is seconds, not minutes

**Comment by bradrydzewski** [comment]
we have a new implementation of the docker runner that solves this issue. This should be a drop-in replacement for the agent.  Some of the environment variables changed, but we do have some logic to try and map old variables to new variables [here](https://github.com/drone-runners/drone-runner-docker/blob/bcaf3a536c52a6077f346649fdc51eb5c72056cf/command/daemon/config.go#L106:L125) (if something is missing please send a pull request)

```
drone/drone-runner-docker:latest
```

I am going to leave this issue open since we are still testing this runner at cloud.drone.io.  Once testing is complete we will tag a release, update the documentation, and then close this issue.
