### ISSUE TITLE
Trigger build for Branch, Commit

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2679]
Currently the only way to programmatically trigger a build is by re-starting an existing build with a new build number via the API.  With 1.0 we now have the ability to fetch command branch data from version control, which means we can trigger a new build without any pre-existing data.

I propose adding the following endpoints:

```
POST /api/repos/{namespace}/{name}/builds
POST /api/repos/{namespace}/{name}/builds?branch={branch}
POST /api/repos/{namespace}/{name}/builds?branch={branch}&commit={commit}
```

Note that if no branch is provided, the default branch (master) is used.

**Comment by rvora** [comment]
Will there be a UI conterpart Build button (like Restart button). You'll need a way to specify / select branch as well as an optional commit.

**Comment by bradrydzewski** [comment]
For this first iteration it will be available via the API and the CLI.  There is a separate effort to add a branch summary screen to the user interface, at which point we will add a button to launch a build for a particular branch. I do not have a timeline for the UI, which is a separate team. Once I have more details I can post an update to this thread.

**Comment by ihakimi** [comment]
@bradrydzewski  does this feature already enabled on v1.1.0? I saw the PR merged on this version but when I send api with builds nothing happened,

**Comment by bradrydzewski** [comment]
@iamjarvo nope it is not part of any release yet. You would have to use master / latest. Also just a side note that you can often check on features and corresponding versions here https://github.com/drone/drone/blob/master/CHANGELOG.md 🙂

**Comment by ihakimi** [comment]
thanks @bradrydzewski 
Just wanted u know its the best ci/cd tool I have ever used!

**Comment by ihakimi** [comment]
@bradrydzewski , when is going to be support for params for /builds
```
		for key, value := range r.URL.Query() {
			if key == "access_token" {
				continue
			}
			if key == "target" {
				continue
			}
			if len(value) == 0 {
				continue
			}
			hook.Params[key] = value[0]
		}
```
I saw in promote its enable

**Comment by ViRb3** [comment]
I couldn't find an active GitHub repo for the docs, but these endpoints are missing from the official docs:
https://readme.drone.io/api/endpoints/builds/
