### ISSUE TITLE
Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by leftcoding** [drone/drone#2682]
my windows have two vmware. 
i want to set project SETTINGS - Project settings -Trusted.
but show error tip : Unexpected token I in JSON at position 0
i don't konw how to do.  
thanks you.
one vmware set gitea . ip:111.111.111.14:3000

version: "3.7"
services:
  gitea-server:
    image: gitea/gitea:1.7.1
    volumes:
    - ../gitea-data:/data
    ports:
    - "3000:3000"
    - "22:22"
    depends_on:
    - gitea-db
    restart: always

other vmware set drone-server and drone-agent. ip:111.111.111.14:80

version: "3.7"
services:
  drone-server:
    container_name: drone.server
    image: drone/drone:1.0.0
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
	- /var/run/docker.sock:/var/run/docker.sock
	- ../drone-data:/data
    environment:
	  - DRONE_GITEA_SERVER=http://111.111.111.14:3000
      - DRONE_TLS_AUTOCERT=false
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=sser
      - DRONE_SERVER_HOST=111.111.111.15
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:lingyan,admin:true 

  drone-agent:
    container_name: drone-agent
    image: drone/agent:1.0.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=111.111.111.15
      - DRONE_RPC_SECRET=sser

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
