### ISSUE TITLE
Include Action in when clause

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2685]
We should start tracking the action associated with a webhook, for example pull request opened/closed/syncronized and branch created/updated. We already store the action field in the database, so the changes would be primarily to:

1. ~~update the go-scm libraries to ensure actions are being set~~
2. ~~update the yaml when section to support actions~~
3. ~~update the yaml trigger section to support actions~~
4. update the /trigger package to evaluate actions
5. update the /runner package to evaluate actions

We should also consider aliasing `push` events as `branch` events to use in conjunction with `created` and `updated` events.

Example update to `when` clause:

```
when:
  event: [ pull_request ]
  action: [ opened ]
```

Example update to `trigger` clause:

```
trigger:
  event: [ pull_request ]
  action: [ opened ]
```

**Comment by aasm-moura** [comment]
Any workaround til we get this feature?

**Comment by lucianjon** [comment]
@bradrydzewski This would be pretty useful for us, any concerns if I were to pick up this work?

**Comment by bradrydzewski** [comment]
@lucianjon yes, I had originally hoped to ship this in 1.2 but I ran out of time. Some of the todos in the list were completed. I will update the issue to reflect which are completed this week so we can come up with a plan.

**Comment by bradrydzewski** [comment]
@lucianjon master now has the updated yaml structure which includes the `action` field in the when clause and in the `trigger` clause. In some cases the action clause is being populated, including pull request opened and synchronized actions.

Next steps are:

1. Update the trigger logic to support action
  https://github.com/drone/drone/blob/master/trigger/trigger.go#L255:L272
2. Update the when logic to support action (might require updated to drone/drone-yaml)
  https://github.com/drone/drone/blob/master/operator/runner/runner.go#L260:L270

**Comment by lucianjon** [comment]
@bradrydzewski Thanks for that, I'll take a look when I have a chance this week

**Comment by lucianjon** [comment]
@bradrydzewski I've created https://github.com/drone/drone-yaml/pull/48 and https://github.com/drone/drone/pull/2741

**Comment by lucianjon** [comment]
I just need to do some more testing around the when conditionals

**Comment by bradrydzewski** [comment]
@lucianjon I'm so sorry 😞we completely missed your pull request and implemented a subset of the functionality. Your pull request was actually much more complete (and better) so I was wondering if you would be willing to rebased and merge. If not I completely understand.

**Comment by bradrydzewski** [comment]
@lucianjon ignore my previous comment, I was able to resolve the merge conflict using the github web editor (had no clue this was possible). I should be able to get this merged soon!

**Comment by bradrydzewski** [comment]
merged into master

**Comment by VengefulAncient** [comment]
Is this currently supported? Please update the documentation if so.
