### ISSUE TITLE
Fallback to Database when S3 Blob Not Found

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2689]
this will allow teams to adopt S3 while still being able to access older logs stored in the database.

**Comment by tboerger** [comment]
That would be great, or alternatively some kind of migration.

**Comment by bradrydzewski** [comment]
@tboerger agreed. I will plan on also adding something to drone-migrate

**Comment by bradrydzewski** [comment]
the fallback is now in place, you can switch to S3 and drone will fallback to the database to display older logs. There is also an s3 log migration option at https://github.com/drone/drone-migrate#migrate-logs-from-08-to-10
