### ISSUE TITLE
 Could not resolve host

### ISSUE THREAD

**Issue by zhijiansd** [drone/drone#2690]
I am testing drone on kubernetes, drone can't clone my repository, this error occurs: fatal: unable to access 'http://gogs:3000/test/test.git/': Could not resolve host: gogs. I am using the flannel network, what should I do to solve this problem, I hope to get the answer from you, thank you!

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
