### ISSUE TITLE
Drone for Kubernetes not deleting local volume when finished

### ISSUE THREAD

**Issue by chrisghill** [drone/drone#2693]
This issue is discussed here: https://discourse.drone.io/t/drone-leaving-directories-behind-in-kubernetes/4395

To summarize: the code exists for the controller drone-job to remove the `/tmp/drone/<namespace>` directory after a build is finished, but the drone job isn't created with a volume mount for the `/tmp/drone` directory, so it is ineffective.

I'm mostly creating this issue to track a branch and link a PR.

PR is here: https://github.com/drone/drone/pull/2694

**Comment by bradrydzewski** [comment]
closing now that  #2694 is merged
