### ISSUE TITLE
Rollback disabled

### ISSUE THREAD

**Issue by andrewhowdencom** [drone/drone#2695]
Holaa,

It looks like Rollback is disabled: 

https://github.com/drone/drone/blame/1c6d751d50dded95fa6c28e9842bb9bf36c89440/handler/api/api.go#L191-L193

It's not clear why, though. Commit just says "squash and merge a local branch".

Is it supposed to be?

**Comment by bradrydzewski** [comment]
rollback is a new feature that was never enabled. Before we can enable the endpoint we need to make some modifications to the user-interface.

**Comment by andrewhowdencom** [comment]
Lovely!

**Comment by bradrydzewski** [comment]
the rollback endpoint is now enabled in master.
