### ISSUE TITLE
Bitbucket access

### ISSUE THREAD

**Issue by vadimkozak** [drone/drone#2696]
Hi everyone.

I started using self-hosted drone with bitbucket but as I see everyone can login to drone in my machine with their bitbucket and put some script there.

- How to give bitbucket users access only for specific team / projects / repo? 
  AND / OR 
- Is it possible to make some authentication in self-hosted drone? 

Thanks! Drone is great project!

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
