### ISSUE TITLE
[Feature] Autoscaler "fleet upgrade" on configuration changes

### ISSUE THREAD

**Issue by jimsheldon** [drone/drone#2700]
We have been evaluating the drone 1.x autoscaler on AWS.  One feature we would like to see is the ability to safely replace all agent instances when relevant configuration changes.  This ensures that all running agents have the latest configuration.  I imagine this would be an opt-in feature, and not the default behavior.

Looking at the autoscaler variables, it seems every `DRONE_AMAZON_*` variable change would trigger the "fleet upgrade".

**Comment by tboerger** [comment]
With the autoscaler you can also just loop through the launched agents and call destroy, that's how we enforce fresh agents based on latest configuration.

**Comment by jimsheldon** [comment]
Looping through is also an option, if that is safer we're happy to write a scripted process for that.

I would expect this to be low frequency, our group only changes these variables a few times a day at most.

**Comment by bradrydzewski** [comment]
@tboerger yep, today this can be achieved with a script that 1) uses the `pause` function to pause the autoscaler 2) loops through and destroys all servers with the `destroy` command and 3) unpauses the autoscaler so that it can launch new servers. The idea would be to wrap these steps in a single command to simplify the process.

@jimsheldon would these variables change by stopping and re-deploying the autoscaler (with something like terraform for example). Currently a restart is required for the new variable to take effect.

**Comment by tboerger** [comment]
Why do you need to pause it? Apply changes to autoscaler, destroy all agents and the autoscaler will directly launch new agents with the new config.

The old agents will anyway stop processing new jobs and just finish the already running jobs before they disappear.

**Comment by jimsheldon** [comment]
@bradrydzewski yes good point, our terraform run would destroy the autoscaler instance and bring up a new instance.  I imagine this would mean the autoscaler would have to maintain the state of all `DRONE_AMAZON_*` settings... That seems impractical.  Unless the autoscaler can easily diff the config it has locally with the agent instance configs...

If we had something scripted that uses the drone cli to replace all instances, we could probably run that as a terraform local-exec.

**Comment by bradrydzewski** [comment]
@jimsheldon would terraform somehow know the configuration changed, and be able to make an API call based on the change?

**Comment by jimsheldon** [comment]
@bradrydzewski I believe so, although I'm not positive

I think we can close this out.  Worst case we can write a script that would safely terminate all agents and start new agents.

**Comment by bradrydzewski** [comment]
I think it is still a good idea, but maybe we pilot as a script and then implement in core once we feel like we have things ironed out?

**Comment by jimsheldon** [comment]
Good idea, I'll share whatever we come up with
