### ISSUE TITLE
Distinct event trigger for Cron pipelines

### ISSUE THREAD

**Issue by chromko** [drone/drone#2705]
I can't skip some pipelines/steps during cron scheduling.
When I use cron jobs, I can set pipeline trigger with cronjob name to include this pipline during cron execution.
```
trigger:
  cron: ['cron']
```
But I can't exclude some pipelines/steps from all cronjobs. 
I tried to use something like
```
trigger:
  cron: 
    exclude: '*'
``` 
 to exclude cronjobs from common pipelines for pushing code to repo.
But when i commit to repo, I'm getting `trigger: skipping pipeline, does not match cron job`.

It would be nice to add event type 'cron' to avoid this problem. 
I think it'll look like
```
trigger:
  event: 
    exclude: 'cron'
``` 

Thanks

**Comment by random-ua** [comment]
I noticed that DRONE_COMMIT_BEFORE and DRONE_SOURCE_BRANCH are empty when build is triggered by cron. Could this be used to reliably distinguish between regular builds and cron-triggered ones ? Or this is something that will be changed in future versions ?

**Comment by bradrydzewski** [comment]
added support for `event: cron` in master.
