### ISSUE TITLE
Drone task branch matching

### ISSUE THREAD

**Issue by podollb** [drone/drone#2714]
When defining a drone task to have a branch condition such as:
```
branch:
  - snapshot/*
```

There seems to be a bug such that it doesn't match as expected (unless I'm missing something).

Hence, a branch like this matches fine (**success**):
```
snapshot/RP-1915
```

But a branch like this does not (**fail**):
```
snapshot/any-text/RP-1915
```

I would think the wildcard glob would match both?!

**Comment by bradrydzewski** [comment]
This is the expected behavior. If you want to match `snapshot/any-text/RP-1915` you would need `snapshot/**` or `snapshot/*/*`. Note that the `**` syntax may require Drone version 1.0 or higher.

**Comment by podollb** [comment]
Ah, thanks!
