### ISSUE TITLE
Build promote: Display environment

### ISSUE THREAD

**Issue by houzefa-abba** [drone/drone#2715]
With drone 1.1.0 I can promote (previously called deploy) a build with:
```
drone build promote [command options] <repo/name> <build> <environment>
```
where I can specify a target environment.

In the web interface however, I can't seem to find out which environment a build has been promoted to.

I only see:
```
user-xxx promoted `branch`
```

I would like instead:
```
user-xxx promoted `branch` to `env`
```
(or any other way to display that info.)

I remember drone 0.8 used to display target environments when running a `drone deploy`.

Thanks

**Comment by bradrydzewski** [comment]
we have existing issue https://github.com/drone/drone-ui/issues/276 for this
