### ISSUE TITLE
drone error for local gitlab

### ISSUE THREAD

**Issue by Felyne** [drone/drone#2716]
I follow this document:  https://docs.drone.io/installation/gitlab/single-machine/

My host ip is 192.168.40.50, the container started successfully. But  when I visit this URL 192.168.40.50:8020, i click the Authorize button ,return a error:

Login Failed. invalid character '<' looking for beginning of value

this is my run.sh:

`gitlab_server=http://192.168.40.131
gitlab_client_id=f87deee38725822e09ba2a4a47b245f31550ce441d2124b93460e424d4f41a0d
gitlab_client_secret=65fb35d513fa49c7660d338888a8a87cacfaaf6d5f46538a87803ef6f3c24d73
drone_server_proto=http
http_port=8020
drone_server_host=192.168.40.50:${http_port}
container_name=drone

docker run \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  --volume=/var/lib/drone:/data \
  --env=DRONE_GIT_ALWAYS_AUTH=false \
  --env=DRONE_GITLAB_SERVER=${gitlab_server} \
  --env=DRONE_GITLAB_CLIENT_ID=${gitlab_client_id} \
  --env=DRONE_GITLAB_CLIENT_SECRET=${gitlab_client_secret} \
  --env=DRONE_RUNNER_CAPACITY=2 \
  --env=DRONE_SERVER_HOST=${drone_server_host} \
  --env=DRONE_SERVER_PROTO=${drone_server_proto} \
  --env=DRONE_TLS_AUTOCERT=false \
  --publish=${http_port}:80 \
  --publish=443:443 \
  --restart=always \
  --detach=true \
  --name=${container_name} \
  drone/drone:1`

**Comment by tboerger** [comment]
`Login Failed. invalid character '<' looking for beginning of value` indicates that Gitlab doesn't respond as expected, are you really sure that Gitlab is answering requests on the defined IP from the Drone container?

**Comment by Felyne** [comment]
Callback URL is http://192.168.40.50:8020/login

**Comment by Felyne** [comment]
> `Login Failed. invalid character '<' looking for beginning of value` indicates that Gitlab doesn't respond as expected, are you really sure that Gitlab is answering requests on the defined IP from the Drone container?

**Comment by bukowa** [comment]
Make sure your `drone` container can find gitlab at `192.168.40.131`.
