### ISSUE TITLE
Feature/Kubernetes: Allow overriding randomly generated namespaces

### ISSUE THREAD

**Issue by NaurisSadovskis** [drone/drone#2717]
Hi there,

it would be great to override Drone creating randomly generated namespaces, thus running all builds in the same namespace as drone agents (`DRONE_KUBERNETES_NAMESPACE`) or using a custom namespace (`DRONE_KUBERNETES_BUILD_STAGE_NAMESPACE` ?) to address this. 

What do you think?

**Comment by bradrydzewski** [comment]
:wave: hey there, we have an open issue dedicated to this topic at https://github.com/drone/drone-runtime/issues/53

**Comment by NaurisSadovskis** [comment]
Thanks for the prompt reply!
