### ISSUE TITLE
Provide a stable latest image / 

### ISSUE THREAD

**Issue by alexanderadam** [drone/drone#2719]
@bradrydzewski once wrote that the `latest` Docker tag isn't considered stable for Drone.

IMHO `latest` is usually pointing to the same image like the latest stable version on other projects I know and therefore the best way to get the latest stable version in general.

So it would be nice to have at least one tag that is equal to that: a tag that points to the latest version that is considered stable.

**Comment by tboerger** [comment]
If you want to use a stable tag you should use :1, everything else could lead to breaking changes.
