### ISSUE TITLE
Don't run Docker image as root where it's not necessary

### ISSUE THREAD

**Issue by alexanderadam** [drone/drone#2720]
It would be nice if the Dockerfiles would use non privileged users instead of root where possible.

For example [like described here](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

[The server part could use a non-privileged port](https://github.com/drone/drone/blob/master/docker/Dockerfile.server.linux.amd64) because everyone can remap the port anyway on the host system for example.

**Comment by tboerger** [comment]
The docker images are running on scratch base images, so how should we add a user at all to it?

**Comment by bradrydzewski** [comment]
I recommend setting user namespaces when running an image [1]. The main process runs as root by default so that it can read and write to the host machine docker socket using default docker installation settings. 

[1] https://docs.docker.com/engine/security/userns-remap/

**Comment by alexanderadam** [comment]
@tboerger aren't all [Drone images based on Alpine](https://github.com/drone/drone/tree/master/docker)?

[I just saw an example like this one](https://github.com/mhart/alpine-node/issues/48#issuecomment-430902787):

```Dockerfile
ARG UID
ARG GID

USER root
RUN apk add --no-cache shadow sudo && \
    if [ -z "`getent group $GID`" ]; then \
      addgroup -S -g $GID dronegroup; \
    else \
      groupmod -n dronegroup `getent group $GID | cut -d: -f1`; \
    fi && \
    if [ -z "`getent passwd $UID`" ]; then \
      adduser -S -u $UID -G dronegroup -s /bin/sh droneuser; \
    else \
      usermod -l droneuser -g $GID -d /home/droneuser -m `getent passwd $UID | cut -d: -f1`; \
    fi && \
    echo "droneuser ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/droneuser && \
    chmod 0440 /etc/sudoers.d/droneuser

WORKDIR /home/droneuser/app
RUN chown droneuser:dronegroup /home/droneuser/app
USER droneuser
```

@bradrydzewski is access through the Docker socket necessary for _every_ image? Why is it necessary for the server image (which is probably often the most exposed application of a Drone setup)?

**Comment by bradrydzewski** [comment]
> Why is it necessary for the server image

50% of drone installations are running in single server mode, which means the server is also acting as the agent and therefore requires the host machine socket.

**Comment by alexanderadam** [comment]
So it would make sense to have an unprivileged option for all other installations then I guess?

**Comment by acim** [comment]
Take care that Drone would not run on OpenShift default rules. It would be really nice to fix this if possible.

**Comment by bradrydzewski** [comment]
> Take care that Drone would not run on OpenShift default rules. It would be really nice to fix this if possible.

This issue is related to the docker runner.  If you are running Drone on openshift you should be using the kubernetes runner.  If you want pipeline steps to run as unprivileged users you can either a) change the default USER in your images or b) change the user and group in your pipeline configuration as was recently enabled by [this pull request](https://github.com/drone-runners/drone-runner-kube/pull/25) specifically with openshift in mind.

**Comment by acim** [comment]
Well, I am using official Helm chart and run on Kubernetes. At the moment, Drone server is using docker.io/drone/drone:1.6.5 image, which runs as root. I would like to introduce a PodSecurityPolicy and dissallow containers to run as root, but Drone server would not run in that case.

**Comment by silverwind** [comment]
Some kind of option to create a unpriviledged user and run as it would be nice for those pesky programs that refuse to run as root.
