### ISSUE TITLE
0.8.x critical Bitbucket API issue.

### ISSUE THREAD

**Issue by matthewhartstonge** [drone/drone#2727]
https://github.com/drone/drone/blob/6d144de7355facbee613dd99afc5c4657b580808/remote/bitbucket/internal/client.go#L45

Seems to be the only line left that references version 1.0 of bitbucket's API which they have deprecated today.

Seeing the following for all repos in the logs:

```
time="2019-06-11T23:48:15Z" level=error msg="error: OUR_TEAM/OUR_REPO: cannot find .drone.yml in refs/heads/OUR_BRANCH: Resource removed"
time="2019-06-11T23:48:15Z" level=error msg="Error #01: Resource removed\n" ip=10.42.133.248 latency=13.657034392s method=POST path="/hook" status=404 time="2019-06-11T23:48:15Z" user-agent="Bitbucket-Webhooks/2.0"
```

**Comment by bradrydzewski** [comment]
This should be solved in Drone 1.x which uses all Bitbucket 2.0 endpoints. There are no immediate plans to backport changes to 0.8, although you should be able to build from source if you want to continue using the legacy version. Have you instead considered using the migration utility to upgrade your instance [1]? Drone 1.x is capable of reading 0.8 yaml file format to help with the upgrade path.

[1] https://github.com/drone/drone-migrate

**Comment by matthewhartstonge** [comment]
Ahh the migration tool exists.. 👌 
I thought that 'November 16th' meant 'November 16th 2019' [under the docs](https://docs.drone.io/releases/1.0.0-rc.1/#upgrading-important)

Will be upgrading today ;)

**Comment by bradrydzewski** [comment]
I'm going to re-open in the short term just to make sure Drone 1.x is working once you successfully upgrade and confirm everything is working. If you have any issues with the migration please post to our [discourse forum](https://discourse.drone.io).

**Comment by bchuntley** [comment]
Also experiencing this issue and we're about to migrate to 1.x.

Glad to have seen this because we were pulling our hair out trying to find the issue!

**Comment by bchuntley** [comment]
@bradrydzewski Just wanted to clarify, as far as migrating from sqlite3 to mysql, 
What would `-e TARGET_DATABASE_DATASOURCE=/path/to/new/database.sqlite` look like?

**Comment by roomthirteen** [comment]
Is there a reason why only one endpoint is referenced from the 1.0 api or could it maybe be changed to also use the 2.0 endpoint? 

The reason i'm asking is that migrating toi version 1.0 is not always so easy and takes time to realise. 

I'm currently having the issue with 1.0 that it is not possible to use a private docker registry to pull images from... or did I just not find the right documentation?

**Comment by bradrydzewski** [comment]
> Is there a reason why only one endpoint is referenced from the 1.0 api

at the time 0.8 was created, there was no 2.0 endpoint for content.

> or could it maybe be changed to also use the 2.0 endpoint?

one could fork and patch 0.8.  I do not have any immediate plans to backport changes to 0.8 since we are focused on 1.x going forward.

> I'm currently having the issue with 1.0 that it is not possible to use a private docker registry to pull images from... or did I just not find the right documentation?

there is full parity between 0.8 and 1.0 and in most cases, when using Drone 1.2.1, it is able to automatically convert the 0.8 yaml on the fly.

https://discourse.drone.io/t/drone-0-8-broken-due-to-bitbucket-v1-api-being-decommissioned/4816/4

**Comment by bradrydzewski** [comment]
lets move the discussion to our support forum at
https://discourse.drone.io/t/drone-0-8-broken-due-to-bitbucket-v1-api-being-decommissioned/4816

I will keep the github issue open for visibility so that others experiencing this issue can easily find this thread, and then follow-along in the forum.

**Comment by bradrydzewski** [comment]
I am going to close this now.  At this point most people have upgraded to the latest version of Drone or found an alternate solution to the Bitbucket API deprecation problem.

_For anyone just coming across this issue, if you are using Drone 0.8 with Bitbucket Cloud you will need to upgrade to Drone 1.0, which fully supports the version 2.0 Bitbucket endpoints._
