### ISSUE TITLE
Restart older build that succeeded

### ISSUE THREAD

**Issue by bouwerp** [drone/drone#2728]
Rebuild an older succeeded build, on the commit of that build.

**Comment by bradrydzewski** [comment]
perhaps I'm misunderstanding the ask, but you can re-start a build using the same commit via the command line utility or the restart button in the user interface. This creates a new build number and does not mutate the existing build.

**Comment by bouwerp** [comment]
Hi @bradrydzewski, thanks for responding so quickly. Sorry, my description was a bit vague. I see that failed builds can be restarted, but not successful builds. The button is available, but nothing happened when it is clicked. 

As a matter of fact, I tried it just now, and it worked! I really don't know what was up 😆 - I'm going to close this.

Brilliant project, by the way. We love golang and everything built with it.
