### ISSUE TITLE
Unexpected behavior of cron filters

### ISSUE THREAD

**Issue by random-ua** [drone/drone#2731]
I'd like to run certain pipeline on cron trigger only. Here's my pipelines configuration:
```
[
    {
        kind: "pipeline",
        name: "first",
        steps: [
            { name: "uname", image: "alpine", command: ["uname","-a"] }
        ],
        trigger: {
            event: ["push"],
        },
    },
    {
        kind: "pipeline",
        name: "second",
        steps: [
            { name: "env", image: "alpine", command: ["env"] }
        ],
        trigger: {
            event: ["promote"], // otherwise cron doesn't appear in output - see #2730
            cron: ["sample"]
        },
    }
]
```

After push initiated build I'm adding cron job with  
 `drone cron add org/repo sample "0 */15 * * *"`

Expected behavior:  pipeline `second` is executed every 15 minutes.  
Observer behaviour: pipeline `first` is executed every 15 minutes. No signs of second.

Also `drone build promote org/repo BUILD_NUMBER somewhere` doesn't start `second` pipeline either. Logs:
```
... trigger: skipping pipeline, does not match event ...
... trigger: skipping pipeline, does not match cron job ...
```

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
