### ISSUE TITLE
Add support for expr

### ISSUE THREAD

**Issue by antonmedv** [drone/drone#2736]
Please, add support for expressions via [expr](https://github.com/antonmedv/expr) evaluator.

**Comment by bradrydzewski** [comment]
:wave: Hey there, I appreciate the issue however Drone is adding dynamic expression support via Jsonnet and Starlark [1]. We previously had an expression evaluator compatible with sql [2] but we ended up moving in another direction. Cheers

[1] https://github.com/drone/drone/issues/2585
[2] https://github.com/drone/expr/blob/master/selector_test.go
