### ISSUE TITLE
Drone UI not accessible due to bad port configuration

### ISSUE THREAD

**Issue by Oduig** [drone/drone#2739]
Running `drone/drone:1` on Kubernetes results in a broken web UI. The cause seems to be a malformed port configuration, which is logged by the pod on startup:

    {"acme":false,"host":"drone.floorx.club","level":"info","msg":"starting the http server","port":"tcp://10.59.244.6:80","proto":"https","time":"2019-06-23T09:17:21Z","url":"https://drone.floorx.club"}

No explicit port is set. With this configuration, the web UI is inaccessible even when using `kubectl exec` to get into the pod. I currently use the following workaround.

    DRONE_SERVER_PORT: ":80"

Setting this should not be necessary, right? It seems like drone is auto-discovering some kind of cluster IP and adding it to the port config. Or maybe my configuration is wrong. I'm pasting the entire `yaml` file below.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
