### ISSUE TITLE
Feature: ability to rearrange the order of pending jobs

### ISSUE THREAD

**Issue by typeless** [drone/drone#2744]
Enabling users to drag & drop the pending jobs would be nice.
Currently, it has to be done by cancel & restart.

Use scenario:
Say, prioritizing release builds over casual development CI builds in the long queue.

**Comment by bradrydzewski** [comment]
after careful consideration, we have decided that re-ordering the build queue through drag and drop is outside the scope of what we are willing to build / support at this time.  Instead we will continue to invest our resources in improving the autoscaler to minimize queue times.
