### ISSUE TITLE
dependabot pull requests does not starts

### ISSUE THREAD

**Issue by skjnldsv** [drone/drone#2746]
Hi!

Sometimes, dependabots created pr does not starts.
The webhook payload is accepted (200) but returns `null`
Example: https://github.com/nextcloud/viewer/pull/151

![Capture d’écran_2019-07-02_18-50-26](https://user-images.githubusercontent.com/14975046/60530969-45e67900-9cfa-11e9-8c0e-08b2ac87b034.png)

What can I do to debug this?
I'm using drone.io

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io). You can also find information regarding builds not starting in [this thread](https://discourse.drone.io/t/nothing-happens-when-i-push-code-no-builds-or-builds-stuck-in-pending/3424).
