### ISSUE TITLE
Using JSON secrets

### ISSUE THREAD

**Issue by ronakh-thaikkat** [drone/drone#2752]
I have the GCR JSON key which I am trying to add as secret. I have basically copy pasted the JSON into the `secret value`. Assigning the secret to an environment variable and trying to `cat` is throws the following error

'
cat: unrecognized option: S
--
3 | BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
4 |  
5 | Usage: cat [-nbvteA] [FILE]...
6 |  
7 | Print FILEs to stdout
8 |  
9 | -n	Number output lines
10 | -b	Number nonempty lines
11 | -v	Show nonprinting characters as ^x or M-x
12 | -t	...and tabs as ^I
13 | -e	...and end lines with $
14 | -A	Same as -vte
15 | Error: Cannot perform an interactive login from a non TTY device
`
Is there a specific structure for adding JSON secrets to drone?

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
