### ISSUE TITLE
[bitbucket] Tag builds not executing

### ISSUE THREAD

**Issue by andrewmclagan** [drone/drone#2758]
# Expected behaviour

Tag builds triggered on pushing tags to remote

# Actual behaviour

Need to push the tag twice for it to be picked up. 

1. create tag and push it to remote
2. delete tag on local and remote
3. create and push it again -- build triggers

# Version

latest

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
