### ISSUE TITLE
Unable to deploy using the drone cli

### ISSUE THREAD

**Issue by mikeytsou** [drone/drone#2762]
Our application's drone.yaml file is currently in drone v0.8.0 and has yet to be migrated to v1.0.0. My drone cli is version 1.1.0. Do I need to downgrade my drone cli to v0.8.0 or is this backwards compatible? Both `drone deploy` and `drone build promote` dont work, I get this error: `invalid character '<' looking for beginning of value`. Can anyone provide some support on this?

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by ron-burgundy1** [comment]
see https://discourse.drone.io/t/drone-orgsecret-add-failing-on-windows/4832/2
