### ISSUE TITLE
server agent mode always in pending

### ISSUE THREAD

**Issue by firstsko** [drone/drone#2764]
drone 1.21
drone-server
version: "2"

services:
  server:
    image: drone/drone:latest
    environment:
      - DRONE_GITEA_SERVER=http://192.168.16.77:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY =2
      - DRONE_SERVER_HOST=192.168.16.77
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=username:root,admin:true
      - DRONE_MACHINE=192.168.16.77
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=false
      - DRONE_LOGS_NOCOLOR=false
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=root:Mm123456@tcp(192.168.25.154:3306)/drone?parseTime=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_RPC_SECRET=40c297ad6590ecf64d02313dd7b31728
    restart: always
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data
    ports:
      - "80:80"
      - "443:443"

drone-agent:
version: "2"

services:
  drone-agent:
    image: drone/agent:latest
    environment:
      - DRONE_RPC_SERVER=http://192.168.16.77
      - DRONE_RPC_SECRET=40c297ad6590ecf64d02313dd7b31728
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_MACHINE=192.168.16.77
      - DRONE_RUNNER_NAME=hoc154
      - DRONE_RUNNER_LABELS=disk:ssd,memory:high
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=false
      - DRONE_LOGS_NOCOLOR=false
    restart: always
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

drone-agent-log:
drone-agent_1  | {"level":"debug","msg":"successfully pinged the docker daemon","time":"2019-07-18T16:34:35Z"}
drone-agent_1  | {"arch":"amd64","level":"debug","machine":"hoc154","msg":"runner: polling queue","os":"linux","time":"2019-07-18T16:34:35Z"}
drone-agent_1  | {"arch":"amd64","level":"debug","machine":"hoc154","msg":"runner: polling queue","os":"linux","time":"2019-07-18T16:34:35Z"}

drone-server-log:
server_1  | {"arch":"amd64","kernel":"","kind":"pipeline","level":"debug","msg":"manager: request queue item","os":"linux","time":"2019-07-18T16:37:51Z","type":"docker","variant":""}
server_1  | {"arch":"amd64","kernel":"","kind":"pipeline","level":"debug","msg":"manager: request queue item","os":"linux","time":"2019-07-18T16:37:51Z","type":"docker","variant":""}

and I found the mysql nodes table is empty?

.drone.yml
kind: pipeline
name: dubhe-ci/cd

steps:
  - name: build
    image: node/v10.16.0
    commands:
        - npm install
        - npm test

node:
  instance: disk
      
drone-ci always in pending,an do nothing ...

**Comment by firstsko** [comment]
when I commit a push,the dreon always display pending ... 
if I set - DRONE_AGENTS_ENABLED=false 
server can be run the job

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
