### ISSUE TITLE
use TOML instead of YAML

### ISSUE THREAD

**Issue by catastrop** [drone/drone#2767]

**Comment by tboerger** [comment]
I can't see any benefit while using toml instead of yaml, so why should that even considered at all?

**Comment by tboerger** [comment]
I have seen your other previous issues for various projects, I don't expect any useful outcome, so I gonna close this issue.

**Comment by catastrop** [comment]
TOML is better than YAML. Even go dep uses TOML

**Comment by tboerger** [comment]
That's just one opinion, not a general fact. I personally totally dislike ini and toml file formats.
