### ISSUE TITLE
v0.8.0, Registry credentials not provided. Guest mode enabled.

### ISSUE THREAD

**Issue by 120011676** [drone/drone#2768]
![image](https://user-images.githubusercontent.com/1992933/62264475-a29c9700-b452-11e9-86fb-731759767eee.png)

![image](https://user-images.githubusercontent.com/1992933/62264507-c65fdd00-b452-11e9-99e3-e13258c876a5.png)

+ /usr/local/bin/dockerd -g /var/lib/docker --registry-mirror http://f1361db2.m.daocloud.io
Registry credentials not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
+ /usr/local/bin/docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: Alpine Linux v3.7 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.46GiB
Name: a5f0e6b868cf
ID: YMC3:WSVQ:JXWE:KJEE:7PTM:CMDM:4YM5:M2UV:BVYM:WRIP:I6FA:R6TE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://f1361db2.m.daocloud.io/
Live Restore Enabled: false

+ /usr/local/bin/docker build --rm=true -f Dockerfile -t ed70e9639c3869829ab1d26ae1c0e2b553335966 . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2019-08-01T02:50:16Z --label org.label-schema.vcs-ref=ed70e9639c3869829ab1d26ae1c0e2b553335966 --label org.label-schema.vcs-url=https://git.changhong.com/hlj/industry-equipment-center-fe.git
Sending build context to Docker daemon  16.17MB

Step 1/10 : FROM registry.changhong.com/ssc_yb_lfl/nginx:alpine
alpine: Pulling from ssc_yb_lfl/nginx
e7c96db7181b: Pulling fs layer
3fb6217217ef: Pulling fs layer
e7c96db7181b: Verifying Checksum
e7c96db7181b: Download complete
3fb6217217ef: Verifying Checksum
3fb6217217ef: Download complete
e7c96db7181b: Pull complete
3fb6217217ef: Pull complete
Digest: sha256:20b62c392073deac500292d6b37c851bb4d00986edb3d73d08c0f0e65019ce6c
Status: Downloaded newer image for registry.changhong.com/ssc_yb_lfl/nginx:alpine
 ---> ea1193fd3dde
Step 2/10 : MAINTAINER Say.li <120011676@qq.com>
 ---> Running in 591e3dea1d5e
Removing intermediate container 591e3dea1d5e
 ---> 5049aa21ca93
Step 3/10 : LABEL maintainer="Say.li <120011676@qq.com>"
 ---> Running in dd541d26b153
Removing intermediate container dd541d26b153
 ---> d5693b4a7997
Step 4/10 : ENV TZ Asia/Shanghai
 ---> Running in f69e48b3bdf0
Removing intermediate container f69e48b3bdf0
 ---> 6cad896226fd
Step 5/10 : RUN apk --update add tzdata && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
 ---> Running in 9dbf9558203a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
OK: 27 MiB in 37 packages
Removing intermediate container 9dbf9558203a
 ---> b81832e6f697
Step 6/10 : COPY ./nginx/ /etc/nginx/
 ---> df4193ec26a9
Step 7/10 : COPY ./dist /usr/share/nginx/html/ec
 ---> 5b60aebdcb7c
Step 8/10 : EXPOSE 80
 ---> Running in ee4a3b345801
Removing intermediate container ee4a3b345801
 ---> ca2e4dd36b44
Step 9/10 : CMD envsubst '$RCG_MGR_SERVER_URL $RCG_MGR_SERVER_LOCATION $MGR_HTML_LOCATION' < /etc/nginx/conf.d/default.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
 ---> Running in 713ae4b5d01d
Removing intermediate container 713ae4b5d01d
 ---> 3ddd0b567571
Step 10/10 : LABEL "org.label-schema.build-date"='2019-08-01T02:50:16Z' "org.label-schema.schema-version"='1.0' "org.label-schema.vcs-ref"='ed70e9639c3869829ab1d26ae1c0e2b553335966' "org.label-schema.vcs-url"='https://git.changhong.com/hlj/industry-equipment-center-fe.git'
 ---> Running in b4679ac4d10e
Removing intermediate container b4679ac4d10e
 ---> ca07aae29772
Successfully built ca07aae29772
Successfully tagged ed70e9639c3869829ab1d26ae1c0e2b553335966:latest
+ /usr/local/bin/docker tag ed70e9639c3869829ab1d26ae1c0e2b553335966 registry.changhong.com/industry/platform-ec-html:test_136
+ /usr/local/bin/docker push registry.changhong.com/industry/platform-ec-html:test_136
The push refers to repository [registry.changhong.com/industry/platform-ec-html]
34fbea13f7bb: Preparing
886d81c6454a: Preparing
b949f30766a7: Preparing
fbe0fc9bcf95: Preparing
f1b5933fe4b5: Preparing
denied: requested access to the resource is denied
time="2019-08-01T02:51:06Z" level=fatal msg="exit status 1"

**Comment by 120011676** [comment]
When will it happen?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [forum](https://discourse.drone.io).
