### ISSUE TITLE
Failed to create migrations tables in MySQL Group Replication

### ISSUE THREAD

**Issue by rluisr** [drone/drone#2771]
Add PK in `migrations` for GR.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by rluisr** [comment]
https://discourse.drone.io/t/failed-to-insert-data-into-migrations-tables-on-mysql-group-replication/5264
