### ISSUE TITLE
Update screenshots to drone 1.0 UI

### ISSUE THREAD

**Issue by miki725** [drone/drone#2775]
screenshots in https://github.com/drone/brand/tree/master/screenshots which are referenced in README are from old UI. Would be nice to update to latest UI but not sure where to access the octocat/hello world examples to take screenshots of. Alternatively maybe take screenshots of the drone build itself?

**Comment by christianruhstaller** [comment]
Home of "The Octocat" with the corresponding repositores: https://github.com/octocat

**Comment by briancurt** [comment]
I believe this is the new example https://cloud.drone.io/drone/hello-world.
