### ISSUE TITLE
Recommended way to restrict access to Drone server?

### ISSUE THREAD

**Issue by arianitu** [drone/drone#2779]
Hello, I was just wondering what the recommended way to restrict access to the Drone server after setting it up.

Any individual can come to your hosted version of Drone and spin builds. There is no way to restrict users or restrict which repos can be built. They just login with their github and then they can do whatever they want.

It's also a bit of a security risk, since users could spin up miners or whatever else. 

Is the recommended way to restrict drone access is basic auth while still allowing the /webhook URL open so github can communicate with the server? Also, if 2 users have access to a repo, do they both have to Activate that repo or does it only activate once?

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by arianitu** [comment]
@bradrydzewski hmm, I looked everywhere before making the issue, the documentation is not clear on how access works. I'm coming from Jenkins where you have an account and create builds and then those builds are assigned tasks.

The user access is just bizarre, why can any github user create an account and start executing actions on the Drone server. even users outside of the organization. Essentially it's like hosting a CI SaaS.

The documentation just makes no sense especially as a new user. I had to make sure to firewall before going public since there's no mention on how Drone even works when it comes to access. 

The Discourse forum points to nothing when searching for "Restrict access", the docs have nothing either.

**Comment by bradrydzewski** [comment]
Hi there, we do not use github issues for end user support. I am happy to help, but we direct all end user support questions to discourse or gitter, which you can create a new thread and ask your question.

**Comment by arianitu** [comment]
@bradrydzewski Apologies, I was a bit frustrated, but Drone does support this.

https://docs.drone.io/reference/server/drone-repository-filter/
https://docs.drone.io/reference/server/drone-user-create/

Next time I will follow up in the correct area (discourse, gitter.) 

I think the documentation needs some work, is there a way to contribute to it? For example, the docs suggest using the ClusterRole cluster-admin in the Kubernetes setup, but on my setup I created my own ClusterRole with limited permissions since using cluster-admin is dangerous.

Further, little comments like restricting user account creation to certain orgs, or allowing only certain users to activate accounts seems critical in the docs when setting up the server.

Cheers,

**Comment by iamsudip** [comment]
> https://docs.drone.io/reference/server/drone-repository-filter/
> https://docs.drone.io/reference/server/drone-user-create/
> 
@arianitu Getting 404 on shared links.
This would help other users: https://docs.drone.io/installation/security/registration/

**Comment by darkguy2008** [comment]
> > https://docs.drone.io/reference/server/drone-repository-filter/
> > https://docs.drone.io/reference/server/drone-user-create/
> 
> @arianitu Getting 404 on shared links.
> This would help other users: https://docs.drone.io/installation/security/registration/

Yeah, 404 too on => https://docs.drone.io/installation/security/registration/

Definitely @arianitu has a good point. The documentation on this part is scarse. Gitter/Discourse, meh. This is not exactly a "support" issue. The documentation is lacking, so it's definitely a **project** issue. 

Now, I've set up Drone all good on my server, but anyone with a repo account can log in and spin up builds. Same issue, 2020. How can I restrict access to the only admin user I've set in my ENV variables? (say, DRONE_USER_CREATE) ?

Any non-404 links or help is greatly appreciated.

**Comment by ashwilliams1** [comment]
this is discussed int he docs (at installation > user > registration)
https://docs.drone.io/server/user/registration/

**Comment by darkguy2008** [comment]
> this is discussed int he docs (at installation > user > registration)
> https://docs.drone.io/server/user/registration/

Yeah , I was about to edit my answer. That link gave me a 404 so I had to go around the docs. That one works, thanks!

**Comment by ashwilliams1** [comment]
> Definitely @arianitu has a good point. The documentation on this part is scarse. Gitter/Discourse, meh (plus, this issue shows up in google, seems GitHub has better indexing...?). This is not exactly a "support" issue. The documentation is lacking, so it's definitely a project issue.

you are welcome.  and thanks for the kind constructive feedback.
