### ISSUE TITLE
[Feature] Autoscaler: Support external secret servers

### ISSUE THREAD

**Issue by mmuehlberger** [drone/drone#2780]
The autoscaler doesn't support external secrets like `drone/amazon-secrets`, because it doesn't set the necessary environment variables.

It would be great, if passing the necessary environment variables `DRONE_SECRET_ENDPOINT` and `DRONE_SECRET_SECRET` would also be supported.

**Comment by bradrydzewski** [comment]
Hi there, you can use the `DRONE_AGENT_ENVIRON` environment variable for this. Use this variable to define addition configuration parameters that should be passed to the agent. For example:

```
DRONE_AGENT_ENVIRON=DRONE_KEY_A=aaa,DRONE_KEY_B=bbb
```

If you have any further questions about this topic, or the autoscaler in general, you can get in touch using our [support forum](https://discourse.drone.io) or our [chatroom](https://gitter.im/drone/drone).

**Comment by mmuehlberger** [comment]
Thanks. I wouldn't have opened an issue, if that was documented somewhere.
