### ISSUE TITLE
Manually Triggering a Cron Job

### ISSUE THREAD

**Issue by aamarill** [drone/drone#2781]
Currently the [cron-api](https://docs.drone.io/api/cron/) does not allow to manually trigger a cron job.

<img width="257" alt="Screen Shot 2019-08-08 at 10 42 42 AM" src="https://user-images.githubusercontent.com/29871004/62725083-4cd36c00-b9c9-11e9-876d-6587fea0261d.png">

As suggested by @bradrydzewski :

> something like `POST /api/repos/{namespace}/{name}/crons/{cron}/run`

If time permits, a button to trigger on the UI would be great as well :)

Thanks and keep doing great work!

**Comment by bradrydzewski** [comment]
the following endpoint was added in b950e28dd3c6f097a4503f6f9b90b805b728fc6a

```
POST /api/repos/:namespace/:name/cron/:cron
```

**Comment by mvdan** [comment]
@bradrydzewski would it be possible to add a button on the UI to do this? It seems generally useful, and it's often inconvenient to set up API access for simple actions.
