### ISSUE TITLE
nodeSelector,resource quota,namespace support for drone jobs.

### ISSUE THREAD

**Issue by lomkju** [drone/drone#2783]
Drone Version: v1.2.3
K8s Version: 1.13

Wanted to know if there are plans for adding nodeSelector, resource quota, namespace support for the k8s drone jobs?

Having an option to specify a nodeSelector, namespace, resources in the `.drone.yml` can help us segregate workloads better.

**Comment by bradrydzewski** [comment]
See https://github.com/drone/drone-runtime/issues/69
