### ISSUE TITLE
Login Failed. You need to sign in or sign up before continuing.:

### ISSUE THREAD

**Issue by jiangby123** [drone/drone#2794]
I entered the drone's homepage. After logging in to the gitlab account, I popped up this. Is there a configuration that I have less? I deployed it according to the official documentation.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
