### ISSUE TITLE
How can specified the k8s job‘s namespace and serviceaccount with drone ?

### ISSUE THREAD

**Issue by RottenLeaf24** [drone/drone#2796]
When a pipeline run ,the drone server will create a job in k8s.But the job always create in the default namespace ,and the job will create namespace to execute pipeline steps by the user system:serviceaccount:default:default.
![image](https://user-images.githubusercontent.com/41962159/63311823-fa337180-c331-11e9-8f37-913f3a667d5d.png)
So,I have to give the permission about create namespace to system:serviceaccount:default:default.
For isolation I want create a namespace ,such as "devops" ,then put the drone server and all of the drone job in this namespace.If the drone can do this?
I would be very grateful if you have good opinions.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
