### ISSUE TITLE
Edit secrets

### ISSUE THREAD

**Issue by jpic** [drone/drone#2798]
Currently to edit a secret you must:

- trigger a build with a hack to dump the current secret variable
- delete the secret in drone
- re-create the secret

Is it possible to make it easier ?

My use case is: I have a secret per deployement ie. STAGING_ENV that contains a multiline list of env vars. Then in my .drone.yml I do `export $(echo $STAGING_ENV| xargs)`.

Keep up the gr8 work :heart:

**Comment by bradrydzewski** [comment]
You can edit secrets using the `drone secret update` command:

```
drone secret update [repository] [--name] [--data]
```

for example:
```
drone secret update octocat/hello-world --name=password --data=correct-horse-battery-staple
```

**Comment by jpic** [comment]
Thanks @bradrydzewski, but is there another solution than pushing a commit with `echo $SECRET_NAME` to review the current value ?

**Comment by tboerger** [comment]
For security reason it's not possible to read the secret except directly from the database if the database encryption is disabled.

Another option could be external secrets.

**Comment by jpic** [comment]
It's certainly possible with echo $SECRET_NAME, after exposing the secret: it's what I'm currently doing.
As such, I wonder if the security effort creates any value, rather than just create new problems when migrating from gitlab-ci and others.
