### ISSUE TITLE
Do drone Support the SVN?

### ISSUE THREAD

**Issue by linux0x5c** [drone/drone#2799]
My CVS is SVN. Can I use drone?

**Comment by tboerger** [comment]
This is not supported so far, drone depends on the authentication and authorization by platforms like github, bitbucket, gitea or gogs.

If your platform provides apis for authentication and authorization it could be possible to integrate support, but I don't think this will get a priority by the team.

**Comment by linux0x5c** [comment]
OK,thanks,I got it.
