### ISSUE TITLE
Single-Machine Drone does not build on arm64 proc

### ISSUE THREAD

**Issue by djimmo** [drone/drone#2800]
Hi all,

I am trying to run a drone server v1 on raspberry pi arm64 processor. I can succesfully start up the server and see the web interface, hook up my GitHub account and the webhook starts a build task. However from this point the build status is stuck at pending and no logs are produced. Nothing happens from here.
I think the problem could be that drone server is trying to spin up a wrong architecture runner to do the building task. If I check the trace output after startup of the server I get the following configuration (_i have bold-faced the error I think_):

license: ""
authn:
  endpoint: ""
  token: ""
  skipverify: false
agent:
  enabled: false
azureblob:
  containername: ""
  storageaccountname: ""
  storageaccesskey: ""
cron:
  disabled: false
  interval: 30m0s
cloning:
  alwaysauth: false
  username: ""
  password: ""
  image: ""
  pull: IfNotExists
database:
  driver: sqlite3
  datasource: /data/database.sqlite
  secret: ""
datadog:
  enabled: true
  endpoint: https://stats.drone.ci/api/v1/series
  token: ""
docker:
  config: ""
http:
  allowedhosts: []
  hostsproxyheaders: []
  sslredirect: false
  ssltemporaryredirect: false
  sslhost: ""
  sslproxyheaders: {}
  stsseconds: 0
  stsincludesubdomains: false
  stspreload: false
  forcestsheader: false
  browserxssfilter: true
  framedeny: true
  contenttypenosniff: false
  contentsecuritypolicy: ""
  referrerpolicy: ""
jsonnet:
  enabled: false
logging:
  debug: false
  trace: true
  color: false
  pretty: false
  text: false
prometheus:
  enableanonymousaccess: false
proxy:
  addr: https://<my domain>
  host: <my domain>
  proto: https
registration:
  closed: false
registries:
  endpoint: ""
  password: ""
  skipverify: false
repository:
  filter: []
runner:
  local: false
  image: drone/controller:1.0.0
  **platform: linux/amd64**
  os: linux
  arch: arm64
  kernel: ""
  variant: ""
  machine: 47a7cce4e9fc
  capacity: 2
  labels: {}
  volumes: []
  networks: []
  devices: []
  privileged: []
  environ: {}
  limits:
    memswaplimit: 0
    memlimit: 0
    shmsize: 0
    cpuquota: 0
    cpushares: 0
    cpuset: ""
nomad:
  enabled: false
  datacenters:
  - dc1
  namespace: ""
  region: ""
  prefix: drone-job-
  image: ""
  imagepull: false
  memory: 1024
  cpu: 500
kube:
  enabled: false
  namespace: ""
  path: ""
  url: ""
  ttl: 300
  serviceaccountname: ""
  pullpolicy: Always
  image: ""
rpc:
  server: ""
  secret: ""
  debug: false
  host: <my domain>
  proto: https
s3:
  bucket: ""
  prefix: ""
  endpoint: ""
  pathstyle: false
secrets:
  endpoint: ""
  password: ""
  skipverify: false
server:
  addr: https://<my domain>
  host: <my domain>
  port: :80
  proto: https
  acme: false
  cert: ""
  key: ""
session:
  timeout: 720h0m0s
  secret: <secret>
  secure: false
  mappingfile: ""
status:
  disabled: false
  name: ""
users:
  create:
    username: ""
    machine: false
    admin: false
    token: ""
  filter: []
  minage: 0s
webhook:
  events: []
  endpoint: []
  secret: ""
  skipverify: false
yaml:
  endpoint: ""
  secret: ""
  skipverify: false
bitbucket:
  clientid: ""
  clientsecret: ""
  skipverify: false
  debug: false
gitea:
  server: ""
  clientid: ""
  clientsecret: ""
  skipverify: false
  scope:
  - repo
  - repo:status
  - user:email
  - read:org
  debug: false
github:
  server: https://github.com
  apiserver: https://api.github.com
  clientid: <id>
  clientsecret: <secret>
  skipverify: false
  scope:
  - repo
  - repo:status
  - user:email
  - read:org
  ratelimit: 0
  debug: false
gitlab:
  server: https://gitlab.com
  clientid: ""
  clientsecret: ""
  skipverify: false
  debug: false
gogs:

  server: ""
  skipverify: false
  debug: false
stash:
  server: ""
  consumerkey: ""
  consumersecret: ""
  privatekey: ""
  skipverify: false
  debug: false

Unfortunately I could not find anything in the documentation on how to change this parameter, to be sure the correct architecture is used. By looking at this configuration I see more options I wouild I like to customize, but have no idea how.. Is there some documentation that more clearly explains this?
I'm starting the drone server using docker-compose and passing some environment variables, are thes settings all customizable through these? Furthermore i'm behind a traefik reverse proxy

kind regards,
Djim

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
