### ISSUE TITLE
Please reopen #2628

### ISSUE THREAD

**Issue by mvdan** [drone/drone#2805]
I commented on https://github.com/drone/drone/issues/2628 a few months ago, as the issue as described was never fully implemented.

Can it be reopened, or at least clarified?

**Comment by tboerger** [comment]
Please don't raise a new issue for that, just comment on the referenced issue.

IMHO it's fine to only use triggers with separate pipelines. When is only used to limit specific steps.

**Comment by mvdan** [comment]
I only opened a new issue because the comments there weren't being noticed. I'd open a thread on the forum, but I haven't had success there in the past either :)
