### ISSUE TITLE
Running drone-agent error through kubernetes

### ISSUE THREAD

**Issue by Twoling** [drone/drone#2806]
#### drone-server：
          - name: DRONE_KUBERNETES_ENABLED
            value: "true"
          - name: DRONE_KUBERNETES_NAMESPACE
            value: default
          - name: DRONE_KUBERNETES_SERVICE_ACCOUNT
            value: drone-pipeline
          - name: DRONE_GIT_ALWAYS_AUTH
            value: "false"
          - name: DRONE_RPC_SERVER
            value: "http://drone"
          - name: DRONE_SERVER_HOST
            value: "drone"
          - name: DRONE_RPC_PROTO
            value: "http"
          - name: DRONE_RPC_HOST
            value: drone.devops:80
          - name: DRONE_SERVER_PROTO
            value: http
          - name: DRONE_RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: drone-secret
                key: secret
          - name: DRONE_DATABASE_DATASOURCE
            value: "/var/lib/drone/drone.sqlite"
          - name: DRONE_DATABASE_DRIVER
            value: "sqlite3"
          - name: DRONE_LOGS_DEBUG
            value: "true"
          - name: DRONE_GITEA_SERVER
            value: http://gitea.devops:3000

#### agent：
```
...
          - name: DRONE_RPC_HOST
            value: http://drone:80
          - name: DRONE_SERVER_HOST
            value: http://drone:80
          - name: DRONE_RPC_SERVER
            value: http://drone:80
          - name: DRONE_RPC_SECRET
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: DRONE_LOGS_DEBUG
            value: "true"
...
```
#### ERROR
```
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
{"arch":"amd64","error":"not implemented","level":"warning","machine":"drone-debug","msg":"runner: cannot get queue item","os":"linux","time":"2019-08-29T12:26:15Z"}
```

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
