### ISSUE TITLE
Whether the mirror repository address of drone/controller supports modification

### ISSUE THREAD

**Issue by Twoling** [drone/drone#2807]
## environment
* drone version： 1.2
* git server： gitea
* kubernetes： v1.15.1

#### image pull failed
```
drone-job-12-fe7phdp8folzz5pmq-6jssn   0/1     ImagePullBackOff
...
Back-off pulling image "drone/controller:1.2.3"
Error: ImagePullBackOff
```
I ran the drone on Kubernetes. After the build task was triggered, the drone created the job correctly in kubernetes. However, because Kubernetes failed to pull the drone/controller docker image in the internal network environment, whether the image address supports modification can be changed. Private registry address

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
