### ISSUE TITLE
Current build stage target variable

### ISSUE THREAD

**Issue by devdigital** [drone/drone#2811]
It would be useful to have access to the current deploy promotion target within a step. This is to avoid potential duplicate step commands for differing targets.

E.g. instead of:

```
name: deployTest
image: ... 
commands: - ./deploy.sh test
when: event: [ promote ] target: [test]

name: deployProd
image: ...
commands: - ./deploy.sh prod
when: event: [ promote ] target: [prod]
```

Have:

```
name: deploy  
image: ... 
commands: - ./deploy.sh $DRONE_BUILD_STAGE  
when: event: [ promote ]
```

Or, if the stage is an empty string when not promoted:

```
name: deploy
image: ...
commands: - ./deploy.sh $DRONE_BUILD_STAGE
```

**Comment by tboerger** [comment]
The promotion target is already available as an environment variable: https://docker-runner.docs.drone.io/configuration/environment/variables/drone-deploy-to/

**Comment by bradrydzewski** [comment]
closing since this feature is already implemented.
