### ISSUE TITLE
missing /api/info/queue endpoint documentation

### ISSUE THREAD

**Issue by naorlivne** [drone/drone#2814]
I'm thinking about how to set drone Docker workers to autoscale inside our Mesos/Marathon/Metronome cluster which isn't covered in the "offical" autoscaler & noticed it seems to have `/api/info/queue` endpoint that provides the needed info about the build queue - I found it referenced in a few closed tickets about it's creation but no documentation about it or any `/api/info` 

Is this endpoint still valid in 1.0 API? if so shouldn't it be documented?

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
