### ISSUE TITLE
API call to create PR builds

### ISSUE THREAD

**Issue by msaizar** [drone/drone#2815]
Currently working on this but my `go` is still weak. There are API calls to create builds, but these will be push event ones. Being able to create a build from a pull request number would be great.

https://github.com/drone/drone/blob/master/handler/api/repos/builds/create.go

**Comment by bradrydzewski** [comment]
you can use `/api/repos/{namespace}/{name}/builds/{number}` to launch a build from an existing pull request build.  If you activate the repository, there should already be a build entry for the pull request. What would be the scenario where a pull request does not exist for a build?  What is the target use case for this feature?

**Comment by msaizar** [comment]
Installing Drone in a repository with existing pull requests. There won't be builds for these

**Comment by bradrydzewski** [comment]
wouldn't you have to add a .drone.yml to the repository, and then re-synchronize the pull requests which would in turn trigger a builds?

**Comment by msaizar** [comment]
In my scenario, I'm using the remote configuration plugin, so the config is being picked up from another repository. Pushing an empty commit is a workaround but not very clean.

**Comment by bradrydzewski** [comment]
I think we need to understand whether or not this is an edge case, or if other members of the community require these capabilities.  If there is a broader benefit to the community then it would make sense to increase the size and scope of our codebase.

**Comment by msaizar** [comment]
I agree that this is a bit of an edge case. For me, the idea behind using the remote config plugin was to make the integration as frictionless as possible. Its just a small pain point, and there is a workaround available. Something like an API call, or closing/opening the PR to trigger a new build would be a nicety to have, to avoid pushing an empty commit.

**Comment by bradrydzewski** [comment]
after some consideration I have decided that this is going to be out-of-scope for Drone. The primary use case for this feature is the initial setup and installation of a repository, and typically we would expect syncing the pull request with the base branch to get the yaml and thus triggering a build.  This feels like too much of an edge case to commit to maintaining this in the long term.

if something changes we can certainly re-consider and re-open in the future.
