### ISSUE TITLE
Drone is not open source

### ISSUE THREAD

**Issue by dn0** [drone/drone#2821]
## User issue

The [README](https://github.com/drone/drone/blob/v1.3.1/.github/readme.md) and documentation should state that this project and its releases + docker images are not open-source software. Currently, this project including its [LICENSE](https://github.com/drone/drone/blob/v1.3.1/LICENSE) file gives the impression that it is a standard open source project. But in fact, the majority of source files is not open source.

## Contributor issue

The way how this project combines open source and proprietary code makes it very complicated to contribute. My understanding of this [comparison table](https://drone.io/enterprise/features/) is that the open source edition should be very limited. But this also means that any user contributions of interesting features may not be accepted or they may end up licensed as not open source code. For example the status badge feature in https://github.com/drone/drone/pull/2770

Furthermore, go.mod links to other drone repositories (libraries) that are also not open source. This makes it very difficult to ensure that the final build is made of open source code only.

I'm a bit worried about forking this repo and working on the open source part. I don't want to touch nor read the non-opensource files. Perhaps splitting the project into two repos (open source and enterprise) would help.

These two files are missing the `!oss` flag:

- https://github.com/drone/drone/blob/v1.3.1/handler/api/badge/status.go
- https://github.com/drone/drone/blob/v1.3.1/service/token/renew.go

Shouldn't the [BUILDING_OSS](https://github.com/drone/drone/blob/v1.3.1/BUILDING_OSS) instructions also mention the `nolimit` build flag?

## Background

I don't want to comment on the _Drone Non-Commercial License_ as there are a lot of discussions about this type of license on the Internet. I can just share my Drone story. And it is a short one: I mistakenly thought that I'm using the open source edition of Drone. I've used it since 0.8.x; read some official blog posts; checked this GitHub repo and Drone's Dockerhub page. But I didn't notice any information about this project not being open source software. Please fix this.

**Comment by aaahrens** [comment]
I'm also slightly confused because I use some of these "oss" features in "open source"

**Comment by briancurt** [comment]
I agree that the licensing and business model in general, which go hand in hand, are not very clear. This [Discourse post](https://discourse.drone.io/t/licensing-and-subscription-faq/3839) gives some context, but it was written only some months ago and has _twenty two_ subsequent edits. With all due respect, I feel that information is extremely important and should be at least on the main website and not in a forum post. Licensing is a key factor when taking a decision about a tool. I thought I was running open source too, then discovered the `5000` builds a year limit.

**Comment by laszlocph** [comment]
And that 5000 used to be 15000 few months ago...

**Comment by ashwilliams1** [comment]
> this project including its LICENSE file gives the impression that it is a standard open source project.

We believe the license file clearly and accurately conveys this repository contains the source code for the community version and the enterprise version, published under the open source apache2 license and enterprise license respectively.

 >The README and documentation should state that this project and its releases + docker images are not open-source software.

We agree the license and readme did a poor job of communicating that the official docker images were distributed under the enterprise license. The readme has been updated accordingly and now provides a disclaimer and instructions to build the open source and enterprise editions.

> But I didn't notice any information about this project not being open source software

This project includes source for an open source version and a non-commercial version. We do not believe such a blanket statement would be accurate. We can agree to disagree.

> These two files are missing the !oss flag

The files in question had incorrect file headers and were updated accordingly. These files were meant to be apache2 licensed and included in the open source version.

> The way how this project combines open source and proprietary code makes it very complicated to contribute [...]

This is common for many large projects, including GitLab.  We acknowledge your feedback however we do not have any plans to restructure our codebase at this time.

> This Discourse post gives some context, but it was written only some months ago and has twenty two subsequent edits

Every time we get a question about licensing we update the FAQ to ensure it is comprehensive and unambiguous. The number of edits reflect our efforts to provide clear licensing information to the community. Is this not a good thing?

> I feel that information is extremely important and should be at least on the main website and not in a forum post

You may have noticed significant updates to the documentation over the past weeks. The plan is to move all posts in the FAQ section of the forum to the documentation, including the license FAQ, which will have its own section. These things take time. We have limited time and resources and do the best we can to prioritize and work through our backlog.

I am closing this issue as we have revised the README and updated the license headers for the files in question.
