### ISSUE TITLE
I want to know if drone can be deployed multi different servers with one gitlab repository

### ISSUE THREAD

**Issue by dayuoba** [drone/drone#2829]
i want to deploy drone at two k8s clusters with only one same repository?
i want to know is it possible? for now one drone server can be triggered, and the other can not be triggered

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
