### ISSUE TITLE
Pipeline Cron schedule skipped if HEAD commit contains [ci skip]

### ISSUE THREAD

**Issue by jndeverteuil** [drone/drone#2835]
**Summary**
A pipeline Cron schedule for a branch is not executed if the HEAD commit of that branch contains [ci skip] in its commit message.

**Steps to reproduce**
Create a nightly pipeline schedule for the master branch
Make a commit on master with [ci skip] in the commit message, and push that commit to GitLab

**Current behavior?**
The nightly schedule will not be executed.

**Expected behavior?**
The nightly schedule should be executed. The commit message instructs GitLab to not create a pipeline for the push, but the nightly schedule should still be executed. Similarly, Drone ignore CI SKIP for tag events.

**Consider the following situation:**

- Have a nightly pipeline schedule for the master branch. As part of your CI process, you check used dependencies for security issues (e.g. using nsp). The idea is that you will get a "failed pipeline" email when a security issue is found in one of your javascript libraries.
- Make a small fix to a readme file and add [ci skip] to the commit message
- Don't do any commits for a few days
- No pipeline schedules for the master branch will be running, and hence you won't be notified on security issues anymore

One could argue that we do not want to run scheduled pipelines for [ci skip] commits, but then we have to run a scheduled pipeline for the last commit of that branch that is not [ci skip].

----
_[Example taken from S. Schweizer as it clearly explains the issue applicable to Drone CI](https://gitlab.com/gitlab-org/gitlab-foss/issues/34618)_

**Comment by bradrydzewski** [comment]
we disabled `[CI SKIP]` for tag events and could do the same for cron events. It makes sense to me.

**Comment by bradrydzewski** [comment]
this behavior was changed in b950e28dd3c6f097a4503f6f9b90b805b728fc6a and is available in the latest docker image.
