### ISSUE TITLE
scratch plugin does not work

### ISSUE THREAD

**Issue by dayuoba** [drone/drone#2836]
i've a scratch based binary image, but when i configure drone's command of this plugin, it fails of no /bin/sh found, i think it may be that drone call `sh -c`  for each command. has any settings can i set it for only run my own command not `sh -c`

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
