### ISSUE TITLE
If the function provided to db.Update() panics, the transaction will not be rolled back

### ISSUE THREAD

**Issue by e-nikolov** [drone/drone#2842]
https://github.com/drone/drone/blob/master/store/shared/db/db.go#L110

If fn() panics, the tx.Rollback() will not be executed, and the transaction will not be released until it times out.

**Comment by bradrydzewski** [comment]
can you share more about the panic you experienced?

**Comment by tboerger** [comment]
Does any of the functions panic at all?

**Comment by e-nikolov** [comment]
I haven't experienced any panics, I was just browsing through the code and noticed that if for whatever reason the function supplied to db.Update panics, it will cause problems. Had a similar issue a while back in one of my projects and it was quite difficult to debug so I thought I should report it.

**Comment by bradrydzewski** [comment]
on one hand I feel pretty confident in the code given that the code has been used in production for many years by many people and it has not been an issue. On the other hand I am pretty paranoid about unexpected panics creating locks.

in this case I decided that some extra safety certainly doesn't hurt
https://github.com/drone/drone/commit/d60054c45943ec3bba5a345a11beb568c45a4b87#diff-e3263587fce93b98f28b299f1db9eb14R111
