### ISSUE TITLE
user defined annotations for kubernetes scheduler

### ISSUE THREAD

**Issue by tlipatov** [drone/drone#2844]
The annotations set by the kubernetes scheduler are hardcoded. There should be a way to add extra user defined annotations. Many people use them for cluster automaton and monitoring. 
One usecase is kube2iam annotations to allow the runner to assume AWS IAM roles.

**Comment by bradrydzewski** [comment]
there is existing issue https://github.com/drone/drone-runtime/issues/38, however, please also be aware of https://github.com/drone/drone-runtime/issues/69.
