### ISSUE TITLE
How to execute tasks in sequence to avoid conflicts？

### ISSUE THREAD

**Issue by think2011** [drone/drone#2847]
![image](https://user-images.githubusercontent.com/3961388/65825374-b6287a80-e2a8-11e9-8b5d-c04fafbdd8ac.png)

As the picture shows, when the task #24 is completed, it will be deployed an old version.
How to avoid this situation?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

Beside that you could set the allowed concurrency within your drone config.

**Comment by think2011** [comment]
thank you, it's working, but  `concurrency`  is not in the document. 😕

```yaml
kind: pipeline
type: docker
name: Default

concurrency:
  limit: 1
```
