### ISSUE TITLE
documentation not up to date/right

### ISSUE THREAD

**Issue by dolanor** [drone/drone#2848]
The [documentation on cloning](https://docker-runner.docs.drone.io/configuration/cloning/) is wrong.
It says to use the alpine:git image for cloning. This image doesn't exist.

Also, a `go build` won't work by default on `golang` image because the drone workspace is on `/drone/src` volume and the GOPATH in the `golang` image points to `/go`. So, it clones a Go project to `/drone/src` which is outside GOPATH. And the build will fail because it can't get the deps right.
I guess the solution would be to have a Go project using modules. I haven't tried yet.

**Comment by bradrydzewski** [comment]
> It says to use the alpine:git image for cloning. This image doesn't exist.
if you find issues with the docs please send a pr to https://github.com/drone-runners/drone-runner-docker/tree/docs

> go build won't work by default on golang image because the drone workspace is on /drone/src volume and the GOPATH in the golang image points to /go

go build works by default if you use go modules. we provide examples for how to use Drone with gopath and goodules in the docs:
https://docker-runner.docs.drone.io/examples/language/golang_gopath/
https://docker-runner.docs.drone.io/examples/language/golang/
