### ISSUE TITLE
What version am I running?

### ISSUE THREAD

**Issue by mattzuba** [drone/drone#2849]
There doesn't seem to be an indication anywhere that I am able to find that shows me exactly what version of Drone I'm running.  I don't see anything in the web interface, the CLI doesn't seem to query or show this information nor am I able to find it in the database.  I use `image: drone/drone:1` in my docker-compose file to make it easier for upgrades (`docker-compose pull`, `docker-compose up -d`), so I know I'm on the 1.x series, but I have no idea which version at a glance.  I just did a `pull` and `up` this morning so I'm assuming I'm on 1.5 now, but I can't confirm.

Please consider this a feature request to display the version of Drone somewhere - footer, CLI, etc.  If there is a way to determine this that I'm missing, please let me know and I'll happily close this issue.

**Comment by ashwilliams1** [comment]
you can access the version at `/version` and we have an existing issue to display in the user interface directly. you can subscribe to https://github.com/drone/drone-ui/issues/288 for updates.

**Comment by mattzuba** [comment]
Thanks!
