### ISSUE TITLE
More descriptive fail build messages.

### ISSUE THREAD

**Issue by kkszysiu** [drone/drone#285]
Hello.

I'm using private drone deployment and started to test it a little.

When my app is failing to build I only get message: 
"HTTP code: 404"
Which is not descriptive enough to track this problem.

Is there possibility to get whole building logs? Are they saved somewhere on server?
Anyway, I think this message should tell more about problem. At least URL should be included, right?

**Comment by bradrydzewski** [comment]
fixed with #777
