### ISSUE TITLE
Add more trigger events

### ISSUE THREAD

**Issue by ViRb3** [drone/drone#2852]
Would be awesome if we had the following trigger events:
- cron
- webapi

**Comment by ashwilliams1** [comment]
see https://github.com/drone/drone/issues/2705

**Comment by ViRb3** [comment]
What about webapi?

**Comment by tboerger** [comment]
What kind of trigger should be webapi? Doesn't make sense

**Comment by ViRb3** [comment]
https://github.com/drone/drone/issues/2679#issue-435262568
https://docs.drone.io/api/endpoints

That would be any build triggered by the web API :)

**Comment by bradrydzewski** [comment]
when you manually trigger a build with the API it uses event type `custom`

**Comment by ViRb3** [comment]
Perfect, thank you! Is there any place I could contribute such information to the docs or is it closed source now?

**Comment by bogdan-calapod** [comment]
> when you manually trigger a build with the API it uses event type `custom`

This should be added in the docs, eventually with a bit more info. I think this would go a long way in improving the DX :D
