### ISSUE TITLE
Can gerrit be used?

### ISSUE THREAD

**Issue by anstns** [drone/drone#2862]
Can gerrit be used?
Can I manually configure the git repository after the program is started?

**Comment by tboerger** [comment]
Currently this is not possible. To get Gerrit integrated it got to be implemented into go-login and go-scm first.

Drone is using the authentication and authorization of the source code providers, that's why this got to be implemented first.

**Comment by anstns** [comment]
This is not elegant, if it is authorized after startup, follow the git protocol, it is very flexible and can satisfy any warehouse.

**Comment by anstns** [comment]
Do you know that there are such open source tools?

**Comment by tboerger** [comment]
It is absolutely elegant because it's using well known standards like OAuth2. It's not only about git protocol, this is simply not enough.

**Comment by bradrydzewski** [comment]
Drone tightly integrates with a source control management system (github, gitlab, etc) for authentication, authentication, access controls and permissions, webhooks to trigger pipelines and more.  Drone made the __explicit__ design decision to tightly integrate with these systems and provide a more integrated experience

> Do you know that there are such open source tools?

Drone cannot do everything for everyone.  It sounds like it does not meet your requirements, so I am glad to hear you have other systems you can use.
