### ISSUE TITLE
drone-runner-docker amd64 vs arm64

### ISSUE THREAD

**Issue by iRbouh** [drone/drone#2865]
Hey,

The `DRONE_PLATFORM_ARCH` variable is not correct in the docker hub! amd64 for linux-arm64 and arm64 for linux-amd64.

Good luck,

**Comment by ashwilliams1** [comment]
hey there, thanks for the report, I recommend sending a patch or creating an issue in the designated issue tracker for the target repository.

**Comment by bradrydzewski** [comment]
>  I recommend sending a patch or creating an issue in the designated issue tracker for the target repository.

No need, I went ahead and fixed.

Please note that the drone-runner-docker is pre-release and is not fully functional. Only contributors or collaborators should be using this image until the official release is available. Until then you should continue using the drone/agent image 🙂
