### ISSUE TITLE
drone server doesn't support custom port

### ISSUE THREAD

**Issue by fred214** [drone/drone#2866]
For some reason I can not use the 80 and 443 port for the drone server, and I set the port when `docker run`
>   --publish=8080:80 \
>   --publish=8443:443 

I noticed that after some url redirection it failed.
I found the `:http` and `:https` about port in the `drone/server/server.go`. It looks like the hard code and meaning not support custom port.

Can you give some advice in my situation?
Thanks a lot

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
