### ISSUE TITLE
fluxctl 

### ISSUE THREAD

**Issue by BitProcessor** [drone/drone#2868]
Hi, 

we are running the Drone server component on Kubernetes, with a GitOps strategy managed by Fluxctl: https://github.com/fluxcd/flux 

Flux is having trouble with the drone docker repo:

ts=2019-11-04T13:52:51.932875392Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/drone/drone auth={map[]} warn="manifest for tag 1.0.0-rc.6 missing in repository drone/drone" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"

Log messages were piling up so high, I had to replace the official image with a copy for the time being. Can you please check your docker repository and clean the above?

Thanks in advance for a great product. Using it for 95% of all our builds (goal 100%) here at SupplyStack.com

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by BitProcessor** [comment]
How is this end-user support? I’m notifying you guys of an issue with one of the images in your docker repo?

**Comment by bradrydzewski** [comment]
hey there, `1.0.0-rc.6` was deprecated and removed from our registry a few months ago. I am not familiar with flux, but is expected that this image does not exist.

**Comment by masterkain** [comment]
I have the same issue.
@BitProcessor did you already tried to contact flux team?

**Comment by BitProcessor** [comment]
> I have the same issue.
> @BitProcessor did you already tried to contact flux team?

Yep, contacted them by mail. It's an issue with Docker Hub, see the following issue:
https://github.com/fluxcd/flux/issues/2517
