### ISSUE TITLE
what is drone agent? 

### ISSUE THREAD

**Issue by JennerChen** [drone/drone#2873]
I am new to drone. I follow docs to install drone on my local server, everything works fine. I also use vault share secrets between reps, and install the related extension https://github.com/drone/drone-vault .  the extension docs say I need put some config to drone agent
```
Update your Drone agent configuration to include the plugin address and the shared secret.

DRONE_SECRET_ENDPOINT=http://1.2.3.4:3000
DRONE_SECRET_SECRET=bea26a2221fd8090ea38720fc445eca6
```
The problem is I can't find docker agent in docs.drone.io. please help me.
Is drone runner is replacement to drone agent ? But I can't find similar config in drone runner reference https://docker-runner.docs.drone.io/installation/reference/

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
