### ISSUE TITLE
Any plans to support "generic git repos"?

### ISSUE THREAD

**Issue by danechitoaie** [drone/drone#2874]
Currently I see GitHub, BitBucket, etc. as supported "triggers".
Are there any plans to support generic git repo, where Drone just clones the code using a SSH key?
Basically I'm looking to be able trough an API to just tell Drone to trigger a build (this repo, this SSH key, etc.) and for me to manage externally the webhook events coming from Github, or any other platform and then just go to drone and tell it to start the build.

**Comment by tboerger** [comment]
The entire authentication and authorization model of Drone relies on the source provider, e.g. GitHub/Bitbucket/Gitlab/Gitea/Gogs, so it's not possible to use a generic git repository.

**Comment by bradrydzewski** [comment]
Drone tightly integrates with a source control management system for authentication, authorization and permissions, and more. At this time there are no plans to support generic git.

**Comment by Arteneko** [comment]
Would it be possible to allow for no authentication, e.g. in the context of a local / personal development environment, or instead use PAM / LDAP / Unix-based authentication ?
