### ISSUE TITLE
S3 region question

### ISSUE THREAD

**Issue by tcrowe** [drone/drone#2883]
Our s3-like service is not on amazon.

I get this message in the log but I could not find it in the source.

```json
{"error":"MissingRegion: could not find region configuration","level":"warning","msg":"manager: cannot upload complete logs","step-id":4,"time":"2019-11-22T02:35:29Z"}
```

Do you know if that associated with s3 region like these?

https://github.com/drone/drone/blob/fa0ebede19a9a5bcf7fbb0e661342a9dc46d0a8e/cmd/drone-server/config/config.go#L383

In the meantime I will try to figure it out too. I have heard Go is nice to work with although I have not tried. In the chance I succeed I will PR this!

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
