### ISSUE TITLE
gitlab cann't sync repositories.

### ISSUE THREAD

**Issue by mouyong** [drone/drone#2886]
gitlab cann't sync repositories.

![image](https://user-images.githubusercontent.com/10336437/70118746-b7f52c80-16a3-11ea-9dbf-ae76edac1b03.png)

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
