### ISSUE TITLE
RFC: Failure step without stopping

### ISSUE THREAD

**Issue by grachevko** [drone/drone#2888]
Pipelines have some steps which important to prevent merging PR, but not important to run tests.
Code style checking for example. 
Today i can ignore failure of step but it will stop build. I want to not stop build, but fail whole build.

**Comment by ashwilliams1** [comment]
I believe this capability already exists. Lets move the discussion to [discourse.drone.io](https://discourse.drone.io) and, if you provide an example, we can help you adjust your yaml accordingly.
