### ISSUE TITLE
Gogs webhook timeout

### ISSUE THREAD

**Issue by LGinC** [drone/drone#2891]
Gogs：0.11.86.0130
Drone: Latest
Docker: 18.09.7
repo has actived.  and test Delivery,
read tcp 172.17.0.6:59468->192.168.1.122:8000: i/o timeout
![image](https://user-images.githubusercontent.com/15363011/70595774-247da780-1c1f-11ea-8ec2-e5fcb3ed8e67.png)

![image](https://user-images.githubusercontent.com/15363011/70596535-1f215c80-1c21-11ea-81a6-f93ee730096b.png)

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
