### ISSUE TITLE
organization secrets

### ISSUE THREAD

**Issue by hhy5861** [drone/drone#2896]
organization secrets This organization is the project group corresponding to gitlab?

http://xxx.com/java/trade

(java) is organization?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
