### ISSUE TITLE
Running and targeting multiple runners

### ISSUE THREAD

**Issue by mintyowl** [drone/drone#2901]
Hi, I already have one exec runner (ER-1) running on one machine connected to drone server (DS-A). Now I want another exec runner (ER-2) to be run on another machine. And I want certain .drone.yml files to target ER-1 and others to target ER-2.

My questions:

1. Is it possible to run multiple exec runners on separate machines connected to DS-A
2. If Yes, then how can I tell repositories (via .drone.yml) to target specific runner?

Thanks

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
