### ISSUE TITLE
Build-limit confusion

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone#2908]
# This belongs to Discourse but I seem not to have permissions to create topics there.
Hi,

[Licensing and subscription FAQ](https://discourse.drone.io/t/licensing-and-subscription-faq/3839) states the following:

>**Is Drone Enterprise Edition Free?**
>***Yes*** , the official docker image provides free access to all Drone Enterprise features, for up to 5,000 builds. This includes both commercial and non-commercial use.

But [Open Source / Enterpise comparison matrix](https://drone.io/enterprise/features/) states that **Builds** for Open Source and Enterprise are both unlimited.

Which statement is correct?

**Comment by bradrydzewski** [comment]
build for enterprise edition are unlimited with purchase of a license
