### ISSUE TITLE
drone-exec-runner service start exit status 1

### ISSUE THREAD

**Issue by NiklasRosenstein** [drone/drone#2917]
Hi,

Trying to set up `drone-exec-runner` on Linux and I'm getting this error when trying to start the service:

```
$ drone-runner-exec service start 
starting service drone-runner-exec
drone-runner-exec: error: exit status 1, try --help
```

Checking `drone-runner-exec service start --help` shows that it will load the config file from `/home/niklas/.drone-runner-exec/config`. This is the content of my config file:

```
$ cat /home/niklas/.drone-runner-exec/config"
DRONE_RPC_PROTO=http
DRONE_RPC_HOST=localhost:9610
DRONE_RPC_SECRET=REDACTED
DRONE_LOG_FILE=/home/niklas/.drone-runner-config/log.txt
DRONE_RUNNER_CAPACITY=4
```

I can get it working, sort of, when I change the config file to to a bash script and then source it.

```
$ cat ~/.drone-runner-exec/config 
export CLIENT_DRONE_RPC_PROTO=http
export CLIENT_DRONE_RPC_HOST=localhost:9610
export CLIENT_DRONE_RPC_SECRET=REDACTED
export DRONE_LOG_FILE=.drone-exec-runner/log.txt
export DRONE_RUNNER_CAPACITY=4
```

Then I can run `drone-runner-exec` without arguments, but of course it is not running in the background.

**Comment by NiklasRosenstein** [comment]
I'm using `drone-exec-runner` from today pulled from `https://github.com/drone-runners/drone-runner-exec/releases/latest/download/drone_runner_exec_linux_amd64.tar.gz `. Couldn't find an option to display the version number in the CLI.

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
