### ISSUE TITLE
Does Drone's Postgres client library support scram-sha-256?

### ISSUE THREAD

**Issue by loganmarchione** [drone/drone#2922]
I setup Drone successfully on Docker using the built-in SQLite database.

I then tried to setup Drone again (deleting all old volumes), but changed the database to use Postgres. Nothing else changed except the database connection.

When starting the Drone docker container, I get this in the logs over and over.
```
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:04:47Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:05:19Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:05:50Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:06:22Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:06:54Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:07:26Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:07:57Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:08:29Z"},
{"error":"pq: unknown authentication response: 10","level":"fatal","msg":"main: cannot initialize server","time":"2020-02-18T14:09:01Z"},
```

A quick Google shows this is due to my use of [scram-sha-256 in Postgres](https://www.postgresql.org/docs/11/auth-password.html) instead of MD5. I can confirm this because when I switched my Drone database user in Postgres to MD5, Drone started without issue.

I see that you're using [pq](https://github.com/lib/pq), and it looks like pq added support for scram-sha-256 in [v1.1.0](https://github.com/lib/pq/releases/tag/v1.1.0). I don't know anything about the Go language, but does [this file](https://github.com/drone/drone/blob/ad6be2073b8f8bd935a4dda9aaf9a449f3d2d000/go.mod) mean you're using v1.0.0? If so, can you update to v.1.1.0?

**Comment by tboerger** [comment]
That's right, drone is still using 1.0.0, and you found the right file where it's defined.

If somebody provides a pull request I'm sure we can merge that.

**Comment by loganmarchione** [comment]
@tboerger I literally know nothing about Go. I can provide a PR with that single file updated, but I don't know how to build Drone and make sure everything works after that...

**Comment by tboerger** [comment]
Looks like you got it, cool. Thanks for the pr!
