### ISSUE TITLE
[bug] executed scheduled task,don`t have default avatar image src

### ISSUE THREAD

**Issue by everhopingandwaiting** [drone/drone#2925]
![image](https://user-images.githubusercontent.com/6021724/75104280-44c7da80-5642-11ea-9273-e8dfd936519f.png)
![image](https://user-images.githubusercontent.com/6021724/75104282-54dfba00-5642-11ea-9ea1-e6c6bd06f855.png)

**Comment by ashwilliams1** [comment]
This was previously fixed by https://github.com/drone/go-scm/commit/721d5294d5c5a02680cf4694e6e6dc5199dc5be0, please update your Drone instance.

**Comment by everhopingandwaiting** [comment]
drone images: 

```
drone/drone                 latest              c4eb12ecb552        4 days ago          67.6MB

```

**Comment by mritd** [comment]
same issue on 1.10.1 @ashwilliams1 
![image](https://user-images.githubusercontent.com/13043245/105123916-f81ba680-5b13-11eb-98ca-1f2c6450fbd6.png)
