### ISSUE TITLE
Disabled repository still run cron jobs

### ISSUE THREAD

**Issue by ogarcia** [drone/drone#2931]
If you configure a cron job in a repository and next you disable it, the cron job still runs.

Steps to reproduce:
1. Enable a repository
2. Make the first build
3. Enable an hourly cron job
4. Disable repository
5. Wait for next cron schedule
6. Voila! cron execute the job

I think that if a repository is disabled, Drone should be disable cron jobs too.

**Comment by bradrydzewski** [comment]
fixed by 32f286e1ed5ecce82ebc8fbbca292e086227329e
