### ISSUE TITLE
error="linter: untrusted repositories cannot mount host volumes"

### ISSUE THREAD

**Issue by huangmeng4520** [drone/drone#2932]
---
kind: pipeline
name: litemall

steps:
- name: build
  image: buildtools:v1
  volumes:
  - name: mavnrepo
    path: /home/tmp
  commands:
  - cd litemall-manage
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn clean package
volumes:
- name: mavnrepo
  host:
    path: /var/lib/drone/tmp

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
