### ISSUE TITLE
No logs or steps show on UI

### ISSUE THREAD

**Issue by wdongyu** [drone/drone#2942]
No logs and steps details

![image](https://user-images.githubusercontent.com/23725216/76844415-3737f600-6878-11ea-957f-77d4f2d24d76.png)

The Chrome console shows the following error: **invalid step argument. loadLogsForStep skipped**

I'm running Drone 1.6.5 on Kubernetes 1.15.5 bare metal, using kubernetes pipeline(drone/drone-runner-kube:latest)

Any suggestion or workaround?

**Comment by tboerger** [comment]
Please stop double-posting issues. You already opened https://github.com/drone/drone-ui/issues/327 3 days ago!
