### ISSUE TITLE
 drone orgsecret rm  404

### ISSUE THREAD

**Issue by dwdcth** [drone/drone#2943]
I use `drone orgsecret add daocloud.io docker_password  my_password` successfully.
But when rm orgsecret, it said 404.

![image](https://user-images.githubusercontent.com/1883728/77022090-a1a97d00-69c3-11ea-9298-a22a07e3a29b.png)

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
