### ISSUE TITLE
Windows exec runner

### ISSUE THREAD

**Issue by betim** [drone/drone#2947]
Hi,

I'm getting `Host key verification failed.` when trying to clone a repository through ssh protocol. In cmd and PS it clones it without any problem. 

First I thought maybe it's the user, and I went and changed it on Computer Management -> Services -> drone-runner-exec to be run as local user not `SYSTEM` user. Same thing. 

Then I went and ran drone-runner-exec.exe (btw it does not have `.exe` at the end when one downloads it) directly on cmd.exe; but same thing. Interestingly runner gives `msg="cannot accept stage" error="Optimistic Lock Error"` and on server output is: `Host key verification failed.` from git command.

Please help,
Regards

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
