### ISSUE TITLE
Active Gogs Repo Failed,  github.com/drone/drone/service/hook.deleteHook

### ISSUE THREAD

**Issue by LGinC** [drone/drone#2952]
There is a bug when I Active gogs repo.
![image](https://user-images.githubusercontent.com/15363011/79181058-14c8d680-7e3e-11ea-88e9-735781d0193e.png)

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
