### ISSUE TITLE
Why drone steps build so slow

### ISSUE THREAD

**Issue by readthecodes** [drone/drone#2953]
i run drone/drone:1 & drone-runner-docker:1 in a centos7, and use alpine as pipeline image, the command is only echo hello world, I am very confuse why it cost 22 seconds. docker version is 19.03.8, Storage Driver: overlay2. I have provide all my env info in https://discourse.drone.io/t/why-drone-steps-build-so-slow/7137, but they block my post automatically.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
