### ISSUE TITLE
drone exec --include more than one step does not work

### ISSUE THREAD

**Issue by cyberb** [drone/drone#2961]
Trying to run multiple steps and exec does not do anything while single individual steps are fine.

```
drone exec --include=build,test
```

**Comment by firefixmaarten** [comment]
does `drone exec --include build --include test` work ?

**Comment by cyberb** [comment]
That works, sorry.
Was it always like this?

**Comment by firefixmaarten** [comment]
No problem,
Not sure, only start using it recently and cannot answer that question.
