### ISSUE TITLE
oauth: cannot exchange code

### ISSUE THREAD

**Issue by AmengSong** [drone/drone#2969]
drone: Gitea

ERRO[0087] oauth: cannot exchange code: xH8HnmCk5D__3dEmVT70bxXBqlqdrDB-DQJhxMm0W0Q=: unauthorized_client: client is not authorized 
DEBU[0087] cannot authenticate user: unauthorized_client: client is not authorized

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
