### ISSUE TITLE
Ability to trigger upstream tests

### ISSUE THREAD

**Issue by rgarcia** [drone/drone#297]
We have many repos that have upstream dependencies, e.g. an ORM library that many different applications depend on. It'd be great to be able to trigger tests in upstream dependencies upon completion of testing a repo.

Sidenote: I think it might be possible to hack this with a bash deploy hook that hits the drone webhook endpoint, but it'd have to recreate the last payload somehow...

**Comment by bradrydzewski** [comment]
I wanted to add some comments here from another thread:

---

I'm thinking the first step is to create a Drone plugin for Drone. The plugin could trigger builds for other repositories using the Drone API. We already have an API library available, which should make this pretty easy to create.

```
notify:
  drone_trigger:
    repos:
      - octocat/Hello-World
      - octocat/Spoon-Knife
    token: $$DRONE_TOKEN
```

While a plugin may be less ideal than a build-in solution, I think it is a great starting point for us to spec out the behavior and get something working as soon as possible. A built-in solution will take time and isn't currently a priority with everything else going on, however, the plugin can be created today without any code changes to Drone whatsoever. Plugin are pretty simple to create if anyone is interested in giving it a try.

**Comment by RomanSaveljev** [comment]
Would it be simply better to allow for triggering a downstream from a command run by drone-exec? One particularly hard usecase we had to implement with Jenkins (also triggers from post-build actions) was to support gerrit review verification step. Compilation happened in one environment and simple smoke testing in another. We had to resort to various inconveniences to transmit artifacts and synchronize them.

**Comment by bradrydzewski** [comment]
@RomanSaveljev a plugin is the recommended way to move forward. Before anything is built directly into Drone it should be a plugin first. This gives us a chance to test out different options and behavior without impacting the core Drone codebase.

> Compilation happened in one environment and simple smoke testing in another

I believe this will be solved by parallel builds. Parallel builds will behave differently than matrix builds because they will run on the same machine and have access to the same `/drone` volume.

> Would it be simply better to allow for triggering a downstream from a command run by drone-exec

If we did build this functionality into Drone I'm not sure drone-exec is the right place because we enforce a strict rule that drone-exec only sends information back to Drone via stdout and the exit code. This is because we can't necessarily count on inter-container communication.

While the inter-container communication limitation would also exist within a plugin, I believe it is acceptable to have a plugin with system-level or configuration requirements. For example, the `drone-docker` plugin requires `aufs` or `overlay` but that restriction isn't placed on Drone itself.

**Comment by RomanSaveljev** [comment]
Okay, thanks for the feedback. I am afraid I did not made myself clear. Sorry for that. Our scenario looked like this:

* Trigger a job from Jenkins gerrit plugin
* Compile the artifacts
* Transfer artifacts to another testing job, which runs in a different slave
* Compilation job waits for the verdict from the testing job
* Compilation job publishes the status for the "Verified" field in the review

Now as I think of it, perhaps something like [this](https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin) renowned Jenkins plugin would solve it gracefully.

I hope proposed parallel builds will be able to handle this kind of setting.

Anyways, apart from being flawed Jenkins has had quite some back and forth, so we need not copy it, but we can learn from it.

**Comment by bradrydzewski** [comment]
@RomanSaveljev thanks for the clarification. Hopefully parallel builds will handle this sort of thing. Once an initial implementation is available I'll let you know. Would love to get your feedback

**Comment by bradrydzewski** [comment]
since the plugin is pretty basic, I have something that is almost ready for testing:
https://github.com/drone-plugins/drone-downstream

it isn't published to the registry yet, but if anyone wants to build and test locally feel free

**Comment by bradrydzewski** [comment]
OK, here it is .... the first plugin for Drone for Drone ...
http://addons.drone.io/trigger/

This plugin will trigger builds for downstream dependencies. You can specify a list of repositories in your yaml, including your Drone token, and you should be good to go. The repository name should be in `owner/name` or `owner/name@branch` format.

The plugin will re-run the latest build for the default or specific branch. It will not create a new build entry. It also needs the ability to communicate the with Drone API. If you are running Drone on localhost or running Drone in a container with icc disabled you might hit some issues.

**Comment by vtolstov** [comment]
Nice! Does it possible to skip token when triggering own repos/jobs ?
29 окт. 2015 г. 2:38 пользователь "Brad Rydzewski" <notifications@github.com>
написал:
