### ISSUE TITLE
cannot get secret if my k8s runner is not deployed in the specific namespace other than 'default'

### ISSUE THREAD

**Issue by he1016060110** [drone/drone#2974]
I deploy k8s not in the namespace 'default', how can i configure secrets to get the secrets.

the command i use is :
```
drone plugins secret get --repo infrastructure/queue docker-key username
```

the output is:
```
kubernetes api: Failure 403 secrets "docker-key" is forbidden: User "system:serviceaccount:cicd:default" cannot get resource "secrets" in API group "" in the namespace "default"
```

**Comment by he1016060110** [comment]
i deploy both server and runner in the k8s, and the namespace is cicd

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
