### ISSUE TITLE
My service is on the internal network, and the webhook of GitHub cannot be recalled. What should I do

### ISSUE THREAD

**Issue by kakj-go** [drone/drone#2976]

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

**Comment by kakj-go** [comment]
OK, then I found that I can trigger the build manually with API
