### ISSUE TITLE
No completed webhook sent

### ISSUE THREAD

**Issue by andrasbacsai** [drone/drone#2977]
Based on the [docs](https://docs.drone.io/webhooks/examples/#completed) there should be a webhook with a completed action.

Saw [this](https://github.com/drone/drone/pull/2923) PR about implementing it.

Am I missing something, or it is really not implemented correctly?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).

BEside that, you already linked an unmerged PR, so how should that be already working if it's missing some functionality?
