### ISSUE TITLE
/bin/sh: can't open '/usr/local/bin/clone'

### ISSUE THREAD

**Issue by IGabor98** [drone/drone#2980]
Hi! I can not clone repository. I get this error /bin/sh: can't open '/usr/local/bin/clone'
![image](https://user-images.githubusercontent.com/25786922/84363015-c84c0e00-abd6-11ea-8b20-ed1d1596d273.png)

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io). Also please provide additional information, including your version of Drone and your full server and runner configurations.
