### ISSUE TITLE
Discussion of usage scenarios of drone CD

### ISSUE THREAD

**Issue by qixiang-liu** [drone/drone#2988]
Wanted a drone to focus on the CD part of the assembly line. I hope to discuss it with the big boys.

How do you use drone to specify a mirrored library instead of a code base, or use API calls to implement the continuous deployment phase ?

**Comment by qixiang-liu** [comment]
I hope someone can discuss it

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support and usage questions please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
