### ISSUE TITLE
Is Drone for Kubernetes Production Ready?

### ISSUE THREAD

**Issue by hardy4yooz** [drone/drone#2995]
Kubernetes runner released for a long time. When can it be used in a production environment?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support and general questions please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
