### ISSUE TITLE
Error in image bradrydzewski/php:5.*

### ISSUE THREAD

**Issue by kimausloos** [drone/drone#3]
In /etc/drone.d/phpenv.sh you add home variable '/home/ubuntu/phpenv/bin'. I think that should be '/home/ubuntu/.phpenv/bin' (note the . in phpenv), as I'm always getting the following error:

/etc/drone.d/phpenv.sh: line 21: phpenv: command not found

**Comment by toby-griffiths** [comment]
I'm still having this issue.   Anyone able to update the images?

**Comment by bradrydzewski** [comment]
closing because all images in `github.com/drone/drone-images/*` are being deprecated in favor of the official docker language stacks
