### ISSUE TITLE
Build Create Api, not working

### ISSUE THREAD

**Issue by clanaid** [drone/drone#3003]
I called Build Create APi
```bash
POST /api/repos/{namespace}/{name}/builds
```
But it not working, retrun
```json
{"message":"Not Found"}
```

However, I call Restart Api and it works normally
Is the way I called it wrong?

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support and general questions please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
