### ISSUE TITLE
Drone images are not official on Docker Hub, restrictions will be applied on 2021

### ISSUE THREAD

**Issue by akhenakh** [drone/drone#3014]
On January 2021 Docker is changing the TOS of Docker hub, it will impact Drone and its plugins https://hub.docker.com/pricing

Anonymous users will be allowed 100 pulls per 6 hours.

Official images are exempted, make Drone and plugins officials.

**Comment by bradrydzewski** [comment]
we are paying customers of DockerHub.  According to the pricing matrix, the data transfer limits for anonymous users are not applicable to images owned by paid plans.

<img width="703" alt="Screen Shot 2020-08-26 at 5 03 18 PM" src="https://user-images.githubusercontent.com/817538/91356691-13c98d80-e7be-11ea-851b-0a93825b10aa.png">

**Comment by akhenakh** [comment]
Not sure how to read this matrix, the 100 pulls apply to who is fetching the image, drone users are anonymous users in regards of Docker Hub ?

**Comment by tboerger** [comment]
the 100/200 pulls are related to free plan, the right column is the paid plan.

**Comment by bradrydzewski** [comment]
100 anonymous pulls per 6 hours per IP address.  I would expect the Drone server image to be pulled once per IP address when the software is initially installed.  I do not think this will negatively impact most users trying to download the Drone image.

In general, I think this will impact teams that are pulling large numbers of images anonymously. The Docker team recognizes and addresses this in the _What about CI systems where pulls will be anonymous?_ section of their FAQ [1].  However, making the Drone image an official image would not solve this larger problem.

If teams begin hitting anonymous download limits, they can provide their Drone runner with authentication credentials [2] which, depending on their account type, would increase or eliminate any download limits. 

[1] https://www.docker.com/pricing/resource-consumption-updates
[2] https://docs.drone.io/runner/docker/configuration/reference/drone-docker-config/

**Comment by xoxys** [comment]
Maybe consider publishing to quay.io as well? They also have a free plan and users could choose which registry to use and have a fallback in case one registry is down/has issues.

**Comment by bradrydzewski** [comment]
https://discourse.drone.io/t/how-to-prevent-dockerhub-pull-rate-limit-errors/8324
