### ISSUE TITLE
Secrets can be deleted and created by non admins

### ISSUE THREAD

**Issue by jlehtimaki** [drone/drone#3015]
Hello,

So currently Drone allows secrets to be created and deleted by nonadmins to project.
This is a security risk in my opinion where a malicious developer can inject some false secrets to the project and then deploy.

I've created a PR to fix the issue. Currently, this is a big issue with one of my customer's teams where they require more RBAC like of control of their project.

**Comment by bradrydzewski** [comment]
Drone _only_ allows individuals with _write_ or _admin_ access to the repository to manage secrets.  Years ago we required _admin_ access to manage secrets, however, we changed this to _write_ access after countless requests.  

The current behavior is desirable for many organizations because it strikes an adequate balance between security and making Drone self-service for their employees. If your organization has special security requirements we would recommend using a secret extension such as vault which will give you more control over access and management. See https://docs.drone.io/extensions/secret/

**Comment by jlehtimaki** [comment]
Thanks for the explanation @bradrydzewski !
Well, then there is a bug of some sorts since we have tested and *everyone* has rights to add/delete secrets from *all* repositories. Also we have noticed that we can disable other repositories but we *cannot* activate them, which is also weird.
We are using BB server.

Is the check made here: https://github.com/drone/drone/blob/66a8057001e15c26af3a0d6cd84261289065224b/handler/api/acl/org.go#L32

**Comment by bradrydzewski** [comment]
If you are a Drone [system admin](https://docs.drone.io/server/user/admin/) you have full access to all repositories.  I ran a quick test and I was unable to reproduce.

The relevant code can be found here:
https://github.com/drone/drone/blob/master/handler/api/acl/check.go

And the relevant unit tests can be found here:
https://github.com/drone/drone/blob/master/handler/api/acl/check_test.go#L342:L471

**Comment by tboerger** [comment]
I also can't reproduce this issue. Can you please clarify what exactly you are doing and also make sure that the user that shouldn't be allowed to create secrets is not part of the Drone admins?

**Comment by jlehtimaki** [comment]
So we are not using the cloud version, we are using our own.
Turned the debug log on and found that somehow our users have *write* permission to all repositories apparently, according to Drone: 
`{"admin":false,"level":"debug","msg":"api: access granted","name":"toivo","namespace":"VTJ","read":true,"request-id":"1ggcNM0i78dRHCew34hTsKKUK9w","time":"2020-08-27T14:47:14Z","user.login":"joonas.lehtimaki_polarsquad.com","visibility":"private","write":true}
{"admin":false,"level":"debug","msg":"api: access granted","name":"toivo","namespace":"VTJ","read":true,"request-id":"1ggcNM0i78dRHCew34hTsKKUK9w","time":"2020-08-27T14:47:14Z","user.login":"joonas.lehtimaki_polarsquad.com","visibility":"private","write":true}
{"fields.time":"2020-08-27T14:47:14Z","latency":273089834,"level":"debug","method":"DELETE","msg":"","remote":"10.0.4.152:23232","request":"/api/repos/VTJ/toivo/secrets/test-secret","request-id":"1ggcNM0i78dRHCew34hTsKKUK9w","time":"2020-08-27T14:47:14Z"}
`
Even though we cannot commit to that repository in BitBucket.

**Comment by wolverian** [comment]
I work with @jlehtimaki. One additional point of data is that we use BitBucket Server (not Cloud) as the source code repository.

**Comment by bradrydzewski** [comment]
The cloud version and the self-hosted version use the same underlying source code.  The only difference is that we are using GitHub and you are using Bitbucket Server as your source control management system.  To determine whether or not a user has write access in Bitbucket Server, we use the following API call:

```text
rest/api/1.0/repos?size=1000&permission=REPO_WRITE&project=%s&name=%s
```

I recommend taking a look at the underlying source code and unit tests:
https://github.com/drone/go-scm/blob/master/scm/driver/stash/repo.go#L118:L156
https://github.com/drone/go-scm/blob/master/scm/driver/stash/repo_test.go#L64-L186
