### ISSUE TITLE
Gitlab Groups/SubGroups Roadmap

### ISSUE THREAD

**Issue by danilorsilva** [drone/drone#3019]
Hello all, 

     Just a simple question, is there a roadmap to solve the problem with groups/subgroups when using gitlab?

Thanks!

**Comment by tboerger** [comment]
See https://github.com/drone/drone/issues/2009#issuecomment-295686484

**Comment by danilorsilva** [comment]
@tboerger nothing changes since 2017?

**Comment by tboerger** [comment]
Nobody really focused on that, I started to do something into that direction but it's far away from being done at all.
