### ISSUE TITLE
Not dependant pipelines are skipped, when any pipeline fails before they are started, even when dependant pipelines are OK

### ISSUE THREAD

**Issue by philippthiele** [drone/drone#3034]
Hello,
I have the following situation:
![image](https://user-images.githubusercontent.com/1737722/97972322-a2f9af80-1dc4-11eb-842b-c9282a064bef.png)
Here the pipelines, test1, test2 and test3 "[depends_on](https://docs.drone.io/pipeline/configuration/)" build.
- release1 depends_on test1
- release2 depends_on test2
- release3 depends_on test3

But release2 has no dependance on test1. When test1 fails before test2 is finished, release2 is skipped. When test1 fails after test2 is successful, release2 will be executed.

I think it should always execute release2 when test2 is successful, regardless of the other pipelines release2 has no dependance on, or what do you think?

Thank you and best regards,
Philipp

**Comment by bradrydzewski** [comment]
If the build is in a failure state, subsequent pipelines are skipped unless they are configured to run on failure. If a pipeline has not started yet due to lack of capacity, and the overall build is in a failure state by the time it starts, it is skipped. So this is the expected behavior.
