### ISSUE TITLE
plugins/docker  How do you configure global host and let clone specify IP or domain name on the Intranet、The same cloud service bandwidth is very small Clone

### ISSUE THREAD

**Issue by mj520** [drone/drone#3035]
plugins/docker  How do you configure global host and let clone specify IP or domain name on the Intranet、The same cloud service bandwidth is very small Clone

**Comment by tboerger** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
