### ISSUE TITLE
Drone server 0.10.0 was not versioned properly

### ISSUE THREAD

**Issue by akhenakh** [drone/drone#3043]
See https://github.com/drone/drone/blob/v1.10.0/version/version.go

**Comment by tboerger** [comment]
But that's nothing we can properly change, the tag have been created and I don't think it will get overwritten.

**Comment by akhenakh** [comment]
Sure but let everyone know, I've spent time figuring out why it was not properly deployed, it was deployed ... 😁

**Comment by bradrydzewski** [comment]
fixed in 1.10.1
