### ISSUE TITLE
My project needs to use vs2019 to compile my c++ program, how do I edit the yml file? 

### ISSUE THREAD

**Issue by cjl3230** [drone/drone#3066]
My project was developed using vs2019, using the C++ language, but I found a lot of information about drone, but I didn't see how to use drone to continuously integrate and deploy my project. Mainly the preparation of the yml of the project

**Comment by ashwilliams1** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
