### ISSUE TITLE
Plugin for Perceptual Diffing

### ISSUE THREAD

**Issue by caffinatedmonkey** [drone/drone#317]
It would be cool if drone.io had perceptual diffing support. Perceptual diffing is the act of diffing two rendered user interfaces to check if there are any differences that shouldn't be there. Here are some resources:

* <http://mattjibson.com/blog/2013/06/11/perceptual-diffs-at-stack-overflow/>
* <https://github.com/bslatkin/dpxdt>

**Comment by bradrydzewski** [comment]
I'm going to close this in favor of pushing this behavior to a plugin and external system, similar to [what we've done with coverage](https://github.com/drone-plugins/drone-coverage). This should be much easier now that Drone supports a rich plugin model.
