### ISSUE TITLE
Google Play Store Publish Plugin

### ISSUE THREAD

**Issue by caffinatedmonkey** [drone/drone#332]
Drone's goal is to replace Jenkins. Android :heart: Jenkins

- [ ] add an android image to `drone/images`
- (n/a) add deployment to play store
- [ ] add deployment to TestFlight

**Comment by bradrydzewski** [comment]
closing this now that plugins are all externalized and (mostly) community contributed. I encourage anyone that stumbles upon this issue to consider creating and publishing such a plugin if one does not already exist.
