### ISSUE TITLE
Cancel the build of a commit.

### ISSUE THREAD

**Issue by kenberland** [drone/drone#336]
Oftentimes it becomes clear very early in the life of a build that it will not succeed.  In these cases, canceling the build conserves scarce resources and allows other builds to proceed.  In short, Drone, like most things, needs a `CANCEL` button.

**Comment by jarthod** [comment]
:+1: That would help a lot for when a build fails, stays stuck or simply to cancel some builds when a newer version is running.

**Comment by nel** [comment]
Is it still expected for v0.3 ?

With the multi build support the lack of "stop build" button is even more important as :
- Drone UI don't display the slave the build is executed on
- There is no way from the docker slave itself to actually tell what is the host server and display it during the build (and drone does not pass the info as an env variable e.g,)

This means that finding the server where the build is currently stuck is crazy complicated in multi-slave mode. Therefore manual kill though docker kill or equivalent is not a viable option.

My 2 cents :)

**Comment by Intrepidd** [comment]
:+1:

**Comment by keysen** [comment]
:+1:, YKWIM

**Comment by os12** [comment]
BTW, here is another usecase related to this Cancel request:
  * we run builds and test suites under Drone
  * the tests hang polling for data/events when a bug is introduced
  * it would be very useful to terminate an active build in such cases

BTW, what happens now in such cases? Is there an internal timeout?

**Comment by nel** [comment]
@os12  There is an internal timeout that you can set. 

But this will still waste lots of time because you will have to wait for the full timeout. The timeout will have to be longer than the minimum time required for your build when you CI servers is busy (otherwise timeout will kill working build).

So there is this solution for blocked builds but this is a bit frustrating to watch your build blocked.

**Comment by os12** [comment]
So, it sounds like the queuing time is bundled with the building time. 
The former has nothing to do with the individual build though...

Also, the manually set timeouts are a maintenance burden - the code 
grows, tests are added...

**Comment by bradrydzewski** [comment]
This is a work in progress. There are pre-requisites to this task that we are addressing.

**Comment by bradrydzewski** [comment]
cancel for non-matrix builds added to 0.4 ... cancel to matrix build will be pushed to 0.4.1

**Comment by bradrydzewski** [comment]
update: this behavior was changed to cancel a single job. If you are running a matrix (which has multiple jobs) you would need to cancel each job individually. I'm not sure if people want to cancel the entire matrix at once, or just a single job. We'll launch 0.4 as-is and see what sort of feedback we get
