### ISSUE TITLE
Run Docker with Custom Options

### ISSUE THREAD

**Issue by 907th** [drone/drone#363]
I broke my brain trying to understand why my custom image is running under `root` instead of `ubuntu` user. [The issue](https://github.com/drone/images/issues/32). Finally I found that Drone uses `root` [for all images](https://github.com/drone/drone/blob/678e4ddea76a47004cc30139f3c2467c049198b3/pkg/build/build.go#L397) except for`bradrydzewski`'s ones. :astonished:

I think Drone should allow to specify a custom user for build in `.drone.yml`

**Comment by bradrydzewski** [comment]
we've added the `docker` section to the yaml and many customization options. We are altering the Drone build process to use the default `USER` assigned to the image. We are tracking this change in #749 so I'm going to close this issue.

**Comment by 907th** [comment]
@bradrydzewski Thanks! Is new `docker` section documented anywhere? Can not find docs for it :(

**Comment by nardeas** [comment]
Still cannot find this anywhere in documentation. Any help here?
