### ISSUE TITLE
Drone status on Github doesn't show when build is pending

### ISSUE THREAD

**Issue by jonahkagan** [drone/drone#365]
If a build has status 'pending' on Drone, Github does not show any information about Drone status in the PR view: http://cl.ly/image/0Z2d26362X2x. When the build is running (status 'started'), it shows a message that the build is pending on Drone: http://cl.ly/image/1J2R1t173J0i. This message should be shown when the build is pending as well.

**Comment by bradrydzewski** [comment]
fixed in 0.4 branch (upcoming release)
