### ISSUE TITLE
Dynamic Plugin support for Remotes

### ISSUE THREAD

**Issue by pigmej** [drone/drone#381]
Rhodecode is full blown hg and git code hosting. It has hooks, user permissions api keys, I think all that's needed to support it in drone.

Also it has ssh clone/push support (https://code.rhodecode.com/rhodecode-ssh)

It's open source, you can run it self hosted (free to 20 users).

Would be cool to support it in drone.

**Comment by darrin-wortlehock** [comment]
Any movement on this?

**Comment by bradrydzewski** [comment]
In an effort to prevent feature creep, I am closing this as out-of-scope for the project.
