### ISSUE TITLE
PPA repository for install via APT

### ISSUE THREAD

**Issue by beefsack** [drone/drone#42]
Hello, looks great!

If you've already set up your .deb building from deb-src, could you please put it up in a PPA?  It would make installation much simpler, particularly for those of us who have our CI server configuration in puppet or chef scripts.

Cheers!
Michael

**Comment by bradrydzewski** [comment]
We now have Bintray integration which supports apt repositories. We should be able to publish the Drone .deb file to Bintray and take advantage of this feature. I'm on it.

**Comment by davidak** [comment]
Bintray looks good. how far is the work on the repo?

you should upload the pgp key to public keyservers that one can simply get it:

gpg --keyserver keyserver.ubuntu.com --send-keys 12345678

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 12345678

**Comment by wingrunr21** [comment]
@bradrydzewski did you finish setting this up? [Looks like](https://bintray.com/drone/drone/drone.deb) Bintray isn't aware of any files. Can you make it pull from S3 automatically or something?

**Comment by bradrydzewski** [comment]
drone is now being distributed as a Docker image
