### ISSUE TITLE
Provide HTTPs Download Link

### ISSUE THREAD

**Issue by benmccann** [drone/drone#424]
The docs say to get it from http://downloads.drone.io/latest/drone.deb

However, it's not secure to download software from http as it opens it up to man in the middle attacks giving you a malicious version of the package. Please make a version available from https :-)

**Comment by davidak** [comment]
so we need another ssl-certificate or a wildcard one.

also if you order one for www.drone.io at rapidssl, you get also drone.io. just for further buys.

you can get a free certificate at https://cert.startcom.org/?lang=en now or wait for https://letsencrypt.org/

**Comment by bradrydzewski** [comment]
with latest release drone is distributed via dockerhub exclusively, so this can be closed
