### ISSUE TITLE
Cache Docker images

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#43]
documenting suggestion from @afex on irc

add a section to the `.drone.yml` called setup

```
setup:
  - apt-get update
  - apt-get -y install libsqlite3 libsqlite3-dev
```

add these install scripts to the Dockerfile that we generate:
https://github.com/drone/drone/blob/master/pkg/build/build.go#L365

```
RUN apt-get update
RUN apt-get -y install libsqlite3 libsqlite3-dev
```

this would allow us to take advantage of Docker's layer caching. The build would use the cached image and avoid re-running install and setup commands. Saves time! If build script commands changed the cache would be invalidated and a new image would be generated.

question: how does this impact matrix builds?

**Comment by Wqrld** [comment]
Why was this closed? Is this already implemented?
(huge bump, but i am unable to find anything about it in the new docs)

**Comment by bradrydzewski** [comment]
this was closed because caching was delegated to plugins, which give much more flexibility in terms of how and when files are cached. You can use an existing cache plugin or write your, but here is a list of cache plugins that people have registered: http://plugins.drone.io/tags/cache/
