### ISSUE TITLE
Reproducible builds using Gitian LXC containers

### ISSUE THREAD

**Issue by JeremyRand** [drone/drone#431]
Reproducible builds using Gitian (the build system used by Bitcoin and Tor) would be really useful, a potential killer app which services like Travis-CI can't handle.  Reportedly Gitian is working within Docker.  Some more info is posted at https://github.com/devrandom/gitian-builder/issues/53 .  Could this be integrated with Drone?

**Comment by bradrydzewski** [comment]
this seems like a good use case for a community-contributed plugin: http://readme.drone.io/devs/plugins/

since this isnt' something we would build directly into drone I'm going to close the issue. But feel free to create a submit a plugin for Gitean to be listed in our plugin index
