### ISSUE TITLE
Document private parameters & injection strategies

### ISSUE THREAD

**Issue by thenewguy** [drone/drone#438]
Build progress output shows the command that is run after params are injected.

Granted, I understand that if someone had access to your account or you left the page up and walked away from your desk a malicious person could click and view the list of params.  I am talking more from the perspective when someone walks up to my desk I don't have to minimize the build status and worry they read the output and are going to cause mischief.

I think it would be a good idea not to show this information.  I am not familiar with Go, so I am not sure where this expansion happens in the code and how difficult it would be to show the command with {{vars}} before they are expanded.

A quick/simple option would be to also make the params available as environment variables.  Then a command can be written like
```
foo --branch-name=$DRONE_BRANCH --param1=$SAFENAMESPACE_PARAM1
```
and the param is not displayed while following build progress.

Versus something like
```
foo --branch-name=$DRONE_BRANCH --param1={{PARAM1}}
```
which displays
```
foo --branch-name=$DRONE_BRANCH --param1="ALL-YOUR-BASE-ARE-BELONG-TO-US"
```

**Comment by bradrydzewski** [comment]
added docs to https://github.com/drone/drone/blob/0.4.0/doc/build/env.md
