### ISSUE TITLE
GitHub Release Plugin

### ISSUE THREAD

**Issue by rgarcia** [drone/drone#439]
We've started to do more and more publishing of (mostly Go binaries) via Github releases.

Right now the process is `make release` to put a bunch of release artifacts in a folder (e.g. `release/`) and then run a script that creates a Github release and uploads the contents of this directory.

I think we could turn this into a fairly generic drone publish plugin. Configuration options:
* `script`: list of commands (or a single command?) to run to build a release
* `dir`: directory to find release artifacts after script is run
* `token`: Github token to use to interact with the Releases API.
* `version_file`: defaults to VERSION at the root of the repository
* `branch`: restrict to this branch

Example: if we were etcd and we wanted to produce their releases (https://github.com/coreos/etcd/releases) the config would look like:
```
publish:
  github:
    script: scripts/build_release
    dir: release
```

Thoughts?

**Comment by bradrydzewski** [comment]
github release plugin recently added by @tboerger http://addons.drone.io/github_release/
