### ISSUE TITLE
Relative url path

### ISSUE THREAD

**Issue by xeor** [drone/drone#475]
I can't find anything in the documentation, nor the sourcecode about a way to put drone.io under example example.com/ci/, instead of using a whole dedicated domain. It looks like all the links in the html template files uses hardlinking, so I guess this is not currently possible.

Is there a plan to implement a more dynamic base url? Its important for many projects.

**Comment by vlkosinov** [comment]
Agree, it is very important feature

**Comment by cboettig** [comment]
Yup, this would definitely be most helpful, thanks for considering.

**Comment by cboettig** [comment]
Hmm, this almost works as is with the following Caddyfile:

```
example.com
  proxy /drone localhost:8000 {
    without /drone
    proxy_header X-Forwarded-Proto {scheme}
    proxy_header X-Forwarded-For {host}/drone
    proxy_header Host {host}/drone
  }
  redir /drone /drone/ 307
}
```

The only problem appears to be that the CSS file isn't found, so all the content is there but just not looking pretty.  This happens just because the css paths start with root, e.g. `/path/to/css` instead of `path/to/css`.  Ideally this would be a config option to set some base, but it seems just using relative urls would work to.  I'm sure I'm not really appreciating the details, but does seem like a potentially straight-forward adjustment to make(?)

**Comment by tboerger** [comment]
@cboettig as you can see at https://github.com/drone/drone/pull/1238 it's not that easy and needs separate automated testing to prevent somebody from breaking it

**Comment by carldanley** [comment]
:+1: for this idea! Would be so awesome :)

**Comment by DaAwesomeP** [comment]
+1 I got part of it to work with an Nginx proxy, but Drone doesn't know, so it redirects to `/login` instead of `/drone/login`.
```nginx
location /drone/ {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header Origin "";

    proxy_pass http://127.0.0.1:8000/;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_buffering off;

    chunked_transfer_encoding off;
}
```

**Comment by tboerger** [comment]
> A subdomain just isn't an option for me right now.

Currently there is simply no other option than subdomains, sorry.

**Comment by barracks510** [comment]
It shouldn't be incredibly difficult to mirror an approach similar to Gogs's. Doesn't add much to the code base, from a cursory glance.

**Comment by timka** [comment]
I suggest configuring nginx to listen on another port on the same host:
```
server {
    listen 8443;
    server_name ripbana.carouselsms.com;

**Comment by strk** [comment]
I'm also looking for this, it would help setups with less control over DNS

**Comment by XuryaX** [comment]
I have been trying to achieve this using manipulation caddyfile.
Works good partially,
If I go to 

`https://abc.mojojo.com/drone/abcd/` it  gives me repo  not available and i can navigate from there.
But if I go to `https://abc.mojojo.com/drone/` it doesn't show me anything. The HTML is almost same, the static files are loaded. Can you tell me why this might happen?

```
https://abc.mojojo.com {
    proxy /drone/ http://127.0.0.1:8000 {
        transparent
        websocket
        without /drone/
        header_upstream X-Forwarded-Proto {scheme}
        header_upstream X-Forwarded-For {host}/drone
        header_upstream Host {host}/drone
    }

    rewrite /static {
        r (.*)
        to /drone/static/{1}
    }
    rewrite /api {
        r (.*)
        to /drone/api/{1}
    }
    rewrite /ws {
        r (.*)
        to /drone/ws/{1}
     }
    rewrite /login {
        to /drone/login
     
    rewrite /authorize {
        to /drone/authorize
     }

    redir /drone /drone/
    errors stdout
    log stdout
}
```

**Comment by bradrydzewski** [comment]
closing due to age, no plans to implement
