### ISSUE TITLE
A way to change the text that appears in Pull Requests

### ISSUE THREAD

**Issue by TheNeikos** [drone/drone#482]
When a build fails/succeeds there is a small piece of text that appears next to *All is well*:

![image](https://cloud.githubusercontent.com/assets/1631166/4389512/d01faf46-43f5-11e4-9167-c8bb284d8599.png)

It could be great if one could change it to custom text or to the domain where it has actually build. 

If you want to have the name drone appear in it (which is perfectly acceptable in my opinion) it could also be something like: *build with drone on <ci.server.hostname>".

PS: This is really an awesome tool!

**Comment by bradrydzewski** [comment]
let's track under issue #312
