### ISSUE TITLE
re-activate repo via UI

### ISSUE THREAD

**Issue by brettlangdon** [drone/drone#523]
I have had issues before where I wanted to remove/re-activate a repo in order to fix an issue with the deploy key or web hook, but there doesn't seem to be a good way of doing that, so I have just been removing the `drone.sqlite` file and starting fresh.

Would be nice to have a button to re-add webhook and deploy key for a repo, or to even "deactivate" a repo.

**Comment by mattbostock** [comment]
I've raised a separate issue to clarify the distinction between the CLI and web admin interface: #806

**Comment by nils-werner** [comment]
+1 UI button. I don't want to give people access to the shell just to clean up their stuff...

**Comment by bradrydzewski** [comment]
as an aside, you wouldn't need to give people access to the shell. The command line utility is already available to anyone with a Drone account. They just need to download the command line utility on their laptop and provide with their personal API token:
http://readme.drone.io/api/authentication/#from-the-command-line:6b57b661b9236f856cd4f0afa1bed671

**Comment by nils-werner** [comment]
Ah, right I forgot. Still, I wouldn't want to force people to install drone on their machine to do that

**Comment by hiroshi** [comment]
I tried re-activate via API, but it failed.
https://github.com/drone/drone/issues/1109#issuecomment-231722966

drone CLI doesn't seem to have `enable|disable` anymore....

Are there other ways to re-activate (create github webhook) a repo?

**Comment by hiroshi** [comment]
FYI: https://discuss.drone.io/t/repair-deleted-webhook/175

**Comment by bradrydzewski** [comment]
fixed in 0.8-rc.1
