### ISSUE TITLE
Changing pwd in `script` breaks `deploy`

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#562]
For example a `.drone.yml` file like

    image: base
    script: 
        - cd proj
        - make

    deploy:
      ssh:
        target: machine
        artifacts:
          - proj/a.out

will not successfully deploy `proj/a.out` as `deploy` is executed after `script` without changing back to the root dir and the `artifact` it would be looking for is `proj/proj/a.out`

    script: 
        - cd proj
        - make
        - cd ..

Fixes this.

I would expect all instructions to run with respect to the root directory: Changing dir in one does not affect any of the others.

**Comment by bradrydzewski** [comment]
fixed in 0.4 branch, which pushes all deploys to external docker plugins. Each plugin container is started with the workingdir set to the repository root
