### ISSUE TITLE
Enhanced Gitter Support

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#569]
Looks like we can establish deeper integration with Gitter by adding Drone as an official service:
https://github.com/gitterHQ/services

JavaScript isn't my forte so I'm hoping someone is willing to pitch in

**Comment by bradrydzewski** [comment]
I think the icons are from font awesome. See `fa-frown-o`, `fa-smile-o` and `fa-meh-o`

The material design icons are another great option. They have png files already generated for multiple sizes, resolutions, and colors which is an added bonus:
https://github.com/google/material-design-icons
http://google.github.io/material-design-icons/

Here are some examples:
* ![success](https://raw.githubusercontent.com/google/material-design-icons/master/social/1x_web/ic_mood_black_18dp.png)
* ![faliure](https://raw.githubusercontent.com/google/material-design-icons/master/content/1x_web/ic_block_black_18dp.png)
* ![faliure](https://raw.githubusercontent.com/google/material-design-icons/master/action/1x_web/ic_highlight_remove_black_18dp.png)
* ![success](https://raw.githubusercontent.com/google/material-design-icons/master/action/1x_web/ic_done_black_18dp.png)
* ![faliure](https://raw.githubusercontent.com/google/material-design-icons/master/content/1x_web/ic_clear_black_18dp.png)

**Comment by bradrydzewski** [comment]
I've also updated the docs to include a sample webhook output:
http://readme.drone.io/usage/notify/webhook/

Note that the `hostname` field will get added tomorrow. Without the hostname it would be impossible to construct a URL back to the commit in Drone. With the "hostname" field we can construct a URL like this:

```
{{ body.hostname }}/{{ body.repository.host }}/{{ body.repository.owner }}/{{.Repo.Name}}/{{ body.commit.branch }}/{{ body.commit.sha }}
```

... actually, as I'm typing this, I'm thinking we should just provide the entire resource URL in the webhook payload in place of the `hostname` field.

**Comment by blaggacao** [comment]
:+1: sounds good, what you're up to! @ciarand are you working on this?

**Comment by ciarand** [comment]
@blaggacao don't have the time I'm afraid, happy to let anyone else have a shot

**Comment by bradrydzewski** [comment]
fyi @daMupfel has been working on this. Looks like it will be ready soon!

**Comment by bradrydzewski** [comment]
![drone_16](https://cloud.githubusercontent.com/assets/817538/6123106/daf1e8b0-b0b2-11e4-9946-7f7414b77182.png)
![drone_32](https://cloud.githubusercontent.com/assets/817538/6123107/db033516-b0b2-11e4-8561-83117c91ef67.png)

**Comment by daMupfel** [comment]
The integration for gitter has been merged :+1:

**Comment by bradrydzewski** [comment]
I just updated the `.drone.yml` file and it works like a charm. Thanks!
