### ISSUE TITLE
Elevate user privs in UI or otherwise

### ISSUE THREAD

**Issue by solarfly73** [drone/drone#576]
Hi Brad, 

We just upgraded to the latest drone today.   Looking great!  I notice the Settings page is blank.  I'm trying to figure out how to give other users Drone admin privs in the UI (so they can see settings and user administration).  Is there a command-line method?

**Comment by bradrydzewski** [comment]
finished. added to UI and rest API in 0.4 branch

**Comment by motin** [comment]
Where is the 0.4 branch? I see only master, bolt and revert-751-pr1
I also don't see the relevant commit in https://github.com/drone/drone/commits/master

**Comment by alexanderadam** [comment]
@bradrydzewski I'm using gitea authentication but I can't see any UI for setting a user as an admin. It's 2019 so I guess your branch should be merged, right?
