### ISSUE TITLE
Document running Drone in Docker

### ISSUE THREAD

**Issue by cboettig** [drone/drone#580]
I notice you provide a Dockerfile that looks like it can be used to deploy the Drone CI system on my server, though I didn't see any documentation to that effect.  

I can build this Dockerfile successfully and run it using something like: 

```bash
docker run --name droned -d -p 80:80 -v ~/drone-config:/host -t drone/drone droned --config=/host/drone.toml
```

to link to a config file at my host.  This seems to work in that the container begins to execute and I can see the Drone welcome screen at my IP.  However, regardless of what I put in for credentials in the `drone.toml` (Gitlab URL, Github client/secret keys, `open=true` under `[registration]`), the welcome page simply points me to "Read the Docs" with no option to log in.  `docker logs` shows the error "invalid token" in the case of providing Github keys, but no message otherwise 

I don't have trouble running Drone as a Docker container via this image: https://registry.hub.docker.com/u/mattgruter/drone/ but that image is rather stale now.

**Comment by bradrydzewski** [comment]
added docs for running drone in Docker:
https://github.com/drone/drone/blob/0.4.0/doc/setup/docker.md
