### ISSUE TITLE
Builds succeeding with errors

### ISSUE THREAD

**Issue by epipho** [drone/drone#592]
In the latest 0.3 (now on master)

The docker publish plugin fails but the build is still reported as success.

$ git checkout -qf 6fa908e5832a6722e6b3c5621de4e8abf40946f8
Docker Plugin: Missing argument(s)

	docker_port not defined in yaml
$ exit 0

**Comment by bradrydzewski** [comment]
closing since we are moving all plugins to github.com/drone-plugins/* and it will be up to the individual plugin to determine when it is appropriate to fail due to missing params. Will add this to the code-review process when merging PRs or adding new plugins, to ensure this is taken into account
