### ISSUE TITLE
Networking restart problem on CentOS with SystemD

### ISSUE THREAD

**Issue by solarfly73** [drone/drone#601]
Running under Centos7, systemd  via service drone start.

I've been experiencing an ongoing issue of droned starting up but failing to acquire its network port (thus, netstat -an | grep LIST shows the port isn't up).  This is especially prevalent when trying to restart the daemon.

A rule was added to firewalld to allow all traffic to and from port 8282 (where my drone server is configured).

I've tried these things:
   1.  stopping firewalld before starting drone
   2.  Stopping docker then restarting drone
   3.  Waiting for all ports using 8282 to complete their TIME_WAIT

Edit: last output I pasted here was a red-herring, I had a bad logging option in the toml.

The networking restart problem is still an intermittent issue.

**Comment by bradrydzewski** [comment]
To simplify distribution we are now only shipping a Docker image. It is recommended to run with `--restart=always` which will instruct Docker to start the container when Docker starts. Docker's init scripts wait for networking, so using our `drone/drone:0.4` docker distribution should fix the issue for you

for reference, here is how you can run with Docker:

```diff
sudo docker run \
	--volume /var/lib/drone:/var/lib/drone \
	--volume /var/run/docker.sock:/var/run/docker.sock \
	--env-file /etc/drone/dronerc \
+	--restart=always \
	--publish=80:8000 \
	--detach=true \
	--name=drone \
	drone/drone:0.4
```
