### ISSUE TITLE
Rebuild button for write-access members?

### ISSUE THREAD

**Issue by mjschultz** [drone/drone#651]
According to (my understanding of ) the [`commit.html`](https://github.com/drone/drone/blob/50e368c24a01e1793ff607c3bba6f5cd9d190347/server/app/views/commit.html#L25) file people that have `repo.role.write` permissions should be able to see and activate rebuilds of failures. However, the people in my organization do not seem to be able to see the rebuild button.

According to the `perms` table they user_id does have repo_write permission, so I'm not sure where the problem lies.

**Comment by bradrydzewski** [comment]
we can close, merged a PR a while back
