### ISSUE TITLE
Safari 8.0 OAuth Login and Cookie Settings

### ISSUE THREAD

**Issue by foresmac** [drone/drone#663]
Whenever I try to log in to drone using Safari, I get redirected to GitHub to log in, type in my name and password, and then get an error message from GitHub. It doesn't appear to redirect back to drone. However, I'm already logged in to GitHub and using it.

My only guess is an issue with redirects or cookies.

**Comment by bradrydzewski** [comment]
I'm going to close this as an upstream issue since there isn't much we can do on our end. I appreciate the effort that went into debugging and documenting the issue. It has helped a number of other projects that were seeing similar issues.

**Comment by jlukic** [comment]
@foresmac Did you ever hear back from GitHub or find an adequate solve? I'm clueless what to do for all my Safari 8 users with issues

**Comment by foresmac** [comment]
I just basically had to change the settings back to "Allow from websites I visit". If there's any other workaround, I haven't been privy to it.

**Comment by ptoomey3** [comment]
I opened a radar about this a while back. And, it sounds like it is a bug that is supposedly fixed in the public beta of the next OS release: https://bugs.webkit.org/show_bug.cgi?id=139683
