### ISSUE TITLE
Author/gravatar inconsistancy

### ISSUE THREAD

**Issue by Tathanen** [drone/drone#667]
Drone will report the opening of a pull request by putting the pull request author's github alias in the `author` field.  When drone reports the MERGING of a pull request, or generally just any direct commit to master, it puts the committer's email address in the `author` field, rather than their github alias.

When the email address is used for the `author` field, the gravatar hash will indeed point to the gravatar for that email address.  When the github alias is used for the `author` field, a different gravatar hash will appear, one that invariably displays the system default gravatar.  Presumably this is a gravatar generated from that alias, rather than an email address.

What this means is that a single user opening pull requests and merging others will appear in Drone results as two people, sometimes with their email address and correct gravatar, and other times with their github alias and a system default gravatar.  This is problematic when attempting to track activity in a user-centric fashion.

I'm not sure if this is something that can be changed on the drone side, or if it's a fundamental github issue, but hopefully there's a resolution here that will allow consistent email-address usage for all drone builds, so people can be tracked and gravatars can be relied upon.

**Comment by bradrydzewski** [comment]
closed in 0.4 branch. we now persist the avatar url

**Comment by Tathanen** [comment]
Nice!

@scottferg fyi
