### ISSUE TITLE
Silent failure when yaml parsing error

### ISSUE THREAD

**Issue by floatdrop** [drone/drone#672]
If `.drone.yml` is malformed misguiding error will be printer.

**Comment by kylewelsby** [comment]
You could do something like this.

create a file `./bin/ci-deploy.sh/` and `chmod +x ./bin/ci-deploy.sh`

    #!/bin/bash -i
    if [ "$DRONE_BRANCH" ]
    then
        if [ $DRONE_BRANCH = "master" ]
        then
            bundle install --path vendor/bundle
            bundle exec cap production deploy
        fi
    fi

then in your `.drone.yml`

    deploy:
        bash:
            script:
               - ./bin/ci-deploy.sh

**Comment by cboettig** [comment]
Thanks for the quick reply and the complete example, that worked perfectly for me.    Of course it would be cleaner if drone didn't trigger other branches but I appreaciate the workaround.  (Didn't realize $DRONE_BRANCH was already defined by default either, that's also handy to know).  

Thanks again for this really excellent project.

**Comment by bradrydzewski** [comment]
another example that might help specifically with deployment and publish is the `when` clause:

```yml
image: gcc
script:
  - make
  - make test

deploy:
  bash:
    script:
      - make deploy
    when:
      branch: master
```

The above approach works well if you want to limit deployments to a single branch (ie master). The approach, however, falls short if you want to run a different deployment script for each branch (ie master, staging). In this case you'll definitely want to use the approach suggested by @kylewelsby until we get #696 resolved.

**Comment by lae** [comment]
I just hit this today actually, but the error was not printed in the server log and I only saw it while sniffing network traffic:
`Failed to parse yaml file or calculate matrix. yaml: line 4: mapping values are not allowed in this context
`
when a developer I work with accidentally added typoed `image` into a dict, like so:
```
pipeline:
  build:
    image: python: 3.5.1-alpine
```
(and for additional context this repo had no builds yet, so whatever solution is used, it should be able to handle that scenario too)

**Comment by bradrydzewski** [comment]
fixed in 0.6

**Comment by floatdrop** [comment]
@bradrydzewski did you mean `0.5`?

**Comment by bradrydzewski** [comment]
I introduced an 0.6 tag since I needed to make a breaking change to the agent <> server communication, and didn't want to impact existing 0.5 installs. I will post to the discourse forum and gitter once it is safe to upgrade to 0.6
