### ISSUE TITLE
deploying multiple artifacts via SSH

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#689]
Deploying multiple files via SSH is annoying as all of a sudden the deploy mechanism switches to zipping the artifacts.

I think the zipping should be independent of the number of files, or removed alltogether. When one wants a zip they should create it in the `script` section themselves.

The current implementation is very unintuitive and forces users to implement the `scp` call themselves.

**Comment by bradrydzewski** [comment]
closing now that we have https://github.com/drone-plugins/drone-rsync
