### ISSUE TITLE
Configure multiple deployments (ie multiple Heroku)

### ISSUE THREAD

**Issue by dvigueras** [drone/drone#696]
Hi,

first I would like to say Drone is awesome, I love the idea.
I would like to replace our Jenkins instance with Drone. I've already installed Drone and set up with one of our projects, but I am not able to migrate the workflow we have already set up in Jenkins.

Example:

For the same project we have 3 branches (develop, rc and master). In Jenkins we have 4 jobs:
- Project-Dev which clones develop branch and deploys the code to dev.project.com
- Project-RC which clones rc branch and deploys the code to rc.project.com
- Project-X which clones master and deploys the code to x.project.com (production environment)
- Project-Y which clones master and deploys the code to y.project.com (production environment)

I am not able to describe this scenario in just one .drone.yml file. It would be a great idea if it would be possible to create multiple jobs/configurations/profiles from each repository, and being able to specify different environment variables to each job.

While I can't get the same results with Drone I can't throw away Jenkins :P

Thanks

**Comment by AaronShea** [comment]
Do we have any update on this issue, it's a serious holdback for me

**Comment by bradrydzewski** [comment]
@AaronShea yes, works in upcoming release. Here is some preliminary documentation:
http://readme.drone.io/docs/build/#/deploy.md

next release is not available, but once I have something for people to try out I'll post to [gitter](https://gitter.im/drone/drone) and the droneio [twitter](https://twitter.com/droneio) account

**Comment by bradrydzewski** [comment]
this has been implemented in 0.4 branch, which uses the new yaml format defined in #902
