### ISSUE TITLE
Provide a way to delete a repo from drone

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#712]
Currently there is no way to disconnect a repository from drone. It would be great to have a way for drone to cleanup its hooks and remove it from the database.

**Comment by bradrydzewski** [comment]
I'm thinking we can add a simple `?remove=true` flag to the existing API call:
https://github.com/drone/drone/blob/master/server/handler/repo.go#L51

It could look something like this:

```diff
func DelRepo(c web.C, w http.ResponseWriter, r *http.Request) {
	var ctx = context.FromC(c)
	var repo = ToRepo(c)
+	var rm = r.FormValue("remove") // using ?remove=true

+	// completely remove the repository from the database
+	if len(rm) != 0 {
+		err := datastore.PutRepo(ctx, repo)
+		if err != nil {
+			w.WriteHeader(http.StatusInternalServerError)
+			return
+		}
+		w.WriteHeader(http.StatusNoContent)
+		return
+	}

	// disable everything
	repo.Active = false
	repo.PullRequest = false
	repo.PostCommit = false
	repo.UserID = 0

	if err := datastore.PutRepo(ctx, repo); err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
```

And then let's add to the `drone` command line utility. Similar to `drone disable` we could invoke `drone delete`

**Comment by JeanMertz** [comment]
What's the "improper" way to do this?

**Comment by bradrydzewski** [comment]
We added `drone delete` to the command line utility as well as a REST endpoint. So you can now do something like this:

`drone delete github.com/foo/bar`

**Comment by mwotton** [comment]
Why do I get "Unauthorized" when i try to run "drone delete github.com/myuser/myrepo"?

**Comment by bradrydzewski** [comment]
are you authenticated?
http://readme.drone.io/api/authentication/

**Comment by mwotton** [comment]
ah, that'd be it. cheers.

**Comment by loord** [comment]
http://readme.drone.io/api/authentication/ - 403 error

**Comment by tboerger** [comment]
> http://readme.drone.io/api/authentication/ - 403 error

The issue have been for 0.3, with the current version 0.4 even the docs got a total rewrite ;)

**Comment by loord** [comment]
yes :) - but i use 0.3  and i need help with deleting repo

**Comment by tboerger** [comment]
@loord and you already know that 0.3 is deprecated? :)

**Comment by loord** [comment]
really !?!?!? sure i know - but my builds does'n know about it .
without jokes - could you please explain to me - how remove github repo from drone.
How i can fix it 
> ./drone repos
> Unauthorized

**Comment by tboerger** [comment]
I never used 0.3, that's something for somebody else.

**Comment by loord** [comment]
then I give up this software

**Comment by denovez** [comment]
same with me, i no have idea for deleting repos in version 0.3..please help

**Comment by tboerger** [comment]
> same with me, i no have idea for deleting repos in version 0.3..please help

Version 0.3 reached EOL, you should switch to 0.4 or wait a little bit to directly switch to 0.5.
