### ISSUE TITLE
UI reports 45 years ago when build in progress

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#719]
If a build is in progress the placard reads 45 years ago for last build. Should probably say the build is in progress instead.

**Comment by bradrydzewski** [comment]
Note that we're getting a new design that will obsolete this issue. This will get fixed when the new design is implemented.

**Comment by mattbostock** [comment]
Would you consider merging #710 for the time being until the new design is implemented?

**Comment by bradrydzewski** [comment]
done
