### ISSUE TITLE
Run builds with --rm flag on the container

### ISSUE THREAD

**Issue by cloudnautique** [drone/drone#743]
I have been looking around and haven't found anything on this, but it doesn't look like Drone is running the builds with the `docker run --rm` flag enabled. This becomes an issue with images that have docker volumes used during the build. They fill up the ../vfs/.. directory.

Has this been considered? Are there workarounds that people have used to mitigate?

I think this could be coded as the default, or opted in, like privileged. Looking at the code, a similar  pattern as the privileged flag could be followed and bubbled up in the UI under repository settings. It seems like running with this flag would prevent cleanup scripts etc. to maintain the host. I don't think it would interfere with caching directories since bind mounts are not impacted.

**Comment by bradrydzewski** [comment]
this is fixed in the 0.4 branch, we use `docker rm -v` equivalent to ensure we remove containers and their volumes.
