### ISSUE TITLE
Docker 1.4 requires `--force` when using existing tag

### ISSUE THREAD

**Issue by novemberborn** [drone/drone#759]
See <https://github.com/docker/docker/pull/8511>.

When the Docker image is built it's tagged with the first tag (<https://github.com/drone/drone/blob/fb254e3f2c675ed65b78551224e3ed1115739f5c/plugin/publish/docker.go#L92>), then later all tags are applied (https://github.com/drone/drone/blob/fb254e3f2c675ed65b78551224e3ed1115739f5c/plugin/publish/docker.go#L102).

This should either use `--force` for all tags, or not retag the first one.

**Comment by bradrydzewski** [comment]
just merged pull request from @gregory90. Feel free to download the latest `.deb` file and try it out.

**Comment by rics3n** [comment]
is there a reason why you don't use the --force option on all tags? The problem I see is that if you want to use static tags like "latest" the build will fail on the second build, because latest is already there.
