### ISSUE TITLE
Bitbucket integration should use the slug to build URLs, not the name of the repo

### ISSUE THREAD

**Issue by orjanbruland** [drone/drone#761]
Hi!

Currently the bitbucket integration uses the name of the repo to build up the clone, git and SSH urls. This breaks if the name of the repo includes whitespace or special characters since Bitbucket generates a slug from the name of the repo to build the URLs. Using the slug returned from the Bitbucket API instead would solve this.

**Comment by bradrydzewski** [comment]
this was fixed by @gtaylor
