### ISSUE TITLE
Bintray as deployment target?

### ISSUE THREAD

**Issue by jbaruch** [drone/drone#771]
Hi guys,
Do you have any plans to support Bintray as a deployment target (similar to your support of S3)?

We see increasing number of questions "How can I deploy to Bintray from Drone?".
At the moment we provide them with an ssh script to run, but it would be nice to have it out of the box.

**Comment by bradrydzewski** [comment]
@jbaruch can you take a look at pr #802 and provide some feedback?

thanks @Bugagazavr for the implementation!

**Comment by Bugagazavr** [comment]
@jbaruch im not working with maven, and don't know how it works, i implement a basic upload for maven/rpm (same). What is central?
![2015-01-12 20 07 36](https://cloud.githubusercontent.com/assets/683590/5707072/d58481d0-9a96-11e4-8cba-4534bdde6989.png)

**Comment by Bugagazavr** [comment]
And my five cents. Now drone use `publish` inside a container via bash, this greatly complicates the interaction with the API. We can't parse json response and we need build raw json inside shell for attributes requests, it can be implemented, but support this code is really pain.

Since https://github.com/drone/drone/issues/749 we can detach publish cmds from `docker build` and when drone gone stable we can implement https://docs.docker.com/reference/api/docker_remote_api_v1.15/#copy-files-or-folders-from-a-container then we can move all publish logic from bash to Go

For now i think we need a simple implementation of publish plugins.

**Comment by bradrydzewski** [comment]
@Bugagazavr this is what I initially thought as well. We implement plugins in Go code in the old (hosted) version of Drone. It made some things easier, but made many things more complicated (like uploading globs to S3). I discussed this briefly here: https://github.com/drone/drone/issues/345#issuecomment-45123470

I agree that it feels a bit 'dirty' to implement such complex login in bash. I do think there is a 3rd option. Plugins that have command line utilities (like S3, NPM) work really really well. If a command line utility doesn't exist for a service, or is inadequate, we could create one as a separate project in a separate repository (ie github.com/drone/bintray-cli).

I think this is best of both worlds. It keeps the Drone repository minimal and focused, but still gives Drone a better way to interact with certain services.

**Comment by Bugagazavr** [comment]
@bradrydzewski agreed, but i suggest to use scripts inside drone publish plugins, python for example

**Comment by bradrydzewski** [comment]
@Bugagazavr yep, Python is a great choice because it is installed by default on all Linux distros. Go is also a great choice because we can download a single binary file into the container.

**Comment by bradrydzewski** [comment]
although I will say the Bintray code doesn't look too bad in bash. I have some ideas that could clean it up a bit and make it more readable. I'll merge the request and then submit a PR for you to review

**Comment by jbaruch** [comment]
Guys, thanks for implementing it so quickly. Not being a Go Pro (hehe) the code looks great. 
Regarding the CLI - it's definitely something to think about. Summoning @yoav for that.

**Comment by bradrydzewski** [comment]
@jbaruch great, I just merged the change and will update our docs to include configuration instructions. I may ask you to review the docs when ready, if you don't mind.

big thanks to @Bugagazavr for his work

**Comment by jbaruch** [comment]
Will gladly do.

**Comment by jbaruch** [comment]
Hey Brad, do you have any estimate when it is going to make it to the Deployments screen? (No pressure, of course).

**Comment by synhershko** [comment]
+1, would love to have this available on the Deployments screen !
