### ISSUE TITLE
RFC - Repository Syncing?

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#776]
I'd like to have a dialog about syncing repositories in Drone. I'd like to understand if it is the right approach going forward, or if it is something we should alter prior to moving from alpha to beta status. The purpose of this thread is to discuss the existing approach, the benefits and pitfalls, and possible alternatives. If we decide to stick with the current approach we can figure out how to fix some of the existing issues.

The more input the better, so please feel free to add your 2 cents.

Here is how we sync repositories today upon login:

* Get all my repositories from remote system (GitHub, GitLab, etc)
* Insert into the database if not exists
* Insert my role into the database if not exists
* If a repository or role already exists, it is skipped

This leads to a few issues:

* If my access is revoked from a repository it is not currently reflected in Drone
* If my access is modified (changed from write -> read) it is not updated in Drone
* Bitbucket does not provide permission data when retrieving the list of repositories, so we grant admin access by default (which really bothers me)
* I may see repositories on my Dashboard that aren't relevant to my daily activities, just because I have access to the repository
* It doesn't allow for role customization. For example, perhaps I should have write access to the repo in GitHub but read access in Drone

We could definitely improve the sync process and fix the issues mentioned above. That being said, syncing is kind of a pain and complicates the underlying codebase. This approach, however, does have two major benefits worth mentioning:

* I only need to manage permissions in one place (ie GitHub)
* As a new user, I immediately see any projects I have access to on my dashboard

---

#### Repository Setup:

1. User authenticates (no syncing)
2. User clicks button to add repository
3. User types repository name (there is no list here, since we didn't sync)
4. Query remote system (ie GitHub) to see if user has access to repository
  1. If Yes, continue
  2. If No, show Not Found error message
5. Does repository already exist in Drone database (ie already setup by another user)?
  1. If Yes, grant user Read / Write access based on permissions in remote system
  2. If No, but user does not have Admin rights to the repository, show Error message
  2. If No, but user has Admin rights, add repository to Drone and grant user Admin access in Drone

#### Access Management

This is kind of a hybrid approach to access management. The user can automatically add themselves to a project without having to involve the repository admin in Drone, using native GitHub permissions. The key difference is that a user is granted access to a repository in Drone on-demand, as opposed to on-sync when they login.

We could add a screen allowing the repository admin to manage user access from Drone. The admin would be responsible for updating roles and revoking access. Since we are not sync-ing data it is still possible that permission data could get stale. Hopefully a user access screen would remove any implied automation of user access.

#### Periodic Syncing Access Management

We could periodically verify user access to a repository to avoid permission data getting stale. When a user access a specific repository, we could track the "last synced" date. Prior to serving the request we could query the remote system and check access to see if it changes or was removed. This could eliminate access management, but would leave a window where an unauthorized user could still access a repository in Drone.

---

**NOTE** this is just one idea that I'm hoping will spark discussion

**Comment by nathany** [comment]
:+1: autocomplete with the ability to paste in a url

**Comment by nathany** [comment]
One nice thing about being able to provide a url is for contributing CI to open source software. I noticed that I am able to recommend a project use CI and setup the config with Travis CI (everything but the webhook). I'm not able to do this with CircleCI which requires that I click through organizations and repos that I own.

**Comment by bradrydzewski** [comment]
this change is complete in 0.4 although not yet ready to preview
