### ISSUE TITLE
using drone on a project with 2 containers

### ISSUE THREAD

**Issue by oren** [drone/drone#778]
I created a new MEAN stack project: node.js and mongodb - https://github.com/oren/mean-drone/blob/master/.drone.yml

The app is using a dockerfile and the mongodb is using the offical mongo from dockerhub.
How to configure .drone.yml to run 'grunt test' against this project?

**Comment by bradrydzewski** [comment]
@oren these should help you get up and running:
https://github.com/drone/drone/blob/v0.2.1/README.md#builds
https://github.com/drone/drone/blob/v0.2.1/README.md#databases

**Comment by oren** [comment]
thanks for those links!

Now I get this: `Error: Unable to pull image bradrydzewski/mongodb:2.4`
I tried just mongodb and just mongodb:2.4 but it didn't help.
```
image: bradrydzewski/node:0.10
services:
  - bradrydzewski/mongodb:2.4                                                                            
script:
  - npm install
  - grunt
  - bower install --allow-root
  - grunt test
```

I have few more questions: (let me know if it's better to ask those questions on a separate ticket)
1. is it possible to provide a Dockerfile for my node.js container?
2. my node code assumes that it will have `MEAN_DB_1_PORT_27017_TCP_ADDR` environment variable (that's what the --link does). is this still the case in drone?
3. is there a way to ssh to my server that is running drone and try testing my .drone.yml file from there instead of 'git push' from my laptop? it might be quicker and give me more insights of the issues i have.

Thanks!

**Comment by bradrydzewski** [comment]
> I have few more questions: (let me know if it's better to ask those questions on a separate ticket

we try to reserve the issue log for issues / bugs, so if you don't mind we'd prefer to use the gitter room or the mailing list for questions. There are typically people in the room to answer questions especially during working hours

> my node code assumes that it will have MEAN_DB_1_PORT_27017_TCP_ADDR environment variable (that's what the --link does). is this still the case in drone?

Yes, Drone uses --link. You can run the `env` command to see how Docker is injecting the environment variable. Drone uses the image name when linking, so I would expect it to look something like this `MONGODB_PORT_27017_TCP_ADDR`. Alternatively, if `socat` is installed Drone will automatically proxy connections over localhost:

>> database and service containers are exposed over TCP connections and have their own local IP address. If the socat utility is installed inside your Docker image, Drone will automatically proxy localhost connections to the correct IP address.

> is there a way to ssh to my server that is running drone and try testing my .drone.yml file from there instead of 'git push' from my laptop? it might be quicker and give me more insights of the issues i have

Drone comes with a command line utility. You can run `drone build .` from the root of your repository (with the .drone.yml in it) and assuming Docker is installed it will run your build directly from the command line without requiring a running Drone server
