### ISSUE TITLE
Wierd URL stuff

### ISSUE THREAD

**Issue by shadowfacts** [drone/drone#779]
If I go to http://drone.io/shadowfacts/EnFusion, everything works perfectly fine. But if I go to http://drone.io/shadowfacts/EnFusion/ I get a 404 page not found error. The second URL should work as well.

**Comment by bradrydzewski** [comment]
hey there, thanks for taking the time to log a bug. This repository is for the open source version of Drone which is a different project / codebase. I'm closing this here since it doesn't impact the open source version, but I'll get it added to our issue tracker for the Drone.IO service
