### ISSUE TITLE
Checkout branches other than master?

### ISSUE THREAD

**Issue by cboettig** [drone/drone#780]
How does one go about checking out branches other than master?  I see the .drone.yml in this directory has a `git` field in the yaml, but I haven't found the documentation for it.  Trying out

```yaml
git:
  branch: source
```

doesn't seem to do the trick.

**Comment by bradrydzewski** [comment]
@cboettig the branch cannot be specified in the `.drone.yml`. The branch is provided by the post-commit hook (sent from GitHub, Bitbucket, etc). Drone uses this information to automatically checkout the correct branch.

**Comment by cboettig** [comment]
Right; of course. It would be handy if this could be set in the interactive
drone configuration for the repository though.

Meanwhile the code to check branches that was posted in #672 works fine for
me (I started following that thread after encountering that issue as well,
and it fit the bill so perfectly I mistook it as a reply to this issue), so
feel free to close this.

Thanks again for the quick reply and for providing such an excellent tool.

**Comment by bradrydzewski** [comment]
Not sure if this helps, but you can also "white list" branches. This will instruct Drone to skip any branches not enumerated in the list:

```yml
image: gcc
script:
  - make
  - make test

# drone will skip any branch that isn't in this list
branches:
  - master
  - staging
```
