### ISSUE TITLE
Drone CLI don't exit container

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#784]
This was a question that came up on gitter that I wanted to open an issue for. cc @maxim

> is there a way for me to start an image by hand and get a checkout in it, so i can debug some stuff? If i just enter a docker image I don't get the repo checkout.
> so something like
> 1. launch image with /bin/bash entry point (i can do this)
> 2. run drone pre-script stuff in it <- need a way to do this
> 3. play around in the container

Today we can use the `drone build` command to run a build locally, however, it exits as soon as the build completes. It would be nice if there were an option to drop you in a bash prompt inside the container after the build is complete for further troubleshooting.

I believe this is something we can achieve with the `bash --init-file` option. We would run the build script as an init file, dropping you to the prompt once complete. For more details:
http://serverfault.com/questions/368054/run-an-interactive-bash-subshell-with-initial-commands-without-returning-to-the

Note that issue #749 is a definite pre-requesite to this request

**Comment by maxim** [comment]
Is there a new way to achieve this now? Sorry, I haven't been keeping up, but anticipating that this might still come up when setting up drone again.

**Comment by donny-dont** [comment]
Should this be moved over to https://github.com/drone/drone-cli?

**Comment by bradrydzewski** [comment]
sorry, I got a little overzealous cleaning up old issues and didn't read closely enough. Docker does have a `docker exec` command that let's you enter a running container. We would need to find a way to keep the container alive even after failure  (maybe a --keepalive flag)

**Comment by bradrydzewski** [comment]
I'm going to close this. I don't see an easy way to implement and there is, at this time, no commitment from any developers to implement this. It seems more of a nice to have at this point. If someone is willing to take ownership and send a PR we can re-open
