### ISSUE TITLE
Update postgres

### ISSUE THREAD

**Issue by elia** [drone/drone#786]
I may be wrong, but apparently the postgres service runs against postgres 9.1 which is quite old and seems to be buggy* too

* https://github.com/drone/images/issues/3

**Comment by elia** [comment]
cc @masterkain

**Comment by bradrydzewski** [comment]
@ella you can specify `postgres:9.3` to use a newer version. We are going to deprecate the images in [drone/images](https://github.com/drone/images) in favor of the official Docker images. You can use these today by specifying `library/postgres:9.4`

You can subscribe to issue #483 for updates

**Comment by elia** [comment]
Thanks, it worked!

**Comment by jGaiser** [comment]
Where does "library/postgres:9.4" belong?
