### ISSUE TITLE
[ws] Unexpected response code: 400

### ISSUE THREAD

**Issue by masterkain** [drone/drone#787]
Hello,
using the latest master (and stable .deb) it appears that websockets are broken.

We are using a private github repository on CI server.

Chrome says:

```
feed.js:10
WebSocket connection to 'ws://ci.xxxx.eu/api/stream/user?access_token=eyJhbGciOiJIUzI1LiIsInR5cCI6IkpXVCJ9.eyJhdWRpZW5jZSI6Imh0dHA6Ly9jaS5uZXQyYi5ldSIsImV4cGlyZXMiOjE0MjA5MDIzNTgsInVzZXJfaWQiOjF9.wYx5JzbGlhASEJKlKKA9gMn-4QDW5w8xRm4zprfuWwk' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by bradrydzewski** [comment]
@masterkain I'm using the latest .deb and can verify websockets are working for me in both Firefox and Chrome. Are you trying to run Drone behind a proxy server? If yes, it requires additional setup:
http://readme.drone.io/setup/misc/nginx/

**Comment by masterkain** [comment]
@bradrydzewski thanks, it turns out the problem is the local squid proxy that's so transparent we totally forgot about :p
