### ISSUE TITLE
Responsive layout for mobile devices?

### ISSUE THREAD

**Issue by foresmac** [drone/drone#795]
The existing layout doesn't look so hot on mobile Safari.

**Comment by foresmac** [comment]
![image](https://cloud.githubusercontent.com/assets/3628189/5696220/ac829c42-998b-11e4-97ed-5367cd533212.jpg)

**Comment by bradrydzewski** [comment]
agreed. We have a new design on the way that is mobile friendly (I'm told, I haven't seen it yet)

**Comment by foresmac** [comment]
Great, I'll keep an eye on this issue and check and see when it is resolved. :+1:

**Comment by foresmac** [comment]
Is this still on the radar? And/or are you interested in contributions here?

**Comment by bradrydzewski** [comment]
@foresmac could definitely use some help in this area, thanks for the offer. We are working out of the 0.4 branch for the upcoming release. The addition of matrix builds complicated the responsive efforts (see attached screenshot) so I welcome any ideas

![image](https://cloud.githubusercontent.com/assets/817538/9563641/268d3cbe-4e3f-11e5-9fac-25c57b519522.png)

**Comment by bradrydzewski** [comment]
the [drone/drone-ui](https://github.com/drone/drone-ui) repository is the new user interface for 0.5 and implements a responsive design. Closing in preparation for upcoming release.

![screen shot 2016-07-12 at 2 36 16 pm](https://cloud.githubusercontent.com/assets/817538/16784542/0ed10a66-483e-11e6-8d35-36e4cd5ee5c6.png)

![screen shot 2016-07-12 at 2 36 10 pm](https://cloud.githubusercontent.com/assets/817538/16784543/0ee4074c-483e-11e6-97cd-457e324c886f.png)
