### ISSUE TITLE
npm publish plugin, only publish if version not exists

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#799]
The proposed change is to check if the npm package/version have already been published. We can add something like this to check:

```sh
test -z "$(npm info bower@1.3.12)"
if [ $? -eq 0 ]
then
       npm publish bower
else
        echo "skipping publish, package bower@1.3.12 already published"
fi
```

Note this is just an example. We would need to substitute `bower` and `1.3.2` for injected values. We would also need a way to determine the current package version. I'm guessing we can get this with a command somehow.

/cc @donny-dont

Anything else I'm missing?

**Comment by bradrydzewski** [comment]
also we should remove `--force` since it's been deprecated

**Comment by donny-dont** [comment]
Looks about right to me. At work we're using https://github.com/rlidwka/sinopia for our private npm server. If you want to setup some tests for it I would suggest using that.

**Comment by shawnzhu** [comment]
@bradrydzewski it needs to parse `package.json` in context to get npm package name and version if checking a specific npm package is published or not.
