### ISSUE TITLE
Ability to enable open registration on a per-plugin basis

### ISSUE THREAD

**Issue by mattbostock** [drone/drone#805]
We use both GitHub.com and a private instance of GitHub Enterprise.

For our GHE users, we would be happy to allow open registration, i.e. anyone with a GHE account can log in. For GitHub.com however, we would need to restrict which users can use Drone.

Currently open registration is a global option affecting all remote plugins. I'd like to be able to enable/disable open registration for specific remotes.

**Comment by bradrydzewski** [comment]
Agreed. I'd like to move this setting to the plugin level and remove as a global plugin.

**Comment by mattbostock** [comment]
Fixed in https://github.com/drone/drone/pull/826
