### ISSUE TITLE
Disabling a repo should remove hooks and SSH keys; reactivating it should re-instate hooks and SSH keys

### ISSUE THREAD

**Issue by mattbostock** [drone/drone#807]
Currently, disabling a repository (using the CLI) removes the SSH key stored in GitHub against that repo, but it doesn't remove the Drone web hook.

Conversely, re-activating a repo after it has been disabled does not add back the SSH key.

I would expect that hooks and the SSH key would be removed and added back when repositories are disabled or reactivated.

**Comment by bradrydzewski** [comment]
Hi Matt, 

> Currently, disabling a repository (using the CLI) removes the SSH key stored in GitHub

When a repository is disabled there is no code to remove the SSH key. Disabling a repository only updates a few flags in the database. You can see the code here:
https://github.com/drone/drone/blob/master/server/handler/repo.go#L51

> Conversely, re-activating a repo after it has been disabled does not add back the SSH key.

Actually re-activating a repo does add the SSH key. I just tested this out to be sure there wasn't a regression. You can see the code here:
https://github.com/drone/drone/blob/master/server/handler/repo.go#L110
https://github.com/drone/drone/blob/master/plugin/remote/github/helper.go#L179
https://github.com/drone/drone/blob/master/plugin/remote/github/helper.go#L233

> I would expect that hooks and the SSH key would be removed and added back when repositories are disabled or reactivated.

This is something I've thought a lot about and decided to omit from Drone. Based on usage data from our hosted service we found that very few users permanently disabled CI. GitHub, Bitbucket and GitLab provide an easy way to cleanup if absolutely necessary.
