### ISSUE TITLE
Allow for optional Gravatar username overrides

### ISSUE THREAD

**Issue by ajlanghorn** [drone/drone#808]
As someone using Drone in a CI environment to test my builds in, I would like to be clearly identified using my own Gravatar which does not use the email address I commit with.

In my example, I commit with a work email address but my Gravatar belongs to a personal email address. I shouldn't have to create a WordPress.com/Gravatar account for my work email address.

**Comment by bradrydzewski** [comment]
@ajlanghorn you can link multiple email addresses under a single gravatar account, and have separate avatars for each email address. In fact, I had this same issue with my work email address and that was how I solved it (see screenshot).

I recommend giving this a try. If there are issues we can discuss further and potentially re-open this issue.

![screen shot 2015-01-12 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/817538/5713046/70a51164-9a6c-11e4-9cef-46ec26bc21df.png)

**Comment by ajlanghorn** [comment]
Oh, you're right @bradrydzewski; thanks for pointing that out!
