### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by kri5** [drone/drone#809]
While trying to login using gitlab.com in drone, i get the following error

    2015/01/13 14:32:18 invalid character '<' looking for beginning of value

I launched drone this way

    DRONE_SERVER_PORT=localhost:9876 DRONE_GITLAB_URL="http://gitlab.com" droned

i tried using the Dockerfile and also using the debian package on ubuntu14.04 .

Btw i also tried to authenticate manually against https://gitlab.com/api/v3/session and it works, so it does not seems to be related to wrong credentials.

Any ideas?

**Comment by bradrydzewski** [comment]
@kri5 yep, you'll want to use **https**://gitlab.com` instead
