### ISSUE TITLE
Time estimation wrong on dashboard. 

### ISSUE THREAD

**Issue by tombert** [drone/drone#810]
There's an issue (not a huge one, just a minor thing) with the time estimates on the dashboard

![screen shot 2015-01-13 at 10 22 45 am](https://cloud.githubusercontent.com/assets/2027925/5724078/97978c28-9b0e-11e4-8c01-6804f145e005.png)

Since I find the idea that this repository being 45 years old a little hard to swallow, I figured I'd report it here.

**Comment by tombert** [comment]
Oh, and just for a note: 
```
ubuntu@ip-172-32-0-118:~$ drone --version
drone version 0.3-dev
```

**Comment by bradrydzewski** [comment]
merging with #719
