### ISSUE TITLE
xgo

### ISSUE THREAD

**Issue by mephux** [drone/drone#811]
Has anyone got this working with drone? https://github.com/karalabe/xgo

**Comment by mattbostock** [comment]
What is the problem that you would like to solve using xgo?

**Comment by Bugagazavr** [comment]
drone cannot build on i386, i think this is because in drone uses int64 variables.

**Comment by mattbostock** [comment]
Forgive my ignorance but I'm curious, under what circumstances when would you need Drone to run under i386?

**Comment by mephux** [comment]
@mattbostock just to have an easy way to cross-compile or have a binary for both arch. https://registry.hub.docker.com/u/karalabe/xgo-base/dockerfile/ it pretty much just sets this up.

**Comment by bradrydzewski** [comment]
@mephux have you tried using the `karalabe/xgo-base` container with Drone? Drone supports using custom Docker images `image: karalabe/xgo-base` when building code. I'm not sure Drone needs to do anything special here.

Let's move this discussion to gitter: https://gitter.im/drone/drone
