### ISSUE TITLE
Report any error when parsing private variables

### ISSUE THREAD

**Issue by jsdir** [drone/drone#812]
If the YAML parser cannot parse the private variables in the settings, it fails silently, and the build continues. The build needs to fail and report the parsing error instead.

**Comment by bradrydzewski** [comment]
Just merged #812 which returns a yaml parsing error when encountered. The yaml parser can be a bit lax but this is still a useful change.

We still need to display error messages in the user interface, but I am tracking this task under a separate issue https://github.com/drone/drone/issues/542#issuecomment-58837055
