### ISSUE TITLE
gnu awk missing

### ISSUE THREAD

**Issue by flokli** [drone/drone#815]
My ./configure script is failing, as it doesn't find gawk:

```
Checking 'gawk'... failed.

Build dependency: Please install GNU awk.
```

Can you include it in the build drone images?

**Comment by bradrydzewski** [comment]
I recommend installing `awk` using apt-get install, using a custom image, or one of the images in the official Docker index (index.docker.io). We will be deprecating the `drone/images` repository in favor of the official Docker language stacks [1]

[1] http://blog.docker.com/2014/09/docker-hub-official-repos-announcing-language-stacks/
