### ISSUE TITLE
Handling PR and commit webhooks for the same Commit

### ISSUE THREAD

**Issue by andy-g** [drone/drone#819]
I work in a team where we all have access to the private github repo, and develop directly against it (as opposed to forking it to our personal GitHub accounts). All our changes are submitted as Pull Requests though (we push the feature branch to the shared private repo on GitHub, and then create a PR from there). 

The issue is that because the branch and the PR are part of the repository linked to drone, github will send a webhook for both the commit on the branch and the PR. This then continues for each subsequent change to that branch after a PR has been created. Drone seems to just respond to 1 and ignore the other (I'm guessing it just responds to the first one it receives 'cause sometimes it is the PR one and sometimes it's the commit one). This results in the following issues:

* If it handles the PR one and ignores the commit one, the commit message is the PR title and not the actual commit message.
* If it handles the PR one after the initial PR was created, it then results in a duplicate block for the same PR under the Pull Requests section
* If it handles the commit one, it doesn't update the PR block at the bottom. For example, if I submit a PR and the build fails, and I then push a fix which builds successfully, if drone runs the commit webhook (rather than the PR one), the PR block will still reflect a failure even though the commit from that PR has built successfully.

I realise that this may be slightly unusual workflow (especially compared to open source repositories), but I'm assuming it should still handle it. Possibly, if a PR webhook is received after the commit webhook for the same SHA, it should update the record in the commits table (updating the commit_pr column, and probably replacing the value of the commit_message column to rather be the PR title too).

**Comment by bradrydzewski** [comment]
is this similar to #740 ?

**Comment by andy-g** [comment]
I think it is related, yes. I think it's all related to 2 webhooks being sent from GitHub when a PR is updated (one for the branch change and the other for the PR change). The inconsistancy of which one drone picks up first and runs results in the issues I specified along with the issues in #740.

I think the isssue that @dangra raised:
> UI shows a branch and PR build but both links to PR, and none to the branch

Is as a result of  
```html
<section ng-if="layout == 'grid'" ng-repeat="group in commits | filter: { pull_request: '' } | unique: 'branch'">
```
which should actually force a strict equality comparison rather than a substring match:
```html
<section ng-if="layout == 'grid'" ng-repeat="group in commits | filter:{ pull_request: '' }:true | unique: 'branch'">
```
So PR's aren't actually excluded from the branch list (similar to what I fixed in #803). I'll submit a new PR for this issue, but we'll still need to work out how to handle the double webhook call.

**Comment by x-cray** [comment]
I have another scenario when building same commit for different branches is necessary. Although checked out source code is the same, deployment logic may differ. We have 2 main branches: `master` and `develop` (main development is performed on `develop` branch while `master` is considered stable and used for production deployments). For deployment purposes we publish Docker images which are tagged with the name of branch the code was checked out from, i.e. `:<project-name>-master` and `:<project-name>-master`. So when (after rebase, for instance) the same commit occurs in both branches, we need to run two separate builds to publish the same Docker image with two tags.

**Comment by x-cray** [comment]
Is https://github.com/soundrop/drone/blame/master/pkg/handler/hooks.go the only place where duplicate builds are prevented?

**Comment by bradrydzewski** [comment]
@x-cray it is being enforced at the database tier, however, this restriction is removed in the release

**Comment by x-cray** [comment]
@bradrydzewski sorry, don't know where I took that link from, it's very outdated =)

**Comment by bradrydzewski** [comment]
sorry, typo in my response as well -- this restriction is removed in the **next** release

**Comment by bradrydzewski** [comment]
fixed in 0.4 branch with use of build number to uniquely identify build, instead of sha+branch

**Comment by dangra** [comment]
is 0.4 usable with mysql as store? I understand it is not "stable" but 0.3 isn't and I am happy using it. 

I have mixed feelings due to references to mysql driver in [pkg/store/builtin/store.go#L19](https://github.com/drone/drone/blob/0.4.0/pkg/store/builtin/store.go#L19) but not actually registering it.

**Comment by bradrydzewski** [comment]
@dangra not yet, check out http://readme.drone.io/docs/setup/#/mysql.md ... there is an issue w/ the driver that I'd really like to see resolved first. It is planned for the authors upcoming release
