### ISSUE TITLE
Dart:  Add pub bin dir to PATH

### ISSUE THREAD

**Issue by seaneagan** [drone/drone#821]
For dart builds if you want to call any [pub global activated executables](https://www.dartlang.org/tools/pub/cmd/pub-global.html#running-a-script-from-your-path) you have to add the following to your drone script:

export PATH="$PATH":"~/.pub-cache/bin"

It would be nice if this were done automatically.

**Comment by bradrydzewski** [comment]
@seaneagan we're going to be deprecating the custom drone images in favor of the official docker images. Have you had any luck with `google/dart`?

**Comment by seaneagan** [comment]
That's great!  Filed an issue there:

https://github.com/dart-lang/dart_docker/issues/10
