### ISSUE TITLE
Drone project Dockerfile currently does not build

### ISSUE THREAD

**Issue by wernerb** [drone/drone#822]
It returns the following error during make build:

	 ---> Running in 8e1e34b89ff6
	fatal: Not a git repository (or any of the parent directories): .git
	mkdir -p packaging/output
	mkdir -p packaging/root/usr/local/bin
	go build -o packaging/root/usr/local/bin/drone  -ldflags "-X main.revision  -X main.version 0.3.0-alpha" github.com/drone/drone/cli
	# github.com/drone/drone/cli
	usage: 6l [options] main.6
	  -1	use alternate profiling code
	  -8	assume 64-bit addresses
	  -B info
	    	define ELF NT_GNU_BUILD_ID note
	  -D addr
        .........
	make: *** [build] Error 2

**Comment by bradrydzewski** [comment]
thanks, removed the `.dockerignore` because it was excluding `.git` which was being used to query the current revision, which is embedded in the binary.
