### ISSUE TITLE
Selective email notifications

### ISSUE THREAD

**Issue by os12** [drone/drone#828]
Is there a way to receive selective email notifications? I am not interested in seeing "yes, your build is still green" stuff, yet absolutely care to know the following:
  1. build failures
  1. or, even better, changes in the build status

This stuff is done quite well in Travis CI. Is there a way to configure at least (1) on Drone?

Thanks!

**Comment by bradrydzewski** [comment]
yep http://readme.drone.io/usage/notify/email/

please feel free to use our chat room for any further questions
https://gitter.im/drone/drone
