### ISSUE TITLE
the commit get stuck in running for some reason and can't manually stop building the commit.

### ISSUE THREAD

**Issue by helxsz** [drone/drone#830]
I have installed the drone on the digital ocean, my app is very simple express node.js app.
```javascript
var express = require('express');
console.log("hello log");
var app = express();
app.get('/', function(req, res){
  res.send('hello world');
});
app.listen(3300);
```
my yml is like
```javascript
image: dockerfile/nodejs
env:
  - GOPATH=/var/cache/drone
script:
   - echo hello world 222
   - pwd
   - ls
   - npm install express redis mqtt
   - node app.js
   - /bin/bash
services:
  - mongodb
  - rabbitmq
  - redis
```

when the drone server is updating on the commit, it will get stuck in running the ###### node app.js, keep running forever...
Firstly, I don't know why it will get stuck in running ###### node app.js, in particular in app.listen(3300), if I commented the line ###### app.listen(3300), the commit update will be successful. The port 3300 is always open.
Secondly, because the update is running forever, and there is no way for me to stop the current commit, even I push a new commit, this new commit will fail to execute since the previous commit is still running.

Anybody help me with these two issues ?

**Comment by bradrydzewski** [comment]
This is because the `app.listen()` function in `node app.js` is a blocking operation. It blocks the terminal and therefore hangs the build. You could try something like `node app.js &` instead, when runs the command in the background and let's the build proceed.

We do plan to introduce the ability to stop / cancel builds. You can subscribe to #336 and #549 for progress updates.

Also we have a chat room where you can ask questions:
https://gitter.im/drone/drone

**Comment by helxsz** [comment]
@bradrydzewski Thanks a lot. 
Currently my drone is also in the docker container, in order to stop the stuck drone process, I manually restarted the drone docker container and pushed several new commits, however every new commits would fail with a message saying: ######Error: Failed to start build container. Internal Server Error .

I don't know what is this so-called ###### Internal Server Error. and I don't know how to fix this, If there is no way to fix the current drone container,  the only way I could figure out is I have to remove this container and re-run a new drone container.
