### ISSUE TITLE
could not connect to the server in the container, is it because of the wrong port mapping between the host and container?

### ISSUE THREAD

**Issue by helxsz** [drone/drone#831]
This is my app , a very simple express node.js app.
```javascript
var express = require('express');
console.log("hello log");
var app = express();
app.get('/', function(req, res){
  res.send('hello world');
});
app.listen(3300);
```
my yml is like
```javascript
image: dockerfile/nodejs
env:
  - GOPATH=/var/cache/drone
script:
   - echo hello world 222
   - pwd
   - ls
   - npm install express redis mqtt
   - node app.js &
   - /bin/bash
services:
  - mongodb
  - rabbitmq
  - redis
```
As the drone.io built up the image and run the app container successfully on my digitalocean server. I opened the url : https:digital_server_ip:3300, it was supposed to obtain the 'hello world' text, but in fact, the page could not be open.

 in the docker, usually the container will have to expose the port, and make a mapping with host_port: container_port,  how does the drone.io handle this port mapping and exposure, is this the reason that my server in the container is open at 3300 port, but not connected from the host environment ?

**Comment by bradrydzewski** [comment]
Drone doesn't expose your application externally. It is meant to run your test (ie `npm test`) and record your test results. Once the tests are executed it exits immediately. It is not meant to host your app.

So your script would look something like this:

```
script:
   - npm install express redis mqtt
   - npm test
```

**Comment by helxsz** [comment]
Thanks, @bradrydzewski . i got it now.
Another question is when the npm test is done well. so I could pack the updated code into a image, run the image into a container and link the container to other service containers like what we do in the docker application, is it ?
