### ISSUE TITLE
A global docker version setting

### ISSUE THREAD

**Issue by vaijab** [drone/drone#835]
Right now it is very difficult to keep docker host and docker client versions that drone installs by default. I am aware that docker client version can be specified per repo, but that does not really help.

My setup has a separate docker host (coreos) and drone connects over tcp socket to it, so when CoreOS updates and ships newer version of docker binary, I have to go and update all my repos to tell drone which version of docker client to download and install.

I think it would be a lot easier to have a global `DRONE_DOCKER_CLIENT_VERSION` parameter. Docker version in `.drone.yml` should still take precedence as it does now.

**Comment by stateci** [comment]
+1

**Comment by danharvey** [comment]
+1

**Comment by bradrydzewski** [comment]
We do something similar with the npm plugin. You can see an example here:
https://github.com/drone/drone/blob/master/plugin/publish/npm/npm.go#L28

Ideally all of our plugins would have global defaults, so I would happily accept a PR that adds globals to the Docker plugin.

**Comment by bradrydzewski** [comment]
we have moved the docker functionality to the [drone-plugins/drone-docker](https://github.com/drone-plugins/drone-docker) external plugin. This uses Docker-in-Docker to mitigate such issues. Creating a custom plugin is now trivial, if you need to modify this behavior
