### ISSUE TITLE
Installed docker client version does not get used

### ISSUE THREAD

**Issue by vaijab** [drone/drone#836]
If `docker_version` is specified in `.drone.yml` file then drone installs that specific version of docker client to `/usr/local/bin`.

However if given base image already has docker client installed in `/usr/bin`, then by default drone uses `/usr/bin/docker`, because usually that has precedence in `$PATH`.

I think drone should delete existing docker binary or should change `$PATH` before it runs docker client.

**Comment by bradrydzewski** [comment]
@vaijab yes, this is the desired behavior. You can either pre-install a Docker version in your container, or you can let Drone install it on the fly. We'll be releasing a new module that allows you to script custom plugins, which may help when the existing plugins don't 100% meet your needs
