### ISSUE TITLE
Build priority to master branch

### ISSUE THREAD

**Issue by Jean85** [drone/drone#850]
I like a lot that drone builds my secondary branches, but I would like to ***prioritize the builds on master branch***, to speed up our CI and prod deployment time.

Considering we are 5 devs on the same project, it happens all the time that we have 1 or 2 commits awaiting to be built on master, while other, lesser important or WIP branches are constantly taking over the consumers and slowing down the queue.

There is something that can be done, apart from disabling all the secondary branches or piling up consumers?

**Comment by bradrydzewski** [comment]
@Jean85 one option would be to increase the number of Docker workers (in the config file). We are working on the ability to spread builds across servers, so you can quickly scale up and down as your demand grows or shrinks.

I'm not sure we'll alter the core Drone queue to prioritize builds. It just gets too complex and everyone has different criteria for prioritization. I do think we can make the queue scriptable / pluggable to meet your specific needs. I'm therefore going to merge this with #758
