### ISSUE TITLE
Become Official Slack Service

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#854]
It would be great to become an official Slack plugin:

![slack_integration_message](https://cloud.githubusercontent.com/assets/817538/5914025/b467b906-a5a2-11e4-8249-60e42549a0a3.png)

I've gotten a lot of feedback about this as well. I was hoping for some help from our Slack enthusiasts out there. If anyone is interested let me know. I'll be contacting the Slack team to see what we need to do to make things official.

**Comment by bradrydzewski** [comment]
cc @donny-dont

**Comment by wernerb** [comment]
Would be great! We use drone in slack with webhooks, which is already working well. I would be glad if the current webhook functionality would continue to work though. One reason is that you can have an unlimited amount of webhooks, but only 5 integrations with slack :)

**Comment by donny-dont** [comment]
This would be great!

One thing I noticed with the e-mail plugin was that you could send an e-mail directly to the person that broke the build. If it were possible to make it so it would not only send a build notification to the channel, so everyone would get that feedback, but also a direct message to the offender. Would be great to configure what that message would look like so you could send out a Luigi death stare or something.

**Comment by dave-tucker** [comment]
:+1: Slack integration has been working well for us. Would love to see this official

**Comment by marksteve** [comment]
:raised_hands:

**Comment by mwotton** [comment]
this'd be great. Would also like to be able to send maybe the last N lines of the build log in the message too?

**Comment by anthonyringoet** [comment]
Would be nice

**Comment by fernandezpablo85** [comment]
+1

**Comment by shabeermothi** [comment]
+1

**Comment by dgroup** [comment]
+1

**Comment by bradrydzewski** [comment]
I am closing this because after reaching out to slack (2 years ago) I never received a reply. I am not sure what benefits being an official provider gives us that we don't have today, aside from marketing. If there is continued interested in seeing Drone as an official service I would encourage a community member to take ownership of this task.
