### ISSUE TITLE
GitLab Refresh Tokens & Concurrency

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#855]
When the `access_token` is refreshed GitLab also sends a new `refresh_token`. This is a perfectly valid (but optional) implementation detail:

> the authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token.

When GitLab sends back a new `refresh_token` it also immediately expires the old `refresh_token`. This is also a perfectly valid (but optional) implementation detail:

> The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client.

This becomes problematic for systems that are making concurrent requests to the API. It is possible for two threads (or in our case goroutines) to successfully refresh an access_token around the same time. This means one thread will have an expired set of tokens that it cannot refresh.

This gets more complicated because we are making these requests offline. This means if we achieve the above race condition, we could get locked out of the API forever until the user physically goes to the website and re-authenticates.

There really isn't a good way to handle this in a concurrent, offline environment. We could try to implement mutexes, but even this is subject to edge cases (ie program quits un-unexpectedly)

I believe we need to engage GitLab for this. One example of a middle ground could be providing `access_type=offline` (similar to Google) that would prevent sending a new `refresh_token` when refreshing an `access_token`.

Another option would be to more closely mirror GitHub and never expire an access token. It looks like this is possible (see https://github.com/doorkeeper-gem/doorkeeper/pull/76) but I'm not sure they would be willing to make such a drastic policy change.

**Comment by Intrepidd** [comment]
I think we stumbled upon this. After recently upgrading drone, we had issues with build not launching.

After digging into the logs and source code, we found that the owner of the repository had to log in again.

Problem is, this issue happens several times a day. I imagine we're having the race condition you're describing

**Comment by bradrydzewski** [comment]
gitlab removed refresh tokens by default, so no longer applicable

**Comment by Intrepidd** [comment]
Indeed, after updating gitlab the issue is now gone, thanks
