### ISSUE TITLE
Jenkins Env Variable Compatibility

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#859]
Per https://github.com/drone/drone/pull/858#issuecomment-71968729 we should consider adding environment variables to match other CI systems (specifically Jenkins).

Below is what the old version of Drone used, which I think is a good starting point. We intentionally omitted some environment variables (like `SVN_REVISION`) since they aren't as relevant today as when Jenkins was created.

* `JOB_NAME`: the name of your project (github.com/:user/:repo)
* `WORKSPACE`: the location of your code and working directory of your build script
* `BUILD_URL`: the url of your build (drone.io/github.com/:user/:repo/:build)
* `BUILD_DIR`: the location of your code and working directory of your build script
* `BUILD_ID`: the current build number
* `GIT_COMMIT`: the commit hash currently being built
* `GIT_BRANCH`: the branch currently being built

cc @craigtracey

**Comment by themihai** [comment]
Is there any reason why the docs indicate this feature is already available? [0]

http://docs.drone.io/env.html

**Comment by daMupfel** [comment]
@themihai this are the docs for the paas on docker.io.

This is the open source version of docker which is currently in development. You can find the docs on http://readme.drone.io/setup/overview/

**Comment by themihai** [comment]
Thanks @daMupfel ! I assume the OS version doesn't provide environment variables or at least they are not documented[1] 

[1] http://readme.drone.io/usage/help/

**Comment by andrewsomething** [comment]
I was looking to see if there was a `DRONE_PULL_REQUEST` or similar environmental variable available in order to add Drone support to another service, and I found `CI_PULL_REQUEST` Though it seems to be set in master but not the 0.4.0 branch or the PaaS version (at least according to the documentation). I would be great if the different environmental variables could be standardized across the different active versions. It would make it much simpler to support Drone in other tools.

**Comment by bradrydzewski** [comment]
@andrewsomething you might find these docs helpeful:
http://readme.drone.io/docs/build/#/env.md

the above documents detail all the environment variables available in the upcoming 0.4 version. The 0.3 version will be deprecated within the coming weeks as we move to 0.4.

the 0.4 codebase splits out the drone server from the drone build engine, which is probably why you couldn't find those variables if you used GitHub search. This decision probably merits a blog post of its own, but basically separating the server from the engine means the build engine is swappable. The drone engine code can be found here: https://github.com/drone/drone-exec  (repo name may change to drone-engine)

**Comment by andrewsomething** [comment]
Great! Thanks for the quick reply @bradrydzewski
