### ISSUE TITLE
Gogs Private Repos

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#860]
The current Gogs implementation works for public (open source) repositories only. We need a way to upload ssh keys to the repository in order to clone. Ideally we would also have a way to see if the key already exists, and either update or delete and re-upload.

We'll need the Gogs team to expose this functionality.

For reference, this is the code we use for GitHub:
https://github.com/drone/drone/blob/master/plugin/remote/github/helper.go#L233:L255

@compressed thoughts?

**Comment by bradrydzewski** [comment]
For reference, I just logged https://github.com/gogits/gogs/issues/878

**Comment by andyjeffries** [comment]
Looking forward to having this functionality working.  I'm a real newbie in Golang, but if I can be of any help testing it, let me know.

**Comment by compressed** [comment]
Thanks for logging this. Yep, it is needed.

On the https side, I worked on a PR (already merged) so we can now clone private repos as well using the drone token: https://github.com/gogits/gogs/pull/845

We should try to support both ssh and https methods when doing this work for private repos.

**Comment by andyjeffries** [comment]
Don't suppose you have any blog post/markdown file on how to setup drone with gogs do you?

**Comment by bradrydzewski** [comment]
we do have some docs for Gogs, although not as complete as our GitHub docs (for example)
http://readme.drone.io/setup/config/gogs/

**Comment by csu** [comment]
+1

**Comment by Ant59** [comment]
+1

**Comment by Kruemmelmonster** [comment]
:+1:
just asking is this going to fix http/s cloning aswell?
because in my setup i rely on it

**Comment by Ant59** [comment]
Is there an ETA on this? It's a really important missing feature. Most people using self-hosted Git/CI want private repos, else we'd be using GitHub.

**Comment by Kruemmelmonster** [comment]
i am working on a workaround on this issue keep looking into here later

**Comment by Kruemmelmonster** [comment]
i found a temporary fix wich has a serious security problem (not a problem for me because my drone installation is not accessible anywhere outside my network).
You can see the Username and Password in the build log

I just edited the database (in my case sqlite) and changed the field `repo_clone_url` and `repo_git_url` to have my credentials in them like `http://username:password@gitserver/user/repo`

**Comment by bradrydzewski** [comment]
@Ant59 I agree this is important, however, I'm a bit oversubscribed at the moment. I'm looking for someone from the community to step up and implement Gogs private repository support. I've labeled the issue accordingly.

To complete this issue we need Gogs to support deploy-keys. I'm not sure if this feature is available yet, however, it is not yet available in the Gogs Go client:
https://github.com/gogits/go-gogs-client

Once the above feature is available in the Gogs Go client, hooking everything up to Drone shouldn't be too difficult.

**Comment by compressed** [comment]
For http cloning of private repos I think all that is needed is to use the drone token we create and modify the clone url to send that token, e.g.: 'https://token@server.git'.

The token should work for cloning already.

**Comment by Kruemmelmonster** [comment]
i just tested it and it works flawless! only thing thats not good is that its in the build log aswell

**Comment by dkisselev** [comment]
+1, here's how I got this working for anyone that lands here;

On Ubuntu, the drone sqlite db is stored in /var/lib/drone. Use an sqlite editing tool to edit the repos table, and change repo_clone_url.

The specific token that you want is on the webhooks page for your project in Gogs. (the "Secret" selection that's a password field by default. Inspect element on it to pull the token out and add it to the URL)

**Comment by bradrydzewski** [comment]
0.4 branch now officially supports Gogs, including the ability to clone private repositories. The 0.4 version uses a `.netrc` file to clone your repositories with a token, which is actually better than `ssh` since it allows you to clone your dependencies as well (great for `npm install` or `go get`, etc).

**Comment by bradrydzewski** [comment]
reference documentation for 0.4 branch

installation instructions: http://readme.drone.io/docs/setup/index.html
gogs setup instructions: http://readme.drone.io/docs/setup/gogs.html

**Comment by denghongcai** [comment]
I'm using Drone 0.4.0-beta+200 and Gogs  0.8.0.1212, added a private repo, but build still fail...

the error message:
```
fatal: could not read Username for 'http://gogs.tld': No such device or address
```

I can't find solution from docs, is there anyone help me ?

**Comment by bradrydzewski** [comment]
@denghongcai I recently upgraded from gogs `0.6.16.1022` to `0.8.10.1217` and am unable to reproduce any issues cloning private repositories. I wish I could suggest a solution, however, it isn't clear what the root cause may be, and since I cannot reproduce in my testing environment I'm not sure how to help.

My recommendation is to start a container on your build server (let's say `docker run -t -i golang /bin/bash`) and then see if you can clone your private repository with a username and password inside the container. Also try using a netrc to clone it (that is what drone does). You need to isolate the root cause which may or may not even be related to Drone. It could have something to do with Docker networking, for example.

**Comment by denghongcai** [comment]
reinstall the same version resolve my problem...maybe something wrong before. Anyway, thanks for your help!

**Comment by Rio** [comment]
@bradrydzewski, I've just installed a completely fresh gogs:0.8.10 image that has version 0.8.10.1217 and the drone:latest image. But I'm also getting the could not read Username. I don't have an netrc. Can't really find how to make one anywhere in the docs. I've also tested if I can clone from a container on the build server and that works.

```
[info] Pulling image plugins/drone-git:latest
$ git init
Initialized empty Git repository in /drone/src/gogs/me/python-project/.git/
$ git remote add origin http://gogs:10080/me/python-project.git
$ git fetch --no-tags --depth=50 origin +refs/heads/master:
fatal: could not read Username for 'http://gogs:10080': No such device or address
[info] build failed (exit code 1)
```

**Comment by bradrydzewski** [comment]
@Rio are you sure you don't have a netrc? It is automatically created by the git clone plugin. https://github.com/drone-plugins/drone-git

**Comment by bradrydzewski** [comment]
per my prior suggestion, did you attempt to clone your repository using the https url inside a Docker container on your build server? It is important to perform this test on the same server running your Drone builds. This will confirm whether or not you are experiencing inter-container-communication issues, in which case it is a networking issue.

**Comment by Rio** [comment]
@bradrydzewski, As I've pointed out in my previous post I've already checked container communication and it works with the http url.

Where would I be able to find that netrc file? I can't get into that docker container using /bin/bash, I guess it's pretty bare.

**Comment by bradrydzewski** [comment]
@Rio you can test the git clone plugin in complete isolation. Use the below command with your repository and user details substituted:

```bash
docker run -i plugins/drone-git <<EOF
{
    "repo": {
        "clone": "https://github.com/drone/drone.git"
    },
    "build": {
        "event": "push",
        "branch": "master",
        "commit": "436b7a6e2abaddfd35740527353e78a227ddcb2c",
        "ref": "refs/heads/master"
    },
    "workspace": {
        "root": "/drone/src",
        "path": "/drone/src/github.com/drone/drone",
        "netrc": {
            "machine": "{{ gogs scheme }}://{{ gogs hostname or ip and port }}",
            "login": "{{ your token here }}",
            "user": "x-oauth-basic"
        }
    }
}
EOF
```

The machine value in the JSON payload comes from the `link_url` field in Drone. The `link_url` and we extract just the scheme and hostname (or ip and port) and strip out the path.

The clone value in the JSON payload comes from the `clone_url` field in Drone. It is important to make sure you test with the exact same fields as Drone is using. You can get these fields by going to `http://my-drone-instance/api/repos/{{ owner }}/{{ name }}` which gives the JSON representation of your repository.

The token (which goes in the login field) comes from the user table in your Drone database. `select * from users where user_login = ?` where `?` is your username.

**Comment by gnanakeethan** [comment]
@bradrydzewski I am facing the same issue as reported by @Rio here. 


I just started gogs and its pull and push works outside Drone(Docker) very well. I has SSHed into a docker container. and was able to clone a repo over internet. Thus, there might not be a problem in connection.

**Comment by bradrydzewski** [comment]
@gnanakeethan did you follow the exact troubleshooting steps mentioned above in my latest [comment](https://github.com/drone/drone/issues/860#issuecomment-166997975)?

**Comment by gnanakeethan** [comment]
@bradrydzewski 
I am getting this error. Its saying something totally different here. 

```
USER@IP:~$ docker run -i plugins/drone-git <<EOF
> {
>     "repo": {
>         "clone": "https://github.com/drone/drone.git"
>     },
>     "build": {
>         "event": "push",
>         "branch": "master",
>         "commit": "436b7a6e2abaddfd35740527353e78a227ddcb2c",
>         "ref": "refs/heads/master"
>     },
>     "workspace": {
>         "root": "/drone/src",
>         "path": "/drone/src/github.com/drone/drone",
>         "netrc": {
>             "machine": "http://IP:10080/",
>             "login": "TOKEN",
>             "user": "x-oauth-basic"
>         }
>     }
> }
> EOF

$ git init
Initialized empty Git repository in /drone/src/github.com/drone/drone/.git/
$ git remote add origin
$ git fetch --no-tags --depth=50 origin +refs/heads/master:
fatal: No path specified. See 'man git-pull' for valid url syntax
```

**Comment by bradrydzewski** [comment]
@gnanakeethan can you try to use `clone_url` instead? Also make sure you alter the JSON to include your repository and commit details (including the clone url, sha, branch, etc) 

```diff
     "repo": {
-         "clone": "https://github.com/drone/drone.git"
+         "clone_url": "https://github.com/drone/drone.git"
     },
```

**Comment by gnanakeethan** [comment]
@bradrydzewski , Its a success in cloning that URL. When I fill in Gogs URL it just fails as originally found. I just generated a token on my account in gogs and used it. 

```
$ git init
Initialized empty Git repository in /drone/src/IP/gnanakeethan/gnana/.git/
$ git remote add origin http://IP:10080/gnanakeethan/gnana.git
$ git fetch --no-tags --depth=50 origin +refs/heads/master:
fatal: could not read Username for 'http://IP:10080': No such device or address
```

**Comment by bradrydzewski** [comment]
Perhaps the netrc file doesnt' like the port number? I've never tested with a raw IP and port, so that is the only difference I can see at the moment between my configuration and yours:

```diff
         "netrc": {
-             "machine": "http://IP:10080/",
+             "machine": "http://IP",
             "login": "TOKEN",
             "user": "x-oauth-basic"
         }
``

**Comment by bradrydzewski** [comment]
also omit the scheme from the `machine` in your test:

```diff
         "netrc": {
-             "machine": "http://IP:10080/",
+             "machine": "IP",
             "login": "TOKEN",
             "user": "x-oauth-basic"
         }
```

**Comment by gnanakeethan** [comment]
Yeah. That was the terrible issue. Now everything is running and going fine. I think you should document this issue very clearly.

**Comment by tboerger** [comment]
> Note that the netrc file only deals with connections at the machine level and should not include a port or protocol designation, meaning both "mymachine.labkey.org:8888" and "https://mymachine
https://www.labkey.org/home/Documentation/wiki-page.view?name=netrc

**Comment by tboerger** [comment]
@bradrydzewski you should strip ports and protocols from netrc content :)

**Comment by Rio** [comment]
After starting my gogs instance to serve on 80 instead of 10080 I can confirm it's working as expected for private repositories.

**Comment by gnanakeethan** [comment]
@bradrydzewski @tboerger I hope this fact gets documented here in Drone. 

@Rio , 😀😀.

**Comment by tboerger** [comment]
It doesn't need to be documented, the code needs to be fixed ;)

**Comment by bradrydzewski** [comment]
@gnanakeethan thanks for running those tests to verify it was a port issue. I've updated the code to strip the port before generating the netrc file. https://github.com/drone/drone/commit/32cdf41ce72980530df6419f59316a1d477224cd

**Comment by gnanakeethan** [comment]
@bradrydzewski its great to have fixes. :+1: :smile: :laughing: . Thanks a lot for your kind help.

**Comment by cusspvz** [comment]
Is that too much to ask for a patch release with this fix included?

**Comment by cusspvz** [comment]
For those who were facing the same as I:
I've configured a `drone` cluster which was connecting to a `gogs` cluster internally (used `http://gogs-servers:3000?open=false` as option).
Happens that builds were unable to fetch remote, printing out the same error described here.

After I've changed option to our global SSL endpoint, it worked like a charm.

**Comment by ben-burlingham** [comment]
@cusspvz I have exactly the same issue, GOGS on port 3000.

> After I've changed option to our global SSL endpoint, it worked like a charm.

Could you explain what option you changed?

**Comment by cusspvz** [comment]
@ben-burlinghamare you must set the url you use as endpoint on **drone**, even if you can reach it internally. If you're using LB in front of **gogs** and your **drone** installation has access to **gogs** directly, you can avoid passing **drone**'s requests through the LB of **gogs** by placing an entry on `/etc/hosts` and adding an **iptables** rule.

**Comment by joelchen** [comment]
Has anyone successfully login to Drone 0.5.0 over self-hosted Gogs repository? I get "Unable to login. Registration is closed." with Gogs running on HTTP port 10080 and SSH port 10022, and /etc/dronerc configured as such:
```
DRONE_DEBUG=true
DRONE_GOGS=true
DRONE_GOGS_URL=http://gogs.company.com:10080
DRONE_AGENT_SECRET=secret
I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION=true
I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS=true
```
