### ISSUE TITLE
Pass Env vars to service imagse

### ISSUE THREAD

**Issue by zelo** [drone/drone#861]
It would be great to have ability to pass env variables to services images in .drone.yml.

e.g. I wanted to use `library/postgres:9.4` as database `service` and pass `POSTGRES_USERNAME` and `POSTGRES_PASSWORD` env variables to image run command.

As far as i know drone currently doesn't support such action.

**Comment by bradrydzewski** [comment]
I've been thinking about this quite a bit. I think the path forward is to take all environment variables (in the `env` section of the yaml) and pass them into all containers.

Let's say we have the following `.drone.yml`

```
image: go
services:
  - library/postgres
env:
  - FOO=BAR
  - POSTGRES_USERNAME=root
  - POSTGRES_PASSWORD=""
```

All three environment variables would get passed into the Go container and also to the Postgres container. This keeps are yaml syntax simple, doesn't introduce any breaking yaml changes, but is still flexible enough for the use case that you described.

**Comment by zelo** [comment]
I agree this was my first try when i tried to pass env variables to those service containers.

**Comment by bradrydzewski** [comment]
capability added in 0.4 branch (for upcoming release) as part of #902 to make the `.drone.yml` more flexible
