### ISSUE TITLE
Error when running drone from deb - 0.3.0-alpha-1423116857

### ISSUE THREAD

**Issue by jvliwanag** [drone/drone#867]
On drone installed via deb on an ubuntu 14.10 machine, deb version 0.3.0-alpha-1423116857, visiting the site results to:

```
2015/02/05 10:30:53 http: panic serving 127.0.0.1:40439: read /usr/local/bin/droned: bad file descriptor
goroutine 36 [running]:
net/http.func·011()
	/usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0xa997c0, 0xc20809b500)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/GeertJohan/go%2erice.(*Box).MustBytes(0xc208111a10, 0xbf7090, 0xa, 0x0, 0x0, 0x0)
	/var/cache/drone/src/github.com/GeertJohan/go.rice/box.go:298 +0xc0
main.func·001(0x7f40b6d7ba10, 0xc208044c80, 0xc208108820)
	/var/cache/drone/src/github.com/drone/drone/server/main.go:133 +0x3d
net/http.HandlerFunc.ServeHTTP(0xc2080362a0, 0x7f40b6d7ba10, 0xc208044c80, 0xc208108820)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc208022930, 0x7f40b6d7ba10, 0xc208044c80, 0xc208108820)
	/usr/local/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc208005c20, 0x7f40b6d7ba10, 0xc208044c80, 0xc208108820)
	/usr/local/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208050980)
	/usr/local/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/local/go/src/pkg/net/http/server.go:1721 +0x313

```

The same machine used to run an older 0.3.0 alpha just fine. Also tried it on a new machine.

**Comment by ryanharper** [comment]
Yeah same for me, it was working fine on the previous version

**Comment by jvliwanag** [comment]
Something wrong with serving the static files. Note that

Running `packaging/root/usr/local/bin/droned` from the build output yields the same error for static files. API calls work fine.

**Comment by jvliwanag** [comment]
In particular the `rice` commit GeertJohan/go.rice@9fe3e28736b95 seemed to have broken it. Reverting `rice` to an earlier version fixes drone. Since I don't `go`, I'm not certain if this is a problem with `drone` or `rice`.

**Comment by bradrydzewski** [comment]
@jvliwanag definitely seems to be an issue with `go.rice`. Can you see if it is just the `index.html`? Or does it also fail to load other static files like `/static/styles/drone.css`? Just trying to get more details so I can open an issue with the `go.rice` team. Unfortunately I'm not on my laptop, so my ability to troubleshoot today is limited :/

**Comment by jvliwanag** [comment]
`/static/styles/drone.css` is served fine. But those at the root: `index.html`, `favicon.png`, `favicon.ico` don't work.

**Comment by jvliwanag** [comment]
Sorry, scratch that. `/static/favicon.png`, `/static/favicon.ico` are ok. It's just `index.html`.

**Comment by bradrydzewski** [comment]
OK thanks, good to know! The `index.html` file is the only one that we manually write to the response:

```
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	w.Write(assets.MustBytes("index.html"))
})
```

This tells me something changed with the `MustBytes` and allows me to log a more targeted issue with the `go.rice` authors.

**Comment by jjn2009** [comment]
Ran into this problem as well. It has me wondering what the best practice is for version pinning in golang for github commits/releases, or if it's possible.

nodejs's package.json allows: "github.com/user/project#commit"

**Comment by bradrydzewski** [comment]
There is no official solution for versioning, however there are some third party tools that allow you to either a) vendor dependencies and b) lock revisions:
https://code.google.com/p/go-wiki/wiki/PackageManagementTools#Revision_Locking

We tried vendoring dependencies (Godep) a while back and it seemed to cause more problems than it solved. At the time, however, none of the revision locking solutions existed. So I definitely think there are some new options worth exploring

**Comment by bradrydzewski** [comment]
Fixed. Thanks for helping diagnose

**Comment by jjn2009** [comment]
Good to know, thanks for the overview.
