### ISSUE TITLE
Merging accounts.

### ISSUE THREAD

**Issue by teodor-pripoae** [drone/drone#885]
Hi,

I have an account made using Github connect, and one made using Bitbucket connect, both with the same email. Is there any option to merge this 2 accounts, in order to have an unified dashboard ?

**Comment by patrickjahns** [comment]
I second this

**Comment by mnbbrown** [comment]
This would be super useful. I host most of my public repositories on Github and my private repos on Bitbucket. Happy to help make this possible as well!

**Comment by bradrydzewski** [comment]
I'm closing this because Drone 0.4 no longer supports multiple integrations. Unfortunately supporting multiple accounts is a non-trivial breaking change going forward that we don't plan to implement
