### ISSUE TITLE
Plugin for Mercurial

### ISSUE THREAD

**Issue by declension** [drone/drone#893]
To my dismay I realised whilst Bitbucket _is_ supported, it's only for Git repos, so I can't use Drone without converting entire repos.  :(

There even seems to be [a TODO for HG/SVN support](https://github.com/drone/drone/blob/8d493b393c8a03ca1eda5d4574875770cfd3a1dd/shared/build/repo/repo.go#L102), and a [note about Git-only support for Bitbucket](https://github.com/drone/drone/blob/38379992bf1c82aae0e7eed94f640bc630bc9eef/plugin/remote/bitbucket/bitbucket.go#L145).

Any idea when this will be available (or even: clues about hacking this in (for a non-Go dev))?

**Comment by bradrydzewski** [comment]
The good news is that it is something we are actively working on. There are a few different proposals / ideas that we are testing out, and even a working pull request. Making the system more pluggable is a bit tricky, so we are definitely taking our time and exploring all of our options before we commit to an approach.

**Comment by declension** [comment]
@bradrydzewski thanks for the update, and yes I see #793 now: +1 to that definitely

**Comment by bradrydzewski** [comment]
I wanted to provide a quick update here. I recently merged a pull request that tracks the `scm` field for each repository. This is typically set to `git`, however, for bitbucket repositories this will be set to `hg`.

I also have a placeholder for a mercurial plugin:
https://github.com/drone-plugins/drone-hg

If someone is willing to create the mercurial plugin (see the [git](https://github.com/drone-plugins/drone-hg) plugin for reference) we can close out this issue, and mercurial will be officially supported. Hopefully we can find a volunteer.

**Comment by bradrydzewski** [comment]
closing now that mercurial is supported
https://github.com/drone-plugins/drone-hg
http://readme.drone.io/plugins/hg/


using the mercurial plugin requires the clone block in the yaml is configured appropriately:

```
clone:
  image: hg
  path: bitbucket.org/foo/bar
```

**Comment by declension** [comment]
Thanks!
