### ISSUE TITLE
RFC: store ref in commit table, enables tags

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#895]
I propose we start storing `ref` field with the commit record. This is a better way to uniquely identify commits, pull requests, branches, tags, etc. This is a pre-requisite if we want to support building, testing, and deploying tags.

The commit+ref is a much better unique identifier than commit+branch:

```
cd1fed3d5344d49f1e913f9b6c03ebd2296f8855 refs/heads/master
c3966b1a59b542e3337b02e05819a918d0fd444e refs/heads/matrix
4c7cd974219774b380820171e39b94f2a15da49d refs/tags/v0.2.0
55a99f1ebc45766ca31d197f6009e7a25b7e55f5 refs/tags/v0.2.1
8d6a233744a5dcacbf2605d4592a4bfe8b37320d refs/pull/877/merge
```

### database changes

We could image a database change like this:

```diff
var commitTable = `
CREATE TABLE IF NOT EXISTS commits (
	 commit_id         INTEGER PRIMARY KEY AUTOINCREMENT
	,repo_id           INTEGER
	,commit_status     VARCHAR(255)
	,commit_started    INTEGER
	,commit_finished   INTEGER
	,commit_duration   INTEGER
+	,commit_ref        VARCHAR(255)
	,commit_sha        VARCHAR(255)
	,commit_branch     VARCHAR(255)
	,commit_pr         VARCHAR(255)
	,commit_author     VARCHAR(255)
	,commit_gravatar   VARCHAR(255)
	,commit_timestamp  VARCHAR(255)
	,commit_message    VARCHAR(255)
	,commit_yaml       BLOB
	,commit_created    INTEGER
	,commit_updated    INTEGER
+	,UNIQUE(commit_sha, commit_ref, repo_id)
-	,UNIQUE(commit_sha, commit_ref, repo_id)
);
`
```

**important** the actual implementation will differ from above. We will need to ensure that we can migrate older versions of Drone. Therefore we should probably `drop` and then `add` the unique index. We should also populate the `commit_ref` field for older records before adding the unique index.

### rest changes

We may need to update the restful API accordingly. Let's figure out a strategy here before we proceed. I'm not quite sure how we want to represent this in the URL.

**Comment by Bugagazavr** [comment]
:+1:

**Comment by bradrydzewski** [comment]
https://github.com/gin-gonic/gin

I think we'll end up altering the routes to look something like this:

```Go
mux.Get("/:host/:owner/:name/commit/:sha/:ref(.+)") // get commit details
mux.Get("/:host/:owner/:name/log/:sha/:ref(.+)")    // get commit docker log
```

a live example:

```
/github.com/drone/drone/commit/cd1fed3d/refs/heads/master
```

**Comment by bradrydzewski** [comment]
ended up implementing build numbers. I liked that the URLs had the commit and ref, since they matched github. This unfortunately limited our ability to do things like support github [deployment API](https://developer.github.com/v3/repos/deployments/)

so now it looks like this:

```
mux.Get("/:owner/:name/:number")
```
