### ISSUE TITLE
empty page on GitHub login redirect

### ISSUE THREAD

**Issue by JeanMertz** [drone/drone#905]
I've setup a local Drone environment for Docker image testing. I'm able to login and work with the interface.

A colleague of mine tried to login as well, but gets stuck on a redirect happening after initial login on GitHub.

The redirect URL is as follows (changed the keys):

`http://ourdrone.com/api/auth/github.com?code=26314215f822zadcc8ebe&state=HLISSI2IG44RPACYZ6IJM55ZL63N7IUAONPHI3HNZAGSTRGN52NQ%3D%3D%3D%3D`

After the white page, we checked GitHub and Drone is actually authorised on his account. We also tried logging in again, this time GitHub redirected right away (due to already given access), but still a white page came up.

Our drone instance is configured like this:

```
[github]
client = "xxx"
secret = "xxx"
orgs = ["blendle"]
```

**Comment by JeanMertz** [comment]
D'oh, should have checked the container logs first:

```
2015/03/04 09:28:12 Error matching state in OAuth2 redirect
2015/03/04 09:28:23 Unable to create account. Registration is closed
```

I guess setting `open` to `true`, but keeping the `orgs` option will only open up registration for our own organisation?

**Comment by bradrydzewski** [comment]
Yes, you have a few different options. The first option is open registration, restricted to members of an organization (by setting `open` and `orgs` variables in config file). The section option is set `open` to false, and to manually grant access to users via the User admin screen.

Regarding the error message (or lack therefore) let's move the discussion to #660
