### ISSUE TITLE
Report tabs

### ISSUE THREAD

**Issue by andy-inc** [drone/drone#907]
Do you think about report tabs for each build, like tests results, coverage or some custom pages generators? Teamcity can take some files by glob mask and you may create report tabs for any of this files. For example `istanbul` create folder with result as html, you can take it back and display in tab of build. And this way can provide a lot of custom reports.

**Comment by bradrydzewski** [comment]
yes definitely something we want. We are first focused on a creating a generic plugin model as the first step. Once we have a generic plugin model in place we can explore a generic way to extract, store and serve reporting data. 

Let's track this feature under #440 and #239
