### ISSUE TITLE
Long commit message causes postgres insert error

### ISSUE THREAD

**Issue by logan** [drone/drone#914]
The postgres schema for commits uses VARCHAR(255) for the message. If the commit message exceeds this length, then an error occurs trying to commit the commit to the DB.

By the way, the error handling in the hook handler leaves a lot to be desired. A lot of these 400s really should be 500s, and all of them discard the error string instead of logging or returning it, leaving us guessing as to the cause.

**Comment by tboerger** [comment]
https://github.com/drone/drone/blob/master/store/datastore/ddl/postgres/1_init.sql#L49-L73 seems to be solved on 0.5?

**Comment by thomasf** [comment]
Always `text` fields, `varchar` should only be used to validate text types which has a known maximum length.     
Looking at the migration sql files it seems that many `varchar` columns which probably should be `text`

**Comment by bradrydzewski** [comment]
I think putting limits on column size is a good thing. We don't want to accept a hook with a 1GB commit message for example.

**Comment by thomasf** [comment]
The kind of validation you are talking about now should probably be done before parsing a request using maximum "request" size check while or before reading.. 

I guess having the database do some checks as well isn't too bad, I see that you also truncate the message if it's too long..
