### ISSUE TITLE
Vagrant provisioning broken

### ISSUE THREAD

**Issue by matthewkmayer** [drone/drone#915]
The Vagrant file isn't bringing up the system as expected.  Steps to repro:

```bash
git clone git@github.com:drone/drone.git
cd drone
vagrant up
```

Results: 
```
==> ubuntu: make: 
==> ubuntu: *** [deps] Error 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Drone doesn't appear to have installed.  After connecting via `vagrant ssh`, there's no drone process running and upstart doesn't know about it:

```bash
sudo status drone
status: Unknown job: drone
```

Not sure if this is related, but there appears to be something wrong with an earlier step:

```bash
==> ubuntu: Building Drone
==> ubuntu: go get github.com/GeertJohan/go.rice/rice
==> ubuntu: go get -t -v ./...
==> ubuntu: code.google.com/p/goauth2 (download)
==> ubuntu: github.com/andybons/hipchat (download)
==> ubuntu: github.com/codegangsta/cli (download)
==> ubuntu: github.com/docker/docker (download)
==> ubuntu: github.com/Sirupsen/logrus (download)
==> ubuntu: package code.google.com/p/goauth2/oauth
==> ubuntu: 	imports github.com/andybons/hipchat
==> ubuntu: 	imports github.com/codegangsta/cli
==> ubuntu: 	imports github.com/docker/docker/pkg/archive
==> ubuntu: 	imports github.com/Sirupsen/logrus
==> ubuntu: 	imports github.com/docker/docker/pkg/parsers
==> ubuntu: 	imports github.com/docker/docker/pkg/stdcopy
==> ubuntu: 	imports github.com/docker/docker/pkg/term
==> ubuntu: 	imports github.com/docker/docker/utils
==> ubuntu: 	imports github.com/docker/docker/autogen/dockerversion
==> ubuntu: 	imports github.com/docker/docker/autogen/dockerversion
==> ubuntu: 	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
==> ubuntu: 	/usr/local/go/src/pkg/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
==> ubuntu: 	/opt/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
```

Related to https://github.com/docker/docker/issues/10922 ?

**Comment by bradrydzewski** [comment]
you should be able to compile and run Drone directly on OSX or Windows. There is nothing platform specific in the codebase that I know of. You just need libsqlite3 installed and a running Docker daemon.

**Comment by matthewkmayer** [comment]
I may be confused about the purpose of the Vagrantfile then.  My assumption is it brings up a VM with Drone and its dependencies installed on it.  If this isn't correct I'll gladly make a PR to update/add documentation for it.

**Comment by davidak** [comment]
i also got the same error.

**Comment by bradrydzewski** [comment]
I believe the intention of the Vagrantfile was to assist with local development of Drone on OSX. I've never used it personally, and it always seems to be broken. I would prefer to remove it. Are you looking to run Drone? Because we have an officially support Docker image that you can run locally on OSX with boot2docker

**Comment by bradrydzewski** [comment]
@davidak that readme refers to the auto-generated drone build. We cannot cross-compile Drone (on Linux) to target OSX because of the SQLite binding. You can still build and run Drone on OSX, however.

You just need libsqlite3 installed. This may already be installed on OSX by default.

**Comment by davidak** [comment]
yes, i want to test drone without setting up a server.

the docker image was my second try. i build it using the Dockerfile. after i done that i saw i could just use `drone/drone`.
i started using `docker run -p 0.0.0.0:80:80 -t 9b9fa36dcd6a` so i can open the webinterface on the ip of the boot2docker-vm.
but now i have to edit a file on it to configure. i don't get a console, also not with `-i`. it would be nice to be able to do that in the webinterface.
it don't work with the Environment Variables set on the mac.

you could build a mac version using travis-ci until drone can do it itself :D

**Comment by bradrydzewski** [comment]
All configuration data can be passed into the container as environment variables (with docker -e flag). Check this out as an example: http://readme.drone.io/setup/config/github/

**Comment by davidak** [comment]
yeah, that works :)

`docker run -p 0.0.0.0:80:80 -t -d -e DRONE_GITHUB_CLIENT=xxxxx -e DRONE_GITHUB_SECRET=xxxxx drone/drone`

**Comment by matthewkmayer** [comment]
Any objections to removing the Vagrantfile?

**Comment by bradrydzewski** [comment]
Go for it. I'll work on beefing up the docs for running on OSX in Docker

**Comment by matthewkmayer** [comment]
All fixed up.
