### ISSUE TITLE
Display download of images in build log

### ISSUE THREAD

**Issue by davidak** [drone/drone#918]
the build log is empty for several minutes.

reason is that the image gets downloaded for the first time:

```
928b8f4c06ba: Pulling metadata
928b8f4c06ba: Pulling fs layer
928b8f4c06ba: Download complete
```

the user should to know that, like with `downloading image...`

**Comment by bradrydzewski** [comment]
The 0.4 release writes to the log when pulling an image instead of displaying a completely blank screen for minutes. Hopefully that is enough, but if not we can revisit.
