### ISSUE TITLE
Wrong build status in readme

### ISSUE THREAD

**Issue by keilw** [drone/drone#920]
Hi,
Especially in Maven multi-module projects (not sure, if that's a reason) I constantly see the status badge like https://drone.io/github.com/unitsofmeasurement/uom-tools/admin/badges
failing in the Readme:
https://github.com/unitsofmeasurement/uom-tools/blob/master/README.md
although the build is passing.

TIA,
Werner

**Comment by bradrydzewski** [comment]
this is for the open source drone repo, which is different than the drone.io service

**Comment by keilw** [comment]
Where does that have a bug tracker then?;-)
