### ISSUE TITLE
gitlab skip_verify don't work

### ISSUE THREAD

**Issue by davidak** [drone/drone#923]
i have a problem with gitlab. our server has a self signed certificate.
so i set `skip_verify=true` but get this message:
`2015/03/18 13:27:33 Error exchanging token. Post https://our.gitlab-server.de/oauth/token: x509: certificate signed by unknown authority`

@Bugagazavr said it is a problem with oauth.

**Comment by jumbojett** [comment]
+1

**Comment by daMupfel** [comment]
For now to get around this you can try to add your self signed certificate to the accepted root certificates or ca certificates on your systems Certificate Store as i mentioned in gitter.

Hope that helps!

Regards

**Comment by jumbojett** [comment]
Thanks @daMupfel. Can you paste a link to the gitter chat for reference?

**Comment by daMupfel** [comment]
Their was not more information on my gitter comment. It's different for os's.

**Comment by bradrydzewski** [comment]
yep, I'm not sure there is anything we can do in Drone other than documenting the issue and steps to install the root ca on a linux machine. If someone can send me a write-up of the required steps I'm happy to add to our docs.

**Comment by davidak** [comment]
the tutorial works for ubuntu 14.04. i had to restart drone after that.

```
Given a CA ceritificate file 'foo.crt', follow these steps to install it on Ubuntu:

Create a directory for extra CA certificates in /usr/share/ca-certificates

sudo mkdir /usr/share/ca-certificates/extra
Copy the '.crt' file to the directory

sudo cp foo.crt /usr/share/ca-certificates/extra/foo.crt
Let Ubuntu add the '.crt' file's path relative to /usr/share/ca-certificates to /etc/ca-certificates.conf

sudo dpkg-reconfigure ca-certificates
```

**Comment by daMupfel** [comment]
Looks like the one that i linked above. Would be nice to have more. I actually did not get this to work on osx (by adding it to the system keystore). So I am happy if someone has a solution.

**Comment by davidak** [comment]
@daMupfel it is the 1. answer from your linked question.

did you try something like this: http://wiki.cacert.org/FAQ/ImportRootCert#Mac_OS_X

**Comment by brunowego** [comment]
Thanks @davidak :+1:
