### ISSUE TITLE
Drone Status API

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#927]
We should have a Drone status API that allows 3rd party system to annotate commits and link back to those 3rd party systems. This would be similar to the GitHub status API.

An example use case would be a coverage system. A coverage system would store detailed coverage metrics, but could provide Drone with a high-level status and link to those detailed coverage reports.

This came out of #239

**Comment by DavidJFelix** [comment]
Just an FYI: https://github.com/badges/shields/issues/294 would really love this.

**Comment by pine613** [comment]
:+1:

**Comment by cooperaj** [comment]
Would have liked to see this implemented. It'd be the only way to tie external services to the drone UI. Using a testresults or coverage 3rd party component is fine but with no way to actually link to a particular build the UX is going to be pretty poor.

**Comment by bradrydzewski** [comment]
Coverage, test results, code quality, and links to external artifacts will be added natively to drone. Drone will provide an API for plugins to send this data back to drone during the build.

**Comment by dwilhel1** [comment]
Is this still being worked on? Is there another issue tracking progress?

**Comment by bradrydzewski** [comment]
We decided not to pursue native reporting in Drone. We instead recommend using Coveralls / Codecov for coverage, Artifactory / Sonatype Nexus / Archiva for artifacts, and tools like Hound / Codacy / Sonarqube / etc for code quality. Many of these tools already have [plugins](http://plugins.drone.io) for Drone.
