### ISSUE TITLE
Please communicate with us about releases

### ISSUE THREAD

**Issue by thieman** [drone/drone#928]
It's now been more than a year since `0.2` was released.

Your milestones page doesn't make any sense to me, given that no `0.3` release has happened. How can `0.3` through `0.3.3` be completed if this is the case? https://github.com/drone/drone/milestones?state=closed

I like Drone, but we are hitting a load of annoying `0.2` bugs that I'd really like to get rid of. The project is clearly very actively developed, it seems totally non-sensical to not be doing releases.

**Comment by floatdrop** [comment]
@thieman `0.3` release was announced in blog quite a while ago - http://blog.drone.io/post/drone-0.3-gitlab-bitbucket-slack/

**Comment by thieman** [comment]
So the official recommendation is still just to grab an arbitrary commit and push that to production? That doesn't really match the definition of a release for me.

Also, I promise I'm not trying to be a jerk here, but stuff like this can be really frustrating, claiming 5 months ago that more information would be coming in "a few weeks," but no real updates since then: https://github.com/drone/drone/commit/42979c55039e2bdd2a5e844aaa51f8ebb537b29d

**Comment by floatdrop** [comment]
@thieman oh, I didn't read blog post well, sorry. It was not release announcement, but status update.

**Comment by bradrydzewski** [comment]
the 0.3.* milestones were cleared out because there will not be an official 0.3 release. We are making significant (backward incompatible changes) to the yaml format to support matrix builds and change to the build process to support plugins. I don't want to encourage people to upgrade to 0.3 since it will soon be obsoleted and not supported, so instead we are going straight to 0.4

**Comment by thieman** [comment]
Thank you for the clarification. I'm sure you have your reasons for everything, it's just as the person taking the flak for the bugs in my organization it's always helpful to go into a conversation armed with as much knowledge as possible. :sweat_smile: 

Would it be possible to make this release plan publicly accessible somewhere so people know about it? Or did I just miss where this was announced previously?

**Comment by daMupfel** [comment]
Can we please document this somewhere? Because for new people it really can be extremely confusing. Another thing is that we still reference v0.2 info about .drone.yml.

**Comment by bradrydzewski** [comment]
Yes, I'll work on some sort of blog post to discuss project milestones and direction. I'm moving the matrix code out of drone-cli into the drone core right now, hopefully I'll have something to show this weekend. Depending on progress we may be better off documenting the new yaml, but let's discuss

**Comment by pikeas** [comment]
+1, would love to hear some details on version 0.4. Roadmap? ETA for first alpha?

**Comment by bradrydzewski** [comment]
thinks I'd like to tackle in 0.4 are here: https://github.com/drone/drone/milestones/v0.4.0

**Comment by bradrydzewski** [comment]
There are many big and complex features, so it is difficult to provide any sort of accurate ETA. Also this project is by no means heavily staffed ... it is just me + community contributions :)

**Comment by bradrydzewski** [comment]
But I will do my best as I have things to share.

I am currently working on data-modeling before I continue coding. We need data model changes to support matrix builds, but also to support pull requests on non-GitHub systems. We've found that GitLab and Bitbucket, for example, require cloning pull requests from the sending repository which means we need to store extra meta data with each commit. Our data structure is currently flat and doesn't lend itself well to a data structure that is becoming more hierarchical.

I am also re-thinking how we handle 3rd party service integration (ie GitLab, Bitbucket, etc). It is not practical to support every possible 3rd party in the Drone codebase, however, I don't want to be the gatekeeper saying which 3rd party services Drone can and will integrate with. I am trying to design a plugin model for 3rd party systems so Drone can integrate with any system without having to send a pull request.

So those will probably keep me busy for the next week. Hopefully that helps. I'm open to suggestions for broadcasting my status so people can see exactly what I'm working on

**Comment by pikeas** [comment]
@bradrydzewski Thanks for the update! I know ETAs are hard, no one is going to break down your door if things take longer than expected. I've been interested in Drone for a while, but have been waiting for it to settle down a bit before using it.

So any estimate you can give us for 0.4 (one month, six months) is better than no estimate!

**Comment by bradrydzewski** [comment]
weekly status updates are now being published, and include detailed progress reports for upcoming releases https://discuss.drone.io/t/weekly-update-12-may-2016/236
