### ISSUE TITLE
Add io.js and Node.js v0.12 support

### ISSUE THREAD

**Issue by yosuke-furukawa** [drone/drone#931]
Node.js has v0.12, and io.js has been released.
I would like to add these environments.

**Comment by bradrydzewski** [comment]
we are deprecating the official drone images in favor of the official docker images (language stacks). Recommended to use `image: library/iojs` as your build image (note: until 0.4 is released you'll need to include `library/` in the image name

**Comment by RIAEvangelist** [comment]
when will this functionality be available on the hosted service?
