### ISSUE TITLE
Pull requests with more than 1 commit break the tests

### ISSUE THREAD

**Issue by jvortmann** [drone/drone#933]
Sending a suggested change on #911 break the test because there is more than 1 commit on the pull request. This made me open another pull request #932, cherry pick only the last change. This made the test pass.

Is this really how it should work? Here is the test result for que PR with 2 commits:

http://test.drone.io/github.com/drone/drone/check_presence_socat_anywhere_in_path/0d36b85e65b51f9820825de360f21b56c0ab7599

**Comment by bradrydzewski** [comment]
pull requests with > 1 commit works fine. There is a single postgres unit test that (for some reason) is non-deterministic and occasionally fails

**Comment by jvortmann** [comment]
@bradrydzewski thanks! I thought it was related to some test setup of postgres and not actually on the code and/or Drone itself. As I was unable to re-run the build, I sent only the other commit to a new PR.

How can we re-run the tests for a PR that shows the same behavior? Should we just point it out?

**Comment by bradrydzewski** [comment]
yep, until I have a permanent fix you can just ask :)

I think going forward we should allow the committer to re-run a failed pull request, even if he / she is not granted access to the repository. We don't track the necessary data (yet) in the database, but I'll look at adding
