### ISSUE TITLE
separate own repos and repos of organisations

### ISSUE THREAD

**Issue by davidak** [drone/drone#934]
i am in one organisation with about 80 repos and i contribute to 3 of them, so the rest disturbs me, especially when i search for one of my own repos.

it should be organized in

- own repos
- organisation 1
- organisation 2

**Comment by bradrydzewski** [comment]
also related is this:
https://github.com/drone/drone/issues/776

Today we automatically sync and build your list of repositories, which as you mention adds repos to your dashboard that you may not care about. We need to move away from syncing (for a variety of reasons) to something more on-demand, which I believe will help solve this problem as well.

**Comment by bradrydzewski** [comment]
closing as this doesn't really apply to the new 0.5 design and layout, although we do have organization filtering where appropriate.

<img width="1324" alt="screen shot 2016-06-08 at 3 14 30 pm" src="https://cloud.githubusercontent.com/assets/817538/16749274/e9d18e5e-477d-11e6-8635-ce5a20989906.png">
