### ISSUE TITLE
Using nginx to proxy to drone causes wrong redirect

### ISSUE THREAD

**Issue by SerialVelocity** [drone/drone#936]
Hey,

I've set up a bitbucket configuration for drone.
I currently forward all data from the encrypted port 443 on my subdomain to an unencrypted port used by drone internally. Unfortunately, this means that I'm getting forwarded to "/api/auth/bitbucket.org" on port 80 of my subdomain instead of to port 443.

I'm using nginx for auth and other checks so it has to go through nginx unfortunately. I hope that makes sense...

**Comment by bradrydzewski** [comment]
Please ensure you are setting `X-Forwarded-For` and `X-Forwarded-Proto` to pass along `https` so that Drone knows to correctly redirect. You can see the code and logic here that we are using:
https://github.com/drone/drone/blob/master/shared/httputil/httputil.go#L31

**Comment by bradrydzewski** [comment]
let's move this discussion to [gitter.im/drone/drone](https://gitter.im/drone/drone) and we can always re-open if we can't find a solution.

**Comment by SerialVelocity** [comment]
Hey @bradrydzewski, I've updated the title and description since it's a docs issue. Could you re-open it? I did try talking to you on gitter.im but got no response

**Comment by bradrydzewski** [comment]
can you provide a snippet that demonstrates how you resolved the issue? I can then include this in the docs

**Comment by SerialVelocity** [comment]
Sure. Just beneath:
```
    proxy_set_header X-Forwarded-For $remote_addr;
```
I put:
```
    proxy_set_header X-Forwarded-Proto $scheme;
```

It should work for both http and https.

I also had to do this (but not sure whether it should be in the docs:
```
        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header Origin "";

            proxy_pass http://127.0.0.1:8000;
            proxy_redirect off;
        }

        location /api/stream {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header Origin "";

            proxy_pass http://127.0.0.1:8000;
            proxy_redirect off;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

**Comment by bradrydzewski** [comment]
thanks, much appreciated. I updated the docs and the latest version should be auto-deployed shortly
