### ISSUE TITLE
Cannot disable gitlab repo.

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#937]
I cannot disable any gitlab repo on my drone account:

    drone disable git-server.de/nils/python-skeleton

does nothing, does not return anything, does not show any effect either. same with

    drone delete git-server.de/nils/python-skeleton

however

    drone status git-server.de/nils/python-skeleton

shows me the status of the last build.

**Comment by bradrydzewski** [comment]
the disable endpoints have changed in Drone to /github.com/foo/bar/deactivate. Are you using the latest client (now found at https://github.com/drone/drone-cli) and the latest server?

there is no expected output from the command line. The program either exits with 0 or 1 depending on if the operation failed. You can run `echo $?` to see the exit code of the last executed shell command.

Note that deactivating sets the following flags:
	repo.Active = false
	repo.PullRequest = false
	repo.PostCommit = false

Deactivating worked for me. So please try the above suggestions. If those don't work and you've found an edge case we can re-open.

**Comment by nils-werner** [comment]
I have drone installed, it comes with a `drone` program... Am I supposed to install both drone and drone-cli? What is the drone executable for then?
