### ISSUE TITLE
Drone - Build failed -Maximum Build time exceeded..

### ISSUE THREAD

**Issue by ShaliniMendu1** [drone/drone#940]
Drone build failed with the message 'Maximum build time exceeded' after 15minutes. How can i increase the build time in drone? I  could not find any setting in drone to set the build time. Please help.

**Comment by bradrydzewski** [comment]
the Drone administrator can go to the repository settings screen (in Drone) and has the option to increase the timeout (see the timeout field)

**Comment by ShaliniMendu1** [comment]
Thanks Brad. I had seen the same comment when i was trying to find the solution but could not see this option. I also read somewhere that this option is no more available now. To tell you the background, I logged into Drone using bitbucket credentials and i explored all the options under settings tab, but was not able to find anything related to Timeout. It took hours to decide on a CI and i have made good progress with Drone except for the timeout issue, Please help me resolve.

**Comment by ShaliniMendu1** [comment]
Who is a Drone administrator? Do i not become an administrator when i login using Bitbucket credentials? Do i have to go under a plan for me to see this option?Let me know

**Comment by bradrydzewski** [comment]
ah ok, that makes sense. This open source project is not the same as the `drone.io` service. The `drone.io` service limits the free tier to 15 minute per build.

**Comment by ShaliniMendu1** [comment]
Ok, what is the fix ? Please suggest.Can buying the license make any difference?

**Comment by ShaliniMendu1** [comment]
If i buy the 25$ plan, will there be any kind of time limit on the build, i would need around 1hour of build time.
