### ISSUE TITLE
25$plan on trial for a week!

### ISSUE THREAD

**Issue by ShaliniMendu1** [drone/drone#941]
Brad/Others,
We tried to configure our project with the free version of drone, but our build failed as it required more than 15 minutes of build time.

We would like to buy the 25$ plan of drone, but before we decide, Is it possible to try this 25$ plan for a week & see that it fixes the build time limit and works fine with everything else?
Thanks 
SHALINI

**Comment by ShaliniMendu1** [comment]
Hi Brad, 
I did not get reply to my question. Can we buy this plan for us to try for a week?

**Comment by bradrydzewski** [comment]
I'm sorry for the confusion, however this is not a support forum for the drone.io website
