### ISSUE TITLE
Access to github organization repository

### ISSUE THREAD

**Issue by venabled** [drone/drone#944]
When trying to add a repository from an open organization repository that I own, and drone.io can see, I get the following error message: 

> Unable to Setup Repository
> Unable to setup github.com/shrimped/dzmq. This most likely means you do not have permission to add build hooks or deploy keys to this repository.

**Comment by bradrydzewski** [comment]
hi there, this forum is reserved for issues with the open source codebase, which is a different product and codebase than the drone.io service. For support with the drone.io service please use `support@drone.io`
