### ISSUE TITLE
Feature request - Private hipchat support

### ISSUE THREAD

**Issue by mattbailey** [drone/drone#950]
It would be nice to be able to specify a hipchat server in the configuration for those of us with private self-hosted hipchat enterprise servers.

**Comment by davidmc24** [comment]
I would also like this.  A minimal implementation of this should just require taking where hipchat.go currently hardcodes "api.hipchat.com", and instead allow the host to be passed in.  The API for the SaaS and privately hosted HipChat products are exactly the same.

**Comment by bradrydzewski** [comment]
closing. merged pull request to add this functionality a while back
