### ISSUE TITLE
Database Changes for 0.4

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#957]
This is a meta-issue that is used to describe overall data storage changes. Individual tasks will be split into a series of separate issues.

---

In order to facilitate matrix builds and pull requests for systems like Bitbucket and Gitlab we'll need to heavily modify our data structure. This is also a good time to re-evaluate this tier of the application and see what improvements can be made.

## Document Oriented

We currently have a very flat data structure. I'd like something a bit more document oriented that allows us to store data in nested structures. Here is how we could represent the build of a Commit:

```js
{
  "number": 1,
  "started_at": "2011-01-26T19:06:43Z",
  "finished_at": "2011-01-26T19:07:43Z",
  "duration": 100,
  "state": "success",
  "commit": {
    "sha": "c5b97d5ae6c19d5c5df71a34c7fbeeda2479ccbc",
    "ref": "master",
    "message": "Merge pull request #6 from Spaceghost/patch-1",
    "author": {
      "name": "The Octocat",
      "login": "octocat",
      "email": "octocat@nowhere.com"
    }
  }
}
```

This is how we could represent the build of a Pull Request:

```js
{
  "number": 1,
  "started_at": "2011-01-26T19:06:43Z",
  "finished_at": "2011-01-26T19:07:43Z",
  "duration": 100,
  "state": "success",
  "pull_request": {
    "number": "6",
    "title": "new feature",
    "body": "Please pull these awesome changes",
    "source": {
      "sha": "c5b97d5ae6c19d5c5df71a34c7fbeeda2479ccbc",
      "ref": "my-feature-branch",
      "remote": {
        "clone_url": "https://github.com/octocat/Hello-World.git",
        "name": "octocat",
        "owner": "Hello-World"
      },
      "author": {
        "name": "The Octocat",
        "login": "octocat",
        "email": "octocat@nowhere.com"
      }
    },
    "target":  {
      "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
      "ref": "master"
    }
  }
}
```

These align much more closely with the GitHub data structures that we receive in our post commit hooks, and play nicely with Bitbucket and Gitlab as well.

Note: a pull request contains addition details such as the source repository details, which are required for cloning pull requests in systems like Bitbucket or Gitlab that don't expose the pull request as refs in the target repo.

## BoltDB

In order to support a more flexible data model we'll need to switch from SQLite to BoltDB (embedded key value store). This means we can continue to ship with a high-performance, embedded database. As an added benefit BoltDB is written in Go which removes our CGO dependency.

See https://github.com/boltdb/bolt

## Plugin Other Databases

Some teams may prefer to use alternative databases, such as Cassandra, MongoDB, Postgres, etc. Drone will provide the ability to create database plugins to swap out implementations. This allows teams to choose the database they are most equipped to support.

Note that plugins **are not** compiled into the binary. We will provide a protocol spec that will allow Drone to interop with external databases. This protocol will be defined this week (April 12 2015). The folks at Cisco Cloud are interested in contributing a Cassandra implementation, which we can probably use as a reference implementation.

**Comment by bradrydzewski** [comment]
Sub issues #958 #959 #960 #961 

cc/ @benschumacher @npateriya

**Comment by bradrydzewski** [comment]
This is some prototype code that uses the `net/rpc` package to interop with an external services over a tcp connection to perform database operations:
https://github.com/drone/drone/blob/bolt/datastore/rpc

You can read more about `net/rpc` here:
http://golang.org/pkg/net/rpc/

This implement the client / plugin code only. There would be an rcp server listening on the other end processing requests.

I added this code to demonstrate how we might implement this feature. We should probably evaluate performance of the `net/rpc` package vs `http` with `json` / `bson` / `msgpack` to understand the performance implications. If performance is comparable we may want to choose `http` + `json` (or whatever) as opposed to a Go-specific solution to support plugins written in other languages.

**Comment by benschumacher** [comment]
This makes sense to me. If the data being stored isn't binary, `http` + `json` has some obvious compatibility benefits. For example, without over complicating configuration, it might be possible to make the API compatible with Orchestrate.io's REST-based API for JSON document storage. It would provide relatively straight-forward semantics for building additional "pluggable" datastores.

**Comment by bradrydzewski** [comment]
![screen shot 2015-04-08 at 12 00 24 pm](https://cloud.githubusercontent.com/assets/817538/7053052/4d3b11ce-dde7-11e4-83c9-546d3a82c7e1.png)

**Comment by benschumacher** [comment]
re: the relationship between User and Repo -- is this relationship intended to be 1:n (which is what you indicated in the graphic), or is it more like M:N. I suppose what I'm trying to figure is this...

Assume two users, Alice and Bob, are part of the organization SuperAppMaker. I think this is the user case I'm trying to figure out:

  1. Alice creates Drone account
  2. Alice creates builds: `github.com/SuperAppMaker/app1`
  3. Drone creates Repo `github.com/SuperAppMaker/app1`
  4. Bob creates Drone account

A few quick questions:

* Do we expect Bob to get access to the build created by Alice?
* Is Drone going to get into the (highly complex) business of ACLs, or are we sticking with the simple `Owner` concept that the schema currently implies?
* Can Bob create his "own" build for the Repo `github.com/SuperAppMaker/app1`?

**Comment by bradrydzewski** [comment]
@benschumacher good questions, let me try to clarify. We can jump on a call if you want to discuss further --

The user->repo relationship in the database does not signify ownership or permissions. Instead, it signifies a user has "starred" (or is watching) a repository and that it should be displayed on their dashboard. This prevented a common issue where a user may have access to 100+ repositories, but only wanted to see a subset on their dashboard.

The permissions are actually no longer stored in the database. We fetch them on-the-fly so that we no longer need to sync with the remote system, which was really complex and error prone:
https://github.com/drone/drone/blob/bolt/server/repos.go#L275

The only exception (and this exists in 0.3 as well) is that we store a reference to the user that created the repository. We do this because we need this user's access token when doing things like updating the GitHub pull request status, fetching the yaml file from the repository, etc. We store this reference in the Repo object here: https://github.com/drone/drone/blob/bolt/common/repo.go#L23

> re: the relationship between User and Repo -- is this relationship intended to be 1:n (which is what you indicated in the graphic), or is it more like M:N. I suppose what I'm trying to figure is this...

Yes, we should probably track the reverse index (of users ids) so that we can fetch which users are watching a repository. There is a bucket / stub for this:
https://github.com/drone/drone/blob/bolt/datastore/bolt/repo.go#L105

> Do we expect Bob to get access to the build created by Alice?

Yes, since we check on the fly.

The repository, however, will not be automatically added to the Bob's dashboard unless they "watch" it. There is a "watch" button in the user interface as well as an API call for this: https://github.com/drone/drone/blob/bolt/server/repos.go#L260

> Is Drone going to get into the (highly complex) business of ACLs

Nope :)

> Can Bob create his "own" build for the Repo github.com/SuperAppMaker/app1?

a build is created by a post-commit hook, so technically speaking neither Bob nor Alice will be able to create a build. A build is equivalent to a commit in the 0.3 codebase

**Comment by benschumacher** [comment]
Got it. Just trying to finish up #959, and got a little confused by the model. I think what hung me up was trying to understand why `SetRepoNotExists` (https://github.com/drone/drone/blob/bolt/datastore/bolt/repo.go#L94) required the `common.User`.

I suppose if I'd followed the code a little closer, I would seen what implementation is doing -- we're only using the `common.User` in the `bucketUserRepos`, and it isn't part of the `common.Repo` at all.

> Yes, we should probably track the reverse index (of users ids) so that we can fetch which users are watching a repository. There is a bucket / stub for this:
> https://github.com/drone/drone/blob/bolt/datastore/bolt/repo.go#L105

I could see the utility of this index for cleanup -- is there another purpose you have in mind? The more of these we add, the more difficult it becomes to ensure coherence when we're working against an external datastore. Honestly, I think some sort of "garbage collection" process might be necessary at some point, anyhow, so it might be useful to consider where we can live with eventual consistency from the start.

**Comment by bradrydzewski** [comment]
> I could see the utility of this index for cleanup -- is there another purpose you have in mind?

Completely agree, cleanup was the primary use case I was considering as well.

> Honestly, I think some sort of "garbage collection" process might be necessary at some point, anyhow, so it might be useful to consider where we can live with eventual consistency from the start.

We could do some interesting stuff here. One example could be triggering garbage collection when a post-commit hook is received (maybe not every time, but we could pick some interval).
