### ISSUE TITLE
Database: Unit Testing

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#958]
we should have very high test coverage for our data storage tier:
https://github.com/drone/drone/tree/bolt/datastore/bolt

these are some reference tests:
https://github.com/drone/drone/blob/bolt/datastore/bolt/user_test.go

let's add tests for all functions

**Comment by oliveiradan** [comment]
As we have lots of changes in task.go and repo.go, the unit test files were rewritten to match the function names and also, using Goblin framework instead of Convey. It also passed initial tests in my system, but I will check with you if we are missing anything else.
