### ISSUE TITLE
RethinkDB support

### ISSUE THREAD

**Issue by Zolmeister** [drone/drone#962]
Please add support for [RethinkDB](http://rethinkdb.com/) for the hosted version of  drone
https://registry.hub.docker.com/u/library/rethinkdb/

**Comment by bradrydzewski** [comment]
Drone can use any Docker image from the index, so this should be supported today. Just update your `.drone.yml` as follows:

```
services:
  - library/rethinkdb
```

**Comment by Zolmeister** [comment]
@bradrydzewski I'm a bit confused, the docs (http://docs.drone.io/) say nothing of a `.drone.yml` file
Is this only available on `test.drone.io` and if so, when is the planned release?

**Comment by Zolmeister** [comment]
@bradrydzewski bump

**Comment by daMupfel** [comment]
Docs for the open source drone project can be found here: http://readme.drone.io/setup/overview/
