### ISSUE TITLE
Run one build on two CPUs

### ISSUE THREAD

**Issue by alexandre-butynski** [drone/drone#967]
I don't know if it's currently possible but I want to use the full potential of my server by running a build on two CPUs. With my actual config I can run two builds simultaneously but when I have only one build running (and it is what happens most of the time) it can use only half of the power of my instance.

Can we configure Drone to launch docker container with the good configuration for that ? Maybe something like the docker config `CpuSet` ?

We have an heavy build that take 30 minutes to run, to divide it by 2 would be very great to improve the feedback loop of continuous integration.

**Comment by bradrydzewski** [comment]
hey there, agreed, we're tracking this in #902 which has a yaml file that better aligns with docker / docker compose and exposes more options

**Comment by bradrydzewski** [comment]
specifically, you can see how we'll model the yaml internally:
https://github.com/drone/drone/issues/902#issuecomment-77308459

which will expose most (eventually all) of the available configuration options:
http://godoc.org/github.com/samalba/dockerclient#ContainerConfig

I'm going to close this in favor of #902 which encapsulates this functionality. Thanks for the feedback!

**Comment by alexandre-butynski** [comment]
Thanks for your answer. I will follow the progress of this issue !
