### ISSUE TITLE
Modify REST endpoints to use build number, and support build matrix

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#975]
The 0.4 angular app and REST API are complete but the routes are a bit messy. This is my proposal to cleanup the routes and finalize our REST API:

```sh
GET PUT 	/api/user # get, update currently authenticated user
GET		 	/api/user/repos # gets all repos the user is watching
GET			/api/user/tokens
POST 		/api/user/tokens/:label  # creates a token with the given label

GET PUT POST 	/api/repos/:owner/:repo
POST 			/api/repos/:owner/:repo/watch
DEL 			/api/repos/:owner/:repo/unwatch
GET 			/api/repos/:owner/:repo/builds # gets recent builds for the repository
GET DEL POST	/api/repos/:owner/:repo/builds/:build  # delete and post will cancel, restart a build, get will return the build and all build tasks
GET 			/api/repos/:owner/:repo/builds/:build/:task # returns a specific build task
GET 			/api/repos/:owner/:repo/builds/:build/:task/logs

POST 			/api/builds/drone/drone/builds/:build/status # gets all build statuses
GET 			/api/builds/drone/drone/builds/:build/status/:label # appends a build status

POST 			/hook  # receives post-commit hook from github, etc
```

**Comment by bradrydzewski** [comment]
cc @benschumacher

**Comment by benschumacher** [comment]
I'm assuming that `:repo` will still end up being something along the lines of "github.com/drone/drone" (i.e. `:service/:owner/:name`)? This scheme seems multi-tenant friendly with that design, particularly the inclusion of `:owner` in URI.

These methods appear incorrect:

```
GET            /api/builds/drone/drone/builds/:build/status # gets all build statuses
POST             /api/builds/drone/drone/builds/:build/status/:label # appends a build status
```

The `PUT` verb indicates an overwrite of the resource at the URI. Is there a case where we might want to to do a partial update, and therefore use `PATCH` instead? In particular, it becomes relevant in the `/api/user` endpoint as I don't know that you'd want to offer a consumer the ability to overwrite the entire resource. (I fully acknowledge this is nitpick-y, but I just witnessed a recent conversation on this topic for another project. Semantically it is more correct, particularly when working with JSON payloads.)

I think the current list lacks APIs for 'admin' users. In v0.3 there was the '/api/users' endpoints:

```
GET      /api/users  # get list of current users
POST    /api/users/:service/:username  # create new :user associated with :service
```

I think something analogous will be useful in the newer version.

I'm going to ponder on this a bit more this evening. I feel like there's something I'm missing, but I can't quite find it just yet...

**Comment by bradrydzewski** [comment]
Thanks for the review!

> I'm assuming that :repo will still end up being something along the lines of github.com/drone/drone

The `:repo` slug represents the fully canonical repository name. It will include the `owner` and `name` at a minimum. We can discuss this in more detail at some point.

> The PUT verb indicates an overwrite of the resource at the URI. Is there a case where we might want to to do a partial update, and therefore use PATCH instead?

Agreed. I'll adjust accordingly

> These methods appear incorrect

Yes, not sure what I was thinking. Maybe something more like this:

```
POST  /api/repos/drone/drone/statuses/:build  # add a new status to the build
GET     /api/repos/drone/drone/statuses/:build # get a list of build statuses
```

> In v0.3 there was the '/api/users' endpoints:

Yes, sorry, forgot to include those. They would still exist and look something like the following:

```
GET     /api/users
GET     /api/users/:login
PATCH   /api/users/:login
POST    /api/users/:login
DELETE  /api/users/:login
```

I think you guys might also find the following useful, for adding API tokens to the user account:

```
POST    /api/users/:login/tokens
DELETE  /api/users/:login/tokens/:label
```

> I'm going to ponder on this a bit more this evening. I feel like there's something I'm missing, but I can't quite find it just yet...

Thanks, just let me know if you think of anything else. I've made most of the changes locally and will push the code this evening, including your suggestions.

**Comment by bradrydzewski** [comment]
I just pushed the updated REST endpoints. I'll think we'll end up tweaking the implementation a bit more, but it is a good start. I'd say 95% there.

**Comment by benschumacher** [comment]
Cool. I'll take a look at in the morning.
