### ISSUE TITLE
Refresh repository values on hook

### ISSUE THREAD

**Issue by ArildBelsvik** [drone/drone#979]
Hi

Using v 7.9.1 of gitlab (local)

Have changes all referenses to hostname in gitlab, but drone seems to still use old hostname.

Any way to make drone reload values from gitlab? Syncing is not changing the hostname.
If hostname is not a value from gitlab, any way to set it manually?

![image](https://cloud.githubusercontent.com/assets/8895450/7180381/77bfca06-e441-11e4-8861-4da68ecb1ff0.png)

![image](https://cloud.githubusercontent.com/assets/8895450/7180395/9bb666e0-e441-11e4-9c1c-5f140f31defd.png)

A

**Comment by bradrydzewski** [comment]
this is something we can easily fix in 0.4 since we started extracting the repository data from the hook. There is no way to update this in 0.3 / master however.

a temporary workaround could be updating the database manually. There is a `repos` table that stores the clone url, for example, that could be updated via sql.

**Comment by ArildBelsvik** [comment]
Thanks

Did the trick for now. Update via sync would be nice.

**Comment by donny-dont** [comment]
We've encountered a similar issue here when we did a GHE update. In ours the avatars were not updated for the repositories activated prior to the update. Also had an instance where the repository had the default branch change after activating.

**Comment by bradrydzewski** [comment]
Partial fix implemented in by https://github.com/drone/drone/commit/c3732041d532142ad84126576eaa09098547facb

When you activate a repository it automatically refreshes the repository details. You can therefore de-activate and then re-activate a repository to fetch the updated information. This will likely be considered _good enough_ for a 1.0 release.

We can revisit updating the repository details on hook in a subsequent 1.X release.
