### ISSUE TITLE
Option to specifiy the hostname/url of the drone instance

### ISSUE THREAD

**Issue by patrickjahns** [drone/drone#980]
I`ve been trying to get drone running behind an apache installation in which I only have access to .htaccess files and mod_rewrite proxy options. drone always detects the internal address (localhost) and internal port and passes it on to github/bitbucket 

So instead of using drone.domain.com drone passes localhost:PORT to the github api.

It would be great to not only have an option to specify the port for the server, but also the domainname / ip address.

(currently I use a dirty hack by hardcoding my url into /shared/httputil/httputil.go

**Comment by bradrydzewski** [comment]
@patrickjahns you'll need to set `X-Forwarded-For` and `X-Forwarded-Proto` from your proxy server for the appropriate hostname and scheme. These fields are supported by nginx, apache and others.

**Comment by bradrydzewski** [comment]
note: you can see an example config here: http://readme.drone.io/setup/misc/nginx/

**Comment by patrickjahns** [comment]
I have seen the config and I have tried every possible combination of .htaccess files I can think of - it does not work in combination with drone/go there. mod_proxy is available on the host, but I can not modify apache config files. Apache and nginx behave here differently when you can not use ProxyPass and ReverseProxyPass but are limited to mod_rewrite.

I examined the behavior of go`s net/http package by creating a small go script examining the contents for certain request parameters and X-Forwarded-For is present with my external ip, all other variables in the httputils package refer to localhost:port
