### ISSUE TITLE
HTTP 400 Error While GitHub Authentication

### ISSUE THREAD

**Issue by erayalakese** [drone/drone#983]
I'm getting error while trying to auth with GitHub. Actually this error same with Telmo's [problem](https://github.com/drone/drone/issues/679#issuecomment-68703200). But that issue closed without resolving problem.

    [server]
    port=":8001"
    ...
    [github]
    client="xxx"
    secret="yyy"
    orgs=[]
    open=true

![image](https://cloud.githubusercontent.com/assets/782514/7216251/4bb27d2a-e601-11e4-971b-7da2973d0e1d.png)
(of course using my real domain instead of *domain.com*)

I'm following these steps and getting error :

1. Browsing to http://domain.com:8001/
1. Clicking to GitHub button and redirected to Github.com
1. Allowing application and redirecting back to this url:
    `http://domain.com:8001/api/auth/github.com?code=62e5cb142fb19ad657b0&state=I6MYHH2YJVHZWXWW44WNWM4DPOZPWCEKHH4BQHCIBQDG64ZX3AOQ%3D%3D%3D%3D`
1. But it's just a blank page. Here Chrome Console logs :

![image](https://cloud.githubusercontent.com/assets/782514/7216277/677c0c46-e602-11e4-8172-64663e915415.png)

**Comment by bradrydzewski** [comment]
the auth flow has good server side logging. Check the server logs and hopefully that will help

**Comment by erayalakese** [comment]
it was because of empty **orgs** array in config file

    orgs=[]

Just commented out this line and that's all.
