### ISSUE TITLE
Remove deprecated Task APIs

### ISSUE THREAD

**Issue by benschumacher** [drone/drone#984]
Per @bradrydzewski, in the [`bolt` branch](https://github.com/drone/drone/tree/bolt), the `Task`, `TaskList` and `SetTask` methods in the datastore are deprecated and can be probably be removed. We need to make sure we aren't still using those functions anywhere else in the code.

**Comment by benschumacher** [comment]
cc @oliveiradan

**Comment by oliveiradan** [comment]
I already talked to @benschumacher and will start looking into this issue to get an idea about where these api's are being used (if/in case they still are) and replace them if that is the case.

**Comment by bradrydzewski** [comment]
@oliveiradan quick Go tip. You can try commenting out the function in the `database.go` file. This is where we define the database interface. If something in the codebase is using that function you will see a compiler error.

**Comment by oliveiradan** [comment]
Great, Thanks!

**Comment by oliveiradan** [comment]
I just tested this and was able to build the code with no problems, so I will go ahead and clean those up and then get a new PR created.
