### ISSUE TITLE
Write error message to hook response

### ISSUE THREAD

**Issue by jpillora** [drone/drone#989]
There are a lot of `w.WriteHeader(http.StatusBadRequest)` with response body in https://github.com/drone/drone/blob/master/server/handler/hook.go so when trying to debug a 400, it makes it quite difficult.

Edit: Sorry for the half post. Just learnt that Ctrl+Enter in Github issues, submits the form, where in other services it adds a new-line (explicitly not submitting)

Also, note, I can send a PR, though I wanted to check first incase this was done on purpose for security reasons.

**Comment by jpillora** [comment]
For example, it took me quite some time to figure out that my `.drone.yaml` should have been `.drone.yml`.

**Comment by daMupfel** [comment]
How would such a message look?
If .drone.yml doesnt exist it will tell you that it can't find it.
I don't think we should check misspellings.

**Comment by jpillora** [comment]
```
HTTP/1.1 400 (Bad Request)
Some: Headers

<Message goes here>
```

 If `.drone.yml` isn't found, [https://github.com/drone/drone/blob/master/server/handler/hook.go#L92-L96](it sends the above response with no message), or maybe I missing something...

No need to check spelling. Instead of doing many:
``` go
w.WriteHeader(http.StatusBadRequest)
return
```
Do

``` go
w.WriteHeader(http.StatusBadRequest)
w.Write([]byte(err.Error())) //assuming err contains the error
return
```

This would allow for debugging in Github like:

![screen shot 2015-04-24 at 12 26 39 am](https://cloud.githubusercontent.com/assets/633843/7299357/b7eff402-ea18-11e4-92b7-42622ed5b866.png)

Happy to send a PR, though wasn't sure if this was on purpose or maybe you guys were handling errors elsewhere

**Comment by bradrydzewski** [comment]
this is something we've been working on. This branch has logging and returned errors for the hook:
https://github.com/drone/drone/blob/bolt/server/hooks.go

**Comment by daMupfel** [comment]
Server side logging looks like the right solution to me

**Comment by jpillora** [comment]
@bradrydzewski awesome, looks good! I'm using Gitlab, indeed it lacks a nice admin screen for webhooks, so I just replicated the webhook in curl and this bolt branch will help.

**Comment by bradrydzewski** [comment]
writing error to hooks merged into master, so this can be closed now
