### ISSUE TITLE
How to debug wsod on github/bitbucket authentication

### ISSUE THREAD

**Issue by motin** [drone/drone#993]
Have following the installation and configuration instructions carefully, but obviously something is not correct. 

Trying to login, but some github/bitbucket users just get stuck on wsod on the following urls:
http://<myhost>/api/auth/github.com?code=12e561562e5126e5&state=LAKSDJHLDGWSDFG672683F287G378HRU8HWFEHIUSFEHU9SEF%3D%3D%3D%3D
http://<myhost>/api/auth/bitbucket.org?oauth_verifier=13123123123&oauth_token=83f7g2873rfgh2f837

Just a white screen. 403 status code. No logging to syslog. 

Also found a comment on about drone from back in january stating https://www.digitalocean.com/community/tutorials/how-to-perform-continuous-integration-testing-with-drone-io-on-coreos-and-docker "This thing is useless. The github authentication is not working and there is no way to debug why is not working."

Logging out from bitbucket/github and using some other users has worked, but for instance my personal github account has never worked. 

Please make it possible to know why it won't work.

**Comment by motin** [comment]
Found relevant information to debug here: https://github.com/drone/drone/issues/389

The drone log is found in ´/var/log/upstart/drone.log´ (and not in /var/log/drone which is implied after [searching for "drone.log" in this repo](https://github.com/drone/drone/search?utf8=%E2%9C%93&q=drone.log))

It mentioned "Unable to create account. Registration is closed" and thus it was easy to find the reason (needed open=true or register the accounts beforehand).

Would it be too insecure to simply write this out instead of WSOD? "Sorry, but the account "username" is not registered. Please contact the administrator to register your account or enable open registration"

**Comment by bradrydzewski** [comment]
> Just a white screen. 403 status code. No logging to syslog.

`/var/log/upstart/drone.log` is where the logs are output on Ubuntu

> Also found a comment on about drone from back in january stating https://www.digitalocean.com/community/tutorials/how-to-perform-continuous-integration-testing-with-drone-io-on-coreos-and-docker "This thing is useless. The github authentication is not working and there is no way to debug why is not working."

this tutorial is extremely outdated and no longer valid. Unfortunately I did not write it and don't own the content, so there isn't much I can do about it.

> Would it be too insecure to simply write this out instead of WSOD? "Sorry, but the account "username" is not registered. Please contact the administrator to register your account or enable open registration"

we're doing that here in this branch. It will be available in our upcoming release:
https://github.com/drone/drone/blob/bolt/server/login.go#L59
