### ISSUE TITLE
Running curl as a drone script command

### ISSUE THREAD

**Issue by ArildBelsvik** [drone/drone#997]
Hi

part of my .drone-yml
deploy:
  bash:
    script:
      - curl -X DELETE http://192.168.1.21:8080/v2/apps/organusfrontend
      - curl -X POST -H "Content-Type: application/json" http://192.168.1.21:8080/v2/apps -d@organus_frontend.json

The first curl line gives a response and runs ok
The second does not, no response and is not running.
I have tried to add escape character \' and \" with no luck

It seem like running a curl command within drone is failing if the command contains the characters ' or ". 

Any suggestion on how to run curl?

Arild

**Comment by bradrydzewski** [comment]
you'll need to quote the entire string in order for the Go yaml parser to correctly parse the string:

```
image: go
script:
  - "curl -X GET -H 'Content-Type: application/json' https://api.github.com/users/octocat"
```

feel free to ask any questions in our chat room at gitter.im/drone/drone
