### ISSUE TITLE
question: why are PRs built against their original predecessor

### ISSUE THREAD

**Issue by os12** [drone/drone#999]
Ditto. I see two conflicting angles here:
  1. a PR has the most chance of getting built against its predecessor (ie the original parent revision)
  1. the *Merge pull request* action would pull the commits and then merge them, so the consecutive build may produce a vastly different result (when other PRs are merged before)

The thing here is that (2) may fail even if (1) succeeded. It would be really nice to run CI on the "post merge" code, whatever it happens to be at the time. That, however, is a moving target as PRs get merged in parallel...

What is the most meaningful way forward?

**Comment by teodor-pripoae** [comment]
We solved this in our team by requiring PR to be rebased with latest master before being merged. This way you are sure that your PR additions are tested against master version.

**Comment by os12** [comment]
@teodor-pripoae, sure, both rebase and merge would work. Yet that is a manual step that people must remember (and there is no indication in the GitHub WebUI that any divergence has occurred).

**Comment by narqo** [comment]
:+1: for the issue. 

Currently drone always checkouts `refs/pull/%s/head` commit, while it looks more natural to check PR as a result of the merge, e.g. `refs/pull/%s/merge`

**Comment by bradrydzewski** [comment]
closing because drone 0.4 now uses `refs/pull/%s/merge` per the above suggestion with the ability to change the default configuration to use `refs/pull/%s/head`
